### ISSUE TITLE
Automatic island level updates

### ISSUE THREAD

**Issue by XHealthy** [BG-Software-LLC/SuperiorSkyblock2#1000]
### Minecraft's Version

1.17.1

### Plugin's Version

latest dev build #557 12/03/2022 19:59:53

### Describe the bug

The island level updates automatically without need to use the /is recalc command.
Setting in config: `calc-interval: 0`

### To Reproduce

Set `calc-interval` to 0 and just place some blocks.

### Additional Information

https://www.youtube.com/watch?v=h0OPQp2-Vn0&ab_channel=Fream_

**Comment by OmerBenGera** [comment]
This is not a bug. Island levels are calculated automatically. The calc-interval is a task that recalculates the blocks and it should be avoided as it may cause lag.
