### ISSUE TITLE
Teleported to sky when going to island

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1002]
### Minecraft's Version

[Tue, 15. Mar 2022 16:05:45 EST INFO] Current: git-Purpur-1586 (MC: 1.18.2)\*
[Tue, 15. Mar 2022 16:05:45 EST INFO] Previous: git-Paper-409 (MC: 1.17.1)

### Plugin's Version

[Tue, 15. Mar 2022 16:06:30 EST INFO] SuperiorSkyblock2 version 1.8.4.539
[Tue, 15. Mar 2022 16:06:30 EST INFO] Feature packed Skyblock core.
[Tue, 15. Mar 2022 16:06:30 EST INFO] Website: https://bg-software.com/
[Tue, 15. Mar 2022 16:06:30 EST INFO] Author: Ome\_R

### Describe the bug

When going to island, it teleports me to an insane y level and then finally teleporting me to my island

### To Reproduce

Join server
Do /is go

### Additional Information

![AA06C886-7C81-40F7-933A-6BE540DCB1EA](https://user-images.githubusercontent.com/65089425/158472698-5887b01d-acc8-41e6-b1e5-1acb9064bb1d.jpeg)

**Comment by DuneSciFye** [comment]
Here is a video as well: https://streamable.com/1oznig

**Comment by OmerBenGera** [comment]
Try it on a server with only SSB installed using the Java Edition

**Comment by DuneSciFye** [comment]
Oddly enough, this doesn't happen to java players on my main server, and this also doesn't happen to me (bedrock) on my testing server. The testing server has the exact same plugins as my main server.

**Comment by Skizzles** [comment]
I can not replicate using the above information, I would check what Y level the teleport is at.

I believe Geyser has a configuration option for Y level for Bedrock users.

**Comment by DuneSciFye** [comment]
Well this is safe to close
