### ISSUE TITLE
Island teleportations got disabled? Build #558

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#1004]
### Minecraft's Version

1.18.1

### Plugin's Version

Build #558

### Describe the bug

When you go out of the island and then come back. You get the "TELEPORTED_FAILED: " message. This is only happening with Build #558 and not the one before.

### To Reproduce

Have an island and try to go to it with /is go.

**Comment by Trinchezito** [comment]
Or how do we disable the safe-blocks thing? Or how to we all all blocks? like WATER, AIR? Most players use WATER to not die when falling and doing /is go

**Comment by Ynfuien** [comment]
Looks like (I think) safe teleportation checks wrong block whether it is safe. I had to add `AIR` to safe-blocks list

**Comment by OmerBenGera** [comment]
> Or how do we disable the safe-blocks thing? Or how to we all all blocks? like WATER, AIR? Most players use WATER to not die when falling and doing /is go

You can add WATER to the safe blocks list if you wish

**Comment by OmerBenGera** [comment]
> Looks like (I think) safe teleportation checks wrong block whether it is safe. I had to add `AIR` to safe-blocks list

This is a wrong thing to do and it will cause players to get teleported to the sky.

**Comment by Ynfuien** [comment]
I know, but otherwise players can't teleport to is home or warp

![image](https://user-images.githubusercontent.com/88110072/158973569-1ad972ee-5712-48f7-8dca-ddab0accf197.png)

**Comment by OmerBenGera** [comment]
> I know, but otherwise players can't teleport to is home or warp
> 
> ![image](https://user-images.githubusercontent.com/88110072/158973569-1ad972ee-5712-48f7-8dca-ddab0accf197.png)

Add the safe blocks you think should exist to the safe-blocks list.

**Comment by Trinchezito** [comment]
> I know, but otherwise players can't teleport to is home or warp
> 
> ![image](https://user-images.githubusercontent.com/88110072/158973569-1ad972ee-5712-48f7-8dca-ddab0accf197.png)

I had to add air. Some players don't change their home location so it stays one block above a block which is the AIR.

**Comment by Ynfuien** [comment]
> > I know, but otherwise players can't teleport to is home or warp
> > ![image](https://user-images.githubusercontent.com/88110072/158973569-1ad972ee-5712-48f7-8dca-ddab0accf197.png)
> 
> Add the safe blocks you think should exist to the safe-blocks list.

I use default list which has most of normal blocks

**Comment by OmerBenGera** [comment]
> > I know, but otherwise players can't teleport to is home or warp
> > ![image](https://user-images.githubusercontent.com/88110072/158973569-1ad972ee-5712-48f7-8dca-ddab0accf197.png)
> 
> I had to add air. Some players don't change their home location so it stays one block above a block which is the AIR.

Then the plugin will look for a new home location and find one above a block that is safe.

**Comment by OmerBenGera** [comment]
Mind showing me the island you try to teleport to?

**Comment by Ynfuien** [comment]
Default island
https://i.imgur.com/mn6YmFw.gif

**Comment by OmerBenGera** [comment]
> Default island https://i.imgur.com/mn6YmFw.gif

Are you able to replicate the issue on another server with only SSB installed?

**Comment by Ynfuien** [comment]
I'm able but now I'm going out. Issue occurs on 3 servers, Trinchezito, mine normal and mine for testing. So I assume that it's a problem in code

**Comment by OmerBenGera** [comment]
> I'm able but now I'm going out. Issue occurs on 3 servers, Trinchezito, mine normal and mine for testing. So I assume that it's a problem in code

What version of the game are you using?
The exact output of /version.

It works fine for me, therefore I can't fix it.

**Comment by Ynfuien** [comment]
Latest Purpur 1.18.2 - everything works fine xd
![image](https://user-images.githubusercontent.com/88110072/159084052-03965f29-5aed-4c2e-8e60-0fdf9e8e7d64.png)

So there is something ~~special~~ in 1.17.1

**Comment by Trinchezito** [comment]
> Latest Purpur 1.18.2 - everything works fine xd ![image](https://user-images.githubusercontent.com/88110072/159084052-03965f29-5aed-4c2e-8e60-0fdf9e8e7d64.png)
> 
> So there is something ~special~ in 1.17.1

I'm on 1.18.1 and added, water, air, lava to the list.... Everything is fine now. It would be great to add those blocks in a comment section in the config for new people.

**Comment by OmerBenGera** [comment]
I can confirm an issue in 1.17.1

**Comment by OmerBenGera** [comment]
Okay, check out latest dev build.
I want you to try it without the additional blocks you added to the safe blocks list.

One exception is to add WATER to the safe blocks, as I haven't added a check for it yet (planned once this issue is fixed)

**Comment by Ynfuien** [comment]
Works fine, but only for /is home, warps still are unsafe

**Comment by OmerBenGera** [comment]
@Ynfuien Check out latest dev build for warps

**Comment by Ynfuien** [comment]
> @Ynfuien Check out latest dev build for warps

Works wonderful

**Comment by OmerBenGera** [comment]
Perfect :)
We will wait for others to reply to make sure it's fixed for them as well.

**Comment by Trinchezito** [comment]
> Perfect :) We will wait for others to reply to make sure it's fixed for them as well.

It works fine for me on 1.18.1 and build 565.
Can you make the /is rename ignore color characters? Like the  EssentialsX nickname system?

**Comment by Davisiiiik** [comment]
Works for me too! 1.18.2, build 565

**Comment by OmerBenGera** [comment]
Perfect.
I am closing this for now :)

**Comment by Trinchezito** [comment]
New island creations are spawning above LEAVES, even if i remove the leaves from the safe block thing. What solution do you have here? 
This wasn't happening before. 
![image](https://user-images.githubusercontent.com/98068350/159140800-3f26c27c-32af-46ed-98ea-7a8605f18a6f.png)

**Comment by Trinchezito** [comment]
or how do i disable the safe block feature you added?
