### ISSUE TITLE
Generation nether island error for 1.18.2

### ISSUE THREAD

**Issue by ElezeDelas** [BG-Software-LLC/SuperiorSkyblock2#1013]
### Minecraft's Version

git-Paper-267 (MC: 1.18.2)

### Plugin's Version

SuperiorSkyblock2 version 1.9.0

### Describe the bug

The bug is it creation of island nether in version minecraft 1.18.2. The schematic´s not created correctly 

### To Reproduce

![imagen_2022-03-23_121701](https://user-images.githubusercontent.com/101078222/159733132-2a0e86a9-b805-42b4-995a-8d92606a3214.png)

### Additional Information

It seems to me that the plugin for version 1.18.2 is not yet developed, that's why it gives an error in the creation of the schematics. Pls update

**Comment by OmerBenGera** [comment]
Delete the schematics folder and let the schematics regenerate.
I dont know why but the schematics in your folder were not renamed correctly when they were saved.

If it happens again, think of a reason why would the plugin fail to rename the schematic files (you can see that they have 1_13 in their names)

Btw, this is not related to 1.18.2 and the plugin works fine on that version, so you do not have to be worried about that.

**Comment by OnLyMaGiK** [comment]
![image](https://user-images.githubusercontent.com/72762434/159990221-982bdc48-f5e2-4d59-894b-6361d40647be.png)

Same problem, schematic removed

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/72762434/159990221-982bdc48-f5e2-4d59-894b-6361d40647be.png)
> 
> Same problem, schematic removed

Looks fine for me, what am I missing?

**Comment by ElezeDelas** [comment]
in version 1.17.1 the same error

**Comment by OmerBenGera** [comment]
> in version 1.17.1 the same error

Everything is fine in the screenshot you sent me.
The warnings about different mc versions can be ignored, and the warning about invalid biomes - fiz those biomes.

I am closing this for now
