### ISSUE TITLE
Missions Resetting upon restarts

### ISSUE THREAD

**Issue by BladeVapes** [BG-Software-LLC/SuperiorSkyblock2#1015]
### Minecraft's Version

1.18.2

### Plugin's Version

 1.9.0-b567

### Describe the bug

Whenever the server restarts, most missions or challenges that are part way through reset back to 0. Finished ones do not reset.

### To Reproduce

Doesn't seem like like the missions section is saving when the server does the save-all command. We currently have auto-restarts running every 24 hours.

**Comment by OmerBenGera** [comment]
Missions are saved when server is stopped and every 5 minutes. Is that not the case for you?

**Comment by BladeVapes** [comment]
They don't seem to be saving every 5 minutes, from what I have seen it's about once a day.

**Comment by OmerBenGera** [comment]
> They don't seem to be saving every 5 minutes, from what I have seen it's about once a day.

Are there any errors from SSB?

**Comment by BladeVapes** [comment]
nope, nothing.  This is why we are so confused.

**Comment by OmerBenGera** [comment]
Also, are you talking about missions progress resetting or the missions status being reset (completed, not completed, etc)?

**Comment by BladeVapes** [comment]
So for example, I have done this since I have been online. https://prnt.sc/IfrKhwDhIdgD

If the server restarts it goes back to 0%

**Comment by BladeVapes** [comment]
The ones that are finished stay finished.

**Comment by OmerBenGera** [comment]
@BladeVapes I understand.
Check out latest dev build, let me know if it works for you.

**Comment by BladeVapes** [comment]
No luck with it sadly. I did get a new error however that I was not getting before 
https://pastebin.com/NMNtCFeH

**Comment by OmerBenGera** [comment]
> No luck with it sadly. I did get a new error however that I was not getting before. https://pastebin.com/NMNtCFeH

The error is not related to the issue, do not mix issues next time.
About the original issue, it works fine for me.
When you stop the server, is there any data saved to the `_data.yml` file?

**Comment by BladeVapes** [comment]
Sorry, it took so long to reply, We did figure out the issue. If the server restarts, we lose all progress on the current missions (not finished) if the server stops however the data is saved and does NOT reset. We have now changed the restart commands to stop and start commands. It all seems to be working now. I am sorry for taking your time and making mistakes with the error.

**Comment by OmerBenGera** [comment]
> Sorry, it took so long to reply, We did figure out the issue. If the server restarts, we lose all progress on the current missions (not finished) if the server stops however the data is saved and does NOT reset. We have now changed the restart commands to stop and start commands. It all seems to be working now. I am sorry for taking your time and making mistakes with the error.

I don't understand what was the issue exactly...
Mind explaining more deeply and how you fixed it, so others can do the same in the future?

**Comment by BladeVapes** [comment]
Ok so if we restarted the server using /restart or a plugin that did /restart the _data.yml file did not update nor save. 

With the server stopping instead it saves it just fine.

**Comment by OmerBenGera** [comment]
Weird.
Do you have logs of a session where you used /restart?
If so, mind sending it here?

**Comment by BladeVapes** [comment]
No, we used an auto-restart plugin, Ultimate Auto Restart. When we disabled and removed that plugin we did lose the copies of logs from it. If I had them I would gladly send them to save anyone else from having this issue.

**Comment by OmerBenGera** [comment]
I understand.
For now, I am closing the issue :)

**Comment by gunhippy** [comment]
We've experienced this very same issue. Superior Skyblock ver 1.9.0. We're using node craft that their standard automated restart scheduled task

**Comment by OmerBenGera** [comment]
> We've experienced this very same issue. Superior Skyblock ver 1.9.0. We're using node craft that their standard automated restart scheduled task

Update to latest dev build.
If the issue still occurs, open a new issue please :)
