### ISSUE TITLE
Nulls in placeholders (levels, ratings)

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1017]
### Minecraft's Version

1.16.5

### Plugin's Version

b570

### Describe the bug

https://imgur.com/kWEBK6d

### To Reproduce

Update from 530 to 570 build

**Comment by exzolink** [comment]
> ### Minecraft's Version
> 
> 1.16.5
> ### Plugin's Version
> 
> b570
> ### Describe the bug
> 
> https://imgur.com/kWEBK6d
> ### To Reproduce
> 
Updated from 530 to 570
> 
> ### Additional Information
> 
> _No response_

**Comment by OmerBenGera** [comment]
What placeholders are you using in your menus?

**Comment by exzolink** [comment]
%superior_island_level_format%
%superior_island_bank_format%

**Comment by exzolink** [comment]
Something wrong with formatting

**Comment by OmerBenGera** [comment]
Seems to work fine for me on latest dev build

**Comment by OmerBenGera** [comment]
What numbers formatting are you using?

**Comment by exzolink** [comment]
They're not hardcoded?

**Comment by exzolink** [comment]
Try to install 530 then update to 570

**Comment by OmerBenGera** [comment]
> They're not hardcoded?

No, its configurable :P

**Comment by OmerBenGera** [comment]
Does `/papi parse me %superior_island_level_format%` show also the null?

**Comment by exzolink** [comment]
> > They're not hardcoded?
> 
> No, its configurable :P

I dont see in config

**Comment by exzolink** [comment]
> Does `/papi parse me %superior_island_level_format%` show also the null?

Yes

**Comment by OmerBenGera** [comment]
> > Does `/papi parse me %superior_island_level_format%` show also the null?
> 
> Yes

What numbers formatting are you using?

**Comment by exzolink** [comment]
> > > Does `/papi parse me %superior_island_level_format%` show also the null?
> > 
> > 
> > Yes
> 
> What numbers formatting are you using?

I cant find options in config

**Comment by OmerBenGera** [comment]
> > > > Does `/papi parse me %superior_island_level_format%` show also the null?
> > > 
> > > 
> > > Yes
> > 
> > 
> > What numbers formatting are you using?
> 
> I cant find options in config

```yaml
# Set the number formatting to be used.
# You can see a list of formats under the "Language Tag" column here:
# https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html
number-format: "en-US"
```

**Comment by exzolink** [comment]
Default, en-US, i didnt change this option

**Comment by OmerBenGera** [comment]
> Default, en-US, i didnt change this option

Gotcha.
What version of PAPI are you using?

**Comment by exzolink** [comment]
2.10.10

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's fixed.

**Comment by exzolink** [comment]
Updated papi and ssb, now works fine
