### ISSUE TITLE
Ender Dragon 

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#1018]
### Minecraft's Version

1.18.1

### Plugin's Version

latest

### Describe the bug

I know you fixed the ender dragon error in the console. Thank you. 

I tough that would fix the ender dragon from flying away right after it spawns. It doesn't fight, it just escapes out of the border even after i maxed out my border size. We also tested it with end crystal and the dragon still escapes, ignoring the player and border.

### To Reproduce

spawn ender dragon in the skyblock end world.

**Comment by OmerBenGera** [comment]
The ender dragon fight seems to be bugged in 1.18 and 1.17.
I will hopefully find time to re-write it and ensure it doesn't happen anymore.
For now, I recommend disabling it.

**Comment by OmerBenGera** [comment]
Just wanted to update that I am almost done with it.
Still need to do more testings, but overall it seems to be working now :)
Hopefully next week the patch will be applied to the official builds.

**Comment by Trinchezito** [comment]
> Just wanted to update that I am almost done with it. Still need to do more testings, but overall it seems to be working now :) Hopefully next week the patch will be applied to the official builds.

Thank you! We appreciate your work!

**Comment by OmerBenGera** [comment]
Hey, what is your discord?
I'd like to give you a jar to test :)

**Comment by Trinchezito** [comment]
> 

Trinchezito#9581

**Comment by OmerBenGera** [comment]
> > 
> 
> Trinchezito#9581

It doesn't seem like you're inside our discord server. Join at https://bg-software.com/discord/

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
