### ISSUE TITLE
Placeholder formated null

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#1019]
### Minecraft's Version

1.18

### Plugin's Version

latest

### Describe the bug

This wasn't happening before. Now the placeholder 
superior_island_total_level_format
throws me null like so:
![image](https://user-images.githubusercontent.com/98068350/160218378-7074b80a-9cbe-44e8-96ad-0879561068e2.png)

### To Reproduce

use the superior_island_total_level_format placeholder

**Comment by OmerBenGera** [comment]
Duplicate of #1017
