### ISSUE TITLE
Problem schema and bioms

### ISSUE THREAD

**Issue by mateusz76721** [BG-Software-LLC/SuperiorSkyblock2#1020]
### Minecraft's Version

spigot-1.18-R0.1-SNAPSHOT.jar

### Plugin's Version

SuperiorSkyblock2-1.9.0-b574

### Describe the bug

I dont see two biomes in  menu -> island-biome
![image](https://user-images.githubusercontent.com/11067194/160256538-40e3d9d2-3636-4b79-9448-0a017c6cab69.png)
![image](https://user-images.githubusercontent.com/11067194/160256416-d2d12433-c760-4af1-a98c-5c62df0bd4b0.png)

problem witch schema if I delete the schema I can't turn on the server

### To Reproduce

if I delete the schema I can't turn on the server

**Comment by OmerBenGera** [comment]
The biomes "NETHER" and "WOODEN_HILLS" are not valid for your minecraft version - correct them.
