### ISSUE TITLE
Island Data rollback

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#1023]
### Minecraft's Version

1.18.1

### Plugin's Version

1.9.0.574

### Describe the bug

Sometimes when my player disconnect and reconnect (the night I have an auto restart at 5am) he lost her previous day island and he get a rollback of the blocks.

I use wildstacker and my players keep their block stacked.

### To Reproduce

I don't exactyle how you can reproduce that

### Additional Information

I use pufferfish 1.18.1 build 47
MySQL 5.7
Java 17
Flags: `java -Xms128M -Xmx11093M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar`
Velocity 3.x + tcpshield

Database config:
  useSSL: false
  allowPublicKeyRetrieval: true
  waitTimeout: 600000
  maxLifetime: 1800000

I use SuperiorSkyblock2-NashornEngine-b6

**Comment by OmerBenGera** [comment]
Does the rollback that you mentioned only affect block counts?

**Comment by Teyir** [comment]
No, all the blocks (block place on the island)

**Comment by OmerBenGera** [comment]
> No, all the blocks (block place on the island)

The blocks in the world?

**Comment by Teyir** [comment]
Yes

**Comment by OmerBenGera** [comment]
> Yes

This is not related to the plugin then, as it doesn't handle anything related to the world.
The plugin only creates the world vanilla-way, and from there it lets Spigot to handle it.

How do you restart your server?

**Comment by Teyir** [comment]
But this is only the superiorskyblock block counts, others blocks are not rollback.

This is an automatic task from my server host

**Comment by OmerBenGera** [comment]
> But this is only the superiorskyblock block counts, others blocks are not rollback.
> 
> This is an automatic task from my server host

I don't know what you mean by "only the superiorskyblock block counts"
I asked you if the blocks in the world reset, you said yes - how is this related to SSB?

**Comment by Teyir** [comment]
This is only on my ssb islands and this is only the blocks with a value / worth

**Comment by OmerBenGera** [comment]
> This is only on my ssb islands and this is only the blocks with a value / worth

Only blocks with values are just gone from the world? It makes no sense.
Try replicating it on localhost with only SSB installed.

**Comment by Teyir** [comment]
Yes I think this bugg have no sense, I search all the possibilities...

**Comment by OmerBenGera** [comment]
> Yes I think this bugg have no sense, I search all the possibilities...

Try replicating the bug on a localhost server with only SSB installed.

**Comment by Teyir** [comment]
Hello,

I come with some new informations.

A new island got a blocks rollback

I have 540 "hopper" on my database, and when I use worldedit or litematica I don't have the same result (738)

DB:
![image](https://user-images.githubusercontent.com/60007549/162682170-b84108dd-28bb-41ef-8e08-be10c037d66b.png)

FAWE count:
![image](https://user-images.githubusercontent.com/60007549/162682200-023b2a41-8a36-461a-b8ba-7601593a8d4c.png)

LITEMATICA:
![image](https://user-images.githubusercontent.com/60007549/162682384-fdaef01a-da9a-4fd7-b9e2-18ae3ec22a51.png)

Player_Count data:
https://www.toptal.com/developers/hastebin/esuwawoduk.json

@OmerBenGera

**Comment by OmerBenGera** [comment]
> Hello,
> 
> I come with some new informations.
> 
> A new island got a blocks rollback
> 
> I have 540 "hopper" on my database, and when I use worldedit or litematica I don't have the same result (738)
> 
> DB: ![image](https://user-images.githubusercontent.com/60007549/162682170-b84108dd-28bb-41ef-8e08-be10c037d66b.png)
> 
> FAWE count: ![image](https://user-images.githubusercontent.com/60007549/162682200-023b2a41-8a36-461a-b8ba-7601593a8d4c.png)
> 
> LITEMATICA: ![image](https://user-images.githubusercontent.com/60007549/162682384-fdaef01a-da9a-4fd7-b9e2-18ae3ec22a51.png)
> 
> Player_Count data: https://www.toptal.com/developers/hastebin/esuwawoduk.json
> 
> @OmerBenGera

Use /is level (or /is admin level) to recount the blocks.
Also WE doesnt care about different data values which SSB takes care of. Also this doesnt seem to be related to the rollback that is mentioned in the issue.

**Comment by OmerBenGera** [comment]
And again, if blocks in the world are rollbacked (not block counts in /is blocks), then it is not related to the plugin

**Comment by Teyir** [comment]
I already do this...

**Comment by OmerBenGera** [comment]
I still don't get which blocks are rollbacked.
Blocks from the world or block counts in `/is blocks`?
