### ISSUE TITLE
Mission Issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1029]
### Minecraft's Version

1.18.2

### Plugin's Version

b579

### Describe the bug

Hello, IDK how to reproduce the bug but i've openned my new server version today and this error drop my server tps to 0 : https://pics.revolis.fr/2022/04/03/16-11_JAS3.png it's related to missions. Thx

### To Reproduce

Break block (i don't know how) and look the console it's spammed.

**Comment by nivcoo** [comment]
I think it's fixed after removing the blockmission jar file, idk why but the jar isn't the same after i deleted it

**Comment by nivcoo** [comment]
I haven't the issue with b576

**Comment by nivcoo** [comment]
I've allways the issue with b576 and new BlockMissions jar

**Comment by nivcoo** [comment]
The issue is due to this commit https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/commit/72fc0d7fdbac44c3b37e2eca71e82fa9fe06d590

**Comment by OmerBenGera** [comment]
Upload the mission related to blocks that you have and upload it to pastebin.

**Comment by nivcoo** [comment]
Idk exactly what is the mission it's not said in error

**Comment by nivcoo** [comment]
I've the issue when my player break block in another world (/spawn for exemple)

**Comment by nivcoo** [comment]
Maybe these missions : https://www.toptal.com/developers/hastebin/juvewiqiru.sql https://www.toptal.com/developers/hastebin/facecenihu.sql https://www.toptal.com/developers/hastebin/idudajufip.sql

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
