### ISSUE TITLE
Nether Island Issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1030]
### Minecraft's Version

1.18.2

### Plugin's Version

b579

### Describe the bug

Hello, i've disabled the nether schematic but when i go to nether with portal i've this message https://pics.revolis.fr/2022/04/03/17-34_dsjC.png

### To Reproduce

Disable Nether schem and go to nether with portal

**Comment by OmerBenGera** [comment]
Thats because you deleted the nether schematic.
If you want to disable the nether completely, do so in the config file of SSB, under the worlds section

**Comment by nivcoo** [comment]
Yes like i said i've already disabled this feature : https://pics.revolis.fr/2022/04/03/19-24_WKv1.png

**Comment by OmerBenGera** [comment]
> Yes like i said i've already disabled this feature : https://pics.revolis.fr/2022/04/03/19-24_WKv1.png

Ah, I see.
You said you disabled the nether schematic, I didnt understand you correctly

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
