### ISSUE TITLE
Spawner Placement issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1032]
### Minecraft's Version

1.18.2

### Plugin's Version

b579

### Describe the bug

Hello, when i place spawner i've this issue in console : https://www.toptal.com/developers/hastebin/aduruceboy.properties

### To Reproduce

Place spawner with wildtacker and ss2

**Comment by OmerBenGera** [comment]
Downgrade SAB for now.

**Comment by nivcoo** [comment]
Downgrade to which version ?

**Comment by xIsm4** [comment]
> Downgrade to which version ?

To the lastest before the bug.

**Comment by OmerBenGera** [comment]
Build 577 should be fine

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works for you

**Comment by OmerBenGera** [comment]
Seems to be fixed, closing this
If it still occurs, lmk
