### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1035]
### Minecraft's Version

Current: git-Purpur-1586 (MC: 1.18.2)*

### Plugin's Version

SuperiorSkyblock2 version 1.8.4.539 Dev build

### Describe the bug

I see this error in console: https://pastebin.com/NubKyibN

### To Reproduce

Not sure

**Comment by OmerBenGera** [comment]
Update to latest dev build, the issue was already fixed
