### ISSUE TITLE
Self Stacker System

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1036]
### Minecraft's Version

1.18.2

### Plugin's Version

b576

### Describe the bug

Hello, in 1.12.2 i used superiorskyblock stacker blocks, now in 1.18.2 the wildstacker system override the stacker system (Barrel), but i don't want to use that (I prefer block than cauldron). Can i do that or you need to edit something ? thx

### To Reproduce

Use SS2 and wildstacker and try to use ss2's stacker system in 1.18.2

**Comment by OmerBenGera** [comment]
Disable WS barrels stacking...

**Comment by nivcoo** [comment]
If i report that it's beacuse i've tried https://pics.revolis.fr/2022/04/05/16-16_OwSI.png https://pics.revolis.fr/2022/04/05/16-16_QXGd.png but with that despite of server restart i can't do /is toggle blocks and activate the stacker

**Comment by nivcoo** [comment]
The plugin said : 
[SuperiorSkyblock2] Using WildStacker as a spawners provider.
[SuperiorSkyblock2] Using WildStacker as a stacked-blocks provider.

**Comment by nivcoo** [comment]
Ok i will try something so, thx you
