### ISSUE TITLE
Bank interest dont charge at all

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1037]
### Minecraft's Version

1.16.5

### Plugin's Version

b579

### Describe the bug

Bank interest dont charge at all, even if balance below limit

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by exzolink** [comment]
It works, but now players cant deposit money due to limit (even if limit not reached)

**Comment by OmerBenGera** [comment]
@exzolink Check latest dev build, should be fixed.

**Comment by exzolink** [comment]
Everything works, thank you
