### ISSUE TITLE
Entity limit is heavy

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1040]
### Minecraft's Version

1.17.1 pufferfish (the spark were done on 1.16)

### Plugin's Version

b577

### Describe the bug

The new entity limit is still a bit heavy, it can take up to 5% in a spark : 
https://spark.lucko.me/7yHBQH5jTS
![image](https://user-images.githubusercontent.com/31826333/162429650-56a709e4-fa66-46ed-a5a2-575bdc3550e7.png)

I got 50~80 players on this spark, with 600 spawners

Also, you'll tell me "it's only loading chunks, so I don't know why it's heavy".
But why is it loading that much chunks, no other solution ? And why is it on main thread : 
![image](https://user-images.githubusercontent.com/31826333/162430107-976d530d-2a5c-477a-ad84-93793e10becd.png)

### To Reproduce

turn on entity limit and ask player to spawn mobs and kill them.

### Additional Information

(There is also an issue where entity limit something bug and do not count correctly mobs, but that's a different issue)

**Comment by OmerBenGera** [comment]
What's the difference between this and #1039 ?

**Comment by WarnDa** [comment]
> What's the difference between this and #1039 ?

This also happened on 1.16, before #1039. Entity limit is always taking 3-5% of spark

**Comment by OmerBenGera** [comment]
> > What's the difference between this and #1039 ?
> 
> This also happened on 1.16, before #1039. Entity limit is always taking 3-5% of spark

It seems like lag from loading chunks, same issue as #1039 (or at least it's another reason for that issue)

**Comment by OmerBenGera** [comment]
I am closing this because I really think by fixing #1039 this will be solved as well.
However, if that's not the case and it will still occur, lmk
