### ISSUE TITLE
Stacker hologram

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1041]
### Minecraft's Version

1.18.2

### Plugin's Version

b586

### Describe the bug

Hello, The armor stand of stacker hologram are counted into island armor stand limit https://pics.revolis.fr/2022/04/09/15-47_KKna.png https://pics.revolis.fr/2022/04/09/15-50_plAF.png so the holograms doesn't appear, can you exclude these armor stand to limit ?

### To Reproduce

Set armor stand limit to 0 and place stacker with ss2.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
