### ISSUE TITLE
Entity limit issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1042]
### Minecraft's Version

1.17 pufferfish

### Plugin's Version

b586

### Describe the bug

Player can get more mobs than the limit, sometimes it doesn't could well mobs (it counts 0 stacks), so player can spawn new mobs, and after 5mn it will count again mobs (the old one + the new one) and player will get 2x more mobs than the limit
 

### To Reproduce

I still don't know exactly how to reproduce.
Sometimes when player come back to his island it says player has 0 stack instead of the right amount

**Comment by WarnDa** [comment]
There is more than 50 stacks, but it counts currenty 20 stacks (the green number)
"quantité actuelle sur l'île" means "current quantity" 
![image](https://user-images.githubusercontent.com/31826333/162955671-4ee2f4a0-1157-418f-b738-06c18ffe44aa.png)

**Comment by WarnDa** [comment]
There is more than 50 stacks, but it counts currenty 20 stacks (the green number)
"quantité actuelle sur l'île" means "current quantity"
![image](https://user-images.githubusercontent.com/31826333/162957887-67c2482b-04cf-4a88-9483-04cf96276132.png)

**Comment by OmerBenGera** [comment]
> There is more than 30 stacks, but it counts currenty 20 stacks (the green number) "quantité actuelle sur l'île" means "current quantity" ![image](https://user-images.githubusercontent.com/31826333/162957887-67c2482b-04cf-4a88-9483-04cf96276132.png)

Try replicating the issue on localhost where you only have SSB & stacker plugin installed

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WarnDa** [comment]
The update : https://hub.bg-software.com/job/SuperiorSkyblock2/597/changes
fixes the placeholder issue, so fine on this, but you can still get more mobs than the maximum stack

**Comment by WarnDa** [comment]
Edit :
still the issue and I don't know how to reproduce it...
So I'll close it and I'll see with my dev to check the code to find the issue

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WarnDa** [comment]
> Sometimes when player come back to his island it says player has 0 stack instead of the right amount

I'm still on this, it wouldn't possible to add debug on this ? As it happens rarely and not on all players it's nearly impossible to find how to reproduce it

**Comment by OmerBenGera** [comment]
> > Sometimes when player come back to his island it says player has 0 stack instead of the right amount
> 
> I'm still on this, it wouldn't possible to add debug on this ? As it happens rarely and not on all players it's nearly impossible to find how to reproduce it.
> 
> It's maybe when it needs to calculate many islands so it forgot some, if you have too much mobs so it skips some mobs, or if the plugin doesn't have time to calculate mobs, so it counts 0

When the island is loaded after it was unloaded (and there's no cooldown), all mobs will be recalculated - no mob will be skipped.

**Comment by WarnDa** [comment]
Yes but sometimes rescan fail, that’s why some debug when a mob is scanned
With the mob type and the count would be cool

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WarnDa** [comment]
Hello,

As you didn't add any debug or things to fnd a way to reproduce it, can't do nothing
So we can close it and when I'll get time I'll try to add debug with a dev

**Comment by OmerBenGera** [comment]
> Hello,
> 
> As you didn't add any debug or things to fnd a way to reproduce it, can't do nothing So we can close it and when I'll get time I'll try to add debug with a dev

Hey, I changed the debug system. Now you can use `/is admin debug` + tab to get a list of available actions to debug - including entity_spawn and entity_despawn. Try using this feature, let me know if it helps with debugging the issue.

**Comment by WarnDa** [comment]
Okay thanks

I can't test until some weeks once I'll update my server, and it might be fixed with the other fixes you did.
So if you want to close it and if the bug appear again I would re-up the ticket

**Comment by WarnDa** [comment]
> 

I still got the issue (currently 130 players on) and enabled the debug.

here are some logs :
https://pastebin.com/mDNpefvT

But I still don't know how they reproduce this issue, but it happens a lot :(

**Comment by OmerBenGera** [comment]
> > 
> 
> I still got the issue (currently 130 players on) and enabled the debug. Some players get their randomly on 0, so they can bypass the limit
> 
> here are some logs : https://pastebin.com/mDNpefvT
> 
> But I still don't know how they reproduce this issue, but it happens a lot :(

Hey, the pastebin does not exist anymore.
Mind re-uploading it?

**Comment by WarnDa** [comment]
> > > 
> > 
> > 
> > I still got the issue (currently 130 players on) and enabled the debug. Some players get their randomly on 0, so they can bypass the limit
> > here are some logs : https://pastebin.com/mDNpefvT
> > But I still don't know how they reproduce this issue, but it happens a lot :(
> 
> Hey, the pastebin does not exist anymore. Mind re-uploading it?

https://hastebin.com/zewaliketa.less

**Comment by OmerBenGera** [comment]
> > > > 
> > > 
> > > 
> > > I still got the issue (currently 130 players on) and enabled the debug. Some players get their randomly on 0, so they can bypass the limit
> > > here are some logs : https://pastebin.com/mDNpefvT
> > > But I still don't know how they reproduce this issue, but it happens a lot :(
> > 
> > 
> > Hey, the pastebin does not exist anymore. Mind re-uploading it?
> 
> https://hastebin.com/zewaliketa.less

Well it doesn't say much, if you have more than one island you debug, it will be a mess.

**Comment by WarnDa** [comment]
> entity_spawn

There is no command to debug only an island ?

**Comment by OmerBenGera** [comment]
> > entity_spawn
> 
> There is no command to debug only an island ?

No.
Again, the plugin recalculates the entities when islands are loaded again, so even if they can bypass the limit, once they go away and come back, it will recalculate entities again.

**Comment by WarnDa** [comment]
> > > entity_spawn
> > 
> > 
> > There is no command to debug only an island ?
> 
> No. Again, the plugin recalculates the entities when islands are loaded again, so even if they can bypass the limit, once they go away and come back, it will recalculate entities again.

Some islands get 41 chicken instead of 10
When you are more than one on the island it may recalculate wrong



OHHH I didn't try to do things like /home or /back

**Comment by OmerBenGera** [comment]
Find out how they spawn chickens and try spawning them yourself (also, check the current entity counts using placeholders)
Also, use the debug command to see if the new mobs are tracked or not.

**Comment by WarnDa** [comment]
https://youtu.be/-dTpYgH1jl4
https://pastebin.com/pegKf9uB

I tried to spawn mobs with egg it doesn't count them (all my limits are on)
Same on my own server

**Comment by OmerBenGera** [comment]
They are stacking to this cow... Why would they count as new mobs?

**Comment by OmerBenGera** [comment]
They are stacking into that cow, why would it increase the entity count?
Also, the log you sent is for untracking entities, not for tracking them.

**Comment by WarnDa** [comment]
I should get 1 stacked cow it counts 0
but I'll redo a video after lunch to explain

**Comment by OmerBenGera** [comment]
> I should get 1 stacked cow it counts 0 but I'll redo a video after lunch to explain

Enable debug for entity spawn as well as despawn. Then, leave the chunk, wait a few moments and come back.
Check if you see the despawn when you leave the chunk and the spawn when you come back

**Comment by WarnDa** [comment]
It doesn't track entity spawning currently, idk why :
https://pastebin.com/A7p5KCiC
https://youtu.be/suD4AMpG2do
![image](https://user-images.githubusercontent.com/31826333/205371481-77e1cec8-a8c0-4178-b403-7d09b96dd90b.png)

**Comment by WarnDa** [comment]
I disconnected and reconnected, there was one stack of cow, I spawned more mobs that stacked into the current cow, it downs the stack to 0 : https://youtu.be/mQh8Q7DDOZI

**Comment by WarnDa** [comment]
When I bread mobs it doesn't detect the new stack : https://youtu.be/xcWDj3WJCP4

Also there is a longer video with the issue from scratch : https://youtu.be/7jjY_jrW5ZY
Here you can see all the issues, mobs are not counted until server restart, and when a new mob spawn and stack to the other, it decrease the mob count.
Recorded with default superiorskyblock config, paper 1.19.2

**Comment by WarnDa** [comment]
On latest version the issue is semi fixed
On some case when I unload and reload the chunk, each mobs is counted twice, so it kills your limit.
I searched 2hr to reproduce it, and I don't get an exact step, but what I did : 
- go on your island
- spawn 5 cows
- restart the server (while you are on your island)
- connect again
- it will shows 10 cows with the placeholder
- if you kill the 5 cows, the placeholder still return "5 cows" (as 10-5 = 5)
- If I restart again, it will returns 0 cow

I did it only with wildstacker (stacked cows) and superior on paper, no other plugin

**Comment by OmerBenGera** [comment]
> On latest version the issue is semi fixed On some case when I unload and reload the chunk, each mobs is counted twice, so it kills your limit. I searched 2hr to reproduce it, and I don't get an exact step, but what I did :
> 
> * go on your island
> * spawn 5 cows
> * restart the server (while you are on your island)
> * connect again
> * it will shows 10 cows with the placeholder
> * if you kill the 5 cows, the placeholder still return "5 cows" (as 10-5 = 5)
> * If I restart again, it will returns 0 cow
> 
> And it’s always TWICE, so there is a loop or something that fail and check every mobs more than 1 time. I did it only with wildstacker (stacked cows) and superior on paper, no other plugin
> 
> .
> 
> .
> 
> . Here you can see : https://pastebin.com/fTuLYydF **when I'm not on his island, the placeholder still returns 19 COW**, it should return 0 as I'm not on his island It returns twice the amount of each mobs, the "38" is when I do : papi parse galagan %superior_island_entity_count_cow% so it counts 19 mobs in logs, but 38 with the placeholders
> 
> Only thing that we did is restarting the server, and player upgraded his mob limit yesterday

I can't replicate the issue, I had 5 cows in my island, then restarted. after the restart, there were still 5 cows counted.
Also, not sure how WildStacker has to do with it, as SSB don't count stacked entities as multiple entities.

**Comment by WarnDa** [comment]
I can’t find how to replicate it, but it didn’t untrack the amount of mobs (19) but it tracks it when you load the chunk so it counts twice.
Will need to find how to replicate it.. but I’m  sure of the issue :/
Maybe sometimes the unload task do not works well, like on server killing, will do more tests once I can

**Comment by OmerBenGera** [comment]
> I can’t find how to replicate it, but it didn’t untrack the amount of mobs (19) but it tracks it when you load the chunk so it counts twice. Will need to find how to replicate it.. but I’m sure of the issue :/ Maybe sometimes the unload task do not works well, like on server killing, will do more tests once I can

You said you restarted the server. The plugin doesn't save this type of information into DB, so what you say here is incorrect.

**Comment by OmerBenGera** [comment]
It seems like when they move between chunks, they are calculated correctly.
However, if you unload and load the chunks quick enough, there's a miscalculation of the mobs.
Is this correct?

**Comment by WarnDa** [comment]
> It seems like when they move between chunks, they are calculated correctly. However, if you unload and load the chunks quick enough, there's a miscalculation of the mobs. Is this correct?

Yes, and it's maybe the same issue I had where it counts all mobs twice, but it's hard to find a way to reproduce at 100%, but now you got the video, so you see the issue is real.

**Comment by WarnDa** [comment]
Anything I could help you with ? running 150 players and mobs are taking 45% because I can't limit them properly :/

**Comment by WarnDa** [comment]
What we've seen with the dev is that sometimes the mob count event is fired twice instead of once, that's why it counts more mobs on some chunks load, but I don't know in what conditions it triggers the event twice. (and the debug only shows the entity load even once...)

**Comment by WarnDa** [comment]
We have fully reproduced the issue and found the fix : 
- create an island
- enable the limit
- spawn 1 mob on your main chunk (the chunk where you spawn doing /is)
- spawn mobs on other chunk than the main chunk
- your limit is good
- wait 5mn
- go to another world
- do /is
- the mobs that aren't in the main chunk of the island will be counted twice

Because your method count differently the "main chunk' and the others, but it counts once all the loaded chunks, and twice the other chunk except the main one.

**We have tested a fix that work :**
https://user-images.githubusercontent.com/31826333/230767278-ecf19782-d115-4011-9f81-e32c76ca4341.png

**Comment by WarnDa** [comment]
We have fully reproduced the issue and found the fix : 
- create an island
- enable the limit
- spawn 1 mob on your main chunk (the chunk where you spawn doing /is)
- spawn mobs on other chunk than the main chunk
- your limit is good
- wait at least 5mn
- go to another world
- do /is
- the mobs that aren't in the main chunk of the island will be counted twice
![image](https://user-images.githubusercontent.com/31826333/230767383-9b360286-6515-4b0d-8116-799dbfe164f6.png)
Here the 4 cows are in the main chunk of the island, so not counted twice, but the single cow on the other chunk it counted twice, so it counts 6 cows instead of 5

Because your method count differently the "main chunk' and the others, but it counts once all the loaded chunks, and twice the other chunk except the main one.

**We have tested a fix that work :**
https://user-images.githubusercontent.com/31826333/230767278-ecf19782-d115-4011-9f81-e32c76ca4341.png

_We also changed some other part of the code but they might doing nothing, only this should fix the issue_

**Comment by WarnDa** [comment]
We have fully reproduced the issue and found the fix : 
- create an island
- enable the limit
- spawn 1 mob on your main chunk (the chunk where you spawn doing /is)
- spawn mobs on other chunk than the main chunk
- your limit is good
- wait at least 5mn
- go to another world
- do /is
- the mobs that aren't in the main chunk of the island will be counted twice
![image](https://user-images.githubusercontent.com/31826333/230767383-9b360286-6515-4b0d-8116-799dbfe164f6.png)
Here the 4 cows are in the main chunk of the island, so not counted twice, but the single cow on the other chunk it counted twice, so it counts 6 cows instead of 5

Because your method count differently the "main chunk' and the others, but it counts once all the loaded chunks, and twice the other chunk except the main one.

**We have tested a fix that work :**
https://user-images.githubusercontent.com/31826333/230767278-ecf19782-d115-4011-9f81-e32c76ca4341.png
![230767278-ecf19782-d115-4011-9f81-e32c76ca4341](https://user-images.githubusercontent.com/31826333/230767421-341b7a08-e322-4e96-9940-127ce77fd48e.png)


_We also changed some other part of the code but they might doing nothing, only this should fix the issue_

**Comment by WarnDa** [comment]
> We have fully reproduced the issue and found the fix :
> 
> * create an island
> * enable the limit
> * spawn 1 mob on your main chunk (the chunk where you spawn doing /is)
> * spawn mobs on other chunk than the main chunk
> * your limit is good
> * wait at least 5mn
> * go to another world
> * do /is
> * the mobs that aren't in the main chunk of the island will be counted twice
>   ![image](https://user-images.githubusercontent.com/31826333/230767383-9b360286-6515-4b0d-8116-799dbfe164f6.png)
>   Here the 4 cows are in the main chunk of the island, so not counted twice, but the single cow on the other chunk it counted twice, so it counts 6 cows instead of 5
> 
> Because your method count differently the "main chunk' and the others, but it counts once all the loaded chunks, and twice the other chunk except the main one.
> 
> **We have tested a fix that work :** https://user-images.githubusercontent.com/31826333/230767278-ecf19782-d115-4011-9f81-e32c76ca4341.png ![230767278-ecf19782-d115-4011-9f81-e32c76ca4341](https://user-images.githubusercontent.com/31826333/230767421-341b7a08-e322-4e96-9940-127ce77fd48e.png)
> 
> _We also changed some other part of the code but they might doing nothing, only this should fix the issue_

**Comments of the devs :**
We started to search where the bug is produced, in /island/algorithm/DefaultIslandEntitiesTrackerAlgorithm.java, we added this:
https://media.discordapp.net/attachments/1083461442440802385/1094656997900697860/image.png?width=1440&height=180
next, we thought some plugins use duplicated mobs to initialize stacks or custom attrributes on the event, to avoid some sort of duplicate, we tried to change the priority of the event to have more chances to avoid this behavior, in /listener/ChunkListener.java
https://media.discordapp.net/attachments/1083461442440802385/1094657520544534668/image.png?width=1440&height=63
Finally, we foud the source of the duplicated mobs on our server, the behavior on your plugin was: on chunk loading, you add mobs to the counter, but if the chunk was the island center, you triggered the recalculate
https://cdn.discordapp.com/attachments/1083461442440802385/1094658896385298432/image.png

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it works.

Working on test server, will put it on prod

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it works.
> 
> Working on test server, will put it on prod

Awesome.
What I don't understand is that in the original report, you reported mobs being counted less than the actual counts. However, this fix will patch mobs being counted too many times.

**Comment by WarnDa** [comment]
> > > Check out latest dev build, let me know if it works.
> > 
> > 
> > Working on test server, will put it on prod
> 
> Awesome. What I don't understand is that in the original report, you reported mobs being counted less than the actual counts. However, this fix will patch mobs being counted too many times.

Because in a year you changed the code, and maybe the code before was resetting the counter after 5mn
