### ISSUE TITLE
New player get two islands

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1044]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b586

### Describe the bug

Player currently own two islands

### To Reproduce

- Create an island
- Go to spawn
- Do /is again
- You are on a new island, but the old one still exist

### Additional Information

/is info    on both island, "chef" means "owner"

![Screenshot_390](https://user-images.githubusercontent.com/31826333/162634573-b1d7e691-f320-4cb0-b196-f975705ecebb.png)
![Screenshot_391](https://user-images.githubusercontent.com/31826333/162634574-30066d6d-756c-4ac3-8e4d-badee668880f.png)

- I'm using MySQL
- I already had this issue before (some month ago) but it was fixed with an update :/
- No error in console

**Comment by WarnDa** [comment]
He appears twice in the mysql database : 
![image](https://user-images.githubusercontent.com/31826333/162634761-361e76fb-96c8-4ff6-b2b5-27968f6d7073.png)

**Comment by WarnDa** [comment]
The old issue that was similar to this one : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/643

**Comment by OmerBenGera** [comment]
Any errors..?

**Comment by WarnDa** [comment]
Nothing, I checked latest.log :/

**Comment by OmerBenGera** [comment]
I can't replicate the issue, it works fine for me on localhost.
Are you able to replicate it yourself on localhost as well?

**Comment by WarnDa** [comment]
It happened to only one player, no other player reported it, so I don't know why it failed for him

**Comment by OmerBenGera** [comment]
> It happened to only one player, no other player reported it, so I don't know why it failed for him

Unless you can't replicate it nor any errors occurred, I can't fix it.

**Comment by WarnDa** [comment]
Can be closed and I'll reopen a ticket if needed, but strange that it happened :/
