### ISSUE TITLE
Warp Categories

### ISSUE THREAD

**Issue by anthod555** [BG-Software-LLC/SuperiorSkyblock2#1045]
### Minecraft's Version

Server version : 1.17.1
Paper : git-paper-402

### Plugin's Version

Plugin's Version : 1.9.0

### Describe the bug

Hello,

I notice a bug when modifying the warp category menu.
When I modify the menu, it does not resize it, so it leaves me with a double chest interface and does not apply the changes in the place of the items.

I am attaching the configuration I am using.

Cordially thank you

### To Reproduce

the configuration :  https://www.toptal.com/developers/hastebin/rekosuxowo.coffeescript

### Additional Information

![image](https://user-images.githubusercontent.com/61117662/162770530-f87c24e1-5741-4011-bce2-f1831b54d971.png)

**Comment by OmerBenGera** [comment]
How do you resize the menu..?

**Comment by anthod555** [comment]
from the warp_category file

**Comment by OmerBenGera** [comment]
> from the warp_category file

Show me the cpnfig file after you change its size

**Comment by anthod555** [comment]
before modification :
![image](https://user-images.githubusercontent.com/61117662/163042322-ac9ee75d-e7f7-4824-b42e-fea2cb7bcbba.png)

config : https://www.toptal.com/developers/hastebin/inawevepor.coffeescript
 
after modification : 

![image](https://user-images.githubusercontent.com/61117662/163042734-f00639f3-f1cf-4629-8dd9-dd7fc4389d6d.png)

config : https://www.toptal.com/developers/hastebin/yidobosufe.coffeescript

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
