### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/SuperiorSkyblock2#1047]
### Minecraft's Version

This server is running Mirai version git-Mirai-412832b (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 412832b on ver/1.18.2)

### Plugin's Version

b588

### Describe the bug

Console error:
https://pastebin.com/H3DJEGWZ

### To Reproduce

I created an island, started to destroy blocks, then deleted the island, created again and got this error.

### Additional Information

I use also addon: SSBOneBlock-1.2.0-b17.jar

**Comment by OmerBenGera** [comment]
Does it happen if you use Paper as well?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, lmk
