### ISSUE TITLE
Event-commands not working

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/SuperiorSkyblock2#1049]
### Minecraft's Version

Server version is 1.8.8 

### Plugin's Version

SuperiorSkyblock2-1.9.0-b588.jar

### Describe the bug

Event-commands do not work, I have tried using everything to get it working and it isnt. 

I have
event-commands:
  IslandDisbandEvent:
  - "/minion pickup"
  IslandResetEvent:
  - "/minion pickup"

Does it doesnt not perform the command.

### To Reproduce

Nothing happens, thats the problem.

**Comment by OmerBenGera** [comment]
It works fine for me.
Try removing the `/` at the start of the command, let me know if it works now.

**Comment by Rhys00** [comment]
> It works fine for me. Try removing the `/` at the start of the command, let me know if it works now.

Already tried that, I spent 40 minutes trying to get it working, I tried with and without the /, it didnt work.

**Comment by OmerBenGera** [comment]
> > It works fine for me. Try removing the `/` at the start of the command, let me know if it works now.
> 
> Already tried that, I spent 40 minutes trying to get it working, I tried with and without the /, it didnt work.

Send me your config.

**Comment by Rhys00** [comment]
> > > It works fine for me. Try removing the `/` at the start of the command, let me know if it works now.
> > 
> > 
> > Already tried that, I spent 40 minutes trying to get it working, I tried with and without the /, it didnt work.
> 
> Send me your config (Upload it to pastebin)

https://paste.helpch.at/hogaduvato.coffeescript (Pastebin wouldnt let me due to "offensive language")

**Comment by Rhys00** [comment]
Removing the / on the minion pickup command didnt work. However putting "say hello" did work and was sent via chat. https://prnt.sc/VM06C-uU4cMr

**Comment by OmerBenGera** [comment]
> Removing the / on the minion pickup command didnt work. However putting "say hello" did work and was sent via chat. https://prnt.sc/VM06C-uU4cMr

This means that the minions command you put is executed, even if the result of the command is not successful.
What minions plugin are you using?
