### ISSUE TITLE
Block values bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1050]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-60 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1d94256 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-47 (MC: 1.18.1)

### Plugin's Version

1.9.0.588 dev build

### Describe the bug

Some players had an issue after a crash where the island values are bugged. For example you can only have 5000 stacked gold blocks max, the stacked blocks is at 4000 but on the /island blocks it's showing it's 5000. You cannot add more gold blocks even after doing /is admin recalc, restart and more. 

### To Reproduce

Crash your server but before that add some island values to your island, relog and bam. 

### Additional Information

Example of the issue: https://gyazo.com/a83d35be83cee95f92493d09cf7ebcf8

**Comment by OmerBenGera** [comment]
`/is admin recalc` will count the blocks again if they are not synced anymore.

**Comment by OmerBenGera** [comment]
I looked at the video, and it looks like the blocks there are not stacked, however they probably were stacked before and due to the crash it occurred, which is more concern than block counts not synced correctly.

Are you able to replicate the issue again?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LuluxClient** [comment]
Edited the db and it got fixed
