### ISSUE TITLE
Barrel with chest access permission

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1051]
### Minecraft's Version

1.18.2

### Plugin's Version

b588

### Describe the bug

Hello, my player can open barrel without chest access permission. Can you add barrel into check ? Thx

### To Reproduce

Try to open barrel without chest permission.

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Players without chest-access cannot open barrels.

Do you have "BARREL" added to the interactables list?

**Comment by nivcoo** [comment]
Yes i didn't have it, it's good thx
