### ISSUE TITLE
Mission error (Same as before)

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1052]
### Minecraft's Version

1.18.2

### Plugin's Version

b588

### Describe the bug

Hello i've the same issue as before : https://pics.revolis.fr/2022/04/14/18-41_VVps.png (I've updated the plugin and remove my jar 
 modules files)

### To Reproduce

Idk exactly how to reproduce that

**Comment by nivcoo** [comment]
I've tried to remove now the BlocksMissions and decompile it and i haven't the recently changes

**Comment by nivcoo** [comment]
And if i place manually the new BlockMissions jar it will be replaced by the old after /is admin reload

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by nivcoo** [comment]
I think it's good, now i've the new module jar in my folder

**Comment by OmerBenGera** [comment]
Great, I probably forgot to actually include them in the plugin itself - dummy me.
Closing this, if it still occurs let me know

**Comment by nivcoo** [comment]
Yes you placed them intot wrong directory look : https://github.com/BG-Software-LLC/SuperiorSkyblock2/tree/dev/src/main/resources/modules/missions/categories in previous commit you have added jar into /category folder, now you can maybe delete them because it's not the good directory
