### ISSUE TITLE
Mission data resetting on restarting server

### ISSUE THREAD

**Issue by gunhippy** [BG-Software-LLC/SuperiorSkyblock2#1053]
### Minecraft's Version

[2022-04-15 08:22:47] [INFO]: This server is running Paper version git-Paper-277 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 87e11bf)

### Plugin's Version

[2022-04-15 08:23:28] [INFO]: SuperiorSkyblock2 version 1.9.0.590

### Describe the bug

Current mission progress is reset upon server stop / restart

### To Reproduce

make progress towards a mission
stop server
start server

ALSO

make progress towards a mission
restart server

### Additional Information

https://pastebin.com/h6UrYUsH

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
What mission are you referring to?

Also, after you stop the server, do you see your progress in the data file?
Try it on localhost.

**Comment by gunhippy** [comment]
Farming, monster and mining missions are all affected by the looks of it.

**Comment by gunhippy** [comment]
the _data.yml doesn't look to have been written to for the last two days, and is generally being ignored by the looks of it

**Comment by OmerBenGera** [comment]
> Farming, monster and mining missions are all affected. It is mission progress in general. There are errors around unloading missions in the server logs on shutdown

You should have mentioned it before.
Upload the errors you encounter to pastebin and send then here.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue.

**Comment by gunhippy** [comment]
new dev build looks to be working more as expected. I deleted the _data.yml for good measure with it not being written to for a number of days.

**Comment by OmerBenGera** [comment]
Should I close it then?
