### ISSUE TITLE
SuperiorSkyBlock translating placeholder

### ISSUE THREAD

**Issue by N1kyZ** [BG-Software-LLC/SuperiorSkyblock2#1054]
### Minecraft's Version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.9.0.591
PlaceholderAPI version 2.11.1

### Describe the bug

Well, I have a Brazilian server and when I put the **SuperiorSkyblock** together with the **PlaceholderAPI**, the placeholder **%server_time_EEEE%** is translated to English

### To Reproduce

1. Open the server with the two mentioned plugins.
2. Download the Server extension using **/papi ecloud download server** and then use **/papi reload** to activate the extension.
3. Then use **/papi to parse me %server_time_EEEE%** and see

### Additional Information

No SuperiorSkyBlock
![image](https://user-images.githubusercontent.com/58773688/163582175-ea700b47-4b59-41c3-8e01-93af741ffacf.png)

With SuperiorSkyBlock
![image](https://user-images.githubusercontent.com/58773688/163582448-80bc94c4-e67f-4b04-9a27-97a2dd74a3f8.png)

**Comment by OmerBenGera** [comment]
This happens because the plugin changes the server's language to English due to issues with other languages breaking things with the plugin.

I will look into that and see what can be done regarding this

**Comment by N1kyZ** [comment]
ok

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by N1kyZ** [comment]
It worked C:
