### ISSUE TITLE
Cobble Gen only making ores when lava flow disabled

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1055]
### Minecraft's Version

1.18.2 purpur

### Plugin's Version

Dev build 588

### Describe the bug

When lava flow is disabled, only ores generate in cobblestone generator

### To Reproduce

Have ores in cobble gen
Disable lava flow

### Additional Information

Is admin info: https://pastebin.com/AYi6awJ4
Video: https://streamable.com/o5codf

**Comment by OmerBenGera** [comment]
I am not sure I get what you reported here - what is the expected behavior?

**Comment by DuneSciFye** [comment]
It should generate cobblestone and ores

**Comment by OmerBenGera** [comment]
> It should generate cobblestone and ores

And what is the issue...?

**Comment by DuneSciFye** [comment]
It only generates ores when lava flow is disabled

**Comment by OmerBenGera** [comment]
> It only generates ores when lava flow is disabled

For me it works just fine.
Mind testing it on a server with only SSB installed on it?

**Comment by DuneSciFye** [comment]
Tested it more, so I have water flow enabled and lava flow disabled. When first placing down the lava, an ore generates. I break the ore block, nothing. However, if I update that block, such as placing any block and breaking it, then another ore generates.
![image](https://user-images.githubusercontent.com/65089425/163683528-7f26db50-6349-4309-9ab7-8e4a2ddb3155.png)
![image](https://user-images.githubusercontent.com/65089425/163683533-1848ba42-b915-4721-a2ef-bf064278a533.png)

**Comment by OmerBenGera** [comment]
Take a video of the issue please (Upload it to YT or any other streaming service)

**Comment by DuneSciFye** [comment]
https://streamable.com/o5codf here you go, and I also posted it in the additional information part

**Comment by OmerBenGera** [comment]
In the video you provided everything looks fine, ores are generated as they should.

**Comment by DuneSciFye** [comment]
But it should also generate cobblestone as is admin shows the cobblegen rates include cobblestone. I posted the is admin info in a pastebin in additional information

**Comment by DuneSciFye** [comment]
also it shouldn't even be generating ores. Lava flow is disabled

**Comment by OmerBenGera** [comment]
Right, that is not the expected behavior, generators should not be working when lava-flow is disabled. 
It's fixed in latest dev build.

Let me know if there's anything else that is not working as intended.

**Comment by DuneSciFye** [comment]
Where do I download the latest dev build? Is it 595?

**Comment by DuneSciFye** [comment]
yup all fixed.
