### ISSUE TITLE
Placeholder Price Type not work.

### ISSUE THREAD

**Issue by Student-FastDev** [BG-Software-LLC/SuperiorSkyblock2#1056]
### Minecraft's Version

1.17.1 Paper
![Screenshot_3](https://user-images.githubusercontent.com/101209411/163668075-2b21a475-09b9-47a6-97d1-f95801cbdcff.png)

### Plugin's Version

1.9.0
![Screenshot_2](https://user-images.githubusercontent.com/101209411/163667920-eea09cef-b391-4d86-86c6-d8d8a5db7710.png)

### Describe the bug

Placeholder Price Type not work.

I use GemsEconomy plugin for Economy. I have 2 currencies: pieniądz, szt. I need the improvements to work on the szt. currency, but it takes money from pieniądz currency. I don't know how it happens.  Pieniadz is default currency, but when i change default currency to szt.  it works properly. Can't set  szt. to default currency, because i need to other plugins. Can anyone help?

### To Reproduce

![Screenshot_4](https://user-images.githubusercontent.com/101209411/163668255-a613afa6-adf6-4f88-a65e-469603ae0ab3.png)

**Comment by OmerBenGera** [comment]
Mind trying to change the currency names to english?
Let me know if it fixes the issue

**Comment by Student-FastDev** [comment]
> Mind trying to change the currency names to english? Let me know if it fixes the issue

Not work.

**Comment by OmerBenGera** [comment]
When you run `/papi parse me <placeholder>`, what does it return? (The placeholder you configured)

**Comment by Student-FastDev** [comment]
![image](https://user-images.githubusercontent.com/101209411/163685492-1673141e-1744-4e4f-bcb3-5523bd0e3b69.png)
This on top is formatted
This on bottom id non-formatted
I use in upgrade config non-formatted

**Comment by OmerBenGera** [comment]
What happens if you run the withdraw command manually?

**Comment by Student-FastDev** [comment]
![image](https://user-images.githubusercontent.com/101209411/163686549-ebc402fa-84dc-4eb9-b2d4-7537dce434fb.png)
This happened.
(informejt1k is my friend)

**Comment by OmerBenGera** [comment]
Why is it only 1 that is being taken away and not 100 as you configured?

**Comment by Student-FastDev** [comment]
> Why is it only 1 that is being taken away and not 100 as you configured?

I set it to take 1 because I didn't know how much he has of this currency

**Comment by OmerBenGera** [comment]
Also, I don't see where you configured the upgrade to use placeholders as price-type.
Add `price-type: 'placeholders'` to the upgrade.

**Comment by Student-FastDev** [comment]
![image](https://user-images.githubusercontent.com/101209411/163687003-440ba909-6f7a-4bc6-9e2a-062a71aa90d0.png)
Works correctly

**Comment by Student-FastDev** [comment]
> Also, I don't see where you configured the upgrade to use placeholders as price-type. Add `price-type: 'placeholders'` to the upgrade.

![image](https://user-images.githubusercontent.com/101209411/163687047-b72abfd8-f132-462a-84bb-2d765ed12fe0.png)
Like this?

**Comment by OmerBenGera** [comment]
> 

Yes.

**Comment by Student-FastDev** [comment]
Sorry missclick xD

**Comment by Student-FastDev** [comment]
> > 
> 
> Yes.

Oh, It started to work well! Thanks!

**Comment by OmerBenGera** [comment]
You welcome :)
