### ISSUE TITLE
Is warp on a glass block

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1057]
### Minecraft's Version

Current: git-Purpur-1565 (MC: 1.18.1)*
Previous: git-Pufferfish-47 (MC: 1.18.1)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

1.9.0 latest stable

### Describe the bug

When you put an is warp on a glass block, you cannot tp to here because it's "unsafe location".

If it's not a bug, i think it's a good idea to add a boolean to the config to allow or not """unsafe""" location.

### To Reproduce

1. Put a glass block down the void.
2. Set a Warp
3. try to tp

### Additional Information

https://gyazo.com/d7a3e6ec40b097337da13f9516a9e173

**Comment by OmerBenGera** [comment]
Try using latest dev build, let me know if it's better

**Comment by SwartZCoding** [comment]
> 
Fixed ! Thx

**Comment by OmerBenGera** [comment]
:)
