### ISSUE TITLE
Breaking stacked block doesn't give drops and error

### ISSUE THREAD

**Issue by kizoukun** [BG-Software-LLC/SuperiorSkyblock2#1060]
### Minecraft's Version

 Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-1.9.0-b595 

### Describe the bug

https://pastebin.com/fqw6BSGk

### To Reproduce

Place stacked block then break the stacked block

**Comment by OmerBenGera** [comment]
Does it occur on a server with only SSB installed?

**Comment by kizoukun** [comment]
Sorry found the issues it was because a plugin called "AdvancedAutoSmelt" and i think because the fitur autopickup
