### ISSUE TITLE
Name of World

### ISSUE THREAD

**Issue by yunanmadenci** [BG-Software-LLC/SuperiorSkyblock2#1061]
### Minecraft's Version

Purpur 1611 MC: 1.18.2 (latest)

### Plugin's Version

1.9.0 (latest)

### Describe the bug

When I change the name of my world from **/island admin settings** or from config (line 284 and 328) it resets to **SuperiorWorld** at line 328 when I reset my server every time.

### To Reproduce

Changing the name of normal world is buggy. I first saw this bug when I changed the world's name. It was ok when I checked in F3. But when I close and re-open my server line 328 changes to SuperiorWorld and resets.

### Additional Information

![image](https://user-images.githubusercontent.com/103884633/163713909-2561cc1f-4078-41e3-b035-327946044deb.png)
![image](https://user-images.githubusercontent.com/103884633/163713923-6a15e9a3-f325-4fd5-b561-094952169004.png)

**Comment by OmerBenGera** [comment]
Delete the database.db file, then change the name of the world.
You cannot change the name of the world while having islands - it even warns you in console.
