### ISSUE TITLE
Placeholder ERROR

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1063]
### Minecraft's Version

1.18.2

### Plugin's Version

b595

### Describe the bug

Hello, idk when but now i've this error, when i do : /papi parse me %superior_island_entity_limit_villager%
![image](https://user-images.githubusercontent.com/36514752/163857537-1ad840f7-ea7a-433a-bcc4-91e062291845.png)

### To Reproduce

Use latest version and try /papi parse me %superior_island_entity_limit_villager%

**Comment by OmerBenGera** [comment]
Use VILLAGER for now

**Comment by nivcoo** [comment]
It works thx

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
