### ISSUE TITLE
I've changed the prices of upgrades in the config but it does not update in game even with a restart

### ISSUE THREAD

**Issue by ItsBixby** [BG-Software-LLC/SuperiorSkyblock2#1064]
### Minecraft's Version

spigot 1.8.8

### Plugin's Version

SuperiorSkyblock2-1.9.0.jar

### Describe the bug

I've changed the prices of upgrades in the config but it does not update in game even with a restart

### To Reproduce

Go into the upgrades config and modify the prices
restart server
check island upgrades

**Comment by OmerBenGera** [comment]
Upload your upgrades file to pastebin and send it here

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Maybe you just didn't update the prices in the item's format?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, lmk by replying here
