### ISSUE TITLE
Problem with reproduce villagers 

### ISSUE THREAD

**Issue by Chrqmated** [BG-Software-LLC/SuperiorSkyblock2#1066]
### Minecraft's Version

Purpur 1.16.5

### Plugin's Version

Plugin version: 1.9.0

### Describe the bug

Hello,

The villagers do not happen again because they can not replant on the island of a player, they can not throw itself from items, nor put things in the composters.

Do you have an idea to solve this?

### To Reproduce

For reproduce this bug, Trying to reproduce villagers on your island in 1.16.5

**Comment by OmerBenGera** [comment]
Try replicating the issue on another server with only SSB installed on it

**Comment by OmerBenGera** [comment]
> I have disabled wildstacker, the problem it's resolve

Did you nerf villagers by any chance?

**Comment by OmerBenGera** [comment]
Ah I saw that you opened a new issue, we'll movr there :)
