### ISSUE TITLE
Players can't interact in their own island

### ISSUE THREAD

**Issue by Ecilpse** [BG-Software-LLC/SuperiorSkyblock2#1067]
### Minecraft's Version

1.18.1 purpur

### Plugin's Version

lastest dev build (1.9.0 600)

### Describe the bug

#1059
when i update lastest dev build, player can not open their's door, chest.
when break blocks message was printed "outsider can not destory block".
but when player command /is home, still moved their island.

### To Reproduce

this problems happend some player's island. (or player?)
so it's seem's hard to reproduce.
i can give island's data file & map

**Comment by OmerBenGera** [comment]
1 - Change your title, it's misleading.
2 - Sounds like the players are not inside their islands (their homes are outside of their island).
Debug the situation using `/is admin show` and report back what you found (For example, the location of their island homes is outside of their island, etc)

**Comment by WarnDa** [comment]
Can confirm the issue, console error on startup :
https://pastebin.com/jT46LSp4

**Comment by Ecilpse** [comment]
> 1 - Change your title, it's misleading. 2 - Sounds like the players are not inside their islands (their homes are outside of their island). Debug the situation using `/is admin show` and report back what you found (For example, the location of their island homes is outside of their island, etc)

not their outside of island. all player can't open their containers. what is title?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
