### ISSUE TITLE
is upgrades

### ISSUE THREAD

**Issue by SolitudineDEV** [BG-Software-LLC/SuperiorSkyblock2#1069]
### Minecraft's Version

1.18.2 paper

### Plugin's Version

SuperiorSkyblock2-1.9.0-b605.jar

### Describe the bug

![image_2022-04-22_233551722](https://user-images.githubusercontent.com/39512065/164799025-d44aa31b-b06c-423e-b35a-23ed3df65e57.png)

/is upgrade response

### To Reproduce

/is upgrade

**Comment by OmerBenGera** [comment]
Is the menu opened for you?

**Comment by OmerBenGera** [comment]
It works fine for me.
Mind trying it with default language file, so I understand which messages exactly are these?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, lmk by replying here
