### ISSUE TITLE
Bedrock players unable to interract with menus when connected viabgeuser

### ISSUE THREAD

**Issue by gunhippy** [BG-Software-LLC/SuperiorSkyblock2#1070]
### Minecraft's Version

1.18.2 - but any version is affected 

### Plugin's Version

Latest dev build

### Describe the bug

Due to click type methods not being implemented  in geyser, any plugin that requires interactions via menus (ssb, deluxemenus) aren't usable for bedrock players.

If they go to click a menu item, it picks it up instead of taking it as a click.

### To Reproduce

Install geyser and floodgate on server 

Connect via a bedrock client

Open /is create testisland

Try to select island type

**Comment by OmerBenGera** [comment]
Do you have any suggestions on how I can implement a workaround? I personally dont have a way to debug it, so I dont really know what bedrock players can do or cannot.

Let me know if you can think about anything :)

**Comment by gunhippy** [comment]
So at the moment they can't do anything that involved interracting with a menu or a sign. So if they try to interract with a menu, instead of the items being clickable into other menus / selecting options, the item instead gets picked up by the player as though they can move it into their inventory

**Comment by OmerBenGera** [comment]
Trying to get a bedrock edition, will hopefully get one soon so I can look into it.

**Comment by OmerBenGera** [comment]
I joined through Windows Bedrock Edition to my Java edition server using Geyser and I can interact with menus (I can't right click them, however clicking them regularly works fine).

Am I missing something?

**Comment by gunhippy** [comment]
Nope, Geyser has had an update which has added new calls by the looks of things. After you said it worked fine, I updated Geyser and it's now working!

**Comment by OmerBenGera** [comment]
> Nope, Geyser has had an update which has added new calls by the looks of things. After you said it worked fine, I updated Geyser and it's now working!

Great. Now the only issue is to do with replacement for right clicking items not working.
Do you have a suggestion how this can be fixed for bedrock players?

**Comment by gunhippy** [comment]
For clickable signs on other maps, we've been using buttons with command blocks to execute the same. However it's not ideals. I don't think there is much on SSB that needs right click is there?

**Comment by OmerBenGera** [comment]
> For clickable signs on other maps, we've been using buttons with command blocks to execute the same. However it's not ideals. I don't think there is much on SSB that needs right click is there?

There's custom actions when right clicking items inside menus.

**Comment by gunhippy** [comment]
ok, I've unleashed the server on our bedrock players now so I'll get them to help with suggestions and feedback anything else

**Comment by OmerBenGera** [comment]
> ok, I've unleashed the server on our bedrock players now so I'll get them to help with suggestions and feedback anything else

Perfect!
Let me know here once you have an idea how we can solve the issue :)

Btw, what version of Geyser did you use before that did not work?

**Comment by gunhippy** [comment]
FYI from one user:
Bedrock issue for touch/controller -- changing Island Permissions, the lack of right click prevents raising the required level for the permission...you can lower the role, but not raise it back

I've asked whether cycling through from the start afyer getting to the end opyion would work if possible and they said "yes, it was what they kinda expected it to do"

**Comment by OmerBenGera** [comment]
@gunhippy I changed it to work the way you mentioned in latest dev build.

I will keep this issue opened so if there are more issues like this you can just report them here and we will find a solution for them :)

**Comment by OmerBenGera** [comment]
I think this can be closed for now, no reports since my last message :)
