### ISSUE TITLE
Pistons cause lag with BlocksMissions

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1072]
### Minecraft's Version

1.18.2

### Plugin's Version

b607

### Describe the bug

Hello, i did spark profiler and i've that on the top https://pics.revolis.fr/2022/04/25/19-25_lPUS.png (I have lot of piston but why to you handle piston for block missions ?). Can you maybe look at this timings ? Thx

### To Reproduce

Use the plugin

**Comment by OmerBenGera** [comment]
Please send a link to the spark that you took

**Comment by nivcoo** [comment]
Yes https://spark.lucko.me/YxEoyXfg6C

**Comment by nivcoo** [comment]
Hello, any news ?

**Comment by nivcoo** [comment]
I think you fixed one point of my timing here : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1073 (But this issue has 3% of tick and i've 13%) here i've another spark : https://spark.lucko.me/oITuBGFikv

**Comment by nivcoo** [comment]
Hello, any news ?

**Comment by OmerBenGera** [comment]
> Hello, any news ?

Not yet.
There is no need to bump the issue

**Comment by nivcoo** [comment]
Maybe add option to disable piston event, i don't really want to check piston move for mission (It's not necessary)

**Comment by OmerBenGera** [comment]
> Maybe add option to disable piston event, i don't really want to check piston move for mission (It's not necessary)

It is necessary.

**Comment by OmerBenGera** [comment]
[BlocksMissions2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8626643/BlocksMissions2.zip)

Hey, I want you to try this one.
Inside the zip there's a jar file. Take this jar file and put it in the missions category; then, change your blocks-related missions to use the mission jar "BlocksMissions2" instead of "BlocksMissions"

After that, take a spark profiler and let me know if it's better.

**Comment by nivcoo** [comment]
Hello, i will try that and chek that tomorrow thx

**Comment by OmerBenGera** [comment]
[BlocksMissions2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8635434/BlocksMissions2.zip)
Try this one instead.

**Comment by nivcoo** [comment]
I haven't error now, i will try tomorrow to do a spark profile

**Comment by nivcoo** [comment]
It's worst now https://spark.lucko.me/2XhoGzm0aZ

**Comment by OmerBenGera** [comment]
The spark profiler you sent shows an improvement of almost 5%, not sure how it's worst.
Anyways, I will look into optimizing it even further.

**Comment by nivcoo** [comment]
Because i've only 20 players in this spark

**Comment by nivcoo** [comment]
Maybe can you do check async ? If it's just getblock you can do that async right ?

**Comment by OmerBenGera** [comment]
> Maybe can you do check async ? If it's just getblock you can do that async right ?

No, this cannot be done async.

**Comment by nivcoo** [comment]
If i don't use "blocks-placement: true " i will disable the piston check ? (because i saw : TrackingType.PLACED_BLOCKS)

**Comment by OmerBenGera** [comment]
> If i don't use "blocks-placement: true " i will disable the piston check ? (because i saw : TrackingType.PLACED_BLOCKS)

No.

**Comment by nivcoo** [comment]
I do lot of spark to compare with big island and less/more players with this spark (1 hours of profiler) SS2 = 25% https://spark.lucko.me/YLZuhiO6jI 22% only for piston, i inspect your code and i understand now why you use piston event. Maybe you can create something (or me). Like BlockMissions, but decrease number when player place specific mission block and add when he break block (And reverse for place mission)

**Comment by nivcoo** [comment]
I edited your code and do that : https://www.toptal.com/developers/hastebin/usajijazet.java 
With that the number can go through 0 / -0

**Comment by nivcoo** [comment]
(It's for my usage but maybe it can help another pleople )

**Comment by nivcoo** [comment]
Hum, https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/8724113333d3c8368e2a11522e3670a54faec95d/BlocksMissions/src/main/java/com/bgsoftware/superiorskyblock/missions/BlocksMissions.java#L353 i think here you check all missions in same times : maybe use hasAllRequiredMissions before check all blocks ?

**Comment by OmerBenGera** [comment]
> (It's for my usage but maybe it can help another pleople )

Not recommended at all, as by removing the piston check players can just move blocks and "dupe" them for progress.

**Comment by OmerBenGera** [comment]
> Hum, https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/8724113333d3c8368e2a11522e3670a54faec95d/BlocksMissions/src/main/java/com/bgsoftware/superiorskyblock/missions/BlocksMissions.java#L353 i think here you check all missions in same times : maybe use hasAllRequiredMissions before check all blocks ?

Great idea.
I will look into implementing it.

**Comment by nivcoo** [comment]
> > (It's for my usage but maybe it can help another pleople )
> 
> Not recommended at all, as by removing the piston check players can just move blocks and "dupe" them for progress.

Yes i understand it's an issue if i disable the piston event in your system but in my code i simply decrease the count when players player block (-1 -2 -3....) and add number if they break blocks and reverse for placement mission

**Comment by nivcoo** [comment]
So it's not a problem if player use piston because their number is previously impact by placement event

**Comment by OmerBenGera** [comment]
> So it's not a problem if players use piston because their proogression is previously impacted by placement event, it's just another way to check mission

This is not a good solution, as players that just want to build will have their progress go down for no reason.

**Comment by nivcoo** [comment]
> > So it's not a problem if players use piston because their proogression is previously impacted by placement event, it's just another way to check mission
> 
> This is not a good solution, as players that just want to build will have their progress go down for no reason.

Yes, but it's better than track all blocks in the server because of lags, why can't you do that async ? You don't interact with server to have to use sync method.

Maybe you can create "Queue track async" to add piston event into async method and calculate the progress after queue event or something like that.


Because your systeme generate 350mb+ with only 35 players, so can you imagine if server has 200+ players.

You can use metadata and update it when piston move, idk if it can create lag like that.

**Comment by OmerBenGera** [comment]
> > > So it's not a problem if players use piston because their proogression is previously impacted by placement event, it's just another way to check mission
> > 
> > 
> > This is not a good solution, as players that just want to build will have their progress go down for no reason.
> 
> Yes, but it's better than track all blocks in the server because of lags, why can't you do that async ? You don't interact with server to have to use sync method.
> 
> Maybe you can create "Queue track async" to add piston event into async method and calculate the progress after queue event or something like that.
> 
> Because your system generate 350mb+ with only 35 players, so can you imagine if server has 200+ players.
> 
> You can maybe use metadata and update it when piston move, idk if it can create lag like that.

It must be done sync because there's interaction with the world; checking for block types, etc. Also, making it async will not help with anything, as the thread-safe logic for the entire container will cause more lag.
If there's a lag from a system, the solution is to **optimize** it and not make it on another thread.

About the metadata suggestion, it will cause memory leaks and metadata should always be avoided. Also, it will not fix anything as I'll still need to track the metadata value when blocks move.

As I stated already, I will look into optimizing it even further and will send you results soon to test them out.

**Comment by OmerBenGera** [comment]
[BlocksMissions.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8688630/BlocksMissions.zip)
Try this one please.
Hopefully it will be better in terms of performance as well as data usage.
Now blocks tracking is done for all the missions instead of duplicating unnecessary data, and I also fixed creation of unnecessary data to help with ram usage.
Let me know how is it now.

Again, make sure you rename the jar inside the zip to "BlocksMissions2.jar" and replace it with the old one, as well as editing all your missions that work with BlocksMissions and change them to work with BlocksMissions2

You cannot replace this one with the regular BlocksMissions, so take that in mind.

**Comment by nivcoo** [comment]
Thx, i will try it

**Comment by nivcoo** [comment]
I've error https://pics.revolis.fr/2022/05/13/16-42_27ME.png

**Comment by OmerBenGera** [comment]
[BlocksMissions2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8688755/BlocksMissions2.zip)
Try this for the error

**Comment by nivcoo** [comment]
I no longer have the error, i will try to do spark profiler if i've tps issue

**Comment by nivcoo** [comment]
For now, with 30 players i don't have tps issue

**Comment by nivcoo** [comment]
https://spark.lucko.me/Weqv6MzVy9

**Comment by nivcoo** [comment]
Some players don't have correct count after breaking blocks that were previously moved by a piston (generator), i will investigate

**Comment by OmerBenGera** [comment]
That might be because you placed a block in the location between the two pistons.
Try placing a block there again and then break it manually, without the pistons moving it. 
Let me know if it helps

**Comment by nivcoo** [comment]
After all restart all data was cleared, the data file is good, i think the load method doesn't work correctly and after the second restart the data will be cleared

**Comment by OmerBenGera** [comment]
[BlocksMissions2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8692537/BlocksMissions2.zip)
There was an issue with loading the tracked blocks, not the counts however.
This should fix the issue, let me know if it's better.

**Comment by OmerBenGera** [comment]
I also changed it for the next update to separate the data files of missions to different files instead of one big file.

**Comment by nivcoo** [comment]
It works for the count but i've always the issue with piston count : https://pics.revolis.fr/2022/05/14/12-39_4EQC.mp4 it doesn't count after piston move

**Comment by OmerBenGera** [comment]
> It works for the count but i've always the issue with piston count : https://pics.revolis.fr/2022/05/14/12-39_4EQC.mp4 it doesn't count after piston move

As I said before:
```
That might be because you placed a block in the location between the two pistons.
Try placing a block there again and then break it manually, without the pistons moving it.
Let me know if it helps
```

**Comment by nivcoo** [comment]
> > It works for the count but i've always the issue with piston count : https://pics.revolis.fr/2022/05/14/12-39_4EQC.mp4 it doesn't count after piston move
> 
> As I said before:
> 
> ```
> That might be because you placed a block in the location between the two pistons.
> Try placing a block there again and then break it manually, without the pistons moving it.
> Let me know if it helps
> ```

Yes like you can see in the video i tried to place block and break it and let minecraft generate block and move it after and it doesn't work

**Comment by nivcoo** [comment]
I think you don't check if the block is currently tracked https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/8724113333d3c8368e2a11522e3670a54faec95d/BlocksMissions/src/main/java/com/bgsoftware/superiorskyblock/missions/BlocksMissions.java#L355 (Before you did that), but i new version : https://pics.revolis.fr/2022/05/14/13-11_vLK7.png you don't check if the block is tracked

**Comment by OmerBenGera** [comment]
> I think you don't check if the block is currently tracked https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/8724113333d3c8368e2a11522e3670a54faec95d/BlocksMissions/src/main/java/com/bgsoftware/superiorskyblock/missions/BlocksMissions.java#L355 (Before you did that), but i new version : https://pics.revolis.fr/2022/05/14/13-11_vLK7.png you don't check if the block is tracked

Right, looks wrong. Looking into it rn.

**Comment by nivcoo** [comment]
No problem, thx

**Comment by OmerBenGera** [comment]
[BlocksMissions2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8692812/BlocksMissions2.zip)
Here, should work now. Let me know if it works or if it dropped performance.

**Comment by nivcoo** [comment]
For the moment it works, i will wait to know if i've performance issue

**Comment by dan28000** [comment]
from testing default missions and these don't count blocks from oneblock if you have oneblock addon

**Comment by OmerBenGera** [comment]
Closing this for now
If it still have problems, lmk
