### ISSUE TITLE
getIslandAt() is heavy

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1073]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b607

### Describe the bug

the event getIslandAt() everytime a mob spawn is heavy, maybe it could be optimised, would help with tps

### To Reproduce

- Turn on mob limit
- Spawn mobs (using spawners)

### Additional Information

![image](https://user-images.githubusercontent.com/31826333/165576739-d00c1fcf-0a5a-4b6f-a170-40d7af4c979d.png)
https://spark.lucko.me/pcq5d5QqQn

**Comment by OmerBenGera** [comment]
There seems to be a serious problem with getting the center of the island, which obviously must be fixed.

I will look into it.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by WarnDa** [comment]
I just tried the update (currenty 2am so only 10 players) and saw a new event I haven't seen before : 
![image](https://user-images.githubusercontent.com/31826333/165864000-a7cc7bcb-228b-49b9-9614-6c1fdb5c62fd.png)

I don't know what it is but it takes 1% : https://spark.lucko.me/hUlXBb5ztl


I'll do another spark tomorrow with more player to compare the getIslandAt() !

**Comment by OmerBenGera** [comment]
> I tested b609 : ![image](https://user-images.githubusercontent.com/31826333/165956097-fddf1490-5fec-48d7-bc60-db33e3202a1c.png)
> 
> Better than before, don't close I'll test b611 soon for the growth event

Send me this spark please as well

**Comment by WarnDa** [comment]
https://spark.lucko.me/qLPzrVPgNV

**Comment by WarnDa** [comment]
New spark on b625:
![image](https://user-images.githubusercontent.com/31826333/166169186-205d55b5-2286-46ea-b359-0cb672000fb7.png)

https://spark.lucko.me/pt4CaTtOkg

**Comment by OmerBenGera** [comment]
Perfect :)

**Comment by WarnDa** [comment]
It can still rise up to 0.5% for this event, I don't know if it can be better (maybe) :
![image](https://user-images.githubusercontent.com/31826333/166492896-578e150a-3368-4fb8-9dfd-fc43af90a602.png)
https://spark.lucko.me/Juf9HyGF7t

**Comment by OmerBenGera** [comment]
> It can still rise up to 0.5% for this event, I don't know if it can be better (maybe) : ![image](https://user-images.githubusercontent.com/31826333/166492896-578e150a-3368-4fb8-9dfd-fc43af90a602.png) https://spark.lucko.me/Juf9HyGF7t

That's fine.
If it makes your TPS go down, let me know.
