### ISSUE TITLE
Sometimes server do not shutdown

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1074]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b605

### Describe the bug

Sometimes the server take 10-15 minutes to restart (using auto restart scheduler on docker) 
It happened 3 times in 2 weeks, everytime on "disabling upgrades"
### To Reproduce

I don't know it's very random

### Additional Information

It freezes on upgrades disabling
![image](https://user-images.githubusercontent.com/31826333/165722514-53d38ceb-6cd9-4057-9c88-9d12ca47b4a8.png)

**Comment by OmerBenGera** [comment]
I uploaded a new version that should print more messages when the plugin disables to better understand what causes this to happen, as I don't think it's the upgrades module, but something after that.

**Comment by WarnDa** [comment]
I tried on b625 and got :
> [17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module bank...
[17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module missions...
[17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module nashorn-engine...
[17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module generators...
[17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module upgrades...
[17:46:14 INFO]: [SuperiorSkyblock2] Unloading worlds...

In logs, I had to kill server because after 2mn it was still on this event

**Comment by OmerBenGera** [comment]
> I tried on b625 and got :
> 
> > [17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module bank...
> > [17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module missions...
> > [17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module nashorn-engine...
> > [17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module generators...
> > [17:46:14 INFO]: [SuperiorSkyblock2] Disabling the module upgrades...
> > [17:46:14 INFO]: [SuperiorSkyblock2] Unloading worlds...
> 
> I had to kill server because after 3mn it was still on this event

Weird, for no reason unloading the worlds cause this.
I will look into it

**Comment by WarnDa** [comment]
Hello,

This happened yesterday, and also today (using b642), did you find a solution ? or more debug ?

**Comment by OmerBenGera** [comment]
> Hello,
> 
> This happened yesterday, and also today (using b642), did you find a solution ? or more debug ?

Not yet.
I suspect it might be an intensive logic being ran when unloading the worlds that cause it to happen.

I will try to kick players before doing so, might help with that.

**Comment by WarnDa** [comment]
I get this problem everyday now :c
I tried to kickall every player before restart, did the same things.
And in logs I got and error : 
https://pastebin.com/nNrfLBVE

**Comment by OmerBenGera** [comment]
> I get this problem everyday now :c I tried to kickall every player before restart, did the same things. And in logs I got and error : https://pastebin.com/nNrfLBVE

Report the error to Pufferfish, nothing to do with SSB.
Also, the error might be the cause of the issue. Have you tried another spigot jar that doesn't have these errors?

**Comment by OmerBenGera** [comment]
> Answer of the dev : Something tried to load a chunk as the server was shutting down, this isn't a pufferfish issue, pufferfish doesn't even touch this code
> 
> Maybe it's superior that try to load chunk for the entity limit ?

As I said before, try another server jar that doesn't throw that error and check if the unloading of worlds still hangs the server.
Let me know once you tried it.

**Comment by WarnDa** [comment]
Paper 1.17 get crashs dupe with lectern and other issue (that pufferfish patchs), so I can't really switch to paper 1.17 :/
I think it's an issue with mobs in the world

**Comment by OmerBenGera** [comment]
I also added a check to make sure no chunks are loaded after plugin was disabled, so you can also check that out in latest dev build and let me know if it helps.

**Comment by kev626** [comment]
> > Answer of the dev : Something tried to load a chunk as the server was shutting down, this isn't a pufferfish issue, pufferfish doesn't even touch this code
> > Maybe it's superior that try to load chunk for the entity limit ?
> 
> As I said, try another server jar that doesn't throw that error and check if the unloading of worlds still hangs the server. Let me know once you tried it.

Every server jar since at least Paper 1.17.1 should throw this error. Loading chunks as the world is shutting down is extremely unsafe and can result in corruption, which is the reason this error exists in the first place - to prevent such things from happening.

**Comment by OmerBenGera** [comment]
> > > Answer of the dev : Something tried to load a chunk as the server was shutting down, this isn't a pufferfish issue, pufferfish doesn't even touch this code
> > > Maybe it's superior that try to load chunk for the entity limit ?
> > 
> > 
> > As I said, try another server jar that doesn't throw that error and check if the unloading of worlds still hangs the server. Let me know once you tried it.
> 
> Every server jar since at least Paper 1.17.1 should throw this error. Loading chunks as the world is shutting down is extremely unsafe and can result in corruption, which is the reason this error exists in the first place - to prevent such things from happening.

As I said, it should have been fixed.

**Comment by WarnDa** [comment]
Hello,

Happened this morning on b644 : https://pastebin.com/0ZziExS4

**Comment by OmerBenGera** [comment]
> Hello,
> 
> Happened this morning on b644 : https://pastebin.com/0ZziExS4

Well, we can say the chunk loading wasnt the issue.
I will look into removing the manually unloading of the worlds and hopefully it will fix everything

**Comment by kev626** [comment]
> Hello,
> 
> Happened this morning on b644 : https://pastebin.com/0ZziExS4

That's a totally different error in a totally different plugin...

**Comment by OmerBenGera** [comment]
> > Hello,
> > Happened this morning on b644 : https://pastebin.com/0ZziExS4
> 
> That's a totally different error in a totally different plugin...

This error is not related to the issue.
As @WarnDa said, he only wanted to show that the issue still happens even without the error from before.

**Comment by WarnDa** [comment]
Hello,
Any news, as you updated some things today :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by WarnDa** [comment]
Seems to work, after 2 restarts still no issue : 
> [03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Disabling SuperiorSkyblock2 v1.10.0.651
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module bank...
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module missions...
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module nashorn-engine...
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module generators...
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Disabling the module upgrades...
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Shutting down calculation task...
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Shutting down executor
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Shutting down database executor
[03:49:25] [Server thread/INFO]: [SuperiorSkyblock2] Closing database. This may hang the server. Do not shut it down, or data may get lost.
[03:49:25] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Shutdown initiated...
[03:49:25] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Shutdown completed.

I'll open it again if I got issues :)
