### ISSUE TITLE
Ores generate with basalt generator

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1075]
### Minecraft's Version

Current: git-Purpur-1609 (MC: 1.18.2)

### Plugin's Version

SuperiorSkyblock2 version 1.9.0.595 (Dev build)

### Describe the bug

Ores are generated in a basalt generator, not sure if this is intentional to make it so basalt replaces cobblestone and ores are generated along with the rates

Video: https://streamable.com/5phi1e

### To Reproduce

1. Make a basalt generator with lava flowing into a block that has blue ice on the side and soul soil below
2. Have an island generator upgrade with ores
3. Break the basalt and ores will generate along with basalt

### Additional Information

https://streamable.com/5phi1e

**Comment by OmerBenGera** [comment]
Run `/is admin show` on that island and show me the generator rates that are shown in the message

**Comment by DuneSciFye** [comment]
Island | Iron Ore: 10% (10) ∞
Island | Cobblestone: 30% (30) ∞
Island | Lapis Ore: 8% (8) ∞
Island | Gold Ore: 8% (8) ∞
Island | Copper Ore: 8% (8) ∞
Island | Redstone Ore: 8% (8) ∞
Island | Emerald Ore: 3% (3) ∞
Island | Coal Ore: 20% (20) ∞
Island | Diamond Ore: 5% (5) ∞

**Comment by OmerBenGera** [comment]
Show me a screenshot if possible :)
I want to check the rates of all the worlds

**Comment by DuneSciFye** [comment]
![image](https://user-images.githubusercontent.com/65089425/165816204-29e0ba52-5c99-499b-9151-e1b86be8ca65.png)

**Comment by OmerBenGera** [comment]
You have generator rates in the nether world, so I am not sure what you're reporting here exactly

**Comment by DuneSciFye** [comment]
Did you watch the video? The generator is made in the overworld

**Comment by OmerBenGera** [comment]
> Did you watch the video? The generator is made in the overworld

I understand what you mean here... The rates are coming from the regular generator instead of the nether one. I will make add an option to change it to basalt generators will take rates out of the nether rates all the time, no matter in which world they are running in.

**Comment by DuneSciFye** [comment]
Oh, so that's how you were supposed to make a nether generator.. I installed a water in nether plugin for a traditional cobblestone generator with lava and water in the nether. When making this bug report I thought that the basalt generator was only supposed to generate basalt and nothing else...

**Comment by OmerBenGera** [comment]
> Oh, so that's how you were supposed to make a nether generator.. I installed a water in nether plugin for a traditional cobblestone generator with lava and water in the nether. When making this bug report I thought that the basalt generator was only supposed to generate basalt and nothing else...

The basalt generator has the same rates as vanilla generator. What makes the difference in the rates is the world they are inside, which I can see why it's an issue when using basalt generators. Same as in vanilla that basalt generator still generates basalt, in SSB it should generate nether's rates.
This is a bug to me, and thanks for reporting it :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by DuneSciFye** [comment]
![image](https://user-images.githubusercontent.com/65089425/166084157-eb1fe103-bcff-44f5-8a0a-de0201bc5f32.png)
I now have hundreds of these errors in my console

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/65089425/166084157-eb1fe103-bcff-44f5-8a0a-de0201bc5f32.png) I now have hundreds of these errors in my console

There's no such thing as "NETHERACK" material. Fix your generator rates and make sure you use correct material values.
