### ISSUE TITLE
Player can't create island

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1077]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b609

### Describe the bug

When a player try to create an island, he can teleport to his island, but if he moves, it teleports him to the spawn

### To Reproduce

- create an island
- teleport and move

### Additional Information

https://youtu.be/WFS6Qg5O890

- No issue on b605
- seems to happen only on mysql

**Comment by WarnDa** [comment]
Island do not appear in mysql database :
![image](https://user-images.githubusercontent.com/31826333/165957757-ef34fa4e-7f99-4bff-b6ab-3026e8eb67fc.png)

**Comment by OmerBenGera** [comment]
Look for errors when creating new islands.
Also, use latest dev build, and let me know if it happens on your localhost as well.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
