### ISSUE TITLE
Players can't break near the border

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1078]
### Minecraft's Version

1.18.2

### Plugin's Version

b611

### Describe the bug

Hello, i've one issue with latest version and border, we can interact with block near the border (1 block) https://pics.revolis.fr/2022/04/29/22-27_UBku.mp4 .

### To Reproduce

Try to interact with the nearest block of the border.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
