### ISSUE TITLE
Block limit no longer working for older islands

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1079]
### Minecraft's Version

When trying to add stackable blocks for the Chiseled_stone_bricks block it simply doesn't work.

### Plugin's Version

1.9.0 dev 615

### Describe the bug

Older island have their block limits doubled, for example diamond block limit is at 3500, they can go up to 7000 while newly created island can go up to 3500. 

### To Reproduce

Have an older island before dev build 602 and upgrade to latest dev build with stacked blocks on your island: 

https://gyazo.com/aef2c828cd905601e02c501d1585264b 

### Additional Information

After checking in the database in the island_blocks_limit I cannot find anything to "diamond blocks" 
https://gyazo.com/287f642cd22117403b545ae3752e49ed 

Config: https://gyazo.com/4d891f9085ac74faa7288a57af3a4ec0

**Comment by LuluxClient** [comment]
Tried restarting, /is admin level, /is admin recalc

**Comment by OmerBenGera** [comment]
Check using `/is admin show` if the island has a limit or not.

**Comment by LuluxClient** [comment]
> /is admin show

Sorry for the delay, they indeed do have a limit: https://pastebin.com/Ezgkn8Fk

**Comment by OmerBenGera** [comment]
> > /is admin show
> 
> Sorry for the delay, they indeed do have a limit: https://pastebin.com/Ezgkn8Fk

Weird. What about /is blocks? Do you see the diamond blocks there?

**Comment by LuluxClient** [comment]
> > > /is admin show
> > 
> > 
> > Sorry for the delay, they indeed do have a limit: https://pastebin.com/Ezgkn8Fk
> 
> Weird. What about /is blocks? Do you see the diamond blocks there?

![2022-04-30_17 03 51](https://user-images.githubusercontent.com/62576432/166110938-5a3c2f55-f869-4f65-ac5d-f22cef685757.png)

**Comment by OmerBenGera** [comment]
Are you able to place regular diamond blocks as well, or only stacked blocks can bypass the limit?

**Comment by LuluxClient** [comment]
> Are you able to place regular diamond blocks as well, or only stacked blocks can bypass the limit?

Hmmm weird I can no longer bypass the limit (server didn't restart even tho I restarted 5 times and did every admin command to fix it) looks like it got fixed automatically (weird) I'll close this ticket if I don't receive any report in the next 2-4 days if that's fine

**Comment by OmerBenGera** [comment]
> > Are you able to place regular diamond blocks as well, or only stacked blocks can bypass the limit?
> 
> Hmmm weird I can no longer bypass the limit (server didn't restart even tho I restarted 5 times and did every admin command to fix it) looks like it got fixed automatically (weird) I'll close this ticket if I don't receive any report in the next 2-4 days if that's fine

Sure :)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, lmk by replying
