### ISSUE TITLE
/is toggle blocks are reset when server restart

### ISSUE THREAD

**Issue by SkytraceXLSU** [BG-Software-LLC/SuperiorSkyblock2#1089]
### Minecraft's Version

1.18.2-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2-1.9.0-b607

### Describe the bug

stacked blocks are reset or delete  when server restart just stay the hologram  

### To Reproduce

create different sort of stacked blocks and restart the server

**Comment by OmerBenGera** [comment]
Upgrade, it will get fixed.
