### ISSUE TITLE
Java15/16 is missing the JavaScript engine

### ISSUE THREAD

**Issue by OmerBenGera** [BG-Software-LLC/SuperiorSkyblock2#109]
In Java15, the javascript engine was removed, and it causes issues for people that use the plugin in this version.
For now, I recommend to **not** use Java 15 until a solution is found.
Pull requests are more than welcomed :)

**Comment by superbiebel** [comment]
possible fix: https://www.graalvm.org/reference-manual/js/RunOnJDK/

**Comment by OmerBenGera** [comment]
> 
> 
> possible fix: https://www.graalvm.org/reference-manual/js/RunOnJDK/

This will not work without additional things that customers need to do, therefore I can't really implement that.

**Comment by ElBananaa** [comment]
> possible fix: https://www.graalvm.org/reference-manual/js/RunOnJDK/

If you really wish to take advantage of graalvm, take a look at Java11-graalvm builds : https://github.com/graalvm/graalvm-ce-builds/releases
They are backward compatible with Nashorn, but take advantage of GraalVM in specific circumstances. However, you should consider testing this for at least a week before considering deploying it on your prod server. I personally had crash issues when using it on my test server.

**Comment by OmerBenGera** [comment]
There might be a solution with the new modules system, it's being tested right now.
Stay tuned!

**Comment by OmerBenGera** [comment]
You may use one of the followings:
https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
https://github.com/BG-Software-LLC/SuperiorSkyblock2-RhinoEngine
https://github.com/BG-Software-LLC/SuperiorSkyblock2-GraalVMEngine (If you use this one, make sure you have GraalVM working correctly - use google to find out how to get it working)

**Comment by ElBananaa** [comment]
> You may use one of the followings:
> https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
> https://github.com/BG-Software-LLC/SuperiorSkyblock2-RhinoEngine
> https://github.com/BG-Software-LLC/SuperiorSkyblock2-GraalVMEngine (If you use this one, make sure you have GraalVM working correctly - use google to find out how to get it working)

Hey, I think someone already reported crash issues when using Java-11 GraalVM with the plugin. Is it solved?

**Comment by OmerBenGera** [comment]
> 
> 
> > You may use one of the followings:
> > https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
> > https://github.com/BG-Software-LLC/SuperiorSkyblock2-RhinoEngine
> > https://github.com/BG-Software-LLC/SuperiorSkyblock2-GraalVMEngine (If you use this one, make sure you have GraalVM working correctly - use google to find out how to get it working)
> 
> Hey, I think someone already reported crash issues when using Java-11 GraalVM with the plugin. Is it solved?

There were issues with GraalVM for no reason, not sure why tbh
However, I told them to use the other engines (Nashorn/Rhino) and it worked well for them, so I can say that it got fixed

**Comment by ElBananaa** [comment]
> > > You may use one of the followings:
> > > https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
> > > https://github.com/BG-Software-LLC/SuperiorSkyblock2-RhinoEngine
> > > https://github.com/BG-Software-LLC/SuperiorSkyblock2-GraalVMEngine (If you use this one, make sure you have GraalVM working correctly - use google to find out how to get it working)
> > 
> > 
> > Hey, I think someone already reported crash issues when using Java-11 GraalVM with the plugin. Is it solved?
> 
> There were issues with GraalVM for no reason, not sure why tbh
> However, I told them to use the other engines (Nashorn/Rhino) and it worked well for them, so I can say that it got fixed

Alright, and what about new versions of java? I mean, afaik they'll be compiled with GraalVM only, so there's no way to use Nashorn or Rhino (And tbho, I feel like usign these engines in the latest versions would be kinda stupid since the most important improvement is the fact that they're switching to GraalVM. Was this issue only related to Java11-GraalVM?

**Comment by OmerBenGera** [comment]
> > > > You may use one of the followings:
> > > > https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine
> > > > https://github.com/BG-Software-LLC/SuperiorSkyblock2-RhinoEngine
> > > > https://github.com/BG-Software-LLC/SuperiorSkyblock2-GraalVMEngine (If you use this one, make sure you have GraalVM working correctly - use google to find out how to get it working)
> > > 
> > > 
> > > Hey, I think someone already reported crash issues when using Java-11 GraalVM with the plugin. Is it solved?
> > 
> > 
> > There were issues with GraalVM for no reason, not sure why tbh
> > However, I told them to use the other engines (Nashorn/Rhino) and it worked well for them, so I can say that it got fixed
> 
> Alright, and what about new versions of java? I mean, afaik they'll be compiled with GraalVM only, so there's no way to use Nashorn or Rhino (And tbho, I feel like usign these engines in the latest versions would be kinda stupid since the most important improvement is the fact that they're switching to GraalVM. Was this issue only related to Java11-GraalVM?

The issue with GraalVM is on their side probably. You will be able to use any of these engines, and it wont affect performance as there are only simple checks done.
