### ISSUE TITLE
blocked-cmd issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1091]
### Minecraft's Version

paper 1.17.1

### Plugin's Version

b625

### Describe the bug

If you set "blocked-visitors-commands:", then you can't use theses messages even in command like /msg

### To Reproduce

- Add commands to blocked-visitors-commands:
- Ask a visitor on your island to "/msg" someone with the command name inside the msg
- it will tell you not to run this commande

### Additional Information

Without anything in blocked-visitors-commands:
![Screenshot_398](https://user-images.githubusercontent.com/31826333/166161673-7ada9e58-40ea-46ac-a75e-d7f4c78dea27.png)

with : 

> blocked-visitors-commands:
> - test
> - hello

![Screenshot_399](https://user-images.githubusercontent.com/31826333/166161689-bef20b45-4d63-425c-bb31-51c408d9a9c8.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
