### ISSUE TITLE
Fisherman mission problem

### ISSUE THREAD

**Issue by Ramcin00** [BG-Software-LLC/SuperiorSkyblock2#1093]
### Minecraft's Version

1.18.2

### Plugin's Version

Latest

### Describe the bug

SuperiorSkyblock, mission module, fisherman category. 
Throwing items into the water (eg books) and then fishing with a fishing rod counts them as part of the mission.

### To Reproduce

Create a fisherman mission in which you have to fish out an item, e.g. a book, then throw it into the water and fish it with a fishing rod, the progress will be counted

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
