### ISSUE TITLE
Can't reset world

### ISSUE THREAD

**Issue by BorcheP** [BG-Software-LLC/SuperiorSkyblock2#1098]
### Minecraft's Version

1.17.1

### Plugin's Version

1.10.0

### Describe the bug

I can't reset the world

### To Reproduce

Ingame screenshot:
https://prnt.sc/KRQQyKnI1svd

Config screneshot:
https://prnt.sc/RUdE1ZHzSOe_

**Comment by OmerBenGera** [comment]
Why would you reset the world for all the islands?!
If you want to start over, delete the world files and delete the database.

**Comment by BorcheP** [comment]
Well I guess that answers my confusion, thanks xd
