### ISSUE TITLE
Database automatic conversion

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1099]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/84990628/166743947-1e47544c-bf70-4f04-923a-6d848efd2a65.png)

### Plugin's Version

![image](https://user-images.githubusercontent.com/84990628/166744180-76415914-6df4-4470-85b1-ab2680ef7a01.png)

### Describe the bug

when doing automatic DB convert from version of superior SuperiorSkyblock2-b104 the jar it self in the zip
[SuperiorSkyblock2-b104.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8624702/SuperiorSkyblock2-b104.zip)
it gives me error when trying to convert island
https://pastebin.com/S1FR9FzJ
![image](https://user-images.githubusercontent.com/84990628/166743869-d97c7ed8-f127-4b0e-ad19-ea558adf261e.png)

### To Reproduce

have mysql database with version SuperiorSkyblock2-b104
create island stop the server and update superior skyblock to latest version as of writing this 
https://bg-software.com/downloads/SuperiorSkyblock2-1.10.0.jar
turn on the server and it will give the following error
https://pastebin.com/qUTaDHry

### Additional Information

tried it with default configs as well same thing

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build
Let me knwo if it works for you

**Comment by dan28000** [comment]
Yep seems fine - works

**Comment by dan28000** [comment]
also forgot after working conversion it spams the console with 
[21:49:57] [Server thread/INFO]: [SuperiorSkyblock2] Cannot load island missions with invalid mission  for (player uuid), skipping...
in DB island missions when the field with name is blank it does it

**Comment by dan28000** [comment]
also forgot after working conversion it spams the console with 
[21:49:57] [Server thread/INFO]: [SuperiorSkyblock2] Cannot load island missions with invalid mission  for (player uuid), skipping...
in DB island missions when the field with name is blank it does it

**Comment by OmerBenGera** [comment]
> also forgot after working conversion it spams the console with [21:49:57] [Server thread/INFO]: [SuperiorSkyblock2] Cannot load island missions with invalid mission for (player uuid), skipping... in DB island missions when the field with name of missions is blank then it throws this warning

Did it happen when you converted the db, or does it happen after you start the server again?

**Comment by dan28000** [comment]
It converts islands without any mission completed so after conversion it throws that error

**Comment by OmerBenGera** [comment]
> It converts islands without any missions completed so after conversion it throws that error

So just to understand - inside the database, there are no completed missions at all?

**Comment by dan28000** [comment]
nono before convert there are islands with no mission complete 


example

- before conversion
- everything is fine

- island 1 mission x completed
- island 2 no mission completed

- after conversion
- island 1 mission x completed - fine
- island 2 no mission completed - blank mission = invalid mission error


after conversion it converts the insland without any mission complete as well as the others and those blank missions spit out the invalid mission error

**Comment by OmerBenGera** [comment]
> nono before convert there are islands with no mission complete
> 
> example
> 
> * before conversion
> * everything is fine
> * island 1 mission x completed
> * island 2 no mission completed
> * after conversion
> * island 1 mission x completed - fine
> * island 2 no mission completed - blank mission = invalid mission error
> 
> after conversion it converts the insland without any mission complete as well as the others and those blank missions spit out the invalid mission error

I understand now.
Mind showing me how the blank mission is shown in the database? (A screenshot will help)

**Comment by dan28000** [comment]
i would need to turn on my server where i have my testing DB but the name field that contains the name of completed mission its blank there's no text = the island that didn't had any mission completed

**Comment by dan28000** [comment]
before
![image](https://user-images.githubusercontent.com/84990628/167146472-0abf37bb-7159-40bb-90ff-e523451217d8.png)

after
![image](https://user-images.githubusercontent.com/84990628/167146589-2cb9c865-80fc-4d35-9def-f4a6734b1042.png)

hope this is enough

**Comment by OmerBenGera** [comment]
About the warning you have, it's only a warning, right?
Everything works fine

**Comment by dan28000** [comment]
yea it's a warning but if you have like over 5k of lines of this warning in a logs then it's annoying

**Comment by OmerBenGera** [comment]
> yea it's a warning but if you have like over 5k of lines of this warning in a logs then it's annoying

Yeah, of course.
I am looking into fixing it rn.

However, you'll need to manually delete the faulty lines yourself by executing a sql command. The fix will be that converting the missions will not make these empty names.

**Comment by OmerBenGera** [comment]
`DELETE FROM islands_missions WHERE mission=''`

I don't take any responsibility for any data lose that may occur if you run SQL commands and somehow break the database, so do so in caution.

**Comment by dan28000** [comment]
I will be doing the conversion agine when i will finish the update so I want this out of the way

**Comment by OmerBenGera** [comment]
> I will be doing the conversion agine when i will finish the update so I want this out of the way

What about data that was created after the migration? It will not exist anymore if you migrate again

**Comment by OmerBenGera** [comment]
Let me know if you encounter any more issues

**Comment by dan28000** [comment]
seems that it works fine
