### ISSUE TITLE
Item limit error when mine cart is cleared by ClearLag

### ISSUE THREAD

**Issue by mk9395** [BG-Software-LLC/SuperiorSkyblock2#1102]
### Minecraft's Version

1.18.2

### Plugin's Version

SuperiorSkyblock2-1.9.0.jar

### Describe the bug

The problem occurred when the Clearlag remove Minecart plugin resulted in an item limit error (hopper)

### To Reproduce

I have 8 hopper limit on the island, and I only placed 7 hoppers with 1 minecart hopper, clearlag clears every 10 minutes and deletes minecart hopper too, and player cannot order 1 more hopper even though minecart hopper has been cleared.

**Comment by OmerBenGera** [comment]
Install Paper and it will be fixed.
Also, update to latest build of the plugin.
