### ISSUE TITLE
is delwarp error 2

### ISSUE THREAD

**Issue by xBeratE** [BG-Software-LLC/SuperiorSkyblock2#1105]
### Minecraft's Version

1.17.1 airplane

### Plugin's Version

1.10.0

### Describe the bug

You wrote that the problem was fixed, but when I updated the add-on and tried it, it gave an error again. Island warps are not deleted and this error comes to the console. 

### To Reproduce

/is delwarp warp name

### Additional Information

https://mclo.gs/w9F9YAF

**Comment by OmerBenGera** [comment]
Update the plugin to latest dev build, the issue is already been fixed.
