### ISSUE TITLE
Mission progression

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1108]
### Minecraft's Version

1.18.2

### Plugin's Version

b639

### Describe the bug

Hello, the mission progression still reset sometimes after restart.

### To Reproduce

Idk exactly but sometimes after reset all my players lose the current progression of island quest.

**Comment by nivcoo** [comment]
Before restart the data file is correct but after he's reset

**Comment by OmerBenGera** [comment]
I need much more information than that.
Look when it happens, how to replicate it, etc.

**Comment by nivcoo** [comment]
Idk but actually my file is 350mb

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Hey, after we have sorted the other issue, we can work on this one.
Does this still happens on latest version?

Latest version has separate data files for different missions, which might have fixed the issue.
Let me know.
