### ISSUE TITLE
Player without island can't speak

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1109]
### Minecraft's Version

1.17.1 pufferfish

### Plugin's Version

b635

### Describe the bug

Player without island can't speak, it makes an error in console (and player do not receive any error) : 
https://pastebin.com/bkhKxVEd

### To Reproduce

delete your island and speak

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
