### ISSUE TITLE
Other Island remove is level

### ISSUE THREAD

**Issue by NewZAZ** [BG-Software-LLC/SuperiorSkyblock2#1113]
### Minecraft's Version

Purpur 1.18.1

### Plugin's Version

1.10.0

### Describe the bug

When player create nether portal and create nether island, they lost 500K island level and when i set schematic-offset true to false recalculate not work

### To Reproduce

Just create nether portal and go on

### Additional Information

https://pastebin.com/frU5mhxV

**Comment by OmerBenGera** [comment]
> ### Minecraft's Version
> Purpur 1.18.1
> 
> ### Plugin's Version
> 1.10.0
> 
> ### Describe the bug
> When player create nether portal and create nether island, they lost 500K island level and when i set schematic-offset true to false recalculate not work
> 
> ### To Reproduce
> Just create nether portal and go on
> 
> ### Additional Information
> https://pastebin.com/frU5mhxV

When you have offset set to true, the island will have a bonus of the value of blocks in the schematic, but the negative of it. Therefore, if players break the blocks of the schematic itself, their level will go down.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If it still have issues, lmk by replying to this issue
