### ISSUE TITLE
Cactus in Farming Missions does not always count correctly

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#1123]
### Minecraft's Version

1.18.2 Purpur dev 1623

### Plugin's Version

SSB-642

### Describe the bug

Cactus does not count when breaking cactus grown, it seems like it may want the cactus to fully grow first?

### To Reproduce

Place a cactus, let it grow one block, then see if it counts.

### Additional Information

https://youtu.be/_1HPPFLMAW8

**Comment by OmerBenGera** [comment]
Upload the mission to pastebin and send it here.

**Comment by OmerBenGera** [comment]
It doesn't seem to occur for me anymore, try updating to latest dev build - let me know if it still occurs for you

**Comment by Skizzles** [comment]
> Any news regarding this?

Still happening
![image](https://user-images.githubusercontent.com/30563757/172292009-415b4949-1fee-41e6-a7d6-d99685127149.png)

**Comment by Tomi0928** [comment]
I have the same problem but i dont know what's causing this, i have this problem with every mission

**Comment by Skizzles** [comment]
> Any news regarding this?

This is still happening on the current version of SSB.

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> Still happening ![image](https://user-images.githubusercontent.com/30563757/172292009-415b4949-1fee-41e6-a7d6-d99685127149.png)

This is an intended behavior.
FarmingMissions will count progress when **a plant grows**, not when it's broken. Therefore, the plant must be placed by the player - the mission tracks which crops were planted by players and then when they grow, they increase the progress for these crops.

**Comment by OmerBenGera** [comment]
@Skizzles Any news regarding this?

**Comment by Skizzles** [comment]
> @Skizzles Any news regarding this?

This is regarding the blocks mission not farming.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now
There was an issue with how blocks are tracked and caused the wrong blocks to be tracked, might have been related to that.
