### ISSUE TITLE
data of missions

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1124]
### Minecraft's Version

1.16.5 yatopia 

### Plugin's Version

SuperiorSkyblock2-1.10.0-b642

### Describe the bug

when updating from build 104 to 642 when converting DB I forgot to swap the mission progress file 
I don't know if it would do anything in the conversion process but after realising this I put the old data file with progress of the players back started the server and after few hours noticed that the tps were like in range of 5 due to missions so i restarted the server and removed the mission data file _data.yml after that the tps were fine
from that restart where i removed the old file with data the new file is empty

with just 11 pistons pushing block in 2 tick loop the mspt went from idle 6,5 to 32,5
![image](https://user-images.githubusercontent.com/84990628/168294588-c4fd7ed3-caba-41cc-8cda-7d574eac6da6.png)

### To Reproduce

not really sure how to reproduce but my guess is that block missions were searching that file thus lagging like a hell the server

### Additional Information

file before from 104 build
[_data.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8688284/_data.txt)
the file after running server for like 2 hours
[_data-new.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8688287/_data-new.txt)

**Comment by dan28000** [comment]
but got another problem looking at the wiki and can't figure out how to setup a nether generator currently it doens't work at all

**Comment by OmerBenGera** [comment]
> but got another problem looking at the wiki and can't figure out how to setup a nether generator currently it doens't work at all we have seperates upgrades for each

Try asking on discord for help with that.
I am closing this for now
