### ISSUE TITLE
0.X value on config for generator doesn't work

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1125]
### Minecraft's Version

Current: git-Purpur-1565 (MC: 1.18.1)*
Previous: git-Pufferfish-47 (MC: 1.18.1)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

1.10.0.642

### Describe the bug

When i put a 0.X value on config, for generator upgrade, this block never spawn.

I have try it with ANCIENT_DEBRIS with 0.3 & 0.8% and he doesn't work.
1% is too much for this item ^^.

### To Reproduce

Put any block on your config with 0.X format. And try to got it on generator.

**Comment by OmerBenGera** [comment]
You don't configure percentages in the config file, you configure rates.
The percentage is calculated as the rate you configured divided by the total rates. Therefore, if you configure only stone to have 1 as its rate, it will be 100%. However, if you add dirt with a rate of 4, for example, the percentage of stone would be 20% (`1 / (1 + 4) = 0.2`). You can see these calculation results ingame by typing `/is admin show`.

Not a bug.
