### ISSUE TITLE
/is admin resetworld * normal retiurns Error | Invalid world normal.

### ISSUE THREAD

**Issue by MHanak1** [BG-Software-LLC/SuperiorSkyblock2#1126]
### Minecraft's Version

Paper Version git-Paper-408 (MC:1.17.1) (Implementating API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)

### Plugin's Version

Superiorskyblock2 version 1.10.0

### Describe the bug

world normal is not recognized as a valid world type

### To Reproduce

enter command **/is admin resetworld \* normal**

### Additional Information

i have deleted SuperiorWorld folder in attempt to delete all the islands

**Comment by OmerBenGera** [comment]
You can't reset the default world.
