### ISSUE TITLE
nether generators

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1127]
### Minecraft's Version

1.16.5 yatopia

### Plugin's Version

b642

### Describe the bug

Firstly I know this should be more into discussion but i need an option to disable check in nether generators for soul soil when i updated from b104 to b642 now the soul soil is needed but my players don't want to rebuild their generators because they have using this for over a year

### To Reproduce

https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/7e0d6f0050647e4c2aeb09d95298e282c25a91db
this is the commit for it

**Comment by OmerBenGera** [comment]
This is how the nether generators work in minecraft. You can get another plugin to change this.
