### ISSUE TITLE
Spawner rate upgrade doesn't work with RoseStacker 

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1128]
### Minecraft's Version

Current: git-Purpur-1565 (MC: 1.18.1)*
Previous: git-Pufferfish-47 (MC: 1.18.1)
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

1.10.0.642

### Describe the bug

When players improve the spawn rate of spawners, it only works once and does not apply to all spawns.

### To Reproduce

1. Use my config on additionnal information
2. Use RoseStacker (Version 1.4.7)
3. check the shift click on spawner and look the spawn tick

Vidéo which describe the bug here : https://www.youtube.com/watch?v=wUPYO_g6ry8

On this video, we can see a normal tick rate without boost of upgrade. After you can see an good update (200 -> 50 instanlty), and after he go again normally without boost, but i have the upgrade.

### Additional Information

`  spawner-rates:
    '1':
      price: 800000.0
      spawner-rates: 1
      commands:
      - island admin setupgrade %player% spawner-rates 2
      - island admin msgall %player% &x&4&D&E&4&5&3&lAméliorations &7◆ &fVotre taux de &x&4&D&E&4&5&3spawn de monstres &fest maintenant à &x&4&D&E&4&5&3x2 &f!
      permission: superior.island.*
    '2':
      price: 1000000.0
      spawner-rates: 2
      commands:
      - island admin setupgrade %player% spawner-rates 3
      - island admin msgall %player% &x&4&D&E&4&5&3&lAméliorations &7◆ &fVotre taux de &x&4&D&E&4&5&3spawn de monstres &fest maintenant à &x&4&D&E&4&5&3x3 &f!
      permission: superior.island.*
    '3':
      price: 0.0
      spawner-rates: 4
      commands:
      - island admin msg %player% &x&4&D&E&4&5&3&lAméliorations &7◆ &fVotre taux de &x&4&D&E&4&5&3spawn de monstres &fest maintenant à &x&4&D&E&4&5&3x4 &f!
      permission: superior.island.*`

**Comment by OmerBenGera** [comment]
Report it to RoseStacker then. Not related to SSB in any way.
