### ISSUE TITLE
Cannot join island after being invited

### ISSUE THREAD

**Issue by TehPigYT** [BG-Software-LLC/SuperiorSkyblock2#1129]
### Minecraft's Version

Server Version: 1.16.5
Download: https://serverjars.com/more/purpur

(I was not able to upload the jar)

### Plugin's Version

Plugin Version: 1.10.0-b646
Download: https://bg-software.com/superiorskyblock/

(I was not able to upload the jar)

### Describe the bug

After adding the plugin to the server and creating an island, I invited one of my friends to it using `/is invite Player` (replace Player with actual username). Everything was alright after a normal restart happened. Once I joined back, my friend was still on the island, but it was saying that "This island is protected" even though my friend normally had access to it. I tried reinviting them and after they accepted, they used the `/is` command to teleport to the island. But instead, it was saying that they had to create an island and did not get teleported to my island. They tried creating a new island and deleting it. After that I invited them to my island again but the issue was still there.

### To Reproduce

I think everything happened after creating an island with `/is`, inviting another player to it and then restarting the server.
I don't exactly know what happened in background but I was hoping to find a solution for this issue.

### Additional Information

https://www.mediafire.com/file/77dgyigdiwatcmd/Additional_Files.zip/file

There is the config file and a video showing the issue.

**Comment by OmerBenGera** [comment]
Reset the db file and let me know if you can replicate the issue.

**Resetting the db means all islands and players data will be lost**

**Comment by TehPigYT** [comment]
But why would I have to reset the db file for this to be fixed?

**Comment by OmerBenGera** [comment]
> But why would I have to reset the db file for this to be fixed?

To check if it happens again.
You can also try replicate it on another server and lmk if it still occurs.

**Comment by TehPigYT** [comment]
Same issue happens.

**Comment by TehPigYT** [comment]
I completely wiped the database, restarted the server, created an island, invited my friend to it, they accepted it, I restarted the server and they still see the "You have no island error".

**Comment by OmerBenGera** [comment]
Send me logs of the two sessions - the one before you restart and the one after that.

**Comment by TehPigYT** [comment]
What exactly do you need from the logs?

**Comment by OmerBenGera** [comment]
Do you have an island mission that listens to IslandSchematicPasteEvent?

**Comment by OmerBenGera** [comment]
Any news regarding this?
