### ISSUE TITLE
Listener cause lags

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#1130]
### Minecraft's Version

1.18.2

### Plugin's Version

b646

### Describe the bug

Hello, look the spark https://spark.lucko.me/dIiRkEDXml you have fixed the pistons performance issue but like you can see, i've performance issue with Entity spawn and StackedBlock. (1.6% for Entity and 0.6 for stacked block).

If you can fix that i think the plugin will be well optimized. Thx

### To Reproduce

Use SS2 with players.

**Comment by OmerBenGera** [comment]
About the entities; there's no much that can be optimized there.
About the stacked blocks; why do you have physics listener enabled for stacked blocks in the config file? Is there a reason you enabled it?

**Comment by WarnDa** [comment]
> About the entities; there's no much that can be optimized there.

Sad that you can't optimise more, for me it's also the things that consume the most (60-70% of superior's consumption in spark)

**Comment by nivcoo** [comment]
I no longer remember why i've enabled the physics listener, i think it's because i've sponge in stacker and if i disable the feature and place water against the sponge it will create wet sponge and remove the stacker

**Comment by OmerBenGera** [comment]
> > About the entities; there's no much that can be optimized there.
> 
> Sad that you can't optimise more, for me it's also the things that consume the most (60-70% of superior's consumption in spark)

Upload a spark.

**Comment by OmerBenGera** [comment]
> I no longer remember why i've enabled the physics listener, i think it's because i've sponge in stacker and if i disable the feature and place water against the sponge it will create wet sponge and remove the stacker

Stacked blocks should not transform into wet sponges.
If they do, open a separate issue regarding this.

**Comment by nivcoo** [comment]
So, look this issue https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/97, why do you say to me to turn on this feature if it's not linked with sponge issue ?

**Comment by WarnDa** [comment]
> > > About the entities; there's no much that can be optimized there.
> > 
> > 
> > Sad that you can't optimise more, for me it's also the things that consume the most (60-70% of superior's consumption in spark)
> 
> Upload a spark.

Already do on the other ticket that you closed

**Comment by nivcoo** [comment]
Ok it's why i've activated this issue, before i used ss2 in 1.12, so now i can disable that

> So, look this issue #97, why do you say to me to turn on this feature if it's not linked with sponge issue ?

**Comment by WarnDa** [comment]
![image](https://user-images.githubusercontent.com/31826333/169621887-cff86764-f883-44c3-be9c-fc53c980a40e.png)
https://spark.lucko.me/Juf9HyGF7t

**Comment by OmerBenGera** [comment]
> So, look this issue #97, why do you say to me to turn on this feature if it's not linked with sponge issue ?

I told you its fixed on versions above 1.13, but if you dont use 1.13 or above, enable it. You are using 1.18 and therefore you should not enable it.

**Comment by OmerBenGera** [comment]
I will look into optimizing it in a future update.
For now, I am keeping this opened :)

**Comment by OmerBenGera** [comment]
Have you checked recent versions?
There should be improvements - let me know what you think.

**Comment by nivcoo** [comment]
I will try it thx

**Comment by OmerBenGera** [comment]
@nivcoo Have you tried it?

**Comment by nivcoo** [comment]
I think it works :p

**Comment by OmerBenGera** [comment]
Great.
If you encounter lags again, let me know
