### ISSUE TITLE
[API] "com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.plugin" is null

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#1133]
### Minecraft's Version

1.18.2 (paper)

### Plugin's Version

latest dev build and API 1.10.0

### Describe the bug

I have this error

`java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.SuperiorSkyblock.getProviders()" because "com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.plugin" is null`

I can't init SuperiorSkyblockAPI.plugin to my plugin.

I already add the softdepend [SuperiorSkyblock2].

### To Reproduce

Main function onEnable: 
` 
        hookSuperiorSkyblock(this);
        SuperiorSkyblockAPI.getProviders();
        `

function hookSuperiorSkyblock()
`    private void hookSuperiorSkyblock(Plugin plugin) {
        for(RegisteredListener listener : HandlerList.getRegisteredListeners(Bukkit.getPluginManager().getPlugin("SuperiorSkyblock2"))) {
            try {
                if(listener.getListener().getClass() == Class.forName("com.bgsoftware.superiorskyblock.module.generators.listeners.GeneratorsListener")){
                    HandlerList.unregisterAll(listener.getListener());
                    plugin.getLogger().info(String.format("%s: Unregistered inbuilt-generator from Plugin (%s) to use this one", this.getClass().getSimpleName(), listener.getListener().getClass().getName()));
                }
            } catch (ClassNotFoundException e) {
                plugin.getLogger().warning(String.format("%s: Generator class for inbuilt-generator not found (%s)", this.getClass().getSimpleName(), listener.getListener().getClass().getName()));
            }
        }
    }`

My pom.xml

`        <dependency>
            <groupId>com.bgsoftware</groupId>
            <artifactId>SuperiorSkyblockAPI</artifactId>
            <version>1.10.0</version>
        </dependency>`

Thank you very much !

**Comment by OmerBenGera** [comment]
SSB sets the instance when plugin loads, and this field cant be null unless you access it before its initialized.

**Comment by OmerBenGera** [comment]
I added a null check for the API instance.
Try using latest dev build, let me know what happens

**Comment by Teyir** [comment]
I have the same issue @OmerBenGera 

![image](https://user-images.githubusercontent.com/60007549/169657954-6943d2d1-870c-4732-bd79-17d3cc768892.png)

**Comment by OmerBenGera** [comment]
> I have the same issue @OmerBenGera
> 
> ![image](https://user-images.githubusercontent.com/60007549/169657954-6943d2d1-870c-4732-bd79-17d3cc768892.png)

Send me your entire logs (Upload them to pastebin)

**Comment by Teyir** [comment]
For sure !
→ https://pastebin.com/ft8pGv0g

**Comment by OmerBenGera** [comment]
> For sure ! → https://pastebin.com/ft8pGv0g

Mind showing me the entire code and how you use the API?

**Comment by Teyir** [comment]
> 

My bad @OmerBenGera, this is the good log*

→ https://pastebin.com/JMT6T6Qk

**Comment by Teyir** [comment]
> > For sure ! → https://pastebin.com/ft8pGv0g
> 
> Mind showing me the entire code and how you use the API?

File (sgUtiles.java)
`                        if(userUtils.getIsLevel(player).compareTo(BigDecimal.valueOf(Integer.parseInt(value))) >= 0){
                            Bukkit.broadcastMessage("Is level good");
                        }`
                        
File (userUtils.java)

`    public static BigDecimal getIsLevel(Player player){
        return SuperiorSkyblockAPI.getPlayer(player.getUniqueId()).getIsland().getIslandLevel();
    }`



> > For sure ! → https://pastebin.com/ft8pGv0g
> 
> Mind showing me the entire code and how you use the API?

> > For sure ! → https://pastebin.com/ft8pGv0g
> 
> Mind showing me the entire code and how you use the API?

File (sgUtiles.java)
`                        if(userUtils.getIsLevel(player).compareTo(BigDecimal.valueOf(Integer.parseInt(value))) >= 0){
                            Bukkit.broadcastMessage("Is level good");
                        }`
                        
File (userUtils.java)

`    public static BigDecimal getIsLevel(Player player){
        return SuperiorSkyblockAPI.getPlayer(player.getUniqueId()).getIsland().getIslandLevel();
    }`

**Comment by OmerBenGera** [comment]
> > > For sure ! → https://pastebin.com/ft8pGv0g
> > 
> > 
> > Mind showing me the entire code and how you use the API?
> 
> File (sgUtiles.java) ` if(userUtils.getIsLevel(player).compareTo(BigDecimal.valueOf(Integer.parseInt(value))) >= 0){ Bukkit.broadcastMessage("Is level good"); }`
> 
> File (userUtils.java)
> 
> ` public static BigDecimal getIsLevel(Player player){ return SuperiorSkyblockAPI.getPlayer(player.getUniqueId()).getIsland().getIslandLevel(); }`
> 
> > > For sure ! → https://pastebin.com/ft8pGv0g
> > 
> > 
> > Mind showing me the entire code and how you use the API?
> 
> > > For sure ! → https://pastebin.com/ft8pGv0g
> > 
> > 
> > Mind showing me the entire code and how you use the API?
> 
> File (sgUtiles.java) ` if(userUtils.getIsLevel(player).compareTo(BigDecimal.valueOf(Integer.parseInt(value))) >= 0){ Bukkit.broadcastMessage("Is level good"); }`
> 
> File (userUtils.java)
> 
> ` public static BigDecimal getIsLevel(Player player){ return SuperiorSkyblockAPI.getPlayer(player.getUniqueId()).getIsland().getIslandLevel(); }`

I have no clue why it happens.
Does it occur if you only have SSB and your plugin installed on your server?
Also, do you have SSB as a soft depend?

**Comment by Teyir** [comment]
Yes !

![image](https://user-images.githubusercontent.com/60007549/169658952-6e8d6595-c202-4f83-b9df-b897a6fcbbfa.png)

**Comment by Teyir** [comment]
> 
> I have no clue why it happens. Does it occur if you only have SSB and your plugin installed on your server? Also, do you have SSB as a soft depend?

And if you want this is my depend
![image](https://user-images.githubusercontent.com/60007549/169658998-d503810c-b064-454c-b626-50d472e2889a.png)

**Comment by OmerBenGera** [comment]
> > I have no clue why it happens. Does it occur if you only have SSB and your plugin installed on your server? Also, do you have SSB as a soft depend?
> 
> And if you want this is my depend ![image](https://user-images.githubusercontent.com/60007549/169658998-d503810c-b064-454c-b626-50d472e2889a.png)

Mind sending me a copy of your plugin?
I will try to replicate it on my localhost and maybe better understand why it happens

**Comment by Teyir** [comment]
> > > I have no clue why it happens. Does it occur if you only have SSB and your plugin installed on your server? Also, do you have SSB as a soft depend?
> > 
> > 
> > And if you want this is my depend ![image](https://user-images.githubusercontent.com/60007549/169658998-d503810c-b064-454c-b626-50d472e2889a.png)
> 
> Mind sending me a copy of your plugin? I will try to replicate it on my localhost and maybe better understand why it happens

If you want (in pm Discord)

**Comment by OmerBenGera** [comment]
> > > > I have no clue why it happens. Does it occur if you only have SSB and your plugin installed on your server? Also, do you have SSB as a soft depend?
> > > 
> > > 
> > > And if you want this is my depend ![image](https://user-images.githubusercontent.com/60007549/169658998-d503810c-b064-454c-b626-50d472e2889a.png)
> > 
> > 
> > Mind sending me a copy of your plugin? I will try to replicate it on my localhost and maybe better understand why it happens
> 
> If you want (in pm Discord)

What's your discord? I will open a ticket for you

**Comment by Teyir** [comment]
> > > > > I have no clue why it happens. Does it occur if you only have SSB and your plugin installed on your server? Also, do you have SSB as a soft depend?
> > > > 
> > > > 
> > > > And if you want this is my depend ![image](https://user-images.githubusercontent.com/60007549/169658998-d503810c-b064-454c-b626-50d472e2889a.png)
> > > 
> > > 
> > > Mind sending me a copy of your plugin? I will try to replicate it on my localhost and maybe better understand why it happens
> > 
> > 
> > If you want (in pm Discord)
> 
> What's your discord? I will open a ticket for you

Teyir#4439

**Comment by OmerBenGera** [comment]
After looking at your jar, I can clearly see what the issue is.
You are shading SSB's API into your jar. Therefore, even tho you use SSB's API methods, you aren't actually using them, but you use a version of your own of the API, as can be seen in the picture below:
https://gyazo.com/525721bdcf5c8eef99b56b584e2cc85f

Make sure you don't shade the API into your jar, and only have it on runtime.
Let me know if it fixes the issue

**Comment by Teyir** [comment]
Oh I have make a mistake with my maven....

Sorry for this "issue"
