### ISSUE TITLE
Can't /is delwarp [name]

### ISSUE THREAD

**Issue by BorcheP** [BG-Software-LLC/SuperiorSkyblock2#1135]
### Minecraft's Version

1.17.1

### Plugin's Version

1.10.0

### Describe the bug

Whenever someone tries to /is delwarp [name] it shows an error.

### To Reproduce

I don't know when this became an issue, might have been from the start but no one noticed I guess.

### Additional Information

Here's a pastebin of what appears in console when I try to execute the command.
https://pastebin.com/2Vr0w3c6

**Comment by OmerBenGera** [comment]
Update to latest dev build
