### ISSUE TITLE
Errors thrown on /is create

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#1136]
### Minecraft's Version

1.18.2 Purpur dev 1623

### Plugin's Version

SSB-642

### Describe the bug

On /is create errors are thrown.

### To Reproduce

https://paste.skizzles.me/exurokasod.md

**Comment by OmerBenGera** [comment]
The server "died" (lag) because of Slimefun hook.
They already know that this method is laggy and told us they will add a better system; they have yet to do it and I cant do anything regarding this.

**Comment by Skizzles** [comment]
@OmerBenGera can you add a way to toggle the hook at least? Because id rather the blocks not clear than have my server crash on nearly every island creation.

**Comment by OmerBenGera** [comment]
I added the ability to disable hooks.
Check out latest dev build :)

**Comment by Skizzles** [comment]
> I added the ability to disable hooks. Check out latest dev build :)

Does this just disable the removing of blocks or does it disable block protection, removing of blocks, and everything else?

**Comment by OmerBenGera** [comment]
> > I added the ability to disable hooks. Check out latest dev build :)
> 
> Does this just disable the removing of blocks or does it disable block protection, removing of blocks, and everything else?

It completely disables the hook.

**Comment by Skizzles** [comment]
> > > I added the ability to disable hooks. Check out latest dev build :)
> > 
> > 
> > Does this just disable the removing of blocks or does it disable block protection, removing of blocks, and everything else?
> 
> It completely disables the hook.

Is it possible to add an option purely for the removing of blocks? Since the protection is needed.

**Comment by OmerBenGera** [comment]
I removed it in latest dev build.
