### ISSUE TITLE
Mobs spawned with SSB schematics are invincible

### ISSUE THREAD

**Issue by Katakalysm** [BG-Software-LLC/SuperiorSkyblock2#1137]
### Minecraft's Version

purpur 1.18.2 dev 1623

### Plugin's Version

ssb 646

### Describe the bug

Once a player unlocked the nether, 2 piglins spawned with the schematics that were completely invincible and did not die when taking damage, as seen in this video: https://www.youtube.com/watch?v=B_9cZeNJVCY

### To Reproduce

Have mobs in a schematic, and spawn them with it

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
Seems resolved with later builds
