### ISSUE TITLE
1.12.2 island map save Serious bug

### ISSUE THREAD

**Issue by p82183645** [BG-Software-LLC/SuperiorSkyblock2#1139]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/5382252/169185634-00b00dec-bef4-4987-9249-055f3708f5c5.png)

### Plugin's Version

SuperiorSkyblock2-1.10.0-b646

### Describe the bug

The latest version is on 1.12.2, can't save sky island 

Create island > restart server > can't go back to island > Sky island be remove

### To Reproduce

Create island > restart server > can't go back to island > Sky island be remove

**Comment by OmerBenGera** [comment]
Does it happen on another server with only SSB installed?

**Comment by p82183645** [comment]
> Does it happen on another server with only SSB installed?

yes , i have test

**Comment by OmerBenGera** [comment]
I can't replicate the issue. Tried it on a server on version:
```
This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

**Comment by p82183645** [comment]
> 

1. is create test
2. spawn world  (leave island area)
3. stop server
4. start server
5. /is ,  can't back to island  ,  island Disappeared

**Comment by p82183645** [comment]
can fix this?

**Comment by Dot0420** [comment]
I'm having the same problem 

After you create an island, close the server and reopen the server, it says there are no safe blocks on the island and does not move to the island

version : paper-1.12.2-1620

**Comment by OmerBenGera** [comment]
> I'm having the same problem
> 
> After you create an island, close the server and reopen the server, it says there are no safe blocks on the island and does not move to the island
> 
> version : paper-1.12.2-1620

Upload logs of the session where you create the island and send it here please

**Comment by OmerBenGera** [comment]
> I'm having the same problem
> 
> After you create an island, close the server and reopen the server, it says there are no safe blocks on the island and does not move to the island
> 
> version : paper-1.12.2-1620

Upload logs of the session where you create the island and send it here please

**Comment by andriycraft** [comment]
same issue

**Comment by OmerBenGera** [comment]
> same issue

I couldn't replicate the issue.
Are you able to replicate it on another server with only SSB installed?

**Comment by andriycraft** [comment]
yes

**Comment by Dot0420** [comment]
> > I'm having the same problem
> > After you create an island, close the server and reopen the server, it says there are no safe blocks on the island and does not move to the island
> > version : paper-1.12.2-1620
> 
> Upload logs of the session where you create the island and send it here please

https://pastebin.com/kaKAmC3N < log1
https://pastebin.com/BhPjyJrm < log2

https://www.youtube.com/watch?v=ByY32dpCjJM < video of bug occurrence

**Comment by Dot0420** [comment]
Haven't you reproduced the issue yet?

**Comment by OmerBenGera** [comment]
> Haven't you reproduced the issue yet?

Havent looked at what you sent yet.
I will look at that in the weekend

**Comment by OmerBenGera** [comment]
That's so weird, it works fine for me.
What Java version do you use?
Also, mind trying it with default files of Paper as well?

**Comment by Dot0420** [comment]
This Paper downloaded the latest version of 1.12.2 from the https://papermc.io/legacy
And the Java version used 'jre1.8.0_333'

To implement the same environment, I will share the test server I used
https://drive.google.com/file/d/1m-Jk9j7OCthPLJPGqdqtPxxgWC2VtgN3/view?usp=sharing

**Comment by Nickfyre** [comment]
this also happens to me, everything after version 1.9.0 doesn't save the islands

**Comment by OmerBenGera** [comment]
Using the test server of @Dot0420 , I can replicate the issue as well.
I will look into what causes this to occur.

**Comment by geumu** [comment]
I am also having the same problem.

**Comment by OmerBenGera** [comment]
I found an interesting thing, thanks to @geumu 
In version 1.9.0.593, everything works fine. Worlds are unloaded and loaded just fine.
However, once you install 1.9.0.594 or above, they are not loaded correctly anymore.
If you install back 1.9.0.593 again, they load again.

In 1.9.0.594, I changed the way dragon fights are handled, which might have caused it to happen.
I will look into it in the next weekend.

**Do not downgrade to 1.9.0.593, otherwise you'll lose your island data!**

**Comment by Gr1ZzLy23** [comment]
And where to download SuperiorSkyBlock's 1.9.0.593 version? :)
Is the stable version paid or free?

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it works for you.

**Comment by Dot0420** [comment]
It's resolved. Thank you :)
