### ISSUE TITLE
Is bank deposit/withdraw custom quantity error

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/SuperiorSkyblock2#1148]
### Minecraft's Version

1.16 airplane

### Plugin's Version

![image](https://user-images.githubusercontent.com/73038322/169663500-da037e47-2f8b-474d-b6bc-91d6cbcd2994.png)

### Describe the bug

If you open the is bank, and then you select withdraw/deposit custom quantity, will ask on the chat to send the quantity, then it throws an error when the message is sent
https://paste.md-5.net/enogelixuh.sql

### To Reproduce

/is bank
Click withdraw/deposit custom quantity
Type a number on the chat
See console

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
