### ISSUE TITLE
Plugin plays a sound when clicking on a empty inventory space

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/SuperiorSkyblock2#1150]
### Minecraft's Version

1.16 airplane

### Plugin's Version

![image](https://user-images.githubusercontent.com/73038322/169667623-5906e427-a8ce-4c34-bc48-149a7e3e6bed.png)

### Describe the bug

If you put sounds to inventory spaces on menus, for example on /is warps or /is visitors, if the gap of the inventory that you're clicking is empty it stills playing a sound.
I don't express myself very well so here's a video

/SuperiorSkyblock2/menus/visitors.yml
![image](https://user-images.githubusercontent.com/73038322/169667695-04ec7bb8-15a2-488d-9ff1-bb94092dcd2e.png)
https://i.imgur.com/dlXHkYH.mp4
So if you have sounds enabled on any menu and you click a empty inventory's space it plays a sound, is that normal?

### To Reproduce

Enable sound on any menu
Open that menu
Click empty space

### Additional Information

idk im using java 16

**Comment by CayeOficial** [comment]
Is this fixed?

**Comment by OmerBenGera** [comment]
> Is this fixed?

There will be a commit referring this issue once its fixed :)
You will be notified about it as well.

Mind uploading your entire menu to pastebin and send it here?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
