### ISSUE TITLE
Mission Errors in console

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1151]
### Minecraft's Version

Current: git-Purpur-1609 (MC: 1.18.2)*

### Plugin's Version

SuperiorSkyblock2 version 1.10.1

### Describe the bug

I get a lot of these errors in console: https://pastebin.com/UZNKfhCC 

### To Reproduce

Update from older version

### Additional Information

https://pastebin.com/UZNKfhCC

**Comment by OmerBenGera** [comment]
Duplicate of #1148
