### ISSUE TITLE
Bedrock/Floodgate players can not create an island after joining

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#1152]
### Minecraft's Version

Minecraft's Version
purpur 1.18.2 dev 1623

### Plugin's Version

Plugin's Version
ssb 646

### Describe the bug

When bedrock players join through geyser/floodgate, they can not create an island until they relog. This happens regardless of time being on the server. Once they rejoin then they can create an is like normal.

### To Reproduce

Possibly something with how the plugin registers a new player?

We use * prefix for users and use floodgate/geyser

**Comment by OmerBenGera** [comment]
What happens when they type /is create?

**Comment by Skizzles** [comment]
> What happens when they type /is create?

Nothing happens, no messages, no gui, it just acts like they never even ran the command

**Comment by OmerBenGera** [comment]
> > What happens when they type /is create?
> 
> Nothing happens, no messages, no gui, it just acts like they never even ran the command

Are you sure its related to SSB?
When I tried Geyser (for adding support to it), it worked like a charm.

Are you able to replicate the issue yourself on another server with only SSB installed?

**Comment by Skizzles** [comment]
> > > What happens when they type /is create?
> > 
> > 
> > Nothing happens, no messages, no gui, it just acts like they never even ran the command
> 
> Are you sure its related to SSB? When I tried Geyser (for adding support to it), it worked like a charm.
> 
> Are you able to replicate the issue yourself on another server with only SSB installed?

Is this with Floodgate installed? maybe somehow floodgate is interfering?

I am able to confirm with just SSB, Geyser, and Floodgate on a fresh server

**Comment by JohnnyX071** [comment]
Hello, I have been using the plugin for a while and my server has both geyser and floodgate and it works fine

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
> I can't replicate the issue myself as well. Are you using default files of Fllodgate, Geyser and SSB?

Yes we are

**Comment by OmerBenGera** [comment]
Well, I dont know why it happens to you.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If you find anything new, let me know by replying here
