### ISSUE TITLE
Placeholders do not work

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1160]
### Minecraft's Version

1.17 Pufferfish

### Plugin's Version

b666

### Describe the bug

Placeholders do not work anymore 

### To Reproduce

![image](https://user-images.githubusercontent.com/31826333/170813934-9f4c3999-7f53-454d-96e8-57dcab76c1d9.png)

### Additional Information

worked fine on b651

**Comment by OmerBenGera** [comment]
It works fine for me on latest versions.

**Comment by WarnDa** [comment]
Same on b671, it's maybe related to this error :
https://pastebin.com/RmRqUpx0

I'll try in local with and without oraxen and tell you

**Comment by WarnDa** [comment]
Can confirm it : 
![image](https://user-images.githubusercontent.com/31826333/170938987-88020096-6de7-4f4c-b5ea-5f34d10b74cd.png)
![image](https://user-images.githubusercontent.com/31826333/170939170-6036528c-ce80-4ed6-96ff-97b0d0c17323.png)

**Comment by OmerBenGera** [comment]
What version of Oraxen are you using?

**Comment by WarnDa** [comment]
I use 1.80.3

Because everytime a new minecraft version is released, old versions aren't supported (you can't even start the plugin)

**Comment by OmerBenGera** [comment]
All's good.
Mind sending me a copy of the plugin privately?

**Comment by OmerBenGera** [comment]
Fixed on latest dev build
