### ISSUE TITLE
Placeholders not working when in a menu? 

### ISSUE THREAD

**Issue by Florens11** [BG-Software-LLC/SuperiorSkyblock2#1166]
### Minecraft's Version

FoxSpigot

### Plugin's Version

1.10.1

### Describe the bug

https://paste.helpch.at/tuxosuwuqa.rb

### To Reproduce

Members.yml config: https://paste.helpch.at/kuxavejema.coffeescript

### Additional Information

![image](https://user-images.githubusercontent.com/52450422/170835871-230def6b-1216-47bd-aa4c-3e96d00485cf.png)
![image](https://user-images.githubusercontent.com/52450422/170835884-3405ac93-8c83-471d-8c0e-035b2af3cd19.png)

**Comment by OmerBenGera** [comment]
This only works inside the members management menu, as I said before.

**Comment by OmerBenGera** [comment]
May I close the issue?

**Comment by Florens11** [comment]
If you could make it so you can add commands to a filling item, it would be sick. It is possible this way but you need to click more. 

But if you close it its fine.

**Comment by OmerBenGera** [comment]
> If you could make it so you can add commands to a filling item, it would be sick. It is possible this way but you need to click more.
> 
> But if you close it its fine.

I will look into doing such thing, yes.
