### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by D3BoxOfficiel** [BG-Software-LLC/SuperiorSkyblock2#1167]
### Minecraft's Version

1.16.5

### Plugin's Version

1.9.0

### Describe the bug

Error console (parsing placeholder)

### To Reproduce

IDK

### Additional Information

https://pastebin.com/6dniu2qA

**Comment by YouSeeMeRunning2** [comment]
Update the plugin and test again
Current stable version is 1.10.2

**Comment by OmerBenGera** [comment]
^^
If the issue persists, let us know by replying.
