### ISSUE TITLE
Farmer missions invalid itemstack

### ISSUE THREAD

**Issue by Sulphinx** [BG-Software-LLC/SuperiorSkyblock2#1168]
### Minecraft's Version

1.8.8 paperspigot

### Plugin's Version

1.10.2

### Describe the bug

When starting the server with superiorskyblock installed, it says a default error "[SuperiorSkyblock2] [config.yml] Couldn't convert rewards.items.1 into an itemstack. Check type & data sections!"

### To Reproduce

As i said, its without changing anything manually it says that error when starting it.
A easy fix to this should be to check if your server version has beetroot as an item and if it has, there is nothing to change.
and if you version is below when they added beetroot, it will be removed from the farmer missions.

### Additional Information

![image](https://user-images.githubusercontent.com/94517012/170872351-42cde9cc-4b6a-4e8d-af2d-fd178f96ea50.png)

**Comment by OmerBenGera** [comment]
Remove the invalid item / change it to something else.

**Comment by Sulphinx** [comment]
Found out that it wasn't the wrong server version, its simply because you haven't added WHEAT_SEEDS to config.yml but set the reward to WHEAT_SEEDS so it cant find it.

**Comment by Sulphinx** [comment]
If anyone is wondering what the fix was to this, it probably wasn't anything with beetroot, more that WHEAT_SEEDS doesn't work.
You have to add SEEDS to the list crops-to-grow: in superiorskyblock2/config.yml
After that, you have to switch out the "WHEAT_SEEDS" in Superiorskyblock/modules/missions/categories/farmer/farmer_1.yml
with "SEEDS".
