### ISSUE TITLE
World providers can't provide dynamically loaded worlds

### ISSUE THREAD

**Issue by YouHaveTrouble** [BG-Software-LLC/SuperiorSkyblock2#1170]
### Minecraft's Version

Current: git-Purpur-1631 (MC: 1.18.2)* is my current testing setup
Making sure to note this, this is not purpur-specific, it also happens on paper.

### Plugin's Version

v1.10.2.674
dev build

### Describe the bug

World providers with island on separate, possibly not loaded worlds are unable to provide worlds properly,

From what I'm seeing the issue is here https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/51e0057f9e6e2d133d9ccc5a15c03e195e0088b6/src/main/java/com/bgsoftware/superiorskyblock/world/GridHandler.java#L652

I encountered this while trying to make it so island world only loads when player belonging to the island is online or it's requested via teleport. This is not possible, because it seems SS2 requires island world to be loaded to properly set its location for island.

### To Reproduce

try using fixed up version of the ssb aswm plugin (https://github.com/YouHaveTrouble/SSB2-AdvancedSlimeWorldManager/releases/tag/yht-1.0.5)

Generate the island.
Restart the server.

### Additional Information

https://paste.youhavetrouble.me/tIOk1V.md - the error that shows up when booting the server up while having one or more islands with possibly unloaded island world

**Comment by OmerBenGera** [comment]
You need to load the world of the last island on startup.
Then, you can unload it later.

**Comment by YouHaveTrouble** [comment]
Is there any convienient method of getting the world's name?

**Comment by OmerBenGera** [comment]
> Is there any convienient method of getting the world's name?

What do you mean?

**Comment by YouHaveTrouble** [comment]
I need last island's world name to load it up on startup 😅

**Comment by OmerBenGera** [comment]
> I need last island's world name to load it up on startup 😅

You'll have to track this data on your own probably - that's the easiest.

**Comment by OmerBenGera** [comment]
After looking at this again, looks like a bug.

**Comment by OmerBenGera** [comment]
Should be fixed.
Let me know if it works for you

**Comment by YouHaveTrouble** [comment]
sadly, still ends up like this https://paste.youhavetrouble.me/tukkbD.md after server restart. SS2 build 688

**Comment by YouHaveTrouble** [comment]
It does indeed work! Thanks!
I'll report back if I find anything else funny

**Comment by YouHaveTrouble** [comment]
@OmerBenGera 
Is there any specific reason why SSB loads all islands on startup? I'd like to avoid this because I'm working on a system that will spread the islands on multiple servers and only 1 server will be allowed to load the island at the time. 
I'm referring specifically to this part of boot https://paste.youhavetrouble.me/IZkSud.md

**Comment by YouHaveTrouble** [comment]
Reopening because this also has to do with dynamically loaded worlds.
While no island worlds are loaded plugin has issues on disable https://paste.youhavetrouble.me/6Q1qwR.md

**Comment by OmerBenGera** [comment]
> @OmerBenGera Is there any specific reason why SSB loads all islands on startup? I'd like to avoid this because I'm working on a system that will spread the islands on multiple servers and only 1 server will be allowed to load the island at the time. I'm referring specifically to this part of boot https://paste.youhavetrouble.me/IZkSud.md

Intended, will be changed in later versions tho

**Comment by OmerBenGera** [comment]
> Reopening because this also has to do with dynamically loaded worlds. While no island worlds are loaded plugin has issues on disable https://paste.youhavetrouble.me/6Q1qwR.md

Fixed.
