### ISSUE TITLE
Missions Bug

### ISSUE THREAD

**Issue by mertout** [BG-Software-LLC/SuperiorSkyblock2#1172]
### Minecraft's Version

1.8 taco spigot

### Plugin's Version

1.10.2

### Describe the bug

Hello, when performing the missions, after a short time, the blocks required in the missions are not counted.This bug?

### To Reproduce

when performing the mission

**Comment by OmerBenGera** [comment]
Take a video of the issue please

**Comment by mertout** [comment]
kırılan kömür cevheri sayısı = count of broken coal ore
video: https://www.youtube.com/watch?v=v_CJy7jyies

**Comment by OmerBenGera** [comment]
As I told you on Discord, the issue is related to the pickup plugin you use :)
