### ISSUE TITLE
You can only use alphabetical letters, numbers and ''_'' for warp names.

### ISSUE THREAD

**Issue by Areanydd** [BG-Software-LLC/SuperiorSkyblock2#1173]
### Minecraft's Version

Spigot 1.17.1

### Plugin's Version

SuperiorSkyblock2-1.10.2-b674

### Describe the bug

I cannot use [IslandWarp], i receive this:
You can only use alphabetical letters, numbers and ''_'' for warp names.

### To Reproduce

I don t know, just take a sign and try to add [IslandWarp] on the first line..and thats it, you will receive this.

### Additional Information

Nop, Thank you!

**Comment by OmerBenGera** [comment]
You must give a proper name to a warp - you cant leave ir blank.
In the second line, put the name you want - let me know if it works.

**Comment by OmerBenGera** [comment]
In latest versions I updated the default messages to better indicate the issue.
The issue is that you didn't provide a name to the warp.

**Comment by Areanydd** [comment]
yep, it s works!
