### ISSUE TITLE
After rebooting the server, I get the message below and cannot teleport to the island. The island seems to have disappeared.

### ISSUE THREAD

**Issue by geumu** [BG-Software-LLC/SuperiorSkyblock2#1174]
### Minecraft's Version

Paperspigot 1.12.2

### Plugin's Version

superiorskyblock 1.10.2

### Describe the bug

After rebooting the server, I get the message below and cannot teleport to the island. The island seems to have disappeared.
"Island | It seem like this island has no safe blocks. Please contact a staff member"

### To Reproduce

**Video**: https://youtu.be/5e6ZX7wmyx4

### Additional Information

**Log**: https://pastebin.com/CUxqcE7U

**Comment by OmerBenGera** [comment]
Duplicate of #1139
