### ISSUE TITLE
Lots of dummy chunk files generated

### ISSUE THREAD

**Issue by aaa8881** [BG-Software-LLC/SuperiorSkyblock2#1175]
### Minecraft's Version

paper 1.12

### Plugin's Version

1.9.0

### Describe the bug

Island count around 300 with 500x500 island size with ~100GB island world. 

hundred thousand chunk file with approx. 4096kb are generated at the same time. invalid dummy chunks. 

### To Reproduce

Not very sure

**Comment by OmerBenGera** [comment]
Sadly, I can't delete old chunks that were created for no reason.
However, check out latest dev build, let me know if you see a decrease of the growth of the world.

**Comment by OmerBenGera** [comment]
Closing this for now
If it still happens, lmk
