### ISSUE TITLE
superior_island_location_name_leader placeholder ignoring default placeholders assigned in config

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1177]
### Minecraft's Version

git-Purpur-1609 (MC: 1.18.2)*

### Plugin's Version

SuperiorSkyblock2 version 1.10.2

### Describe the bug

I have
`default-placeholders:
- superior_island_leader:N/A
- superior_island_level:0
- superior_island_worth:0
- superior_island_location_name_leader:Hub`
set in config.yml, but the placeholder superior_island_location_name_leader still returns null, instead of Hub.

### To Reproduce

1. Add superior_island_location_name_leader to the default placeholders in config.yml
2. Go to a non island world
3. Parse the placeholder

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Upload your config to pastebin and send it here

**Comment by DuneSciFye** [comment]
https://pastebin.com/SJMJPZJu

**Comment by OmerBenGera** [comment]
> https://pastebin.com/SJMJPZJu

Can't access it, it's private or moderated.
Use another service

**Comment by DuneSciFye** [comment]
https://paste.md-5.net/pokucaqeko.coffeescript

**Comment by OmerBenGera** [comment]
It works fine for me in latest builds.

**Comment by DuneSciFye** [comment]
Is there a way to test or figure out why its not working for me?

**Comment by OmerBenGera** [comment]
> Is there a way to test or figure out why its not working for me?

check it on a server with default files with only SSB and PAPI installed

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by DuneSciFye** [comment]
Seems to work fine on the testing server, I don't understand what might be breaking it on the production server.

**Comment by OmerBenGera** [comment]
> Seems to work fine on the testing server, I don't understand what might be breaking it on the production server.

No clue neither

**Comment by OmerBenGera** [comment]
Any news regarding this?
Have you found the cause?

**Comment by DuneSciFye** [comment]
Nope, tried it on testing server, worked fine. No clue at all whats happening. Feel free to close
