### ISSUE TITLE
Issue with Stable Download ULR on BG Software website.

### ISSUE THREAD

**Issue by RediPanda** [BG-Software-LLC/SuperiorSkyblock2#1186]
### Minecraft's Version

N/A

### Plugin's Version

2.3.1

### Describe the bug

Download link on the BG-Software website leads to an invalid URL.
https://bg-software.com/var/www/html/downloads/SuperiorSkyblock2-1.10.2.jar

Instead, the link should've lead to:
https://bg-software.com/downloads/SuperiorSkyblock2-1.10.2.jar

This seems to appear in other software provided by BG-Software.

### To Reproduce

Simply go to any plugin section you wish to download: E.g.
https://bg-software.com/wildchests/

And click on the Stable Version.

**Comment by OmerBenGera** [comment]
Fixed. thanks for reporting
