### ISSUE TITLE
epicspawners and island level

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1188]
### Minecraft's Version

{"currentVersion":"git-Purpur-1631 (MC: 1.18.2)"}

### Plugin's Version

SuperiorSkyblock2-1.10.2-b677

### Describe the bug

when player have a custom spawners or omni spawners on island, when players try to (/island level) he got a message say to contact server administrator and in console i have a error.

https://mcpaste.io/230665eb2ee01931
https://mcpaste.io/5d09e2f6d30ad710

### To Reproduce

place custom spawner or omni spawner and execute /island level command

### Additional Information

https://mcpaste.io/230665eb2ee01931
https://mcpaste.io/5d09e2f6d30ad710

**Comment by OmerBenGera** [comment]
What version of EpicSpawners are you using?

**Comment by DuckyDou** [comment]
Latest 7.2.7

**Comment by OmerBenGera** [comment]
What is your Discord?
I need you to send me a copy of the plugin.

**Comment by DuckyDou** [comment]
Ducky_Dou#0001

**Comment by OmerBenGera** [comment]
After looking into it more deeply, it doesn't look like an issue with SSB, but with EpicSpawners.
When the plugin tries to get the identifier name of the spawner, EpicSpawners fetches it from the first stack of the spawner.
However, the first stack returns null spawner data, which causes this error.

Try contacting them, provide a link to this issue.
I'll keep this one opened until they respond.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
Closing this for now
If it still occurs, lmk
