### ISSUE TITLE
Lang settings bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1190]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-71 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 671d68b on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-70 (MC: 1.18.2)

### Plugin's Version

1.10.2.675

### Describe the bug

When changing the lang and disabling the auto lang feature it's locked to EN-US lang even thos I specified something else such as fr-FR. It only works in console.

https://gyazo.com/cbabf851284dc95327baa0ffda83a616
https://gyazo.com/70fe2546a33127a16da264a296d80d8b
https://gyazo.com/b9beb68ad8c81973ff5ab49cefe191fb

### To Reproduce

Change the lang to fr-FR and disable to automatic lang system

**Comment by OmerBenGera** [comment]
default-lang is only applied to new players.
Delete the database and your lang will change.
