### ISSUE TITLE
Hex color bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1191]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-71 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 671d68b on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-70 (MC: 1.18.2)

### Plugin's Version

1.10.2.677

### Describe the bug

I saw that a config line in the lang folder did not have support for the hex color format: 
GOT_INVITE: '&{HEX:FFEC00}{0} &{HEX:55DE0A}has invited you on his island.'

### To Reproduce

Go in the fr_fr lang file, go to the GOT_INVITE line and add some hex colors

**Comment by LuluxClient** [comment]
The First message is the bugged message and the bottom one is how it should look like: 
![image](https://user-images.githubusercontent.com/62576432/173901211-33bdda5a-c7e4-475b-97d9-7274368d4a1e.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
