### ISSUE TITLE
Superiorblock2 - Border

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SuperiorSkyblock2#1192]
### Minecraft's Version

1.17.1

### Plugin's Version

![image](https://user-images.githubusercontent.com/105610066/174018772-2819a007-c3a3-4b93-8b36-8f34e7b147c6.png)

### Describe the bug

Island border is not displayed

### To Reproduce

-

### Additional Information

Something strange happened, I tried to remove the island / create from scratch and there was still no border, none of the players can see border now (it worked earlier)

I tried every option here and unfortunately it does not appear at all (I turned on / off the border) and restarted the server

![image](https://user-images.githubusercontent.com/105610066/174018828-996974c4-df8a-45bd-a031-c6b06e860e93.png)

**Comment by xOpasik** [comment]
https://www.youtube.com/watch?v=Mn-2Jiuwcxs

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue on another server?
I can't replicate the issue myself.

**Comment by xOpasik** [comment]
Hmm, maybe I have something wrong in my config, but I don't know to send you a file or something?

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/174426869-2c9a8f88-14bd-46f7-9fdb-05e9c4419f02.png)
Could it be this?

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/105610066/174426869-2c9a8f88-14bd-46f7-9fdb-05e9c4419f02.png) Could it be this?

I dont believe so.
Have you tried replicating it on another server?

**Comment by xOpasik** [comment]
Not

**Comment by OmerBenGera** [comment]
> Not

Then try...

**Comment by xOpasik** [comment]
Mordo, I found what the problem was

**Comment by xOpasik** [comment]
BORDER_PLAYER_COLOR_NAME_BLUE: '&x&4&7&c&c&f&fNiebieski'
BORDER_PLAYER_COLOR_NAME_RED: '&x&f&f&3&c&3&cCzerwony'
BORDER_PLAYER_COLOR_NAME_GREEN: '&x&4&9&d&a&5&8Zielony'

When I have this, border stops working

Ale gdy mam tak:

BORDER_PLAYER_COLOR_NAME_BLUE: Niebieski
BORDER_PLAYER_COLOR_NAME_RED: Czerwony
BORDER_PLAYER_COLOR_NAME_GREEN: Zielony

It works already
Basically what I sent were chat messages

**Comment by xOpasik** [comment]
But it still doesn't work for me to change the border color hmm
I was combining and I don't know why I don't want to change

**Comment by OmerBenGera** [comment]
> But it still doesn't work for me to change the border color hmm I was combining and I don't know why I don't want to change

Again, does it happen on another server, using default files of the plugin?

**Comment by xOpasik** [comment]
I did it on the same server

**Comment by xOpasik** [comment]
Which does not change the fact that I will have the same, since it was enough to remove the graident in 3 places to start working again

**Comment by OmerBenGera** [comment]
> Which does not change the fact that I will have the same, since it was enough to remove the graident in 3 places to start working again

You said it doesn't work even after you changed the messages..
Does changing the messages fix the issue?

**Comment by xOpasik** [comment]
Fixes 50% because when I deleted '' along with the gradient
![image](https://user-images.githubusercontent.com/105610066/174450506-c1282aec-fa59-4247-9816-ea8730ae1f52.png)

The border itself has started to be visible (it can be turned on / off) but there is still no option to make the colors of this border work

**Comment by OmerBenGera** [comment]
> Fixes 50% because when I deleted '' along with the gradient ![image](https://user-images.githubusercontent.com/105610066/174450506-c1282aec-fa59-4247-9816-ea8730ae1f52.png)
> 
> The border itself has started to be visible (it can be turned on / off) but there is still no option to make the colors of this border work

I really don't understand what you mean by "fixes 50%" or "make the colors of this border work"

**Comment by xOpasik** [comment]
![image](https://user-images.githubusercontent.com/105610066/174450860-38a88014-c084-4858-8e2a-8ec2146bb474.png)
![image](https://user-images.githubusercontent.com/105610066/174450870-7d8a1f12-6883-42fd-8064-234d21bbba3c.png)
I can turn border on / off, but I can't set the color anymore
![image](https://user-images.githubusercontent.com/105610066/174450883-5a60171e-ef18-4078-acc7-cb52be449fa5.png)

**Comment by OmerBenGera** [comment]
I tried to replicate it myself and everything works fine, even using your custom messages.
Are you sure there are no errors or anything?

**Comment by xOpasik** [comment]
I do not see anything in the console, or I will try to restart again

**Comment by OmerBenGera** [comment]
I again ask you to try it **on another server** with default files.
If you'll refuse to do so, I'll just close this issue as there's no point in me helping you when you refuse to do what I ask.

**Comment by xOpasik** [comment]
But understand that everything works with the default files

**Comment by OmerBenGera** [comment]
> But understand that everything works with the default files

Send me your files of the plugin by uploading them as zip and send a link here.

**Comment by xOpasik** [comment]
[SuperiorSkyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8934095/SuperiorSkyblock2.zip)

**Comment by xOpasik** [comment]
And how?

**Comment by xOpasik** [comment]
And how?

**Comment by OmerBenGera** [comment]
It works just fine using your files. I noticed you have this:
```
# Should world borders be enabled by default for new players?
default-world-border: false
```
Maybe that's the issue? You just have world borders turned off for players by default.

**Comment by xOpasik** [comment]
I still can't change the border color

**Comment by xOpasik** [comment]
I updated the superior and the oneblock module, changed this option and nothing has changed. I still can't change the border color from white to green / red / blue

**Comment by xOpasik** [comment]
I figured it out and it works
