### ISSUE TITLE
is top spawners

### ISSUE THREAD

**Issue by xOpasik** [BG-Software-LLC/SuperiorSkyblock2#1195]
### Minecraft's Version

1.17.1

### Plugin's Version

newest

### Describe the bug

![image](https://user-images.githubusercontent.com/105610066/174449412-acd31849-8b4e-496a-aea1-d6f9923c180c.png)
![image](https://user-images.githubusercontent.com/105610066/174449413-ecc9239f-aa25-4f57-8547-6829448b5e38.png)
Does not count levels or spawner values -> also checked by restarting

### To Reproduce

-

### Additional Information

-

**Comment by OmerBenGera** [comment]
in 1.17, the correct material name for spawners is "SPAWNER" and not "MOB_SPAWNER".
Use https://bg-software.com/materials/ to find the correct material names for your version

**Comment by xOpasik** [comment]
thanks
