### ISSUE TITLE
API Changed?

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1199]
### Minecraft's Version

1.12.2

### Plugin's Version

Switched to b688 from b510

### Describe the bug

https://pastebin.com/ryrYMhfE

### To Reproduce

-

### Additional Information

The plugin that uses the SSB API works on b510, but doesn't on b688, something changed?

**Comment by OmerBenGera** [comment]
Obviously a bug.
Mind showing me how you fetch top islands?

**Comment by OmerBenGera** [comment]
@Superalex0102 Make sure you send me your code :)

**Comment by Superalex0102** [comment]
> @Superalex0102 Make sure you send me your code :)

Sorry about the late reply, I were not at the computer for the last few days.

```
  public void fetchTop() {
    int current = 0;
    this.toplist.clear();
    Island island;
    while ((island = SuperiorSkyblockAPI.getGrid().getIsland(current++, SortingType.getByName("LEVEL"))) != null) {
      if (island.isIgnored())
        continue; 
      long delta = island.getIslandLevel().longValue() - getConfig().getLong("islands." + island.getUniqueId().toString(), 0L);
      boolean already = false;
      for (Map.Entry<UUID, Long> entry : this.toplist) {
        if (((UUID)entry.getKey()).equals(island.getUniqueId())) {
          already = true;
          break;
        } 
      } 
      if (!already) {
        this.toplist.add(new AbstractMap.SimpleEntry<>(island.getUniqueId(), Long.valueOf(delta)));
        this.islandOwners.put(island.getUniqueId(), island.getOwner().getName());
      } 
    } 
    sortTop();
  }
```

**Comment by OmerBenGera** [comment]
> > @Superalex0102 Make sure you send me your code :)
> 
> Sorry about the late reply, I were not at the computer in the last few days.
> 
> ```
>   public void fetchTop() {
>     int current = 0;
>     this.toplist.clear();
>     Island island;
>     while ((island = SuperiorSkyblockAPI.getGrid().getIsland(current++, SortingType.getByName("LEVEL"))) != null) {
>       if (island.isIgnored())
>         continue; 
>       long delta = island.getIslandLevel().longValue() - getConfig().getLong("islands." + island.getUniqueId().toString(), 0L);
>       boolean already = false;
>       for (Map.Entry<UUID, Long> entry : this.toplist) {
>         if (((UUID)entry.getKey()).equals(island.getUniqueId())) {
>           already = true;
>           break;
>         } 
>       } 
>       if (!already) {
>         this.toplist.add(new AbstractMap.SimpleEntry<>(island.getUniqueId(), Long.valueOf(delta)));
>         this.islandOwners.put(island.getUniqueId(), island.getOwner().getName());
>       } 
>     } 
>     sortTop();
>   }
> ```

It should be fixed in latest dev build.
I recommend iterating through the islands by iterating on a sorted list that you can get from GridManager instead of accessing the islands by positions for better performance :)
