### ISSUE TITLE
Bungeecord SkinsRestorer

### ISSUE THREAD

**Issue by ProfessorDeBroglie** [BG-Software-LLC/SuperiorSkyblock2#1203]
### Minecraft's Version

1.18.2

### Plugin's Version

SuperiorSkyblock2-1.10.2.jar

### Describe the bug

https://pastebin.com/5G2XGVwZ

### To Reproduce

whenever a player enters, this appears

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by ProfessorDeBroglie** [comment]
It worked
:)
