### ISSUE TITLE
Starting to load islands...

### ISSUE THREAD

**Issue by XHealthy** [BG-Software-LLC/SuperiorSkyblock2#1204]
### Minecraft's Version

git-Purpur-1632 (MC: 1.18.2)

### Plugin's Version

dev build #694 24/06/2022 14:42:37

### Describe the bug

The plugin cannot load player islands.

### To Reproduce

I was using version 1.10.2 and when I updated the plugin to the latest dev version this error occurred.

**Comment by OmerBenGera** [comment]
Upload the error you get to pastebin and send it here

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.
