### ISSUE TITLE
Level bug

### ISSUE THREAD

**Issue by mertout** [BG-Software-LLC/SuperiorSkyblock2#1205]
### Minecraft's Version

1.8.8 paper spigot

### Plugin's Version

SuperiorSkyblock2-1.11.0

### Describe the bug

"vine" gives level even if you make it 0 in levels.yml

### To Reproduce

"vine" gives level even if you make it 0 in levels.yml

**Comment by OmerBenGera** [comment]
Levels aren't given out of nowhere.
If you set it to 0, it might get the worth/level from shop plugins

Look from where the price is taken - you can use `/is admin debug Action: Get Worth` and watch the console.

**Comment by mertout** [comment]
console is typing [DEBUG] Action: Get Level, Block: VINE:4 - Levels File, Level: 0.001
but vine gave 1 levels

**Comment by OmerBenGera** [comment]
Thats because of level roundings. You can disable it in the config if you wish.
