### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by mertout** [BG-Software-LLC/SuperiorSkyblock2#1206]
### Minecraft's Version

1.8.8 paper spigot

### Plugin's Version

SuperiorSkyblock2-1.11.0

### Describe the bug

He can fly even if he does not have a flight permission on the island

### To Reproduce

He can fly even if he does not have a flight permission on the island

**Comment by OmerBenGera** [comment]
Players cannot fly using `/island fly` on other islands they don't have access to do so.
Other sources of fly are permitted (such as essentials /fly)

**Comment by OmerBenGera** [comment]
Any news regarding this?
