### ISSUE TITLE
API island get and checks return null Island

### ISSUE THREAD

**Issue by YouHaveTrouble** [BG-Software-LLC/SuperiorSkyblock2#1207]
### Minecraft's Version

Current: git-Purpur-1671 (MC: 1.19)*

### Plugin's Version

SuperiorSkyblock2 version 1.11.0.695 (dev build)

### Describe the bug

API method `SuperiorSkyblockAPI.getIslandAt()` returns null on an island of which world has been dynamically loaded.
API method `SuperiorPlayer.isInsideIsland()` returns false even when player is on their own island

### To Reproduce

Get a world provider that dynamically loads island worlds, try using methods mentioned above and log the results

**Comment by YouHaveTrouble** [comment]
Sorry, that one's on me, I messed up with isIslandsWorld() method in my custom provider

**Comment by OmerBenGera** [comment]
B

**Comment by OmerBenGera** [comment]
Btw, I also plan on working on proxy support for SSB, so you might want to check it out as well :)

**Comment by YouHaveTrouble** [comment]
Appreciated, but I have my own thing planned for my server, I just need something working for now and will migrate later. Might aswell help out with catching weird bugs here ;)
