### ISSUE TITLE
Custom Schematics not working

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/SuperiorSkyblock2#1209]
### Minecraft's Version

Purpur 1.19.2 (1628)

### Plugin's Version

1.11.0.696

### Describe the bug

I cant create new island with custom schematic.
"/is create 123 custom" command not working. When I type this command there is no response on chat and in console.
I made this schematic via SuperiosSkyblock2.
Defaults schematics working.
No errors in console. Only one on startup - "[SuperiorSkyblock2] Biome 'WOODED_HILLS' is not valid, skipping..." but it comes with default settings without my schematic.

### To Reproduce

Make custom schematic and try to create.

**Comment by OmerBenGera** [comment]
Add the schematic to the creation menu.
Also, make sure you follow the tutorial on our wiki for creating new schematics
