### ISSUE TITLE
sorting issue

### ISSUE THREAD

**Issue by HiddenSeaMC** [BG-Software-LLC/SuperiorSkyblock2#1211]
### Minecraft's Version

1.18.2 Spigot

### Plugin's Version

1.11.0.696 (dev build)

### Describe the bug

When i do /is top (with the default config) i ve got an error.
i asked on discord, the moderator Itchy said to open an issue it can be a sorting issue

### To Reproduce

have the default config (is top)
do /is top

see on the console a lot of error logs and the is top doesn't work

### Additional Information

error : https://www.toptal.com/developers/hastebin/ohabigitew.shell

**Comment by nivcoo** [comment]
Same issue here

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
