### ISSUE TITLE
menu to set role member and moderator options don't work

### ISSUE THREAD

**Issue by ProfessorDeBroglie** [BG-Software-LLC/SuperiorSkyblock2#1214]
### Minecraft's Version

1.18.2

### Plugin's Version

SuperiorSkyblock2-1.11.0-b693

### Describe the bug

SuperiorSkyblock2/menus/members-role.yml
member and moderator options don't work.
"unknown command"

### To Reproduce

try to modify member role
https://cdn.discordapp.com/attachments/554282577322704896/991314895247261806/unknown.png

**Comment by OmerBenGera** [comment]
It works just fine.
Make sure you have access to `/is setrole` command.
