### ISSUE TITLE
Cannot load SuperiorWorld

### ISSUE THREAD

**Issue by olivervincent** [BG-Software-LLC/SuperiorSkyblock2#1215]
### Minecraft's Version

3499-Spigot-87c4d13-64c1527 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-1.11.0-b696.jar

### Describe the bug

I start the server. Plugin load fine.  When it starts to load the SuperiorWorld, it spams console with this error: https://pastebin.com/q791rd8K

Server never starts.

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Try using Paper instead of Spigot.

**Comment by olivervincent** [comment]
Fixed it.
