### ISSUE TITLE
Visitor signs do not deactivate.

### ISSUE THREAD

**Issue by Snowmansir** [BG-Software-LLC/SuperiorSkyblock2#1217]
### Minecraft's Version

(MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.11.0

### Describe the bug

Hello!

From my limited understanding from 

https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/src/main/java/com/bgsoftware/superiorskyblock/listener/SignsListener.java

It should replace an old sign when a new one is placed. But they both stay activated (green).

![javaw_d2WEPkVjXA](https://user-images.githubusercontent.com/108475475/176705720-59e63499-840a-4b90-b251-e5e3c043807b.png)

But I believe they should be like this!

![javaw_v7oLIigYRV](https://user-images.githubusercontent.com/108475475/176705786-a090e06d-abe4-4b61-8490-ac81166fcc7a.png)

Could you please take a look at it? 👍 

### To Reproduce

Place 1 welcome sign then place another and the old one stays active. :(

### Additional Information

This video shows the same results as my local server which I used to test with the information provided above.
Not the best quality, but had to do something given the limitation of size. I can upload it if it's not clear enough.

[saved.webm](https://user-images.githubusercontent.com/108475475/176723536-dc4da0cc-fd4d-42d0-9a69-ca3bef08fab3.webm)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Snowmansir** [comment]
Thank you! 👍
