### ISSUE TITLE
Warnings that appear when the player join the server.

### ISSUE THREAD

**Issue by ejdzeys** [BG-Software-LLC/SuperiorSkyblock2#1221]
### Minecraft's Version

MC: 1.16.5 Paper-794 Last version.

### Plugin's Version

1.11.0

### Describe the bug

It gives this warning when a player join the server. SkinRestorer support team wrote that the problem is that the plugin is trying to connect to APIs in proxy mode. My console is getting very dirty because of this warning, which is still up to date.

- https://hastebin.app/62beedffd5c6ab001c6269f8

### To Reproduce

The warns renews itself each time a player logs into the server.

**Comment by OmerBenGera** [comment]
Update the plugin to latest version, already been fixed.
