### ISSUE TITLE
ViaVersion warnings when creating an island.

### ISSUE THREAD

**Issue by ejdzeys** [BG-Software-LLC/SuperiorSkyblock2#1222]
### Minecraft's Version

MC: 1.16.5 Paper-794 Last version.

### Plugin's Version

1.11.0

### Describe the bug

When the player creates a new island, they spam these warnings via viaversion.

ViaVersion Support: You have a plugin sending chunk data before light data; figure out which one it is and report that as incorrect behavior to them. That's usually oreobfuscation or farther viewdistance plugins. - what kennytv said in other issues before.

- https://hastebin.app/62beefdfd5c6ab001c6269f9

### To Reproduce

It usually happens when a player creates a new island.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
