### ISSUE TITLE
Island Chest doesn't open

### ISSUE THREAD

**Issue by olivervincent** [BG-Software-LLC/SuperiorSkyblock2#1223]
### Minecraft's Version

1.19 PaperSpigot

### Plugin's Version

Latest

### Describe the bug

When I'm in the Island Chest menu, i click an empty minecart, it just plays the chest opening sound, but nothing happens.

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Give yourself chests using `/is admin setchestrow` or via the config file
