### ISSUE TITLE
Crop upgrade is not working, even if crop growth is set manually. 

### ISSUE THREAD

**Issue by Michaelopolis** [BG-Software-LLC/SuperiorSkyblock2#1226]
### Minecraft's Version

1.19

### Plugin's Version

#706 dev build

### Describe the bug

Crops only grow at the set speed. This happens after a server reset. but now i cant even make it work manualy. 

### To Reproduce

give a player an upgrade for crop growth then restart server.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If the issue still occurs, let me know
