### ISSUE TITLE
negative the level and worth

### ISSUE THREAD

**Issue by xsorencoolx** [BG-Software-LLC/SuperiorSkyblock2#1228]
### Minecraft's Version

paper 1.16.5

### Plugin's Version

SuperiorSkyblock2-1.11.0-b706

### Describe the bug

bug is when you go to nether island your island level and worth change to negative number

### To Reproduce

open nether island and go in it

### Additional Information

https://user-images.githubusercontent.com/51112473/177024936-e1a0cd04-ecea-4907-bb52-12ed506e2ed1.mp4

**Comment by Olek012** [comment]
Happens to me too on paper 1.19

As I have seen there is a problem with /is blocks too, but I think it's related to this case:
When you go to the nether, and return to your island and use is level, 4096 blocks of netherrack are added to your /is blocks command

Steps to reproduce:
- Make a new island
- Go to the nether
- Use /is level
- Return to overworld island
- Use /is level again and then /is blocks

The same thing happens when you go to the end, a random block of the island is added to your is block x4096

**Comment by OmerBenGera** [comment]
@Olek012 @xsorencoolx when you go to the nether, a schematic is placed and therefore its blocks are added to your block counts. The level should not be affected, thats a bug

**Comment by xsorencoolx** [comment]
can you fix it fast cause lots of my members gonna get angry for this bug

**Comment by OmerBenGera** [comment]
> can you fix it fast cause lots of my members gonna get angry for this bug

I am not at home and its not a big deal - `/is level` will recalculate the blocks and sync them again

**Comment by Olek012** [comment]
Sorry @OmerBenGera my users are getting problems with the /is level without going nether too. I can't reproduce It. But using /is level don't syncs well or something because it shows lvl 0 all times, same if i try with /is admin recalc (player).

Should i create a new issue in GitHub even without knowing how to reproduce the bug?

**Comment by OmerBenGera** [comment]
> Sorry @OmerBenGera my users are getting problems with the /is level without going nether too. I can't reproduce It. But using /is level don't syncs well or something because it shows lvl 0 all times, same if i try with /is admin recalc (player).
> 
> Should i create a new issue in GitHub even without knowing how to reproduce the bug?

If the level was calculated recently / the island is not active, it will not calculate it.

**Comment by xsorencoolx** [comment]
@OmerBenGera when you gonna fix this problem? its been 1 week and my players reporting this alot and is recalc is not making there level back i should set there bonus to 0

**Comment by OmerBenGera** [comment]
> @OmerBenGera when you gonna fix this problem? its been 1 week and my players reporting this alot and is recalc is not making there level back i should set there bonus to 0

When I have the time. There is no need to bump the issue.
I only work on the plugins when I am at home, which is only on weekends, so be patient.

**Comment by OmerBenGera** [comment]
There is indeed an issue with calculating block counts on chunks that are not loaded.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.
Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.

**Comment by olivervincent** [comment]
> Check out latest dev build, let me know if it's better. Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.

Running 1.11.0.716. The problem is not fixed. Tried /is level and /is recalc https://i.imgur.com/WAdFsiI.png

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it's better. Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.
> 
> Running 1.11.0.716 on 1.19 Paper. The problem is not fixed. Tried /is level and /is recalc https://i.imgur.com/WAdFsiI.png
> 
> Dunno if me running the OneBlock addons, also interfering with this.

Do you have any parts of the island outside of your border?
I checked it out myself and it worked fine for me.

**Comment by olivervincent** [comment]
No I do not.

**Comment by olivervincent** [comment]
> > > Check out latest dev build, let me know if it's better. Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.
> > 
> > 
> > Running 1.11.0.716 on 1.19 Paper. The problem is not fixed. Tried /is level and /is recalc https://i.imgur.com/WAdFsiI.png
> > Dunno if me running the OneBlock addons, also interfering with this.
> 
> Do you have any parts of the island outside of your border? I checked it out myself and it worked fine for me.

[https://www.loom.com/share/63f1c543b2aa44a199db0cdeaac80285](url)

**Comment by xsorencoolx** [comment]
it's not fixed, I'm using default schematic

**Comment by OmerBenGera** [comment]
> > > > Check out latest dev build, let me know if it's better. Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.
> > > 
> > > 
> > > Running 1.11.0.716 on 1.19 Paper. The problem is not fixed. Tried /is level and /is recalc https://i.imgur.com/WAdFsiI.png
> > > Dunno if me running the OneBlock addons, also interfering with this.
> > 
> > 
> > Do you have any parts of the island outside of your border? I checked it out myself and it worked fine for me.
> 
> https://www.loom.com/share/63f1c543b2aa44a199db0cdeaac80285

The reported issue is when going to the nether, your levels decrease - if they are negative without the nether, then this is not an issue, and its caused by the schematic offset.

**Comment by olivervincent** [comment]
> > > > > Check out latest dev build, let me know if it's better. Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.
> 
> > > > 
> 
> > > > 
> 
> > > > Running 1.11.0.716 on 1.19 Paper. The problem is not fixed. Tried /is level and /is recalc https://i.imgur.com/WAdFsiI.png
> 
> > > > Dunno if me running the OneBlock addons, also interfering with this.
> 
> > > 
> 
> > > 
> 
> > > Do you have any parts of the island outside of your border? I checked it out myself and it worked fine for me.
> 
> > 
> 
> > https://www.loom.com/share/63f1c543b2aa44a199db0cdeaac80285
> 
> 
> 
> The reported issue is when going to the nether, your levels decrease - if they are negative without the nether, then this is not an issue, and its caused by the schematic offset.

On the filmed Island, I have been to the nether. = same issue

**Comment by OmerBenGera** [comment]
> > > > > > Check out latest dev build, let me know if it's better. Make sure the entire schematic is within the borders of the island, so when doing `/is level` all the blocks will be calculated.
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > Running 1.11.0.716 on 1.19 Paper. The problem is not fixed. Tried /is level and /is recalc https://i.imgur.com/WAdFsiI.png
> > 
> > 
> > > > > Dunno if me running the OneBlock addons, also interfering with this.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Do you have any parts of the island outside of your border? I checked it out myself and it worked fine for me.
> > 
> > 
> > > 
> > 
> > 
> > > https://www.loom.com/share/63f1c543b2aa44a199db0cdeaac80285
> > 
> > 
> > The reported issue is when going to the nether, your levels decrease - if they are negative without the nether, then this is not an issue, and its caused by the schematic offset.
> 
> On the filmed Island, I have been to the nether. = same issue

Try going to the nether, and as soon as you're there type /is level. Let me know if the worth/level are different.

**Comment by olivervincent** [comment]
> 

Nope, still negative.

**Comment by Envqu** [comment]
Its not fixed. 25 level before nether portal. Now its updated to -15,000 when I typed /is level on my nether island...

**Comment by xsorencoolx** [comment]
i have stupid idea to fix it in is mission if players join nether or end on reward command set /is admin bonus * level 0

**Comment by Envqu** [comment]
Its working but only for new islands. If I want to recalculate old island its still showing negative level.

**Comment by OmerBenGera** [comment]
> Its working but only for new islands. If I want to recalculate old island its still showing negative level.

The issue was that when going through portals, there was a possibility that the bonus worth will be added more than once, causing it to be too big and levels be negative. In order to fix it, you'll have to manually adjust the bonus worth and level to islands, unfortunately.

My suggestion is to do it through the database when the server is shut down.

**Comment by OmerBenGera** [comment]
In latest dev build I added `/is admin syncbonus` command which will synchronize the worth/level bonus again for old islands as well.

**Comment by Envqu** [comment]
> In latest dev build I added `/is admin syncbonus` command which will synchronize the worth/level bonus again for old islands as well.

When I type `/is admin syncbonus * worth` it will sync worth for all players online or also offline players?

**Comment by OmerBenGera** [comment]
> > In latest dev build I added `/is admin syncbonus` command which will synchronize the worth/level bonus again for old islands as well.
> 
> When I type `/is admin syncbonus * worth` it will sync worth for all players online or also offline players?

it will sync the worth bonus for all the islands.

**Comment by OmerBenGera** [comment]
Seems to be fixed.
If it still occurs, lmk by commenting here
