### ISSUE TITLE
SS2 enables Legacy Material Support on 1.13+

### ISSUE THREAD

**Issue by YouHaveTrouble** [BG-Software-LLC/SuperiorSkyblock2#1231]
### Minecraft's Version

spans all versions through 1.13 to 1.19 throughout all spigot and its forks server software

### Plugin's Version

SuperiorSkyblock2 version 1.11.0.706 (dev)

### Describe the bug

Loading any schematic enables legacy material compat layer which makes already huge Material enum even bigger by loading all legacy materials into it. This is considered a bug, since SS2 is not considered legacy plugin (has api-version in plugin.yml).

### To Reproduce

1. turn on debug mode in server.properties to see which class exactly called for legacy materials
2. start the server with SS2 on

### Additional Information

Log with debug mode enabled: https://paste.youhavetrouble.me/YgKbxq.md

It's important to say that this also happens when schematic was created on the modern version and should not have any legacy block or material data inside of it

**Comment by OmerBenGera** [comment]
How does it affect you?

**Comment by YouHaveTrouble** [comment]
I'd rather have faster startup times, less memory usage, less process time when I need to loop over material class for whatever reason.

I'm aiming for a setup where I automatically add more servers to the network as need arises and that startup time is *relatively important*, so even those 2-5 seconds legacy compat layer enables is a huge deal.

**Comment by OmerBenGera** [comment]
Send me your schematic please, I will look into it.

**Comment by YouHaveTrouble** [comment]
[default_island.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9066149/default_island.zip)

rename the file to .schematic extension, github didn't let me upload with that one

**Comment by YouHaveTrouble** [comment]
Because compat layer should not even exist, was really bad idea by md_5 to begin with.

How much time in total have you spent updating the plugin each version due to it having to have separate module for nms?

I won't go into detail here, but the point is, trying to cut off legacy code. You can write all of that once for 1.13+ using api and never think about it again because it will just work ;P

I'm in your discord, feel free to ping me there if you want me to go into more detail

**Comment by OmerBenGera** [comment]
> Because compat layer should not even exist, was really bad idea by md_5 to begin with.
> 
> How much time in total have you spent updating the plugin each version due to it having to have separate module for nms?
> 
> I won't go into detail here, but the point is, trying to cut off legacy code. You can write all of that once for 1.13+ using api and never think about it again because it will just work ;P
> 
> I'm in your discord, feel free to ping me there if you want me to go into more detail

The performance of the API methods most of the time is no way as optimized as using direct nms. Therefore, I disagree with you.

**Comment by YouHaveTrouble** [comment]
> The performance of the API methods most of the time is no way as optimized as using direct nms.

You're not wrong here, but I believe using one single module for 1.13+ instead of nms modules for each supported version would save more cpu cycles and memory from loading all of that classes (yep, they are still being loaded into jvm, even if not used and yep, we're talking about the difference in cpu cycles, that's how insignificant that is for serializing usecase). Other then that add a perk of not having to update that module since it's not very likely we're gonna get second flattening.

**Comment by OmerBenGera** [comment]
> > The performance of the API methods most of the time is no way as optimized as using direct nms.
> 
> You're not wrong here, but I believe using one single module for 1.13+ instead of nms modules for each supported version would save more cpu cycles and memory from loading all of that classes (yep, they are still being loaded into jvm, even if not used and yep, we're talking about the difference in cpu cycles, that's how insignificant that is for serializing usecase). Other then that add a perk of not having to update that module since it's not very likely we're gonna get second flattening.

You're talking here about classes loading to the JVM? Really? Thats really not gonna affect anything, your server is more powerful than you think. If you want to eliminate lag, we should use methods and code that takes as least time as possible - and if it means to use nms, thats what I will do.

**Comment by YouHaveTrouble** [comment]
Notice how I brought it up only after you started going about performance. And I agreed with you there, but responded with providing an example of what insignificant that is for serialization. My point is to remove the loading of legacy support classes on a modern server for basically no reason. If you need help with that, I'm happy to provide. Somehow worldedit doesn't use legacy compat layer in their schematic serialization/deserialization and I didn't ever seen anyone saying their schematics load too slow.

**Comment by OmerBenGera** [comment]
> Notice how I brought it up only after you started going about performance. And I agreed with you there, but responded with providing an example of what insignificant that is for serialization. My point is to remove the loading of legacy support classes on a modern server for basically no reason. If you need help with that, I'm happy to provide. Somehow worldedit doesn't use legacy compat layer in their schematic serialization/deserialization and I didn't ever seen anyone saying their schematics load too slow.

WorldEdit is awful in performance. As I said, the usage of the "legacy layer" is because of the methods I use, which are better in performance than the rest.
Performance is the first priority, and if it means the plugin will use "legacy" methods, then that's what will be used.

Anything else I can help you with?

**Comment by YouHaveTrouble** [comment]
Forget it, I'll just fork and ip it out myself then
