### ISSUE TITLE
Splash potions bypassing island protection

### ISSUE THREAD

**Issue by JShin39** [BG-Software-LLC/SuperiorSkyblock2#1235]
### Minecraft's Version

This server is running Paper version git-Paper-39 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 37afe98)

### Plugin's Version

SuperiorSkyblock2 version 1.11.0

### Describe the bug

Players can harm other players' island animals using splash potions such as poison.

### To Reproduce

Throwing splash poison at animals.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
