### ISSUE TITLE
Island Missions

### ISSUE THREAD

**Issue by olivervincent** [BG-Software-LLC/SuperiorSkyblock2#1236]
### Minecraft's Version

1.19 Paper

### Plugin's Version

1.11.0.696

### Describe the bug

When a member of an island enters the nether/triggers the schematic paste event, which would give the money and completion of the explorer I mission. It doesn't. The money to complete the mission is given to the owner of the island, not the member. And the member is now not able to complete that mission.

Right now I assume the explorer missions are only able to complete by the owner of the island.

### To Reproduce

^^

**Comment by olivervincent** [comment]
> Island missions are co-operative between the island members, therefore if one member completes it, no one else can. I agree that the money should go towards the member's bank instead tho.
> 
> 
> 
> Show me how you configured the mission.

It's the default missions. Nothing changed. 

Also, the progress like slayer, it says I have killed 14 blazes, where my co-member it says another number.

These stats don't follow eachother. Shouldn't they if the missions is co-operative? And show as completed at all players, if a co-member completes a mission.

**Comment by olivervincent** [comment]
Another issue regarding the Explorer 2 mission, going to the end.
As a member I went through the portal as the first person. I didn't get the mission completed (prob. because the nether mission isn't completed for me either?), and neither did the island owner, after he went through after me.

**Comment by olivervincent** [comment]
I can confirm, that it's not co-op missions, it's individual..

**Comment by OmerBenGera** [comment]
Send me how you configured the mission by uploading it to pastebin and send a link here.

**Comment by olivervincent** [comment]
> Send me how you configured the mission by uploading it to pastebin and send a link here.
[missions.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9076368/missions.zip)

**Comment by OmerBenGera** [comment]
Your missions are not set with `island: true`, therefore it's different for each player in the island - both slayer and explorer.
You might want to change that.

I don't see a bug here.
