### ISSUE TITLE
Placeholder Top

### ISSUE THREAD

**Issue by deanle8** [BG-Software-LLC/SuperiorSkyblock2#1238]
### Minecraft's Version

1.18.2

### Plugin's Version

version 1.11.0

### Describe the bug

I'm getting an error when parsing placeholder top , like not being able to parse without player data
EG: %superior_island_top_worth_value_2%
-> No 2nd player data
Logs: https://pastes.dev/Gza4Rle0FS

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.
