### ISSUE TITLE
Placeholder bug

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1240]
### Minecraft's Version

1.18.2

### Plugin's Version

1.11.0.706 dev build

### Describe the bug

The top level position placeholder isn't working with the location option:

Normal placeholder: %superior_island_top_level_position% 
Location placeholder: %superior_island_location_top_level_position%

Tried switching the word location to some places but I couldn't make it work.

### To Reproduce

Do /papi parse me %superior_island_location_top_level_position% when visiting an island.

### Additional Information

It just returns a blank message.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
