### ISSUE TITLE
Ender Dragon gone

### ISSUE THREAD

**Issue by olivervincent** [BG-Software-LLC/SuperiorSkyblock2#1243]
### Minecraft's Version

paper 1.19

### Plugin's Version

1.11.0.696

### Describe the bug

When going to the end for the first time, if you go back to your island, then re-enter the Dragon is gone.
There is still a boss bar, but the dragon is gone.

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by olivervincent** [comment]
> Check out latest dev build, let me know if it works.

The ender dragon is back now. Seems to work.
