### ISSUE TITLE
Player warps 

### ISSUE THREAD

**Issue by Kub1sEej** [BG-Software-LLC/SuperiorSkyblock2#1244]
### Minecraft's Version

Yatopia 1.16.5

### Plugin's Version

SuperiorSkyblock2-1.11.0-b706

### Describe the bug

In this version SuperiorSkyblock2-1.11.0-b706, player warps do not work properly. And in SuperiorSkyblock2-1.10.2 it works fine. When I want to change the warp material e.g. diamond, it says invalid material. The video posted shows it -> https://www.youtube.com/watch?v=N546OGKCFlE

### To Reproduce

Idk what message type here

### Additional Information

we

**Comment by Kub1sEej** [comment]
No, i am from Czech Republic

**Comment by OmerBenGera** [comment]
> No, i am from Czech Republic

My guess is that you have a custom letter that when you upper-case it, it's not the same as in english. A good example for it is Turkish, as it has 2 versions of i: https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

Probably the case for you as well.

**Comment by dan28000** [comment]
When i was looking into code I didn't find much about this setting (maybe I missed it somewhere?) We will look into it tomorrow probably

But you are just taking the input from the chat and uppercasing it right? Nothing works even -cancel so maybe I think could be something to do with chatformating maybe?
(I'm from him)

**Comment by OmerBenGera** [comment]
> When i was looking into code I didn't find much about this setting (maybe I missed it somewhere?) We will look into it tomorrow probably
> 
> But you are just taking the input from the chat and uppercasing it right? Nothing works even -cancel so maybe I think could be something to do with chatformating maybe? (I'm from him)

Ah, might be your chat formatting, yes. What plugin are you using for that?

**Comment by dan28000** [comment]
It's bit complicated
Vault as base with custom plugin witch is string based and on top of that CMI for being able to click in on someone's message that brings msg command to that player

(Not sure right now but it might've worked in b674 but really not sure needs testing)

**Comment by OmerBenGera** [comment]
> It's bit complicated Vault as base with custom plugin witch is string based and on top of that CMI for being able to click in on someone's message that brings msg command to that player
> 
> (Not sure right now but it might've worked in b674 but really not sure needs testing)

In general, this can happen if the formatter is running before SSB - aka, the priority of its event is lower than SSB.
It might be an issue on my side, so first I will look into it on SSB - I will report back once I have done so

**Comment by dan28000** [comment]
After very short testing we found it's our chat formatting plugin but it was working in 1.10.2 b674
Tested also

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
