### ISSUE TITLE
Custom Menu

### ISSUE THREAD

**Issue by Tptuaazn** [BG-Software-LLC/SuperiorSkyblock2#1246]
### Minecraft's Version

Paper 1.19

### Plugin's Version

SuperiorSkyblock2-1.11.0-b706

### Describe the bug

https://discord.com/channels/554276823010246687/554282577322704896/994593278110482442

As shown in the picture, the name of the custom menu is not a subcommand.

### To Reproduce

null

### Additional Information

Can use `aliases` instead, it's not too important.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If the issue still happens, lmk
