### ISSUE TITLE
Database Malformed - Serious issue

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/SuperiorSkyblock2#1250]
### Minecraft's Version

1.8.8

### Plugin's Version

SuperiorSkyblock2-1.11.0-b716.jar

### Describe the bug

The database of SuperiorSkyblock2 was malformed and caused peoples islands to disappear and have sections of islands that where missing. Here is the error that spammed about 50 times a second. https://paste.helpch.at/ahinorosek.md

### To Reproduce

N/A

**Comment by OmerBenGera** [comment]
Your db was malformed, therefore data was not loaded / corrupted.
There is no solution for that, just load a backup.
