### ISSUE TITLE
Bank Balance Not Showing Properly

### ISSUE THREAD

**Issue by noulalu** [BG-Software-LLC/SuperiorSkyblock2#1251]
### Minecraft's Version

Server Version 1.8.8 
Plugin Jar Version: 1.11.0
Spigot

### Plugin's Version

1.11.0

### Describe the bug

The bank doesnt show, it only shows:
![image](https://user-images.githubusercontent.com/92051998/178191439-364130cf-89d6-4969-8d09-a958bacf62bb.png)

### To Reproduce

Open bank, and put your cursoron the paper.

**Comment by OmerBenGera** [comment]
Install PlaceholderAPI
