### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by Sulphinx** [BG-Software-LLC/SuperiorSkyblock2#1254]
### Minecraft's Version

1.8.8 Paper

### Plugin's Version

Superiorskyblock 1.11.0

### Describe the bug

When starting my server with superiorskyblock i get 3 NullPointerExceptions
[message (1).txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9091233/message.1.txt)

### To Reproduce

Remove the nullpointerexception i guess, i dont understand java spigotmc very good.

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed
