### ISSUE TITLE
Error creating island.

### ISSUE THREAD

**Issue by bellaclever** [BG-Software-LLC/SuperiorSkyblock2#1261]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

1.11.0

### Describe the bug

[error.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9112859/error.txt)
It gives an error while creating the island, when I delete the nashor-engine file and try again, it doesn't work.

### To Reproduce

It gives an error while creating the island, when I delete the nashor-engine file and try again, it doesn't work.

### Additional Information

It gives an error while creating the island, when I delete the nashor-engine file and try again, it doesn't work.

**Comment by OmerBenGera** [comment]
You have an issue with your nashorn engine.
Use purpur or another external nashorn plugin provider.

This cannot be fixed on SSB's side.
