### ISSUE TITLE
Command cooldowns do not work

### ISSUE THREAD

**Issue by gary81013** [BG-Software-LLC/SuperiorSkyblock2#1262]
### Minecraft's Version

paper-1.18.1-216

### Plugin's Version

SuperiorSkyblock2-1.11.0

### Describe the bug

I set it but it doesn't work
  rename:
     cooldown: 86400000
     bypass-permission: superior.cooldown.bypass.rename

### To Reproduce

I set it but it doesn't work
  rename:
     cooldown: 86400000
     bypass-permission: superior.cooldown.bypass.rename
/is rename

**Comment by OmerBenGera** [comment]
There is indeed an issue with setting cooldown to aliases of command and not their main label.
For `rename`, use `name` instead.

I will make sure it's patched so it works with any alias of the command.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
