### ISSUE TITLE
"You cannot hit players inside islands" message gets sent when hitting a vanished player (SuperVanish)

### ISSUE THREAD

**Issue by outsparkled** [BG-Software-LLC/SuperiorSkyblock2#1265]
### Minecraft's Version

CraftBukkit version git-SparkingPaper-"d29ae42" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

NOTE: SparklingPaper is a Paper fork which makes only minor changes. The issue also exists on Paper.

### Plugin's Version

1.11.0

### Describe the bug

When a player hits a vanished player using SuperVanish inside an island with pvp disabled, the "You cannot hit players inside islands" message is shown, "giving away" the vanished player.

### To Reproduce

1. get 2 players on a server with both SuperiorSkyblock2 and SuperVanish installed
2. get both players on an island with pvp disabled
3. one player vanishes with /v
4. the other player hits the location of the vanished player
5. a message ("You cannot hit players inside islands") is shown to the non-vanished player, which can be problematic, for example when a server administrator teleports to a player while vanished.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by outsparkled** [comment]
That fixed it, thank you! :D
