### ISSUE TITLE
Teleported to the corner of blocs

### ISSUE THREAD

**Issue by Cr4zyGeek** [BG-Software-LLC/SuperiorSkyblock2#1266]
### Minecraft's Version

1.17.1

### Plugin's Version

SuperiorSkyblock2-1.11.0

### Describe the bug

Can't define the spawn.location with decimal numbers like this :
```yml
location: spawn, -25.5, 41.0, 15.5, -90.0, 20.0
```
This configuration will result by spawning at -26, 41.0, 16, -90.0, 0.0

This problem seems to be for all teleportation systems.

### To Reproduce

-

**Comment by Cr4zyGeek** [comment]
Effectively the plugin adjusts the localtion but not for all the teleportations
Actually :
- when you disband your island you will be teleported on the corner of the bloc at the spawn.location
- when you do /is visit <player/name> you will be teleported on the corner of the bloc where the sign is
- ...

**Comment by OmerBenGera** [comment]
- I disbanded my island and got teleported to the center of the block of the spawn.
- Both actions teleport the player to the corner of the block, which I will fix.

**Comment by Cr4zyGeek** [comment]
I didn't tried all the teleportations of the plugin, so it's possible some other one do the same thing

**Comment by OmerBenGera** [comment]
The one that you reported is fixed in latest dev build.
If you find other ones, report them here by opening new issues.

I am closing this one :)
