### ISSUE TITLE
Some performance issues

### ISSUE THREAD

**Issue by Hyronymos1337** [BG-Software-LLC/SuperiorSkyblock2#1269]
### Minecraft's Version

1.19 purpur

### Plugin's Version

latest dev build

### Describe the bug

https://spark.lucko.me/YKXBYloh8y

### To Reproduce

https://spark.lucko.me/YKXBYloh8y

**Comment by OmerBenGera** [comment]
The lag you report is from the crops upgrade - which makes sense, as it makes many more block updates, block grows, etc.
Not something that can be fixed within the plugin, therefore I am closing this one

Thanks for the report :)

**Comment by totKing** [comment]
Please check their statement.
With the latest stable version 1.11.0 no TPS drops occur.

**Comment by OmerBenGera** [comment]
> Please check their statement. With the latest stable version 1.11.0 no TPS drops occur.

Nothing was changed in that manner, it just depends on how many active islands there are.
