### ISSUE TITLE
Why does the SuperiorSkyblock plugin crash after turning on the server?

### ISSUE THREAD

**Issue by sktom1314** [BG-Software-LLC/SuperiorSkyblock2#1273]
### Minecraft's Version

1.18.2

### Plugin's Version

SuperiorSkyblock2-1.11.0-b700.jar

### Describe the bug

Why does the SuperiorSkyblock plugin crash after turning on the server?

### To Reproduce

Why does the SuperiorSkyblock plugin crash after turning on the server?

### Additional Information

Why does the SuperiorSkyblock plugin crash after turning on the server?[]
[crash-2022-07-15_22.18.58-server.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9126959/crash-2022-07-15_22.18.58-server.txt)

**Comment by OmerBenGera** [comment]
This issue is fixex with latest dev build of the plugin
