### ISSUE TITLE
/admin bypass not functioning as intended, cannot interact with interactive blocks with the feature enabled.

### ISSUE THREAD

**Issue by Elekktrouus** [BG-Software-LLC/SuperiorSkyblock2#1274]
### Minecraft's Version

This server is running Paper version git-Paper-59 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b58063a)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads

### Plugin's Version

1.11.0.720 Dev Build

### Describe the bug

/is admin bypass does not affect interactable blocks in islands, cannot break or interact with chests, trapdoors, fences, doors, gates, etc. on a protected island/spawn, even with /is admin bypass ENABLED.

### To Reproduce

Place down any number of interactive blocks in an island you do not have permissions to with /is admin bypass on and break/interact with them.

### Additional Information

YouTube clip of the bug with necessary info:
https://www.youtube.com/watch?v=Fu4Vx0iSPxs&t=4s

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
