### ISSUE TITLE
Why does the SuperiorSkyblock plugin crash after turning on the server?

### ISSUE THREAD

**Issue by sktom1314** [BG-Software-LLC/SuperiorSkyblock2#1275]
### Minecraft's Version

1.18.2

### Plugin's Version

paper-1.18.2-387

### Describe the bug

Why does the SuperiorSkyblock plugin crash after turning on the server?

### To Reproduce

Why does the SuperiorSkyblock plugin crash after turning on the server?

### Additional Information

Why does the SuperiorSkyblock plugin crash after turning on the server?

https://pastebin.com/fkYrCGK5
[](url)https://pastebin.com/fkYrCGK5
[crash-2022-07-17_10.55.03-server.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9127361/crash-2022-07-17_10.55.03-server.txt)

**Comment by OmerBenGera** [comment]
Update the plugin to latest dev build, the issue was already been fixed
