### ISSUE TITLE
Blocks unloaded in the nether aren't added to Island Worth

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1276]
### Minecraft's Version

Current: git-Purpur-1715 (MC: 1.19)*

### Plugin's Version

SuperiorSkyblock2 version 1.11.0.688

### Describe the bug

If you have a ton of valuable blocks like diamond blocks in the nether, and your in the overworld and the islands get recaclulated, the blocks in the nether don't get calculated into the worth. You have to go into the nether world and then do /is recalc for it to be added.

### To Reproduce

Make an island, unlock nether world, place valuables in the nether, unload the nether, recaclulate island worth.

**Comment by OmerBenGera** [comment]
Update SSB, already been fixed.
