### ISSUE TITLE
Void Teleport not working in Spawn

### ISSUE THREAD

**Issue by granpacho** [BG-Software-LLC/SuperiorSkyblock2#1282]
### Minecraft's Version

1.17.1 Paper-402

### Plugin's Version

1.11.0.720

### Describe the bug

In spawn world only, when you jump into the void you do not get teleported back to spawn. I thought this was a feature before but I might be mistaken.

### To Reproduce

Jump into the void

### Additional Information

Config: https://pastebin.com/hLXApTRV

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
