### ISSUE TITLE
Island Creation Issue

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#1283]
### Minecraft's Version

This server is running ReliableSpigot version 2.4.4 (MC: 1.8.8) (Implementing API version 1.8.8-R0.3)

### Plugin's Version

Build #720

### Describe the bug

When i try to create an island nothing happens and when i do it again it says you are already in an island and that error in that link shows up

### To Reproduce

I don't know

### Additional Information

https://pastebin.com/4uxSE7uT

**Comment by OmerBenGera** [comment]
For no reason, ReliableSpigot has a method called "getChunkAtAsync", which fails to be executed.
Contact them regarding this, it doesn't seem like an issue with SSB.
If they say otherwise, tell them to comment here so we can discuss about a fix for this issue

**Comment by DebuffPvP** [comment]
I'm waiting till he replies

**Comment by DebuffPvP** [comment]
He fixed it
