### ISSUE TITLE
PostgreSQL do not work

### ISSUE THREAD

**Issue by Cr4zyGeek** [BG-Software-LLC/SuperiorSkyblock2#1284]
### Minecraft's Version

1.17.1

### Plugin's Version

SuperiorSkyblock2-1.11.0

### Describe the bug

When I try to configure the plugin with PostgreSQL it make the plugin crash at the start of the server

### To Reproduce

-

### Additional Information

https://pastebin.com/C7uQYaE8

**Comment by OmerBenGera** [comment]
It serms like the plugin couldnt connect to your sql server.
Are you sure its up and running correctly, and that you configured the correct credentials?

**Comment by Cr4zyGeek** [comment]
I have some other plugins running with Postgre so I think I could say it's up and running correcty
And I checked 3 times the credentials

**Comment by OmerBenGera** [comment]
Did you set the database type to "PostgreSQL"?

**Comment by Cr4zyGeek** [comment]
Yeah sûre

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if works now.

**Comment by Cr4zyGeek** [comment]
It's still not working but the error is different
https://pastebin.com/xy4cufvm

**Comment by OmerBenGera** [comment]
> It's still not working but the error is different https://pastebin.com/xy4cufvm

Do you have another plugin or something that has the PostgreSQL driver shaded into it?
SSB doesn't have the driver shaded and it assumes you already have it.

**Comment by Cr4zyGeek** [comment]
I have Luckperms running with PostgreSQL on all my network so yeah ?

**Comment by OmerBenGera** [comment]
> I have Luckperms running with PostgreSQL on all my network so yeah ?

If it's running on the proxy instance, then no - you don't have a plugin on the spigot server that has the driver.

**Comment by Cr4zyGeek** [comment]
It's running on proxy and all the spigot

**Comment by OmerBenGera** [comment]
> It's running on proxy and all the spigot

Well, you are clearly miss the driver.
I'd say just use MySQL or SQLite, the easiest solution for you.

**Comment by OmerBenGera** [comment]
I decided to get rid of PostgreSQL as even if you had driver, it wouldn't work due to missing features that the plugin currently uses.
Maybe in the future I'll be able to add support for that again :)
