### ISSUE TITLE
Spawner rates not working

### ISSUE THREAD

**Issue by DeludedMC** [BG-Software-LLC/SuperiorSkyblock2#1287]
### Minecraft's Version

Spigot 1.12

### Plugin's Version

1.11.0

### Describe the bug

The spawner rates upgrade only works on one spawner at a time

For example, if I do /island admin setspawnerrates (island) 20 for a 20x spawner speed buff
And I have 2 spawners on my island, a villager and an iron golem for example, only one spawner will receive that 20x buff, not both

### To Reproduce

/island admin setspawnerrates (island) (amount)
then place 2 or more different spawners

the multi will only work for one spawner at a time

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by DeludedMC** [comment]
Tried it with dev build #737 (latest), still doesn't work

**Comment by DeludedMC** [comment]
https://gyazo.com/d79bb52af750699571563b08001d768c

**Comment by DeludedMC** [comment]
Nvm its been fixed ty

**Comment by OmerBenGera** [comment]
> Nvm its been fixed ty

Great :)
If it occurs again lmk
