### ISSUE TITLE
Mission Cache Reward  -- No Island 

### ISSUE THREAD

**Issue by seanm-cloud** [BG-Software-LLC/SuperiorSkyblock2#1288]
### Minecraft's Version

1.18.2 Pufferfish (Latest) 

### Plugin's Version

SuperiorSkyblock2 v1.11.0

### Describe the bug

https://pastebin.com/Q7fDEfSq

### To Reproduce

SuperiorSkyblock was caching island mission first-invite reward and it generated an exception since they didn't have an island. Why is it caching users that do not have a island for rewards? 
https://pastebin.com/Q7fDEfSq

**Comment by OmerBenGera** [comment]
Upload your `first-invite` mission to pastebin and send it here

**Comment by seanm-cloud** [comment]
File is shown below: 
https://pastebin.com/7dPuuNSu

**Comment by OmerBenGera** [comment]
You configured it so the invite mission will be rewarded be the player that is being invited, then why did you configure jt to be an island mission (island: true)? No one ensures you the player that is being invited has an island already.

Fix your mission configuration and it will be fixed.
