### ISSUE TITLE
Placeholder from PlaceholderAPI don't parse

### ISSUE THREAD

**Issue by Tyguh** [BG-Software-LLC/SuperiorSkyblock2#1294]
### Minecraft's Version

PaperSpigot 1.8.8

### Plugin's Version

1.11.0.-b731

### Describe the bug

Placeholders from PlaceholderAPI aren't parsing in the lore of items in menus.

### To Reproduce

Add a placeholder from PlaceholderAPI to the lore of an item in value.yml and open the menu, it'll just return the text instead of the parsed value.

### Additional Information

![image](https://user-images.githubusercontent.com/11821057/180627808-12eb5c7a-d7ba-43f8-98f5-4d00875da732.png)
![image](https://user-images.githubusercontent.com/11821057/180627822-f8d32f9a-ed9a-4aee-a022-355cb6089c5a.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
