### ISSUE TITLE
/is tp While falling gives fall damage

### ISSUE THREAD

**Issue by granpacho** [BG-Software-LLC/SuperiorSkyblock2#1297]
### Minecraft's Version

1.17.1 Paper-402

### Plugin's Version

SuperiorSkyblock 1.11.0.720

### Describe the bug

If you fall, and you teleport with an island command, you take fall damage. 

### To Reproduce

Fall in void then do /is tp and you take fall damage/die

**Comment by OmerBenGera** [comment]
Thats not an issue with the plugin, it will happen with every type of teleportation. This is how the game is coded - you cant escape from taking fall damage like this.
