### ISSUE TITLE
Spawners performance issue

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1298]
### Minecraft's Version

1.18.2
Purpur #1632

### Plugin's Version

Latest dev build #737

### Describe the bug

Performance issue with superiorskyblock2 and spawners
https://spark.lucko.me/1uzCd5XiC5
### To Reproduce

Place spawners and wait

**Comment by OmerBenGera** [comment]
This happens because of one of the recent commits, causing chunks to get loaded again and cause lag.
I will fix it in the weekend

**Comment by DuckyDou** [comment]
Oh thanks, what dev build i need to use for now? Because server is unstable

**Comment by OmerBenGera** [comment]
> Oh thanks, what dev build i need to use for now? Because server is unstable

Build 728.
Downgrading is at your own risk.

**Comment by DuckyDou** [comment]
Thanks!

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed.
If the issue still happens, lmk.
