### ISSUE TITLE
Islands permissions reset every server restart

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/SuperiorSkyblock2#1301]
### Minecraft's Version

1.18.2 Purpur-1628

### Plugin's Version

1.11.0.728

### Describe the bug

I have plugin KGenerators which supports SuperiorSkyblock2.
Its adds 3 new island permissions but these permissions resets every server restart and its only for leader by default, so players have to set this again every day.
Author of this plugin said that this is SuperiorSkyblock2 bug.

### To Reproduce

Change island permissions for KGenerators and restart server (its not saving).

**Comment by OmerBenGera** [comment]
How does the plugin register their custom privileges?

**Comment by Envqu** [comment]
Sorry but I don't really know
https://github.com/Kryniowesegryderiusz/KGenerators

**Comment by OmerBenGera** [comment]
> Sorry but I don't really know https://github.com/Kryniowesegryderiusz/KGenerators

I will look into it, thanks :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works
@Envqu

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed.
If the issue still happens, lmk.
