### ISSUE TITLE
Nether Mobs Spawned with SSB schematic are invincible

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#1307]
### Minecraft's Version

paper dev 81 1.19

### Plugin's Version

Dev 743

### Describe the bug

Mobs are invincible when they are included in the base schematic for the island

### To Reproduce

I simply create an island, go to nether, and try to attack the mobs.

### Additional Information

https://www.youtube.com/watch?v=fY7nT-3rt2o
[schematic.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9228063/schematic.zip)

**Comment by OmerBenGera** [comment]
Try replicating the issue when only SSB is installed

**Comment by Skizzles** [comment]
> Try replicating the issue when only SSB is installed

Was able to confirm with just SSB

**Comment by OmerBenGera** [comment]
Update spigot/Paper to 1.19.1, as I can't replicate the issue myself.
If it still occurs, please send me your nether schematic so I can check it out

**Comment by Skizzles** [comment]
> Update spigot/Paper to 1.19.1, as I can't replicate the issue myself. If it still occurs, please send me your nether schematic so I can check it out

This seems fixed after updating up to 1.19.2 and further updating SSB. Can't confirm the issue further and will close for ya
