### ISSUE TITLE
The players only can enter the nether in creative mode.

### ISSUE THREAD

**Issue by rozsos23** [BG-Software-LLC/SuperiorSkyblock2#1309]
### Minecraft's Version

1.17.1

### Plugin's Version

SuperiorSkyblock2-1.11.0-b740

### Describe the bug

The players only can enter the nether in creative mode.

### To Reproduce

I placed the obsidian and I couldn't enter in survival mode

### Additional Information

https://youtu.be/44ktZZKvC5w

**Comment by OmerBenGera** [comment]
I can't watch the video as it's private and I tried to replicate my issue myself but it works just fine for me.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If the issue still occurs, lmk
