### ISSUE TITLE
End Island won't be generated

### ISSUE THREAD

**Issue by Tron2x** [BG-Software-LLC/SuperiorSkyblock2#1310]
### Minecraft's Version

1.19.1

### Plugin's Version

1.11.0

### Describe the bug

When a new player is activating a new portal and jumps in it, nothing happens. 
This is since Update to MC 1.19 excisting Portals are workin' normally.

### To Reproduce

create a new island - (unlock end world) - create an endportal -  jump in 

### Additional Information

maybe this exception helps? 
![image](https://user-images.githubusercontent.com/110622539/182897332-cd01f8da-ec6c-4f00-bbb6-34cf834b5304.png)

**Comment by OmerBenGera** [comment]
Update to latest dev build
