### ISSUE TITLE
Disable lava flow cause water not to flow correctly

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1312]
### Minecraft's Version

pufferfish 1.17.1

### Plugin's Version

b759

### Describe the bug

If you disable lava flow, in some case it will also disable water flow, like in this example below

### To Reproduce

https://youtu.be/ULabzAaU0YA

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
