### ISSUE TITLE
Biome placeholder error

### ISSUE THREAD

**Issue by DarkOakHD** [BG-Software-LLC/SuperiorSkyblock2#1313]
### Minecraft's Version

1.8.8

### Plugin's Version

1.11.1 b759

### Describe the bug

When you put the biome placeholder in a menu (%superior_island_biome%) you get a error.
https://pastebin.com/vvRdkiBF

### To Reproduce

Put the "%superior_island_biome%" in any menu probably. For me it was in the control-panel.yml.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by DarkOakHD** [comment]
Works
