### ISSUE TITLE
Spawner Error

### ISSUE THREAD

**Issue by SalvatoreZx** [BG-Software-LLC/SuperiorSkyblock2#1314]
### Minecraft's Version

paper-1.18.2

### Plugin's Version

8.13.8

### Describe the bug

https://pastebin.com/VbSj5fyx

### To Reproduce

I placed a spawner and i got the error in my console

**Comment by OmerBenGera** [comment]
Update to latest dev build, should be fixed already.

**Comment by SalvatoreZx** [comment]
Thank you

**Comment by SalvatoreZx** [comment]
https://pastebin.com/zB5v5Rjc nope the same :(

**Comment by SalvatoreZx** [comment]
Thank you!

**Comment by OmerBenGera** [comment]
Let me know if it works

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, lmk
