### ISSUE TITLE
Nether Portal error

### ISSUE THREAD

**Issue by DarkOakHD** [BG-Software-LLC/SuperiorSkyblock2#1316]
### Minecraft's Version

1.8.8

### Plugin's Version

1.11.1 build 764

### Describe the bug

https://pastebin.com/wWiknEDm

When nether is disabled in config, i get this error.
That doesn't happen for the end portal though.

### To Reproduce

Create a nether portal, and go into the portal.

**Comment by OmerBenGera** [comment]
Did you disable only SSB's nether or the entire nether dimension in server.properties (or both)?

**Comment by DarkOakHD** [comment]
> Did you disable only SSB's nether or the entire nether dimension in server.properties (or both)?

I only disabled the SSB's nether.

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, lmk
