### ISSUE TITLE
Superior causing lags

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1317]
### Minecraft's Version

1.18.2

### Plugin's Version

1.11.1.766 dev build

### Describe the bug

I've noticed that superiorSkyblock is the #1 plugin that consumes the most. After updating from dev buld 605 to 766 I've noticed that superior was taking way more than usual and I saw  multiple things that were not in the timings before.

Also I was wondering what could I do to optimize it ? 

![image](https://user-images.githubusercontent.com/62576432/184548475-ea5aa791-b8c0-4141-9a37-f87854bc4f7e.png)

### To Reproduce

260 players on 

### Additional Information

If you need the spark link I can send it in dms

**Comment by OmerBenGera** [comment]
Nothing to do regarding this, this is your crops multiplier.
Also, it only takes around 3% which is a reasonable value, especially when you have 260 players on your server.

**Comment by LuluxClient** [comment]
> Nothing to do regarding this, this is your crops multiplier. Also, it only takes around 3% which is a reasonable value, especially when you have 260 players on your server.

Well I've been doing multiple sparks and the "IslandFlagsListener$PaperListener.onEntitySpawn()" just appeared out of no where after updating. Why does it uses soo much. SuperiorSkyblock is 3-4 times more laggy than any other plugins I have atm. the second most laggiest plugin only takes 0.9% 

![image](https://user-images.githubusercontent.com/62576432/184680514-acff770c-8640-43eb-92c1-2a80f3661727.png)


What changed for that flag to consume sooo much and how can I resolve it.

**Comment by LuluxClient** [comment]
Before updating it consumes way less than now: (screenshot of spark before updating Superior)
![image](https://user-images.githubusercontent.com/62576432/184680818-93a32887-a81f-478c-91b7-9a81013b78e3.png)

**Comment by LuluxClient** [comment]
My spawners aren't stacked, they don't do any island levels, default mob spawning is disabled block stacking method is from Superior and not from a 3rd plugin

**Comment by OmerBenGera** [comment]
The entities that you see is the entity limiter - every mob that is added SSB counts and makes sure it doesnt exceed the limit. The crops you see in the spark is from the crop-growth multiplier and the spawners you see is due to the spawner-rates multiplier.

I will look into optimizing the spawners more, however for the rest nothing can be done regarding this - nothing was changed regarding of entities, and the lag from crops is because a lot of crop growth can cause lag.

**Comment by OmerBenGera** [comment]
Btw, 3% for a plugin in this scale is pretty good, especially with all the things it does and tracks.
Dont expect it to be at 0 because thats just not possible.

**Comment by OmerBenGera** [comment]
Also, please send the spark link here and do not take screenshots, as I would like to investigate the spark myself as well.

**Comment by LuluxClient** [comment]
> Also, please send the spark link here and do not take screenshots, as I would like to investigate the spark myself as well.

https://spark.lucko.me/rNtkpnG96q
https://spark.lucko.me/6fdvQSLhva
https://spark.lucko.me/G1A6TiQIVE

**Comment by OmerBenGera** [comment]
About spawners -
it looks like lag comes from RoseStacker and not SuperiorSkyblock, as you can see here:
https://gyazo.com/6cd45a3299f47830833d589b0bc4cc11
https://gyazo.com/8f4a09561be1d8544db0ffef89e93935
https://gyazo.com/08d0bd9ddea861b013a7e494e090a75f

It shown under SSB as SSB registers a custom spawner tile that notifies the plugin when the spawner reaches it's final tick. However, it runs the original logic with is RoseStacker's in this case.

About the crops - I can clearly see an issue, and I will look into it. 

About entity spawning - I see an issue with it as well, it struggles with checking for islands. I will look into it.

**Comment by LuluxClient** [comment]
> About spawners - it looks like lag comes from RoseStacker and not SuperiorSkyblock, as you can see here: https://gyazo.com/6cd45a3299f47830833d589b0bc4cc11 https://gyazo.com/8f4a09561be1d8544db0ffef89e93935 https://gyazo.com/08d0bd9ddea861b013a7e494e090a75f
> 
> It shown under SSB as SSB registers a custom spawner tile that notifies the plugin when the spawner reaches it's final tick. However, it runs the original logic with is RoseStacker's in this case.
> 
> About the crops - I can clearly see an issue, and I will look into it.
> 
> About entity spawning - I see an issue with it as well, it struggles with checking for islands. I will look into it.

Ok thank you <3 ! This might be related to this issue because both of them happened after upgrade my superiorskyblock version #1323

**Comment by OmerBenGera** [comment]
I pushed a new update with some optimizations. Hopefully it will be better now

**Comment by LuluxClient** [comment]
After updating it looks a lot better

**Comment by OmerBenGera** [comment]
> After updating it looks a lot better

Send a new spark profiler if possible :)

**Comment by LuluxClient** [comment]
> > After updating it looks a lot better
> 
> Send a new spark profiler if possible :)

![image](https://user-images.githubusercontent.com/62576432/186520213-0f9d0e3b-a81b-4d7f-9c0c-a8a0844bce5f.png)

**Comment by OmerBenGera** [comment]
> > > After updating it looks a lot better
> > 
> > 
> > Send a new spark profiler if possible :)
> 
> ![image](https://user-images.githubusercontent.com/62576432/186520213-0f9d0e3b-a81b-4d7f-9c0c-a8a0844bce5f.png)

Send me a link please

**Comment by LuluxClient** [comment]
> > > > After updating it looks a lot better
> 
> > > 
> 
> > > 
> 
> > > Send a new spark profiler if possible :)
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/62576432/186520213-0f9d0e3b-a81b-4d7f-9c0c-a8a0844bce5f.png)
> 
> 
> 
> Send me a link please

https://spark.lucko.me/PtnhaaRZcv 

Also what's MobSpawnerAbstracter ? I don't have anything related to spawner value or things to accelerate it.

**Comment by OmerBenGera** [comment]
> > > > > After updating it looks a lot better
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Send a new spark profiler if possible :)
> > 
> > 
> > > 
> > 
> > 
> > > ![image](https://user-images.githubusercontent.com/62576432/186520213-0f9d0e3b-a81b-4d7f-9c0c-a8a0844bce5f.png)
> > 
> > 
> > Send me a link please
> 
> https://spark.lucko.me/PtnhaaRZcv
> 
> Also what's MobSpawnerAbstracter ? I don't have anything related to spawner value or things to accelerate it.
This is for tracking spawners for the spawner rates upgrade.
However, the lag comes from RoseStacker and not SSB in that case.

**Comment by OmerBenGera** [comment]
I pushed a new update with another optimization for the spawn check.
Anything else I can help you with?

**Comment by LuluxClient** [comment]
Beh thanks other than that the only thing remaining is the /is recalc
issue.

**Comment by OmerBenGera** [comment]
> 

That's for the other report :)
Closing this for now
