### ISSUE TITLE
Stacked Blocks

### ISSUE THREAD

**Issue by Cr4zyGeek** [BG-Software-LLC/SuperiorSkyblock2#1322]
### Minecraft's Version

1.17.1

### Plugin's Version

SuperiorSkyblock2-1.11.0-b731.jar

### Describe the bug

Impossibility to place a block against another one when he is in the stacked-blocks config list.
I mean if DIAMOND_BLOCK is in stacked-blocks list, and I want to place a DIAMOND_BLOCK againt an other DIAMOND_BLOCK, I can't because it will be stacked.
So it could be interesting if we SHIFT + CLICK or SNEAK + CLICK the block is not stacked but just placed

### To Reproduce

-

**Comment by OmerBenGera** [comment]
You can place it against another block so they will be placed next to each other, or disable the stacking mode and you will not stack blocks together at all.
