### ISSUE TITLE
Mobs spawning on island when mob flag is OFF

### ISSUE THREAD

**Issue by Monjiigames** [BG-Software-LLC/SuperiorSkyblock2#1324]
### Minecraft's Version

Paper Spigot 1.19.1 

### Plugin's Version

Dev Version 1.11.1.759

### Describe the bug

Hello, 

Players are complaining that mobs do spawn sometimes, despite having the spawning flag on. 

Here is proof that the flag is disabled 

https://cdn.discordapp.com/attachments/1008125170063523971/1008428337829511270/2022-08-14_19.33.06.png

Here is proof that mobs do spawn on islands

https://cdn.discordapp.com/attachments/1008125170063523971/1008815638548066438/2022-08-15_21.11.53.png

### To Reproduce

N/A

### Additional Information

N/A

**Comment by OmerBenGera** [comment]
What is the spawn reason they spawned with?
You can find it out if you have WildStacker installed. If not, try using the `/data` command.

**Comment by Monjiigames** [comment]
Hi Omer, 

I don't have WildStacker so unfortunately won't be able to say the spawn reason.

Also I can't seem to do /data ? It's not a command

**Comment by OmerBenGera** [comment]
> Hi Omer,
> 
> I don't have WildStacker so unfortunately won't be able to say the spawn reason.
> 
> Also I can't seem to do /data ? It's not a command

`/data` should work in 1.19.1.
Make sure you are opped.

**Comment by Monjiigames** [comment]
Hi - is there a full command entry, because /data on it's own does not work, I am OP on the server.

Like /data get entity etc - the full chain of command like this, does work. What should I run when the zombies have spawned?

**Comment by OmerBenGera** [comment]
> Hi - is there a full command entry, because /data on it's own does not work, I am OP on the server.
> 
> Like /data get entity etc - the full chain of command like this, does work. What should I run when the zombies have spawned?

You can find the command usage on google and how to use it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by exzolink** [comment]
> Any news regarding this?

Bats can spawn even if mob spawn disabled

**Comment by OmerBenGera** [comment]
What's the spawn reason of these mobs?
Have you checked it?

**Comment by OmerBenGera** [comment]
Any news regarding this?
