### ISSUE TITLE
Duplication Pigling and gold nugget

### ISSUE THREAD

**Issue by darktw596** [BG-Software-LLC/SuperiorSkyblock2#1325]
### Minecraft's Version

1.18.2

### Plugin's Version

1.110

### Describe the bug

When players have the mob loot upgrade maxed out
and that he gives gold to the piglin and kills them the gold is duplicated in large quantities
https://youtu.be/9_mK_e6RRic

### To Reproduce

Buy upgrade from loot
spawn a piglin
give him gold
To kill him
and here is the gold and duplicate

**Comment by OmerBenGera** [comment]
Your piglins don't barter the gold ingot but instead just pick it up? This is not a vanilla behavior.
Try replicating it on a server with only SSB installed, let me know if it still occurs.

**Comment by darktw596** [comment]
if he swaps it but I killed him before so with the double drop he duplicates the gold

**Comment by darktw596** [comment]
if he swaps it but I killed him before so with the double drop he
duplicates the gold

**Comment by OmerBenGera** [comment]
> if he swaps it but I killed him before so with the double drop he duplicates the gold

I don't understand. In your video, there's clearly a non-vanilla behavior of piglins.
Were you able to replicate the issue on a server with only SSB installed?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
