### ISSUE TITLE
Unable to chat or use commands

### ISSUE THREAD

**Issue by Vaspei** [BG-Software-LLC/SuperiorSkyblock2#1326]
### Minecraft's Version

1.12.2
Paper 1.12.2

### Plugin's Version

2-1.11

### Describe the bug

If one is editing the material name of their island in is top list, and leaves the game and joins back they cannot use any commands or send messages until they enter the editor again and then type -cancel, is it possible to make it force cancel  the player our of the edit menu of they log out?

but if you type in -cancel when you join back it wont work still, you would have to run the command again to get that message back to type -cancel

### To Reproduce

If one is editing the material name of their island in is top list, and leaves the game and joins back they cannot use any commands or send messages until they enter the editor again and then type -cancel, is it possible to make it force cancel  the player our of the edit menu of they log out?

but if you type in -cancel when you join back it wont work still, you would have to run the command again to get that message back to type -cancel

### Additional Information

https://youtu.be/z4yJLpyl95M

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
