### ISSUE TITLE
"block stacking" toggle doesn't work

### ISSUE THREAD

**Issue by moonies44** [BG-Software-LLC/SuperiorSkyblock2#1327]
### Minecraft's Version

1.18.2 paper R0.1-SNAPSHOT

### Plugin's Version

1.11.1

### Describe the bug

Hi there,
when using the command /island toggle blocks, (which is block stacking) blocks stack regardless of this setting being disabled by a user. so stacks always block no matter what. 

### To Reproduce

use /island toggle blocks and enable or disble. for both options, blocks still stack when it should of been disabled.

### Additional Information

https://user-images.githubusercontent.com/66435479/186227101-9bb9e539-3d59-48c8-ab5d-553a42e4e903.mp4

**Comment by OmerBenGera** [comment]
I can't replicate the issue using latest dev build

**Comment by moonies44** [comment]
resolved by updating to the newest versions, unsure why. thank you for the time
