### ISSUE TITLE
Leaves decaying on islands

### ISSUE THREAD

**Issue by OGreenC** [BG-Software-LLC/SuperiorSkyblock2#1328]
### Minecraft's Version

paper-1.17.1-411.jar

### Plugin's Version

SuperiorSkyblock2-1.11.1-b759.jar

### Describe the bug

Leaves are decaying from start island (custom schematic)

Please see Gif Below:
https://gyazo.com/812f3a5f599143b1dd58dc3f96b5666e 

### To Reproduce

I created a schematic using the inbuilt schematic tool, and an island with said schematic.

I even tried setting up a test server, with limited plugins enabled, to test if it where still happening.
I testet with default config of SuperiorSkyblock, with the only change being that I added my custom schematic to the schematic folder and island-creation menu, and the issue was still present.

Please see attached image below, for installed plugins on the test server, where the problem was still happening.
![image](https://user-images.githubusercontent.com/46462998/186523577-7989be95-1f44-43db-9d65-69cf9d720e01.png)

**Comment by OmerBenGera** [comment]
Make sure your laves dont have the "decayable" tag, otherwise they will decay. The plugin does not prevent leaves from decaying, its up to you to make them not decayable.
