### ISSUE TITLE
Ghost chunks

### ISSUE THREAD

**Issue by DeludedMC** [BG-Software-LLC/SuperiorSkyblock2#1329]
### Minecraft's Version

1.8.8-R0.1-SNAPSHOP Paper

### Plugin's Version

1.11.1-b766

### Describe the bug

Whenever a player logs out in their island and then logs back in, it sends a error in console as they are logging in, and the chunk they were standing in dissapears, but then if they leave the chunk (i.e /spawn then /is go again) the chunk will come back

This only happens in islands
https://pastebin.com/E2DsYwWR
https://media.discordapp.net/attachments/966664050459164712/1012004847018582157/unknown.png

### To Reproduce

Whenever a player logs out in their island and then logs back in, it sends a error in console as they are logging in, and the chunk they were standing in dissapears, but then if they leave the chunk (i.e /spawn then /is go again) the chunk will come back

**Comment by DeludedMC** [comment]
nvm I'm dumb it was because of interactivechat

**Comment by OmerBenGera** [comment]
> nvm I'm dumb it was because of interactivechat

Yeah - it looks like they tried to get the biome of the player async, causing the chunk to not load or something.
