### ISSUE TITLE
Vanished players showing up under /is expel

### ISSUE THREAD

**Issue by LPXZIsGod** [BG-Software-LLC/SuperiorSkyblock2#1330]
### Minecraft's Version

1.18.2

### Plugin's Version

Superiorskyblock 2 1.11.1
Supervanish 6.2.11

### Describe the bug

Whenever a vanished admin/mod teleports to an island players are able to see them on /is expel which kind of ruins the feature of vanish

### To Reproduce

Its easy to reproduce, just have one account vanished and the other account with just is expel perms. The vanished account shows up on ./is expel you cannot expel them but it stil shows u vanished players.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
