### ISSUE TITLE
Upgrades/limits resetting when setting upgrade

### ISSUE THREAD

**Issue by OGreenC** [BG-Software-LLC/SuperiorSkyblock2#1331]
### Minecraft's Version

paper-1.17.1-411.jar

### Plugin's Version

SuperiorSkyblock2-1.11.1-b772.jar

### Describe the bug

I'm essentially experiencing the same bug as in #1065, where all upgrades/limits/island size, are reset to config default, upon setting a upgrade to a lower level than it previously was, using the admin command /is admin setupgrade

### To Reproduce

Please see attatched PDF, for instructions on how to reproduce.

I started a completely new Island moments before this - This is also a test server, with only Essentials, Luckperms, PlaceholderAPI & Vault installed, besides SuperiorSkyblock, of cause.

[SB2 Reproduction.pdf](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9435999/SB2.Reproduction.pdf)

My Upgrades configuration can be found here:
https://pastebin.com/6XR3EQPh

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by OGreenC** [comment]
Hi,

I'm sorry, but there still seems to be a problem.

I just succeeded in provoking the same error, doing the exact same steps as shown in the initual post, using 
``SuperiorSkyblock2-1.11.1-b778.jar``

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still happens

**Comment by OGreenC** [comment]
Hi!

Sorry for the late response.

I've not had a version of the plugin with these changes running for a few days, and I've not head anyone complain about loosing progress on their upgrades / island properties so far.

Thank you! :-)

**Comment by OmerBenGera** [comment]
Awesome, glad to hear.
If this happens again let me know
