### ISSUE TITLE
Nether Mobs still invincible when spawned in from schematics

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#1333]
### Minecraft's Version

1.19.2 Purpur dev 1768

### Plugin's Version

SSB dev 778

### Describe the bug

Mobs are invincible when they are included in the base schematic for the island

### To Reproduce

I simply create an island, go to nether, and try to attack the mobs.

### Additional Information

https://www.youtube.com/watch?v=fY7nT-3rt2o
[schematic.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9438826/schematic.zip)

**Comment by Skizzles** [comment]
This has the included schematic mentioned previously, and also was tested fully on a server with just SSB installed using the latest dev build.

**Comment by OmerBenGera** [comment]
Please provide your schematic

**Comment by Skizzles** [comment]
> Please provide your schematic

its the "schematic.zip" file in the bottom of the original post

**Comment by OmerBenGera** [comment]
> > Please provide your schematic
> 
> its the "schematic.zip" file in the bottom of the original post

Mention / link it here please

**Comment by Skizzles** [comment]
https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9438826/schematic.zip

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Try it on a server with only SSB installed, let me know if it still happens.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, let me know by replying to the issue again.
