### ISSUE TITLE
ShopGUI+ error

### ISSUE THREAD

**Issue by DarkOakHD** [BG-Software-LLC/SuperiorSkyblock2#1334]
### Minecraft's Version

1.18.2

### Plugin's Version

1.11.1 #778

### Describe the bug

I just updated the plugin and this error appeared.
From #776 to #778

I also use the latest ShopGUI+ version

https://pastebin.com/p0na3w6A

### To Reproduce

I don't know how to reproduce it...

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs

**Comment by DarkOakHD** [comment]
Fixed.
