### ISSUE TITLE
OneBlock Schematic

### ISSUE THREAD

**Issue by Ventty** [BG-Software-LLC/SuperiorSkyblock2#1336]
### Minecraft's Version

1.16.5

### Plugin's Version

SuperiorSkyblock2-1.11.1 + SSBOneBlock-1.2.1

### Describe the bug

Hi, how can I create a oneblock schematic, I am using the wiki tutorial, but when I enter island creation nothing happens and the schematic was created correctly and is in the files.

### To Reproduce

idk

**Comment by OmerBenGera** [comment]
Add your schematic to the menu file.
For further help, as on the discord.
This is the place to report bugs.
