### ISSUE TITLE
problem of delete new islands, upgrades and more after restart server

### ISSUE THREAD

**Issue by beautybloodtr** [BG-Software-LLC/SuperiorSkyblock2#1337]
### Minecraft's Version

1.8.8 InterstellarSpigot

### Plugin's Version

1.11.1

### Describe the bug

After stopping the server, SuperiorSkyblock2 does not shut down for a while and it takes about 1 hour to shut down. All island creations, island upgrades etc. related to the last 12 (presumably) SuperiorSkyblock2 are deleted when the server is shut down and restarted.

Not: my english bad so i translated this artict on google translate

### To Reproduce

i dont know what is tthis

### Additional Information

i dont have :/ i will send soon

**Comment by OmerBenGera** [comment]
Use latest dev build & use paper instead.
Let me know if it still occurs.

**Comment by beautybloodtr** [comment]
its not solved, i change my version to latest build and change my spigot to tacospigot (i used my old season and its never gived my error)

**Comment by OmerBenGera** [comment]
Show me logs from your server when you use TacoSpigot

Make aure you only have SSB installed

**Comment by beautybloodtr** [comment]
i dont have only SSB and i never do somethings for this, i will send you tomorrow night because i trying somethings

**Comment by OmerBenGera** [comment]
Run it on a server with only SSB installed then.

**Comment by beautybloodtr** [comment]
i cant but its alr did

**Comment by OmerBenGera** [comment]
> i cant but its alr did

Make a server on localhost and do it there?

**Comment by OmerBenGera** [comment]
> Dude, that's the problem. If I do this without the players or my plugins, it doesn't make any sense, the problem will probably be solved anyway.

Something causing SSB to not shut down - probably one of your plugins.
Try adding them one by one until it works again.

**Comment by beautybloodtr** [comment]
I leave my list of plugins to the link below so that you can make suggestions. I have some custom plugins and its have stabil codes so dont worry

https://hastebin.com/ekujopujar.properties

**Comment by OmerBenGera** [comment]
> I leave my list of plugins to the link below so that you can make suggestions. I have some custom plugins and its have stabil codes so dont worry
> 
> https://hastebin.com/ekujopujar.properties

Add them one by one until it occurs again.
I dont know what can cause it.

This entire issue you always refuse to do what I ask you to do. If thats gonna continue, I will have to close this issue. I cant help you if you'll keep ignoring what I say

**Comment by beautybloodtr** [comment]
I did what you said and got no results. I am dealing with lag issues not just data loss and I am sure they are caused by SuperiorSkyblock. I even tried analysis a Memory Dump file, issues consistently targeting SuperiorSkyblock

**Comment by OmerBenGera** [comment]
> I did what you said and got no results. I am dealing with lag issues not just data loss and I am sure they are caused by SuperiorSkyblock. I even tried analysis a Memory Dump file, issues consistently targeting SuperiorSkyblock

The memory file you keep showing only shows objects held by the database threads, which are obviously large as they handle the entire connection with the database. If you believe there is lag that comes from SSB, memory dump is not the tool to be used. Instead, take a spark profiler and send it here so it can be investigated.

**Comment by OmerBenGera** [comment]
However, I did change the way the plugin interacts with the database. From now on, instead of using multiple threads it will use a single thread for this. This should fix potential issues with synchronizations between the threads.

Let me know if it helps

**Comment by beautybloodtr** [comment]
i fixed this problem btw look now :D i deleted latest dev build and downloaded v1.8.4 build, this fixed my all problems lagg, data lost, stabilization haha thats ironic

**Comment by beautybloodtr** [comment]
you shared new version today, i will try tonight new dev build

**Comment by OmerBenGera** [comment]
> i fixed this problem btw look now :D i deleted latest dev build and downloaded v1.8.4 build, this fixed my all problems lagg, data lost, stabilization haha thats ironic

Downgrading for such an old version can cause your database to break, never do that on production server.

**Comment by beautybloodtr** [comment]
The island broke its banks, but it wasn't much of a problem, other than that, what else could it break?

**Comment by OmerBenGera** [comment]
> The island broke its banks, but it wasn't much of a problem, other than that, what else could it break?

some versions have a complete different database, which may lead to many things to just not load / break.
Downgrading is never a solution.

**Comment by beautybloodtr** [comment]
sooo latest dev build fix my all problems, right?

**Comment by beautybloodtr** [comment]
i didn't try yet

**Comment by OmerBenGera** [comment]
> sooo latest dev build fix my all problems, right?

Hopefully

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, let me know by replying to the issue again.
