### ISSUE TITLE
Spawner flags not working.

### ISSUE THREAD

**Issue by AllayOwner** [BG-Software-LLC/SuperiorSkyblock2#1338]
### Minecraft's Version

This server is running Paper version git-Paper-"df630a2" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### Plugin's Version

1.11 Dev Build #778 (NEWEST)

### Describe the bug

Just as the title states, when the island settings 'Spawner Monsters Spawn' & 'Spawner Animals Spawn' are disabled, the spawners are still spawning mobs & animals.

I am using RoseStacker spawners so I'm wondering if that is the issue.

### To Reproduce

When the island settings 'Spawner Monsters Spawn' & 'Spawner Animals Spawn' are disabled, the spawners are still spawning mobs & animals.

### Additional Information

Here is the data from one of the Iron Golems that were spawned from the spawners.

![image](https://user-images.githubusercontent.com/112505646/187496821-61a376cf-9042-406a-a3e7-a45620d22797.png)
![image](https://user-images.githubusercontent.com/112505646/187496853-f3394a16-428b-454e-926f-8b8154d57686.png)

**Comment by OmerBenGera** [comment]
SSB cancels the events. RoseStacker might not check for cancel status / not fire the events at all.
Probably a bug with RoseStacker, contact them.
