### ISSUE TITLE
Natural live spawns do not count from the limitation of entity-limits!

### ISSUE THREAD

**Issue by ejdzeys** [BG-Software-LLC/SuperiorSkyblock2#1342]
### Minecraft's Version

1.16.5 Paper-794

### Plugin's Version

v1.11.1.778

### Describe the bug

Hello, I have added entity-limits to the upgrade configuration.

entity-limits:
    '1':
      price: 0.0
      price-type: "Money"
      entity-limits:
        MINECART: 10
        VILLAGER: 10
        BEE: 15
        SHEEP: 15
        CREEPER: 10
        GUARDIAN: 15
        SPIDER: 10
        CAVE_SPIDER: 10
        WITHER: 2
        ZOMBIFIED_PIGLIN: 15
        BLAZE: 15
        CHICKEN: 15
        IRON_GOLEM: 15
        SKELETON: 10
        ZOMBIE: 10
        RABBIT: 15
        PIG: 15
        HORSE: 15
        SQUID: 15
        CAT: 15
        COW: 15
        WOLF: 15
        PANDA: 15
        ENDERMAN: 10
        ZOMBIE_VILLAGER: 15
        SLIME: 15
        PARROT: 15
        MUSHROOM_COW: 15
        DONKEY: 15
        SKELETON_HORSE: 15
        ZOMBIE_HORSE: 15
        FOX: 15
      commands: []

For example, when I take an egg and put it on the player's island, the limitation that I have arranged works beautifully. However, this limit does not work for natural monster spawning.

Bees are limited to 15, but there are more than 100 bees on a player's island. The same example applies to the rabbit that comes to life naturally, after killing them all, we noticed that the rabbit was born again above the limit.

I need serious help with this, because most players have more than the limit of entitys on their island, and this greatly reduces my tps and lags the game.

### To Reproduce

I became aware of this error with the constant overload of the server and investigated the islands. I have found that there are too many limited entitys and I have confirmed this with the timings report.

**Comment by OmerBenGera** [comment]
Very weird.
Does it happen when running SSB on it's own server?

**Comment by ejdzeys** [comment]
> Very weird. Does it happen when running SSB on it's own server?

Yes, I couldn't understand it either.

**Comment by OmerBenGera** [comment]
> > Very weird. Does it happen when running SSB on it's own server?
> 
> Yes, I couldn't understand it either. Could it be because I added some entitys limits later?

Probably another plugin conflicting with it.
Try adding plugins one by one until you manage to replicate the issue again.

**Comment by ejdzeys** [comment]
> Probably another plugin conflicting with it.
> Try adding plugins one by one until you manage to replicate the issue again.

I don't use any other plugin that forces or limits spawning. I just did a server optimization in paper.yml. (Related to entities)

**Comment by OmerBenGera** [comment]
> > Probably another plugin conflicting with it.
> > Try adding plugins one by one until you manage to replicate the issue again.
> 
> I don't use any other plugin that forces or limits spawning. I just did a server optimization in paper.yml. (Related to entities)

If it works fine on another server but on your server it doesnt, then something is conflicting with SSB.
Find what causes this behavior to occur and report back

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response.
If it still occurs, let me know by replying to the issue again.
