### ISSUE TITLE
mobSpawner is null

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1343]
### Minecraft's Version

Current: git-Purpur-1749 (MC: 1.19.1)*
Previous: git-Purpur-1670 (MC: 1.19)
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

1.11.1 stable

### Describe the bug

place / break spawner using RoseStacker

Error : https://gyazo.com/777fd382b7b6fb970941a648b9a61e0a

### To Reproduce

place / break spawner using RoseStacker and the error is throw sometime.

### Additional Information

RoseStacker version 1.4.13

**Comment by OmerBenGera** [comment]
Upload the error to pastebin

**Comment by SwartZCoding** [comment]
> 

https://pastebin.com/eqAbc78c

**Comment by SwartZCoding** [comment]
> Upload the error to pastebin

https://pastebin.com/eqAbc78c

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it still occurs

**Comment by SwartZCoding** [comment]
> Update to latest dev build, let me know if it still occurs

Hi ! I try this tomorrow.

**Comment by SwartZCoding** [comment]
> Update to latest dev build, let me know if it still occurs

When i try to restart with the latest version (with same conditions of this issue 1.19.2 etc etc ...) I got this 2 erreors and my server stop instantly.

https://pastebin.com/vNPzE4yE

**Comment by OmerBenGera** [comment]
Any news regarding this? Was it fixed?

**Comment by SwartZCoding** [comment]
> Any news regarding this? Was it fixed?

sorry don't have time to try it since 6 days. I try this later in the day and update you.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed.
If it still occurs let me know by replying to this issue
