### ISSUE TITLE
Island-size parameter not working

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1345]
### Minecraft's Version

Current: git-Purpur-1749 (MC: 1.19.1)*

### Plugin's Version

1.11.1 stable

### Describe the bug

When i put : island-size: 30 on my config.yml, this is not working i have an 50 radius island. So 100 blocks X 100 blocks and not 60x60.

### To Reproduce

1. Put 30 on your island-size parameter.
2. Stop the server.
3. Clear world & data to be sure it's a new island.
4. restart & create island.

### Additional Information

All my parameters about island size

max-island-size: 120
island-size: 30
size: 150

when i use : /is admin setsize name 30. Border is correct. But with default value set in config, is not.

**Comment by OmerBenGera** [comment]
If you have upgrades then you should use them instead.
