### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1348]
### Minecraft's Version

1.19.2 Purpur-1774

### Plugin's Version

latest dev build

### Describe the bug

https://pastebin.com/4jiCMFxW

### To Reproduce

Turn on server with latest dev build (791)

**Comment by SwartZCoding** [comment]
Same error reported on another issue when we try to debug something with Omer :)
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1343#issuecomment-1242669334

**Comment by dan28000** [comment]
793 build error
https://pastebin.com/eFjqbwyr

**Comment by OmerBenGera** [comment]
Fixed, check out build 794.
