### ISSUE TITLE
Mission progress isn't saving automaticaly

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1349]
### Minecraft's Version

1.19.2 purpur

### Plugin's Version

latest dev build

### Describe the bug

Curently progress of missions only saves when turning off server but if server crashes then it rollbacks to state when server started which was last saved

How to solve it add task that saves the progress currently on the server could be 10mins, 15mins combined maybe with some threshold when enought updates to progress have players done

### To Reproduce

get progress in mission and crash the server after turning back on the server your progress wont be saved

**Comment by OmerBenGera** [comment]
First of all, make sure you fix the reason of your crash. Your server should never crash.
Secondly, missions tracked data is saved every 5 minutes. Therefore, I recommend fixing the crash so it doesn't happen anymore and you will not have any data rollbacks.

**Comment by dan28000** [comment]
If it would be working then i wouldn't have last change date the time of server start
