### ISSUE TITLE
Progress of missions isn't saving every 5 mins

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1350]
### Minecraft's Version

1.19.2 purpur

### Plugin's Version

latest dev build

### Describe the bug

The saving just doesn't work every 5 minuts for progress in missions
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1349
https://drive.google.com/file/d/1m-K6sOLfrSYmTMIVLHmDUZmvxtm0U_Az/view?usp=sharing

### To Reproduce

video on google drive
tldr:
1. creating fresh server
2. create island
3. mine stone
4. wait like 5mins
5. isn't saved
6. restart server
7. mine more stone do some other missions
8. wait another 5mins still nothing

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
