### ISSUE TITLE
Island Blocks getting deleted

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1351]
### Minecraft's Version

Current: git-Purpur-1765 (MC: 1.19.2)*

### Plugin's Version

SuperiorSkyblock2 version 1.11.1.765

### Describe the bug

I made an island, went to it, built some things on it, then restarted the server. I came back, floating in empty void. I checked coords and thats where I logged off + where the island was. I tried [/guild go] (changed prefix to guild) and it gave me an internal error: https://mclo.gs/YLoubOY

### To Reproduce

I'm not entirely too sure when the blocks get deleted, but maybe a few server restarts.

**Comment by DuneSciFye** [comment]
I figured out whats going on. The blocks aren't getting deleted, its the world option in SS2's config getting set to 'SuperiorWorld' every 2 restarts. 
![image](https://user-images.githubusercontent.com/65089425/189559280-201544a7-e88d-49b9-902e-305f8041ad5b.png)

**Comment by OmerBenGera** [comment]
> I figured out whats going on. The blocks aren't getting deleted, its the world option in SS2's config getting set to 'SuperiorWorld' every 2 restarts. ![image](https://user-images.githubusercontent.com/65089425/189559280-201544a7-e88d-49b9-902e-305f8041ad5b.png)

If you change it, you must delete the database file.

**Comment by OmerBenGera** [comment]
Closing this for now, doesn't seem like a real bug.
