### ISSUE TITLE
Failed to serialize unloading chunk data

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1352]
### Minecraft's Version

Current: git-Purpur-1749 (MC: 1.19.1)*
Previous: git-Purpur-1670 (MC: 1.19)

### Plugin's Version

1.11.1.794 dev build

### Describe the bug

Don't know what happen bug i got error on my console. But i prefer report it

https://pastebin.com/yw5CPDs7

### To Reproduce

Don't know

**Comment by OmerBenGera** [comment]
I could replicate the issue as well, however I have no clue why it occurs at this moment.

**Comment by dan28000** [comment]
I've tested b790 and it's fine so it will be your mappings in build 791-793 that don't work at all at least on 1.19.2

**Comment by Skizzles** [comment]
> I could replicate the issue as well, however I have no clue why it occurs at this moment. Try contacting the Purpur team, maybe they know why such thing can occur and how it can be fixed. It also happens on Spigot, just to be clear.

Managed to reproduce as well, it happened for me on generation of the end island when the player teleports to the world and when I went to that world with /is admin tp (player name) the_end the island was not generated.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
