### ISSUE TITLE
Losing islands after having the UUID changed

### ISSUE THREAD

**Issue by ChicoIdeal** [BG-Software-LLC/SuperiorSkyblock2#1354]
### Minecraft's Version

git-Pufferfish-28 (MC: 1.19.1) 

### Plugin's Version

SuperiorSkyblock2 version 1.11.1

### Describe the bug

When creating an island having all the permissions when restarting the server permissions are removed, it appears that I do not have an island, and when returning to the coordinates appears that if I own it but I have no permissions I can not do anything.

### To Reproduce

1. Create a new island
2. Restart the server

### Additional Information

When replicating it, also if you add it as administrator when restarting it no longer appears in the list of members, it is deleted, all happened after the player used /premium, being non-premium it happens the same, the only way to have permissions is using /is coop nick

**Comment by OmerBenGera** [comment]
This occurs because you have your UUID get changed.
Do you see in console "Changing UUID of player X to.." when you join?

**Comment by OmerBenGera** [comment]
Also, what plugin do you use for the premium thingy?

**Comment by ChicoIdeal** [comment]
ok, if that's your uuid, thank you that was it

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, it works fine for me.
Are you able to replicate the issue yourself on another server with only SSB installed?

**Comment by DuckyDou** [comment]
I have same issue here.

**Comment by OmerBenGera** [comment]
> I have same issue here.

Let me know how to replicate it. 
It may happen if another plugin uses SSB's API and does not adjust its data as well, then tries to get an instance of a player that technically doesn't exist anymore. Try replicating it on a server with only SSB installed, let me know if it still happens.

**Comment by ChicoIdeal** [comment]
> > I have same issue here.
> 
> Let me know how to replicate it. It may happen if another plugin uses SSB's API and does not adjust its data as well, then tries to get an instance of a player that technically doesn't exist anymore. Try replicating it on a server with only SSB installed, let me know if it still happens.

The player must login for the first time using /login password command, then he must create an island and then use /premium to not login again with password, as his permissions data is not saved in sqlite database, I am now in ufferfish version git-Pufferfish-36 (MC: 1. 19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 58865aa on HEAD) and the error continues, the player must use another account to not lose the permissions and give his account the permissions.

**Comment by OmerBenGera** [comment]
@ChicoIdeal Try replicating the issue on a server with only SSB installed and your login plugin please

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
@ChicoIdeal Have you tried it?

**Comment by DuckyDou** [comment]
Its not a issue with ss2

**Comment by OmerBenGera** [comment]
> Its not a issue with ss2

What was the issue?

**Comment by ChicoIdeal** [comment]
> @ChicoIdeal Have you tried it?

Hello, I have managed to solve the uuid from the db, apparently when changing username in minecraft some players are not changed automatically and others if, it happens only to random players, what you have to be to solve it in changing the old uuid and rename it to null.

**Comment by OmerBenGera** [comment]
> > @ChicoIdeal Have you tried it?
> 
> Hello, I have managed to solve the uuid from the db, apparently when changing username in minecraft some players are not changed automatically and others if, it happens only to random players, what you have to be to solve it in changing the old uuid and rename it to null.

Change the name in the database to null?
Also, if you change username, it doesn't change the name automatically? How is it related?
Mind giving more details - maybe I can somehow fix it on the plugin's side

**Comment by Kocimietka7192** [comment]
Hey, I have a similar problem - 

Using FastLogin plugin.

We enter the server having a premium account, but log in as usual nonpremium account,

We create an island - set a premium account, and leave and enter the server.

After entering, the server thinks that this player does not have any island

Return to the account /cracked does not give anything.

**Comment by OmerBenGera** [comment]
> Hey, I have a similar problem -
> 
> Using FastLogin plugin.
> 
> We enter the server having a premium account, but log in as usual nonpremium account,
> 
> We create an island - set a premium account, and leave and enter the server.
> 
> After entering, the server thinks that this player does not have any island
> 
> Return to the account /cracked does not give anything.

Are you able to replicate the issue yourself with only SSB and FastLogin installed?

**Comment by OmerBenGera** [comment]
@Kocimietka7192 @DuckyDou @ChicoIdeal Check out latest dev build, let me know if it's fixed.

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue persists let me know
