### ISSUE TITLE
Breaking one block generator does not contribute to BlockMission

### ISSUE THREAD

**Issue by Technofied** [BG-Software-LLC/SuperiorSkyblock2#1355]
### Minecraft's Version

[14:22:12 INFO]: This server is running Pufferfish version git-Pufferfish-60 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 1d94256 on HEAD)

### Plugin's Version

1.11.1

### Describe the bug

Say you have a Block Mission to break 15 natural-ONLY cobblestone and you try to break the one block generator for the cobblestone, even if you break the naturally generated stone to get the cobblestone, it won't count towards the mission.

This applies for any type of block, including coal_ore, iron_ore etc.

It does however count Worldedited (//set stone) blocks oddly enough.

### To Reproduce

1. Create BlockMission to collect any amount of stone
2. Set it to natural blocks only
3. Try to break stone from the one block generator
4. Observe that it doesn't count towards your mission

### Additional Information

Here's the configuration file for the mission in question [miner_2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9548401/miner_2.txt)

**Comment by OmerBenGera** [comment]
When you say "OneBlock" you mean the block of the OneBlock addon?

**Comment by Technofied** [comment]
> When you say "OneBlock" you mean the block of the OneBlock addon?
That's correct.

**Comment by OmerBenGera** [comment]
> > When you say "OneBlock" you mean the block of the OneBlock addon?
> 
> That's correct.

Is it the official OneBlock module or something else?

**Comment by democracycraft** [comment]
> > > When you say "OneBlock" you mean the block of the OneBlock addon?
> 
> > 
> 
> > That's correct.
> 
> 
> 
> Is it the official OneBlock module or something else? 

Yes, the official OneBlock module.

**Comment by Technofied** [comment]
> > > When you say "OneBlock" you mean the block of the OneBlock addon?
> > 
> > 
> > That's correct.
> 
> Is it the official OneBlock module or something else?

Yes, the official OneBlock module.

**Comment by OmerBenGera** [comment]
Update both the plugin and OneBlock, let me know if it still occurs.
For me it worked fine with both plugins updated to latest versions.

**Comment by Technofied** [comment]
Solved, thank you for your help. The issue was the OneBlock addon was outdated.
