### ISSUE TITLE
Island commands not wroking

### ISSUE THREAD

**Issue by FuzzyWuzz59** [BG-Software-LLC/SuperiorSkyblock2#1358]
### Minecraft's Version

1.19.1

### Plugin's Version

1.11.1

### Describe the bug

when a player logs onto the server and tried to create an island using /is create they get an  error msg "unknown command".
This has reproduced by several players. The island warps also do not work.

### To Reproduce

Not sure what you mean. I de-op'd my payer and had the exact same isues.

**Comment by OmerBenGera** [comment]
Give your players the permission to use the command. A list of perms can be found on the wiki page.
For further support ask for help on the discord server, github issues is not the place to do so.
