### ISSUE TITLE
Crashing Server 

### ISSUE THREAD

**Issue by KingVibes12** [BG-Software-LLC/SuperiorSkyblock2#1359]
### Minecraft's Version

1.19.2 paper 

### Plugin's Version

1.11.1

### Describe the bug

The server crashes when I run the plugin everytime, I haven't had this issue ever since I downloaded the latest version of the plugin 1.11.1 and I tried to go back and it's doing the same thing pls fix.

### To Reproduce

idk 

### Additional Information

![16631163156894389972750437129491](https://user-images.githubusercontent.com/82794935/190033958-37ff79e0-ef37-4a5d-8e96-b3a7f519df8f.jpg)

**Comment by OmerBenGera** [comment]
Update to latest dev build.
Next time read the console logs - you'd see the plugin states it doesnt support 1.19.2

**Comment by KingVibes12** [comment]
when is it gonna be updated?

**Comment by OmerBenGera** [comment]
> when is it gonna be updated?

Already supports 1.19.2, just in the dev builds.
Update

**Comment by KingVibes12** [comment]
can we talk on discord?
