### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by deanle8** [BG-Software-LLC/SuperiorSkyblock2#1363]
### Minecraft's Version

1.19.2

### Plugin's Version

SuperiorSkyblock2 version 1.11.1.788

### Describe the bug

i am having problem with missions
**1.** `StatisticsMissions `=> `MINE_BLOCK` when i use `{value_mine_block}` it just return `-1`
**2.** `ItemsMissions` I can't use `{value_spawner_zombie}` to return quantity

### To Reproduce

.

### Additional Information

ItemsMissions -> https://pastes.dev/SxdILmO93b
StatisticsMissions -> https://pastes.dev/lTu25mv08c

**Comment by OmerBenGera** [comment]
As I told you on discord, ItemsMissions don't have placeholders at all as it doesn't track amounts of items. It just checks when you click the complete button that you have enough items.
About the statistics missions, I will look into it.

**Comment by OmerBenGera** [comment]
The issue is that "MINE_BLOCK" must take an argument - what block exactly to be broken.
For example, "MINE_BLOCK:COBBLESTONE" for the amount of cobblestone broken by the player.
You see "-1" as it's invalid.

Not a bug, hopefully this information helps :)
