### ISSUE TITLE
Players are no longer leaders of their island.

### ISSUE THREAD

**Issue by MrGrOGC** [BG-Software-LLC/SuperiorSkyblock2#1365]
### Minecraft's Version

1.18.2

### Plugin's Version

1.10.2

### Describe the bug

I wanted to change the maximum island size from config.yml. As the file recommends, I turned off the server then made the modification to restart my server. No more than 5 minutes to do everything, but when I restarted my players no longer owned their island!

This is not the first time we have had this kind of problem. Before, I changed the information directly from the database and it worked, but now there are too many players and islands for me to work like this.

We urgently need a solution.

We use a database under phpMyAdmin with MariaDB as a base from the plugin.

### To Reproduce

1. Shutdown the server
2. Modify config.yml (max-island-size:)
3. Save
4. Start the server

Result : Player don't have access to their island.

**Comment by OmerBenGera** [comment]
You cant change the max-island-size without deleting the database. If you did delete the database, then of course your players no longer part of ther island - you deleted the db..

**Comment by Tptuaazn** [comment]
Update plugin guys.

**Comment by MrGrOGC** [comment]
> You cant change the max-island-size without deleting the database. If you did delete the database, then of course your players no longer part of ther island - you deleted the db..

The database was not deleted. And, if deleting the database is necessary for this change, why was this not written in the config.yml file?

**Comment by OmerBenGera** [comment]
> > You cant change the max-island-size without deleting the database. If you did delete the database, then of course your players no longer part of ther island - you deleted the db..
> 
> The database was not deleted. And, if deleting the database is necessary for this change, why was this not written in the config.yml file?

```
# Set the maximum island size. Island distances is 3 times bigger than the max size.
# Please, do not change it while you have a running islands world!
```
It tells you to not change it while having an active islands world. I will make it more clear.
If you even tried to change it, it would revert your changes and warn you in console.

**Comment by OmerBenGera** [comment]
Wait, you use 1.10.2... jesus.
Update.
