### ISSUE TITLE
Dragon Fight NMS

### ISSUE THREAD

**Issue by SisaNyza** [BG-Software-LLC/SuperiorSkyblock2#1367]
### Minecraft's Version

Current: git-Purpur-1784 (MC: 1.19.2)*

### Plugin's Version

2022.8

### Describe the bug

Dragon Fight NMS not loading correctly for newer versions 

### To Reproduce

![download (23)](https://user-images.githubusercontent.com/49325769/191847543-05377eb0-f48e-4a55-a39d-53280d4e7c59.png)

![download (24)](https://user-images.githubusercontent.com/49325769/191847579-4a256f52-6355-4f9a-8343-b1924f9c610a.png)

Dragon fight nms doesn't get loaded when dragon fight is enabled in config

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
