### ISSUE TITLE
Bug is level

### ISSUE THREAD

**Issue by D3BoxOfficiel** [BG-Software-LLC/SuperiorSkyblock2#1369]
### Minecraft's Version

1.18.2

### Plugin's Version

![image](https://user-images.githubusercontent.com/38442389/191973222-0736c39b-a1a7-4dc7-9fe9-d6b6ee84715c.png)

### Describe the bug

![image](https://user-images.githubusercontent.com/38442389/191973178-209198cd-a213-4578-84ec-35b8724143cc.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/38442389/191973173-914d1331-b3de-4744-9659-b266d531947d.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
