### ISSUE TITLE
Island not finishing creation

### ISSUE THREAD

**Issue by tripoloski2** [BG-Software-LLC/SuperiorSkyblock2#1371]
### Minecraft's Version

1.19

### Plugin's Version

Dev build #821

### Describe the bug

After using the command /is create test, the console returns an error and gets stuck in the creation proces.

### To Reproduce

/is create test
look at the console.

**Comment by OmerBenGera** [comment]
What error do you receive...?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
I am closing this as it should be fixed
If the issue still occurs, let me know by replying here
