### ISSUE TITLE
Mining blocks is bugged

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1372]
### Minecraft's Version

1.19.2 purpur-1780

### Plugin's Version

b816

### Describe the bug

Not really sure if it's SS. 
Player mines thru block or not at all (nothing drops).

https://youtu.be/qYfNkS2EqEw

### To Reproduce

Not really sure feels that it happens on random

**Comment by OmerBenGera** [comment]
Doesn't look like its related to SSB.
If you believe it is, try to replicate the issue on a server with only SSB installed. If you manage to do so, reopen the ticket and give more information about how to replicate the issue.
