### ISSUE TITLE
Light aren't updated when island are created

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1373]
### Minecraft's Version

pufferfish 1.19.2

### Plugin's Version

b822

### Describe the bug

when you create an island, light isn't updated.
my config : 
> Should lights get updated when pasting schematics?
> Enabling this can drop performance a bit.
> lights-update: true

### To Reproduce

- create an island
- check lights

### Additional Information

I created my schematic in 1.19.2, 1 month ago
![image](https://user-images.githubusercontent.com/31826333/192161625-eefbf7b6-9602-4a25-991d-a583cc25eb1f.png)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works
