### ISSUE TITLE
Can't enter nether world island 

### ISSUE THREAD

**Issue by clarkkentz** [BG-Software-LLC/SuperiorSkyblock2#1376]
### Minecraft's Version

1.18.2

### Plugin's Version

2022.8

### Describe the bug

Nether World Bugged, Can enter nether island first time but after that you can't enter nether island

### To Reproduce

Use nether portal first time and 2nd time

**Comment by OmerBenGera** [comment]
It works fine for me.
Try using latest dev build, let me know if it works.

**Comment by clarkkentz** [comment]
Didn't work for me, i can enter the nether island first time fine but after that I can't enter

**Comment by clarkkentz** [comment]
Here's proof, clean server, only 2 plugins. #823 dev build. Please test it again.
https://streamable.com/vnykom

**Comment by OmerBenGera** [comment]
There's a cooldown after you teleport to your island that you can't enter portals in this cooldown.
Wait a few seconds, then try again.

**Comment by OmerBenGera** [comment]
> How can I remove this cooldown, I don't see it in config.yml

You cant. Its there to prevent from being portal-trapped.

**Comment by clarkkentz** [comment]
Didn't work after the cooldown, i waited like 5 minutes

**Comment by Acaendra** [comment]
The server I play on have the same issue. If people enter the nether before unlocking it from a mission, once they relog they're not able to go back. Resetting the nether for specific people regens it and they can use the portal once but relogging makes the issue persist. We also tried to set a home on the nether island, and after a relog people fall to into the void when going to the home that previously was their nether island

**Comment by OmerBenGera** [comment]
> The server I play on have the same issue. If people enter the nether before unlocking it from a mission, once they relog they're not able to go back. Resetting the nether for specific people regens it and they can use the portal once but relogging makes the issue persist. We also tried to set a home on the nether island, and after a relog people fall to into the void when going to the home that previously was their nether island

It sounds like the world is gone which is why it causes the issue. Make sure you use latest dev build, as I already fixed a similar issue.
Let me know if it helped.

**Comment by clarkkentz** [comment]
> > The server I play on have the same issue. If people enter the nether before unlocking it from a mission, once they relog they're not able to go back. Resetting the nether for specific people regens it and they can use the portal once but relogging makes the issue persist. We also tried to set a home on the nether island, and after a relog people fall to into the void when going to the home that previously was their nether island
> 
> It sounds like the world is gone which is why it causes the issue. Make sure you use latest dev build, as I already fixed a similar issue. Let me know if it helped.

Can you add a message of how much cooldown time remains when using a portal or an option to adjust it?

**Comment by UniqueUserName500** [comment]
Have the same problem, lastest dev version, default config.

**Comment by OmerBenGera** [comment]
> > > The server I play on have the same issue. If people enter the nether before unlocking it from a mission, once they relog they're not able to go back. Resetting the nether for specific people regens it and they can use the portal once but relogging makes the issue persist. We also tried to set a home on the nether island, and after a relog people fall to into the void when going to the home that previously was their nether island
> > 
> > 
> > It sounds like the world is gone which is why it causes the issue. Make sure you use latest dev build, as I already fixed a similar issue. Let me know if it helped.
> 
> Can you add a message of how much cooldown time remains when using a portal or an option to adjust it?

Cooldown is for like 5 seconds, thats not the issue.

**Comment by OmerBenGera** [comment]
> > > The server I play on have the same issue. If people enter the nether before unlocking it from a mission, once they relog they're not able to go back. Resetting the nether for specific people regens it and they can use the portal once but relogging makes the issue persist. We also tried to set a home on the nether island, and after a relog people fall to into the void when going to the home that previously was their nether island
> > 
> > 
> > It sounds like the world is gone which is why it causes the issue. Make sure you use latest dev build, as I already fixed a similar issue. Let me know if it helped.
> 
> Can you add a message of how much cooldown time remains when using a portal or an option to adjust it?

Cooldown is for like 5 seconds, thats not the issue.

**Comment by OmerBenGera** [comment]
> Have the same problem, lastest dev version, default config.

If you use /is admin teleport, are there any blocks?

**Comment by UniqueUserName500** [comment]
> > Have the same problem, lastest dev version, default config.
> 
> If you use /is admin teleport, are there any blocks?

nope. the nether island is gone

**Comment by clarkkentz** [comment]
Same here, nether island no longer exist

**Comment by OmerBenGera** [comment]
Weird, this is probably the cause.
I will look into it as well as add a warning message when it occurs.

**Comment by OmerBenGera** [comment]
@clarkkentz @UniqueUserName500 @Acaendra Please update to latest dev build.
It will not fix the issue, however it will give me more information on why it occurs so it can be patched.
Try going through the nether and look for errors.

**Comment by clarkkentz** [comment]
Latest dev build worked for me

**Comment by OmerBenGera** [comment]
> Latest dev build worked for me

Awesome :)
If the issue continues, let me know by replying here
