### ISSUE TITLE
Paper: Tasks still running when onDisable() is called.

### ISSUE THREAD

**Issue by Longehh** [BG-Software-LLC/SuperiorSkyblock2#1377]
### Minecraft's Version

1.18.2 - Pufferfish

### Plugin's Version

1.11.1

### Describe the bug

When the server is stopped on 1.18.2 this error is thrown: https://ghostbin.me/633214be044d7

### To Reproduce

Stop the server.

**Comment by Tptuaazn** [comment]
Try using latest dev build.

**Comment by OmerBenGera** [comment]
Can be ignored.

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, let me know if it's better.

**Comment by OmerBenGera** [comment]
Should be fixed.
If the issue still persists, let me know by replying here
