### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by srnyx** [BG-Software-LLC/SuperiorSkyblock2#138]
**Minecraft's Version**
Paper-Spigot 1.16.5

**Plugin's Version**: -
1.5.2

**Describe the bug**
The server crashes upon startup

**Additional information**
Logs: https://paste.gg/p/anonymous/2af72af2876a4489a2902b20f20679a2

**Comment by OmerBenGera** [comment]
Use latest dev build from https://bg-software.com/superiorskyblock/
