### ISSUE TITLE
Skyblock

### ISSUE THREAD

**Issue by itsmeDucky** [BG-Software-LLC/SuperiorSkyblock2#1380]
### Minecraft's Version

1.18.2

### Plugin's Version

826

### Describe the bug

Spawners can go through the barriers a.k.a Borders

### To Reproduce

pretty simple they just go through it

**Comment by OmerBenGera** [comment]
These are only virtual borders and there is nothing to do regarding this.
There should not be any blocks in these chunks in the first place.

**Comment by itsmeDucky** [comment]
how can i stop spawners going outside the border , if u try to throw items they dont go through border
