### ISSUE TITLE
Superior using lots of % with 1 player on the server / island

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1382]
### Minecraft's Version

1.19.2

### Plugin's Version

1.11.1.795 dev

### Describe the bug

For some reason I noticed the CPU being high and when doing a profiler I noticed that superior was taking 5% of the ticks when **NO ONE** is playin. It's a dev server so I find it weird: https://spark.lucko.me/OOx2a3kjyj https://spark.lucko.me/w0ZtXV92Y7

### To Reproduce

I was afk at my island with 0 farms

### Additional Information

Small gif to prove there is nothing / no one playing: https://gyazo.com/58ebad88645ad1c1280d883b4e9a8a10

**Comment by OmerBenGera** [comment]
I sadly do not have a solution as of now.
You can disable entity limits and it will fix the issue.
If someone has improvements, a PR is more than welcomed.
