### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1384]
### Minecraft's Version

1.19.2
Purpur  build-1799

### Plugin's Version

2022.8-B826

### Describe the bug

Since a while I find that SuperiorSkyblock consumes more and more, would it be possible to stabilize this?

### To Reproduce

have server on production

### Additional Information

https://spark.lucko.me/6M047nSoSf

**Comment by OmerBenGera** [comment]
Check out latest dev build. let me know if its better

**Comment by DuckyDou** [comment]
Its a little bit better

**Comment by OmerBenGera** [comment]
> Its a little bit better

Mind sending me a new spark profiler so I can also compare it?

**Comment by OmerBenGera** [comment]
@DuckyDou

**Comment by DuckyDou** [comment]
Hi!
Finally, the problem seems to be solved I don't have any more performance issues with the plugin! Thanks again
https://spark.lucko.me/m8MKpYaqBD

**Comment by OmerBenGera** [comment]
Optimized it even further, try latest dev build :)

**Comment by DuckyDou** [comment]
https://spark.lucko.me/XE6rueK5Tj

**Comment by DuckyDou** [comment]
https://spark.lucko.me/UqEIURhP65

**Comment by OmerBenGera** [comment]
> https://spark.lucko.me/UqEIURhP65

Much better now.
I still want to implement another optimization tho. I will let you know once its implemented :)

**Comment by OmerBenGera** [comment]
@DuckyDou Check out latest dev build

**Comment by DuckyDou** [comment]
https://spark.lucko.me/yuyD7yIW6K
Idk if its better

**Comment by OmerBenGera** [comment]
> https://spark.lucko.me/yuyD7yIW6K Idk if its better

I reverted the changes for the time being as it doesnt work well in some cases.

**Comment by DuckyDou** [comment]
https://spark.lucko.me/RFR1KQyZzn

I think this could be better

**Comment by OmerBenGera** [comment]
> https://spark.lucko.me/RFR1KQyZzn
> 
> I think this could be better

I am 100% agree with you.

**Comment by WarnDa** [comment]
Spark with 120 players 1.19.2 : https://spark.lucko.me/9d6fnksbYQ

**Comment by DuckyDou** [comment]
https://spark.lucko.me/mgV5YAqRtg
1.19.2

**Comment by OmerBenGera** [comment]
Hey,
please take a new spark profiler using the latest dev builds
thanks.

**Comment by WarnDa** [comment]
> Hey, please take a new spark profiler using the latest dev builds thanks.

He deleted his server, but here is a spark with 150 players : https://spark.lucko.me/zt0riP6y5R

**Comment by OmerBenGera** [comment]
> > Hey, please take a new spark profiler using the latest dev builds thanks.
> 
> He deleted his server, but here is a spark with 150 players : https://spark.lucko.me/zt0riP6y5R Another spark of 2hr on b984 with 120 players : https://spark.lucko.me/p4kDjEUL4S

Looks fine for me.
Is there anything that I missed?

**Comment by WarnDa** [comment]
> > > Hey, please take a new spark profiler using the latest dev builds thanks.
> > 
> > 
> > He deleted his server, but here is a spark with 150 players : https://spark.lucko.me/zt0riP6y5R Another spark of 2hr on b984 with 120 players : https://spark.lucko.me/p4kDjEUL4S
> 
> Looks fine for me. Is there anything that I missed?

Recalculation can be heavy, but the rest is fine

**Comment by OmerBenGera** [comment]
> > > > Hey, please take a new spark profiler using the latest dev builds thanks.
> > > 
> > > 
> > > He deleted his server, but here is a spark with 150 players : https://spark.lucko.me/zt0riP6y5R Another spark of 2hr on b984 with 120 players : https://spark.lucko.me/p4kDjEUL4S
> > 
> > 
> > Looks fine for me. Is there anything that I missed?
> 
> Recalculation can be heavy, but the rest is fine

That's fine, recalculation is a heavy task.
That's why it's advised to have it in cooldown, and there are many optimizations to make sure it doesn't lag your server :)

Closing this for now.
