### ISSUE TITLE
Cant go to nether

### ISSUE THREAD

**Issue by BlueMooon777** [BG-Software-LLC/SuperiorSkyblock2#1385]
### Minecraft's Version

1.19.2

### Plugin's Version

latest dev

### Describe the bug

I have multiverse Portals and cant go to the nether
also i cant figure out how to get spawners

### To Reproduce

start server with this plugin on paper 1.19.2 with multiverse core and multiverse portals

**Comment by OmerBenGera** [comment]
Duplicate of #1376
