### ISSUE TITLE
ItemMissions mission not formatting lore properly

### ISSUE THREAD

**Issue by calebneuf** [BG-Software-LLC/SuperiorSkyblock2#1386]
### Minecraft's Version

1.19-R0.1-SNAPSHOT

### Plugin's Version

2022.8

### Describe the bug

ItemMissions lore's arent formatting with {value_some_material}

https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/master/ItemsMissions/src/main/java/com/bgsoftware/superiorskyblock/missions/ItemsMissions.java

It appears its the only one that doesnt have formatItem method in it compared to the other ItemMissions.

### To Reproduce

Add {value_dirt} or whatever in the lore of an item missions mission.

![image](https://user-images.githubusercontent.com/78993537/193211453-7b6cfa50-dcbf-4cd7-ad3f-95a7c6374069.png)

**Comment by OmerBenGera** [comment]
ItemsMissions don't have any placeholders, and that's intended.
ItemsMissions dont track anything, it only checks if you have all the required items when you try to complete the mission.

**Comment by jeniok360v** [comment]
If that's intended then your wikipage is misleading:

     ...
      - ''
      - '&6Nether Star Collected: &7{value_nether_star}/1'
      - '&6Progress: &7{0}%'
     ...

https://wiki.bg-software.com/superiorskyblock/overview/missions/itemsmissions

**Comment by OmerBenGera** [comment]
> If that's intended then your wikipage is misleading:
> 
> ```
>  ...
>   - ''
>   - '&6Nether Star Collected: &7{value_nether_star}/1'
>   - '&6Progress: &7{0}%'
>  ...
> ```
> 
> https://wiki.bg-software.com/superiorskyblock/overview/missions/itemsmissions

You're right, I will fix it soon.
