### ISSUE TITLE
Bugs/Glitches

### ISSUE THREAD

**Issue by itsmeDucky** [BG-Software-LLC/SuperiorSkyblock2#1387]
### Minecraft's Version

1.18.2

### Plugin's Version

dev #839

### Describe the bug

There are no borders , values were broken with new update idk why but it happen :/

### To Reproduce

I downloaded latest version and then it broke

**Comment by OmerBenGera** [comment]
What values are you talking about?

**Comment by itsmeDucky** [comment]
Spawners value and Block values

**Comment by itsmeDucky** [comment]
Oh Omer so the old islands could not see the border , lost all value etc but the new created islands
workds perfect

**Comment by OmerBenGera** [comment]
@itsmeDucky Check out latest dev build, let me know if its better now.

**Comment by itsmeDucky** [comment]
way better now

**Comment by OmerBenGera** [comment]
Great
If the issue continues, let me know by replying here
