### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1389]
### Minecraft's Version

Purpur 1804 - 1.19.2

### Plugin's Version

latest dev build 844

### Describe the bug

error on loading islands

### To Reproduce

use latest dev build and start server

### Additional Information

https://pastebin.com/raw/JHUajk5V

**Comment by OmerBenGera** [comment]
Check out latest dev build, it should give us a better understanding of the issue.

**Comment by DuckyDou** [comment]
Hi! Thanks for that!
But now i have this:
https://pastebin.com/raw/bCg9zAa0

**Comment by OmerBenGera** [comment]
> Hi! Thanks for that! But now i have this: https://pastebin.com/raw/bCg9zAa0

Yeah, weird.
As you can see, there are chunks considered "dirty" (aka they have blocks) for an island, however they are outside of the area of it...

I will look into it so it fixes itself by removing these chunks

**Comment by DuckyDou** [comment]
Thanks

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
