### ISSUE TITLE
Placeholder dosen't work

### ISSUE THREAD

**Issue by D3BoxOfficiel** [BG-Software-LLC/SuperiorSkyblock2#1390]
### Minecraft's Version

1.18.2 Purpur

### Plugin's Version

![Uploading image.png…]()

### Describe the bug

![image](https://user-images.githubusercontent.com/38442389/193446575-30417e4c-d0be-4fff-8547-7dfd6fc63579.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/38442389/193446578-5c898cff-f61f-4217-a8c4-30aba7791661.png)

**Comment by OmerBenGera** [comment]
What's not working?

**Comment by D3BoxOfficiel** [comment]
Return 0 or the placeholder need to return 78,588.72

**Comment by OmerBenGera** [comment]
> Return 0 or the placeholder need to return 78,588.72

You use the placeholder that returns the amount of players in your island.
Use `%superior_island_top_worth_1%` and `%superior_island_top_worth_value_1%`

**Comment by D3BoxOfficiel** [comment]
I need placeholders that return the name and levels of top 1 - 2 and 3

**Comment by OmerBenGera** [comment]
> I need placeholders that return the name and levels of top 1 - 2 and 3

You can checkout the wiki for a list of available placeholders.
