### ISSUE TITLE
Island bank interest stuck

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1395]
### Minecraft's Version

Purpur-1809 (MC: 1.19.2)

### Plugin's Version

SuperiorSkyblock dev build #848

### Describe the bug

Hello, since some time the interest time is not updated for some players, it is blocked on "1 second".

### To Reproduce

Seriously I could not say, only some players have the problem, maybe due to my current configuration

### Additional Information

Configuration of module bank
https://pastebin.com/raw/pD5LJ6BK

**Comment by DuckyDou** [comment]
It seems that one of the players the IDs of the bank logs are all the same (#185)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by DuckyDou** [comment]
I have deleted all data in bank_transactions and its work great

**Comment by OmerBenGera** [comment]
> I have deleted all data in bank_transactions and its work great

was it fixed due to the new update or because you deleted the bank transactions from db?

**Comment by DuckyDou** [comment]
Because i have deleted in DB

**Comment by OmerBenGera** [comment]
> Because i have deleted in DB

Hmm I understand.
If the issue occurs, let me know
