### ISSUE TITLE
Blockcount reset after recalculate

### ISSUE THREAD

**Issue by tripoloski2** [BG-Software-LLC/SuperiorSkyblock2#1396]
### Minecraft's Version

Minecraft version: 1.19
Server: Spigot paper

### Plugin's Version

Plugin version: 2022.8.1

### Describe the bug

When creating a new island, using /is blocks will show all the blocks with a given value. But after using /is recalc, all the blocks dissapear from the menu. This also results that block limits like hoppers can be bypassed by using /is recalc, because the previously placed hoppers dont count anymore.

### To Reproduce

**Scenario 1**
Create a new island
use /is blocks to check the current blocks
use /is recalc to trigger the bug
use /is blocks and see all blocks dissapeared

**Scenario 2**
Create a new island
place random blocks that count towards the value
use /is blocks to check the current blocks
use /is recalc to trigger the bug
use /is blocks and see all blocks dissapeared

**Scenario 3**
Create a new island
place hoppers till you got to the limit
use /is blocks to check the hoppers
use /is recalc to trigger the bug
use /is blocks and see all hopper dissapeared
Try to place hoppers now that the previously placed hoppers dont count.

**Comment by exzolink** [comment]
Same problem
Airplane 1.16.5
b848

> Look for errors, as it works fine for me. Also, update to latest dev build.

**Comment by ArefyNetwork** [comment]
Take a look at the stacked blocks on the island (https://m.arefy.net/dKHGXxq.png)

And then take a look on /is values, so weird
https://www.youtube.com/watch?v=j3h89tCjRkg

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by exzolink** [comment]
> Check out latest dev build, let me know if it works.

Fixed, thank you

**Comment by ArefyNetwork** [comment]
> Take a look at the stacked blocks on the island (https://m.arefy.net/dKHGXxq.png)
> 
> And then take a look on /is values, so weird https://www.youtube.com/watch?v=j3h89tCjRkg

This still happening

**Comment by ArefyNetwork** [comment]
> > > Take a look at the stacked blocks on the island (https://m.arefy.net/dKHGXxq.png)
> > > And then take a look on /is values, so weird https://www.youtube.com/watch?v=j3h89tCjRkg
> > 
> > 
> > This still happening, even with latest version 852
> 
> What exactly still happens? As with b852, the blocks are calculated again correctly.

Could you contact me xNekio#9001 via discord please, to show you via test server? Thanks!

**Comment by exzolink** [comment]
> > > Take a look at the stacked blocks on the island (https://m.arefy.net/dKHGXxq.png)
> > > And then take a look on /is values, so weird https://www.youtube.com/watch?v=j3h89tCjRkg
> > 
> > 
> > This still happening, even with latest version 852
> 
> What exactly still happens? As with b852, the blocks are calculated again correctly.

Tested with mariadb, still not fixed

**Comment by OmerBenGera** [comment]
> > > > Take a look at the stacked blocks on the island (https://m.arefy.net/dKHGXxq.png)
> > > > And then take a look on /is values, so weird https://www.youtube.com/watch?v=j3h89tCjRkg
> > > 
> > > 
> > > This still happening, even with latest version 852
> > 
> > 
> > What exactly still happens? As with b852, the blocks are calculated again correctly.
> 
> Still not works for old islands (created before patch)

It will work with latest version.
If not, open a new issue.
