### ISSUE TITLE
Island are not saved after restart

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1397]
### Minecraft's Version

Purpur 1.19.2 (# 1814)

### Plugin's Version

[SuperiorSkyblock2-2022.8.1-b850.jar](https://hub.bg-software.com/job/SuperiorSkyblock2/lastSuccessfulBuild/artifact/target/SuperiorSkyblock2-2022.8.1-b850.jar)

### Describe the bug

Hello, since 2 days, the new islands are not saved in the database (mariadb), in the table skyblockplayers players are well saved and also in the table skyblockplayers_settings on the other hand the islands are simply not saved at each restart players must redo their island (no error in the console) no data saved in tables skyblockislands ect

### To Reproduce

I really don't know, the problem appeared without any reason (we haven't updated anything on our side)

### Additional Information

![image](https://user-images.githubusercontent.com/98712497/194110774-c04367d2-4793-401f-8bdd-6cfabb15f99f.png)
![image](https://user-images.githubusercontent.com/98712497/194110817-6b0d933b-86d6-49e2-bc83-115d9a3fe03b.png)

**Comment by DuckyDou** [comment]
Let me know if there is a solution I had to close my server indefinitely

**Comment by DuckyDou** [comment]
Take note that we have tried this:

Remove the plugins 1 by 1
Remove all plugins except SuperiorSkyblock2
Change the java version (8,11,16,17,18)
Replace purpur with papermc
Delete the database to generate a new one
Remove the skyblock world

**Comment by DuckyDou** [comment]
Update:

Issue persist with sqlite database too its save players but not island

**Comment by OmerBenGera** [comment]
> Edit: The save work with [SuperiorSkyblock2-2022.8-b822.jar](https://hub.bg-software.com/job/SuperiorSkyblock2/822/artifact/target/SuperiorSkyblock2-2022.8-b822.jar)

Please find the exact build that it stopped working.
I can't replicate the issue myself with the latest dev build, therefore I can't do it myself.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by DuckyDou** [comment]
Unfortunately I can't try all the versions, but with #838 the problem persists, and with the last version you published the problem persists

**Comment by OmerBenGera** [comment]
> Unfortunately I can't try all the versions, but with #838 the problem persists, and with the last version you published the problem persists

Still occurs with b853?

**Comment by WarnDa** [comment]
Hello,
I don't get the problem anymore on b854 :)
(I had the issue on b850)

**Comment by DuckyDou** [comment]
Thanks, im going to try that!

**Comment by OmerBenGera** [comment]
@DuckyDou If it still isn't fixed, run the following and then create an island:
`/is admin debug DATABASE_QUERY`

**Comment by DuckyDou** [comment]
Its fixed!

**Comment by OmerBenGera** [comment]
Awesome :)
