### ISSUE TITLE
Nether generator generate only basalt

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1398]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

848

### Describe the bug

Nether generator (End generator too, i guess) generate only basalt, in normal and in the nether worlds. Previously works as should.

### To Reproduce

Add custom blocks to nether generator upgrade and try to mine nether generator

### Additional Information

Part with generator-rates
https://pastebin.com/VaYCNKGG
Ingame info about players generators
https://imgur.com/6NaxfSN

**Comment by exzolink** [comment]
> ### Minecraft's Version
> 
> Airplane 1.16.5
> ### Plugin's Version
> 
> 848
> ### Describe the bug
> 
> Nether generator generate only basalt, in normal and in the nether worlds. Previously works as should.
> ### To Reproduce
> 
> Add custom blocks to nether generator upgrade and try to mine nether generator
> ### Additional Information
> 
> Part with generator-rates https://pastebin.com/VaYCNKGG

Ingame info about players generators https://imgur.com/6NaxfSN

**Comment by OmerBenGera** [comment]
As you can clearly see, the generator rates you configured were not applied to the island.
This is probably because you edit them not in the correct place - you should edit the upgrades, not the config file.

**Comment by exzolink** [comment]
> As you can clearly see, the generator rates you configured were not applied to the island. This is probably because you edit them not in the correct place - you should edit the upgrades, not the config file.

It is upgrades config, in previous versions its works as should

**Comment by exzolink** [comment]
> As you can clearly see, the generator rates you configured were not applied to the island. This is probably because you edit them not in the correct place - you should edit the upgrades, not the config file.

Full config from upgrades module
https://pastebin.com/PYmsr5D4

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by exzolink** [comment]
Thank you
