### ISSUE TITLE
Issue with KillsMissions counting the whole stack of mobs during clear lag from wildstacker

### ISSUE THREAD

**Issue by Meliodazzz** [BG-Software-LLC/SuperiorSkyblock2#1400]
### Minecraft's Version

1.16.5

### Plugin's Version

Latest

### Describe the bug

Whilst you are grinding mobs from a mob stack, if it a clear occurs from WildStacker while you are still killing mobs simultaneously., it counts the whole stack towards your KillsMission progress.

### To Reproduce

1. Create a KillsMission with a specific mob
2. Place down enough spawners of said mob to maintain a big stack while grinding
3. Keep grinding/killing mobs until a clear occurs from WildStacker
4. Check your progress in the KillsMission and you will see the whole stack counted.

**Comment by OmerBenGera** [comment]
What version of Spigot do you use?
WildStacker kills the entities using the Entity#remove method, which for no reason calls EntityDeathEvent on your spigot - this is not an intended behavior, and causes this bug to occur.
On regular Spigot/Paper jars, it doesn't occur (I am using `git-Paper-786 (MC: 1.16.5)` and it works just fine)

**Comment by Meliodazzz** [comment]
I use `git-Paper-794`

**Comment by OmerBenGera** [comment]
> Paper

Tried it as well, the event is not fired.
Mind taking a video of the issue?

**Comment by Meliodazzz** [comment]
https://www.youtube.com/watch?v=7d9zMo78Pto&ab_channel=Kiloridge

Here you go, I just realized something. Something weird happens when the "issue" occurs. In the wildstacker clear, it doesnt actually fully clear the mob, it just takes a big chunk of the stack thats all.

**Comment by OmerBenGera** [comment]
I see that you have clearlag, you haven't mentioned that.
Do you have sync-kill-task enabled?

**Comment by Meliodazzz** [comment]
I dont have clearlag? I only use WildStacker

**Comment by OmerBenGera** [comment]
> I dont have clearlag? I only use WildStacker

Try replicating the issue on a server with only WildStacker and SSB installed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
