### ISSUE TITLE
PlayerLoginEvent error

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1401]
### Minecraft's Version

Current: git-Purpur-1749 (MC: 1.19.1)*
Previous: git-Purpur-1670 (MC: 1.19)

### Plugin's Version

2022.8.1

### Describe the bug

Error, when i try to join the server.

https://pastebin.com/vUTsy13b

### To Reproduce

1.  Whitelist the server.
2. Join with unwhitelisted account.
3. Error on console

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.
