### ISSUE TITLE
Console Error Latest ver

### ISSUE THREAD

**Issue by AlekseyTitov99** [BG-Software-LLC/SuperiorSkyblock2#1402]
### Minecraft's Version

1.19.2 - Pufferfish jar (Paper fork)

### Plugin's Version

2022.8.1-b857

### Describe the bug

Errors in console - https://imgur.com/a/mOyUbeA

### To Reproduce

Not sure

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works
