### ISSUE TITLE
/is ban doesn't work

### ISSUE THREAD

**Issue by HiddenSeaMC** [BG-Software-LLC/SuperiorSkyblock2#1403]
### Minecraft's Version

git-Pufferfish-67 (MC: 1.18.2)

### Plugin's Version

2022.8.1-b848

### Describe the bug

When i do /is ban (player)
I confirm it, i can't ban it and he can come again on my island.

### To Reproduce

/is ban (player)

player step : /is warp (island's owner)

### Additional Information

Config : 

######################################################
######################################################

title: ':offset_-30:&f%img_menuiles%'
previous-menu: true

pattern:
  - '➏ ➊ @ @ @ @ @ ➎ ➏'
  - '➎ @ @ @ @ @ @ @ ➋'
  - '@ @ @ 1 @ 2 @ @ @'
  - '@ @ @ @ @ @ @ @ @'
  - '➍ @ @ @ @ @ @ @ ➎'
  - '➏ ➎ @ ◀ ✕ ▶ @ ➌ ➏'

confirm: '1'
cancel: '2'

commands:
  '✕':
    - '[back]'

items:
  '1':
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzc0NzJkNjA4ODIxZjQ1YTg4MDUzNzZlYzBjNmZmY2I3ODExNzgyOWVhNWY5NjAwNDFjMmEwOWQxMGUwNGNiNCJ9fX0='
    name: '&aAccepter'
    lore:
      - ''
      - ' &7| &fÊtes-vous sûr de vouloir bannir ce joueur?'
  '2':
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjk1M2IxMmEwOTQ2YjYyOWI0YzA4ODlkNDFmZDI2ZWQyNmZiNzI5ZDRkNTE0YjU5NzI3MTI0YzM3YmI3MGQ4ZCJ9fX0='
    name: '&cAnnuler'

  #CUSTOM GUI
  #'▼':
  #  type: SUNFLOWER
  #  name: '&7&lP&7age: {0}'
  #'▶':
  #  type: PLAYER_HEAD
  #  skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODI3MWE0NzEwNDQ5NWUzNTdjM2U4ZTgwZjUxMWE5ZjEwMmIwNzAwY2E5Yjg4ZTg4Yjc5NWQzM2ZmMjAxMDVlYiJ9fX0'
  #  name: '{0}&7&lP&7.&fsuivante &7→'
  #'◀':
  #  type: PLAYER_HEAD
  #  skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjllYTFkODYyNDdmNGFmMzUxZWQxODY2YmNhNmEzMDQwYTA2YzY4MTc3Yzc4ZTQyMzE2YTEwOThlNjBmYjdkMyJ9fX0'
  #  name: '{0}&7← &7&lP&7.&fprécédente'
  '✕':
    type: PLAYER_HEAD
    skull: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJkN2E3NTFlYjA3MWUwOGRiYmM5NWJjNWQ5ZDY2ZTVmNTFkYzY3MTI2NDBhZDJkZmEwM2RlZmJiNjhhN2YzYSJ9fX0'
    name: '&fMenu précédent'
  '➊':
    type: BLUE_STAINED_GLASS_PANE
    name: '&8'
  '➋':
    type: BLUE_STAINED_GLASS_PANE
    name: '&8'
  '➌':
    type: BLUE_STAINED_GLASS_PANE
    name: '&8'
  '➍':
    type: BLUE_STAINED_GLASS_PANE
    name: '&8'
  '➎':
    type: BLUE_STAINED_GLASS_PANE #cornerStainedWhiteGlass
    name: '&8'
  '➏':
    type: BLUE_STAINED_GLASS_PANE #extremiteStainedWhiteGlass
    name: '&8'

sounds:
  '1':
    type: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 0.2
    pitch: 0.2
  '2':
    type: BLOCK_ANVIL_PLACE
    volume: 0.2
    pitch: 0.2

**Comment by OmerBenGera** [comment]
Are there any errors?
If so, upload to pastebin and send them here.

**Comment by HiddenSeaMC** [comment]
No, any errors :/

**Comment by exzolink** [comment]
Same bug, latest dev build

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
