### ISSUE TITLE
Command disabler

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1404]
### Minecraft's Version

1.19.2

### Plugin's Version

2022.8.1 b858

### Describe the bug

When disabling the is panel command in the command disabler it will disable the /is members command 

### To Reproduce

Add "panel" in the **disabled-commands:** section in the config.yml file

### Additional Information

https://gyazo.com/65cf960621a37e47efc68410284c47cc

**Comment by OmerBenGera** [comment]
Not really a bug as /is members technically runs `/is panel members`, however I will change it to not do so.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
