### ISSUE TITLE
Plugin not loading because of Nashorn Er

### ISSUE THREAD

**Issue by Simonmaribo** [BG-Software-LLC/SuperiorSkyblock2#1405]
### Minecraft's Version

Minecraft version is 1.8.8 using Paper 1.8.8 and Java 8

### Plugin's Version

Newest - 2022.8.1, downloaded October 12th.

### Describe the bug

![image](https://user-images.githubusercontent.com/64478800/195437618-e0cf7c9c-c509-41dc-aa69-61eb45210893.png)
![image](https://user-images.githubusercontent.com/64478800/195437665-201eeb56-a5d6-4fe9-b539-6d4873a8619f.png)

The server won't load SuperiorSkyblock, because the Nashorn Engine is created in another Java version.
When setting the Java version to 11 (JDK 55.0), it doesn't show this error but instead logs this.

![image](https://user-images.githubusercontent.com/64478800/195437302-f02a5810-5725-42a0-a0d1-bcd8ba6d104c.png)
![image](https://user-images.githubusercontent.com/64478800/195437331-f33c6e37-26a4-4859-a4b9-19841cda6d5e.png)

The error just suddenly started to happen, so my first thought was that the plugin had downloaded an update automatically, but when rollbacking to an earlier version is still happened, so I believe something is wrong with the "Nashorn engine"

### To Reproduce

I have no idea, it keeps happening. I tried downloading other versions of the plugin, but it wont load because of this Nashorn Engine error.

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed.
