### ISSUE TITLE
Can't kick some island members

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#1406]
### Minecraft's Version

1.8.8

### Plugin's Version

858 dev build

### Describe the bug

Some island leaders can't kick some players (they're bugged)

### To Reproduce

I'm using superiorskyblock on both gamemodes (prison, skyblock) and there are the same bugs on both of them, some players can't be kicked out of the island, would be better if you come to test as you did before (xNekio#9001), thanks and much appreciated again!

**Comment by OmerBenGera** [comment]
Does it happen for only specific players?
If so, was their uuid got changed? Are there any other issues they have (losing their islands, etc)?

**Comment by OmerBenGera** [comment]
> > Does it happen for only specific players? If so, was their uuid got changed? Are there any other issues they have (losing their islands, etc)?
> 
> No, they didn't have uuid changed, they're members that can't be kicked from the gang

What happens when trying to kick them?
It says they were successfully kicked but they are still in the island?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If the issue persists let me know by replying to this issue.
