### ISSUE TITLE
Island bank and deposit all money

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1409]
### Minecraft's Version

git-Purpur-1820 (MC: 1.19.2)

### Plugin's Version

[SuperiorSkyblock2-2022.8.1-b867.jar](https://hub.bg-software.com/job/SuperiorSkyblock2/lastSuccessfulBuild/artifact/target/SuperiorSkyblock2-2022.8.1-b867.jar)

### Describe the bug

When we use the /is bank menu and we try to put all the money at once with the option "Deposit all your money" we get an error in the chat and the money is not transferred

### To Reproduce

/is bank
Use deposit all button

### Additional Information

![unknown (1)](https://user-images.githubusercontent.com/98712497/195986310-e5245265-936a-462a-aeb5-8a7307873de9.png)

**Comment by OmerBenGera** [comment]
> ### Minecraft's Version
> git-Purpur-1820 (MC: 1.19.2)
> 
> ### Plugin's Version
> [SuperiorSkyblock2-2022.8.1-b867.jar](https://hub.bg-software.com/job/SuperiorSkyblock2/lastSuccessfulBuild/artifact/target/SuperiorSkyblock2-2022.8.1-b867.jar)
> 
> ### Describe the bug
> When we use the /is bank menu and we try to put all the money at once with the option "Deposit all your money" we get an error in the chat and the money is not transferred
> 
> ### To Reproduce
> /is bank Use deposit all button
> 
> ### Additional Information
> ![unknown (1)](https://user-images.githubusercontent.com/98712497/195986310-e5245265-936a-462a-aeb5-8a7307873de9.png)

This happens when the plugin tries to make the transaction but no money was transferred.
This is an issue with your economy provider, not SuperiorSkyblock.

**Comment by DuckyDou** [comment]
No, its a issue with superiorskyblock.
With build #857 its work

**Comment by OmerBenGera** [comment]
> No, its a issue with superiorskyblock. With build #857 its work

Might be because you have less than a 1$.

**Comment by DuckyDou** [comment]
Not really, I tried with 10$, 1000$, 10000$, 100000$ ect

**Comment by OmerBenGera** [comment]
I can't replicate the issue myself.
What economy plugin are you using?

**Comment by DuckyDou** [comment]
Cmi,vault

**Comment by OmerBenGera** [comment]
I can't test it myself as CMI is paid.
Try it with Essentials on another server, let me know if it still occurs

**Comment by DuckyDou** [comment]
Same issue

**Comment by OmerBenGera** [comment]
> Same issue

Not sure why it happens for you, as it works flawlessly fine for me.
Mind taking a video of the issue, showcasing how to replicate the issue?

**Comment by WarnDa** [comment]
I already had the issue multiple times and reported it on discord
Sometimes it tries to add +1 to your current money, so you got 1000$, and it tries to add 1001$ so it fails

**Comment by OmerBenGera** [comment]
> I already had the issue multiple times and reported it on discord Sometimes it tries to add +1 to your current money, so you got 1000$, and click on "transfer all" it tries to add 1001$ so it fails

In what conditions does it occur? I can't replicate the issue myself.

**Comment by WarnDa** [comment]
> > I already had the issue multiple times and reported it on discord Sometimes it tries to add +1 to your current money, so you got 1000$, and click on "transfer all" it tries to add 1001$ so it fails
> 
> In what conditions does it occur? I can't replicate the issue myself.

I don't know the conditions, that's why I didn't reported it to github :/

**Comment by OmerBenGera** [comment]
> > > I already had the issue multiple times and reported it on discord Sometimes it tries to add +1 to your current money, so you got 1000$, and click on "transfer all" it tries to add 1001$ so it fails
> > 
> > 
> > In what conditions does it occur? I can't replicate the issue myself.
> 
> I don't know the conditions, that's why I didn't reported it to github :/

Try playing with it. Adding really small values to your bank (using your economy plugin) until you find how to replicate it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
@DuckyDou

**Comment by DuckyDou** [comment]
Look like fixed

**Comment by OmerBenGera** [comment]
> Look like fixed

I didn't change anything... :/
Should I keep this opened or close it for now?

**Comment by DuckyDou** [comment]
It works every other time but if you can't do anything about it, it doesn't matter :)

And yes we can close the issue

**Comment by OmerBenGera** [comment]
I'll close this for now
If the issue continues let me know by replying here.
