### ISSUE TITLE
Stacked blocks broken 

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SuperiorSkyblock2#1412]
### Minecraft's Version

1.19.2

### Plugin's Version

b870

### Describe the bug

When stacking blocks it won't stack at all and it's bugged and they no longer count toward the /is level.

### To Reproduce

https://gyazo.com/f85fbb9cf0b8e1bb0de1312e10947911
https://gyazo.com/c1c92948b24bccedec5cdb2036bb1028

### Additional Information

I'm on the latest of paper patches about the chunks and I'm using SuperiorSkyblock internal system for stacking blocks and I have RoseStacker. 

When placing blocks that doesn't count stack but counts in the /is level it will work.

**Comment by LuluxClient** [comment]
Issue found, caused by coreprotect implementations

**Comment by OmerBenGera** [comment]
> Issue found, caused by coreprotect implementations

Are you sure it's not a bug of SSB with newer versions of CoreProtect?
It looks like you had errors in console that you missed when placing the stacked blocks.
