### ISSUE TITLE
The island doesn't belong to me anymore.

### ISSUE THREAD

**Issue by quangpao** [BG-Software-LLC/SuperiorSkyblock2#1413]
### Minecraft's Version

1.19.2 (also 1.16.5)

### Plugin's Version

lastest (2022.8.1)

### Describe the bug

Some of my members lost their ownership of the island after I re-running my server again. 
The island is still there, they can also use /island to come back to their island. But not interacting with it and it also disappears from /is top.

### To Reproduce

When I stop the server, those scripts have shown up. 
![image](https://user-images.githubusercontent.com/102311709/196036049-d4eb15e7-49aa-487f-b430-9d3b345cc609.png)

After these scripts have shown up, every time I start my server again. There will be some users losing their island control permissions.

### Additional Information

![image](https://user-images.githubusercontent.com/102311709/196036008-d3750c63-4024-4d56-984c-85bb1eb4e2be.png)
An island leader trying to interact with his island after this error occurs.

**Comment by OmerBenGera** [comment]
Update to latest dev build
