### ISSUE TITLE
Admin Join does not call IslandJoinEvent

### ISSUE THREAD

**Issue by RedW0lfStoneYT** [BG-Software-LLC/SuperiorSkyblock2#1418]
### Minecraft's Version

1.8, checked the code though, does not call it at all

### Plugin's Version

2022.8-b800

### Describe the bug

I was attempting to do stuff with island join and found out that the admin join does not actually fire the IslandJoinEvent, this is kinda needed for what I am doing at the moment

### To Reproduce

/is admin join <player> while testing for IslandJoinEvent calls

**Comment by DuckyDou** [comment]
Update to latest dev build

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, thanks for reporting!
