### ISSUE TITLE
Massive Skyblock world 

### ISSUE THREAD

**Issue by mja00** [BG-Software-LLC/SuperiorSkyblock2#1420]
### Minecraft's Version

This server is running Paper version git-Paper-210 (MC: 1.19.2)

### Plugin's Version

SuperiorSkyblock2 version 2022.8.1

### Describe the bug

Currently we're seeing odd behavior with the size of our Skyblock world. It'll start normally but after a few hours it'll grow exponentially in size. Currently after only 2 hours it went from 8GB to 100GB and grows a few thousand bytes per second. Something feels off.

### To Reproduce

It's currently just loading up the server with the SuperiorSkyblock2 plugin installed and using SuperiorWorld as our skyblock world. 

### Additional Information

World size: `103G    SuperiorWorld/`
Config: [https://gist.github.com/mja00/34f2155611a4e4f9d6d5c33393e134c3](https://gist.github.com/mja00/34f2155611a4e4f9d6d5c33393e134c3)

**Comment by mja00** [comment]
I've updated to that version and will let it just sit for a few hours to see if the behavior happens again. I'll let you know my findings.

**Comment by mja00** [comment]
Looks like it's still going up pretty quickly. Here's a list of my plugins if they may be doing something:
`
BetterRTP, BuycraftX, CMILib, CoreProtect, CrateReloaded, DeluxeHub, dynmap, EconomyShopGUI, Essentials, EssentialsChat, Geyser-Spigot, Graves, GriefPrevention, Jobs, LuckPerms, Multiverse-Core, Multiverse-Inventories, PlugManX (PlugMan), SimplePluginManager*, sleep-most, SuperiorSkyblock2, TAB, UltimateAutoRestart, VanishNoPacket, Vault, VeinMiner, WorldEdit, WorldGuard
`

**Comment by OmerBenGera** [comment]
Its probably because SSB loads chunks that it shouldnt.

I will look into it

**Comment by OmerBenGera** [comment]
I looked into it again and everything is fine on SSB's side.
The reason for the massive world is probably due to high view distance on your server, as well as players being spread far from each other in the world (it's a skyblock server at the end)

Are you sure it's an issue with the plugin?

**Comment by mja00** [comment]
We have a couple other worlds in our server that don't do this. It's only the one SSB is hooked onto.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
