### ISSUE TITLE
Mob limit issue on disconnect

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1423]
### Minecraft's Version

1.19.2 paper-211

### Plugin's Version

b877

### Describe the bug

When you disconnect/reconnect, your mob limit isn't save correctly and goes back to 0

### To Reproduce

- Spawn mobs up to the limit
- You can't spawn more mobs
- Disconnect/reconnect
- you can now place more mobs and old one are still here

### Additional Information

https://youtu.be/0ERcHBtbAFk

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by WarnDa** [comment]
Fixed thanks
