### ISSUE TITLE
Plugin cannot use java8

### ISSUE THREAD

**Issue by 2592019238-ai** [BG-Software-LLC/SuperiorSkyblock2#1425]
### Minecraft's Version

1.12.2
mohist-1.12.2-321-server

### Plugin's Version

SuperiorSkyblock2-2022.8.1-b877

### Describe the bug

Plugin cannot use java8
Generate island error after use
![image](https://user-images.githubusercontent.com/62113680/196877386-b38d61ef-41b3-4e0c-821a-0fab79cfea8d.png)

### To Reproduce

After java8 starts the server, use /is create to create an island

### Additional Information

![image](https://user-images.githubusercontent.com/62113680/196877915-803b4a82-c517-407b-ab10-a87ff837f965.png)

**Comment by OmerBenGera** [comment]
Its something with your upgrades, nothing to do related to your Java version.
Try it on a server with default files, let me know if it still occurs

**Comment by OmerBenGera** [comment]
Mind sharing with me your config file?
Upload it to pastebin and send it here.

**Comment by 2592019238-ai** [comment]
> 

The configuration file is automatically generated by the plugin
[SuperiorSkyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9832214/SuperiorSkyblock2.zip)

**Comment by OmerBenGera** [comment]
> > 
> 
> The configuration file is automatically generated by the plugin [SuperiorSkyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9832214/SuperiorSkyblock2.zip)

I see.
The issue is that for no reason, when trying to sync some upgrades, it goes through world environments that don't exist anymore, which I am sure is caused because of Mohist.
If you try it on Paper, it will work.

**Comment by 2592019238-ai** [comment]
> > > 
> > 
> > 
> > 配置文件由插件[高级天空块2自动生成.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9832214/SuperiorSkyblock2.zip)
> 
> 明白了。问题是，无缘无故地，当尝试同步某些升级时，它会穿过不再存在的世界环境，我确信这是由于Mohist造成的。如果你在纸上尝试它，它会起作用。
Oh, looks like I have to change other plugins. This core 1.12 has been discontinued.

**Comment by OmerBenGera** [comment]
> > > > 
> > > 
> > > 
> > > 配置文件由插件[高级天空块2自动生成.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9832214/SuperiorSkyblock2.zip)
> > 
> > 
> > 明白了。问题是，无缘无故地，当尝试同步某些升级时，它会穿过不再存在的世界环境，我确信这是由于Mohist造成的。如果你在纸上尝试它，它会起作用。
> > Oh, looks like I have to change other plugins. This core 1.12 has been discontinued.
