### ISSUE TITLE
Nether border isnt working on last dev build

### ISSUE THREAD

**Issue by LO383krystianch** [BG-Software-LLC/SuperiorSkyblock2#1426]
### Minecraft's Version

1.19.2 purpur las build 

### Plugin's Version

Dev Build
#884

### Describe the bug

players can't do anything in nether, it says "you can't build outside the island border" all the time

### To Reproduce

Go to nether as player and try do anything

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
