### ISSUE TITLE
Get this warn after server load

### ISSUE THREAD

**Issue by Neeekss** [BG-Software-LLC/SuperiorSkyblock2#1427]
### Minecraft's Version

1.19.2

### Plugin's Version

2022.8.1

### Describe the bug

I just upload a new superiorskyblock2 version on my server and when I get this warning messages https://pastebin.com/7Qt99aHz

### To Reproduce

install the new version on 1.19.2

**Comment by Neeekss** [comment]
and get this on load islands https://pastebin.com/wi7yxcgb

**Comment by Tptuaazn** [comment]
Try using dev build.

**Comment by OmerBenGera** [comment]
Update to latest dev build
