### ISSUE TITLE
Entities are not counted after disconnect

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1428]
### Minecraft's Version

paper 1.19.2

### Plugin's Version

b885

### Describe the bug

When you disconnect, tile entities like armor_stand aren't counted anymore for island limit

### To Reproduce

- place armor_stand
- disconnect/reconnect
- the count goes back to 0

### Additional Information

https://youtu.be/donBI699Dd4

**Comment by OmerBenGera** [comment]
Armor stands are not tile entities.
Does it happen with other mobs as well?

**Comment by WarnDa** [comment]
Didn’t get the issue on mobs, only on tile entity
Will try other mobs once at home

**Comment by OmerBenGera** [comment]
> Didn’t get the issue on mobs, only on tile entity Will try other mobs once at home

Tile entities are blocks that have additional data - chests, hoppers, etc. However, you pointed armor stands not counted, so I am confused.

**Comment by WarnDa** [comment]
Oh sorry thought armorstand where counted as tile entity

Didn’t get the issue on zombie/skeleton

**Comment by OmerBenGera** [comment]
Armor stands that are not visible are not counted towards entity limits - might be that?

**Comment by WarnDa** [comment]
I also get the issue with MINECART, and just get the issue with SKELETON
It doesn't happen every disconnect/reconnect

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
When loading the island it will count all entities again and adjust the counts again.

I set an entity limit to minecarts, then place a minecart. After that, I log out, wait for the chunk to unload, then log in again.
I still can't place new minecarts.

**Comment by WarnDa** [comment]
Didn't wait for the chunk to unload, and it doesn't always happen.

Also, I tried to manually spawn mobs, and sometimes it doesn't count well mobs (skeleton). I got 8 skeletons it counts 6
https://youtu.be/mlYEuBumXqI

**Comment by OmerBenGera** [comment]
Use `/is admin debug entity_spawn` and `/is admin debug entity_despawn` and start debugging it.
Also, you already opened an issue regarding this - why the duplicate? Can this be closed and we'll move to the other one?

**Comment by WarnDa** [comment]
That's not the same one, this is a new issue that was not before, before when you disconnected/reconnected, it didn't reset the count

**Comment by WarnDa** [comment]
I spawned mobs, disconnected/reconnected, it counts 0 :
https://pastebin.com/37wRHir9

**Comment by OmerBenGera** [comment]
Upload your upgrades file and send it here please

**Comment by WarnDa** [comment]
config : https://hastebin.com/ututisojel.yaml
upgrades : https://hastebin.com/inidomiwug.yaml

**Comment by WarnDa** [comment]
Updated, same issue : https://pastebin.com/MaYDgmSV

**Comment by OmerBenGera** [comment]
What spigot jar do you use?
Exact output of /version

**Comment by WarnDa** [comment]
I was using https://ci.pufferfish.host/job/Pufferfish-1.19/40/changes
pufferfish-40 1.19.2

Now tried on :
> This server is running Paper version git-Paper-246 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: aaf5e39)
You are running the latest version
Previous version: git-Pufferfish-40 (MC: 1.19.2)
and same issue : https://pastebin.com/HYjT4pSx

**Comment by OmerBenGera** [comment]
I found an issue that entities were not counted again if they were not inside the center chunk of the island.
Check out latest dev build, let me know if it works now.

**Comment by WarnDa** [comment]
Thanks it works, but mobs aren't counted for all world, but per world.
It I set ZOMBIE limit to 2,
I can get 2 zombie in SuperiorWorld
2 zombies in superiorworld_nether
2 zombies in superiorworld_the_end

Is it normal ?

**Comment by OmerBenGera** [comment]
I placed a minecart in the normal world, then teleported to nether and tried to place another but I can't.
I can't replicate the issue with the worlds... What am I doing wrong?

**Comment by OmerBenGera** [comment]
However, I believe the bug is because the chunks in the overworld are unloaded, so the entities are not counted anymore. Therefore, you can spawn more entities in the other worlds. This can be fixed by not removing counts for entities in unloaded chunks, however I am not sure if that's a good idea, as it can lead to incorrect entity counting.

**Comment by WarnDa** [comment]
Yes I see, it's fine, shouldn't be a big issue I hope

I think we can close the other ticket about mob issue, and hope your current changed fixed the other ticket too

**Comment by OmerBenGera** [comment]
> Yes I see, it's fine, shouldn't be a big issue I hope
> 
> I think we can close the other ticket about mob issue, and hope your current changed fixed the other ticket too

We'll keep it open for the time being.
However, make sure you update me there what's the status of that bug.

I am closing this now :)
