### ISSUE TITLE
generators not work

### ISSUE THREAD

**Issue by kikozz** [BG-Software-LLC/SuperiorSkyblock2#1434]
### Minecraft's Version

Purpur 1.19.2-R0.1-SNAPSHOT

### Plugin's Version

2022.8.1-b885

### Describe the bug

  generator:
    normal:
      - COBBLESTONE:92
      - COAL_ORE:5
      - IRON_ORE:3

I changed generators in config and reload it doesn't work

![SN~I5E00B9$E}NV1Q`LV28B](https://user-images.githubusercontent.com/26044865/198611382-0148a5ea-06cf-4ee6-b20d-a952c7b0173d.png)

### To Reproduce

~

### Additional Information

~

**Comment by kikozz** [comment]
only IRON_ORE have this Bug
wtf

**Comment by OmerBenGera** [comment]
You need to update the upgrades file, it's even stated in the config file.
https://wiki.bg-software.com/superiorskyblock/overview/upgrades
