### ISSUE TITLE
Undercalculation

### ISSUE THREAD

**Issue by Pledix** [BG-Software-LLC/SuperiorSkyblock2#1435]
### Minecraft's Version

When the player starts the game, the blocks of the initial island must be counted when calculating the island level. Since this is not the case now, when players break even one of the blocks, they fall below 0, that is, negative levels.

### Plugin's Version

2022.8.1-b885

### Describe the bug

Negative island level problem caused by undercalculation

### To Reproduce

The player creates his island. After breaking a block on his island, the island level drops to negative values.

**Comment by OmerBenGera** [comment]
Not a bug, this is an intended behavior.
If you offset levels and worth for islands, then breaking schematic blocks will make them go negative.
