### ISSUE TITLE
Generators not work

### ISSUE THREAD

**Issue by Neeekss** [BG-Software-LLC/SuperiorSkyblock2#1440]
### Minecraft's Version

Paper 1.19.2

### Plugin's Version

2022.8.1-b886

### Describe the bug

I've noticed that Cobble-Generators break after a few blocks because the lava spawns a "Ghost Block" which makes it stop flowing towards the water which will then stop the generator from working.

### To Reproduce

make a generator and start mining it will stop after 4-8 blocks mined

**Comment by OmerBenGera** [comment]
I can't replicate the issue on my server
Try replicating it yourself on a server with only SuperiorSkyblock installed.

**Comment by Neeekss** [comment]
The problem was in generator-rates where I was using the wrong name (LAPIS_LAZULI) now I change it to LAPIS_ORE and it working fine.

**Comment by OmerBenGera** [comment]
> The problem was in generator-rates where I was using the wrong name (LAPIS_LAZULI) now I change it to LAPIS_ORE and it working fine.

Great :)
