### ISSUE TITLE
Island member can not shear sheeps

### ISSUE THREAD

**Issue by nhanledev** [BG-Software-LLC/SuperiorSkyblock2#1441]
### Minecraft's Version

paper-1.19.2-245

### Plugin's Version

SuperiorSkyblock2-2022.8.1-b885

### Describe the bug

Given permissions as default config file, island member can breed, can kill, can spawn animals but can not shear the sheep for wools. Owner of the island still can do it.

### To Reproduce

1. Create an island
2. Invite other player as member
3. Use the shears to shear the sheep. Expect wools drop. Result: ISLAND_PROTECTED error message.

**Comment by OmerBenGera** [comment]
Thanks for reporting!
Add `ANIMAL_SHEAR` to coop in your config file to fix it :)

**Comment by nhanledev** [comment]
> Thanks for reporting! Add `ANIMAL_SHEAR` to coop in your config file to fix it :)

Thank you for the quick reply! I could not find this on the WIKI so I think you should add it 👍

**Comment by OmerBenGera** [comment]
> > Thanks for reporting! Add `ANIMAL_SHEAR` to coop in your config file to fix it :)
> 
> Thank you for the quick reply! I could not find this on the WIKI so I think you should add it 👍

I added it by default to the config file. I will also make sure the wiki is up to date.
