### ISSUE TITLE
Oneblock block reset

### ISSUE THREAD

**Issue by PISOGKalg** [BG-Software-LLC/SuperiorSkyblock2#1446]
### Minecraft's Version

1.8.8

### Plugin's Version

SuperiorSkyblock2-1.10.2.jar

### Describe the bug

Ehmm i need some help, everytime I break chests, and pumpkin's the block will not respawn

### To Reproduce

Everytime i break pumpkin's, and not full blocks on my island, i wont respawn

### Additional Information

![image](https://user-images.githubusercontent.com/35006868/199427243-cfc4b6a6-912b-4991-b73c-352a68f9b44e.png)

**Comment by OmerBenGera** [comment]
I dont understand what I see in the screenshot...
Also, you use a really old version of SSB, which means you also use an old version of the OneBlock module.
Update both, check if the issue still occurs.

**Comment by PISOGKalg** [comment]
Sometimes it will not respawn. and then u nead to place a block to get it to respawn, and in the same time, if u are getting to phase 2, u will go to phase 10.

**Comment by OmerBenGera** [comment]
> Sometimes it will not respawn. and then u nead to place a block to get it to respawn, and in the same time, if u are getting to phase 2, u will go to phase 10.

After you complete level 10 it will not go back to level 1 unless you configure it to do so...

**Comment by PISOGKalg** [comment]
i know i know, but when i do complet level 1, it gos to level 10 
no stop in other levels

**Comment by OmerBenGera** [comment]
> i know i know, but when i do complet level 1, it gos to level 10 no stop in other levels
> 
> ![image](https://user-images.githubusercontent.com/35006868/200411100-b1e0a3ec-bb4c-40aa-9f01-0e9fdbf739d1.png)

Use default files, you probably changed something that caused it

**Comment by PISOGKalg** [comment]
nope, i have just reinstale, and it still makes the still error

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
Please take a video and upload it to an online streaming service (youtube, for example)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
