### ISSUE TITLE
/is command problem

### ISSUE THREAD

**Issue by sh1220** [BG-Software-LLC/SuperiorSkyblock2#1447]
### Minecraft's Version

1.12.2

### Plugin's Version

2022.9

### Describe the bug

![is problem](https://user-images.githubusercontent.com/61071228/199504889-1ccb4203-72da-4bf5-8245-84870893101f.PNG)

When I type /is, This will appear in the chat

### To Reproduce

type /is

**Comment by OmerBenGera** [comment]
Another plugin overrides /is, nothing to do with the plugin.
You can use /island or just configure another command in the config file.
