### ISSUE TITLE
The option to surrender the leader on the island does not work, and you cannot withdraw a person to a member

### ISSUE THREAD

**Issue by xFlike** [BG-Software-LLC/SuperiorSkyblock2#1448]
### Minecraft's Version

paper-1.19-81.jar

### Plugin's Version

SuperiorSkyblock2-2022.9-b896

### Describe the bug

Two options do not work: returning the island leader and returning a person to an island member. Giving a moderator or admin works without a problem. These two options do nothing at all. There is no chat message.

### To Reproduce

You must have at least two people on the island to join via "/is members"

Then you come into the player roles

And if you use a moderator or an admin, you cannot withdraw a person to a member. It is also impossible to completely give an island leader

### Additional Information

![Zrzut ekranu 2022-11-02 161503](https://user-images.githubusercontent.com/116177569/199528007-ff0cfa72-3347-4e6b-a35b-50985240f0be.png)

https://pastebin.com/WfQuJy7L

**Comment by xFlike** [comment]
Please help me bro

**Comment by xFlike** [comment]
Help me please bro

**Comment by OmerBenGera** [comment]
It works fine for me.
Maybe you changed the role names and didn't update the members role menu?

**Comment by xFlike** [comment]
![image](https://user-images.githubusercontent.com/116177569/200012404-3fa26095-ea82-4cf0-9477-599f9294184c.png)

![image](https://user-images.githubusercontent.com/116177569/200012597-e42c3efa-eb1b-4e28-b5f5-e58d00636efc.png)

I haven't changed this in the config :/

**Comment by xFlike** [comment]
No matter, sorry to bother you at all, I did not notice that it was my fault that I had a wrong configuration. I couldn't find it completely

Thanks for helping out, have a nice day

**Comment by OmerBenGera** [comment]
All's good bud :)
