### ISSUE TITLE
Can't set teleported_success empty

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1449]
### Minecraft's Version

pufferfish 1.19.2

### Plugin's Version

b894

### Describe the bug

If you set 
> TELEPORTED_SUCCESS: ''

it will send an empty space in the chat everytime you teleport, I want to disable completely this message

### To Reproduce

1) Set TELEPORTED_SUCCESS: ''
2) Teleport to island

**Comment by OmerBenGera** [comment]
I changed it to `''` and used `/is tp` and didn't receive any message.

**Comment by WarnDa** [comment]
Okay I'm dumb it was another plugin sending a space, sorry for this
