### ISSUE TITLE
Top placeholders are not updated

### ISSUE THREAD

**Issue by BaM6Uk** [BG-Software-LLC/SuperiorSkyblock2#1451]
### Minecraft's Version

git-Purpur-1632 (MC: 1.18.2)

### Plugin's Version

2022.9-b897

### Describe the bug

Top placeholders are not updated
![image](https://user-images.githubusercontent.com/106199442/200121149-14abd9dd-fa5e-4217-b7ee-302f3c931c2a.png)
They will be updated if you write /is top
%superior_island_top_level_1%
%superior_island_top_level_value_1%
The positions in the top do not change when using placeholders

### To Reproduce

The positions in the top do not change when using placeholders

### Additional Information

Add auto-update top placeholders

**Comment by OmerBenGera** [comment]
Top islands are updated when you execute /is top.
