### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by PISOGKalg** [BG-Software-LLC/SuperiorSkyblock2#1456]
### Minecraft's Version

1.8.8

### Plugin's Version

SuperiorSkyblock2-2022.9.jar

### Describe the bug

Hello!

1 question
when i am mining my oneblock, and it gets a new level, it goes from level 1, to max level?

2 question
when i am mining my oneblock, it sometimes wont respawn again, and yes I got the lates version of all the plugin, and module

### To Reproduce

as i sad, it wont respawn, ant it goes to max level

### Additional Information

![image](https://user-images.githubusercontent.com/35006868/200182093-a55fdab0-66d3-4b9e-8bd2-fbadb2b76ab4.png)

**Comment by OmerBenGera** [comment]
The OneBlock will not generate again if another plugin interfaces with it. Also you should ask questions on the discord server and not here.
Anyways, not related to SSB.
