### ISSUE TITLE
End Crystals can be placed and exploded on any island

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1458]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

897

### Describe the bug

End Crystals can be placed and exploded on any island even if player doesn't have permissions and explosions are disabled on island

### To Reproduce

Place end crystal on other island (on obsidian)

**Comment by OmerBenGera** [comment]
I could place an end crystal (which is a bug on its own), however couldn't explode it.
How did you explode the end crystal?

**Comment by OmerBenGera** [comment]
I fixed the ability to spawn end crystals on other islands.
I also want to fix the ability to explode them if you don't have access to attack entities, so let me know how you did it :)

**Comment by exzolink** [comment]
Thank you, sorry, misinformed you a bit, players really can't blow them.
