### ISSUE TITLE
Settings option in control panel often doesn't work

### ISSUE THREAD

**Issue by Sizzuns** [BG-Software-LLC/SuperiorSkyblock2#1462]
### Minecraft's Version

git-Purpur-1832 (MC: 1.19.2)*

### Plugin's Version

2022.9

### Describe the bug

https://user-images.githubusercontent.com/56275373/200636435-8f43aaac-725e-4478-9100-aed7d9f13485.mp4

### To Reproduce

it's working perfectly fine, but sometimes it's bugging a lot, so I don't have a specific way to reproduce this bug, because it's random

**Comment by OmerBenGera** [comment]
I couldn't replicate the issue myself.

**Comment by Sizzuns** [comment]
Hello, I've found the reason of the error. It only happens when deluxemenus plugin is installed on the server. Is there a possibility that both plugins will work well with each other?

**Comment by OmerBenGera** [comment]
> Hello, I've found the reason of the error. It only happens when deluxemenus plugin is installed on the server. Is there a possibility that both plugins will work well with each other?

Weird.
Is your settings menu from DeluxeMenus or its from SSB?

**Comment by Sizzuns** [comment]
It's from SSB

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by Sizzuns** [comment]
Yeah it's working, but now the island top icon do nothing, same as the ./is top

**Comment by OmerBenGera** [comment]
I reworked on the menus and some of them gonna have issues and errors, so sorry about that mess.
Make sure you report all of the errors you find :)

Anyways, I fixed the top menu bug. If you encounter other issues, report them on separate issues :)
I am closing this
