### ISSUE TITLE
islands being deleted

### ISSUE THREAD

**Issue by saffue** [BG-Software-LLC/SuperiorSkyblock2#1463]
### Minecraft's Version

Paper: 263 
MC: 1.19.2 

### Plugin's Version

SuperiorSkyblock2-2022.9-b897

### Describe the bug

no error or anything, doesnt happen every time, for some reason just to 2 of my players, they will leave for the night and log on in the morning to find that their island has been deleted, if you tp to the coords of where the island was its still there they just cant do /is to go back. i checked logs and they arent deleteing or resetting their island, they literally log off at night, log back on in the morning and its gone. doesnt happen when they log off and rejoin a few mins/hours later, only during the night

### To Reproduce

quite literally no idea, theres no error, i have checked config, logs and permissions for an idea and nothing is different

### Additional Information

[SuperiorSkyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/9963937/SuperiorSkyblock2.zip)

**Comment by OmerBenGera** [comment]
Was there a restart between their logout time and their login time?
Do you have any login plugin that might have changed their UUID?

**Comment by OmerBenGera** [comment]
Was there a restart between their logout time and their login time?
Do you have any login plugin that might have changed their UUID?

**Comment by saffue** [comment]
i think there was a restart between their login and log out, and no i dont think have a plugin that would change their uuid

**Comment by OmerBenGera** [comment]
> just happened again, i just noticed they were using one of my islands i had made, same with the other island that got deleted, could it be something i did wrong there?

Wdym an island that you made?

**Comment by OmerBenGera** [comment]
> just happened again, i just noticed they were using one of my islands i had made, same with the other island that got deleted, could it be something i did wrong there?

Wdym an island that you made?

**Comment by saffue** [comment]
one of the schematics i made and added to the list of starter island

**Comment by OmerBenGera** [comment]
> one of the schematics i made and added to the list of starter island

I dont think its related to that

**Comment by saffue** [comment]
i just tried using a deopped account, reloaded the server and the island was still there

**Comment by OmerBenGera** [comment]
> i just tried using a deopped account, restarted the server and the island was still there

Does it happen only for OPed accounts..?
Also, after it happens, open the DB and check if the island for the player exists inside it.

**Comment by saffue** [comment]
no it happens for all accounts, both opped and not. 
as for the db, the accounts that lost their islands were dode, deadpicsel, one_ and ghost, ghost and one_ remade his island and i moved his stuff over, but dode and deadpicsel havnt made new island since it "deleted", all mentioned names are in the database

**Comment by OmerBenGera** [comment]
> no it happens for all accounts, both opped and not. as for the db, the accounts that lost their islands were dode, deadpicsel, one_ and ghost, ghost and one_ remade his island and i moved his stuff over, but dode and deadpicsel havnt made new island since it "deleted", all mentioned names are in the database, however all deletes happened minimum 24 hours ago, so next time it happens i will check

Check if their islands is in the db, not if they have their player records...

**Comment by OmerBenGera** [comment]
> idk if im lookin in the wrong file or i just dont know what im looking for but its just a string of numbers and letters with the usernames in

You need to look for their island record, there will be no username in there

**Comment by saffue** [comment]
could you point me to what exactly i might be looking for, i search island and theres a million things but not sure its the things i need, that and half of it looks like this 
![image](https://user-images.githubusercontent.com/67953277/201451402-708b8969-193e-41e2-804d-c92d823a215c.png)

**Comment by OmerBenGera** [comment]
> could you point me to what exactly i might be looking for, i search island and theres a million things but not sure its the things i need, that and half of it looks like this, unless this is what im looing for ![image](https://user-images.githubusercontent.com/67953277/201451402-708b8969-193e-41e2-804d-c92d823a215c.png)

You need a program in order to open the database.
Search on google "sqlite viewer" or something like that.

**Comment by saffue** [comment]
name mc says this is deadpicsels but /is admin visit deadpicsel says he doesnt have an island
![image](https://user-images.githubusercontent.com/67953277/201504607-582b2280-2ff0-410e-9de5-6af675ed57be.png)
![image](https://user-images.githubusercontent.com/67953277/201504635-7b89ee3f-63ed-462f-b9da-d8103ab3cec5.png)

**Comment by OmerBenGera** [comment]
> using deadpicsel as i know he hasnt logged on since his island got deleted name mc says this is deadpicsels but /is admin visit deadpicsel says he doesnt have an island ![image](https://user-images.githubusercontent.com/67953277/201504607-582b2280-2ff0-410e-9de5-6af675ed57be.png) ![image](https://user-images.githubusercontent.com/67953277/201504635-7b89ee3f-63ed-462f-b9da-d8103ab3cec5.png)

For the third time, check if there is an island that he is the leader of / member of in the db file.

**Comment by saffue** [comment]
no theress not

**Comment by OmerBenGera** [comment]
> no theres not

Sounds like the island was either deleted by disbanding it or it was never placed in first place to db.
Look for errors related to the database from your logs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by saffue** [comment]
Oh I must have forgotten to reply. Not happened since that I have heard of but there wasn’t one for deadpicsel at all, so I assume it just didn’t make one for some reason

**Comment by OmerBenGera** [comment]
> Oh I must have forgotten to reply. Not happened since that I have heard of but there wasn’t one for deadpicsel at all, so I assume it just didn’t make one for some reason

Should I close this for now?

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs let me know
