### ISSUE TITLE
Island spawn yaw not being utilized

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/SuperiorSkyblock2#1464]
### Minecraft's Version

1.19.2 paper-256

### Plugin's Version

2022.9

### Describe the bug

Doing /is admin setspawn seems to save the yaw in the config, but upon going to the spawn the player will be facing the opposite direction.

### To Reproduce

Set a spawn facing north, then disband your island and it'll send you to this location facing south instead

### Additional Information

Not sure if this is related to using the new proxy bridge, but I think I noticed this happening before I installed it.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
