### ISSUE TITLE
move island command

### ISSUE THREAD

**Issue by Skockwave** [BG-Software-LLC/SuperiorSkyblock2#1465]
### Minecraft's Version

1.12.2

### Plugin's Version

SuperiorSkyblock2-2022.9

### Describe the bug

When the user tps to the island, it works fine, but at some point the command does not move.

### To Reproduce

When the user tps to the island, it works fine, but at some point the command does not move.

**Comment by OmerBenGera** [comment]
A) Bug reports should be in English.
B) what is move command?

**Comment by OmerBenGera** [comment]
> > A) 버그 보고서는 영어로 작성해야 합니다. B) 이동 명령이란 무엇입니까?
> 
> is tp

What do you mean then by not moving?
What happens when they try to teleport?

**Comment by Skockwave** [comment]
> > > A) 버그 보고는 한국어로 작성해야 합니다. B) 이동식 물리학자?
> > 
> > 
> > 이다
> 
> 그렇다면 움직이지 않는다는 것은 무엇을 의미합니까? 텔레포트를 시도하면 어떻게 됩니까?

If you write a command, the command is not written. The red line doesn't appear and it's crazy. How do I explain this?

Command will not tp the player to the island.

Also, island owners tend not to be moved, and not all island members can be moved.

**Comment by OmerBenGera** [comment]
> > > > A) 버그 보고는 한국어로 작성해야 합니다. B) 이동식 물리학자?
> > > 
> > > 
> > > 이다
> > 
> > 
> > 그렇다면 움직이지 않는다는 것은 무엇을 의미합니까? 텔레포트를 시도하면 어떻게 됩니까?
> 
> If you write a command, the command is not written. The red line doesn't appear and it's crazy. How do I explain this?
> 
> Command will not tp the player to the island.
> 
> Also, island owners tend not to be moved, and not all island members can be moved.

Take a video of the issue.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know by replying here
