### ISSUE TITLE
Nether generator does not work

### ISSUE THREAD

**Issue by iXmaxGames** [BG-Software-LLC/SuperiorSkyblock2#1466]
### Minecraft's Version

Paper-388 (MC: 1.18.2)

### Plugin's Version

2022.9

### Describe the bug

I have added a nether generator type in the upgrades config file and it does not work and only produces cobblestone. The overworld (normal) world works fine. 

### To Reproduce

Make a generator in the nether.

### Additional Information

Upgrades config file (https://pastebin.com/05nAkLn5)

**Comment by OmerBenGera** [comment]
Do you see your generator rates in /is admin show?

**Comment by iXmaxGames** [comment]
Yes I do. 
![image](https://user-images.githubusercontent.com/52090355/201321440-8187006f-66aa-4082-9a00-1573a94c03aa.png)

**Comment by OmerBenGera** [comment]
> Yes I do. ![image](https://user-images.githubusercontent.com/52090355/201321440-8187006f-66aa-4082-9a00-1573a94c03aa.png)

Mind taking a video of the nether generator?

**Comment by iXmaxGames** [comment]
[https://streamable.com/q2t27o](url)

**Comment by OmerBenGera** [comment]
> [https://streamable.com/q2t27o](url)

That's not how you make generators in the nether... How did you place water in the nether in first place?
https://minecraft-archive.fandom.com/wiki/Basalt_Generator

**Comment by iXmaxGames** [comment]
Never knew basalt generators were a thing.
