### ISSUE TITLE
Players can create islands without premission to them

### ISSUE THREAD

**Issue by kamo125** [BG-Software-LLC/SuperiorSkyblock2#1468]
### Minecraft's Version

git-Purpur-1835 (MC 1.19.2)

### Plugin's Version

2022.8 b885

### Describe the bug

In confuguration of menu island create, i have setup a permission, that players need to create this island, but they can access it even without the permission.

### To Reproduce

Setup permission for island in this menu, player without permission opens /is and can create this island anyway.

**Comment by OmerBenGera** [comment]
How did you setup the permission?
Upload the menu to pastebin and send it here
