### ISSUE TITLE
The Upgrade is Free

### ISSUE THREAD

**Issue by Xeppy94** [BG-Software-LLC/SuperiorSkyblock2#1469]
### Minecraft's Version

1.19.2

### Plugin's Version

SuperiorSkyblock2-2022.9 

### Describe the bug

All island development is free, don't check the amount (I'm not an admin)

### To Reproduce

island development

**Comment by OmerBenGera** [comment]
Try using the default files and check if it still occurs.
Also, make sure you have Vault and an economy plugin installed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know by replying here
