### ISSUE TITLE
Why does island biome change

### ISSUE THREAD

**Issue by MYJAYDERN** [BG-Software-LLC/SuperiorSkyblock2#1470]
### Minecraft's Version

1.18.1

### Plugin's Version

2022.9

### Describe the bug

I am trying to convert my desert to nether biome

### To Reproduce

I am trying to change island biome

**Comment by OmerBenGera** [comment]
You need to give more information about the bug you report.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know by replying here
