### ISSUE TITLE
IslandGenerateBlockEvent not triggering

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1471]
### Minecraft's Version

Previous: git-Purpur-1825 (MC: 1.19.2)
* You are 4 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

SuperiorSkyblock2 version 2022.8.1-b885
Feature packed Skyblock core.
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

An IslandMission with the event IslandGenerateBlockEvent never triggers.

### To Reproduce

1. Upload mission
2. Restart Server
3. Make a cobblestone generator on your island

### Additional Information

[createcobblegen.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10017369/createcobblegen.txt)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
