### ISSUE TITLE
error can't use plugin

### ISSUE THREAD

**Issue by PandaKeny** [BG-Software-LLC/SuperiorSkyblock2#1472]
### Minecraft's Version

1.16.5 Paper

### Plugin's Version

1.11.0
![image](https://user-images.githubusercontent.com/87780831/202252643-995898aa-9685-4ea3-b0f4-17bc8ebebf5c.png)

### Describe the bug

error can't use plugin

### To Reproduce

![image](https://user-images.githubusercontent.com/87780831/202252772-15ba2538-56ae-4dad-8de5-b5d29f6c270a.png)

**Comment by OmerBenGera** [comment]
Update to latest dev build...
