### ISSUE TITLE
Deprecated use of CustomTimingsHandler

### ISSUE THREAD

**Issue by DarkyCat** [BG-Software-LLC/SuperiorSkyblock2#1475]
### Minecraft's Version

1.19.2

### Plugin's Version

SuperiorSkyblock2 v2022.9-b903

### Describe the bug

Console warnings

### To Reproduce

Use the latest version of the Purpur/Paper.

### Additional Information

Log: https://mclo.gs/R0d85wq

**Comment by OmerBenGera** [comment]
I know about it, ignore it for now :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
