### ISSUE TITLE
/is setperm fly bypass

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1476]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b903

### Describe the bug

Players can bypass fly limitation in worlds if another player execute /is setperm and allow fly for this player

### To Reproduce

Enable fly, teleport to the world where fly disabled, from another account execute /is setperm firstplayer and allow fly

**Comment by OmerBenGera** [comment]
Island fly is only enabled within island areas.
Is your world with the disabled fly an island world?

**Comment by exzolink** [comment]
> Island fly is only enabled within island areas. Is your world with the disabled fly an island world?

No, its not

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
