### ISSUE TITLE
variables in item missions not working

### ISSUE THREAD

**Issue by KaBoom13** [BG-Software-LLC/SuperiorSkyblock2#1477]
### Minecraft's Version

Current: git-Purpur-1845 (MC: 1.19.2)*
Previous: git-Purpur-1817 (MC: 1.19.2)
* You are running the latest version

### Plugin's Version

2022.9-b903

### Describe the bug

this error occurs in the mission items jar.
is that the variables '{value_<block>}' and '{percentage_<block>}' are not detected and only the variables '{0}' and '{1}' work, which are not suitable when you want to display the amount of required single blocks when multiple blocks are used at once

### To Reproduce

here is what the error looks like
https://pastebin.com/4wqBZUgQ

### Additional Information

here is what the error looks like

![image](https://user-images.githubusercontent.com/76953171/202877868-5437a473-c569-4bdb-9258-9a85722f3607.png)

**Comment by OmerBenGera** [comment]
Not a bug - ItemMission types do not support placeholders, as they don't track this data.
It only checks if you have all of your items in the inventory when you try to complete the mission, unlike other missions that track your progress.
