### ISSUE TITLE
Purge does not work

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#1479]
### Minecraft's Version

1.19.2
Purpur#1851

### Plugin's Version

SuperiorSkyblock2 v2022.9-b911

### Describe the bug

When we purge islands, when we want to restart, we have an error in the console and the server simply does not want to restart

### To Reproduce

> is admin purge 2678400

Restart the server

### Additional Information

https://pastebin.com/raw/r43FLusV

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by DuckyDou** [comment]
Yes but purge dont work
https://pastebin.com/raw/kHq9cw1E

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs let me know by replying here
