### ISSUE TITLE
Crashes server on startup.

### ISSUE THREAD

**Issue by grcq** [BG-Software-LLC/SuperiorSkyblock2#1480]
### Minecraft's Version

version
[16:16:19 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[16:16:19 INFO]: Unknown version

### Plugin's Version

2022.9, can't give output since it crashes the server on start.

### Describe the bug

Whenever I start the server, it tries to override the .jar file in the modules folder, but when it tries to do so it keeps throwing out 2 errors showing "[16:47:08 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while registering module SuperiorSkyblock2-NashornEngine-b6.jar:" and "[SuperiorSkyblock2] An unexpected error occurred while downloading nashorn engine:".
I will give you the whole log file.
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10098643/latest.1.log)

### To Reproduce

I don't know what to write here, and unsure how to reproduce it.

**Comment by OmerBenGera** [comment]
Upload the errors you get to pastebin and send them here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by grcq** [comment]
Forgot I had this and never got any notifications, sorry. Yes, it got fixed somehow after I reinstalled the plugin.
