### ISSUE TITLE
Players die when they enter nether portal

### ISSUE THREAD

**Issue by padakoys** [BG-Software-LLC/SuperiorSkyblock2#1482]
### Minecraft's Version

1.19.2

### Plugin's Version

latest stable

### Describe the bug

Players are keep dying on nether after joining it through portal. I have to temporarily close my server due to this "feature".
They complete the nether missions in order to unlock nether world, but they die when they are joining it. 

### To Reproduce

Create an Island,
Accept and complete the "nether world" mission. 
Create a nether portal and join.

**Comment by OmerBenGera** [comment]
Send me logs of your server by uploading it to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by KvasirQc** [comment]
Hello, I have the same exact issue. I am on last dev build (took here https://hub.bg-software.com/job/SuperiorSkyblock2/)

Here are my logs : https://pastebin.com/vTtDBRzg   (password:password)

Either the portal won't let us tp or we have to type both /is admin unlockworld and /is admin reset ....

I do understand we probably have deleted the world...so I have tried to delete both world folder nether / the end in the root of the server...

But I couldn't find how to load a schematic into an Island... I do see the schematic off the end and the nether in my folder but it never have been applied to my island. :) 

Thank you for your plugin

**Comment by OmerBenGera** [comment]
> Hello, I have the same exact issue. I am on last dev build (took here https://hub.bg-software.com/job/SuperiorSkyblock2/)
> 
> Here are my logs : https://pastebin.com/vTtDBRzg (password:password)
> 
> Either the portal won't let us tp or we have to type both /is admin unlockworld and /is admin reset ....
> 
> I do understand we probably have deleted the world...so I have tried to delete both world folder nether / the end in the root of the server...
> 
> But I couldn't find how to load a schematic into an Island... I do see the schematic off the end and the nether in my folder but it never have been applied to my island. :)
> 
> Thank you for your plugin

Make sure your max-world-size in server.properties is not a small number
If the issue still persists, please open a new issue

**Comment by KvasirQc** [comment]
Haa thank you ill check it out
