### ISSUE TITLE
Warp categories force enabled

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#1483]
### Minecraft's Version

1.8.8 paper

### Plugin's Version

#915 (27-nov-2022 19:15:17)

### Describe the bug

When I disable warp-categories on config.yml, it force enabled when starting (even if set on false)

Thanks!

### To Reproduce

Just set on false and start the server, you'll be seeing warp categories when doing /is warps

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
