### ISSUE TITLE
Island effect make beacon bugged

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1484]
### Minecraft's Version

Pufferfish+ 
32

### Plugin's Version

b911

### Describe the bug

When you got an island effect (using /islands admin seteffect XXX) and you got a beacon, the effect take the lead over the effect.

- If you got the island effect "fast_digging" 1
- You got a beacon with fast digging 2

You'll have the fast digging 1, and the fast digging 2 will bug and will stop applying during 10s every ~18s
https://www.youtube.com/shorts/2_Z6GlXYse8

### To Reproduce

- give yourself fast digging 1
- place a beacon fast digging 2
- wait and see the effect fast digging 2 not always applied

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
