### ISSUE TITLE
Island level calculating issues.

### ISSUE THREAD

**Issue by RisDN** [BG-Software-LLC/SuperiorSkyblock2#1485]
### Minecraft's Version

Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1597 (MC: 1.18.2)
* You are running the latest version

### Plugin's Version

2022.9

### Describe the bug

Some player's island just stops calculating the island value, and it just stays on zero even if they modify the island.  I couldn't reproduce this issue.
Also the /is recalc command doesnt work.

### To Reproduce

The error comes up when using /is recalc.

### Additional Information

![image](https://user-images.githubusercontent.com/64377188/204915548-61f984c4-78ef-46f3-942d-c12e85f4b18b.png)

**Comment by OmerBenGera** [comment]
Update both WildStacker and SuperiorSkyblock, let me know if it helps.

**Comment by RisDN** [comment]
> Update both WildStacker and SuperiorSkyblock, let me know if it helps.

Updated both, still the same error.

**Comment by OmerBenGera** [comment]
> > Update both WildStacker and SuperiorSkyblock, let me know if it helps.
> 
> Updated both, still the same error.

Send me the error again from latest versions.
Upload it to pastebin and send it here instead of a screenshot of it.

**Comment by RisDN** [comment]
Here you go!
https://pastebin.com/t0dgFLYP

**Comment by OmerBenGera** [comment]
Check out latest dev build (of SuperiorSkyblock).
If it is still happening, please send me the logs again from that session.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by RisDN** [comment]
Hey.
Sorry for the late respond. I'm still having this issue. I can send the logs in the afternoon.

**Comment by RisDN** [comment]
https://pastebin.com/pQCUc0dT

SuperiorSkyblock2 - 2022.9-b957
WildChests - 2022.7-b87
WildStacker - 2022.6-b408

git-purpur-1632 (MC: 1.18.2) (Latest)

**Comment by RisDN** [comment]
Recalculation error from the prod server: https://pastebin.com/eB9jqZdT
Also when i asked the player to try using the /is recalc command it just said 0 level. The worth calculation was fine.

**Comment by OmerBenGera** [comment]
SuperiorSkyblock tries to interact with WildStacker but fails as it for no reason tries to load the class instead of using the classes from WildStacker, which makes me believe it's due to Purpur.
Use regular Paper/Spigot, check if it still occurs.

**Comment by RisDN** [comment]
I dont think that WildStacker error has anything to do with the island level calculation thingy.

**Comment by OmerBenGera** [comment]
> I dont think that WildStacker error has anything to do with the island level calculation thingy.

Of course it does.
Do what I asked you to do, let me know if it helps.

**Comment by RisDN** [comment]
Unfortunately replacing purpur is not an opinion.

**Comment by OmerBenGera** [comment]
> Unfortunately replacing purpur is not an opinion.

You can do it for a moment and check if it helps.
Do it on a separate server, check if that helps.

**Comment by RisDN** [comment]
As i said replacing purpur is not an opinion in any way. Can't you just make it support purpur?

**Comment by OmerBenGera** [comment]
> As i said replacing purpur is not an opinion in any way. Can't you just make it support purpur?

That's not something to support, I suspect it's a bug in their core code.
Try it on a Paper server with only WS and SSB installed, let me know if it still occurs.
Run a server on localhost, not on your production server.

**Comment by RisDN** [comment]
> > As i said replacing purpur is not an opinion in any way. Can't you just make it support purpur?
> 
> 
> 
> That's not something to support, I suspect it's a bug in their core code.
> 
> Try it on a Paper server with only WS and SSB installed, let me know if it still occurs.
> 
> Run a server on localhost, not on your production server.

On paper it doesn't seem to have this issue. What can we do to make it work on purpur?

**Comment by OmerBenGera** [comment]
> > > As i said replacing purpur is not an opinion in any way. Can't you just make it support purpur?
> > 
> > 
> > That's not something to support, I suspect it's a bug in their core code.
> > Try it on a Paper server with only WS and SSB installed, let me know if it still occurs.
> > Run a server on localhost, not on your production server.
> 
> On paper it doesn't seem to have this issue. What can we do to make it work on purpur?

Contact Purpur regarding this, it is not an issue with the plugins. I recommend sending them a link to this issue so they better understand the issue.
I am closing this for now.
