### ISSUE TITLE
Plugin not available in default world

### ISSUE THREAD

**Issue by seogwam** [BG-Software-LLC/SuperiorSkyblock2#1486]
### Minecraft's Version

1.8.8 paper-445

### Plugin's Version

Dev Builds
#915 27/11/2022 20:15:17

### Describe the bug

Plugin not available in default world "world"

### To Reproduce

~config

worlds:
  default-world: normal
  world-name: world

  difficulty: EASY
  normal-world: world

### Additional Information

[log.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10128453/log.txt)

**Comment by OmerBenGera** [comment]
This is indeed not supported.
I fixed the error not being indicative at all so it will now properly tell you that this is not supported.
