### ISSUE TITLE
Island Top Menu opening incorrect menu when trying to view the island values

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/SuperiorSkyblock2#1487]
### Minecraft's Version

1.16.5 and Paper-794

### Plugin's Version

SuperiorSkyblock2-2022.9-b915

### Describe the bug

 When I try to left-click any of the island top players head which instead it opens the values menu instead it shows the island visitor's menu

### To Reproduce

Open the island top menu with /is top 
then left-click any of the top island player's heads and when you left click it will show the visitors menu not the island values

### Additional Information

https://i.gyazo.com/8df4e75f9f2005870a738ccf964d0dfc.mp4

**Comment by Tptuaazn** [comment]
Addtional:

![](https://media.discordapp.net/attachments/554282577322704896/1047690344755634197/image0.jpg)

**Comment by Tptuaazn** [comment]
Should be openValues

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
