### ISSUE TITLE
Can't take items on the border

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1491]
### Minecraft's Version

paper-302 1.19.2

### Plugin's Version

b921

### Describe the bug

When you farm items near the border, sometimes there are outside the border and can't be taken.
Also it spams the chat when you try to take them

### To Reproduce

I planted bamboo near the border, and one item that I broke was on the border : 
https://youtu.be/G2gx_TSe_G0
(my lang is FR but it says I  can't build outside my island)

The item hitbox : 
![Screenshot_418](https://user-images.githubusercontent.com/31826333/205444809-871cb903-6d75-4410-b0d1-a0842b721375.png)

**Comment by OmerBenGera** [comment]
Please upload your configuration file, I can't seem to replicate the issue myself.

**Comment by WarnDa** [comment]
> Please upload your configuration file, I can't seem to replicate the issue myself.

Default config just with langage on FR
It doesn't always happen, I tried 10 times until it drops on the border

**Comment by OmerBenGera** [comment]
Do you mind trying it on a server with only SSB installed?

**Comment by WarnDa** [comment]
It’s what I did on the video.
But it’s rare as item need to be out of the border

**Comment by OmerBenGera** [comment]
> It’s what I did on the video. But it’s rare as item need to be out of the border when it falls

You have some sort of an items stacker installed.

**Comment by WarnDa** [comment]
> > It’s what I did on the video. But it’s rare as item need to be out of the border when it falls
> 
> You have some sort of an items stacker installed.

It's wildstacker, will try without it, but will be the same

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
