### ISSUE TITLE
Skip One Item Menus does not work

### ISSUE THREAD

**Issue by N1kyZ** [BG-Software-LLC/SuperiorSkyblock2#1494]
### Minecraft's Version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b925

### Describe the bug

I recently updated the plugin and now when I use the /is command it opens the menu even with **"skip-one-item-menus: true"**. So I went back to the previous version and it was working normally
![image](https://user-images.githubusercontent.com/58773688/205837275-8619f016-6878-41c2-a0d8-40eed2ab74f2.png)

I believe that island-warps and island-chest are not working either but I can't prove it because I didn't test it

### To Reproduce

In island-creation.yml leave only 1 item, and then restart the server and see. Remembering that **"skip-one-item-menus:"** must be true in config.yml
![image](https://user-images.githubusercontent.com/58773688/205837023-f4f78460-16e2-4a7f-9869-cd8ebf96aa81.png)

### Additional Information

my island-creation.yml https://pastebin.com/Qy5mWN32

I tried to post the config.yml but it was saying "dangerous file". But the only changes I made to the config was:

**required-for-creation: false**
![image](https://user-images.githubusercontent.com/58773688/205836845-698e92b1-644b-41f3-a3f1-f100a91f801c.png)

old version that works: SuperiorSkyblock2-2022.8

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by WarnDa** [comment]
Hello,
I still got the issue using b930 on 1.19.2
![image](https://user-images.githubusercontent.com/31826333/207038898-6bdd947a-5107-4289-a089-a2388ad9ef0e.png)

**Comment by N1kyZ** [comment]
I still have it too D:
SuperiorSkyblock2 version 2022.9-b930

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
