### ISSUE TITLE
Error | You are lacking the permission to upgrade into another level

### ISSUE THREAD

**Issue by H565656** [BG-Software-LLC/SuperiorSkyblock2#1495]
### Minecraft's Version

1.12.2

### Plugin's Version

2022.9

### Describe the bug

Users can upgrade their Island into another Level. Please say its an Bug or please help me to finde the permession.

### To Reproduce

n/a

**Comment by OmerBenGera** [comment]
The permission is superior.island.rankup

Not a bug.

**Comment by OmerBenGera** [comment]
> The same Message comes out

Maybe you have a custom permission set to your upgrade?

**Comment by H565656** [comment]
Where can I see or check this?

**Comment by OmerBenGera** [comment]
> Where can I see or check this?

In the upgrades config file

**Comment by H565656** [comment]
Nothing

**Comment by OmerBenGera** [comment]
> Nothing

If you use LuckPerms you can find which permission they lack using their verbose system (google it for more info)

**Comment by H565656** [comment]
I use PermissionsEx

**Comment by H565656** [comment]
I know. Is there anything to do there?

**Comment by OmerBenGera** [comment]
> I know. Is there anything to do there?

Give your players superior.island.*, check if it helps.

**Comment by H565656** [comment]
I gave that permission already.  Do you have any ideas?

**Comment by OmerBenGera** [comment]
> I gave that permission already. Do you have any ideas?

I have an idea; I will add debug messages to when players missing permissions from SSB, and it will be logged to console.
This way we will better know what permission is missing.

**Comment by OmerBenGera** [comment]
Install latest dev build
then, before they open the upgrade menu, run `/is admin debug permission_lookup`, and you'll see in console all permissions checks that the plugin does and the result of them.
This way you'll find which permission they are missing.

**Comment by H565656** [comment]
Thanks I will try it in a few days and will report back. Thanks
