### ISSUE TITLE
The toplist sort is random after restart

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#1496]
### Minecraft's Version

paper 1.12.2

### Plugin's Version

SuperiorSkyblock2-2022.9-b915

### Describe the bug

![image](https://user-images.githubusercontent.com/41546701/205953951-855c6df9-f771-46eb-ad3f-db0c1fcc035f.png)

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Island top is resorted when running `/is top`
Does it fix the issue for you?

**Comment by Superalex0102** [comment]
Yeah it does, didn't know this feature works like this.

**Comment by OmerBenGera** [comment]
> Yeah it does, didn't know this feature works like this.

It should still sort them on startup, so I look into this.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, the islands should get sorted on startup now
