### ISSUE TITLE
Allow to change the priority of player-respawn

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1500]
### Minecraft's Version

pufferfish-46 1.19.2

### Plugin's Version

b929

### Describe the bug

If you set player respawn on island_teleport and die
> player-respawn:
> - ISLAND_TELEPORT

superior won't take the highest priority of the event, and multiverse will respawn you before (without you seeing this), and then teleport to the island, so if you do /back, it will teleport you on the default respawnpoint of the server.

So player can't use /back once they die, as it teleport to the spawn, and not to their last location.

### To Reproduce

- Use multiverse
- use /setspawn
- setup default spawn world
- setup player-respawn to ISLAND_TELEPORT
- suicide/die
- then do /back

### Additional Information

I can't disable multiverse managing spawning, as I need first spawn to be handled
So if superior can take the highest priority on the respawn event, it would solve this

**Comment by OmerBenGera** [comment]
I haven't tried replicating it, but I don't think changing priorities will help.
The issue is that SSB doesn't actually change the respawn location of the event, but it teleports the player - this is because SSB makes sure to teleport you to a safe block before actually teleporting you, and all of this is done asynchronously.

I have a suggestion tho, why not using SSB's `SPAWN_TELEPORT` to handle your spawn teleportation as well as `ISLAND_TELEPORT`? You can combine both of them together to probably achieve the same affect.

**Comment by WarnDa** [comment]
Because I want player to be teleported to his island on respawn, and I can't find a way for multiverse not to handle respawn at all

**Comment by OmerBenGera** [comment]
> Because I want player to be teleported to his island on respawn, and I can't find a way for multiverse not to handle respawn at all

Does it only happen with multiverse, or it happens with any spawn plugin (EssentialsXSpawn, for example)?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WarnDa** [comment]
Essentials make user respawn in the main spawnpoint, if I lower essentials priority I spawn on the world spawnpoint (so idk if it’s managed by multiverse or minecraft itself)

So even without essentialsX it happens

**Comment by WarnDa** [comment]
If you don’t handle the respawn it won’t work, as minecraft/multiverse handle the respawn, and then you teleport player

**Comment by OmerBenGera** [comment]
> Yes I know, you don’t directly block player respawn and force superior to fully handle it, so no solution currently, only solution would be to block other event and force superior to handle it

It's not possible to disable the event. Also, even if I set the respawn location to somewhere and then teleport the player, your /back will not be to the place they died.

**Comment by WarnDa** [comment]
Essentials do it without issue, it respawn them on a defined spawnpoint, and when they /back it’s on their last point, but might be because they just store the death location for the /back

So no known solution, only solution I have is create a plugin that hook in both superior/essentials to handle respawn and /back

thanks for the help
