### ISSUE TITLE
Island Recalc 

### ISSUE THREAD

**Issue by djtmk1** [BG-Software-LLC/SuperiorSkyblock2#1505]
### Minecraft's Version

1.18.2

### Plugin's Version

2022.9

### Describe the bug

When the server restarts /is top does not recalc correctly and you have to do the cmd everytime. 

### To Reproduce

I am not sure exactly but reboot a server with people having Island levels and it wont update

### Additional Information

![image](https://user-images.githubusercontent.com/78946962/206944167-841c012d-177d-4c0c-8e7b-80aea7e9f5fc.png)
Before the recals

![image](https://user-images.githubusercontent.com/78946962/206944200-2dcd408c-f0eb-4c58-9cd6-49a7ac720d56.png)
After the recalc

**Comment by OmerBenGera** [comment]
Update to dev build, already been fixed.
