### ISSUE TITLE
Chunk's PDC is being reset

### ISSUE THREAD

**Issue by fr3qu3ncy-dev** [BG-Software-LLC/SuperiorSkyblock2#1506]
### Minecraft's Version

1.19.2

### Plugin's Version

2022.9

### Describe the bug

When saving data in a chunk's PDC, SSB2 clears the data after a few minutes.

### To Reproduce

Create an island and use another plugin to save data for that chunk, after a few minutes the data disappears.

**Comment by OmerBenGera** [comment]
What is chunk PDC?

**Comment by fr3qu3ncy-dev** [comment]
> What is chunk PDC?

PersistentDataContainer

**Comment by OmerBenGera** [comment]
I saved data to the PDC, then restarted and everything is saved.
Maybe a specific action caused it to occur?
Try replicating it yourself with only that plugin and SSB installed, find what causes this to occur.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
