### ISSUE TITLE
Error when opening a settings menu

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1510]
### Minecraft's Version

1.19.2

### Plugin's Version

b925

### Describe the bug

when opening a is settings menu with custom flag it shows this error

https://pastebin.com/uUX2wgE3

this is section of config for custom flag

https://pastebin.com/cKQ0XuGv

in menu it shows up fine and works

### To Reproduce

create a custom islandflag and add it to settings menu file

**Comment by dan28000** [comment]
edit when having more free slots then flags it does the error

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now

**Comment by dan28000** [comment]
works fine
