### ISSUE TITLE
Hoglin count as animal

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1512]
### Minecraft's Version

b930

### Plugin's Version

puffer 1.19.2

### Describe the bug

In /is permissions, "animal damage" include hoglin, but per default these are hostile mobs.

### To Reproduce

- Allow "animal damage" but not "monster damage" to visitor
- spawn hoglin
- they can kill them

**Comment by WarnDa** [comment]
![image](https://user-images.githubusercontent.com/31826333/207924117-2ca85788-3469-45bc-80f1-14ad74b00cf3.png)
I was more thinking about this, player uses more this as hostile mob :/

**Comment by OmerBenGera** [comment]
You are totally right, I am not sure why Bukkit considered it as Animal, it even stated on minecraft wiki:
```Despite being technically an animal, this mob is classified as a monster in Minecraft.```

Should be fixed in latest dev build, I explicitly added a check so Hoglin are not considered as animals.

**Comment by WarnDa** [comment]
Player tell me "players can't kill hoglin without block break permission"

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by WarnDa** [comment]
fixed thanks
