### ISSUE TITLE
Not a part of island

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1513]
### Minecraft's Version

git-Purpur-1870 (MC: 1.19.3)*

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b930

### Describe the bug

I'm the leader of an island but it say's I'm not part of any island. 
![image](https://user-images.githubusercontent.com/65089425/207976905-8050cbd0-5e8d-4500-8868-b73e172308e8.png)
![image](https://user-images.githubusercontent.com/65089425/207976928-423d2aea-e4ba-4894-9b5c-b23701c50002.png)

### To Reproduce

Not Sure

**Comment by OmerBenGera** [comment]
Has your UUID changed?
This can happen if your server is in offline mode and you have premium login plugin

**Comment by DuneSciFye** [comment]
Yes my UUID has changed in the past. What's a fix?

**Comment by DuneSciFye** [comment]
I've tried removing all traces of me from the database but doesn't fix it.

**Comment by DuneSciFye** [comment]
This might help: https://pastebin.com/3HDpkMEr I ran /is members mega-island and it threw this error. Doesn't for other islands.

**Comment by OmerBenGera** [comment]
Send me your logs file please

**Comment by DuneSciFye** [comment]
https://pastebin.com/PyXRn08u

**Comment by DuneSciFye** [comment]
Any news on this?

**Comment by OmerBenGera** [comment]
Please install latest dev build, and when your server starts, run (from console) `/is admin debug replace_player`
Then, try to login again. If the issue still occurs, send me your logs again.

By running that debug command, more information will be printed to console so we can better understand why it doesn't work.

**Comment by DuneSciFye** [comment]
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10282924/latest.log)

**Comment by OmerBenGera** [comment]
> [latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10289292/latest.log) Still don't have an island, and I forgot to do this until quite a bit later so there will be a bunch of filler. Scroll down to the bottom of the log to see the debug messages.

Did you run it after you logged in?

**Comment by DuneSciFye** [comment]
I was on, ran it, logged off, logged back in

**Comment by OmerBenGera** [comment]
That's interesting that even after you logged in it still tries to replace your player.
Use latest dev build, make sure you run `/is admin debug replace_player` before you log in.

**Comment by DuneSciFye** [comment]
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10296576/latest.log)
Still not a part of any island. I'm using latest dev build, restarted server, ran the command the second it was finished starting, then I joined.

**Comment by OmerBenGera** [comment]
Let's talk on discord, some strange things are happening.

**Comment by OmerBenGera** [comment]
Closing this as it's been fixed.

**Comment by WarnDa** [comment]
it completely killeda all islands.
After the update all players do not get islands anymore

**Comment by OmerBenGera** [comment]
> it completely killeda all islands. After the update all players do not get islands anymore, I had to rollback the database and superior to b943 to fix this

Make sure you use latest dev build.

**Comment by WarnDa** [comment]
> > it completely killeda all islands. After the update all players do not get islands anymore, I had to rollback the database and superior to b943 to fix this
> 
> Make sure you use latest dev build (953)

I did... and it litterally broke everything, nobody was part of an island and they could create a new island

**Comment by OmerBenGera** [comment]
> > > it completely killeda all islands. After the update all players do not get islands anymore, I had to rollback the database and superior to b943 to fix this
> > 
> > 
> > Make sure you use latest dev build (953)
> 
> I did... and it litterally broke everything, nobody was part of an island and they could create a new island

Have you looked for errors or warnings in console?

**Comment by OmerBenGera** [comment]
> > > it completely killeda all islands. After the update all players do not get islands anymore, I had to rollback the database and superior to b943 to fix this
> > 
> > 
> > Make sure you use latest dev build (953)
> 
> I did... and it litterally broke everything, nobody was part of an island and they could create a new island

Upload your session logs to pastebin and send it here.

**Comment by WarnDa** [comment]
session logs ?

**Comment by OmerBenGera** [comment]
> session logs ?

The logs file from when ypu used the dev build that broke everything

**Comment by WarnDa** [comment]
It spammed errors : https://pastebin.com/zg6rbs6A

(sorry didn't check logs before)

**Comment by WarnDa** [comment]
https://paste.helpch.at/ehaqapevuf.makefile

**Comment by OmerBenGera** [comment]
Do you mind also uploading logs of a working session (using an older version)?

**Comment by WarnDa** [comment]
https://paste.helpch.at/duzajugiye.makefile

**Comment by OmerBenGera** [comment]
@WarnDa Hey, please try using latest dev build
I added more log messages if the issue occurs again, so we better understand what causes this to occur.
I changed the plugin to not load data for unrecognized players anymore from the DB, and it seems like some of your island have unrecognized owners. I added log messages with the unrecognized player uuids so you can later lookup manually and see if they are in the DB.

You don't have to load it on the production server, you can try it on a testing server with the same DB (copy it or something)

**Comment by WarnDa** [comment]
Will try it once I can, thanks

**Comment by WarnDa** [comment]
https://paste.helpch.at/iwaqaqojew.makefile

**Comment by WarnDa** [comment]
But I only uploaded database not the map, not sure if it's fine, but I don't want to create issue by putiting it again on the production server

**Comment by OmerBenGera** [comment]
You need to copy the entire SSB folder as many of the islands are not loaded in this run because they are not correctly centered, even tho in the production server they probably are.

Do you mind doing it again with the same SSB folder?

**Comment by WarnDa** [comment]
I already copied the whole folder, but I might need to copy also all the player database

**Comment by OmerBenGera** [comment]
> I'll try with a perfect replica of the server this weekend and tell you

Awesome, waiting for your response :)

**Comment by WarnDa** [comment]
https://paste.helpch.at/daqavobuyu.makefile

It worked on b950, updated to b954 and had this error, I had to recreate my island as I didn't get any island in database according to the plugin.

**Comment by DuneSciFye** [comment]
For some reason, the issue isn't really fixed. We discussed on discord and we we're able to fix it specifically for me, maybe because we did something in the database, but for any other player that joins on both java and bedrock lose their island and basically breaks their account.

**Comment by OmerBenGera** [comment]
> 

Your players DB does not contain a player record for your player as it seems.
I don't know how it occurred.

**Comment by OmerBenGera** [comment]
> https://paste.helpch.at/daqavobuyu.makefile
> 
> It worked on b950, updated to b954 and had this error, I had to recreate my island as I didn't get any island in database according to the plugin. And my UUID : eb69cef0-8d6b-49bb-9575-e751185834b2 (premium server running under Velocity)

Your players DB does not contain a player record for your player as it seems.
I don't know how it occurred.

**Comment by OmerBenGera** [comment]
> For some reason, the issue isn't really fixed. We discussed on discord and we we're able to fix it specifically for me, maybe because we did something in the database, but for any other player that joins on both java and bedrock lose their island and basically breaks their account.

Does it still occur for new players?

**Comment by DuneSciFye** [comment]
> 

What do you mean by new players? New players that aren't in the database yet? I'm not sure, but for anyone that has another account join with the same username loses their island.

**Comment by OmerBenGera** [comment]
> > 
> 
> What do you mean by new players? New players that aren't in the database yet? I'm not sure, but for anyone that has another account join with the same username loses their island.

Do you see the converting message in console for them?

**Comment by WarnDa** [comment]
Still no news ? still can't upgrade because of this :/
On discord I can share you database before conversion (b950) + database after conversion (b964) if needed

**Comment by WarnDa** [comment]
Edit : I just switched on a replica of my server from b950 to b964, seems working, will try in production soon and hope

**Comment by OmerBenGera** [comment]
This seems to be fixed with latest versions
If the issue still occurs, let me know
