### ISSUE TITLE
Problem with refresh placeholders

### ISSUE THREAD

**Issue by D3BoxOfficiel** [BG-Software-LLC/SuperiorSkyblock2#1514]
### Minecraft's Version

1.18.2 

### Plugin's Version

2022.9-b935

### Describe the bug

Hi, I have a problem every time the server restarts the /is top (placeholder does not refresh) players need to put a block for it to refresh possible to make it refresh on its own after every reboot?

### To Reproduce

Just put your placeholders in decentholo and restart (normaly ur placeholder dosen't refresh)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know

**Comment by D3BoxOfficiel** [comment]
Hi, sorry for the late response with the holidays but the latest dev version doesn't work (it doesn't update the placeholders, you still have to wait)

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue myself
Do you have a SQLite database that I can try and look into it myself with your DB?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
