### ISSUE TITLE
[1.19.2+] When depositing money into the Island Bank via the GUI, the game kicks you for "Chat message validation failure"

### ISSUE THREAD

**Issue by JoelSoep** [BG-Software-LLC/SuperiorSkyblock2#1515]
### Minecraft's Version

1.19.2

### Plugin's Version

2022.9

### Describe the bug

When using /is bank you get a nice GUI. However, when selecting the option "Deposit Money" you are prompted to insert an amount. When doing so, the game kicks everyone with the message "Chat message validation failure."

### To Reproduce

1. /is bank
2. Select option "Deposit Money" (So not all or half)
3. Enter the amount

**Comment by JoelSoep** [comment]
Update: this happens in island teamchat as well.

**Comment by OmerBenGera** [comment]
I did some research and found out its something to do with your client.
https://bugs.mojang.com/browse/MC-255394

Try it with vanilla client, let me know if it works.

**Comment by JoelSoep** [comment]
I was on vanilla. However, I was playing on a Velocity proxy, if that can make a difference.

**Comment by OmerBenGera** [comment]
> I was on vanilla. However, I was playing on a Velocity proxy, if that can make a difference.

Maybe
Try it on a regular Spigot/Paper server

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by DarkyCat** [comment]
> ### Minecraft's Version
> 
> 1.19.2
> ### Plugin's Version
> 
> 2022.9
> ### Describe the bug
> 
> When using /is bank you get a nice GUI. However, when selecting the option "Deposit Money" you are prompted to insert an amount. When doing so, the game kicks everyone with the message "Chat message validation failure."
> ### To Reproduce
> 
>     1. /is bank
> 
>     2. Select option "Deposit Money" (So not all or half)
> 
>     3. Enter the amount
> 
> 
> ### Additional Information
> 
> _No response_

Fix https://modrinth.com/plugin/freedomchat/version/1.2.1

**Comment by JoelSoep** [comment]
After doing some research, this is not an error of the SuperiorSkyblock2 (for me), as I run it on a Velocity proxy. A fix for this has been scheduled in their 3.1.2 update. For more information, please visit https://github.com/PaperMC/Velocity/issues/804

**Comment by OmerBenGera** [comment]
I am closing this as I don't think it's an issue with SSB neither.
