### ISSUE TITLE
[BUG] enchant missions not working

### ISSUE THREAD

**Issue by KaBoom13** [BG-Software-LLC/SuperiorSkyblock2#1519]
### Minecraft's Version

Current: git-Purpur-1845 (MC: 1.19.2)*
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

2022.9-b943

### Describe the bug

when we combine 2 tools in the anvil to get a given item required for a mission, it is not counted.

### To Reproduce

take 2 tools that will give you the item that is given in the mission, e.g. one pickaxe (fortune 3, unbreaking 3, efficency 4) and the second pickaxe with (efficiency 4) to get the required pickaxe (fortune 3, unbreaking 3, efficency 5) which is needed to complete the mission but fails the mission.

**Comment by OmerBenGera** [comment]
Upload your enchanting mission to pastebin and send it here please

**Comment by KaBoom13** [comment]
https://pastebin.com/k36P0TrK

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
