### ISSUE TITLE
Blocks cannot be placed.

### ISSUE THREAD

**Issue by Kocimietka7192** [BG-Software-LLC/SuperiorSkyblock2#1520]
### Minecraft's Version

Pufferfish-41 1.19.2

### Plugin's Version

b943

### Describe the bug

When updating the plugin ( b7772) and the oneblock addon to b943 - The player can only teleport to the island, but cannot destroy or place anything

### To Reproduce

none

### Additional Information

I am hoping for guidance on how to resolve this.

**Comment by OmerBenGera** [comment]
What happens when your players place or break blocks?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs let me know
