### ISSUE TITLE
Island team offline issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1521]
### Minecraft's Version

1.19.2 pufferfish 

### Plugin's Version

b943

### Describe the bug

Since the latest update, on /is team, all offline player are "offline since 1s"

### To Reproduce

- update your plugin
- do a /is team <player>
- check for an offline player

**Comment by WarnDa** [comment]
Edit : doesn't happen to everyone, maybe a bug on my side if something failed, I'll have to test it on my test server after christmas.

**Comment by OmerBenGera** [comment]
It seems to work fine for me. However, this might be because their `last_time_updated` in the database is `-1` (due to an old bug that was patched already) - do you mind checking if that's the case?

**Comment by WarnDa** [comment]
> It seems to work fine for me. However, this might be because their `last_time_updated` in the database is `-1` (due to an old bug that was patched already) - do you mind checking if that's the case?

Yes it's this
![image](https://user-images.githubusercontent.com/31826333/209365898-8a653272-9890-4450-9540-d981501450f9.png)

**Comment by OmerBenGera** [comment]
> > It seems to work fine for me. However, this might be because their `last_time_updated` in the database is `-1` (due to an old bug that was patched already) - do you mind checking if that's the case?
> 
> Yes it's this ![image](https://user-images.githubusercontent.com/31826333/209365898-8a653272-9890-4450-9540-d981501450f9.png)

Yeah there's nothing really to do regarding this until they log in / modify the db manually?

**Comment by WarnDa** [comment]
A player is offline since 6hr but it still in "offline for 1s" in /is team, so there is still an issue.
but it's not for all players (only things I did since yesterday is a server restart)

**Comment by OmerBenGera** [comment]
> A player is offline since 6hr but it still in "offline for 1s" in /is team, so there is still an issue. but it's not for all players (only things I did since yesterday is a server restart)

So you say `-1` is written even for players that still play?
Do you know when it happens?

**Comment by WarnDa** [comment]
Yes, and it might be on server restart

**Comment by OmerBenGera** [comment]
I checked it again and this value is never set to -1.
This means that it cannot be set to -1 for new players, and this value is updated once players join or leave the server.

**Comment by WarnDa** [comment]
Seems fixed if player login, will reopen if it occurs again
