### ISSUE TITLE
Fishing mission incompatible with mcMMO

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/SuperiorSkyblock2#1525]
### Minecraft's Version

1.19.2 Paper version 210

### Plugin's Version

2022.9

### Describe the bug

Due to mcMMO's custom fishing skill (and fishing rewards), items reeled in by the player won't be counted in the Fishing mission it seems. 

### To Reproduce

Fish and reel in armor, swords, enderpearls, etc and it won't be counted.

### Additional Information

I've included this as a bug because of mcMMO's uber popularity. mcMMO is more common than not on Skyblock servers I think.

**Comment by OmerBenGera** [comment]
Ask them to fire Bukkit's event so they are compatible with every plugin.
In general, I dont add support for 3rd party plugins in missions.

**Comment by Elgorond** [comment]
> Ask them to fire Bukkit's event so they are compatible with every plugin. In general, I dont add support for 3rd party plugins in missions.

I was wrong about this, it works fine. I just didn't add the items to the missions file!

**Comment by OmerBenGera** [comment]
Ah, awesome
I am glad it woks for you
