### ISSUE TITLE
Island Missions not ordered ideally

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/SuperiorSkyblock2#1526]
### Minecraft's Version

1.19.2 Paper version 210

### Plugin's Version

2022.9

### Describe the bug

If you add more than 10+ missions the ordering in the menu will go 1, 10, 11, 12 13 in the first row... 14, 15, 2, 3, 4 in the 2nd, etc.

### To Reproduce

Have more than 10 missions of any category, and use this pattern in the menu:
`pattern:
  - '# # # # # # # # #'
  - '# # @ @ @ @ @ # #'
  - '# # @ @ @ @ @ # #'
  - '# # @ @ @ @ @ # #'
  - '# # # # # # # # #'`

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it fixes the issue.

**Comment by Elgorond** [comment]
> Use latest dev build, let me know if it fixes the issue. Also, did you configure weights correctly to your missions?

Oh I see. Didn't know about weights because default missions didn't have them. Though I tried dev build without weights and it still didn't sort by name like it should. Weights do work tho, my b

**Comment by OmerBenGera** [comment]
> > Use latest dev build, let me know if it fixes the issue. Also, did you configure weights correctly to your missions?
> 
> Oh I see. Didn't know about weights because default missions didn't have them. Though I tried dev build without weights and it still didn't sort by name like it should. Weights do work tho, my b

If the weights are the same (which is like that by default), they will be sorted out by their names. I will look into why it didn't sort them by their names - therefore I am keeping this opened for now.

**Comment by OmerBenGera** [comment]
I am closing this for now, it seems to be fine for me
If it happens for you, just use weights.
