### ISSUE TITLE
the island precious blocks are missing

### ISSUE THREAD

**Issue by DarkyCat** [BG-Software-LLC/SuperiorSkyblock2#1528]
### Minecraft's Version

![изображение](https://user-images.githubusercontent.com/50515714/210129433-c12b08a4-a13a-4fd0-8a8c-5fbe76173777.png)

### Plugin's Version

![изображение](https://user-images.githubusercontent.com/50515714/210129426-8e489701-0722-4f7f-b991-a59c4786693e.png)

### Describe the bug

![изображение](https://user-images.githubusercontent.com/50515714/210129469-de87a032-94c3-4edd-86c7-f6c578f38786.png)
updated the plugin to the latest build and the blocks that add up to one block disappeared. there were 40 diamond blocks, 30 gold blocks, 10 emerald blocks.

### To Reproduce

just update for 942 to 954.
![изображение](https://user-images.githubusercontent.com/50515714/210129522-bbf9ca2c-ecb0-44af-94cd-87bb6b5c1360.png)

**Comment by OmerBenGera** [comment]
Do you see these blocks in the DB?

**Comment by DarkyCat** [comment]
on the example of the top player's island

islands table
before update
![изображение](https://user-images.githubusercontent.com/50515714/210179416-cdffddf2-7728-44f5-8362-7644919aec71.png)
[{"id":"DIAMOND_BLOCK","amount":"356"},{"id":"BREWING_STAND","amount":"4"},{"id":"CHEST","amount":"196"},{"id":"GOLD_BLOCK","amount":"400"},{"id":"IRON_BLOCK","amount":"891"},{"id":"BEDROCK","amount":"1"},{"id":"COAL_BLOCK","amount":"2108"},{"id":"ENDER_CHEST","amount":"6"},{"id":"HOPPER","amount":"10"},{"id":"EMERALD_BLOCK","amount":"193"},{"id":"ENCHANTING_TABLE","amount":"1"}]

after update
![изображение](https://user-images.githubusercontent.com/50515714/210179433-79a8c24a-cd6b-4aa6-ae52-82d3ea0e1363.png)
[{"id":"DIAMOND_BLOCK","amount":"3"},{"id":"BREWING_STAND","amount":"4"},{"id":"CHEST","amount":"195"},{"id":"GOLD_BLOCK","amount":"3"},{"id":"IRON_BLOCK","amount":"908"},{"id":"BEDROCK","amount":"1"},{"id":"COAL_BLOCK","amount":"2131"},{"id":"ENDER_CHEST","amount":"6"},{"id":"HOPPER","amount":"10"},{"id":"EMERALD_BLOCK","amount":"2"},{"id":"ENCHANTING_TABLE","amount":"1"}]

**Comment by OmerBenGera** [comment]
Look for stacked blocks, not for block counts.
There's a table for them.

**Comment by Skizzles** [comment]
I have the same issue on my server. All stacked blocks data is lost from the database.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
I recommend to load a backup of your stacked blocks as they might be completely gone from the DB.
