### ISSUE TITLE
Island worth and level bug out

### ISSUE THREAD

**Issue by ItsRedd2** [BG-Software-LLC/SuperiorSkyblock2#1529]
### Minecraft's Version

1.19.2

### Plugin's Version

B954

### Describe the bug

![2023-01-01_17 17 45](https://user-images.githubusercontent.com/121762218/210178023-c37ff8f1-c73c-4b3c-bcdb-7c42194a788b.png)
![2023-01-01_17 17 24](https://user-images.githubusercontent.com/121762218/210178025-cea16291-b656-45da-8683-67f52c54c438.png)

I clearly have around 14k of island worth. But when I do /is recalc, or look at my island worth in any way, it shows that I'm in -2500. Aka, the island worth doesn't get calculated correctly.

### To Reproduce

I placed lots of blocks to make my islands worth higher and then I did /is recalc. to Make it show up. but instead my island worth dropped hugely.

**Comment by OmerBenGera** [comment]
This can happen when you have schematic offset enabled but you break blocks from your schematic.
If you don't think that's the case, your worth bonus might be too high - use `/is admin syncbonus` to reset it to the schematics' value.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
