### ISSUE TITLE
Crop limit and farmer tasks issue

### ISSUE THREAD

**Issue by unecRoe** [BG-Software-LLC/SuperiorSkyblock2#1531]
### Minecraft's Version

Minecraft: 1.8.9
Server: paper-1.8.8-445

### Plugin's Version

Latest stable version
2022.9 30/10/2022 18:00:14

### Describe the bug

Crop Limit Problem: I set the crop limit to 10 and planted 1 crop. I grew the crop with bone powder. I kept repeating and finally he said that there was a limit and more than 1 crop could not be planted.

Farmer Mission Issue: Except for pumpkin and cactus, none of the crops' missions work. Even though I set the item names according to https://helpch.at/docs/1.8.8/org/bukkit/Material.html it still didn't work. No way did it happen. I asked Discord for help and they told me to create a bug report.

### To Reproduce

Crop Limit Problem: I set the crop limit to 10 and planted 1 crop. I grew the crop with bone powder. I kept repeating and finally he said that there was a limit and more than 1 crop could not be planted.

Farmer Mission Issue: Except for pumpkin and cactus, none of the crops' missions work. Even though I set the item names according to https://helpch.at/docs/1.8.8/org/bukkit/Material.html it still didn't work. No way did it happen. I asked Discord for help and they told me to create a bug report.

**Comment by unecRoe** [comment]
I also used the latest dev build. It didn't work.

**Comment by OmerBenGera** [comment]
Farmer mission only works if you plan the plants and let them grow. Otherwise, it will not count towards your progress.
Anyways, open a new issue if you struggle with it.

About the crop limit - you set a limit to which block? There's no such thing as "crop limit".

**Comment by unecRoe** [comment]
Crop Limit= Block Limit I added carrots to it.

**Comment by OmerBenGera** [comment]
Run `/is admin show`, do you see your block limit there?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
