### ISSUE TITLE
Dispenser bypass the block-limit

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SuperiorSkyblock2#1532]
### Minecraft's Version

paper-1.19.3-353

### Plugin's Version

SuperiorSkyblock2-2022.9-b935

### Describe the bug

The block-limit works great, but as soon as a player use a dispenser on rails with minecart and hopper minecart the limit can be bypassed

### To Reproduce

place the max limit of minecart or minecart hopper
Then use a dispenser to place more

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
