### ISSUE TITLE
Required placeholder system in island missions not working

### ISSUE THREAD

**Issue by unecRoe** [BG-Software-LLC/SuperiorSkyblock2#1533]
### Minecraft's Version

paper-1.8.8-445

### Plugin's Version

Latest stable version
2022.9 30/10/2022 18:00:14
and
Dev Builds
#954 28/12/2022 09:23:24

### Describe the bug

I set the required island level to complete a quest, but the island quest does not work when the level is higher than necessary.

### To Reproduce

required-checks:
  - '%superior_island_level% > 250'
I am adding this task is not working.
It works after deleting it.

**Comment by OmerBenGera** [comment]
Please upload your entire mission you configured to pastebin and send it here.

**Comment by unecRoe** [comment]
pastebin.com/7wdSPKfX

**Comment by OmerBenGera** [comment]
As you can see here:
<https://wiki.bg-software.com/superiorskyblock/overview/placeholders/island-placeholders#superior_island_level>
This placeholder returns the level formatted - aka with commas and what not.
You need to use a placeholder that returns a raw input - `%superior_island_level_raw%` for example.
Let me know if it helps.

**Comment by OmerBenGera** [comment]
I am closing this for now
If you still need help with this let me know
