### ISSUE TITLE
a few issues about disband and member system

### ISSUE THREAD

**Issue by LyingYi** [BG-Software-LLC/SuperiorSkyblock2#1534]
### Minecraft's Version

1.8.9

### Plugin's Version

2022.9

### Describe the bug

1. missions wont reset and inventory wont clear after an admin disband a player's isband
2. i think its better to set a historical member limit or make the default member upgrade digits smaller since people will use alts to join the island, complete missions, transfer the money and leave the island

### To Reproduce

/is admin disband

**Comment by OmerBenGera** [comment]
1. `/is admin disband` works just fine for me - it clears inventories and missions.
2. You can request it on github as a feature if you want.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
