### ISSUE TITLE
stacked blocks disappear.

### ISSUE THREAD

**Issue by unecRoe** [BG-Software-LLC/SuperiorSkyblock2#1536]
### Minecraft's Version

paper-1.8.8-445

### Plugin's Version

Latest Dev Build is not working.
Release Version is working.

### Describe the bug

I'm placing a stacked block on the island. I turn the server off and on and the stacked blocks disappear.

### To Reproduce

Put the block on the island and stack it, turn the server off and on. There are no stacks.

**Comment by OmerBenGera** [comment]
Duplicate of #1528
