### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by yasin345353** [BG-Software-LLC/SuperiorSkyblock2#1537]
### Minecraft's Version

1.16.5 Purpur

### Plugin's Version

SuperiorSkyblock2-2022.9-b954

### Describe the bug

the server is randomly crashing at different times

### To Reproduce

[s.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10366993/s.txt)

### Additional Information

[s.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10366992/s.txt)

**Comment by OmerBenGera** [comment]
Check out latest dev build, it should fix the issue.

**Comment by yasin345353** [comment]
[s.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10367294/s.txt)
crashed again

**Comment by yasin345353** [comment]
The server keeps crashing even though I installed the latest version

**Comment by OmerBenGera** [comment]
Send me your entire session logs and not only part of them.
Upload them to pastebin and send them here, do not upload the files directly here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by yasin345353** [comment]
With the latest updates the problem is gone.
