### ISSUE TITLE
Slayer kills don't count if the mob dies from fire (flame enchant, fire aspect, etc)

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/SuperiorSkyblock2#1538]
### Minecraft's Version

Paper 1.19.2-210

### Plugin's Version

2022.9-b900

### Describe the bug

If you kill a mob and they die from fire damage (from flame bow or fire aspect sword) it won't count as a kill towards your Slayer Mission

### To Reproduce

Attack a mob and let it die with fire damage

**Comment by OmerBenGera** [comment]
Right, you must be the last person that hit the entity for it to register.

**Comment by Hero-Gate** [comment]
> Right, you must be the last person that hit the entity for it to register.

But isn't this kind of problematic? You can kill a wither, but then get unlucky if the killing was due to fire so it won't count. Players won't really understand this

**Comment by Elgorond** [comment]
> Right, you must be the last person that hit the entity for it to register.

> Right, you must be the last person that hit the entity for it to register.

But isn't this kind of problematic? You can kill a wither, but then get unlucky if the killing was due to fire so it won't count. Players won't really understand this

**Comment by OmerBenGera** [comment]
> > Right, you must be the last person that hit the entity for it to register.
> 
> But isn't this kind of problematic? You can kill a wither, but then get unlucky if the killing was due to fire so it won't count. Players won't really understand this

Thats how the game works. If I would want to change it, it would require me to track every damage a player dealt to any mob and do everything on my own. I dont want this - too complicated and will lead to many bugs, memory usage...
