### ISSUE TITLE
Invincible hostile mobs bug

### ISSUE THREAD

**Issue by Elgorond** [BG-Software-LLC/SuperiorSkyblock2#1539]
### Minecraft's Version

Paper 1.19.2-210

### Plugin's Version

2022.9-b900

### Describe the bug

Sometimes (randomly it seems) a hostile mob on an island will be invincible and not take damage. I've noticed what fixes it is if all the players on the island log-out then return to it. Then it can take damage. I thought it might be the island thinking they are guests, but they get no deny-message when trying to kill it. This can happen to a single mob or one that is stacked (with WildStacker), it doesn't matter.

### To Reproduce

Unsure yet what causes it.

**Comment by OmerBenGera** [comment]
It might be relates to WS but not SSB.
Update WS, let me know if it still happens

**Comment by Elgorond** [comment]
> It might be relates to WS but not SSB. Update WS, let me know if it still happens

I don't think the bug has happened again (yet) but updating has led to a new bug where WildStacker is overriding MythicMobs mob drops. I've set up a MythicMob to drop gold and execute a command, but now it doesn't do that anymore, it's just dropping rotten flesh (since it's technically a zombie).

**Comment by OmerBenGera** [comment]
Closing this for now
