### ISSUE TITLE
island top page unresponsive

### ISSUE THREAD

**Issue by KasaiSora** [BG-Software-LLC/SuperiorSkyblock2#1541]
### Minecraft's Version

1.18.2

### Plugin's Version

2022.9-b957

### Describe the bug

All the buttons on the island top page are not responsive. It is fixed on 'sort by worth' and no one is able to change it. When I make a new server with the same plugin version, the problem is not there. But with my current server (around 100 players), it does not work.

### To Reproduce

I don't exactly know how to reproduce the problem. When my server was smaller, the problem wasn't there. It only started after hitting about 50+ players. So I guess having many players registered and playing is a way to reproduce it

**Comment by OmerBenGera** [comment]
What do you mean by "not responsive"? What are you clicking exactly? What do you expect from the button to occur, etc.
You must provide more information about the issue you're having.

**Comment by KyleStance** [comment]
> What do you mean by "not responsive"? What are you clicking exactly? What do you expect from the button to occur, etc. You must provide more information about the issue you're having.

Don't update top data by categories. Like clicking by rating, by money don't print data.

**Comment by OmerBenGera** [comment]
@KasaiSora @KyleStance Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue persists let me know
