### ISSUE TITLE
EcoEnchants Replenish doesn't count with the /is missions

### ISSUE THREAD

**Issue by iSeitan** [BG-Software-LLC/SuperiorSkyblock2#1544]
### Minecraft's Version

paper-1.19.3-370

### Plugin's Version

SuperiorSkyblock2-2022.9-b956
EcoEnchants v9.15.0

### Describe the bug

I've got a farmer mission wich can be completed by making wheat grow
If a player has replanted a wheat seed with the enchant replenish, when the wheat has grown it wont be counted in the is mission

Would that be on superiorskyblock side to detect this enchant replant method?

### To Reproduce

plant with replenish (the ecoenchants plugin is opensourced)

**Comment by OmerBenGera** [comment]
They should fire the BlockGrowEvent so other plugins can know about the block actually being grown.
In general I don't add direct support for other plugins in missions anyways.
Closing this
