### ISSUE TITLE
Cobble generator lowering /is level

### ISSUE THREAD

**Issue by Hero-Gate** [BG-Software-LLC/SuperiorSkyblock2#1546]
### Minecraft's Version

Paper 1.19.2-210

### Plugin's Version

2022.9-b900

### Describe the bug

Have a player make a cobble generator, and use it. Every block mined will lower their Island Level.

### To Reproduce

See above

**Comment by OmerBenGera** [comment]
Everytime a block is mined from the generator it will make the level down, and when it is generated it will go up again.

**Comment by Hero-Gate** [comment]
It seems like block-break lowers the level, but then the new block formed also lowers it?
[https://www.youtube.com/watch?v=boJl01DE6Kg&ab_channel=HeroGateNetwork](https://www.youtube.com/watch?v=boJl01DE6Kg&ab_channel=HeroGateNetwork)

**Comment by Hero-Gate** [comment]
> /is admin debug block_place

`[04:16:06] [Server thread/INFO]: Elgorond issued server command: /is admin debug block_break
[04:16:12] [Server thread/INFO]: Elgorond issued server command: /i diamondpickaxe 1
[04:16:20] [Server thread/INFO]: Elgorond issued server command: /is admin debug block_place
[04:16:24] [Server thread/INFO]: [SuperiorSkyblock2] [DefaultIslandBlocksTrackerAlgorithm] ::untrackBlock {Elgorond} {COBBLESTONE:0} {1}
[04:16:25] [Server thread/INFO]: [SuperiorSkyblock2] [DefaultIslandBlocksTrackerAlgorithm] ::untrackBlock {Elgorond} {COBBLESTONE:0} {1}
`

**Comment by OmerBenGera** [comment]
> : /is admin debug block_place

Looks like it's running twice.
Run `/is admin debug show_stacktrace` (make sure the block_place and block_break are also toggled) and break a generator block. Send me the output again (it will show like errors are in console)

**Comment by Hero-Gate** [comment]
> /is admin debug show_stacktrace

[https://pastebin.com/CJAD8SxZ](https://pastebin.com/CJAD8SxZ)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Elgorond** [comment]
> Fixed in latest dev build

For some reason mining cobblestone from the generator is still lowering the is level (but then /is recalc fixes it). Mining any other block from the generator does not have this issue. Here's more debug messages if that helps: [https://pastebin.com/2g9e1Gtq](https://pastebin.com/2g9e1Gtq)

**Comment by OmerBenGera** [comment]
Enable BLOCK_BREAK and SHOW_STACKTRACE only, then break cobblestone and send me the results.

**Comment by Elgorond** [comment]
> Enable BLOCK_BREAK and SHOW_STACKTRACE only, then break cobblestone and send me the console logs.

[https://pastebin.com/vKwGE0mD](https://pastebin.com/vKwGE0mD)

**Comment by Elgorond** [comment]
Looks fixed, ty
