### ISSUE TITLE
is toggle blocks isn't saving after restart

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1547]
### Minecraft's Version

1.19.2

### Plugin's Version

latest dev build b957

### Describe the bug

after server restart toggle blocks reverts to off state

### To Reproduce

toggle stacking blocks on and restart the server
after restart it's off

/is toggle blocks

**Comment by OmerBenGera** [comment]
Right, this is not something that is saved to DB.
You are more than welcome to make a feature request.
