### ISSUE TITLE
Bug occurs when deleting island

### ISSUE THREAD

**Issue by yasin345353** [BG-Software-LLC/SuperiorSkyblock2#1548]
### Minecraft's Version

1.16.5

### Plugin's Version

SuperiorSkyblock2-2022.9-b957

### Describe the bug

When I try to delete the island, the message "deleted" appears in the chat, it is deleted, but it does not send from the deleted island, it gives such an error in the console. What is the solution?

### To Reproduce

[hata.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10404186/hata.txt)

**Comment by OmerBenGera** [comment]
Send me your entire session logs  by uploading them to pastebin and send a link to it here.

**Comment by yasin345353** [comment]
https://hastebin.com/osubokulix.sql

**Comment by OmerBenGera** [comment]
You have in your DB a player with uuid 0 which doesn't make a lot of sense.
What is that player? Do you mind looking in the DB and find the player record for this player, then send a screenshot of it here?

If you don't know how to do that, you can just upload your DB to a third-party service and send a link to it here and I will look into it myself.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue persists let me know
