### ISSUE TITLE
ItemsMissions taking items from inv when its completed

### ISSUE THREAD

**Issue by jara155** [BG-Software-LLC/SuperiorSkyblock2#1550]
### Minecraft's Version

git-Purpur-1774 (MC: 1.19.2)*

### Plugin's Version

2022.9-b960

### Describe the bug

When its completed it remove items from inventory

### To Reproduce

Dont take items from inventory and complete mission

**Comment by OmerBenGera** [comment]
The items missions will take the items from the inventory, of course.
That's intended, not a bug.
