### ISSUE TITLE
Entity limits are not working at all

### ISSUE THREAD

**Issue by airoons** [BG-Software-LLC/SuperiorSkyblock2#1552]
### Minecraft's Version

1.17.1

### Plugin's Version

A dev build, I have modified it with stuff, but that isn't relevant

### Describe the bug

https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/listener/EntityTrackingListener.java#L46

Please check that line, `BukkitEntities.canHaveLimit(entity.getType())` should be inverted.

### To Reproduce

See above, sorry for not exactly following your issue template

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, thanks for reporting :)
