### ISSUE TITLE
Ore generator for normal islands can't be edited from the config file.

### ISSUE THREAD

**Issue by EditChris** [BG-Software-LLC/SuperiorSkyblock2#1553]
### Minecraft's Version

Paper Spigot for 1.19.3, Build 376.

### Plugin's Version

2022.9-b960, dev build

### Describe the bug

I'm trying to configure the ore generators of my worlds. To test its functionality, I have set these values on the config.yml file:

generator:
    normal:
    - GREEN_CONCRETE:70
    - WHITE_STAINED_GLASS:30
    nether:
    - GOLD_BLOCK:40
    - RED_SAND:60
    the_end:
    - GLASS:50
    - REDSTONE_ORE:50

When I load the server to try them, the Nether and End generators work perfectly generating their respective blocks, but when I try the same thing in the overworld, the plugin doesn't seem to recognize what I wrote on the config file, instead forcing the default values of 95% of Stone and 5% of Coal Ore:

![Rates](https://user-images.githubusercontent.com/48211020/212549451-5b90e092-995e-4b06-a97e-22af7a2e1c27.png)

The only thing that allows me to change that list is using the in-game commands, but that method is not ideal, because it's not easy to edit as it saves the values just on the database, and you have to write every single entry of the list one by one.

### To Reproduce

1. Open "config.yml" and go to "generator:"
2. Try to change anything on normal. Percentages, blocks, etc.
3. Reload the server with those values.
4. Perform: /is admin show [your name]

**Comment by OmerBenGera** [comment]
Do you have an upgrade that changes generator rates?

**Comment by OmerBenGera** [comment]
Do you have an upgrade that changes generator rates?

**Comment by EditChris** [comment]
...It's amazing how blind I am. Ok, I found the upgrades config file on the modules folder. I deleted everything there regarding generator upgrades and now everything works as I needed. I'm really sorry for wasting your time, you can close this.

**Comment by OmerBenGera** [comment]
All's good, I am glad it works now :)
