### ISSUE TITLE
Island calculation not working correctly

### ISSUE THREAD

**Issue by SinonCute** [BG-Software-LLC/SuperiorSkyblock2#1554]
### Minecraft's Version

1.16.5 - Paper

### Plugin's Version

SuperiorSkyblock2-2022.9-b960

### Describe the bug

Island calculation not count stacked block for unload chunk and some old island will not recalculate just get old result to new one but database stacked block column saved wrong block counts make entire system of worth and level going wrong.

### To Reproduce

RoseStacker
1. Place some stacked block and then go outside Island make the chunk unload by server
2. Recalculation 
3. Result will just count 1 block of stacked block instead all of it.

### Additional Information

RoseStacker don't like unloaded chunk to get information.

**Comment by OmerBenGera** [comment]
Contact RoseStacker regarding this.
If they dont support it then how do you expect it to work?
