### ISSUE TITLE
the bank in the panel does not show how much money I have

### ISSUE THREAD

**Issue by ArianPL** [BG-Software-LLC/SuperiorSkyblock2#1562]
### Minecraft's Version

1.8

### Plugin's Version

2022.9

### Describe the bug

the bank in the panel does not show how much money I have 
the bank in the panel does not show how much money I have, it only shows $%superior_island_bank_format%

### To Reproduce

Type is bank and hover over a piece of paper

### Additional Information

![bez](https://user-images.githubusercontent.com/32176853/213020261-e696c225-e6f2-486e-a2fc-b0d363b6e6e1.png)

**Comment by OmerBenGera** [comment]
Install PAPI or use MVDW placeholder if you have it installed.
