### ISSUE TITLE
Player rank issue

### ISSUE THREAD

**Issue by George-Rowland** [BG-Software-LLC/SuperiorSkyblock2#1565]
### Minecraft's Version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### Plugin's Version

[12:43:30 INFO]: SuperiorSkyblock2 version 2022.9-b960
[12:43:30 INFO]: Feature packed Skyblock core.
[12:43:30 INFO]: Website: https://bg-software.com/
[12:43:30 INFO]: Author: Ome_R

### Describe the bug

Players are randomly being "assigned leader" in their island however after this happens they can no longer interact on the island / be edited by the official island leader as it says "they are not apart of this island" (view videos)

https://media.discordapp.net/attachments/1064423438816653352/1064890169947328532/Minecraft__1.19.2_-_Multiplayer_3rd-party_Server_2023-01-15_23-52-45.mp4

https://youtu.be/0YdSCi-tjaw

### To Reproduce

Happens randomly to players who are grouped together

### Additional Information

Config: https://hastebin.com/ewemegonuq.yaml

**Comment by OmerBenGera** [comment]
I don't understand what the issue is from the video
They do not have an island.

**Comment by George-Rowland** [comment]
https://media.discordapp.net/attachments/1064423438816653352/1064890169947328532/Minecraft__1.19.2_-_Multiplayer_3rd-party_Server_2023-01-15_23-52-45.mp4

Player is randomly assigned leader but "not a part of the island"

**Comment by George-Rowland** [comment]
https://youtu.be/0YdSCi-tjaw

Players data was randomly cleared, they did have an island before

**Comment by OmerBenGera** [comment]
> https://youtu.be/0YdSCi-tjaw
> 
> Players data was randomly cleared, they did have an island before

Data is not cleared randomly.
Maybe they had their UUID changed?
Find the cause of the bug.

**Comment by George-Rowland** [comment]
> > https://youtu.be/0YdSCi-tjaw
> > Players data was randomly cleared, they did have an island before
> 
> Data is not cleared randomly. Maybe they had their UUID changed? Find the cause of the bug.

I will look into this. But given all their data stayed other than their island status suggests to me their UUID has not changed.

As for the other video any update?

**Comment by OmerBenGera** [comment]
> > > https://youtu.be/0YdSCi-tjaw
> > > Players data was randomly cleared, they did have an island before
> > 
> > 
> > Data is not cleared randomly. Maybe they had their UUID changed? Find the cause of the bug.
> 
> I will look into this. But given all their data stayed other than their island status suggests to me their UUID has not changed.
> 
> As for the other video any update?

It sounds like their UUID was changed and this what caused the issue to occur.
Do you have a plugin that changes UUIDs (premium login plugins, geyser, etc)

**Comment by George-Rowland** [comment]
Found that this issue is caused via FastLogin and links to an outstanding bug report you have open

**Comment by OmerBenGera** [comment]
> Found that this issue is caused via FastLogin and links to an outstanding bug report you have open

Yeah, as I said - a plugin changes UUIDs.
This is already known, you can find the original issue here: #1513
