### ISSUE TITLE
Island bug

### ISSUE THREAD

**Issue by lucashw** [BG-Software-LLC/SuperiorSkyblock2#1567]
### Minecraft's Version

Paper 1.15.2

(paper-1.15.2-391.jar)

### Plugin's Version

1.4.5

### Describe the bug

when i create island, i have this island bug

### To Reproduce

make an island

**Comment by lucashw** [comment]
![image](https://user-images.githubusercontent.com/36309464/214421351-f2153f22-ea1c-4fcc-bb95-811044079861.png)

**Comment by Tptuaazn** [comment]
Lol version 1.4.5 update your ss2 plugin.

**Comment by OmerBenGera** [comment]
Update the plugin and don't use versions that are over a year ago (both spigot and the plugin)
