### ISSUE TITLE
Issues with ShopGUIPlus?

### ISSUE THREAD

**Issue by JShin39** [BG-Software-LLC/SuperiorSkyblock2#1568]
### Minecraft's Version

This server is running Paper version git-Paper-384 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 18fabc0)

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b964
Feature packed Skyblock core.
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

I'm not sure if this is a bug from SuperiorSkyblock or ShopGUIPlus, but ShopGUIPlus fails to load items from MMOItems when I install/run SuperiorSkyblock. Without SuperiorSkyblock, ShopGUIPlus loads everything perfectly.

### To Reproduce

Starting a 1.19.3 paper server with the latest version of plugins: MMOItems, ShopGUIPlus, and SuperiorSkyblock2. 

### Additional Information

Start-up log (with no SuperiorSkyblock; ShopGUIPlus hooks onto MMOItems) - https://pastebin.com/gCzvJbq7

Start-up log (with SuperiorSkyblock installed; ShopGUIPlus doesn't hook onto MMOItems) - https://pastebin.com/qkG6FewG

**Comment by OmerBenGera** [comment]
In which line do you see that SGP hooks into MMOItems?

**Comment by JShin39** [comment]
https://pastebin.com/gCzvJbq7; Line 707

**Comment by OmerBenGera** [comment]
Have you tried contacting ShopGUIPlus regarding this..?

**Comment by JShin39** [comment]
Yes, I have, but their support is nonexistent lmao. And I wasn't sure if this was a bug from this plugin or ShopGUIPlus, so I thought I'd give it a shot here.

**Comment by OmerBenGera** [comment]
I think this is a bug of ShopGUIPlus
SSB doesn't interact with MMOItems in any way and I can't think about a reason why it would interface with SGP.
