### ISSUE TITLE
Island Settings

### ISSUE THREAD

**Issue by SkyWaves123** [BG-Software-LLC/SuperiorSkyblock2#1569]
### Minecraft's Version

This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b964 (dev version)

### Describe the bug

When i try to acces island settings from control panel , the menu doesnt open. i need to click for about 3-4 times for it to open.

### To Reproduce

1. do /is cp
2. click island settings
3. if it doesnt open click a few more times

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue myself
Try doing so on a server with only SSB installed and default menu files

**Comment by SkyWaves123** [comment]
i have no ideea how to replicate this. it just happenes once in a while

**Comment by OmerBenGera** [comment]
I need you to find the cause of the issue, or at least take a video of the issue

**Comment by SkyWaves123** [comment]
Next time this happenes I will make a video of it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SkyWaves123** [comment]
The issue started again. This is what happenes:
https://youtu.be/EgQmo1MbS7k

**Comment by OmerBenGera** [comment]
> Reference in ne

Try replicating it on a server with only SSB installed.
Let me know how to replicate the issue so I can get it fixed.

**Comment by SkyWaves123** [comment]
i tried replicating it on a new server and it seems like i cant replicate it. It seems fine on a new server

**Comment by OmerBenGera** [comment]
Add plugins one by one from the server that it doesn't work on and find the plugin that conflicts with the plugin.

**Comment by SkyWaves123** [comment]
There are a lot of plugins but I will try to do it if I have time.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
