### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by Aldor2-Projesi** [BG-Software-LLC/SuperiorSkyblock2#1571]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/111376484/215261002-bfc38022-5ae0-4af0-9c5a-16161be372bc.png)

### Plugin's Version

![image](https://user-images.githubusercontent.com/111376484/215261465-7fcaf8c8-9f72-4e42-851d-a96bc33e7451.png)

### Describe the bug

**When I click on the space in the menu, it transfers it to the task page, and even though I removed the task there, the tasks seem to have shifted.**
![image](https://user-images.githubusercontent.com/111376484/215261260-3848f2e6-bd5b-4a70-b3a4-e3adfa359b76.png)
![image](https://user-images.githubusercontent.com/111376484/215261271-1bd50bb5-439f-4df2-8f65-d872d3452b04.png)
**I am leaving the contents of the missions.yml file in the attachment.**

### To Reproduce

**I don't understand exactly what it is, so I'm leaving this blank.**

### Additional Information

[PasteBin](https://pastebin.pl/view/3617b423)

**Comment by OmerBenGera** [comment]
Upload your missions file (the categories one) to pastebin and send a link to it here
The link you provided does not work

**Comment by Aldor2-Projesi** [comment]
```
**######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

title: '&9          Görevler Menüsü'
previous-menu: true

pattern:
  - '$ $ $ $ $ $ $ $ $'
  - '$ * * * * * * * $'
  - '$ * # @ * % ^ * $'
  - '$ * * * * * * * $'
  - '$ $ $ $ $ $ $ $ $'

items:
  '$':
    type: STAINED_GLASS_PANE
    data: 11
    name: '&4&lMining&f&lCraft.net'
  '*':
    type: STAINED_GLASS_PANE
    data: 8
    name: '&4&lMining&f&lCraft'
  '#':
    type: DIAMOND_PICKAXE
    name: '&e✦ &6Madenci Görevleri &e✦'
    lore:
      - ''
      - '&6» &eTaş kırarak para kazan!'
      - ''
    flags:
      - HIDE_ATTRIBUTES
  '@':
    type: SKULL_ITEM
    data: 2
    name: '&e✦ &6Avcı Görevleri &e✦'
    lore:
      - ''
      - '&6» &eZombileri öldür parayı kap!'
      - ''
  '%':
    type: WHEAT
    name: '&e✦ &6Çiftçi Görevleri &e✦'
    lore:
      - ''
      - '&6» &eEk / Biç para kazan!'
      - ''
  '^':
    type: FISHING_ROD
    name: '&e✦ &6Balıkçı Görevleri &e✦'
    lore:
      - ''
      - '&6» &eBalık tut pazarda okut!'
      - ''

sounds:
  '#':
    type: BLOCK_CHEST_OPEN
    volume: 0.8
    pitch: 1
  '@':
    type: BLOCK_CHEST_OPEN
    volume: 0.8
    pitch: 1
  '%':
    type: BLOCK_CHEST_OPEN
    volume: 0.8
    pitch: 1
  '^':
    type: BLOCK_CHEST_OPEN
    volume: 0.8
    pitch: 1
  '&':
    type: BLOCK_CHEST_OPEN
    volume: 0.8
    pitch: 1**
```

**Comment by OmerBenGera** [comment]
> ```
> **######################################################
> ##                                                  ##
> ##                SuperiorSkyblock 2                ##
> ##                Developed by Ome_R                ##
> ##                                                  ##
> ######################################################
> 
> title: '&9          Görevler Menüsü'
> previous-menu: true
> 
> pattern:
>   - '$ $ $ $ $ $ $ $ $'
>   - '$ * * * * * * * $'
>   - '$ * # @ * % ^ * $'
>   - '$ * * * * * * * $'
>   - '$ $ $ $ $ $ $ $ $'
> 
> items:
>   '$':
>     type: STAINED_GLASS_PANE
>     data: 11
>     name: '&4&lMining&f&lCraft.net'
>   '*':
>     type: STAINED_GLASS_PANE
>     data: 8
>     name: '&4&lMining&f&lCraft'
>   '#':
>     type: DIAMOND_PICKAXE
>     name: '&e✦ &6Madenci Görevleri &e✦'
>     lore:
>       - ''
>       - '&6» &eTaş kırarak para kazan!'
>       - ''
>     flags:
>       - HIDE_ATTRIBUTES
>   '@':
>     type: SKULL_ITEM
>     data: 2
>     name: '&e✦ &6Avcı Görevleri &e✦'
>     lore:
>       - ''
>       - '&6» &eZombileri öldür parayı kap!'
>       - ''
>   '%':
>     type: WHEAT
>     name: '&e✦ &6Çiftçi Görevleri &e✦'
>     lore:
>       - ''
>       - '&6» &eEk / Biç para kazan!'
>       - ''
>   '^':
>     type: FISHING_ROD
>     name: '&e✦ &6Balıkçı Görevleri &e✦'
>     lore:
>       - ''
>       - '&6» &eBalık tut pazarda okut!'
>       - ''
> 
> sounds:
>   '#':
>     type: BLOCK_CHEST_OPEN
>     volume: 0.8
>     pitch: 1
>   '@':
>     type: BLOCK_CHEST_OPEN
>     volume: 0.8
>     pitch: 1
>   '%':
>     type: BLOCK_CHEST_OPEN
>     volume: 0.8
>     pitch: 1
>   '^':
>     type: BLOCK_CHEST_OPEN
>     volume: 0.8
>     pitch: 1
>   '&':
>     type: BLOCK_CHEST_OPEN
>     volume: 0.8
>     pitch: 1**
> ```

You have * configured to have a name.
Remove it from the items list and it should be fine.

**Comment by Aldor2-Projesi** [comment]
I did not understand what you said, but I removed it correctly, the problem still persists.

**Comment by OmerBenGera** [comment]
> I did not understand what you said, but I removed it correctly, the problem still persists.

Remove the * symbol from the items section and restart, you won't see it there anymore
The plugin doesn't magically add items to your menu - make sure they are configured correctly.
Closing this for now

**Comment by OmerBenGera** [comment]
Also, make sure you have set the slot of the categories correctly in the missions config file
