### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by WinTone01** [BG-Software-LLC/SuperiorSkyblock2#1573]
### Minecraft's Version

1.19.2 paper

### Plugin's Version

![image](https://user-images.githubusercontent.com/103455948/215267068-2d7104c0-5f28-499f-940e-f061dfc4f65c.png)

### Describe the bug

I am getting the following errors on my server, please help with the solution.

### To Reproduce

I don't understand this part

### Additional Information

https://pastebin.com/embed_js/cTBTt9pD

**Comment by OmerBenGera** [comment]
Remove the ".5" from your spawn location, the plugin will automatically make it centered.
