### ISSUE TITLE
island formation within the island of another island

### ISSUE THREAD

**Issue by yasin345353** [BG-Software-LLC/SuperiorSkyblock2#1575]
### Minecraft's Version

1.16.5 purpur

### Plugin's Version

SuperiorSkyblock2-2022.9-b964

### Describe the bug

I created a new schematic and used it as a replacement for the old default island design, but when players create a new island they spawn inside the old default island, sorry if I didn't explain properly, my native language is not english

![image](https://user-images.githubusercontent.com/61907148/215344938-0305cf07-f055-4d6a-9833-beb8dc3ee87c.png)

### To Reproduce

I created a new schematic and used it as a replacement for the old default island design, but when players create a new island they spawn inside the old default island, sorry if I didn't explain properly, my native language is not english

### Additional Information

https://pastebin.mozilla.org/ufuWGvE4

**Comment by OmerBenGera** [comment]
Islands are not created where old ones did
It looks like you didn't reset the world at some point causing this behavior to occur
Nothing to be done regarding this, make sure you reset your world properly between sessions.
