### ISSUE TITLE
when i want to create an island i have an error 

### ISSUE THREAD

**Issue by RudyDinis** [BG-Software-LLC/SuperiorSkyblock2#1578]
### Minecraft's Version

mohist-1.12.2-320

### Plugin's Version

SuperiorSkyblock2-2022.9-b967

### Describe the bug

![image](https://user-images.githubusercontent.com/60667200/215890185-1fa53d33-5f34-4732-9a8c-8d3dfd121087.png)
![image](https://user-images.githubusercontent.com/60667200/215890282-1c9e0018-6ae4-40fd-9e9a-98d17fe0323d.png)

when i do : /is create test

### To Reproduce

/is create test

**Comment by OmerBenGera** [comment]
Mohist is not supported
