### ISSUE TITLE
Redstone doesnt work for new islands

### ISSUE THREAD

**Issue by LO383krystianch** [BG-Software-LLC/SuperiorSkyblock2#1579]
### Minecraft's Version

1.19.2 pufferfish

### Plugin's Version

#967

### Describe the bug

Redstone doesnt work on new island, on old island works 

### To Reproduce

Create island as player and try do something with redstone

**Comment by DarkyCat** [comment]
+1

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
