### ISSUE TITLE
Mobs despawning

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1582]
### Minecraft's Version

Purpur 1.19.3

### Plugin's Version

  [Thu 21:06:28 INFO ] SuperiorSkyblock2 version 2022.9
  [Thu 21:06:28 INFO ] Feature packed Skyblock core.
  [Thu 21:06:28 INFO ] Website: https://bg-software.com/
  [Thu 21:06:28 INFO ] Author: Ome_R

### Describe the bug

Mobs despawn, I have two cases:
An old case where dolphins on a player's island kept disappearing whenever you unloaded the island. Dolphin is named, was not killed, did not die, and was kept alive for multiple hours. The moment the player went to spawn and back, dolphin is gone. And the dolphin is name tagged.

Second case just happened, multiple piglins were named in the nether in cages, for trading, and all of a sudden they dissapeared. I was told the island was not unloaded, and last time I checked myself an hour ago the piglins were there

### To Reproduce

Unsure

**Comment by OmerBenGera** [comment]
SSB does not kill or remove any mobs.
Try it on a server with only SSB installed, check if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by DuneSciFye** [comment]
It's still happening, I haven't tested with just ss2

**Comment by OmerBenGera** [comment]
> It's still happening, I haven't tested with just ss2

Then do it and report back.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
