### ISSUE TITLE
JetMinions integration not fully

### ISSUE THREAD

**Issue by DarkyCat** [BG-Software-LLC/SuperiorSkyblock2#1584]
### Minecraft's Version

1.19.2

### Plugin's Version

![изображение](https://user-images.githubusercontent.com/50515714/216664239-201a3d41-9caf-4f69-b4db-96922ac8583a.png)

### Describe the bug

When a player places a minion on an island, they will not despawn if the player leaves the island. Also, players cannot interact with other people's minions on the same island or delete them if the player left the island. In this case, if the player left the island, the limit of his minions is not updated.
![изображение](https://user-images.githubusercontent.com/50515714/216664639-d54580ec-5b04-4038-9ddf-f961c670c9b7.png)
A screenshot of the player, he left the island, but his minions were not reset and remained on the island, no one can delete them or interact with them.

### To Reproduce

install jetminions in your server

**Comment by OmerBenGera** [comment]
When a player leaves the island but the island should not disband (if he was a member of the island, for example), there's no reason for his minions to get removed - he should have removed them by himself.
However, if the island is disbanding then his minions should be removed, and I will fix it.

**Comment by DarkyCat** [comment]
> When a player leaves the island but the island should not disband (if he was a member of the island, for example), there's no reason for his minions to get removed - he should have removed them by himself. However, if the island is disbanding then his minions should be removed, and I will fix it.

It is possible to implement that the owner of the island could remove other people's minions.

**Comment by OmerBenGera** [comment]
> > When a player leaves the island but the island should not disband (if he was a member of the island, for example), there's no reason for his minions to get removed - he should have removed them by himself. However, if the island is disbanding then his minions should be removed, and I will fix it.
> 
> It is possible to implement that the owner of the island could remove other people's minions.

I talked with Jets regarding this, he will fix the issue on disbands.
About the other feature, talk with Jet regarding this, as this is not a feature SSB should implement.

**Comment by OmerBenGera** [comment]
I am closing this as I am pretty sure he added it.
If not, contact him for further support :)
