### ISSUE TITLE
API not working due to `SuperiorSkyblockAPI.plugin` being null

### ISSUE THREAD

**Issue by wxipwastaken** [BG-Software-LLC/SuperiorSkyblock2#1587]
### Minecraft's Version

Current: git-Purpur-1895 (MC: 1.19.3)*
* You are 13 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b969
Feature packed Skyblock core.
Website: https://bg-software.com/
Author: Ome_R

### Describe the bug

It throws `java.lang.NullPointerException: Cannot invoke "com.bgsoftware.superiorskyblock.api.SuperiorSkyblock.getPlayers()" because "com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.plugin" is null` error when trying to get superior player. The error is happening on this line:
```java
final SuperiorPlayer superiorPlayer = SuperiorSkyblockAPI.getPlayers().getSuperiorPlayer(player);
```

### To Reproduce

Make a SuperiorSkyblock2 API dependant plugin and try to get superior player through it (`SuperiorSkyblockAPI.getPlayers().getSuperiorPlayer(...)`).

### Additional Information

I tried it with Paper, didn't work either

**Comment by OmerBenGera** [comment]
Dont shade the APi into your jar.
