### ISSUE TITLE
SSB Proxy Bridge Redis Island Data Is Deleted Every Time Server Is Shutdown

### ISSUE THREAD

**Issue by PnterNN** [BG-Software-LLC/SuperiorSkyblock2#1588]
### Minecraft's Version

1.19.2

### Plugin's Version

#967

### Describe the bug

Island datas of players are saving successfully however, the MySQL database does not stores that which island is in which server. So, if I restart the server, players gets 'It seems like this island has no safe blocks please contact a staff member' error when they tried to going their island. There's no problem until I restart the server.

### To Reproduce

shutdown server

### Additional Information

i bought ssbproxy from patreon and i read entire wiki carefully but i couldn't find anything about this issue

**Comment by OmerBenGera** [comment]
Issues related SSBProxyBridge should be reported on the discord server.
Also, ita not currently stable and you might experience such issues.
https://discord.gg/UcQ3Uerz9N
