### ISSUE TITLE
count placeholder issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1589]
### Minecraft's Version

paper v302 1.19.2

### Plugin's Version

b969

### Describe the bug

When a block get a _ inside his ID, it doesn't parse using superior_island_count

### To Reproduce

https://youtu.be/PyJasfbPyPE

**Comment by OmerBenGera** [comment]
This works fine for me: `/papi parse me %superior_island_count_diamond_block%`

**Comment by WarnDa** [comment]
Edit : 
The block wasn't in block value so didn't count.

but there is an issue on end_portal_frame counting, it doesn't count well when we place the eye in it : 
https://youtu.be/2OxE_6PTEjk

**Comment by OmerBenGera** [comment]
end portal frames with eyes are considered different blocks

**Comment by WarnDa** [comment]
it's which block ? Because it detects some portal with eyes as a normal portal, but not all

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
