### ISSUE TITLE
Cant hit mobs

### ISSUE THREAD

**Issue by Benntehboss** [BG-Software-LLC/SuperiorSkyblock2#1591]
### Minecraft's Version

1.8.9
[server.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10714268/server.zip)

### Plugin's Version

2022.9

### Describe the bug

players can hit the monsters 2-3 times with swords/tools and then they become immune to anything

### To Reproduce

spawning mobs via /spawnmob, spawners and natural

**Comment by Benntehboss** [comment]
i can see after some more looking, its in wildstacker, i tryed 2022.6-b417 and the 2022.6 and both does the same

**Comment by OmerBenGera** [comment]
How is it related to SuperiorSkyblock?
Also, update it to latest dev build.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
