### ISSUE TITLE
Skin providers don't work.

### ISSUE THREAD

**Issue by Dot0420** [BG-Software-LLC/SuperiorSkyblock2#1592]
### Minecraft's Version

Server : Paper-1618

### Plugin's Version

SSB 2022.9-b972

### Describe the bug

When I put the ChangeSkin plugin in, it doesn't work with the error popping up.
and I put SkinsRestorer, no error pops up and it doesn't work.

Steve head in the picture below has the original skin.

### To Reproduce

Put plugins foloder ssb and ChangeSkin or SkinsRestorer and run the server.

### Additional Information

https://pastebin.com/7UfRMz9n
![image](https://user-images.githubusercontent.com/75387229/218318155-ace2870b-26f9-4395-bb82-f783bb432231.png)

**Comment by OmerBenGera** [comment]
Send me a link to the plugin that you use.

**Comment by Dot0420** [comment]
https://www.spigotmc.org/resources/changeskin.21469/
https://www.spigotmc.org/resources/skinsrestorer.2124/

I've tested both of the above two plugins and it still doesn't work.

**Comment by OmerBenGera** [comment]
Hey, I fixed the error you saw in console.
If you want to use ChangeSkin, you must use ChangeSkin v3.1 (not the one listed on Spigot)
