### ISSUE TITLE
is top and is levels not working

### ISSUE THREAD

**Issue by dan28000** [BG-Software-LLC/SuperiorSkyblock2#1594]
### Minecraft's Version

1.19.2 purpur

### Plugin's Version

latest dev build 972b

### Describe the bug

after restart everyone is is top shows as having zero is level after recalc it fixes the island and after admin recalc for all it only fixes online players

### To Reproduce

start server place some blocks with value on island recalc do restart and you are back to zero in is top and is info

**Comment by OmerBenGera** [comment]
Might be because the block counts weren't saved to DB or something.
Also, `/is admin recalc` for all islands will only calculate online players.

Make sure the block counts are saved in the DB correctly. If so, might be because SGP not loading prices or something, causing the block count worths to not sync correctly.

**Comment by dan28000** [comment]
I've tested this on completly stock SSB without any plugins only SSB and also this happens on production server that restarts once a day

create latest 1.19.2 purpur server put SSB on it create island put some valueable blocks on it now you have some level and after restart you are in negative for level and worth from zero after creating fresh island

**Comment by OmerBenGera** [comment]
> I've tested this on completly stock SSB without any plugins only SSB and also this happens on production server that restarts once a day
> 
> create latest 1.19.2 purpur server put SSB on it create island put some valueable blocks on it now you have some level and after restart you are in negative for level and worth from zero after creating fresh island

As I asked before:
```
Make sure the block counts are saved in the DB correctly.
```
Have you checked it?

**Comment by dan28000** [comment]
Stacked blocks are saving fine but non stacked blocks can't find anywhere in DB

**Comment by OmerBenGera** [comment]
Try latest dev build of SSB, let me know if it's better

**Comment by dan28000** [comment]
from quick testing it works will see tomorow what will happen on production server

**Comment by dan28000** [comment]
seems fine
