### ISSUE TITLE
Problème avec les "entity-limits" 

### ISSUE THREAD

**Issue by Chrqmated** [BG-Software-LLC/SuperiorSkyblock2#1595]
### Minecraft's Version

J'utilise la version 1.18.2 de Minecraft avec le Pufferfish (git-purpur-1632 (MC: 1.18.2)

### Plugin's Version

The plugin version it's latest (Version: 2022.9)

### Describe the bug

Dans le fichier configuration j'ai indiqué ma limite d'entité comme ceci :
```
  entity-limits:
  - MINECART:12
  - VILLAGER:8
  - ARMOR_STAND:12
```
Le problème étant que en jeu, après avoir recréé une île, aucune de ses limites ne fonctionnent. Après avoir été sur le support, on m'a demandé d'utiliser la commande /is admin setentitylimit * armor_stand 2 et de tester sans être admin, rien ne fonctionne même après des redémarrages.

J'en conclu donc que dans ma version, avec les plugins que j'utilise qui touchent aux mobs (RoseLoot, WildStacker ainsi que UpgreadableSpawners) la limitation d'entités ne fonctionne juste pas.

### To Reproduce

Pour reproduire le souci, installer les mêmes plugins que moi avec le même Purpur et retenter.

**Comment by WarnDa** [comment]
t'es sur la dernière version "stable" mais pas dev build, et ce bug a été fixé récemment :
https://hub.bg-software.com/job/SuperiorSkyblock2/
télécharge la b972 ici

**Comment by OmerBenGera** [comment]
Recreate your issue in English.
