### ISSUE TITLE
Island Top

### ISSUE THREAD

**Issue by CertifiedCallatic** [BG-Software-LLC/SuperiorSkyblock2#1598]
### Minecraft's Version

1.19.3 Purpur

### Plugin's Version

Latest Dev Build

### Describe the bug

So noticed on any player leaving and joining back, there calculated level is gone, they need to recalculate it and also with island top it only shows people online on it, once they're offline they do not show or stay there.

Also I use SELL provider for ShopGUIPlus for island worth and this spams everytime on server boot.

### To Reproduce

Use SELL for worth provider and stuff for ShopGUIPlus to reproduce spam error

### Additional Information

[Error.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10738321/Error.txt)

**Comment by OmerBenGera** [comment]
```
net.brcdev.shopgui.exception.shop.ShopsNotLoadedException: Shops aren't loaded yet
```
Why are your shops from SGP not loaded?
This is not an issue of SSB, but SGP not loading their data.

**Comment by CertifiedCallatic** [comment]
Did you totally forget to read the part where island top is not working at all?

**Comment by OmerBenGera** [comment]
> Did you totally forget to read the part where island top is not working at all?

That's because SGP does not load the shops, causing the worth values of all the blocks to be 0.
Therefore, all the island top values stay at 0.
