### ISSUE TITLE
island counts bug after restart

### ISSUE THREAD

**Issue by SyphiX897** [BG-Software-LLC/SuperiorSkyblock2#1599]
### Minecraft's Version

purpur 1.19.3

### Plugin's Version

latest dev build (b972)

### Describe the bug

/is counts gets cleared after restarting server (island level becomes negative).

### To Reproduce

when i create a island, island level is 0 and /is counts is okey but after restarting  the server, island level become negative and /is counts is empty
![Screenshot_20230215_120236](https://user-images.githubusercontent.com/123269034/218976016-d1c70a71-399c-4075-a899-bf028ff84c22.png)
https://youtu.be/ZZAdIlm5uu0

**Comment by OmerBenGera** [comment]
Can't seem to replicate the issue

**Comment by OmerBenGera** [comment]
Try latest dev build of SSB, let me know if it's better

**Comment by SyphiX897** [comment]
> Try latest dev build of SSB, let me know if it's better

today i tested b976 and its okay and doesn't have the bug.
