### ISSUE TITLE
Duping on someone else's island with a bed

### ISSUE THREAD

**Issue by DarkyCat** [BG-Software-LLC/SuperiorSkyblock2#1600]
### Minecraft's Version

1.19.3

### Plugin's Version

in video

### Describe the bug

[[in video](https://litter.catbox.moe/o1gl9z.mp4)](https://litter.catbox.moe/o1gl9z.mp4)

### To Reproduce

in video

**Comment by klaidosHka** [comment]
That's just minecraft things, same in our 1.16.5 survival server, nothing to do with Stacker/SSB.

**Comment by DarkyCat** [comment]
> That's just minecraft things, same in our 1.16.5 survival server, nothing to do with Stacker/SSB.

Have you found an option on how to fix it?

**Comment by dan28000** [comment]
what server are you running paper/purpur/other?

**Comment by DarkyCat** [comment]
> what server are you running paper/purpur/other?

Purpur

**Comment by DarkyCat** [comment]
[DarkDupeFix.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10759601/DarkDupeFix.zip)
Fix solution to this problem. Protocollib and skyblock plugin dependencies.
