### ISSUE TITLE
level counting problem

### ISSUE THREAD

**Issue by LocK3rX** [BG-Software-LLC/SuperiorSkyblock2#1602]
### Minecraft's Version

Mc: 1.19.2
Server: paper-1.19.2-307

### Plugin's Version

SuperiorSkyblock2-2022.9

### Describe the bug

When I am setting island-level-formula: '{} / 2' to island-level-formula: '{} / 4' all levels are 0, not matters how many worth it is. Only one player can count his level...

### To Reproduce

Change island-level-formula: '{} / 2' to island-level-formula: '{} / 4', reload and recalc

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by LocK3rX** [comment]
> Check out latest dev build, let me know if it works

Level counts when player create new island. On old island worth can be 1 bilion but level is 0.

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it works
> 
> Level counts when player create new island. On old island worth can be 1 bilion but level is 0.

What version of SGP do you use?

**Comment by LocK3rX** [comment]
> > > Check out latest dev build, let me know if it works
> > 
> > 
> > Level counts when player create new island. On old island worth can be 1 bilion but level is 0.
> 
> What version of SGP do you use?

ShopGUIPlus-1.81.2

**Comment by OmerBenGera** [comment]
> Author

Try updating SGP, might fix the issue
I can't seem to replicate the issue myself.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue persists, let me know
