### ISSUE TITLE
Transactions Menu Errors

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1603]
### Minecraft's Version

Current: git-Purpur-1876 (MC: 1.19.3)*

### Plugin's Version

SuperiorSkyblock2 version 2022.9

### Describe the bug

https://pastebin.com/LDtc8Yd0
Trying to click the sort by money or sort by time gives this error

### To Reproduce

NA

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
