### ISSUE TITLE
Spawn island TP ignore decimals in X, Y and Z coordinates

### ISSUE THREAD

**Issue by EditChris** [BG-Software-LLC/SuperiorSkyblock2#1606]
### Minecraft's Version

Paper Spigot for 1.19.3, Build 404.

### Plugin's Version

2022.9-b975, dev build

### Describe the bug

When you teleport to the spawn island for any reason, the X, Y and Z coordinates are ignoring their decimal values (when they have them) and you end up teleporting to the center of the nearest block to the specified coordinate.

It doesn't matter if you configured this manually on the config file or if you used the "/is admin setspawn" command, even when the spawn location is correct and looks like it should work, it will still teleport you ignoring whatever decimal you used there.

Yaw and Pitch coordinates work perfectly, this only affect X, Y and Z values.

### To Reproduce

1. Try to set the location for the spawn island directly in the config file to something like...

`location: SuperiorWorld, 32.0, 100.0, 74.0, -90.5, 0.8`

...or use the command "/is admin setspawn" to do it in-game. If you use this command it will save the coordinates and world location perfecly on the config file, also taking note of the decimals.

2. Go to the spawn, either by using "/is admin spawn" or doing something that ends up teleporting you to the spawn, for example island disbanding.

3. Notice that you were teleported incorrectly. Instead of appearing on the world "SuperiorWorld", at X: 32.0, Y: 100.0, Z: 74.0, you will appear in that world at X: 32.5, Y: 100.5, Z: 74.5, but the Yaw and Pitch will be correct.

**Comment by OmerBenGera** [comment]
The spawn location will teleport you to the middle of the block you configured.
Not a bug

**Comment by EditChris** [comment]
Then, can I open a feature request about this, or you won't add this alternative behavior? It would be really nice to have...
