### ISSUE TITLE
rgb hex does not work in all messages

### ISSUE THREAD

**Issue by DarkyCat** [BG-Software-LLC/SuperiorSkyblock2#1608]
### Minecraft's Version

1.19.3 purpur

### Plugin's Version

build 972

### Describe the bug

![изображение](https://user-images.githubusercontent.com/50515714/220152660-996c9c38-29a4-4342-844a-37fd21e5e694.png)

### To Reproduce

/is trust player - execute command

**Comment by OmerBenGera** [comment]
https://wiki.bg-software.com/superiorskyblock/overview/messages#raw-messages
Use the syntax shown in the wiki.
