### ISSUE TITLE
SpawnerMeta - SuperiorSkyBlock limit bug

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/SuperiorSkyblock2#1609]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-58 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 9edb00b on HEAD)
You are running 1 version beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Pufferfish-55 (MC: 1.19.3)

### Plugin's Version

#976

### Describe the bug

Hey. I am using the plugin "SPAWNERMETA" which allows you to dig a spawner however when you dig a spawner there is an error with limits from SuperiorSkyBlock.

The spawner is destroyed but the limit indicates that the spawner is still erected. I can destroy all the spawners on the island and still the limit will show that the spawners are erected.
The author of "SpawnerMeta" added a "cancel-break-event" but it did nothing.

### To Reproduce

Set the spawner limit in SuperiorSkyBlock.
Upload the SpawnerMeta plugin and dig up the spawner you put up.

### Additional Information

After restarting the server, you can put up a spawner as if it read that the spawners have been removed.

**Comment by OmerBenGera** [comment]
You need to contact SpawnerMeta developers so they add support for SuperiorSkyblock.
They probably have custom handling of breaking spawners and they don't let SSB know about the broken block.
They need to either A) call the BlockBreakEvent again or B) Use SSB's API and use Island#handleBlockPlace
