### ISSUE TITLE
Upgrades menu 

### ISSUE THREAD

**Issue by SyphiX897** [BG-Software-LLC/SuperiorSkyblock2#1610]
### Minecraft's Version

purpur 1.19.3

### Plugin's Version

b976

### Describe the bug

upgrade doesnt work, for example when i click on the generator upgrade it says unknown command. type "/help" for help

### To Reproduce

upgrade doesnt work, for example when i click on the generator upgrade it says unknown command. type "/help" for help

**Comment by OmerBenGera** [comment]
Make sure your players have access to the `/is rankup` command
