### ISSUE TITLE
Limitation of specific spawners on an island

### ISSUE THREAD

**Issue by Chrqmated** [BG-Software-LLC/SuperiorSkyblock2#1612]
### Minecraft's Version

Java Minecraft : 1.19.2
Jar version: git-petal-"cc69154" (MC: 1.19.2)*

### Plugin's Version

Version: 2022.9 (no't modified by my developer)

### Describe the bug

I don't know if it's a bug or an unimplemented addition,
I wanted to limit the spawner in "Zoglin" to 10 per island, I did not find how to do it.

After asking the support, I was told to do in block-limits :
- 'SPAWNER:10:ZOGLIN'

After trying, then recreating an island, restarting the server, nothing works. I tried to send the command in game and nothing works. It seemed to me that this addition was possible, but am I wrong?

If not, is it possible to add it? 

### To Reproduce

For reproduce this "bug", test with the same version of plugin and add in "block-limits" :
- 'SPAWNER:10:ZOGLIN'

If the limit worked the problem comes from me ?

**Comment by OmerBenGera** [comment]
You should use `SPAWNER:ZOGLIN` as a block type.
Therefore, `SPAWNER:ZOGLIN:10` should be the correct format.

**Comment by Chrqmated** [comment]
Okay, i have test "SPAWNER:ZOGLIN:10", bu't it's no't working

**Comment by OmerBenGera** [comment]
> Okay, i have test "SPAWNER:ZOGLIN:10", bu't it's no't working

Check your island limits by running /is admin show.
Do you see your limit in there?

**Comment by Chrqmated** [comment]
Hello,

I have retest after restarting of my server and all is good, thanks for your help

**Comment by Chrqmated** [comment]
please specify that restarting are asked for working of that

**Comment by OmerBenGera** [comment]
> please specify that restarting are asked for working of that

Glad it works now!
