### ISSUE TITLE
Nether Portal not working after oneblock addon download

### ISSUE THREAD

**Issue by ELIAS7281** [BG-Software-LLC/SuperiorSkyblock2#1613]
### Minecraft's Version

Minecraft version 1.19 latest version. SSB latest Dev Build.

### Plugin's Version

latest dev build

### Describe the bug

After installing the one block addon, i added a one block schematic then reloaded, the one block worked but entering the nether showed up complete red and rubberbanding when trying to move, I removed the oneblock schematic and reinstated the normal schematics with the addon still installed but still nether not working, as operator i can enter the nether through the portal and the nether island works fine.,  i recently deleted the superior world nether and restarted so i could try regenerate the nether but now even as operator i cannot enter the nether at all.

### To Reproduce

please read above 

### Additional Information

https://pastes.dev/Qi1HOpdosy
ssb config

**Comment by ELIAS7281** [comment]
https://pastes.dev/XgUsDHRie6

**Comment by ELIAS7281** [comment]
![image](https://user-images.githubusercontent.com/111949540/220894762-cbd16f77-451d-438c-bea2-d6920ed29e59.png)

**Comment by ELIAS7281** [comment]
Yes but I removed the 1 block schematic and now using normal and normal_nether.schem as default , restarted, then created a new island using normal island.

**Comment by OmerBenGera** [comment]
> Yes but I removed the 1 block schematic and now using normal and normal_nether.schem as default , restarted, then created a new island using normal island.

Take a video of the issue please.
Make sure you do so on a new island.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ELIAS7281** [comment]
hi sorry , yes i made a video, this is on a new island and i entered the portal, it just shows red and rubberbanding. i can enter the nether no problem on my opped account and all is fine.

https://user-images.githubusercontent.com/111949540/225200473-04761561-b218-45e1-9553-c90e52e847af.mp4

**Comment by ELIAS7281** [comment]
![image](https://user-images.githubusercontent.com/111949540/225200825-329f626b-57ee-4002-ae19-a6e65f86d072.png)
i have everything back to normal now with the original schematics that came with the plugin as you can see

**Comment by OmerBenGera** [comment]
I see that you are stuck in the video. Try relogging if it happens, check if it helps.
Also, try it on a server with only SSB installed, on Paper 1.19.3

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
