### ISSUE TITLE
Unsupported Java Version

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/SuperiorSkyblock2#1615]
### Minecraft's Version

1.8.8

### Plugin's Version

2022.9-b976

### Describe the bug

Whenever I load up my server, it says "Unsupported Java Version" as you can see here https://prnt.sc/sHvD5L1CDgtg 

### To Reproduce

Run SuperiorSkyblock on a Java 8 server

**Comment by OmerBenGera** [comment]
Not related to SSB or minecraft in general in any way.
Your pterodactyl panel warns you about using Java 8.
