### ISSUE TITLE
Issue with ss2 loading 

### ISSUE THREAD

**Issue by Kristopherrr** [BG-Software-LLC/SuperiorSkyblock2#1616]
### Minecraft's Version

paper 1.19.3 build 420

### Plugin's Version

Dev build #977

### Describe the bug

![Screenshot_1](https://user-images.githubusercontent.com/114158743/221358368-b39af0f7-419a-4c6f-8c7c-245a573f1faf.png)

paper changed their plugin loading system and its causing issues to ss2

### To Reproduce

install the ss2 and one of the other plugins mentioned in 1.19.3 build of paper

**Comment by OmerBenGera** [comment]
Disable paper's new loading system.
