### ISSUE TITLE
Island upgrade effects dont get taken

### ISSUE THREAD

**Issue by Warrior1321** [BG-Software-LLC/SuperiorSkyblock2#1617]
### Minecraft's Version

1.17.1-R0.1.1-SNAPSHOT

### Plugin's Version

superiorskyblock2 2022.9-b972

### Describe the bug

when i have a beacon effect island upgrade and i disband my island i keep all effects

### To Reproduce

make a beacon island upgrade

https://pastebin.com/1xBbTXnB - here is the one i made that im using

once you maxed it out and you relog (hopefully this can be fixed too where it instantly gives effect not make a player have to relog)  you will have all the effects needed, but then if you disbanded your island and make a new island you keep all the effects but allowed to upgrade the island upgrade again

**Comment by OmerBenGera** [comment]
Just to make sure I understand you correctly, island effects are not taken away for players when they disband their island?
If so, I tried doing just that and it worked fine for me. I gave myself island effect using `/is admin seteffect` and then disbanded the island and the effect was taken away.

**Comment by Warrior1321** [comment]
I did it for the island upgrade

using the format of island-effects as shown below



    '2':
      price: 50000.0
      price-type: 'placeholders'
      placeholder: '%supermobcoins_mobcoins%'
      island-effects:
        SPEED: 3
      withdraw-commands:
      - 'mobcoins take %player% 50000'
      commands:
      - island admin setupgrade %player% effects 3
      - island admin msgall %player% &e&lSuperiorSkyblock &7Your island have received their effects!


when i make an island and i upgrade i get the effect, but on disband i keep the effect, i relogged and still had the effect

**Comment by Warrior1321** [comment]
Also, i just tried the same thing doing /is admin seteffects and still isnt clearing that for me

**Comment by OmerBenGera** [comment]
Take a video of the issue please, as I might be doing something wrong as it seems fine for me
Upload it to YT or any other online streaming services and send a link to it here please

**Comment by Warrior1321** [comment]
Ok, ill try doing this

**Comment by Warrior1321** [comment]
https://youtu.be/OXKI2Ny7oE4

**Comment by Warrior1321** [comment]
event-commands:
  IslandDisbandEvent:
  - 'island admin cmdall %island% false effect clear %player%'
  
  I did put this in the config.yml, but it keeps saying there is no island with the name false, thought doing this may work but nah

**Comment by OmerBenGera** [comment]
Does it happen on a 1.19 server?

**Comment by Warrior1321** [comment]
idk, not sure as im using 1.17.1

**Comment by OmerBenGera** [comment]
> idk, not sure as im using 1.17.1

Test it on a 1.19.3 paper server, let me know if it still occurs.

**Comment by Warrior1321** [comment]
ok, ill test it

**Comment by Warrior1321** [comment]
Nope, after testing the effects dont get removed on a 1.19.3 server

**Comment by Warrior1321** [comment]
I also tried using the islanddisbandevent in the config and also didnt work, i did 

event-commands:
  IslandDisbandEvent:
  - 'island admin cmdall %island% false effect clear %player%'
but it keeps saying island false is not an island

**Comment by OmerBenGera** [comment]
Upload the entire mob drops upgrade to pastebin and send it here
It looks like any changes to effects don't work for you.

**Comment by Warrior1321** [comment]
https://pastebin.com/RHRGYb5d - FULL upgrades.yml from modules
https://pastebin.com/EiK0TVUj - FULL upgrades.yml menu file

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed.

**Comment by Warrior1321** [comment]
Thats fixed, thank you!!!
