### ISSUE TITLE
island creation problem

### ISSUE THREAD

**Issue by jjjjjjfn** [BG-Software-LLC/SuperiorSkyblock2#1618]
### Minecraft's Version

purpur-1.19.3-1913

### Plugin's Version

SuperiorSkyblock2-2022.9-b976

### Describe the bug

I created a new schematic with the /is admin schematic command.
but it does not go to this island, I write /is create asdd island, but nothing happens, it does not give an error
![image](https://user-images.githubusercontent.com/66686400/222393677-d2a18294-d368-42b4-a3c9-85a599de3c1e.png)
![image](https://user-images.githubusercontent.com/66686400/222393713-91efb9ca-81aa-4cce-8669-1d8dd0787d30.png)
there is no error but it does not create the candidate either
https://wiki.bg-software.com/superiorskyblock/overview/schematics I watched this video and installed it by looking at it

### To Reproduce

..

**Comment by call911nowplz** [comment]
Can confirm
The schematic works perfectly to be clear. But SSB2 doesn't recognize schematic names outside the default ones
Renamig the schematic you created to "normal" will allow you to use the schematic perfectly fine

**Comment by call911nowplz** [comment]
FIX:
The schematic name must be in island-creation.yml
If the schematic name is not in there, The plugin will ignore it. I don't know if this is intentional or not

**Comment by OmerBenGera** [comment]
> FIX: The schematic name must be in island-creation.yml If the schematic name is not in there, The plugin will ignore it. I don't know if this is intentional or not

You must add the schematic you want to be used to the island creation menu
