### ISSUE TITLE
Blocks dont count if broken by piston with slimeblock

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1619]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

977

### Describe the bug

Blocks dont count if broken by piston with slimeblock

### To Reproduce

https://imgur.com/a/YgFb95i

**Comment by OmerBenGera** [comment]
I am afraid it is similar to #1014

**Comment by exzolink** [comment]
> I am afraid it is similar to #1014

But it is Paper fork

**Comment by OmerBenGera** [comment]
> > I am afraid it is similar to #1014
> 
> But it is Paper fork

1.16.5 fork tho
Paper added support for such actions in the world in newer versions probably.

**Comment by JanReich** [comment]
Maybe you can Hold track of the Blocks and get the "PistonMoveReaction". You can trace which blocks are effected when the piston moves and then ask for every single block the PistonMoveReaction. Than you can track which material will break when the piston moves

**Comment by OmerBenGera** [comment]
@exzolink @JanReich Any news regarding this?
