### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by SkyWaves123** [BG-Software-LLC/SuperiorSkyblock2#1620]
### Minecraft's Version

PaperSpigot-445 1.8.8

### Plugin's Version

SuperiorSkyBlock2-2022.9

### Describe the bug

Error on startup
03.03 19:22:45 [Server] [ERROR] [SuperiorSkyblock2] An unexpected error occurred while registering hook SkinsRestorerHook:
03.03 19:22:45 [Server] [WARN] java.lang.reflect.InvocationTargetException
03.03 19:22:45 [Server] [WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.03 19:22:45 [Server] [WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
03.03 19:22:45 [Server] [WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.03 19:22:45 [Server] [WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:568)
03.03 19:22:45 [Server] [WARN] at com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerHook(ProvidersManagerImpl.java:567)
03.03 19:22:45 [Server] [WARN] at com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.registerGeneralHooks(ProvidersManagerImpl.java:370)
03.03 19:22:45 [Server] [WARN] at com.bgsoftware.superiorskyblock.external.ProvidersManagerImpl.lambda$loadData$1(ProvidersManagerImpl.java:92)
03.03 19:22:45 [Server] [WARN] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
03.03 19:22:45 [Server] [WARN] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352)
03.03 19:22:45 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783)
03.03 19:22:45 [Server] [WARN] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
03.03 19:22:45 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
03.03 19:22:45 [Server] [WARN] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
03.03 19:22:45 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:831)
03.03 19:22:45 [Server] [WARN] Caused by: java.lang.NoClassDefFoundError: skinsrestorer/shared/exception/SkinRequestException
03.03 19:22:45 [Server] [WARN] at com.bgsoftware.superiorskyblock.external.SkinsRestorerHook.register(SkinsRestorerHook.java:38)
03.03 19:22:45 [Server] [WARN] ... 14 more
03.03 19:22:45 [Server] [WARN] Caused by: java.lang.ClassNotFoundException: skinsrestorer.shared.exception.SkinRequestException
03.03 19:22:45 [Server] [WARN] at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:432)
03.03 19:22:45 [Server] [WARN] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
03.03 19:22:45 [Server] [WARN] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
03.03 19:22:45 [Server] [WARN] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
03.03 19:22:45 [Server] [WARN] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
03.03 19:22:45 [Server] [WARN] ... 15 more

### To Reproduce

I honestly dont know. From the error i suppose the plugin cant hook into SkinRestorer.

**Comment by OmerBenGera** [comment]
Update SSB please to latest dev build, let me know if it works

**Comment by SkyWaves123** [comment]
ive updated to the latest stable dev build and the error is gone. thank you
