### ISSUE TITLE
/fly getting turned off when teleporting - Needs further look

### ISSUE THREAD

**Issue by CreeperJockeyJr** [BG-Software-LLC/SuperiorSkyblock2#1621]
### Minecraft's Version

purpur-1.19.2-1856.jar

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

When you teleport and you switch dimension, you lose /fly and have to retype it to be able to fly.

### To Reproduce

Steps to reproduce the issue?
have /fly
teleport to somewhere else that is in another dimension
try to fly

**Comment by OmerBenGera** [comment]
Do you mean /island fly or /fly of another plugin?

**Comment by CreeperJockeyJr** [comment]
It is /fly from CMI that is being turned off and it only happens with superiorskyblock installed.

**Comment by OmerBenGera** [comment]
I tried it without SSB installed and it still occurs.
How do you teleport between dimensions?

**Comment by CreeperJockeyJr** [comment]
Any type of world switching makes /fly get turned off. So when players use /homes, portals, and /rtp their fly gets disabled.

**Comment by OmerBenGera** [comment]
> Any type of world switching makes /fly get turned off. So when players use /homes, portals, and /rtp their fly gets disabled.

I tried it without SSB as well and it seems to also occur.
Can you confirm/deny it?

**Comment by CreeperJockeyJr** [comment]
> > Any type of world switching makes /fly get turned off. So when players use /homes, portals, and /rtp their fly gets disabled.
> 
> I tried it without SSB as well and it seems to also occur. Can you confirm/deny it?

Confirm

**Comment by OmerBenGera** [comment]
> > > Any type of world switching makes /fly get turned off. So when players use /homes, portals, and /rtp their fly gets disabled.
> > 
> > 
> > I tried it without SSB as well and it seems to also occur. Can you confirm/deny it?
> 
> Confirm

Its not an issue with SSB as you can see...

**Comment by OmerBenGera** [comment]
Closing this as it doesn't seem related to the plugin
