### ISSUE TITLE
Crop Simulator Sweet Berry quest

### ISSUE THREAD

**Issue by CreeperJockeyJr** [BG-Software-LLC/SuperiorSkyblock2#1622]
### Minecraft's Version

purpur-1.19.2-1856.jar

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

Make the Crop Simulator Sweet Berry quest actually detect how Sweet Berries are harvested
Reason: It will actually make it a challenge as opposed to just right/left clicking until it is done

### To Reproduce

When harvesting sweet berries for the sweet berry quest just right click and it will not register.

**Comment by OmerBenGera** [comment]
Show me how you configured your mission please.
Upload it to pastebin and send a link to it here

**Comment by CreeperJockeyJr** [comment]
https://pastebin.com/82h6qHsX

**Comment by OmerBenGera** [comment]
BlocksMissions is only tracking breaking or placing of blocks. Therefore, by using this type of mission, it will only detect breaking or placing sweet barries.
Why aren't you using FarmingMissions for this? It might work better for you.

**Comment by Skizzles** [comment]
> BlocksMissions is only tracking breaking or placing of blocks. Therefore, by using this type of mission, it will only detect breaking or placing sweet barries. Why aren't you using FarmingMissions for this? It might work better for you.

This is one my server admins so apologies. The issue lies in the farming mission being used for sweet berries and not detecting their harvest method properly. They sent you the blockbreak mission we had to use as a work around.

If you need a farmingmission I can locate mine to send as this issue is for the FarmingMission type.

**Comment by OmerBenGera** [comment]
> > BlocksMissions is only tracking breaking or placing of blocks. Therefore, by using this type of mission, it will only detect breaking or placing sweet barries. Why aren't you using FarmingMissions for this? It might work better for you.
> 
> This is one my server admins so apologies. The issue lies in the farming mission being used for sweet berries and not detecting their harvest method properly. They sent you the blockbreak mission we had to use as a work around.
> 
> If you need a farmingmission I can locate mine to send as this issue is for the FarmingMission type.

No need for that, I will look into it myself.

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, should be fixed.
Make sure you use "SWEET_BERRY_BUSH" as a material (and not "SWEET_BERRIES")

**Comment by Skizzles** [comment]
Hello Omer,

We will reply back to you as soon as we can. Thank you for the update on that!

**Comment by OmerBenGera** [comment]
I am closing this as it seems to work.
If the issue continues let me know
