### ISSUE TITLE
/is Chest sending you to the main island chest menu

### ISSUE THREAD

**Issue by CreeperJockeyJr** [BG-Software-LLC/SuperiorSkyblock2#1623]
### Minecraft's Version

purpur-1.19.2-1856.jar

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

When exiting a ./is chest with esc, instead of kicking you out of the GUI, send you back to the is chest selection menu

### To Reproduce

Open /is chest and exit out using esc.

### Additional Information

Unsure if this is a bug or if it is intentional.

**Comment by OmerBenGera** [comment]
Add "previous-menu: false" to the island chest menu config file.

**Comment by Skizzles** [comment]
@OmerBenGera 

I think what they mean is that ESC is not sending to the previous menu. When ESC is pressed it exits out the menu completely, even when "previous-menu: true" is set in the file.

I just tested with false and true and both exit out the menu when using ESC and do not return to the previous menu.

**Comment by OmerBenGera** [comment]
> @OmerBenGera
> 
> I think what they mean is that ESC is not sending to the previous menu. When ESC is pressed it exits out the menu completely, even when "previous-menu: true" is set in the file.
> 
> I just tested with false and true and both exit out the menu when using ESC and do not return to the previous menu.

They reported the opposite.
Open a new issue tho as previous-menu should affect it.

**Comment by CreeperJockeyJr** [comment]
@OmerBenGera 
Apologies, this is my bad. Yes, what i meant was when players are pressing ESC it is not going back to the previous menu. Would you still like me to make a new issue so this does not get confusing.

**Comment by OmerBenGera** [comment]
> @OmerBenGera Apologies, this is my bad. Yes, what i meant was when players are pressing ESC it is not going back to the previous menu. Would you still like me to make a new issue so this does not get confusing.

It's not gonna be an easy fix as the island chests are not actually treated as a regular menu.
Also, I am not sure how people would love this change.

Therefore, I am keeping this as it is for the time being.
