### ISSUE TITLE
RoseStacker Spawners cannot be disabled with is settings

### ISSUE THREAD

**Issue by George-Rowland** [BG-Software-LLC/SuperiorSkyblock2#1625]
### Minecraft's Version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### Plugin's Version

[12:07:30 INFO]: SuperiorSkyblock2 version 2022.9
[12:07:30 INFO]: Feature packed Skyblock core.
[12:07:30 INFO]: Website: https://bg-software.com/
[12:07:30 INFO]: Author: Ome_R

### Describe the bug

 RoseStacker Spanwers are still spawning mobs even when toggled in /is settings.
See for reproduction and video: https://youtu.be/WjZm0F4HUqs

Spawners are set to use RoseStacker: https://prnt.sc/bSMDkf4NrfQh

### To Reproduce

Place a RoseStacker spawner, toggle mob spawning off in /is settings, mobs still spawn

### Additional Information

https://youtu.be/WjZm0F4HUqs

**Comment by OmerBenGera** [comment]
Contact RoseStacker regarding this.
SuperiorSkyblock disables the SpawnerSpawnEvent, and I suspect they do not call it properly.

**Comment by George-Rowland** [comment]
I have passed this on to RoseStacker support and will keep you updated if applicable

**Comment by OmerBenGera** [comment]
> I have passed this on to RoseStacker support and will keep you updated if applicable

Awesome!
