### ISSUE TITLE
Visitors are able to remove items from Flower Pots

### ISSUE THREAD

**Issue by OGreenC** [BG-Software-LLC/SuperiorSkyblock2#1626]
### Minecraft's Version

paper-1.17.1-411.jar

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

Visitors are able to remove items from flower pots, but not to place items in flower pots. Please see the video below, which was sent to me by one of my players:

https://medal.tv/games/minecraft/clips/W17P3jru5zv2V/zHdbD316n8vG

### To Reproduce

Visit a island owned by another player, and attempt to remove an item from a flower point on said island.

**Comment by OmerBenGera** [comment]
Add flower pot to the interactables list, let me know if it helps.
(Look for the correct material name on https://bg-software.com/materials/)

**Comment by OGreenC** [comment]
Hi!

Thank you - Adding the missing IDs to the Interactables list seems to do the trick.

It seems like every variant of potted flower pots, have to be added individually (eg. 'POTTED_WITHER_ROSE'), and a few of them was missing from my list.

**Comment by OmerBenGera** [comment]
> Hi!
> 
> Thank you - Adding the missing IDs to the Interactables list seems to do the trick.
> 
> It seems like every variant of potted flower pots, have to be added individually (eg. 'POTTED_WITHER_ROSE'), and a few of them was missing from my list.

Sounds right
I will make sure they are included in the default interactables file.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
