### ISSUE TITLE
Crash server 

### ISSUE THREAD

**Issue by ByWoX** [BG-Software-LLC/SuperiorSkyblock2#1628]
### Minecraft's Version

1.18.2

### Plugin's Version

2022.9 30/10/2022 18:00:14

### Describe the bug

Hello, I have this error which is displayed on the console and the server at startup crash https://media.discordapp.net/attachments/1043540515129401425/1081539941252730890/firefox_CPYZh02Hvy.png

### To Reproduce

This error appears since I deleted the SuperWorld world to recreate a new one

**Comment by OmerBenGera** [comment]
Update to latest dev build
