### ISSUE TITLE
island missions

### ISSUE THREAD

**Issue by Warrior1321** [BG-Software-LLC/SuperiorSkyblock2#1629]
### Minecraft's Version

 1.17.1-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2-2022.9-b977

### Describe the bug

I was setting up island missions but when setting up witches i put

&b{value_witch}/3,000' when i restarted server it would just show the {value_witch}/3000 it doesnt actually change like the rest where it changes it to a number, wasnt sure if i put the wrong thing but was told it should be witch

### To Reproduce

setup an island mission with witch in it

**Comment by Warrior1321** [comment]
Also, an addon, to island missions, when im making potions it counts the 3 potions i made as 12? like i brewed 3 speed potions, but it counted as 12 towards the /is missions

**Comment by OmerBenGera** [comment]
Upload your mission file to pastebin and send it here please.
Regarding the second issue, please open a separate issue.

**Comment by OmerBenGera** [comment]
Upload your mission file to pastebin and send it here please.
Regarding the second issue, please open a separate issue.

**Comment by Warrior1321** [comment]
[missions.zip.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10909364/missions.zip.zip)

**Comment by OmerBenGera** [comment]
You have a mistake in your mission file. You put under the `required-entities` the section `3` two times - one for the witch and one for creeper. Because they were with the same name, the creeper section overridden the witch section.
Change one of them to `4` or any other unique string and it will work :)
