### ISSUE TITLE
Island Top Not Showing skins correctly

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/SuperiorSkyblock2#1630]
### Minecraft's Version

1.16.5

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

When looking at the island top it's only showing a certain amount of player skins for some reason 

### To Reproduce

Unsure tbh

### Additional Information

https://i.gyazo.com/b5d489cdc70b2e5aaa62463bd5eee97a.png

**Comment by OmerBenGera** [comment]
What skins plugin are you using?
Let me know its name and the version of the plugin

**Comment by DJDan21** [comment]
I am not using a skin plugin at all just for some unknown reason it's not showing players offline skins on the /is top menu

**Comment by OmerBenGera** [comment]
Do you have your server in offline mode?

**Comment by DJDan21** [comment]
Yes, that's causes its connect to a bungee cord network

**Comment by DJDan21** [comment]
Any idea how I can resolve this issue?

**Comment by DevTarlow** [comment]
I am having this same issue 
![image](https://user-images.githubusercontent.com/49800587/225945880-a7005551-0515-4fcb-af32-e48d8ad04fbb.png)

**Comment by OmerBenGera** [comment]
Has it ever worked before?
I am pretty sure you must have a skins plugin if your server is in offline mode, even if it's because of Bungeecord.

**Comment by OmerBenGera** [comment]
@DevTarlow This is not related to this issue.

**Comment by DevTarlow** [comment]
You are correct, I misread the title. I resolved my issue by doing /is
admin syncbonus

**Comment by DJDan21** [comment]
@OmerBenGera yes it has worked before, it will show skins of when the player last logged in but then when the server reboots they return to steve heads

**Comment by OmerBenGera** [comment]
> @OmerBenGera yes it has worked before, it will show skins of when the player last logged in but then when the server reboots they return to steve heads

Check if their skin texture is saved in the database.
You should see a weird and long string in the players table.

**Comment by DJDan21** [comment]
@OmerBenGera is this what you're looking for? https://pastebin.com/UnxhqA1x

**Comment by DJDan21** [comment]
@OmerBenGera I see something like this indexsqlite_autoindex_islands_1islands          û    Bû3‘´Ýâ¬{±€O í ¼ ‹ R                                         9
4ef0decc-71f3-46d1-8e8c-4267ef336faaJohnnyPVPc(±/U
3335ac48-8399-4869-9aba-2194ca0e6f95nullÿ/U
e3c6d7da-dafc-4ef3-a47f-c201819a2b77nullÿ/U
8cbf74f7-5d2e-4435-981e-8b75fbcdfcc0nullÿ/U
7fb739a4-610e-4374-b4e5-bc48f65798b5nullÿ/
U
dc6f09e9-277f-4bc0-aa91-e4adc65a2521nullÿ/U
54c06d29-a719-48bf-814d-9e9a0f0bc7canullÿ/U
047d31d5-0126-4a2a-bb41-3205c472bf96nullÿ…U#‰E0ff1207a-2a9a-400a-9abf-fc2109987b5eHeyWannaHugewogICJ0aW1lc3RhbXAiIDogMTY3MTEzOTU5MjkzMiwKICAicHJvZmlsZUlkIiA6ICIwZmYxMjA3YTJhOWE0MDBhOWFiZmZjMjEwOTk4N2I1ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJIZXlXYW5uYUh1ZyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMmYzMDQxMWNjNTMzNWU1OTEzZmJiZDllYjVmNWYyZTIxMTk1OGQ1N2Q2OWViMmE1NjNiODQzZGQ5ZWVmNGUxIgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMzQwYzBlMDNkZDI0YTExYjE1YThiMzNjMmE3ZTllMzJhYmIyMDUxYjI0ODFkMGJhN2RlZmQ2MzVjYTdhOTMzIgogICAgfQogIH0KfQ==c›î/
U
0d6b52ab-5daf-48cc-93d1-f188533a5091nullÿ/	U
38c4659f-1ce3-40b0-912a-83151d0ffae0nullÿƒTU†Ead860dea-841c-4973-882e-d3b0ad6a9511Kronucks1ewogICJ0aW1lc3RhbXAiIDogMTY3MTI0MjEzMTgzOSwKICAicHJvZmlsZUlkIiA6ICJhZDg2MGRlYTg0MWM0OTczODgyZWQzYjBhZDZhOTUxMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJLcm9udWNrczEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI4MmYyOWU2ZTlmMjRmMWE5YjZhNmYyZjk5MmFlOTAyMWEyNzliYWY0NmFkOTJkNjZjNzA5NTEzM2Y0NmQ1NyIKICAgIH0KICB9Cn0=c"þƒZU#†M98c27218-e34b-4a91-a058-620bad54b52bhellogodbayewogICJ0aW1lc3RhbXAiIDogMTY3MTAxMTE3MDczMiwKICAicHJvZmlsZUlkIiA6ICI5OGMyNzIxOGUzNGI0YTkxYTA1ODYyMGJhZDU0YjUyYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJoZWxsb2dvZGJheSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMmY5MmMzZWNkYTk2ZDZhOTFjY2FlNjY3NWEzMmI2MjM2MDg4ZmYwNGFkZWZjMjc5OTEwZDViZjUyMTY5ZjJkIgogICAgfQogIH0KfQ==c™œo…U-‰M4a9236a0-8331-4108-83d0-34c661c27e0dGame_Over_HaHaHaewogICJ0aW1lc3RhbXAiIDogMTY2NzE2Njc0ODA1OSwKICAicHJvZmlsZUlkIiA6ICI0YTkyMzZhMDgzMzE0MTA4ODNkMDM0YzY2MWMyN2UwZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJHYW1lX092ZXJfSGFIYUhhIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzlmMGFjMjNiNGQ5ODNjMmJiMTI2Mjk4YTg0NjgzYjQ0OTJlNDNiMzk2MTc2MGY3OWZmMmYyZjUwYjkzOTg1ZmUiCiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzNDBjMGUwM2RkMjRhMTFiMTVhOGIzM2MyYTdlOWUzMmFiYjIwNTFiMjQ4MWQwYmE3ZGVmZDYzNWNhN2E5MzMiCiAgICB9CiAgfQp9c^ùw/U
ad8ea840-ff75-4d3e-863c-88ec357cc3ednullÿ/U
3dd9b45c-5f52-4c9e-aba3-e7d68ec4209dnullÿƒ\U'†M08810ae2-606f-48ff-93b3-57b7cb1cb327RandomUser101ewogICJ0aW1lc3RhbXAiIDogMTY3MTA3NjczOTc0OSwKICAicHJvZmlsZUlkIiA6ICIwODgxMGFlMjYwNmY0OGZmOTNiMzU3YjdjYjFjYjMyNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJSYW5kb21Vc2VyMTAxIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2MGZmNzFkODUxODg3MzYyZmEwMjQ1YjIwZGY5ZTBjZGIyOTg2MTA1OGRhODg5OTQzYzNkMDE0ZmIzN2I4M2UiCiAgICB9CiAgfQp9cšž$…	U‰5e3ffe036-afcf-4024-a488-0e2087b4a41c_DJDanewogICJ0aW1lc3RhbXAiIDogMTY3MTI0MzY0ODkyMiwKICAicHJvZmlsZUlkIiA6ICJlM2ZmZTAzNmFmY2Y0MDI0YTQ4ODBlMjA4N2I0YTQxYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJfREpEYW4iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmMwM2ViOGQ1NzliMGUzMzIxNWFmNmMwNmI4NmVkZTI1ZThkZjk5ZTY4NGVhNTRiMWE5Y2M3MDA5ZmVkZDgxMyIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0   A

**Comment by OmerBenGera** [comment]
> @OmerBenGera I see something like this indexsqlite_autoindex_islands_1islands� � � ��û B�û�3�‘�´�Ý�â�¬�{�±�€�O�� í ¼ ‹ R 9� ��4ef0decc-71f3-46d1-8e8c-4267ef336faaJohnnyPVPc�(±/��U� ��3335ac48-8399-4869-9aba-2194ca0e6f95nullÿ/��U� ��e3c6d7da-dafc-4ef3-a47f-c201819a2b77nullÿ/��U� ��8cbf74f7-5d2e-4435-981e-8b75fbcdfcc0nullÿ/��U� ��7fb739a4-610e-4374-b4e5-bc48f65798b5nullÿ/ �U� ��dc6f09e9-277f-4bc0-aa91-e4adc65a2521nullÿ/�U� ��54c06d29-a719-48bf-814d-9e9a0f0bc7canullÿ/��U� ��047d31d5-0126-4a2a-bb41-3205c472bf96nullÿ…���U#‰E��0ff1207a-2a9a-400a-9abf-fc2109987b5eHeyWannaHugewogICJ0aW1lc3RhbXAiIDogMTY3MTEzOTU5MjkzMiwKICAicHJvZmlsZUlkIiA6ICIwZmYxMjA3YTJhOWE0MDBhOWFiZmZjMjEwOTk4N2I1ZSIsCiAgInByb2ZpbGVOYW1lIiA6ICJIZXlXYW5uYUh1ZyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9jMmYzMDQxMWNjNTMzNWU1OTEzZmJiZDllYjVmNWYyZTIxMTk1OGQ1N2Q2OWViMmE1NjNiODQzZGQ5ZWVmNGUxIgogICAgfSwKICAgICJDQVBFIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS8yMzQwYzBlMDNkZDI0YTExYjE1YThiMzNjMmE3ZTllMzJhYmIyMDUxYjI0ODFkMGJhN2RlZmQ2MzVjYTdhOTMzIgogICAgfQogIH0KfQ==c›î�/ �U� ��0d6b52ab-5daf-48cc-93d1-f188533a5091nullÿ/ �U� ��38c4659f-1ce3-40b0-912a-83151d0ffae0nullÿƒT��U�†E��ad860dea-841c-4973-882e-d3b0ad6a9511Kronucks1ewogICJ0aW1lc3RhbXAiIDogMTY3MTI0MjEzMTgzOSwKICAicHJvZmlsZUlkIiA6ICJhZDg2MGRlYTg0MWM0OTczODgyZWQzYjBhZDZhOTUxMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJLcm9udWNrczEiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI4MmYyOWU2ZTlmMjRmMWE5YjZhNmYyZjk5MmFlOTAyMWEyNzliYWY0NmFkOTJkNjZjNzA5NTEzM2Y0NmQ1NyIKICAgIH0KICB9Cn0=c�"þƒZ��U#†M��98c27218-e34b-4a91-a058-620bad54b52bhellogodbayewogICJ0aW1lc3RhbXAiIDogMTY3MTAxMTE3MDczMiwKICAicHJvZmlsZUlkIiA6ICI5OGMyNzIxOGUzNGI0YTkxYTA1ODYyMGJhZDU0YjUyYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJoZWxsb2dvZGJheSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kMmY5MmMzZWNkYTk2ZDZhOTFjY2FlNjY3NWEzMmI2MjM2MDg4ZmYwNGFkZWZjMjc5OTEwZDViZjUyMTY5ZjJkIgogICAgfQogIH0KfQ==c™œo…���U-‰M��4a9236a0-8331-4108-83d0-34c661c27e0dGame_Over_HaHaHaewogICJ0aW1lc3RhbXAiIDogMTY2NzE2Njc0ODA1OSwKICAicHJvZmlsZUlkIiA6ICI0YTkyMzZhMDgzMzE0MTA4ODNkMDM0YzY2MWMyN2UwZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJHYW1lX092ZXJfSGFIYUhhIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzlmMGFjMjNiNGQ5ODNjMmJiMTI2Mjk4YTg0NjgzYjQ0OTJlNDNiMzk2MTc2MGY3OWZmMmYyZjUwYjkzOTg1ZmUiCiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzNDBjMGUwM2RkMjRhMTFiMTVhOGIzM2MyYTdlOWUzMmFiYjIwNTFiMjQ4MWQwYmE3ZGVmZDYzNWNhN2E5MzMiCiAgICB9CiAgfQp9c^ùw/��U� ��ad8ea840-ff75-4d3e-863c-88ec357cc3ednullÿ/��U� ��3dd9b45c-5f52-4c9e-aba3-e7d68ec4209dnullÿƒ\��U'†M��08810ae2-606f-48ff-93b3-57b7cb1cb327RandomUser101ewogICJ0aW1lc3RhbXAiIDogMTY3MTA3NjczOTc0OSwKICAicHJvZmlsZUlkIiA6ICIwODgxMGFlMjYwNmY0OGZmOTNiMzU3YjdjYjFjYjMyNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJSYW5kb21Vc2VyMTAxIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlL2M2MGZmNzFkODUxODg3MzYyZmEwMjQ1YjIwZGY5ZTBjZGIyOTg2MTA1OGRhODg5OTQzYzNkMDE0ZmIzN2I4M2UiCiAgICB9CiAgfQp9cšž$… ��U�‰5��e3ffe036-afcf-4024-a488-0e2087b4a41c_DJDanewogICJ0aW1lc3RhbXAiIDogMTY3MTI0MzY0ODkyMiwKICAicHJvZmlsZUlkIiA6ICJlM2ZmZTAzNmFmY2Y0MDI0YTQ4ODBlMjA4N2I0YTQxYyIsCiAgInByb2ZpbGVOYW1lIiA6ICJfREpEYW4iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmMwM2ViOGQ1NzliMGUzMzIxNWFmNmMwNmI4NmVkZTI1ZThkZjk5ZTY4NGVhNTRiMWE5Y2M3MDA5ZmVkZDgxMyIKICAgIH0sCiAgICAiQ0FQRSIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjM0MGMwZTAzZGQyNGExMWIxNWE4YjMzYzJhN2U5ZTMyYWJiMjA1MWIyNDgxZDBiYTdkZWZkNjM1Y2E3YTkzMyIKICAgIH0KICB9Cn0 A�

You need to open the DB using a program that can do so, not a text editor.
Use DB Browser or google "sqlite viewer" to open the DB.

**Comment by DJDan21** [comment]
@OmerBenGera I have opened the players table using the DB browser program and quite a few skins textures are missing as shown here 
![image](https://user-images.githubusercontent.com/19984107/227583237-1dcb6474-2021-4bcf-bb72-24415055a8f8.png)
![image](https://user-images.githubusercontent.com/19984107/227583271-1a978311-ad82-40e2-9613-129a35ee3516.png)

**Comment by OmerBenGera** [comment]
So for these players, a steve texture will be shown in the top islands menu.
This will be updated as soon as these players join the server and their skin will be updated.

**Comment by DJDan21** [comment]
@OmerBenGera the skins do update when these players join the server but this is still my issue when the server reboots they lose their skin and only some players' skins remain, how can I fix this issue?

**Comment by OmerBenGera** [comment]
> @OmerBenGera the skins do update when these players join the server but the issue I'm having is even when those players log in to the server after the server performs a reboot/restarting the server they turning back to steve heads, how can I prevent this issue from occurring?

Check if their skin texture is saved to the DB.

**Comment by DJDan21** [comment]
@OmerBenGera It's not saving the player's skin texture for all players it's only for some players that it will save the skin texture. I can send you the database file if needed, for some reason it only will show the player's skin when the player login into the server then after I restart my Minecraft server almost all skins apart from some players turn back to steve's heads.

**Comment by DJDan21** [comment]
@OmerBenGera this is still occurring even after updating my server to 1.19.3

**Comment by OmerBenGera** [comment]
> @OmerBenGera this is still occurring even after updating my server to 1.19.3

Why would it help or affect anything? I didn't tell you to do it.

The issue is that the texture skin is not saved to DB because your server is in offline mode.
There's nothing to be done regarding this besides getting a skins plugin.

**Comment by DJDan21** [comment]
@OmerBenGera I have installed a skin plugin but it hasn't resolved my issue. My server is connected to a bungeecord server and skins are showing even without a skin plugin. I wonder something in bungeecord might have caused this issue to occur?

**Comment by OmerBenGera** [comment]
> @OmerBenGera I have installed a skin plugin but it hasn't resolved my issue. My server is connected to a bungeecord server and skins are showing even without a skin plugin. I wonder something in bungeecord might have caused this issue to occur?

The plugin fetches the skins from the player's profile data when they log in. However, if your server is in offline mode, the players will not have this type of data and therefore the plugin will not save the skin texture. But this would also make the players not have their skin, which is not the case here.

I will look into it again, I might have missed something.

**Comment by DJDan21** [comment]
Alright thanks :)

**Comment by OmerBenGera** [comment]
I looked at this again, and as I suspected, skins don't work if you don't have a skins plugin.
The skyblock server is set to offline-mode, therefore skins aren't fetched from mojang.

**Comment by DJDan21** [comment]
I have to have my skyblock server in offline mode due to it being connected to Bungeecord, well how come then some skins are showing for some players but the rest of the player's skins aren't showing

**Comment by OmerBenGera** [comment]
> I have to have my skyblock server in offline mode due to it being connected to Bungeecord, well how come then some skins are showing for some players but the rest of the player's skins aren't showing in addition to this never used to be a problem for me

As I said multiple times, if your server is in offline mode, no matter what the reason is, you must have a skins plugin installed so SSB can get the skins out of players.

**Comment by DJDan21** [comment]
I have now installed a skin restorer plugin, and it's still not saving the skins to the database, I have installed a skin restorer plugin on both my bungee-cord server and the skyblock server, I believe it could be something to do with my database being corrupted or something?

**Comment by OmerBenGera** [comment]
> I have now installed a skin restorer plugin, and it's still not saving the skins to the database, I have installed a skin restorer plugin on both my bungee-cord server and the skyblock server, I believe it could be something to do with my database being corrupted or something? What can you suggest now for me to resolve this problem?

You must have the skins plugin installed on your spigot server to SSB knows it is installed.
Then, it will listen to its events and fetch the skins data of logged in players (not offline ones).

**Comment by DJDan21** [comment]
@OmerBenGera here is my latest server log after adding a skinrestorer plugin https://pastebin.com/Qe2j5V5w

**Comment by OmerBenGera** [comment]
As I said, it will update the skins of players that log in from now on - it will not update offline players.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by DJDan21** [comment]
nothing has changed it showed skins of players that logged in before even before I added the skin restorer plugin, but here is something that I didn't mention in other messages is that this issue only occurred when randomly island randomly disappeared and skins showed correctly for online and offline players if this issue happens again I will update this post. I don't know what caused it to occur in the first place.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by DJDan21** [comment]
@OmerBenGera i'm going to close this for now, but if I manage to find the cause of why I have this bug I will either make a new report or reopen this report. I hope this is okay.
