### ISSUE TITLE
Calculation of the island's level

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/SuperiorSkyblock2#1631]
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

SuperiorSkyblock2-2022.9-b977

### Describe the bug

I currently use the CustomCobbleGen plugin. The developer of this plugin is trying to fix the problem but he can't. When I break a block with his generator the island level is instantly calculated and so if two players are on an island and one breaks blocks at the generator and the other breaks or sets blocks elsewhere on the island, he won't be able to because of the island calculation which is done instantly. Would it be possible to have an option to avoid that the calculation is done at each action with blocks? For example, the player should do /is level to update (Knowing that I have disabled the generator module by default)

### To Reproduce

Breaking blocks with the CustomCobbleGen generator and another player interacts with the blocks on the island.

**Comment by OmerBenGera** [comment]
He should not recalculate the worth of the entire island when players break generator blocks.
Instead, he can use Island#handleBlockBreak to notify the plugin about the broken block.

Not an issue, closing this.
