### ISSUE TITLE
Potion issue

### ISSUE THREAD

**Issue by Warrior1321** [BG-Software-LLC/SuperiorSkyblock2#1632]
### Minecraft's Version

1.17.1-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b977

### Describe the bug

when im making potions it counts the 3 potions i made as 12? like i brewed 3 speed potions, but it counted as 12 towards the /is missions

### To Reproduce

i made a potion island mission and then when i was testing it instead of it counting ad 3 potions it would count it as 12 towards the island mission, but lets say if i needed 25 potions, and i did 3 brews of 3, that would count as 36 potions brewed even tho i only did 9 in total, but it still wouldn't complete the island missions

**Comment by OmerBenGera** [comment]
Please upload your mission to pastebin and send a link to it here.

**Comment by Warrior1321** [comment]
https://pastebin.com/cVyW54x6 - Brewing mission file

**Comment by OmerBenGera** [comment]
The placeholder `{0}` shows the percentage of completion, and that might what confuses you.
Try replacing the placeholder with `{1}`, let me know if it shows the correct values.

**Comment by Warrior1321** [comment]
Thank you, that fixed it, going to make another ticket for brewing tho as i setup requirement but it isnt working
