### ISSUE TITLE
Island Creating Bug

### ISSUE THREAD

**Issue by DennisSquad1** [BG-Software-LLC/SuperiorSkyblock2#1634]
### Minecraft's Version

this server is running Paper version git-Paper-442 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 5cc78f2)

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b977
Dev build

### Describe the bug

I have created a schematica of a custom island. I changed the schematica in the config file. If i create an island the server gets an error and its taking like 2 minuts before the island is created

Log: https://paste.learnspigot.com/mojuwoboze.md

### To Reproduce

Create a schematica and create a island with that schematica

### Additional Information

Logs: https://paste.learnspigot.com/mojuwoboze.md

**Comment by OmerBenGera** [comment]
Contact JetsMinions regarding this
It seems as they load chunks when SSB creates a new island, causing this issue to occur
