### ISSUE TITLE
Nether portals not working properly.

### ISSUE THREAD

**Issue by GreenedDev** [BG-Software-LLC/SuperiorSkyblock2#1637]
### Minecraft's Version

git-Paper-1620 (MC: 1.12.2)

### Plugin's Version

2022.9-b977

### Describe the bug

creating portal is useless. when i go in it it just loading loading (dont mean loading world or something just nether portal's window is moving) and nothing.

### To Reproduce

i just created portal and went in it first time with gamemode creative. then i thought i just cannot go in nether with gmc and switched to gamemode survival. still nothing. cant access nether.

### Additional Information

[config.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10981452/config.zip)

**Comment by OmerBenGera** [comment]
You need to enable the nether and end worlds first in the config file before you'll be able to access them.
Look for the `worlds` section in the config file and enable nether and end worlds.
Also, if the worlds are not unlocked by default for islands, you'll have to unlock them by running `/is admin unlockworld`
