### ISSUE TITLE
Bank interest

### ISSUE THREAD

**Issue by SkyWaves123** [BG-Software-LLC/SuperiorSkyblock2#1638]
### Minecraft's Version

This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-2022.9-b977.jar

### Describe the bug

When setting bank interest to 1% it gives the player 0.01$ no matter the money he has in the bank

### To Reproduce

set bank interest to 1%

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
If I have enough money in the island bank, I'll get more from the interest task, even if it's set to 1%.
If you have less than 1$ in your bank, the plugin will give you interest as you had 1$ in the bank, which would end up giving you 0.01$ - maybe that's the case?

**Comment by SkyWaves123** [comment]
ive updated the plugin and now it even weirder. The interest is 1% and i have in the bank 20000$. The first day i got 200$ which is good. The second day i got 202$. The third 204 , fourth 206 and so on.

**Comment by OmerBenGera** [comment]
> ive updated the plugin and now it even weirder. The interest is 1% and i have in the bank 20000$. The first day i got 200$ which is good. The second day i got 202.00$. The third 204.02 , fourth 206.06 and so on.

Sounds good to me.
You get 1% of the balance at the time you get the interest. On the first day you had 20,000, which 1% of it is 200.
On the second day you had 20,200, which 1% of it is 202. The third day you had 20,402, which 1% of it is 204.02.

**Comment by SkyWaves123** [comment]
oh yeah sorry my bad. i will open a new issue if the first issue happenes again
