### ISSUE TITLE
Bank interest ceases to accrue after some time.

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1639]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

977

### Describe the bug

Bank interest ceases to accrue after some time. No errors, just every day in bank appears new log with interest and removes all previous.

### To Reproduce

Happens randomly

**Comment by OmerBenGera** [comment]
I don't understand what the bug is.
Please give more information.

**Comment by exzolink** [comment]
> I don't understand what the bug is. Please give more information.

https://imgur.com/a/qMrQCMK

First screen last server transaction, second screen last transaction in general

**Comment by OmerBenGera** [comment]
I don't understand what the bug is.

**Comment by exzolink** [comment]
Bank interest stop working for some islands after some time

**Comment by OmerBenGera** [comment]
> Bank interest stop working for some islands after some time

When islands are loaded from the database, the bank interest will start again if it can. Otherwise, it will start it later, when it should. Therefore, by restarting you'll guarantee that the bank interest will run eventually.

If you have placeholders plugin, you can check the seconds left until the next bank-interest by parsing `%superior_island_bank_next_interest%`

**Comment by exzolink** [comment]
> 

I know about it, but issue still occurs

**Comment by OmerBenGera** [comment]
> > 
> 
> I know about it, but issue still occurs

What does the placeholder show for the broken island?

**Comment by exzolink** [comment]
> > > 
> > 
> > 
> > I know about it, but issue still occurs
> 
> What does the placeholder show for the broken island?

Remaining time as for all other islands

**Comment by OmerBenGera** [comment]
> > > > 
> > > 
> > > 
> > > I know about it, but issue still occurs
> > 
> > 
> > What does the placeholder show for the broken island?
> 
> Remaining time as for all other islands

Does it go down after some time?

**Comment by exzolink** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I know about it, but issue still occurs
> > > 
> > > 
> > > What does the placeholder show for the broken island?
> > 
> > 
> > Remaining time as for all other islands
> 
> Does it go down after some time?

Yes, it works absolutely fine.

**Comment by OmerBenGera** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > I know about it, but issue still occurs
> > > > 
> > > > 
> > > > What does the placeholder show for the broken island?
> > > 
> > > 
> > > Remaining time as for all other islands
> > 
> > 
> > Does it go down after some time?
> 
> Yes, it works absolutely fine.

Then it sounds like it's working.
What is the bug?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
