### ISSUE TITLE
Circular plugin loading detected!

### ISSUE THREAD

**Issue by TheMartyCZ** [BG-Software-LLC/SuperiorSkyblock2#1640]
### Minecraft's Version

Latest Pufferfish 1.19.3

### Plugin's Version

![image](https://user-images.githubusercontent.com/45405349/225634667-c31f17da-4b70-46d5-bd97-fc7212ff92dc.png)

### Describe the bug

![image](https://user-images.githubusercontent.com/45405349/225634733-ad8f2542-1382-42da-b281-9f0880895c3f.png)

[crash-2023-03-16_14.36.57-server.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10991414/crash-2023-03-16_14.36.57-server.txt)

### To Reproduce

start server with latest dev build

**Comment by OmerBenGera** [comment]
Update paper, they already fixed it.
This is not an issue with SSB.

**Comment by TheMartyCZ** [comment]
> Update paper, they already fixed it. This is not an issue with SSB.
Okay, the problem is only with the SS2 plugin, so I thought it was a bug. :) Thanks!

**Comment by TheMartyCZ** [comment]
> Update paper, they already fixed it. This is not an issue with SSB.

@OmerBenGera 
I tried the latest Paper and the error is still there.

![image](https://user-images.githubusercontent.com/45405349/225813692-ca81a79b-bbcb-4ebe-b04d-ed803062517b.png)

**Comment by OmerBenGera** [comment]
> > Update paper, they already fixed it. This is not an issue with SSB.
> 
> @OmerBenGera I tried the latest Paper and the error is still there.
> 
> ![image](https://user-images.githubusercontent.com/45405349/225813692-ca81a79b-bbcb-4ebe-b04d-ed803062517b.png)

Use the legacy loading then, as said in the console
