### ISSUE TITLE
island missions potion bug

### ISSUE THREAD

**Issue by Warrior1321** [BG-Software-LLC/SuperiorSkyblock2#1646]
### Minecraft's Version

1.17.1-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b984

### Describe the bug

I am brewing a potion and in my potion mission config for tier 2 i have https://pastebin.com/mAmXKVTn which has the requiredmissions on however when brewing a potion it counts it for all tiers that have this requirement on  

### To Reproduce

brew potions with multiple tiers 

https://pastebin.com/rsieXG8v - TIER 1
https://pastebin.com/mAmXKVTn - TIER 2

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
