### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Leylahennessey** [BG-Software-LLC/SuperiorSkyblock2#1647]
### Minecraft's Version

1.19.2 paper spigot

### Plugin's Version

1.19.2

### Describe the bug

The plugin was fine when i first installed it but recent it has been crashing the server so i had to disable it. The server will constantly start then restart in repetition.. no new plugins have been added or anything

### To Reproduce

Was hoping for some advice myself

**Comment by OmerBenGera** [comment]
Please upload your logs file to pastebin and send a link to it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
