### ISSUE TITLE
The is level not work correctly (Can it be traced back to shopguiplus?)

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1648]
### Minecraft's Version

1.19.3 purpur

### Plugin's Version

#989 

### Describe the bug

The plugin not load correctly the is level. It is not loaded neither from the config nor from the is level. Only blocks are loaded spawners don't.

### To Reproduce

1) Wait for the server to show Done. So the server loads the shopguiplus correctly. I understand that the is level is not loaded by shogpuiplus directly. But in the config it is set by default that the is level is half the value.
2) once inside take any spawner (that is not zombies because it loads it)
3)For example. Note that for each cow spawner only the worth is updated but not the is level.
4) Funny thing, if you do is admin reload it seems to load it correctly. 

![image](https://user-images.githubusercontent.com/73421268/227727995-be2b547c-4784-4e96-8286-a3be3d81fe2f.png)

if you look closely it's not half of how it's set up in the config.yml.

Warning: By default it should take the prices from shopguiplus as I set since, I repeat, the is level is half of the worth. So indirectly it is also shopguiplus. But for correctness I also set the levels.yml file as you told me. And it doesn't work anyway. I will send you the files below to show you the evidence. With video demonstration of what happened

### Additional Information

Levels.yml: https://pastebin.com/zvvQgsTh

Config.yml https://gist.github.com/Distolfix/17c91c9974c09a499aa0e1a4c2d13acc 

Look closely at line 145. worth/2 so in theory it should still take shopguiplus prices. And yet levels.yml doesn't work either

![image](https://user-images.githubusercontent.com/73421268/227728578-10059802-efa4-4ad1-897d-bed6e8dda20e.png)

![image](https://user-images.githubusercontent.com/73421268/227728606-af7cc2c9-9896-41ee-b38b-a1529c6b4b00.png)

I'm sending you the video for accuracy. Hoping you understand this issue.

**Comment by Distolfix** [comment]
https://www.youtube.com/watch?v=vW4R3UA24-k

**Comment by OmerBenGera** [comment]
You use incorrect material names.
`MOB_SPAWNER` should be replaced with `SPAWNER`.

Regarding worth not being detected.
Use `/is admin debug get_worth` and then run `/is value` while holding a spawner that does not work. Let me know what is printed to your console.

**Comment by OmerBenGera** [comment]
> 8:59:47 INFO]: WhiteOmbrah_ issued server command: /is value [18:59:47 INFO]: [SuperiorSkyblock2] BlockValuesManagerImpl::getBlockWorth {SPAWNER:PIGLIN} [18:59:47 INFO]: [SuperiorSkyblock2] BlockValuesManagerImpl::getBlockWorth Return Price {1200000.0}

Seems like the worth value is returned correctly for the spawner.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Distolfix** [comment]
I used the level.yml you can close this
