### ISSUE TITLE
Legacy Support Material

### ISSUE THREAD

**Issue by NoopyyGaming** [BG-Software-LLC/SuperiorSkyblock2#1649]
### Minecraft's Version

Version: 1.19.4
Jar: pufferfish-paperclip-1.19.4-R0.1-SNAPSHOT-reobf.jar
(this is my local server)

### Plugin's Version

Plugin version: 2023.1
It is not a dev build but the latest stable version.

### Describe the bug

The exact little issue, is due to an legacy material and/or data. I'm getting that warning message from the plugin.
I'll put a screen of it down below.

### To Reproduce

When i'm starting the server, the plugin is loading as it should and that warning message always appear.
I've tried to take off the few plugins i also have to see which one is doing this but none does, only SuperiorSkyblock.

### Additional Information

![SKYBLOCK](https://user-images.githubusercontent.com/33123515/227738816-a909977f-52fe-472a-a33a-d5e285e04e94.PNG)

**Comment by OmerBenGera** [comment]
Can be ignored.
Sadly there is no fix for this.
