### ISSUE TITLE
weirdest bug ever with mob on different world

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1650]
### Minecraft's Version

Current: git-Purpur-1834 (MC: 1.19.2)*
Previous: git-Purpur-1749 (MC: 1.19.1)
* You are 24 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

2022.9 Stable

### Describe the bug

Monsters that are in the nether can hit players in the overworld

### To Reproduce

Don't know how to reproduce that. My player report it without any more info. He thinks it's related to the coordinates.

### Additional Information

Video show : https://cdn.discordapp.com/attachments/1089641485059772528/1089641551887614033/2023-03-26_22-04-46.mp4

**Comment by OmerBenGera** [comment]
Upload the video to an online streaming service and send a link to it here.

**Comment by SwartZCoding** [comment]
> Upload the video to an online streaming service and send a link to it here.

https://youtu.be/-bwe1N9sTTU

**Comment by OmerBenGera** [comment]
This is probably not a bug with SSB, as its your spigot server that handles the worlds.
Try it on a Paper server with only SSB installed, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> I can try it later today. But i use purpur so i don't think this is a spigot issue ^^

It probably is as Purpur handles the worlds on your server.
Try it with regular Spigot or Paper and with only SSB installed and report back if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I'd like if you could test it on Paper, just to make sure this is indeed not an issue with Purpur.
The issue is that SuperiorSkyblock (or technically any other plugin on the market) does not actually handle worlds. It uses the Bukkit API to create the islands world and that's it - the rest is handled by your server software. Therefore, my guess is that it is Purpur that causes this weird behavior.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
If the issue continues, let me know.
