### ISSUE TITLE
BlockUnstackEvent dont cancel BlockBreakEvent

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1653]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

989

### Describe the bug

If BlockUnstackEvent is cancelled, the block still breaks and only 1 piece drops

### To Reproduce

Write a code which cancells any BlockUnstackEvent and break stacked block

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
