### ISSUE TITLE
Surfer crashes on startup when changing at least 1 character in confing.yml SSb2

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1654]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

There is not /is admin version command. On file "2023"

### Describe the bug

The server with the skyblock with default settings starts. I turn off the server and try to make some configuration changes via SublimeText/Notepad++ and start the server. However, after changing at least one character in config.ynl, the server crashes on startup. (I did not touch anything except the configuration of this SSb2). If you delete config.yml and run it, the server will start. Encoding in text editors UTF-8. I noticed that when crashing, there is a complaint about one plugin. I removed this plugin. And now it's complaining about EssentialsX! 

My plugins
![image](https://user-images.githubusercontent.com/126126362/228682136-9da174b0-9142-4b41-8db6-b246527c206c.png)

I am attaching the log file
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11106049/latest.log)

### To Reproduce

Setup server with PurPur 1.19.3
Paste plugin in the plugins folder
start server (will start)
stop sever
change config.yml of SSB2
start server (will not start)

**Comment by OmerBenGera** [comment]
Your spawn location is in invalid world.
Make sure you have spelled it correctly.

**Comment by Evalutik** [comment]
> Your spawn location is in invalid world. Make sure you have spelled it correctly.

I mean world's name

**Comment by OmerBenGera** [comment]
> > Your spawn location is in invalid world. Make sure you have spelled it correctly.
> 
> I found and changed, but it's strange why it didn't work with default settings. However, could you tell me what is the difference between these two parameters in the configuration and what does each of them do?
> 
> 
> ![image](https://user-images.githubusercontent.com/126126362/228766370-6623fb2f-b432-4ddc-a0e3-12f777d1673f.png) 2) ![image](https://user-images.githubusercontent.com/126126362/228766359-ae06618d-5848-4140-bde3-9d5844949831.png)

Probably a deprecated field.
I will look into it.
