### ISSUE TITLE
Is settings pvp not work!

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1655]
### Minecraft's Version

1.19.3 and 1.19.4 tested

### Plugin's Version

989

### Describe the bug

When you activate PVP mode on is settings the pvp isn't work on island

### To Reproduce

https://user-images.githubusercontent.com/73421268/228686053-87afd7a0-31f8-4ac7-97e1-bf7d366f5533.mp4

### Additional Information

Vanilla files. Test server with default config.

**Comment by OmerBenGera** [comment]
Upload your config to pastebin and send a link to it here

**Comment by Distolfix** [comment]
It's the config that comes out by default

**Comment by Distolfix** [comment]
I also wrote it to you in the video.  it's all by default
