### ISSUE TITLE
Island level doesn't calculate according to island-level-formula

### ISSUE THREAD

**Issue by playsenge** [BG-Software-LLC/SuperiorSkyblock2#1658]
### Minecraft's Version

git-Purpur-1735 (MC 1.19)

### Plugin's Version

2023.1-b990

### Describe the bug

Hi,
I have a problem when trying to make a proper island level calculation based on worth formula.

**Scenario 1**
`island-level-formula: '{}'`
Island worth = 0, Island level = 34000 (Expected result: Island level = 0)
Island worth = 17560, Island level = 52220 (Expected result: Island level = 17560)

**Scenario 2**
`island-level-formula: '{} / 4'`
Island worth = 0, Island level = 0
Island worth = 17560, Island level = 0 (Expected result: Island level = 4390)

So yeah, the formula doesn't match at all the real level. Am I doing something wrong? (I tried it both with the javascript java 15+ calculation module and without, also tried enabling/disabling negative island worth/level, doesn't change anything)

### To Reproduce

Install SuperiorSkyBlock2, add some block worths into worth.yml, set a formula, see mismatching level and worth

### Additional Information

![image](https://user-images.githubusercontent.com/40773107/229281671-a1a9d34c-209d-4cbe-b2d4-d6a517db59cf.png)
Screenshot taken with formula "{} / 4"

**Comment by OmerBenGera** [comment]
Run `/is value` while holding an item, check if the level is correct.
Island level is calculated per block, not for the entire island.

**Comment by Distolfix** [comment]
I had your same problem which I reported to omar. See: https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1648

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
