### ISSUE TITLE
Upgrading crop growth (and possibly other island upgrades) does not work until the server is restarted or until island chunks are unloaded

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1660]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

2023

### Describe the bug

Crop growth multiplier only works after a server restart or after all players re-enter the island world. I don't know how it 's going with other upgrades, but if a player is upgrade crop growth to x100 and he plays solo, then the crop will grow in the same way as from the very beginning until the server is restarted or until the player rejoins his island. If there are two players on the island, then both of them must leave and enter for the rapid growth to work. Many players think that pumping does not work therefore. This will most likely also work with most of the other island upgrades, but these are harder to test.

### To Reproduce

1) In the plugins\SuperiorSkyblock2\modules\upgrades\config.yml change the growth multiplier for the last level of pumping to 100 or 200 or 400
2) Create new islend
3) Plant a crop and see how fast it grows without a growth boost
4) Pump crop growth to the maximum level
5) See how fast the crop is growing now (nothing has changed)
6) Relogin to the server
7) See how fast the crop is growing now (Now the multiplier works and the crop will grow 100 or 400 times faster than usual)
8) This will most likely also work with most of the other island upgrades, but these are harder to test.

### Additional Information

![image](https://user-images.githubusercontent.com/126126362/229304938-114c84ce-11bf-4f63-984f-46c427286fa8.png)

Please, fix this or help ;(

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
I created a new island, then ran `/is admin setcropgrowth <player-name> 1000` and it worked.
Does it work for you when you run the command?

**Comment by Kocimietka7192** [comment]
I have similar symptoms, crop-grow does not work at all. Even using the command that was pointed out by the author of the answer above, or restarting the mode does not help.

**Comment by OmerBenGera** [comment]
> I have similar symptoms, crop-grow does not work at all. Even using the command that was pointed out by the author of the answer above, or restarting the mode does not help. b994, oneblock b62 pufferfish-65
> 
> upgrades.yml
> 
> ```
>   crop-growth:
>     '1':
>       price: 40000.0
>       price-type: Money
>       crop-growth: 1
>       commands:
>       - island admin setupgrade %player% crop-growth 2
>       - island admin msgall %player% &8• &7Przyśpieszyłeś wzrost plonów
>         o &a15%&7!
>     '2':
>       price: 80000.0
>       price-type: Money
>       crop-growth: 5
>       commands:
>       - island admin setupgrade %player% crop-growth 3
>       - island admin msgall %player% &8• &7Przyśpieszyłeś wzrost plonów
>         o &a20%&7!
>     '3':
>       price: 0.0
>       price-type: Money
>       crop-growth: 10
>       commands:
>       - island admin msg %player% &8• &7Osiągnąłeś &cmaksymalny poziom
>         &7tego ulepszenia!
> ```

Try setting a higher crop growth multiplier using a command, around 1000.
Let me know if it still doesn't work.

**Comment by Evalutik** [comment]
> It seems to work fine for me. I created a new island, then ran `/is admin setcropgrowth <player-name> 1000` and it worked. Does it work for you when you run the command?

I don't have access to a computer right now, but I'll also try it on a completely new server in 3 days and let you know the result

**Comment by Kocimietka7192** [comment]
> 
/is admin setcropgrowth <player-name> 1000

using the above command does not change anything in terms of changing the growth rate of crops (i.e. pumpkins, melons, etc.)

**Comment by OmerBenGera** [comment]
> `/is admin setcropgrowth <player-name> 1000`
> 
> using the above command does not change anything in terms of changing the growth rate of crops (i.e. pumpkins, melons, etc.)

Are you able to replicate the issue on a server with only SSB installed?

**Comment by Kocimietka7192** [comment]
> > `/is admin setcropgrowth <player-name> 1000`
> > using the above command does not change anything in terms of changing the growth rate of crops (i.e. pumpkins, melons, etc.)
> 
> Are you able to replicate the issue on a server with only SSB installed?

It didn't do anything, it continued the same way.

**Comment by OmerBenGera** [comment]
Try replicating the issue on a server with only SSB installed.

**Comment by Evalutik** [comment]
> Try replicating the issue on a server with only SSB installed.

I recorded a video of this error being reproduced on a server without third party plugins. Please take a look at the video below.

https://youtu.be/ADar3s9ypO8

Here we can see that the problem remained through the command /island admin setupgrade <player> crop-growth <lvl> . This means that accelerated growth starts working only when you relog to the server. We can also see that the /is admin setcropgrowth <player> 400 command works correctly. However, this does not make sense, because the accelerated growth leveling system works based on the /island admin setupgrade command. Therefore, it would be good to fix the original /island admin setupgrade command

**Comment by OmerBenGera** [comment]
After you change the upgrade, run `/is admin show` to make sure the crop growth was actually been updated.
Also, if it works by running `/is admin setcropgrowth`, then it means the crop growth multiplier works, and it might be a faulty configuration or the plugin not updating the values correctly - that's why you must run `/is admin show` to ensure the multiplier was actually been updated to your island.

**Comment by Evalutik** [comment]
> После того, как вы измените обновление, запустите `/is admin show`, чтобы убедиться, что рост урожая действительно был обновлен. Кроме того, если он работает при запуске `/is admin setcropgrowth`, это означает, что множитель роста урожая работает, и это может быть неисправная конфигурация или плагин, который не обновляет значения правильно — поэтому вы должны запустить, `/is admin show`чтобы убедиться, что множитель был действительно обновлен для вашего острова.


Look at the screenshot. After pumping, the growth rate is set, but the plants do not start growing faster

![image](https://user-images.githubusercontent.com/126126362/231202505-872f2fb2-bd6d-4e4e-b484-f52ec14c3b84.png)

By the way, what do the green signs of infinity next to it mean?

**Comment by Evalutik** [comment]
> After you change the upgrade, run `/is admin show` to make sure the crop growth was actually been updated. Also, if it works by running `/is admin setcropgrowth`, then it means the crop growth multiplier works, and it might be a faulty configuration or the plugin not updating the values correctly - that's why you must run `/is admin show` to ensure the multiplier was actually been updated to your island.

I also attach my main config.txt:

[config.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11201879/config.txt)

And the upgrade config file from plugins/SSB2/moduls/upgrades/config.yml

[file from modules-upgrade-config.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11201891/file.from.modules-upgrade-config.txt)

**Comment by Kocimietka7192** [comment]
> Try replicating the issue on a server with only SSB installed.

are installed only SuperiorSkyblock2, Viabackwards and viaversion plugins. Further setcrop does not work.

**Comment by Evalutik** [comment]
> 

Yes exactly. The bug only occurs when using` /is admin setupgrade`. When `/is admin setcropgrowth` everything works as it should.

**Comment by Evalutik** [comment]
> > > After you change the upgrade, run `/is admin show` to make sure the crop growth was actually been updated. Also, if it works by running `/is admin setcropgrowth`, then it means the crop growth multiplier works, and it might be a faulty configuration or the plugin not updating the values correctly - that's why you must run `/is admin show` to ensure the multiplier was actually been updated to your island.
> > 
> > 
> > Look at the screenshot. After pumping, the growth rate is set, but the plants do not start growing faster
> > ![image](https://user-images.githubusercontent.com/126126362/231203408-4a347c2a-a9bc-46df-a877-594148cc353e.png)
> > By the way, what do the green signs of infinity next to it mean?
> 
> It means that the value next to the symbol is synced with an upgrade and was not set using an admin command. So just to confirm that I understand correctly, it only happens if you use the `/is admin setupgrade` (or upgrade using `/is rankup`), but it works if you change the crop growth with `/is admin setcropgrowth` - right?

Yes exactly. The bug only occurs when using` /is admin setupgrade`. When `/is admin setcropgrowth` everything works as it should.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
