### ISSUE TITLE
Piston TPS Problem

### ISSUE THREAD

**Issue by Sueseba** [BG-Software-LLC/SuperiorSkyblock2#1663]
### Minecraft's Version

Purpur 1.16.5

### Plugin's Version

Latest Stable version

### Describe the bug

TPS PROBLEM

https://timings.aikar.co/dev/?id=fc68098eb4224c7ea97d76b05537e6f3#timings

### To Reproduce

TPS PROBLEM

https://timings.aikar.co/dev/?id=fc68098eb4224c7ea97d76b05537e6f3#timings

**Comment by OmerBenGera** [comment]
I can clearly see a performance issue with pistons, seems to be related to missions.
In order to better understand what the exact issue is, I'll need a spark profiler to better analyze what is going on.
Please take a spark profiler and send a link to it here.

**Comment by Sueseba** [comment]
https://spark.lucko.me/idJM2RWIhi

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it helps.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to work.
If the issue continues let me know
