### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by JoshhDevv** [BG-Software-LLC/SuperiorSkyblock2#1664]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.1

### Describe the bug

Console Log 
https://pastes.dev/Ak3wCsDzP8

Ingame Error 
https://cdn.discordapp.com/attachments/554282577322704896/1092264761967788103/image.png

### To Reproduce

when i use /island create (name) it takes me to the select island screen once i select the island it says 'An error occurred while creating your island. Please contact the administrator to investigate the issue'

**Comment by JoshhDevv** [comment]
I was using 1.19.4 but now changed but would like to use 1.19.4 if your able to resolve

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OmerBenGera** [comment]
Send me the result of /version.
Saying "1.19.4" is not enough. I need to know the exact spigot jar you use.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by JoshhDevv** [comment]
Hey sorry this was resolved, by my system admin sorry about no response

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OmerBenGera** [comment]
Glad it was solved :)
