### ISSUE TITLE
Circular plugin loading error

### ISSUE THREAD

**Issue by Kopekk** [BG-Software-LLC/SuperiorSkyblock2#1665]
### Minecraft's Version

1.19.4 purpur build 1952

### Plugin's Version

2023.1

### Describe the bug

Server fails to load when circular plugin loading is disabled, just wanted to let you know

### To Reproduce

Have the plugins listed in latest.log
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11141767/latest.log)

**Comment by OmerBenGera** [comment]
Upload the logs file to pastebin and send a link to it here.

**Comment by Kopekk** [comment]
https://mclo.gs/fJjf9NF
logs from startup before enabling legacy loading

**Comment by OmerBenGera** [comment]
Report it over KGenerators , not related to SuperiorSkyblock.
They have loadbefore on SuperiorSkyblock, but then one of their dependencies depends on SuperiorSkyblock.

**Comment by Kryniowesegryderiusz** [comment]
For anyone who comes here looking for an answer: KGenerators have special addon for running it with SS2, check the KGen wiki

**Comment by tuanhp0** [comment]
> 

what link?
