### ISSUE TITLE
Mob loot multiplier less than 1 does not affect on a loot from Cows, Pigs....

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1666]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

2023

### Describe the bug

Mob loot multiplier less than 1 (for example 0.5) does not affect on a loot from Cows, Pigs, Skeletons and probably other mobs. This works well for zombies and slugs for example. I thought it might not work for those mobs that can drop two or more different items after killing them, but the pig does not fit this trait. 

In addition, for some reason, I have skeletons burning in a completely closed cave during the day on the island. To what can this be sacred?

### To Reproduce

1) Set in the main file (config.yaml) and in the swap file (moduls/upgrades/config.yml) spawner-rates: 0.2 or any other number less than 1
2) Restart server
3) Create a new island
4) Kill about 20 mobs and compare the loot table with a regular minecraft table (or test the same with spawner-rates: 1)
5) You can see there is no difference

### Additional Information

![image](https://user-images.githubusercontent.com/126126362/229611936-aa8e6806-a05d-4908-a83e-20f8604d9fb2.png)

**Comment by OmerBenGera** [comment]
The plugin will divide the spawn-delay when a mob spawns by the spawner rate.
Which means, by setting it to 0.3, you make it slower. However, this value cannot be higher than the max-spawn-delay, therefore by setting it as low as 0.3 will make no affect.
In general, slowing down spawners like this will not make a lot of difference as the regular spawn-delay is many times close to the max-spawn-delay of the spawner.

I recommend making the spawner-rates higher than 1 for better experience.

About the other bug, open a new issue on github.

**Comment by Evalutik** [comment]
> 

I originally had a different question in mind, but I'll explain it later in another new issue on github. To begin with, I would like to clarify with the speed of the appearance of monsters from spawners.

I can't find "max-spawn-delay" in any of the files. Could you elaborate on what exactly you mean? 

I did not understand if I can somehow reduce the spawn rate of mobs from spawners? The default value is 1, right? But a value below 1 doesn't work?

**Comment by OmerBenGera** [comment]
> > 
> 
> I originally had a different question in mind, but I'll explain it later in another new issue on github. To begin with, I would like to clarify with the speed of the appearance of monsters from spawners.
> 
> I can't find "max-spawn-delay" in any of the files. Could you elaborate on what exactly you mean?
> 
> I did not understand if I can somehow reduce the spawn rate of mobs from spawners? The default value is 1, right? But a value below 1 doesn't work?

The `max-spawn-delay` is a vanilla NBT tag assigned to spawners, which is the maximum delay (in ticks) that a spawner can have until its next time it spawns an entity.
You shouldn't use the multiplier to decrease spawn rate of spawners. Instead, you can have other plugins that manage spawners, there you can play with the `min-spawn-delay` and `max-spawn-delay` to make spawner rates fit your server needs.

**Comment by Evalutik** [comment]
> > > 
> > 
> > 
> > I originally had a different question in mind, but I'll explain it later in another new issue on github. To begin with, I would like to clarify with the speed of the appearance of monsters from spawners.
> > I can't find "max-spawn-delay" in any of the files. Could you elaborate on what exactly you mean?
> > I did not understand if I can somehow reduce the spawn rate of mobs from spawners? The default value is 1, right? But a value below 1 doesn't work?
> 
> The `max-spawn-delay` is a vanilla NBT tag assigned to spawners, which is the maximum delay (in ticks) that a spawner can have until its next time it spawns an entity. You shouldn't use the multiplier to decrease spawn rate of spawners. Instead, you can have other plugins that manage spawners, there you can play with the `min-spawn-delay` and `max-spawn-delay` to make spawner rates fit your server needs.

OK, got it. That is, to pump the frequency of appearance of mobs from spawners by default, I need to use values ​​for `spawner-rates` ` >=1`? Then the speed of spawning of mobs on the island from spawners will increase, right?

But I can use non-integer values ​​like `1.5` right?

**Comment by OmerBenGera** [comment]
> > > > 
> > > 
> > > 
> > > I originally had a different question in mind, but I'll explain it later in another new issue on github. To begin with, I would like to clarify with the speed of the appearance of monsters from spawners.
> > > I can't find "max-spawn-delay" in any of the files. Could you elaborate on what exactly you mean?
> > > I did not understand if I can somehow reduce the spawn rate of mobs from spawners? The default value is 1, right? But a value below 1 doesn't work?
> > 
> > 
> > The `max-spawn-delay` is a vanilla NBT tag assigned to spawners, which is the maximum delay (in ticks) that a spawner can have until its next time it spawns an entity. You shouldn't use the multiplier to decrease spawn rate of spawners. Instead, you can have other plugins that manage spawners, there you can play with the `min-spawn-delay` and `max-spawn-delay` to make spawner rates fit your server needs.
> 
> OK, got it. That is, to pump the frequency of appearance of mobs from spawners by default, I need to use values ​​for `spawner-rates` ` >=1`? Then the speed of spawning of mobs on the island from spawners will increase, right?
> 
> But I can use non-integer values ​​like `1.5` right?

You should be able to use 1.5

**Comment by OmerBenGera** [comment]
I am closing this for now, as there doesn't seem to be a bug here.
