### ISSUE TITLE
CloudSpawners not working with ss2 block limit

### ISSUE THREAD

**Issue by Josh-wa** [BG-Software-LLC/SuperiorSkyblock2#1667]
### Minecraft's Version

1.19.2

### Plugin's Version

cloudspawners latest

### Describe the bug

CloudSpawners isnt getting limited once place on islands. Currently have island missions set to place spawners however no matter the type of spawner it can be placed

### To Reproduce

place a spawner once you set the blocklimit of spawner:blaze to 1 then using cloud spawners
 try to place another mob.

**Comment by OmerBenGera** [comment]
They might overwrite the way they handle spawners placement.
Talk with them about adding support for SuperiorSkyblock. They should call Island#handleBlockPlace if they overwrite the spawner placement method, so SSB can know about the placement of spawners.
