### ISSUE TITLE
Island Top not sorting correctly after server reboot

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/SuperiorSkyblock2#1669]
### Minecraft's Version

1.19.3 Paper-448

### Plugin's Version

SuperiorSkyblock2-2023.1-b990.jar

### Describe the bug

My island top is not remaining in the correct order with most island values least it is not staying in that order upon server reboot, if I get the island back to the correct order and then I reboot my server it automatically goes back to not being sorted based on the true island values.

### To Reproduce

not exactly sure how to reproduce this issue tbh

### Additional Information

![image](https://user-images.githubusercontent.com/19984107/229842780-b6ec6a13-9531-4204-a79e-c49e35c42407.png)
This is how my island top returns after a server reboot

![image](https://user-images.githubusercontent.com/19984107/229844486-955b5ca1-3401-41b1-8708-2d7365692e8e.png)
this is how it should be if the island worth actually

**Comment by OmerBenGera** [comment]
Your report is lacking a lot of information.
The screenshots show nothing.

**Comment by DJDan21** [comment]
Here is my latest server log https://pastebin.com/zFi77iD2

**Comment by OmerBenGera** [comment]
Do you have your worth values synced with SGP?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now.

**Comment by DJDan21** [comment]
@OmerBenGera even after installing the latest fixed it still hasn't resolved the issue

**Comment by OmerBenGera** [comment]
> @OmerBenGera even after installing SuperiorSkyblock2-2023.1-b993, it hasn't resolved the issue

Let me know if it happens on a server with only SSB installed.

**Comment by DJDan21** [comment]
@OmerBenGera after updating to SuperiorSkyblock2-2023.1-b994 update it has fixed the issue thanks

**Comment by OmerBenGera** [comment]
Awesome, glad it works now!
