### ISSUE TITLE
Island Admin Info Issue.

### ISSUE THREAD

**Issue by PixelButix** [BG-Software-LLC/SuperiorSkyblock2#1673]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.1-b998

### Describe the bug

Console Log:
https://prnt.sc/nE_NA-j8vIpN
In-Game Error:
https://prnt.sc/d2hCjq_adcDF

### To Reproduce

When I use /is admin info (Player) i got this error "An internal error occurred while attempting to perform this command" when I am using.

**Comment by OmerBenGera** [comment]
You have two same block limits with different values or something like this.
Make sure you avoid this in your configuration files (upgrades, config, etc.)

Let me know if it still occurs after you resolve it.

**Comment by PixelButix** [comment]
Nope, is still the same. i've tried to reset the config on upgrades and is still the same.

**Comment by OmerBenGera** [comment]
> Nope, is still the same. i've tried to reset the config on upgrades and is still the same.

Look at the DB for that island in the upgrades table and send a screenshot of it.

**Comment by PixelButix** [comment]
https://prnt.sc/9LP0ly0hdLC7

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works now.

**Comment by PixelButix** [comment]
Yep, now it works well!! Thank you so much <3
