### ISSUE TITLE
no possibility of visiting

### ISSUE THREAD

**Issue by Kocimietka7192** [BG-Software-LLC/SuperiorSkyblock2#1674]
### Minecraft's Version

pufferfish-65

### Plugin's Version

b994

### Describe the bug

Despite having all the permissions, "*" and opa, I am unable to teleport to islands that are excluded for guest visits. 

### To Reproduce

Just type "/tp nick" which has the island blocked for visitors.

**Comment by OmerBenGera** [comment]
You need to enable bypass mode (/is admin bypass), or give yourself explicitly the permission superior.admin.bypass.close_bypass
