### ISSUE TITLE
Unable to use boats with Use and Interact permissions on islands

### ISSUE THREAD

**Issue by George-Rowland** [BG-Software-LLC/SuperiorSkyblock2#1676]
### Minecraft's Version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### Plugin's Version

2022.9-b981

### Describe the bug

When a player is given use and interact permissions they cannot use boats despite being specified in the interactables.yml

### To Reproduce

Join an island as member, have only use and interact permissions, try to use a boat

### Additional Information

https://prnt.sc/h3foqgtEPCcX

**Comment by OmerBenGera** [comment]
Boats are not blocks but considered vehicles.
Look for the vehicle permissions, check if it works.

**Comment by OmerBenGera** [comment]
I am closing this as it doesn't seem like a bug for me.
If the issue continues let me know
