### ISSUE TITLE
Can bypass closed islands by using essentials /home

### ISSUE THREAD

**Issue by George-Rowland** [BG-Software-LLC/SuperiorSkyblock2#1677]
### Minecraft's Version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### Plugin's Version

2022.9-b981

### Describe the bug

If you set your home (using essentials homes) on an island whilst it is open you are able to teleport to this home even when the island is closed

### To Reproduce

1. /sethome at an open island
2. Close the island
3. /home and teleport to the island despite it being closed

**Comment by OmerBenGera** [comment]
SuperiorSkyblock cancels the teleportation event when the island is closed to non-accessible players.
I also tried replicating the issue myself and I cannot teleport to my home:
https://gyazo.com/22382f68f12758d61ef891afe3730dd3

Make sure the players do not have access to visit the island while it's closed and they do not have `/is admin bypass` enabled or `superior.admin.bypass.close_bypass`

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by George-Rowland** [comment]
sorry. unsure if still relevant as server is currently closed so can't check. you can feel free to close this issue

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue pops up again in the future make sure you let me know
