### ISSUE TITLE
Minecart bug - no delete minecarts

### ISSUE THREAD

**Issue by KalviPL** [BG-Software-LLC/SuperiorSkyblock2#1679]
### Minecraft's Version

Server verion 1.19.4

### Plugin's Version

2023.1 and
Dev Build #1005

### Describe the bug

I just put 10 minecraft on the island, then destroy 1 or more and can't put any more.
After typing this command, nothing happens in the console.

  minecarts-limit:
    '1':
      price: 1000000.0
      price-type: "Money"
      entity-limits:
        MINECART: 3
      commands:
        - 'island admin setupgrade %player% minecarts-limit 2'
        - 'island admin msgall %player% &7Your minecarts limit was increased to 8!'

### To Reproduce

https://gyazo.com/8bed11ccf26808b1cc88b3136f0b2178

**Comment by OmerBenGera** [comment]
What version of Spigot do you use?
I need to know the exact output of /version

**Comment by KalviPL** [comment]
> What version of Spigot do you use? I need to know the exact output of /version


https://imgur.com/3WbpiyH

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
