### ISSUE TITLE
Disabled subcommands still show in tab completions

### ISSUE THREAD

**Issue by Wupin** [BG-Software-LLC/SuperiorSkyblock2#1680]
### Minecraft's Version

Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version

### Plugin's Version

2023.1-b1005 (dev build)

### Describe the bug

basically disabled subcommands are still displayed while tab completing

### To Reproduce

just put some subcommand in config under disabled-commands and restart server then try to tab completing command

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
