### ISSUE TITLE
Interact issue with Sign & dye

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1682]
### Minecraft's Version

Current: git-Purpur-1834 (MC: 1.19.2)*
Previous: git-Purpur-1749 (MC: 1.19.1)
* You are 24 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

2023.1

### Describe the bug

When we right click on sign with Dye in the hand on others islands, the sign is edited by dye color.

### To Reproduce

Take a dye
go on enemy island
use it on a sign

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
