### ISSUE TITLE
Sounds Not Working

### ISSUE THREAD

**Issue by AlFr3on111** [BG-Software-LLC/SuperiorSkyblock2#1683]
### Minecraft's Version

1.16.5 purpur

### Plugin's Version

SuperiorSkyblock2-2023.1

### Describe the bug

when you try to create an island or change the island biome you cant hear the sounds
i didnt edit anything in the sounds everything from the plugin

Vido Link: https://cdn.discordapp.com/attachments/554282577322704896/1095684425859215460/unknown_2023.04.12-14.15.mp4

### To Reproduce

idk

### Additional Information

https://cdn.discordapp.com/attachments/554282577322704896/1095684425859215460/unknown_2023.04.12-14.15.mp4

i cant upload the video size is 30MB

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
