### ISSUE TITLE
PLugin doesn't work

### ISSUE THREAD

**Issue by elkoyofficial** [BG-Software-LLC/SuperiorSkyblock2#1684]
### Minecraft's Version

Minecraft 1.19.4

Server.jar - paper-1.19.4-510

### Plugin's Version

2023.1

### Describe the bug

Can't create new islands or access old islands.
 https://pastebin.com/hEeZkpuF

### To Reproduce

Install the plugin and try to create an island

**Comment by OmerBenGera** [comment]
Update to latest dev build, already been fixed
