### ISSUE TITLE
can't create island on latest dev build

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1686]
### Minecraft's Version

1.19.3 pufferfish

### Plugin's Version

b7

### Describe the bug

I upgraded to latest dev build and player can't create an island, it says name already exist, but I disabled name requirement 

### To Reproduce

- disable name requirement on island creation
- put only 1 island schematic
- disable "one item menu"
_so you just need to do /is to create an island_
- it doesn't create the island

### Additional Information

I didn't try it myself as I'm at work, but I had to downgrade to dev build b3 and it's working for my new players

**Comment by WarnDa** [comment]
> Fixed in latest dev build

Not fixed, I can't create an island, it says "teleportation.."
and nothing happen, if I do /is it says "your island is not securised"

**Comment by OmerBenGera** [comment]
> > Fixed in latest dev build
> 
> Not fixed, I can't create an island, it says "teleportation.." and nothing happen, if I do /is it says "your island is not securised"

Look for errors.

**Comment by titidelaff** [comment]
Same problem, the island is created but the schematic does not seem to be pasted.
if I go to the island, the island is empty.

**Comment by titidelaff** [comment]
On clean server with only SSB, its working.

**Comment by WarnDa** [comment]
> Same problem, the island is created but the schematic does not seem to be pasted. if I go to the island, the island is empty.

Yes, and can't replicate it on a clean server, so there is another configuration settings that we changed and create the issue :/

**Comment by titidelaff** [comment]
I just tested by putting 1 by 1 the same plugin and I can't get the problem.
The only difference is that on the test server I am op.

**Comment by WarnDa** [comment]
> I just tested by putting 1 by 1 the same plugin and I can't get the problem. The only difference is that on the test server I am op.

I reproduced it only with superior, I'm searching which option is it :)
maybe the "default-border: false"

**Comment by titidelaff** [comment]
I tried to put the config file back to default and I no longer have the problem.
I put my config back little by little.
The problem seems to come from my spawn which is not in the world SuperiorWorld.

**Comment by WarnDa** [comment]
**Just reproduced it : **
- install multiverse-core
- create a map (here "Test")
- change the spawn world from "SuperiorWorld" to another one (here "Test")
- restart
- create an island, it won't teleport you

**Comment by Smiil3** [comment]
I have the same problem, just updated my server to 1.19.4 and the island is empty after the creation..

**Comment by OmerBenGera** [comment]
I reverted the change that caused this issue
Sorry about that
