### ISSUE TITLE
Is upgrade problem.

### ISSUE THREAD

**Issue by MrTokyo12345** [BG-Software-LLC/SuperiorSkyblock2#1688]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15020 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 425421f on paper_upstream)

### Plugin's Version

SuperiorSkyblock2-2023.1-b9

### Describe the bug

When I try to click an island update it gives me an unknown command in the console and doesn't upgrade.

![image](https://user-images.githubusercontent.com/57362525/232225046-09db8b84-6934-4792-b5d4-07d69540f5f2.png)

### To Reproduce

When I try to click an island update it gives me an unknown command in the console and doesn't upgrade.

**Comment by OmerBenGera** [comment]
You must have the `superior.island.rankup` permission in order to rankup upgrades.
The upgrades menu simply triggers an `/is rankup` command in the background.

I recommend giving your players `superior.island.*` for all the regular player permissions.
