### ISSUE TITLE
Clicking on an island warp in the warps menu throwing errors

### ISSUE THREAD

**Issue by tncc2k** [BG-Software-LLC/SuperiorSkyblock2#1691]
### Minecraft's Version

Paper1.12.2-1620

### Plugin's Version

SuperiorSkyblock2 v2023.1

### Describe the bug

I use the command /is warp to open the menu and left or right click on the cell gives 2 errors on the console.

### To Reproduce

(LEFT CLICK)
[SuperiorSkyblock2] Task #1795 for SuperiorSkyblock2 v2023.1 generated an exception
(RIGHT CLICK)
Could not pass event InventoryClickEvent to SuperiorSkyblock2 v2023.1

### Additional Information

https://pastes.dev/kJdUIrkUwu

**Comment by OmerBenGera** [comment]
Does it happen with any warp that you click or it only happens with a specific one?

**Comment by tncc2k** [comment]
without creating warp and clicking tiles on GUI, watch the video:
https://www.youtube.com/watch?v=bqKp3F2Z4WA

**Comment by tncc2k** [comment]
![image](https://user-images.githubusercontent.com/77291313/235117269-df59338b-309a-41f4-850f-69e378989234.png)

**Comment by OmerBenGera** [comment]
I can't replicate the issue
Does it happen with a new island?

**Comment by tncc2k** [comment]
happen a newly created island and all default configuration
note /is warp not /is warps

**Comment by OmerBenGera** [comment]
I think it is only triggered in 1.12, as in 1.19 it seems to work.
I managed to replicate it now, looking into it rn

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
