### ISSUE TITLE
Island Creation not working

### ISSUE THREAD

**Issue by elkoyofficial** [BG-Software-LLC/SuperiorSkyblock2#1692]
### Minecraft's Version

purpur-1962 (1.19.4)

### Plugin's Version

SuperiorSkyblock2-2023.1-b9. [Dev Build]

### Describe the bug

Everytime I change the config for superiorskyblock and change the world, it will not let you create an island. 

It says processes the request but doesn't actually generate anything. There's no errors.

### To Reproduce

Download purpur-1962 (1.19.4) & SuperiorSkyblock2-2023.1-b9. [Dev Build].

Change the world in the config, restart and try to generate a world.

**Comment by totKing** [comment]
https://mclo.gs/jDEKt2q

**Comment by WarnDa** [comment]
Reason here : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1686#issuecomment-1509855309

**Comment by OmerBenGera** [comment]
Duplicate of #1686

**Comment by OmerBenGera** [comment]
Update the plugin to recent dev build, this error was fixed already.
