### ISSUE TITLE
Unable to enter Hell and the End properly

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#1697]
### Minecraft's Version

1.19.3 paper-440

### Plugin's Version

2023.1

### Describe the bug

Unable to enter Hell and the End properly

### To Reproduce

At first my service didn’t have the function of hell and the end, but later I turned on this function, and then I can enter the hell and the end normally, then for some reason I directly deleted the hell and the end world of the island, and then restarted Let him spawn and I can no longer enter hell and the end normally, can you tell me how to fix him, thanks!

**Comment by OmerBenGera** [comment]
`/is admin unlockworld` must be used in order to enter other worlds
Also, are you sure the worlds are enabled in first place?
In general, it is not recommended at all to disable and enable the other worlds.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
