### ISSUE TITLE
/is disband not deleting blocks

### ISSUE THREAD

**Issue by imklumsy** [BG-Software-LLC/SuperiorSkyblock2#1701]
### Minecraft's Version

1.19

### Plugin's Version

supsb2 2023

### Describe the bug

When a player disbands their island it doesnt delete the blocks so when new players create an island those blocks are sometimes still there.

### To Reproduce

disband island and create new ones

**Comment by OmerBenGera** [comment]
When creating new islands, they don't take the place of old islands, therefore new islands will not be placed on top of old islands.
The plugin deletes the blocks after you disband the island, and I cannot replicate the issue myself.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by imklumsy** [comment]
no

**Comment by OmerBenGera** [comment]
Closing this for now then
If the issue persists let me know
