### ISSUE TITLE
{player} placeholder on newly created island signs not working properly

### ISSUE THREAD

**Issue by GreenedDev** [BG-Software-LLC/SuperiorSkyblock2#1702]
### Minecraft's Version

git paper 1.12.2 1620

### Plugin's Version

2023.1

### Describe the bug

title says it all 
![image](https://user-images.githubusercontent.com/108997309/234945507-aa7cbd94-d67c-46f0-b9e8-54f30a0e6fea.png)

### To Reproduce

create an island. and look at the sign.

### Additional Information

https://paste.md-5.net/avipezojex.coffeescript

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
