### ISSUE TITLE
Problem with broken blocks count on missions

### ISSUE THREAD

**Issue by SalomonPicos** [BG-Software-LLC/SuperiorSkyblock2#1703]
### Minecraft's Version

git-Purpur-1858 (MC: 1.19.2)*

### Plugin's Version

Plugin: 2023.1 (not a dev build)

### Describe the bug

When player break a x amount of stone required for a mission the plugin doesn't count all of them. It happens just with certain missions. For example: 1st stone missions works fine, 2nd don't.

### To Reproduce

Break stone and count the amount of stone you broke.

The plugin will count less if the mission is bugged

### Additional Information

https://discord.com/channels/554276823010246687/554282577322704896/1101828918509580389

Check this video i sent in the superior skyblock chat, it shows the bug.

**Comment by OmerBenGera** [comment]
There's no difference in the logic of different missions if they use the same mission jar.
The blocks that are not counted might not being whitelisted, not meeting all requirements (for example, they weren't naturally generated), etc.

**Comment by SalomonPicos** [comment]
So why it is not working?

**Comment by OmerBenGera** [comment]
> So why it is not working?

Make sure you meet all the criteria of your mission.
