### ISSUE TITLE
Upgrades Menu Pattern not working with multiple items

### ISSUE THREAD

**Issue by nf-projects** [BG-Software-LLC/SuperiorSkyblock2#1705]
### Minecraft's Version

Paper 1.19.4

### Plugin's Version

2023.1-b12

### Describe the bug

I have the following `menus/upgrades.yml` file: https://paste.gg/p/anonymous/b14c8db8136f4788aa7f67304a08b30e
The problem is that, even though the `pattern` option includes items multiple times, only one item actually shows up in the menu (the top left one; presumably because it is read before the others):
```yaml
  - '~ ~ ~ ~ ~ @ @ @ @'
  - '~ ~ ~ ~ ~ @ @ @ @'
  - '~ ~ ~ ~ ~ @ @ @ @'
  - '! ! ! ! ! ! ! ! !'
  - '! ! ! ! ! ! ! ! !'
  - '! ! ! ! ! ! ! ! !'  
  ```
  
The reason I need the upgrade items multiple times is that I'm using custom textures to make a custom GUI:
https://i.gyazo.com/73ad0b6bd935518d81d8eabe054dc0de.gif

### To Reproduce

1. Load https://paste.gg/p/anonymous/b14c8db8136f4788aa7f67304a08b30e as a menu config
2. `/island upgrades`

### Additional Information

- This happens with or without the custom model data
- **This issue doesn't happen for all menus. I have tried the control panel menu, and it worked fine.**

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
