### ISSUE TITLE
Coop Island Missions/Upgrades aren't shared

### ISSUE THREAD

**Issue by Tom4tenmark** [BG-Software-LLC/SuperiorSkyblock2#1706]
### Minecraft's Version

1.19.2

### Plugin's Version

SuperiorSkyblock2 version 2023.1

### Describe the bug

So two of the players which play on my server created a coop island. The problem is, that the Missions + Upgrades aren't shared meaning they get everything twice. For example: After the first Miner Mission you get an Generator Upgrade. Since the progress isn't shared tho, they get the generator upgrade twice which upgrades the generator to level 3 immediatly. Same for all the other upgrades and missions containing rewarding upgrades.

### To Reproduce

Create a coop island with someone else. Both of you mine the required amount of blocks to complete Miner Mission 1. You both receive the generator upgrade which boosts your generator two levels up instead of one.

**Comment by OmerBenGera** [comment]
Coop players are not part of the island that they are coop with, therefore upgrades / missions will not count towards that island.
`/is invite` is a thing.
