### ISSUE TITLE
EnderDragon egg bug value

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1708]
### Minecraft's Version

Current: git-Purpur-1834 (MC: 1.19.2)*
Previous: git-Purpur-1749 (MC: 1.19.1)
* You are 24 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

SuperiorSkyblock2 version 2023.1

### Describe the bug

A player wanted to move these 30 dragons eggs by breaking a block underneath. The egg is well lowered by 1 block by levitation. But now it shows him only one egg when he had value with several stacked blocks.
He still has 30 eggs in the /is blocks and the levels are still kept.

### To Reproduce

1. put dragon egg on a block
2. break this block
3. see what's happen

**Comment by SwartZCoding** [comment]
> Everything works fine for me.

try by myself and no i have an issue.

Video here : https://www.youtube.com/watch?v=Pm4UQgnJPPM

**Comment by SwartZCoding** [comment]
And for sure, i have the values on is values. But i lost all the stacked blocks

<img width="245" alt="image" src="https://user-images.githubusercontent.com/39431572/236485171-41a1d1f2-016e-426d-af13-cc2fdde46835.png">

**Comment by OmerBenGera** [comment]
Is this SSB's blocks stacking system?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
