### ISSUE TITLE
Chunk Bug issue when starting

### ISSUE THREAD

**Issue by granpacho** [BG-Software-LLC/SuperiorSkyblock2#1709]
### Minecraft's Version

1.19.4 git-Paper-524

### Plugin's Version

2023.1

### Describe the bug

On startup I get a error notice that it cannot load chunks or something like that 

error message: https://hastebin.com/share/hoqotiwoqi.css

this gets spammed a lot but then it stops once everything on my server is fully started up

### To Reproduce

Not sure

**Comment by WarnDa** [comment]
Use latest dev build it will fix the issue : https://hub.bg-software.com/job/SuperiorSkyblock2/

**Comment by OmerBenGera** [comment]
Already been fixed on latest dev build.
