### ISSUE TITLE
Bank dupe

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1711]
### Minecraft's Version

X

### Plugin's Version

X

### Describe the bug

![image](https://user-images.githubusercontent.com/31826333/236621461-3a0566f5-89bd-4e1d-aeac-d4580acdca44.png)

### To Reproduce

X

### Additional Information

Was just for you not to forgot

**Comment by OmerBenGera** [comment]
I am closing this as this is irrelevant.
Unless someone finds out how to replicate it and report it over, I can't do anything.
