### ISSUE TITLE
Island Effects not working after restart

### ISSUE THREAD

**Issue by WaterArchery** [BG-Software-LLC/SuperiorSkyblock2#1714]
### Minecraft's Version

1.18.2 - Purpur - Latest build

### Plugin's Version

Dev build 12

### Describe the bug

When a player upgrades its island effects like haste and jump it works but after the server restart it is not giving the effects until some admin manually types "island admin seteffect %player% FAST_DIGGING 1". Also, it is visible that upgrade is still active in /is upgrades menu.

### To Reproduce

Upgrade speed or haste upgrade.
Restart the server.

**Comment by OmerBenGera** [comment]
Hey, please upload your upgrades file to pastebin and send a link to it here.
I want to try and replicate the issue with your exact same upgrades setup :)

**Comment by WaterArchery** [comment]
Hi,

There is hastebin link:

https://hastebin.com/share/viwibicowu.yaml

Also, some other upgrades like warp limit are visible like they are active on /is upgrade menu but in game players can add warps until some admin do /is admin syncupgrades on them. I don't know what triggers that but it happens after server restart as jump and haste problem and happening on a few players not all of them.

**Comment by OmerBenGera** [comment]
Can you upload your upgrades menu as well?

**Comment by WaterArchery** [comment]
Upgrades are saving on database and they are clearly showing active on /is upgrades menu but not giving effects until reset and upgrade again. It is not happening on every island, just a few of them.

**Comment by OmerBenGera** [comment]
> Upgrades are saving on database and they are clearly showing active on /is upgrades menu but not giving effects until reset and upgrade again. It is not happening on every island, just a few of them.

Let me know how to replicate the issue then.
If it only happens to some of the islands, check out why it occurs only to them.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
