### ISSUE TITLE
Effect not given after teleport to another island

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1719]
### Minecraft's Version

paper 1.19.3

### Plugin's Version

b18

### Describe the bug

If you have an effect on your island, and you go on another islands where there is also an effect, once you back on your island you don't get your effect anymore

### To Reproduce

- take 2 accounts
- create an island on each
- set "/islands admin seteffect fast_digging 1" on each
- teleport from one island to another
- go back to your island
- you don't get your effect of fast digging you should get.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
