### ISSUE TITLE
When compiling, the NMS versions dont get put in superiorskyblock/nms/..

### ISSUE THREAD

**Issue by malafk** [BG-Software-LLC/SuperiorSkyblock2#1721]
### Minecraft's Version

latset

### Plugin's Version

dev branch

### Describe the bug

When compiling, the NMS versions dont get put in superiorskyblock/nms/..

And when I run it says no class found err ... 

It only properly compiles once every 10 tries.. really annoying

### To Reproduce

Download the dev branch (clone it)
Run build
It wont put the NMS versions in the NMS folder 
Should look like (onyl shows 3 versions tho):
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/34745578/2a9ec6ed-c339-431a-8723-10c340a1a8b6)
I get:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/34745578/8ffc3d54-6cfe-40ac-bd55-faeab08f82ab)

### Additional Information

I was trying to port to folia but this is the main issue I encounter

**Comment by OmerBenGera** [comment]
You should use `gradlew build` and you will find the final jar in a folder called `target`, under the root folder.

**Comment by OmerBenGera** [comment]
Also, Folia cannot be supported as they lack a lot of essential features (world management, for example)
I will add support to it once it is more stable.

**Comment by OmerBenGera** [comment]
Also, Folia cannot be supported as they lack a lot of essential features (world management, for example)
I will add support to it once it is more stable.

**Comment by malafk** [comment]
Already tried this many times

> You should use `gradlew build` and you will find the final jar in a folder called `target`, under the root folder.

**Comment by OmerBenGera** [comment]
You won't see anything in the NMS folder as the final jar is in the `target` folder.
