### ISSUE TITLE
Items ending up outside the border

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1724]
### Minecraft's Version

1.19.3

### Plugin's Version

latest

### Describe the bug

Dear Omar, players have been complaining about an issue for a while now, which unfortunately affects the Skyblock (Acid Island module). When they die, it sometimes happens that items end up outside the island's border. I know it's not a bug, but could you add a feature that prevents items from ending up outside the border, so that players don't lose their items?

### To Reproduce

no

**Comment by OmerBenGera** [comment]
That's sadly not possible within Minecraft at all.
I can't really control how items are thrown, and because the world-border is only a visual border and not a real border in the world, items can go through it.
