### ISSUE TITLE
Freezed mobs do not count for island limit

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1726]
### Minecraft's Version

1.19.3 pufferfishplus

### Plugin's Version

b18

### Describe the bug

All infos on discord

### To Reproduce

Will open a ticket to give you the plugin and the used config I use for this (don't want to put it here)

### Additional Information
I already use wildstacker with "nerfed-entity" to all entities.

**Comment by OmerBenGera** [comment]
SuperiorSkyblock will count all entities in the area, no matter if they have AI or don't.
Why would giving them AI somehow affect the entity count in any way?

**Comment by WarnDa** [comment]
> SuperiorSkyblock will count all entities in the area, no matter if they have AI or don't. Why would giving them AI somehow affect the entity count in any way?

I don't know but maybe the plugin that change their state create an issue into the counting, But without this plugin I got no issue in counting entities

**Comment by OmerBenGera** [comment]
> > SuperiorSkyblock will count all entities in the area, no matter if they have AI or don't. Why would giving them AI somehow affect the entity count in any way?
> 
> I don't know but maybe the plugin that change their state create an issue into the counting, But without this plugin I got no issue in counting entities

Might be.
Do you mind creating a ticket and send me a copy of that plugin so I can look into it?

**Comment by WarnDa** [comment]
> 



> > > SuperiorSkyblock will count all entities in the area, no matter if they have AI or don't. Why would giving them AI somehow affect the entity count in any way?
> > 
> > 
> > I don't know but maybe the plugin that change their state create an issue into the counting, But without this plugin I got no issue in counting entities
> 
> Might be. Do you mind creating a ticket and send me a copy of that plugin so I can look into it?

https://discord.com/channels/554276823010246687/1108689427145949225/1108689551578365962

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by WarnDa** [comment]
I didn't get issue today, to it seems good to me, thanks a lot for this fix !
