### ISSUE TITLE
Pistons not registered as "block break" for the upgrade block-limit

### ISSUE THREAD

**Issue by JakkitDE** [BG-Software-LLC/SuperiorSkyblock2#1728]
### Minecraft's Version

1.19.4 PaperMC

### Plugin's Version

latest dev build # 18

### Describe the bug

When pistons are breaking blocks, the blocks do not get counted as those. So e.g. block-limit cactus 10.. Player breaks 2 and piston breaks 2.. Then the counter says 8 but should say 6. 

### To Reproduce

Just setup cactus in block-limit e.g., then break it.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by JakkitDE** [comment]
> Is this still relevant?

Yes, it is. I finally could reproduce the issue with sugar cane... I posted a video regarding that issue on discord.. 
Case: 3 blocks high sugar cane. Piston always breaks second sugar cane and everything above automatically drops..
When its 3 high, piston breaks 2 of them, it only counts one. If its 2 high and piston breaks the single sugar cane, nothing gets counted. Because of that some players fastly got 512 sugar cane but only currently have placed 55... To "repair" that thing for a player I have to execute the command /is admin recalculate <player>.....

**Comment by OmerBenGera** [comment]
A) Players can run `/is recalc` by themselves, you don't need to do anything for them.
B) Send me a link to the video here.

**Comment by JakkitDE** [comment]
Here it is the link to the video: https://discord.com/channels/554276823010246687/554282577322704896/1133931862931288114

Yes, we have disabled that for users because recalculation costs server performance… If the limit counter would work properly we could execute the recalculation command once per day for all islands. 

Thanks for your Support. I appreciate that.
Kind Regards,
Tom

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry for the long waiting time
