### ISSUE TITLE
Redstone Bug 

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1729]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 9 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/103aee75-5121-4dea-926a-7082819aa699)

### Describe the bug

If, for example, a player has a pumpkin farm using pistons and automatic observers, and they leave the server, the farm gets stuck, which is expected. However, upon their return, it remains stuck and you're forced to break the pumpkins to get it running again. It's as if when re-entering, the redstone, especially the observers, don't reactivate properly. They remain dormant.

### To Reproduce

To reproduce it:

Set up the pumpkin farm with observers and pistons. Notice that if the following configuration is set to true:
afk-integrations:

Should redstone be disabled when all the players inside the island are AFK?
disable-redstone: false

When a player goes AFK and returns, the observer is not reactivated.

If it is set to false, as in my case: simply leave the server and when you return, you will notice that the observer has remained dormant. You are then manually forced to break the pumpkins by hand.

**Comment by OmerBenGera** [comment]
This is not a bug.
Redstone did not work, and therefore there weren't any updates that the observers can catch.
This is a known bug in Minecraft, nothing I can do regarding this.
