### ISSUE TITLE
Mission Bug (Island Level)

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1733]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 9 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/f4902c7b-7e30-4967-baef-bc3bd4c59d3f)

### Describe the bug

There is a recurring issue when completing an island where certain missions related to reaching specific island levels are marked as completed, even though the levels in my island are solely based on the spawners placed.

### To Reproduce

I will provide an example of one of my missions and my island levels. As you can see, the mission implies that to unlock it, you must reach level x. Level x is achieved by placing spawners. However, when creating the island without any spawners placed, it often happens that the levels are already completed. There seems to be an error in the level calculation, presumably.

Example:

Mission: Unlock level x of the island.
Current levels on the island: No spawners placed.
Unexpected behavior: Level x is already considered completed.

### Additional Information

Mission isola_3.yml https://pastebin.com/xd7QUu14

Level.yml https://pastebin.com/0Z8qdih7

Video bug: https://youtu.be/RWstY0O8suU

**Comment by Distolfix** [comment]
It seems that when the island is generated, the worth is not at 0, it generates afterwards, and I don't understand why it gives me already completed missions...

**Comment by OmerBenGera** [comment]
The mission is based on worth values, not levels.
Is this intended?

**Comment by Distolfix** [comment]
It is on the levels I got confused I meant to worth looks video

**Comment by OmerBenGera** [comment]
The mission you provided checks for worth values and not island levels.
when you create your island and run `/is show`, do you have any worth value or island levels?
Show me what the command shows.

**Comment by Distolfix** [comment]
I know, watch the video closely. When I generate the island, it tells me island value 80 thousand. 0:08 in the video.

Then look at how at 0:13 the missions are completed! I also sent you mission 3 and if you look closely, you can see it's already completed in the video.

**Comment by OmerBenGera** [comment]
Everything looks fine for me.
Your worth value of the island is 80k, while the level is 0.
And because your missions are according to your island worth and you have them auto-completed, they are being completed as soon as you create the island.
You can make the island worth start as 0 by setting `offset` to true in the island-creation menu file

**Comment by Distolfix** [comment]
the problem is not me but the users who enter for the first time.

**Comment by OmerBenGera** [comment]
> the problem is not me but the users who enter for the first time.

I already gave you a solution.
You can either make it so the worth value is 0 when new islands are created, or increase the worth for these missions as it doesn't make a lot of sense.

**Comment by Distolfix** [comment]
Even if you increase it from the same problem.. because it also completes the 1 million one

**Comment by Distolfix** [comment]
where is this offset true?

**Comment by OmerBenGera** [comment]
> where is this offset true?

You should add it to the schematics in the island-creation menu. This is also documented in the wiki.
<https://wiki.bg-software.com/superiorskyblock/overview/schematics#adding-your-own-schematic>

I am closing this as there is no bug.
