### ISSUE TITLE
island recalc create lag spike

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1734]
### Minecraft's Version

b22

### Plugin's Version

1.19.3 pufferfish+

### Describe the bug

When a user with a big island recalc his island that hasn't been recalculated since 2-3 days, it creates a massive lag spike (3500ms) and tps drop to ~10tps
Sometimes it creates a freeze during 3-4s
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/f86628ce-8dbd-49ec-9ce7-5d16a1e18da6)
https://spark.lucko.me/0BUjzohmED

It wouldn't be possible to slow down the process or add a limit to the lag it can create ?

### To Reproduce

Get a big island (here it's 200x200 islands with tonsss of farms)

**Comment by WarnDa** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/6474c43e-c638-42c7-84a1-f2c861c7ae9d)
Here a big island recalculed, there was a massive freeze for 10s (didn't record spark :/)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is better.
If it still not good, send me another spark profiler with the new version.

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is better. If it still not good, send me another spark profiler with the new version.
Thanks !! Plugin takes 34% but do not create massive lag spike, so it's well better (but not perfect)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/226f2a2f-81e2-43a2-a77b-d6215cc19c2c)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/79fcc376-b651-4da9-ba4b-935e636e497f)

https://spark.lucko.me/sG1pMYRvdO

**Comment by WarnDa** [comment]
Some recalc of big islands can still take some seconds and do a "minor" spike of 125ms ( I forgot to take a spark)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/3dbf9136-6332-4995-b644-fea214312b4b)

**Comment by OmerBenGera** [comment]
> Some recalc of big islands can still take some seconds and do a "minor" spike of 125ms ( I forgot to take a spark) ![image](https://user-images.githubusercontent.com/31826333/248505380-3dbf9136-6332-4995-b644-fea214312b4b.png)

Mind taking a spark and send it here as well?

**Comment by WarnDa** [comment]
> Mind taking a spark and send it here as well?
Already sent one above (after your update)
https://spark.lucko.me/sG1pMYRvdO

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is better.

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is better.

It's nearly the same
https://spark.lucko.me/XLt6qjZ6BH
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/869ca2b3-9b57-414f-b1be-3dc099db7b4a)

**Comment by OmerBenGera** [comment]
Try latest dev build

**Comment by WarnDa** [comment]
> Try latest dev build

Well better, the first recalc can be heavy, but the one after it's fine, here I did a /is admin recalc * with 120 players online : 
https://spark.lucko.me/TNYkrkLd3z

**Comment by OmerBenGera** [comment]
`/is admin recalc *` will obviously create lag, as it's gonna go through tons of blocks and recount them.
If you run `/is admin recalc` on a specific island, does it still cause lag?

**Comment by WarnDa** [comment]
> /is admin recalc

https://spark.lucko.me/3l9bTxkAvR
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/a9b74509-067d-49ae-8086-8c1cf8a916a3)
Just a peak at 200ms but seems fine

**Comment by OmerBenGera** [comment]
Check out latest dev build, will hopefully improve performance even better.

**Comment by OmerBenGera** [comment]
Most of the lag is due to the iteration on blocks, and not SSB's code.
I can't really do much regarding this.

**Comment by WarnDa** [comment]
Yes no problem, it's far better than before, thanks for all theses update !
