### ISSUE TITLE
Items on the ground cannot be picked up when the server is turned off/on again

### ISSUE THREAD

**Issue by TunanaX** [BG-Software-LLC/SuperiorSkyblock2#1735]
### Minecraft's Version

paper-1.12.2-1620.jar

### Plugin's Version

SuperiorSkyblock2-2023.1-b22.jar

### Describe the bug

spawn:
  # The location of the island. Players will be teleported to this
  # location in many events, such as disbanding islands & getting expelled from one.
  location: SuperiorWorld, 0, 100, 0, 0, 0

Let's test at (SuperiorWorld, 0, 100, 0, 0, 0)
Throw the item on the ground
Shutdown the server
Reopen the server
Go back to the place where you dropped the item you just dropped, and pick up the item you just dropped, see if it works?
(/ws kill - cannot remove that subterranean entry)

### To Reproduce

Let's test at (SuperiorWorld, 0, 100, 0, 0, 0)
Throw the item on the ground
Shutdown the server
Reopen the server
Go back to the place where you dropped the item you just dropped, and pick up the item you just dropped, see if it works?
(/ws kill - cannot remove that subterranean entry)

### Additional Information

No errors in the console
But the item on the ground is faulty
tried removing all plugins and found the cause: SuperiorSkyblock2

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
Tested it on a Paper 1.12.2 server with only SSB installed and everything is fine.

SuperiorSkyblock only prevents players from picking up items if they do not have access to do so on the island their on. Maybe that's the case?

**Comment by TunanaX** [comment]
I just tested again it's not caused by SuperiorSkyblock2
=.=''
