### ISSUE TITLE
crop growth problem

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1736]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 11 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

#23

### Describe the bug

Hi Omar,

I'm reaching out to discuss an ongoing issue on our server. We have always had crop-growth enabled with the multiplier set at its default value of 20. However, this has recently started to cause problems.

When cactus break in large quantities, they generate significant lag, which is negatively impacting the server's performance. This issue is making the daily management of activities quite challenging.

Could you consider implementing a tick limiter in your plugin? We believe this could help optimize the process and limit the lag caused by crops, thereby making our server more stable and efficient.

Thank you in advance for your attention to this matter. We hope to rely on your assistance in resolving this issue.

Best regards,

### To Reproduce

no

### Additional Information

https://spark.lucko.me/zZEv9N8Uuz

**Comment by OmerBenGera** [comment]
There's no much to optimize on SSB's side.
The crop growth multiplier is a laggy mechanism as most servers cannot handle many block ticking at the same time, and this feature causes many more block ticking, especially if you are near many tickable blocks (such as a cactus farm)

I recommend disabling the crop growth, decrease the multiplier or increase the crops interval.
