### ISSUE TITLE
Build Outside the border

### ISSUE THREAD

**Issue by HiddenSeaMC** [BG-Software-LLC/SuperiorSkyblock2#1739]
### Minecraft's Version

1.19.3

### Plugin's Version

2023.1

### Describe the bug

Players can build outside the border

### To Reproduce

Place a 2x dispenser looking outside the border (glued to the border)
Place Lava on 1 and Water on 2
Activate with lever

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/108014329/78a6fe86-f3c4-4428-9740-b44f62c467a8)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
