### ISSUE TITLE
SuperiorSkyblock LockettePro bug

### ISSUE THREAD

**Issue by AxteriaFX** [BG-Software-LLC/SuperiorSkyblock2#1741]
### Minecraft's Version

1.16.5

### Plugin's Version

Latest DEV build

### Describe the bug

With the lockettepro plugin installed, it is enough to bend over the sign and right click.

### To Reproduce

With the lockettepro plugin installed, it is enough to bend over the sign and right click.

**Comment by OmerBenGera** [comment]
I don't understand what the bug is.
Do you mind giving more details about it?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
