### ISSUE TITLE
mob-drops (uppgrades) do not work for not whole numbers (for exampls 0.5 , 1.4 , 2.9)

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1742]
### Minecraft's Version

Core: PurPur 1.19.3

### Plugin's Version

PL ver: 23 03/06/2023 10:17:15

### Describe the bug

I noticed that the mob's drop limit does not work if the multiplier is not a whole number;
This is a really big problem for me, I don't want players to get full drop from mobs on the starting level of the island and step like x1 x2 x3... to big for me.
The multiplier works if it is equal to 2.0, 3.0, 4.0, etc. However, if I set it to 0.2 or 1.5 or 2.7 for example, it will give the same loot from mobs equal to the standard minecraft loot.
I have done some experiments related to this, please have a look:

All these screenshots consist of 3 lines. Each line is all the loot that I got from killing 20 mobs. 

1st line, drop multiplier = 0.2
2nd line, drop multiplier = 1.2
3rd line, drop multiplier = 2.0

Skeleton:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/1ef29f4f-804d-4885-83e3-264b5b534d33)

Zombie:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/f8691da1-2876-4dbb-a367-a5fb3b7a504f)

Creeper:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/47772205-249f-4f22-92b8-42b19fad5d9d)

Pig:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/8cfbe65e-d752-4daf-8758-b6e87283e2af)

Cow:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/56fc2a1a-6402-452d-851d-96c2f1579f4d)

As a result, we can see that there is no difference between a multiplier of 0.2 and 1.2. I did similar tests with different mobs and multipliers and noticed that it only works correctly for integers.

### To Reproduce

1) Kill 20 mobs with drop-multiplier = 0.2
2) Kill 20 mobs with drop-multiplier = 1.2
3) Kill 20 mobs with drop-multiplier = 2.0

See that in the first and in the second case the production is the same

**Comment by OmerBenGera** [comment]
I added support for `mob-drops` to be less than 1 for lowering the mob drops rate.
Let me know if it fixes anything.

**Comment by OmerBenGera** [comment]
I added the ability to have mob drops multiplier less than 1.
However, a decimal multiplier has always been supported. You might won't notice the difference as these are too small numbers, but it works.

**Comment by Evalutik** [comment]
> Y

Hello, I tested this on the new update and nothing seems to have changed. Strange, but the amount of resources at n = 0.2 is the same as at n=1.0

**Comment by OmerBenGera** [comment]
> > Y
> 
> Hello, I tested this on the new update and nothing seems to have changed. Strange, but the amount of resources at n = 0.2 is the same as at n=1.0

Probably because when you multiply something by 0.2, after rounding, it will be the same.

**Comment by Evalutik** [comment]
> > > Y
> > 
> > 
> > Hello, I tested this on the new update and nothing seems to have changed. Strange, but the amount of resources at n = 0.2 is the same as at n=1.0
> 
> Probably because when you multiply something by 0.2, after rounding, it will be the same.

Yes, but why dont make the multiplier be the chance of an item drop when n < 1? thus, the smaller n, the less chance that something will droped at all

**Comment by OmerBenGera** [comment]
> > > > Y
> > > 
> > > 
> > > Hello, I tested this on the new update and nothing seems to have changed. Strange, but the amount of resources at n = 0.2 is the same as at n=1.0
> > 
> > 
> > Probably because when you multiply something by 0.2, after rounding, it will be the same.
> 
> Yes, but why dont make the multiplier be the chance of an item drop when n < 1? thus, the smaller n, the less chance that something will droped at all

The multiplier multiplies the current drops, not increasing/decreasing chances of drops.
