### ISSUE TITLE
Strength effect in island upgrades (island-effects) doesn't work

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1743]
### Minecraft's Version

Core: PurPur 1.19.3

### Plugin's Version

Pl.ver 23 03/06/2023 10:17:15

### Describe the bug

For some reason, the effect of the island of strength simply does not work when leveling this effect. However, if I write any other effect, it works. Please fix this.

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/746d500c-38f2-43a8-9e72-d470cff73875)

*Doesn't work with uppercase or lowercase letters

### To Reproduce

Try to create a leveling module with a strength effect.

**Comment by OmerBenGera** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html

In your case, you should use `INCREASE_DAMAGE`
