### ISSUE TITLE
Serious Bug: Incorrect Island Levels Calculation with Beta 23

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1744]
### Minecraft's Version

pufferfish 1.19.3

### Plugin's Version

b23

### Describe the bug

Hi Omar,

I am encountering a significant issue with the recently released Beta 23. Since I installed this version, the island levels are no longer calculated correctly.

Before the update to Beta 23, my server calculated the island levels based on the placed spawners. This functionality had been specifically set up for my server and has always worked without issues. However, with the update to Beta 23, players are complaining that the spawners they place no longer influence their island level.

I conducted tests on my own and encountered the same problem. I then tried reinstalling Beta 22 and the issue disappeared, which seems to indicate that the problem lies specifically within Beta 23.

Unfortunately, I cannot send you a video demonstrating the problem because it would be a lengthy and pointless process. So, I kindly ask you to trust my word and check the IS recalc that you modified in Beta 23. I believe the problem might be there.

I hope that you can take a look at this issue and fix it in future versions. Thank you for your attention and for the hard work you are putting into your work.

Best regards.

### To Reproduce

Here's how to reproduce it:

On very large islands, insert my 'levels.yml' file.
You will notice that the island level count is static and does not go up or down.
Place or remove spawners, you will see that it doesn't work.

**Comment by Distolfix** [comment]
https://pastebin.com/dX78cRMZ ----> levels.yml

https://youtu.be/lbCYDGCMfI0 --- > video 

please watch the video carefully

livello/levelli = levels

**Comment by civilcoder91990** [comment]
I also have the exact same problem, thank you, I put the beta22 on the server and it started working correctly again. We await a new update to fix this bug.

**Comment by BlackGiok** [comment]
I've noticed too, some players even complain that the level count for the is recalc stops. Additionally, sometimes I've noticed that the worth is completely wrong, with the last update to b23.

**Comment by OmerBenGera** [comment]
@Distolfix @civilcoder91990 @BlackGiok First of all, are you all using Pufferfish?
Secondly, how can I replicate the issue? I made my island as big as possible (default config values, aka island-size=200), and it counted all of my blocks just fine (I placed diamond blocks at the edges of the island and it seems to calculate them)

**Comment by Distolfix** [comment]
Yes i‘ m using pufferfish, use my island.yml and levels not work like video

**Comment by Distolfix** [comment]
Use my levels.yml with wildstacker  @OmerBenGera

**Comment by OmerBenGera** [comment]
> Use my levels.yml with wildstacker @OmerBenGera

Does it count all blocks correctly in `/is counts`?
Also, WildStacker has nothing to do with that.

**Comment by Distolfix** [comment]
@OmerBenGera not counts me spawners

**Comment by Distolfix** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/d122feb5-c0db-410c-82ae-08aff7704bfb)


Firs page
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/5ed52e99-40ab-4050-b4e0-d27eb2e3d8e9)

Second page

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/5ebf5392-32ad-4f39-983f-b06b868ec862)

Third page

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/5aeed511-ca46-44be-87dd-c0d70138c144)


is this related to this?
https://pastebin.com/Z7VMkSby

**Comment by Distolfix** [comment]
Line 95 

[15:01:57 WARN]: java.lang.NullPointerException: Cannot invoke "net.brcdev.shopgui.spawner.internal.InternalSpawnerHandler.getSpawnerItem(org.bukkit.entity.EntityType)" because "this.internalHandler" is null

**Comment by OmerBenGera** [comment]
> Line 95
> 
> [15:01:57 WARN]: java.lang.NullPointerException: Cannot invoke "net.brcdev.shopgui.spawner.internal.InternalSpawnerHandler.getSpawnerItem(org.bukkit.entity.EntityType)" because "this.internalHandler" is null

Yes, might be.
You should test the issue without SGP and check if the issue still occurs.

**Comment by Distolfix** [comment]
In the beta 22 works but in the beta 23 spawner not work for calculate mine Island level

**Comment by Distolfix** [comment]
Can you look your code, because i think is this error for the spawner not work for my island level

**Comment by Distolfix** [comment]
Now I'm sending you the step-by-step video to replicate the bug. Keep in mind, the bug is now 100% confirmed since I'm exclusively using only one plugin, which is SSB2. As you can see, neither the value nor the level calculations are working. I'm also sending you the only files I've changed through Pastebin, as you can see:
worth.yml https://pastebin.com/2zbj1XeT
levels.yml https://pastebin.com/GKHrMpPc

This guide shows you how I create a server from scratch, and by placing these 2 files it doesn't work. I beg you to be lenient this time.

https://youtu.be/M91trL8ntNI

**Comment by ImStige11** [comment]
the problem persists with the jar pufferfish 1.19.3/1.19.4.
if you use spigot you will be able to use the plugin without problems.
Please fix i have the same problem.

**Comment by Distolfix** [comment]
I tried with pufferfish 1.19.4 problem still persist. But on spigot problem solved. The fact is that omar has all the cards to fix this bug, this is related to pufferfish

**Comment by OmerBenGera** [comment]
Hmm interesting, might be related to Pufferfish.
Do you mind testing it on Paper, just to confirm it is something to do with SSB and Pufferfish?

**Comment by Distolfix** [comment]
Yes

**Comment by Distolfix** [comment]
i tested out with spigot and pufferfish. is related to pufferfish

**Comment by ImStige11** [comment]
I also tested and the problem persists only on pufferfish

**Comment by OmerBenGera** [comment]
It seems to work for me; I might be missing something.
Does it only happening with spawners not being calculated correctly?

**Comment by Distolfix** [comment]
yes

**Comment by Distolfix** [comment]
https://youtu.be/M91trL8ntNI looks my video, and use my files 

worth.yml https://pastebin.com/2zbj1XeT
levels.yml https://pastebin.com/GKHrMpPc

**Comment by Distolfix** [comment]
i tried with pufferfish #73

and pufferfish #61

**Comment by OmerBenGera** [comment]
The issue persists with Pufferfish and Paper, and only affect spawners.
I am working on a fix right now.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by Distolfix** [comment]
Works!

**Comment by OmerBenGera** [comment]
Glad it is fixed now.
