### ISSUE TITLE
Bug with drops

### ISSUE THREAD

**Issue by kristophergeou** [BG-Software-LLC/SuperiorSkyblock2#1747]
### Minecraft's Version

![Screenshot 2023-06-16 041657](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/114158743/ebe49f3d-21ed-4166-b978-8b03a368a0ea)

### Plugin's Version

![Screenshot 2023-06-16 041640](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/114158743/4ba337c7-f2a4-429d-87cb-2e956b02f5d9)

### Describe the bug

The issue for some reason when i have both Roseloot and Executableblocks installed on the server .When i place an executableblock in the islands, restart the server and then try to break it will drop a vanilla block instead. This doesnt happen in the other worlds only in the island world. If i remove roseloot everything is fine but if i add it again the bug happens. And i repeat there r no loottables on roseloot when i use it its only installed so it gotta be ss2 incapability with it and executableblocks i guess ( This also happens to oneblock )

### To Reproduce

1) Install ExecutableBlocks, Roseloot, SS2 on a server.
2) Give yourself an executableblock and place it in your island
3) /save-all and restart the server
4) then go back to your island and break the executableblock
5) It will end up being a vanilla block and not the executableblock

**Comment by OmerBenGera** [comment]
Should be reported over ExecutableBlocks / Roseloot. SSB doesn't interface with such thing.
