### ISSUE TITLE
spawner value

### ISSUE THREAD

**Issue by liyola** [BG-Software-LLC/SuperiorSkyblock2#1752]
### Minecraft's Version

1.20

### Plugin's Version

SuperiorSkyblock2-2023.1-b28

### Describe the bug

all spawner value work only the zombie_pigman spawner not now called zombified_piglin.

image link from {orth.yml} :
https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/131618661/bbf6a6fa-5f37-4251-a07c-7269b7d42ac1

ingame value image
https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/131618661/76fe0c31-82a4-4da4-8021-c2d00e8b9e3c

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Ypu can edit that in the values.yml file

**Comment by liyola** [comment]
i did but only the zombie pigman dusnt work for me

**Comment by HypiMC** [comment]
Yeah Zombie Pigman doesn't work for me as well.

**Comment by OmerBenGera** [comment]
Seems to work fine for me after I update `values.yml`; I set the zombie pigman block to be `SPAWNER:ZOMBIFIED_PIGLIN`

I will make sure it is set so by default as well.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to work
If the issue continues, let me know
