### ISSUE TITLE
Skyblock missions doesn't work

### ISSUE THREAD

**Issue by HypiMC** [BG-Software-LLC/SuperiorSkyblock2#1754]
### Minecraft's Version

1.8.8 spigot

### Plugin's Version

SuperiorSkyblock2-2023.1-b28

### Describe the bug

My superiorskyblock2 island missions farming is not working properly. The code is written wrong. The carrots and potatoes I fixed it, I just removed the -es -s ( potatoes-> potato, carrots -> carrot) and It worked, but for wheat and others I don't know how to fix. Firstly I thought I was doing something wrong, but then i changed this and carrots and potatoes worked. The items are in plural but they should be in singular (potato not potatoes, carrot not carrots) thats why minecraft doesn't recognise the items. I was trying to fix it but these two I fixed but the rest I can't becuase I'm not an expert.

### To Reproduce

I was trying to /Island missions the first missions but couldn't do it, bacause the carrots and potatoes and wheat was not working. Then I deleted the -es and -s from carrots and potatoes to make them carrot and potato and It worked, but for wheat gathering I couldn't find out, so I deleted it. Then It was fixed. Then I tried the next mission for melon and pumkins, Pumkings worked but melon harvesting wasn't.

######################################################
######################################################

# The mission file to use
mission-file: FarmingMissions

# Whether the mission should be given when completing all requirements.
auto-reward: true

# Should block counts of players get reset when completing the mission?
reset-after-finish: true

# Rewards given when completing the mission.
rewards:
  items:
    '1':
      type: PUMPKIN_SEEDS
      amount: 1
    '2':
      type: MELON_SEEDS
      amount: 1
  commands:
    - 'eco give %player% 100000'
    - 'is admin msg %player% &e&lFarmer | &7Successfully finished the mission Farmer I!'

# List of all required blocks must be gathered in order to complete the mission.
required-plants:
  '1':
    types:
      - CARROTS
    amount: 10
  '2':
    types:
      - POTATOES
    amount: 10
  '3':
    types:
      - WHEAT
    amount: 10

# Icons used in the menus.
icons:
  not-completed:
    type: PAPER
    name: '&aFarmer I'
    lore:
      - '&7Plant a small farm.'
      - ''
      - '&6Required Plants:'
      - '&8 - &7x10 Carrots'
      - '&8 - &7x10 Potatoes'
      - '&8 - &7x10 Wheat'
      - ''
      - '&6Rewards:'
      - '&8 - &7x1 Pumpkin Seed'
      - '&8 - &7x1 Melon Seed'
      - '&8 - &7$100,000'
      - ''
      - '&6Grown Carrots: &7{value_carrots}/10'
      - '&6Grown Potatoes: &7{value_potatoes}/10'
      - '&6Grown Wheat: &7{value_wheat}/10'
      - '&6Progress: &7{0}%'
      - '&c&l ✘ &7Not Completed'
  can-complete:
    type: PAPER
    name: '&aFarmer I'
    lore:
      - '&7Plant a small farm.'
      - ''
      - '&6Required Plants:'
      - '&8 - &7x10 Carrots'
      - '&8 - &7x10 Potatoes'
      - '&8 - &7x10 Wheat'
      - ''
      - '&6Rewards:'
      - '&8 - &7x1 Pumpkin Seed'
      - '&8 - &7x1 Melon Seed'
      - '&8 - &7$100,000'
      - ''
      - '&6Grown Carrots: &7{value_carrots}/10'
      - '&6Grown Potatoes: &7{value_potatoes}/10'
      - '&6Grown Wheat: &7{value_wheat}/10'
      - '&6Progress: &7{0}%'
      - '&a&l ✔ &7Click to redeem your reward.'
    enchants:
      DURABILITY: 1
    flags:
      - HIDE_ENCHANTS
  completed:
    type: MAP
    name: '&aFarmer I'
    lore:
      - '&7Plant a small farm.'
      - ''
      - '&6Rewards:'
      - '&8 - &7x1 Pumpkin Seed'
      - '&8 - &7x1 Melon Seed'
      - ''
      - '&6Grown Pumpkins: &710/10'
      - '&6Grown Melons: &710/10'
      - '&6Progress: &7100%'
      - '&a&l ✔ &7Already Claimed.'

**Comment by OmerBenGera** [comment]
Try using `CROPS` for wheat in 1.8.8. I think that `WHEAT` in 1.8.8 is used for the actual wheat item, while the crops are referred as `CROPS`

**Comment by HypiMC** [comment]
What about carrots and potatoes? I remove the .e -es?

**Comment by OmerBenGera** [comment]
You can find a list of material names here: https://bg-software.com/materials/check.php?version=1.8
So according to this listing, you should use either `MELON_STEM` or `MELON`

For further help, you can ask on the discord server.

**Comment by HypiMC** [comment]
Hey tried and for some plants worked. It didn't worked for melons and sugar cane. Tried everything.

**Comment by HypiMC** [comment]
Hey everything works now. Potatoes are "POTATO" Carrots "CARROT" Wheat is now "WHEAT" Melon is "MELON" Pumkin is "PUMKIN" Sugar Cane "SUGAR_CANE" Cactus "CACTUS". Works great now. Thanks for helping.

**Comment by OmerBenGera** [comment]
Glad it works now :)
