### ISSUE TITLE
Default Signs feature does not support text formatting.

### ISSUE THREAD

**Issue by ItchyDitchy** [BG-Software-LLC/SuperiorSkyblock2#1756]
### Minecraft's Version

git-Purpur-1858 (MC: 1.19.2)*

### Plugin's Version

SuperiorSkyblock2 version 2023.1-b23

### Describe the bug

The default-signs option currently does not support text formatting features, such as color codes.

### To Reproduce

1. Modify `default-signs` in the `config.yml`. Make sure to add color codes/formatting (e.g. `&c&n`).
2. Restart the server, and create a new island with a schematic that contains signs.
3. View the signs.

### Additional Information

# config.yml Snippet
```yml
# Set lines for signs inside island schematics.
# You can use the following placeholders:
# {player} - The island-owner's name
# {island} - The island's name if exists. if not, the owner's name will be pasted.
# You can disable this feature by setting the section to 'default-signs: []'
default-signs:
- "&a&n{player}&f, you are &c&nbad&f!"
- "&fYour island name sucks"
- "&fImaging having &a&n{island}"
- "&fas your island name."
```

# Sample Screenshot
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/51221502/a48c533e-e2c8-4abc-9878-321f3a0b09bd)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
