### ISSUE TITLE
Skyblock + minions bug

### ISSUE THREAD

**Issue by Szejkuss** [BG-Software-LLC/SuperiorSkyblock2#1758]
### Minecraft's Version

Paper 1.19.3 
This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version
Previous version: git-Paper-550 (MC: 1.19.4)

### Plugin's Version

2023.2 - latest stable

### Describe the bug

Hi, there is a problem with JetsMinions hook. 
When i will attach chest to minion everything working while i will stay on my island. When i will teleport to other world or another island, my minion didn't put items on attached chest. 
This problem exist only on SuperiorWorld for normal overworld it didn't apear. I think this is problem with SuperiorSkyblock2, Minions working normaly on any other world. 

### To Reproduce

1. Attach JetsMinions to chest on island
2. Teleport to another island/world
3. -> Mined Items didn't apear in chest

### Additional Information

https://clipchamp.com/watch/QpdGekHlOE4

**Comment by Distolfix** [comment]
I think it's normal, in order not to keep the piece loaded and not to lag. Think about whether all players will return functioning minions while you're elsewhere. That would be very laggy or am I wrong?

**Comment by Szejkuss** [comment]
It is ok, but when you arrive on chunk with chest and minion - items which minions breaks didn't appear in chest

**Comment by Distolfix** [comment]
I think it's more a problem of jetsminions than superior skyblock try to contact jetsminions

**Comment by Szejkuss** [comment]
You probably didn't read the whole post?
''This problem exist only on SuperiorWorld for normal overworld it didn't apear.''

**Comment by OmerBenGera** [comment]
This is not an issue with SuperiorSkyblock2.
Seems like JetsMinions don't handle other worlds correctly or something.
Contact them for support.

**Comment by Szejkuss** [comment]
Ohh... This error working only while minion is placed on SuperiorSkyblock world - any other world didn't break minion like this. I can place minions on overworld, overwold_nether any other world and this bug didn't apear - in my opinion this is problem with superiorworld

**Comment by OmerBenGera** [comment]
> Ohh... This error working only while minion is placed on SuperiorSkyblock world - any other world didn't break minion like this. I can place minions on overworld, overwold_nether any other world and this bug didn't apear - in my opinion this is problem with superiorworld

Contact JetsMinions for support.
