### ISSUE TITLE
Mining carts with TNT destroy the island even though TNT is disabled

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1761]
### Minecraft's Version

pufferfish 1.19.4

### Plugin's Version

latest dev

### Describe the bug

"I place a minecart with TNT, make it explode, and despite TNT being disabled on the island, it still gets destroyed

### To Reproduce

no

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
