### ISSUE TITLE
SSB2 - Warp Creation Sign error

### ISSUE THREAD

**Issue by Ancienty** [BG-Software-LLC/SuperiorSkyblock2#1762]
### Minecraft's Version

1.8.9 flamepaper

### Plugin's Version

SSB2 v2023.2

### Describe the bug

So the bug occurred after I updated the plugin from v2023.1 to v2023.2
I'm hosting a Turkish server and to create welcome-sign on my server, you have to type "[HOŞGELDİN]" on the first line of the sign and then the warp was created no problem with the previous versions.

But after the update, when I tried typing "[HOŞGELDİN]" and clicking "Okay", it started giving me the "You can only use alphabetic characters or '_'" error on chat and the sign turns completely blank.

I tried replacing non-English characters such as Ş and İ with S I, so the line eventually became [HOSGELDIN], this didn't fix the issue.
I then thought that maybe the brackets ( [] ) were causing the problem, so I deleted them as well, finally the line became "HOSGELDIN" with no special characters, all latin alphabet and English characters, yet the error still persists.

### To Reproduce

You may try what I wrote above, I'm sure it'll reproduce.

**Comment by OmerBenGera** [comment]
It seems to work fine for me with default config file.
Do you mind testing it on another server with default config file as well?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
