### ISSUE TITLE
Superiorskyblock2

### ISSUE THREAD

**Issue by DumpyMc** [BG-Software-LLC/SuperiorSkyblock2#1763]
### Minecraft's Version

1.19.4

### Plugin's Version

build 37

### Describe the bug

player's in survival cant stack spawners sometimes not even being able to place them

### To Reproduce

go in survival give yourself a spawner and place it

**Comment by OmerBenGera** [comment]
Doesnt sound like it is related to SuperiorSkyblock.

**Comment by DumpyMc** [comment]
it might be wildstackers then idk

**Comment by DumpyMc** [comment]
i was reading someone else had the same problem you told them to go back to build 551

**Comment by DumpyMc** [comment]
but the was supiorskyblock not superiorskyblock2

**Comment by DumpyMc** [comment]
or some idk

**Comment by OmerBenGera** [comment]
SuperiorSkyblock has no feature to stack spawners, unless you use the stacked-blocks feature for that, which makes no sense.

**Comment by OmerBenGera** [comment]
I am closing this as it is not related to SuperiorSkyblock.
