### ISSUE TITLE
Error island ore level member

### ISSUE THREAD

**Issue by quocn9043** [BG-Software-LLC/SuperiorSkyblock2#1764]
### Minecraft's Version

1.12.2 paper

### Plugin's Version

1.11.0

### Describe the bug

Hello, why does my member when placing an ore block, the level of the island increases but when it is broken, it does not subtract? But when there's an OP, it's still going to increase when you put and break it on and then beat it, minus normal activity

### To Reproduce

Idk i need use fix this error

**Comment by ItchyDitchy** [comment]
Update your plugin. https://hub.bg-software.com/job/SuperiorSkyblock2/

**Comment by OmerBenGera** [comment]
Update the plugin.
If the issue continues, let me know.
