### ISSUE TITLE
Missions not reset via /is admin mission reset command

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1767]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

I'm trying to reset the mission as an administrator, but I can't do it. The command does not work, despite the fact that it writes in the chat about successful execution.  This mission config has `reset-amount: 0`. However, I don't want the mission to be completed more than once. I just want to reset the mission forcibly as an exception sometimes.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/7d9fb12f-efae-4b0c-b73e-2b46f7fc42b8)

### To Reproduce

Create a mission with `reset-amount: 0`.
Complete this mission
Try `/is admin mission <your nick> reset <name of mission> `
Mission still completed

### Additional Information

Please, see the video:
https://youtu.be/RS49y0DSduo

See files of my missions in `.txt` format:
[fighting1.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11919375/fighting1.txt)
[fighting2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11919376/fighting2.txt)

**Comment by OmerBenGera** [comment]
Try setting the reset-amount to 1.

**Comment by Evalutik** [comment]
> Попробуйте установить количество сброса на 1.

Yes, this solved both problems. Thanks a lot!
