### ISSUE TITLE
The missions are automatically reset after completion

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1768]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

If it is for example `reset-amount: 10` and `auto-reward: true` then missions are automatically completed and reset after completion. I need to make all missions reset to default only when leaving the island or when the island is disbanded, however this is not possible! If I set `reset-amount: 0` then missions will never be reset at all, even when leaving the island, despite the fact that I have `disband-reset: true` and `
leave-reset: true` .

### To Reproduce

Create a mission with `reset-amount: 10` and `auto-reward: true`.
Try to complete it.
After completing missions automatically resets.
I need the mission to be reset only when the island is removed or the island is exited.

### Additional Information

Please see the video:
https://youtu.be/dnkI1ulma18

See mission files in `.txt` format:
[fighting1.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11919559/fighting1.txt)
[fighting2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11919558/fighting2.txt)

**Comment by OmerBenGera** [comment]
#1767 ?

**Comment by OmerBenGera** [comment]
Anyways, if you don't want your missions to be reset (and stay completed), set `reset-amount` to 1, as I already told you in the other ticket

**Comment by Evalutik** [comment]
> В любом случае, если вы не хотите, чтобы ваши миссии сбрасывались (и оставались выполненными), установите `reset-amount`значение 1, как я уже говорил вам в другом выпуске.

Yes, this solved both problems. Thanks a lot!
