### ISSUE TITLE
Spawner Limit Bug

### ISSUE THREAD

**Issue by xBooga** [BG-Software-LLC/SuperiorSkyblock2#1769]
### Minecraft's Version

git-Purpur-1956 (MC: 1.19.4)*

### Plugin's Version

SuperiorSkyblock2 version 2023.2
RoseStacker version 1.5.7

### Describe the bug

People are having the number of spawners placed in the block limit messed up, people have an issue where they place the max amount of spawners that they can (150 for my server) and after some time it shows up that they have 200 something placed. Once they remove any spawner they aren't able to place any more so they would have around 140 placed with it saying that have 190 which is over the 150 limit. For us having the island type /is recalc sets the correct amount of spawners back in as the amount placed.

### To Reproduce

Use rosestacker and superior skyblock with a limit of 150 spawners and try restarting the server or waiting a bit

**Comment by OmerBenGera** [comment]
Run `/is admin debug block_place` and place spawners, check if you see anything incorrect in the prompt messages in console.

**Comment by exzolink** [comment]
Same issue

**Comment by OmerBenGera** [comment]
> Same issue with vanilla spawners (without any stackers)

Are you related to @xBooga ?

**Comment by OmerBenGera** [comment]
> Reference in new is

Then I am not sure if the issues are related to each other.
Open a new issue regarding this, I will help you there.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
