### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by chamsreimom123** [BG-Software-LLC/SuperiorSkyblock2#1770]
### Minecraft's Version

1.19.2

### Plugin's Version

2023.2-b40

### Describe the bug

It says that making an island is only possible by the op, and those who are not the op are called "Unkown command. Type "/help" for help."

### To Reproduce

no

### Additional Information

no

**Comment by OmerBenGera** [comment]
https://wiki.bg-software.com/superiorskyblock/overview/commands-and-permissions/permissions
