### ISSUE TITLE
Blocking gold farm on portals

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1771]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

Everyone knows the famous gold farm that works on portals to the nether. With large volumes, it can cause lags and drawdowns in TPS. In addition, this has a bad effect on the balance of the economy within the server. I would like to block this feature so that zombie piglins and other creatures do not go to the upper world from portals. Usually the following setting in the spigot.yml file helps with this:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/659c702e-f78c-4a26-8f49-3d16bcccd566)
However, for some reason this does not work for portals in SSB2. How can I solve this problem? 

### To Reproduce

- Set `enable-zombie-pigmen-portal-spawns: false` in `spigot.yml`
- Build a nether portal on an island
- Wait
- Mobs still appearing from the portal

### Additional Information

I would also like to prevent the creation of such an ender pearl farm:
(example): https://www.youtube.com/watch?v=pouHEr1GHvA

**Comment by OmerBenGera** [comment]
SSB does not make any portals in the nether, therefore this feature is already disabled.
If mobs appear in the nether portal, then it means something else is spawning them.

You can use the entity-limit feature of SSB, and if that doesn't help, I recommend getting other plugins to limit these kind of farms.

**Comment by Evalutik** [comment]
> SSB does not make any portals in the nether, therefore this feature is already disabled. If mobs appear in the nether portal, then it means something else is spawning them.
> 
> You can use the entity-limit feature of SSB, and if that doesn't help, I recommend getting other plugins to limit these kind of farms.

The player can build a portal in hell on their own, then if the portal is and in the upper world the mobs will teleport

**Comment by OmerBenGera** [comment]
> > SSB does not make any portals in the nether, therefore this feature is already disabled. If mobs appear in the nether portal, then it means something else is spawning them.
> > You can use the entity-limit feature of SSB, and if that doesn't help, I recommend getting other plugins to limit these kind of farms.
> 
> The player can build a portal in the nether on their own, then if there is a portal in the upper world as well, the mobs will teleport

They are not connected tho, as portals will look for their connected one at the coords x 8 (or divided by 8), but SSB spawns the nether world at the same coords as your island in the overworld.
