### ISSUE TITLE
Misssions: Splash / Extended /  Upgraded Potions ammount placeholders do not work 

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1772]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

I'm trying to make a mission where you need to brew 3 potions:

```
required-potions:
  '1':
    potions:
      '1':
        type: POISON
        upgraded: false
        extended: true
        splash: true
    amount: 200
  '2':
    potions:
      '1':
        type: WEAKNESS
        upgraded: false
        extended: true
        splash: true
    amount: 150
  '3':
    potions:
      '1':
        type: SLOWNESS
        upgraded: true
        extended: false
        splash: true
    amount: 100
```

But apparently placeholders that should show the number of potions made do not work for this:

```
      - '&7Made splash potion of poison (1:30): &f{value_poison}&7/&f200'
      - '&7Made splash potion of weakness (4:00): &f{value_weakness}&7/&f150'
      - '&7Made splash potion of slowness IV (00:20): &f{value_slowness}&7/&f100'
```
      
gives:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/4406e868-3760-4180-91ba-8752195c4b0e)
      
   
File with my mission it `.txt` format:
[brewing2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11929292/brewing2.txt)

### To Reproduce

- Paste file with my mission in one of your mission categories
- Change it to `.yml` file
- Start your server
- Open this mission
- See:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/bb0d842c-9b65-4218-8a5d-530ad1d885b1)

**Comment by Evalutik** [comment]
I also have a question about the potion of turtle power: what will be the placeholder for it and did I place it correctly in the list of required potions?

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/be5881b5-ad9e-4428-8ef3-d61de7be0b9d)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/e00ec851-8c1b-47af-88ca-138a27121fa7)

```
required-potions:
  '1':
    potions:
      '1':
        type: HARM
        upgraded: true
        extended: false
        splash: true
    amount: 4000
  '2':
    potions:
      '1':
        type: REGENERATION
        upgraded: true
        extended: false
        splash: true
    amount: 1800
  '3':
    potions:
      '1':
        type: JUMP
        upgraded: true
        extended: false
        splash: true
    amount: 1600
  '4':
    potions:
      '1':
        type: SLOWNESS
        upgraded: true
        extended: false
        splash: false
      '2':
        type: DAMAGE_RESISTANCE
        upgraded: true
        extended: false
        splash: false
    amount: 40
```

**Comment by Evalutik** [comment]
This string:
` - '&7Сделано взрывных зелий регенерации II (0:22): &f{value_regeneration}&7/&f1800'`
Leads to the error:
```
[15:38:07 WARN]: java.lang.IllegalArgumentException: This is not a valid potion data.
[15:38:07 WARN]: 	at com.bgsoftware.superiorskyblock.missions.BrewingMissions$PotionData.fromString(BrewingMissions.java:368)
[15:38:07 WARN]: 	at com.bgsoftware.superiorskyblock.missions.BrewingMissions$1.getRequirementFromKey(BrewingMissions.java:191)
[15:38:07 WARN]: 	at com.bgsoftware.superiorskyblock.missions.BrewingMissions$1.getRequirementFromKey(BrewingMissions.java:188)
[15:38:07 WARN]: 	at com.bgsoftware.superiorskyblock.missions.brewing.Placeholders.parsePlaceholders(Placeholders.java:55)
[15:38:07 WARN]: 	at com.bgsoftware.superiorskyblock.missions.BrewingMissions.formatItem(BrewingMissions.java:214)
[15:38:07 WARN]: 	at SuperiorSkyblock2-2023.2-b37.jar//com.bgsoftware.superiorskyblock.core.menu.button.impl.MissionsPagedObjectButton.modifyViewItem(MissionsPagedObjectButton.java:91)
[15:38:07 WARN]: 	at SuperiorSkyblock2-2023.2-b37.jar//com.bgsoftware.superiorskyblock.core.menu.button.AbstractPagedMenuButton.createViewItem(AbstractPagedMenuButton.java:29)
[15:38:07 WARN]: 	at SuperiorSkyblock2-2023.2-b37.jar//com.bgsoftware.superiorskyblock.core.menu.layout.PagedMenuLayoutImpl.populateInventory(PagedMenuLayoutImpl.java:69)
[15:38:07 WARN]: 	at SuperiorSkyblock2-2023.2-b37.jar//com.bgsoftware.superiorskyblock.core.menu.layout.AbstractMenuLayout.buildInventory(AbstractMenuLayout.java:73)
[15:38:07 WARN]: 	at SuperiorSkyblock2-2023.2-b37.jar//com.bgsoftware.superiorskyblock.core.menu.AbstractMenu.lambda$buildInventory$2(AbstractMenu.java:79)
[15:38:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101)
[15:38:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[15:38:07 WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[15:38:07 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[15:38:07 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[15:38:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
```


If I comment it:
` #- '&7Сделано взрывных зелий регенерации II (0:22): &f{value_regeneration}&7/&f1800'`

It will be ok. Seems like `{value_regeneration}` is incorrect.

**Comment by OmerBenGera** [comment]
The format for the potion in the value is as follows:
`<potion_type>;<upgraded?true|false>;<extended?true|false>;<splash?true|false>`

Therefore, for your poison potion, you'd use:
`POISON;false;true;true`

Let me know if that fixes the issue.

**Comment by Evalutik** [comment]
> The format for the potion in the value is as follows: `<potion_type>;<upgraded?true|false>;<extended?true|false>;<splash?true|false>`
> 
> Therefore, for your poison potion, you'd use: `POISON;false;true;true`
> 
> Let me know if that fixes the issue.

I changed it but the placeholders just show 0 now even though I tried brewing every type of this potion.

My potions now:
```
required-potions:
  '1':
    potions:
      '1':
        type: POISON
        upgraded: false
        extended: true
        splash: true
    amount: 200
  '2':
    potions:
      '1':
        type: WEAKNESS
        upgraded: false
        extended: true
        splash: true
    amount: 150
  '3':
    potions:
      '1':
        type: SLOWNESS
        upgraded: true
        extended: false
        splash: true
    amount: 100
```

My placeholders now:
```
      - '&7Сделано взрывных зелий отравления (1:30): &f{value_POISON;false;true;true}&7/&f200'
      - '&7Сделано взрывных зелий слабости (4:00): &f{value_WEAKNESS;false;true;true}&7/&f150'
      - '&7Сделано взрывных зелий замедления IV (0:20): &f{value_SLOWNESS;true;false;true}&7/&f100'
```
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/6f6afaad-ee3c-4cdb-8fe4-cf1bdcda5a45)

mission file in `.txt` format:
[brewing2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11984095/brewing2.txt)

**Comment by Evalutik** [comment]
Some news about it?

**Comment by OmerBenGera** [comment]
Works just fine for me
https://gyazo.com/21d3d875edff2f5b6cce53adec83146f

**Comment by OmerBenGera** [comment]
I used the one you sent me.

**Comment by Evalutik** [comment]
> > Works just fine for me https://gyazo.com/21d3d875edff2f5b6cce53adec83146f
> 
> Could you please send your mission config?

Yes, it seems to work. But how do I check and what placeholder will be for `Turtle Master` Potion? Am I checking it correctly: 

```
  '4':
    potions:
      '1':
        type: SLOWNESS
        upgraded: true
        extended: false
        splash: false
      '2':
        type: DAMAGE_RESISTANCE
        upgraded: true
        extended: false
        splash: false
    amount: 40
```

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/d718463d-19f6-4e37-b205-4616fec0108b)


But what is the placeholder then?

**Comment by OmerBenGera** [comment]
You should use the correct potion data names from Bukkit.
Google it.

**Comment by Evalutik** [comment]
> You should use the correct potion data names from Bukkit. Google it.

Oh yes, i know, I think i used it (REGENERATION and SLOW_FALLING should be correct, idk whats wrong...)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/5034c346-b411-4d25-9d36-62fde8475926)
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html#:~:text=entity%20over%20time.-,static%20final%20PotionEffectType,Regenerates%20health.,-static%20final%20PotionEffectType

and 

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/e7a6c941-c1a4-403f-97bf-3e4cc0a68c96)
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html#:~:text=Decreases%20dig%20speed.-,static%20final%20PotionEffectType,Slows%20entity%20fall%20rate.,-static%20final%20PotionEffectType

I also cant find info about turtle potion effect

**Comment by OmerBenGera** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html

It should be `SLOW_FALLING` and `REGEN`

**Comment by OmerBenGera** [comment]
Is there anything else I can help you with?

**Comment by Evalutik** [comment]
Thx
