### ISSUE TITLE
sometimes hopper limit calculation was not worked properly.

### ISSUE THREAD

**Issue by Ecilpse** [BG-Software-LLC/SuperiorSkyblock2#1773]
### Minecraft's Version

1.19.2 purpur

### Plugin's Version

2023.1-b22

### Describe the bug

sometimes hopper limit calculation was not worked properly.
when i use command "/is admin recalc [player]", it worked.

### To Reproduce

It is difficult to reproduce because it often happens irregularly.

**Comment by OmerBenGera** [comment]
The plugin tracks blocks as they are placed or broken.
If it happens only with hoppers, my guess is that another plugin interfaces with this.

Try it on a server with only SSB installed, check if that happens.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
