### ISSUE TITLE
Error with MyWorlds plugin

### ISSUE THREAD

**Issue by YKDZ** [BG-Software-LLC/SuperiorSkyblock2#1775]
### Minecraft's Version

git-Purpur-2005 (MC: 1.20.1)*

### Plugin's Version

SuperiorSkyblock2-2023.2-b40

### Describe the bug

https://github.com/bergerhealer/MyWorlds/issues/45
https://mcpaste.com/0fe686b11ddb1e0e3654191bce5ee6c3
The error appears every time the server is restarted, followed by the server shutting down automatically after the startup completes. The problem is fixed after bringing the server up again, after which the process is repeated.

My platform is git-Purpur-2005 (MC: 1.20.1)*
Plugin version is MyWorlds 1.20.1-v1

### To Reproduce

Restart server

**Comment by YKDZ** [comment]
https://pastebin.com/0TwvD3CN

**Comment by OmerBenGera** [comment]
For no reason SuperiorSkyblock doesn't load before My_Worlds, and this is what causes the error to occur.
Not a bug of SSB itself, as it worked before - probably because of Paper's new plugins loading system breaking things.

Why do you need My_Worlds?

**Comment by YKDZ** [comment]
MyWorlds is only used by me to do some testing and I still use Multiverse-Core in my production environment.
MyWorlds is compatible with the Iris plugin, while Multiverse-Core is not, so I will use MyWorlds on servers that use Iris.
By the way, when I uninstall CMI from my server, this error will not appear. So it may be causing the problem.

**Comment by YKDZ** [comment]
Strictly speaking, it is CMILib, but I cannot reproduce this issue locally.

**Comment by OmerBenGera** [comment]
> MyWorlds is only used by me to do some testing and I still use Multiverse-Core in my production environment. MyWorlds is compatible with the Iris plugin, while Multiverse-Core is not, so I will use MyWorlds on servers that use Iris. By the way, when I uninstall CMILib from my server, this error will not appear. So it may be causing the problem.

As I said, this is an issue with Paper's loading system of plugins.
Just disable it.

**Comment by YKDZ** [comment]
Oh, I got it. Solved by add -Dpaper.useLegacyPluginLoading=true in the run command.

**Comment by OmerBenGera** [comment]
Awesome :)
