### ISSUE TITLE
Island level

### ISSUE THREAD

**Issue by WolfAlex17** [BG-Software-LLC/SuperiorSkyblock2#1776]
### Minecraft's Version

Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

2023.2 the latest stable version

### Describe the bug

i am trying to modify the island level in the config with the worth formula...but if i want to do worth/10 the level is negative

### To Reproduce

in the config i changeg the formula then reloaded the plugin and then /is level
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/86449461/024a2e19-81dc-40d6-be5e-278bbab969a2)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/86449461/3daeb310-94e7-4e39-bbdf-94ebf5aa5afe)

**Comment by OmerBenGera** [comment]
That's not how formula works.
The formula will apply the level for each block level value, therefore you won't see that the levels are worth divided by 10.

Not a bug.
