### ISSUE TITLE
Modules => Missions => FarmingMissions: BAMBOO doesn't count [OR counts wrong]

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1778]
### Minecraft's Version

Core: PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

For some reason, bamboo doesn't count (or doesn't count correctly). 
Bamboo is not considered at all in the video (`{value_bamboo}` always `= 0`), but previously, I was able to repeat the experiment from my video below, but then bamboo was just considered very strange. `{value_bamboo}` changed from time to time, but I couldn't figure out what it was because it didn't work correctly.

My video: https://youtu.be/MprdNVXbjD0
My mission file in the `.txt` format:
[farming3.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/11967919/farming3.txt)

Perhaps I'm doing something wrong?

### To Reproduce

Try to complete growing bamboo with FarmingMissions. (Doesn't work)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
