### ISSUE TITLE
Missions: watermelons and pumpkins are counted differently

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1780]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

The fact is that FarmingMissions counts the growth of plants such as wheat differently compared to pumpkins, watermelons and nether wart.
See what I mean with an example:
1st: Let's say I grow one wheat:
n is the number that placeholder `{value_wheat}` will take.

- status 1:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/4ac05f0b-046c-46d4-ae10-9a8c77fa7338)
n = 0

- status 2:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/358bf56c-3ca7-4a5e-8ced-bc46cf006397)
n = 0

- status 3:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/098fb375-ead0-4719-a8c5-980ca5a626a3)
n = 0

. . .

- status 6:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/cae56f86-0099-4622-a945-886ed3ad5357)
n = 0

- status 7:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/64b93751-b111-49ad-9ffa-2da843b2353b)
**n = 1**

We see that the placeholder only changed its value when the wheat was fully grown. So it should be, I think this behavior is correct. It also works with potatoes, carrots, beets. It is perfectly! But let's try to grow a watermelon:
2nd: I grow one watermelon:
n is the number that placeholder `{value_watermelon}` will take.

- status 1:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/9694bd29-fed2-49e4-863a-7eb2dfa06b53)
n = 0

- status 2:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/4be6dee7-46de-4094-97a2-5f8719acc340)
**n = 1**

- status 3:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/6dc18d0f-5fe6-4762-a07e-2d31f2555264)
**n = 2**

. . .

- status 7:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/6f2210e6-9e0e-47bc-a0ec-d166bc10bfda)
**n = 6**

- status 8:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/c93ba39b-2f05-4721-998e-8529792547b1)
**n = 7**

- status 9:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/74e643b3-2dd4-4a3e-aea8-1c3dd230af55)
**n = 8**

The same situation will be with pumpkin and nether wart.

For this to work correctly, status 8 should still be n = 0. Then status 9 should still be n = 1. This way the mission should trigger when a new watermelon or pumpkin grows, not just the growth status changes.

### To Reproduce

Try to repeat what i did:
- check `{value_watermelon}`  when plant starts growth, then check it when it already grown. The placeholder will increase not by 1 but by 8 or 9.

**Comment by Evalutik** [comment]
In addition, if I apply bone_meal to a pumpkin or watermelon, then the status jumps several positions at once (for example, from status 1 to status 4) but `{value_watermelon}` only increases by 1

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Evalutik** [comment]
works perfect
