### ISSUE TITLE
Bypass island restrictions on ARMOR_STAND

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1782]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b37

### Describe the bug

I'm trying to limit the number of armor stands on an island (in my example the limit is 8). However, I have noticed that sometimes I can exceed this limit. I tested it with boats and boats work fine. I don't know if this is related, but I have a plugin like Money From Mobs (https://www.spigotmc.org/resources/money-from-mobs-1-12-1-20.79137/), it seems to me that it signs a rising nametag when killing a mob with an invisible ARMOR_STAND. I do not know how this can affect, but the fact is that the limit on the ARMOR_STAND limit does not work. (I tried this without operator rights). However, I would like the invisible armor stands to still be available for placement with other plugins, as this can cause conflicts if other plugins can't.

Please, see my viseo:
https://youtu.be/UtudzEJJA60

### To Reproduce

Install Money From Mobs plugin
Set limit for ARMOR_STAND in config.yml of SSB2
After reaching limit try to kill mob, and put ARMOR_STAND in short

**Comment by OmerBenGera** [comment]
Invincible armor stands do not count for entity counts or limits.
Use `/is admin debug entity_spawn` and `/is admin debug entity_despawn` to better understand when the plugin detects spawning and despawning of entities, and find out when they are not working together.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by Evalutik** [comment]
perfect
