### ISSUE TITLE
EnchantingMissions: Placeholders shows "YES" or "NO" if amount: 1 instead of "1" or "0"

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1783]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b45

### Describe the bug

Why does placeholdes {enchanted_<item>} for amount: 1 show YES or NO? After all, all other placeholders with amount: 1 still show 0 or 1. This interferes with the overall design.
I have:
```
      - '&7Зачаровано деревянных кирок: &f{enchanted_wooden_pickaxe}&7/&f1'
      - '&7Зачаровано каменных кирок: &f{enchanted_stone_pickaxe}&7/&f1'
      - '&7Зачаровано железных кирок: &f{enchanted_iron_pickaxe}&7/&f1'
```
I see in minecrat:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/4807e529-dde7-4f04-9afc-42c062aa8654)

But with fighting missions:
I have:
```
      - '&7Убито драконов: &f{value_ender_dragon}&7/&f1'
      - '&7Убито хранителей: &f{value_warden}&7/&f1'
```

I see in minecraft:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/40019514-e258-43b0-bfa3-ad71d9ac08eb)
(as it should be)

### To Reproduce

Try to create mission with EnchantingMissions jar and set amount: 1; placeholder {enchanted_<item>} shows NO (should be "0")

**Comment by OmerBenGera** [comment]
Not a bug.
