### ISSUE TITLE
Upgrade with placeholder not work

### ISSUE THREAD

**Issue by Rap3erka** [BG-Software-LLC/SuperiorSkyblock2#1785]
### Minecraft's Version

Paperspigot 1.19.4

### Plugin's Version

SuperiorSkyblock2-2023.2-b45

### Describe the bug

Upgrading by any placeholder doesn't work.

### To Reproduce

  Add for example this type of upgrade:
  
  border-size:
    '1':
      price: 100.0
      price-type: 'placeholders'
      border-size: 12
      placeholder: 'cmi_user_balance'
      withdraw-commands:
      - 'money take %player% 100'
      commands:
      - say test

**Comment by OmerBenGera** [comment]
What does `%cmi_user_balance%` return?
Give me an example of the output.

**Comment by Rap3erka** [comment]
This is the account balance from the CMI plugin. But I need it to set my own tokens from my plugin. 
And I tried all the placeholders from different plugins

**Comment by Rap3erka** [comment]
When I set it as above in the example, it shows that I do not have enough in my account, but I actually have an account

**Comment by OmerBenGera** [comment]
The value of the placeholder must be a number (not formatings or anything), otherwise it won't work.

**Comment by Rap3erka** [comment]
Are you able to show an example? I am following the example from the wiki
There is:

  placeholders-example-upgrade:
    '1':
      price: 1000000.0
      price-type: 'placeholders'
      placeholder: 'custom_economy_balance'
      withdraw-commands:
      - 'customeco take %player% 1000000'
      commands:
        - ...

So I set my placeholder instead of "custom_economy_balance" that is "cmi_user_balance"

**Comment by OmerBenGera** [comment]
Run `/papi parse me %cmi_user_balance%` and show me what is shown in chat.

**Comment by Rap3erka** [comment]
Okey. 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/72500362/d54631f6-f6f3-4c71-bbd7-ab091c7a2202)

**Comment by Rap3erka** [comment]
I have it done this way:

  border-size:
    '1':
      price: 100.0
      price-type: 'placeholders'
      border-size: 12
      placeholder: 'cmi_user_balance'
      withdraw-commands:
      - 'money take %player% 100'
      commands:
      - say test
      - island admin setupgrade %player% border-size 2
    '2':
      price: 10000.0
      price-type: 'placeholders'
      border-size: 15
      placeholder: 'cmi_user_balance'
      withdraw-commands:
      - 'money take %player% 100'
      commands:
      - island admin setupgrade %player% border-size 3

And it shows a message that I don't have enough to upgrade and I have 142,000$

**Comment by OmerBenGera** [comment]
Upload your entire upgrade to pastebin and send a link to it here.
I will try to replicate it myself.

**Comment by Rap3erka** [comment]
https://pastebin.com/2naCaG5q

**Comment by Rap3erka** [comment]
no placeholder upgrade works, I also try others

**Comment by OmerBenGera** [comment]
You should use the format of placeholders in the placeholder field. 
This means that you should add `%` or `{}` (depends on your placeholders plugin), same as you'd use it in any other place.

**Comment by OmerBenGera** [comment]
I am closing this as the solution above should fix the issue.
If the issue continues, let me know
