### ISSUE TITLE
Placeholder warps bugged

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1787]
### Minecraft's Version

1.19.4

### Plugin's Version

b-45

### Describe the bug

I have encountered an issue in the warps.yml translation file. Specifically, the placeholders {0}, {1}, etc. are not working as expected. When I use the /is warp command on the server, I see {0} displayed instead of the corresponding placeholder values.

I have also checked the default configuration file, but the issue persists. Your investigation into this issue would be much appreciated.

Thank you so much for your assistance.

### To Reproduce

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/fc7f0030-abcc-49e7-b7d2-55b4abb5f949)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/bd864d47-b606-43fe-ac41-2de0113d2a96)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/638ebe41-5ce9-4829-bf68-6ff35e38b595)

**Comment by OmerBenGera** [comment]
That's totally fine, not a bug.
It shows you the item in raw, so no placeholders are translated. Then, in the `/is warps` menu, the placeholders will be translated.
