### ISSUE TITLE
Zombie Spawn Issue: Zombies Spawn Despite Natural Mob Spawn Being Disabled

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1788]
### Minecraft's Version

1.19.4

### Plugin's Version

b-45

### Describe the bug

I'm experiencing an unexpected issue related to mob spawning on the island, despite having disabled natural mob spawn in the settings.

Specifically, it seems that the disable feature effectively works for all types of mobs with the exception of zombies. Surprisingly, zombies continue to spawn even when they should not. This anomalous behaviour not only deviates from the expected results based on the established settings, but it also disrupts the gameplay experience as it seemingly bypasses the rules set by the user.

### To Reproduce

disable mob spawning

**Comment by Evalutik** [comment]
Idk about this problem, it will not fix it, but may solve your problem:Try to disable mob spawning, using wg plugin, add flag to the __global__ rg in the world with islands

**Comment by Distolfix** [comment]
I'm sorry, but why shouldn't it be fixed? I mean, a person turns off the natural mob spawn in the /is settings and zombies spawn despite they shouldn't. What does WorldGuard have to do with it?

**Comment by OmerBenGera** [comment]
Are you sure this is related to SuperiorSkyblock?
Try it on a server with only SuperiorSkyblock installed, let me know if it still occurs.

**Comment by Distolfix** [comment]
Yes, I'm sure it depends on Superiorskyblock. I have also already tried it on a server with only Superiorskyblock2. When you disable natural mob spawning, zombies still spawn. It should be noted that this phenomenon occurs in the latest versions; it didn't happen before.

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
SSB checks whether the mob was spawned with one of the listed spawn reason associated with natural spawning, and then prevents its spawning - it doesn't care whether it's a Zombie or another entity.

What version of Spigot do you use? It might be related to that.
Send me the exact output of `/version` please.

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/73421268/253631801-aa6adaa0-6abb-4b3c-9843-a91289dbd46b.png)

Check the entity's spawn reason with the `/data` command.

**Comment by waiching514** [comment]
I got the same problem with you, I think Natural mob spawning not including Zombie Siege, can it adding to Natural mob spawning?
