### ISSUE TITLE
Island Bank interest

### ISSUE THREAD

**Issue by Zsomi** [BG-Software-LLC/SuperiorSkyblock2#1789]
### Minecraft's Version

git-Purpur-1985 1.19.4

### Plugin's Version

2023.2-b45

### Describe the bug

Once the interest period reaches 1 second, the bank will stop paying interest.

### To Reproduce

Let's put a larger amount in the island bank, for example 10 million. Then we wait for the 1 second to see when it starts to accrue interest.

### Additional Information

https://cdn.discordapp.com/attachments/904489608367190018/1128343257789775944/2023-07-11_17.13.01.png

**Comment by OmerBenGera** [comment]
You said in the bug that you don't get the interest, however in the "to reproduce" you said you get the interest..?

**Comment by Zsomi** [comment]
The point is that they don't get a palcehodler that stops after 1 second.

**Comment by OmerBenGera** [comment]
What do you mean by "they don't get a placeholder"?

**Comment by Zsomi** [comment]
The point is that when the interest rate is due to occur, it takes 1 second and does not count when the interest rate is due

**Comment by OmerBenGera** [comment]
Take a video of the bug please.

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
