### ISSUE TITLE
Minecart limit on island

### ISSUE THREAD

**Issue by Patryk9751** [BG-Software-LLC/SuperiorSkyblock2#1790]
### Minecraft's Version

1.19.3

### Plugin's Version

2023.2

### Describe the bug

If minecart with hopper will  fall into the void it still counts into the island's limit 

### To Reproduce

If minecart with hopper will  fall into the void it still counts into the island's limit

**Comment by OmerBenGera** [comment]
What version of Spigot do you use?
The exact output of `/version` please.

**Comment by Patryk9751** [comment]
This server is running Paper version git-Paper-448 (MC:1.19.3)
(Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git:155aa36)

pt., 14 lip 2023, 12:14 użytkownik Ome_R ***@***.***> napisał:

**Comment by OmerBenGera** [comment]
What exactly is counted towards the island limit? The hopper block, or the minecart (as an entity)?

**Comment by Patryk9751** [comment]
Both, 1 minecart with hopper counts as one hopper but it doesn't matter,
more important fact is that if minecart with hopper falls into the void it
still counts to the limit as if it had existed

pt., 14 lip 2023, 15:12 użytkownik Ome_R ***@***.***> napisał:

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
