### ISSUE TITLE
Server won't starting (World loading error with Multiverse-Core)

### ISSUE THREAD

**Issue by Achent007** [BG-Software-LLC/SuperiorSkyblock2#1791]
### Minecraft's Version

1.20.1
purpur-1.20.1-2014.jar

### Plugin's Version

2023.2-b45

### Describe the bug

The server stop directly after fully load due to the world was already loaded.

The only way i have to let the server start is to remove Multiverse-Core and load them manually with plugman when the server is fully loaded

### To Reproduce

Install superiorskyblock and multiverse-core and start the server

### Additional Information

This is the error from the console : https://pastebin.com/nDgrUjdy

I don't have so many information that i think it can help you but if you need some informations just ask them !

**Comment by OmerBenGera** [comment]
Please disable Paper's plugins loading system and it will work.
