### ISSUE TITLE
Placeholders don't work at lang file JOINED_ISLAND and JOINED_ISLAND_NAME

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1793]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b45

### Describe the bug

I checked and placeholders `{0}` doesn't output anything in chat messages on strings:
`JOINED_ISLAND` (str 517 my file) and
`JOINED_ISLAND_NAME` (str 518 my file)
 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/4b95f250-e065-4059-bd20-19c148210b2d)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/1ba1e8b3-49ca-4d17-a72d-c93c25f1a45b)

### To Reproduce

Try to join the island, check the chat.

**Comment by OmerBenGera** [comment]
`JOINED_ISLAND_NAME` will have the island's name in the {0} placeholder.
Therefore, if you disabled names, it won't show anything, and you simply need to get rid of the placeholder.

**Comment by Evalutik** [comment]
> `JOINED_ISLAND_NAME`будет иметь название острова в заполнителе {0}. Поэтому, если вы отключили имена, он ничего не покажет, и вам просто нужно избавиться от заполнителя.

Thank you
