### ISSUE TITLE
Remove coop from all places if they are off

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1796]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

SuperiorSkyblock2-2023.2-b45

### Describe the bug

Coop still remains in some places in the menu, even if they are disabled in the configuration:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/d1d914b3-6c40-49bd-b215-6f790ef41226)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/6a5a7cea-9d5e-451a-92cb-eea29dca1f23)
It would be great if all mentions of coop would disappear if they are turned off on the server anyway.

### To Reproduce

turn off coops in config
restart server
you see coops still in the menu, for example permissions menu

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is better.
Also, if you find any other places that coop members are shown, let me know.

**Comment by Evalutik** [comment]
I think its okay for now, if something, ill let u know
