### ISSUE TITLE
Bank menu not updating on deposit/withdrawal

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1798]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

dev build .45

### Describe the bug

When I deposit or withdraw funds into the bank using the "deposit all" or "deposit half" button, the bank menu does not update automatically. You have to reopen the menu to see the changes. Please fix it

### To Reproduce

give money to you /eco give ...
go to /is bank
press deposit all
bank balance at the icon in the middle didn changed
reopen /is bank
we see balance updated

**Comment by OmerBenGera** [comment]
The bank menu does not have a placeholder to show the current money in the bank, you use a third-party placeholder to do so, and therefore the menu is not updating.
Not an actual bug.

**Comment by Evalutik** [comment]
> The bank menu does not have a placeholder to show the current money in the bank, you use a third-party placeholder to do so, and therefore the menu is not updating. Not an actual bug.

But there is a placeholder` %superior_island_bank_format%` which shows current money in the bank. Am I right, or.. not sure

Screen from default bank menu (`SSB2/menus/island-bank.yml`):
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/fc92ea0b-2022-485a-906d-5074ed6bdf8f)

Code:

```
  '*':
    type: PAPER
    name: '&6Balance'
    lore:
      - '&7Your bank currently has $%superior_island_bank_format%'
```

Default `island-bank.yml` file in `.txt` format:
[island-bank.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/12053639/island-bank.txt)

**Comment by OmerBenGera** [comment]
This is not a built-in placeholder of the menu.
Therefore, it is not updated between interactions of the menu.
You can suggest it as a feature request if you wish.
