### ISSUE TITLE
I can rename my island to the player's nickname

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1800]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

dev build .45

### Describe the bug

It's ok that I can use` /is rename <player>` where player is any player. Will it break commands? Doesn't ssb2 take OR the name of the island OR the name of the leader as an argument in some commands? Will it cause serious bugs? And is the situation taken into account when a player first renames his island to X and then a player with the nickname X enters the server for the first time and starts playing?

### To Reproduce

Try to rename islan with /is rename command, usin nick of the player as island name

**Comment by OmerBenGera** [comment]
Should be fine.
If you encounter issues, report them over.
