### ISSUE TITLE
Bank transactions do not work (bank-logs.yml)

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1801]
### Minecraft's Version

PurPur 1.19.3

### Plugin's Version

Dev build .45

### Describe the bug

It looks like bank transactions are not working. I carry out various transactions, withdraw and deposit money, but no transactions are added. 

Please watch my video:
https://youtu.be/8unfIDT5gjA

### To Reproduce

Try to withdraw/add money to the` /is bank`
check transactions
(nothing)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/e8ef27b6-9c61-4bf1-bd7d-8ebcda22174f)

### Additional Information

Transaction menu file (`SSB2/menus/bank-logs.yml`) in `.txt` format:
[bank-logs.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/12058943/bank-logs.txt)

**Comment by OmerBenGera** [comment]
Try it on a server with default files of SSB.
Also, make sure bank logs are enabled in the config file of the bank module.

**Comment by Evalutik** [comment]
Forgot about module config file, sorry
