### ISSUE TITLE
island permissions not working

### ISSUE THREAD

**Issue by Zoometryfr** [BG-Software-LLC/SuperiorSkyblock2#1802]
### Minecraft's Version

minecraft version 1.19.4

### Plugin's Version

SuperiorSkyblock2-2023.2.jar

### Describe the bug

when i put the permissions in lp, it just wont work in game. it says command not found, type /help like if you get a command wrong in vanilla

### To Reproduce

as far as i know nothing happened. i went to set up permissions and it just didnt work

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/139131418/d69eb04b-4508-4add-9f87-d2cdaca9f1c9)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/139131418/2e08856b-bfa0-473d-afd8-dd1805fbf2b6)

thats is i do /island, and yes, the permission is in luckperms

**Comment by Zoometryfr** [comment]
nevermind, it works all the sudden, sorry for the disturbance

**Comment by Evalutik** [comment]
Btw what permissions are responsible for the fact that the player can only create an **certain** type of island/change the biome of the island only to a **certain** one/change  only a **certain **island settings/ so on..? 
`For example, I want the player to be able to create a forest island, but to create a mushroom and desert island, he must buy a donate. ` How can i fo this?
Or
`I would like the player to only be able to manage some of the island's settings (can switch the weather but can't switch day/night) until he buys a donation.`

And so on
What permissionis responsible for this?

**Nothing on the wiki.**

**Comment by OmerBenGera** [comment]
> Btw what permissions are responsible for the fact that the player can only create an **certain** type of island/change the biome of the island only to a **certain** one/change only a **certain **island settings/ so on..? `For example, I want the player to be able to create a forest island, but to create a mushroom and desert island, he must buy a donate. ` How can i fo this? Or `I would like the player to only be able to manage some of the island's settings (can switch the weather but can't switch day/night) until he buys a donation.`
> 
> And so on What permissionis responsible for this?
> 
> **Nothing on the wiki.**

Regarding the island types, you can assign custom permissions to items - it is in the wiki.
Regarding the other menus, you cant.

Please do not seek for support on the issues tracker, use the discord server instead.

**Comment by Evalutik** [comment]
> 

I can indeed restrict the player from accessing the menu to create an island, but the player can still create an island with the `/is create` command, right? And if the player does not have permission `superior.island.create`, then he will not be able to create an island at all, even if the menu is available.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126126362/8419b9b4-9107-4425-8537-c929db1baf6d)
I asked about this issue earlier on discord but got no answer ;( Sorry for this

**Comment by OmerBenGera** [comment]
The plugin makes sure the player the player has permission even using the create command.
