### ISSUE TITLE
Zombie in Nether

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/SuperiorSkyblock2#1805]
### Minecraft's Version

Paper 1.19.4

### Plugin's Version

2023.2

### Describe the bug

When players kill pig zombies, zombies appear

### To Reproduce

Kill pig zombies
![screenZombie](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/53669476/44e4b5a5-1b2f-4a26-986e-e507e56fe8d2)

**Comment by OmerBenGera** [comment]
Not related to SuperiorSkyblock.
