### ISSUE TITLE
[Bug] SuperiorSkyblock permission crops

### ISSUE THREAD

**Issue by NoHere32** [BG-Software-LLC/SuperiorSkyblock2#1810]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/123643370/4f7e7a63-326c-4053-9a49-3e7aca30f533)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/123643370/caee0538-85e9-4ca6-a775-19c1ad3f2508)

### Describe the bug

So the bug is as simple as anything...
So the "jump on crops" permission in /is permissions removes the ability to put good meal on sweets berrys

### To Reproduce

to see an island
faire /is permissons
disable plantation breaking when jumping on it

**Comment by ArDiDEx** [comment]
> I don't understand what the bug is.

Hey! 
He is talking about the "farm_trampling" permission messing with a member's ability to put bone meal on sweet_berries

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
