### ISSUE TITLE
lighting bug

### ISSUE THREAD

**Issue by kbcode85** [BG-Software-LLC/SuperiorSkyblock2#1812]
### Minecraft's Version

paper-1.20.1-84

### Plugin's Version

SuperiorSkyblock2-2023.2

### Describe the bug

light on the island bugs
reconnecting to the server helps however when i create a new island it's back

![2023-07-22_13 24 42](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20464140/08179a26-1c96-4a99-8e3d-06689f3660dd)
![2023-07-22_13 26 06](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20464140/bc589363-292a-4c59-acf8-e4be46d5c8ac)
![2023-07-22_14 13 05](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20464140/0984ff88-b59b-4283-9b53-d20986537418)
![2023-07-22_14 37 59](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20464140/3a5c59d1-0e95-4075-a660-9c64b871af85)
![2023-07-22_14 38 26](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/20464140/f28f6395-3e59-4a90-9769-2354541c5e97)

### To Reproduce

just create a new island

**Comment by KvasirQc** [comment]
PS: When we broke a few leaves, the shadow goes away

**Comment by exzolink** [comment]
Enable lighting-update in config

**Comment by SrMonsterYT** [comment]
Minecraft's Version

This server is running Pufferfish version git-Pufferfish-15 (MC: 1.20.1)

Plugin's Version

SuperiorSkyblock2-2023.2-b61


the same thing happens to me.

bug 1: https://prnt.sc/MOLdidvZ0DkC
bug 2: https://prnt.sc/l9rjUPa7fGjD

**Comment by SrMonsterYT** [comment]
> Enable lighting-update in config

this solved my problem

**Comment by OmerBenGera** [comment]
@kbcode85 @KvasirQc Does it work for you as well?

**Comment by Teyir** [comment]
> @kbcode85 @KvasirQc Does it work for you as well?

Hello,

I have the same problem and with the setting lighting-update it's work great 

(paper 1.20.1 #126)
SSB #69

**Comment by OmerBenGera** [comment]
Awesome.

I am closing this for now.
Make sure you set `lighting-update` to true.
