### ISSUE TITLE
Hungarian Translation

### ISSUE THREAD

**Issue by Davee09015** [BG-Software-LLC/SuperiorSkyblock2#1813]
### Minecraft's Version

Purpur, 1.18.2

### Plugin's Version

2023.2

### Describe the bug

Please also do a Hungarian translation for the plugin.There are already so many people wanting and looking forward to it.

### To Reproduce

There is no Hungarian language, although it has been written in many places that there is.

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/110773329/0ab44bcc-18de-4843-96a6-6137f670152f)

**Comment by OmerBenGera** [comment]
I am not an Hungarian myself, sadly I cannot do it by myself.
You cab donate one if you wish :)
