### ISSUE TITLE
Multiverse-NetherPortals can not link nether portal in the island to nether world

### ISSUE THREAD

**Issue by YKDZ** [BG-Software-LLC/SuperiorSkyblock2#1816]
### Minecraft's Version

git-Purpur-2018 (MC: 1.20.1)*

### Plugin's Version

SuperiorSkyblock2-2023.2-b56

### Describe the bug

I want to set the nether portal target of the island world as a custom nether world, but the Multiverse-NetherPortals configuration is invalid.

### To Reproduce

1. Use this config in Multiverse-NetherPortals
https://pastebin.com/CHAy2NJP
2. Find that the nether portal can not take player to world_nether.

**Comment by OmerBenGera** [comment]
SSB overrides any nether interaction in the island worlds.
You can disable this behavior by disabling nether worlds.

**Comment by YKDZ** [comment]
I set worlds.nether.enabled to false in config.yml but Multiverse-NetherPortals still not work.

**Comment by OmerBenGera** [comment]
What happens when you try to enter nether portal when having the world disabled?

**Comment by YKDZ** [comment]
Nothing, no error in the console and no message in game. Player can only hear the sound effect of nether portal end, and then nothing happens.

**Comment by OmerBenGera** [comment]
Please enable debug mode (change the globaldebug section to higher value), and check what is printed from the NetherPortals plugin when you enter a portal in SSB's islands world.

**Comment by YKDZ** [comment]
https://pastebin.com/nQQFiZWK

**Comment by OmerBenGera** [comment]
What debug level did you set it to ?

**Comment by YKDZ** [comment]
Level 3

**Comment by OmerBenGera** [comment]
> Level 3

Try setting it higher? 100?
I am expecting some other messages that I don't see in there.

**Comment by YKDZ** [comment]
java.lang.IllegalArgumentException: debugLevel must be between 0 and 3!
When I set it to higher level, mv will print this error into console, so I think the max level is 3.

**Comment by OmerBenGera** [comment]
> java.lang.IllegalArgumentException: debugLevel must be between 0 and 3! When I set it to higher level, mv will print this error into console, so I think the max level is 3.

Hmm, interesting.
I will look into it more deeply later.

**Comment by YKDZ** [comment]
I conducted another test and the output of Debug seems to have changed:
https://pastebin.com/WmeCNBq7

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by YKDZ** [comment]
It works properly in latest dev build. Thank you for your unremitting support!

**Comment by OmerBenGera** [comment]
:)
