### ISSUE TITLE
item on border issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1817]
### Minecraft's Version

pufferfish 1.19.3

### Plugin's Version

dev build b56

### Describe the bug

Sometimes when breaking items near the border, the item can be stuck behind the border (so player can't take it) or it can directly fall into the void

### To Reproduce

Here is a video of a player that had the issue : https://youtu.be/UCcT1m0F1fM

**Comment by OmerBenGera** [comment]
Nothing to be done regarding this.
Borders are visual only, therefore items and entities can go through them.

**Comment by WarnDa** [comment]
> Nothing to be done regarding this. Borders are visual only, therefore items and entities can go through them.

But possible to add a delay between two messages it sends ? To avoids spamming player (so I can change the message to "you can't take this item, we can't do nothing" ?

**Comment by OmerBenGera** [comment]
What message is being sent?

**Comment by WarnDa** [comment]
BUILD_OUTSIDE_ISLAND

**Comment by OmerBenGera** [comment]
Will look into this.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
I decided to let players pickup items from outside of the border if it's in the first block, as it makes no sense to not be able to pick it up.
