### ISSUE TITLE
Invisible zombie pigman

### ISSUE THREAD

**Issue by Xitryne** [BG-Software-LLC/SuperiorSkyblock2#1818]
### Minecraft's Version

Paper 1.19.4 

### Plugin's Version

2023.2

### Describe the bug

An invisible pigman zombie kills the player on his island, but no one can see him, even when disconnecting, reconnecting etc...

### To Reproduce

The player goes into the Nether, returns to his island and is killed by an invisible pigman zombie. He has a portal on his island, but not in the Nether. The bug also persists when there is no portal on his island.

**Comment by OmerBenGera** [comment]
Nothing related to SSB.
SSB does not handle any entities what so ever.
