### ISSUE TITLE
Wrong database name in removePersistentDataContainer method

### ISSUE THREAD

**Issue by Tejnox** [BG-Software-LLC/SuperiorSkyblock2#1821]
### Minecraft's Version

git-Purpur-1985 (MC: 1.19.4)*

### Plugin's Version

[12:07:47 INFO]: SuperiorSkyblock2 version 2023.2
[12:07:47 INFO]: Feature packed Skyblock core.
[12:07:47 INFO]: Website: https://bg-software.com/
[12:07:47 INFO]: Author: Ome_R

### Describe the bug

When you try to delete custom data for a specific island, an error pops up stating that the **'island'** column is missing in the **'players_custom_data'** database. The reason for this is the incorrect column name in the **'removePersistentDataContainer()'** method in **IslandsDatabaseBridge** class.

```java
    public static void removePersistentDataContainer(Island island) {
        runOperationIfRunning(island.getDatabaseBridge(), databaseBridge ->
                databaseBridge.deleteObject("players_custom_data", createFilter("island", island)));
    }
```

### To Reproduce

 You can try adding some custom data to the island first using the command **/is admin data set island Test test 1**, and then attempt to remove it with the command **/is admin data remove island Test test**. When attempting to remove the value, it will be deleted locally, but an error will be displayed in the console during the attempt to remove it from the database.

### Additional Information

![r4s5e6t2](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/68534126/4b17cd9b-aa3a-409d-9ad0-f35517c34cb4)

**Comment by OmerBenGera** [comment]
Fixed with your PR :)
