### ISSUE TITLE
SkinsRestorer problem again..

### ISSUE THREAD

**Issue by ZappySK** [BG-Software-LLC/SuperiorSkyblock2#1830]
### Minecraft's Version

Pufferfish 1.20.1

### Plugin's Version

SuperiorSkyBlock2 dev #60
SkinsRestorer latest dev version

### Describe the bug

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/76651966/482d2501-b1e2-4a1a-b048-bbdb5c318921)

### To Reproduce

After server restars, the skulls of players for example in /is top are "Steve" heads..

**Comment by OmerBenGera** [comment]
Seems like SkinsRestorer might have broken their API.
What version of SkinsRestorer are you using?

**Comment by ZappySK** [comment]
> Seems like SkinsRestorer might have broken their API. What version of SkinsRestorer are you using?

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/76651966/e136df39-9c04-4178-9fbf-ed679d6ef312)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by ZappySK** [comment]
https://pastebin.com/v5i3m8uU

**Comment by OmerBenGera** [comment]
Send me

**Comment by OmerBenGera** [comment]
Send me the entire session logs.
Upload them to pastebin and send a link to them here

**Comment by ZappySK** [comment]
https://pastebin.com/mJ8MHPvU

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs

**Comment by ZappySK** [comment]
Problem fixed, thank you.
