### ISSUE TITLE
Missing placeholder {value_<block>} for some items.

### ISSUE THREAD

**Issue by Merunko** [BG-Software-LLC/SuperiorSkyblock2#1833]
### Minecraft's Version

Minecraft Paper server version: 1.19.4

### Plugin's Version

2023.2

### Describe the bug

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/141312536/5835ab36-7df2-4ba6-a357-3e820fa29a10)

### To Reproduce

required-items:
  '1':
    types:
      - 'BREAD'
    amount: 512
  '2':
    types:
      - 'BEEF'
    amount: 256
  '3':
    types:
      - 'PORKCHOP'
    amount: 128
    
    - '&6Breads Collected: &7{value_bread}/512'
    - '&6Raw Beefs Collected: &7{value_beef}/256'
    - '&6Raw Porkchops Collected: &7{value_porkchop}/128'

**Comment by Merunko** [comment]
These 2 also not working.
{value_red_mushroom}
{value_brown_mushroom}

**Comment by Merunko** [comment]
@OmerBenGera Is this an issue or was I using the wrong <block> name inside the placeholder?

**Comment by OmerBenGera** [comment]
Please upload the entire mission file to pastebin and send a link to it here

**Comment by Merunko** [comment]
https://pastebin.com/u9B10ety

**Comment by OmerBenGera** [comment]
What is `ItemsMissions_v2`?
This is not a mission jar of SSB - have you tried contacting the developer that made it for you?

**Comment by Merunko** [comment]
It's just the same with ItemsMissions jar of SSB but with extra naming format inside the itemFormat class. If you try it with ItemsMissions jar, the original jar from SSB, the issue is still there. It still shows {value_itemname} without actually showing the tracked block value for
{value_bread}
{value_beef}
{value_porkchop}
{value_red_mushroom}
{value_brown_mushroom}

**Comment by OmerBenGera** [comment]
Item missions do not track this type of information.
This is not a bug.

ItemMissions check for the amount of items required to complete the mission in the inventory only as soon as you try to complete it.
Instead of using the ItemMission, you might want to look at FarmingMission, which tracks your data.
