### ISSUE TITLE
Island bank deposit error

### ISSUE THREAD

**Issue by housemazter** [BG-Software-LLC/SuperiorSkyblock2#1836]
### Minecraft's Version

java 19, paper latest 1.20.1 #100 build

### Plugin's Version

latest stable 2023.2 
dated 24/06/2023 21:21:13

### Describe the bug
"deposit" command have some issues...

STR
1) go to island of friend
2) take "member" role
3) run /is deposit 100

AR
1) answer from plugin in player chat:
"Error | Successful."
2) no money on the island bank account
3) charged money from player

ER
1) money appended to bank account
2) charged from player
3) message in chat - "Deposit is done sucessf..."

### To Reproduce

STR
1) go to island
2) run /is deposit 100

### Additional Information

thank you

**Comment by OmerBenGera** [comment]
Thia ia an issue with your econony plugin.
When a transaction succeeds, they set the error message in Vault as "Successful", which makes no sense.
They should instead leave it empty.

The solution is either to report it over them or switch to another economy plugin.

**Comment by housemazter** [comment]
yep, i asked they and have an answer:
"Why don't they just check the type of the response? Why checking the error message? It makes no sense."

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by housemazter** [comment]
it works! thank you! awesome!
