### ISSUE TITLE
Generate islands with significant lag

### ISSUE THREAD

**Issue by YKDZ** [BG-Software-LLC/SuperiorSkyblock2#1838]
### Minecraft's Version

Purpur 1.20.1

### Plugin's Version

SuperiorSkyblock2-2023.2-b65

### Describe the bug

When generating a new island, it will cause huge lag.
Even generate one block skyblock will cause huge lag.
My platform is R7 7900X, but generate a new island will let the tps drop to 7 to 10.
https://spark.lucko.me/cfMbQZYMRv
https://spark.lucko.me/U8UP1VdnCf

### To Reproduce

Generate a new island

### Additional Information

I'm using datapack (like Territh and Incendium) to change the other world, not sure if that has anything to do with it...

**Comment by OmerBenGera** [comment]
None of the provided sprak profilers show any indication to lag.
Does it happen on a server with only SSB installed?

**Comment by YKDZ** [comment]
No, this is not an SSB issue. SSB alone works fine.
After restoring the issue locally and testing it, I realized that it's a lag caused by the SSB-compatible module provided by the plugin known as QuickShop-Hikari.
I will report this to them.

**Comment by YKDZ** [comment]
https://github.com/Ghost-chu/QuickShop-Hikari/issues/1026
They have fixed it.
