### ISSUE TITLE
Loot upgrade not working

### ISSUE THREAD

**Issue by nejcmiholic** [BG-Software-LLC/SuperiorSkyblock2#1840]
### Minecraft's Version

Paper 1.20.1-108, ( I have also tested latest paper 1.20.1-117)

### Plugin's Version

SuperiorSkyblock2 [[v2023.2]] (latest on spigot.com)
I have also tested the latest build SuperiorSkyblock2-2023.2-b67

### Describe the bug

The problem is that mobs do not have multiplied drops when island (loot upgrade) is upgraded and the mob stack is more than 1.

### To Reproduce

Use Rose Stacker, upgrade Island loot multiplier, summon 2 or more mobs.

### Additional Information

I am using Rose Stacker (Latest verison) with SuperiorSkyblock2. I have tested this in private server with only this 2 plugins. When you upgrade island (loot upgrade) and a single mob spawns, dropped loot will be multiplied, BUT when for example 2 or more spawn none will have multiplied drop not even the first one.

**Comment by OmerBenGera** [comment]
SSB changes the drops in the EntityDeathEvent.
If RoseStacker doesn't fire this event or doesn't take the drops from the event, there's nothing SSB can do regarding this.

Contact RoseStacker's support for further help.
