### ISSUE TITLE
Error while enabling plugin

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#1842]
### Minecraft's Version

paper 1.20.1 - b126

### Plugin's Version

b72

### Describe the bug

When I'm starting my server I have this error
`>.... [12:38:55 INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.2-b72
>.... [12:38:55 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while enabling the plugin:
>.... [12:38:55 WARN]: java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
>.... [12:38:55 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
>.... [12:38:55 WARN]: at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.loadListOrSection(SettingsContainer.java:577)
>.... [12:38:55 WARN]: at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.config.SettingsContainer.<init>(SettingsContainer.java:245)
>.... [12:38:55 WARN]: at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.config.SettingsManagerImpl.<init>(SettingsManagerImpl.java:79)
>.... [12:38:55 WARN]: at SuperiorSkyblock2-2023.2-b72.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:226)
>.... [12:38:55 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
>.... [12:38:55 WARN]: at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
>.... [12:38:55 WARN]: at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
>.... [12:38:55 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
>.... [12:38:55 WARN]: at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
>.... [12:38:55 WARN]: at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
>.... [12:38:55 WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
>.... [12:38:55 WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
>.... [12:38:55 WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
>.... [12:38:55 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
>.... [12:38:55 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
>.... [12:38:55 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)`

### To Reproduce

Start the server

### Additional Information

After all my plugins are loaded, my server crash and restart.
If I remove SuperiorSkyblock, I don't have this problem

**Comment by Teyir** [comment]
After some tests, I have this error after this commit : https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/f43d2ebdbda5c06a71bf4b53c0fbc60bd9be77dc

(Build 71)

**Comment by OmerBenGera** [comment]
Please upload your config to pastebin and send a link to it here.

**Comment by Teyir** [comment]
> Please upload your config to pastebin and send a link to it here.

https://hastebin.com/share/pegeserawo.yaml

**Comment by OmerBenGera** [comment]
> > Please upload your config to pastebin and send a link to it here.
> 
> https://hastebin.com/share/pegeserawo.yaml



> > Please upload your config to pastebin and send a link to it here.
> 
> https://hastebin.com/share/pegeserawo.yaml

You configured the entity limits incorrectly.
You should remove the `-` from the start of the line of the PHANTOM.

**Comment by Teyir** [comment]
> > > Please upload your config to pastebin and send a link to it here.
> > 
> > 
> > https://hastebin.com/share/pegeserawo.yaml
> 
> > > Please upload your config to pastebin and send a link to it here.
> > 
> > 
> > https://hastebin.com/share/pegeserawo.yaml
> 
> You configured the entity limits incorrectly. You should remove the `-` from the start of the line of the PHANTOM.

Ok thank you it's good.

But why I have this problem now ? 

I'm using this config sync 2021

**Comment by OmerBenGera** [comment]
> > > > Please upload your config to pastebin and send a link to it here.
> > > 
> > > 
> > > https://hastebin.com/share/pegeserawo.yaml
> > 
> > 
> > > > Please upload your config to pastebin and send a link to it here.
> > > 
> > > 
> > > https://hastebin.com/share/pegeserawo.yaml
> > 
> > 
> > You configured the entity limits incorrectly. You should remove the `-` from the start of the line of the PHANTOM.
> 
> Ok thank you it's good.
> 
> But why I have this problem now ?
> 
> I'm using this config sync 2021

I changed the way some sections are read and they must be in the expected type (either a list or a section)

**Comment by Teyir** [comment]
Ok thank you
