### ISSUE TITLE
The Cobblestone Generator when STONE block changed to another

### ISSUE THREAD

**Issue by housemazter** [BG-Software-LLC/SuperiorSkyblock2#1843]
### Minecraft's Version

java 19, paper latest 1.20.1 #126 build

### Plugin's Version

Dev Build #72 12/08/2023

### Describe the bug

if STONE was not used in the list of /modules/upgrades/config.yml:generator-rates, 
then the Generator do not generate any blocks at all

### To Reproduce

STR
0) stop the server
1) open /modules/upgrades/config.yml in editor
2) go to any level of "generator-rates:"
3) change "STONE: 95" to "COBBLESTONE: 95"
4) start server
5) the generator do not generate any block. even if we have two blocks like STONE: 95 and COAL_ORE: 5. no ore, no cobblestone.

### Additional Information

...continue checking back:
6) stop the server
7) return back STONE: 95 instead of COBBLESTONE: 95
8) start server
9) generator works! and generate STONE and ores.

**Comment by OmerBenGera** [comment]
Check your rates in the server with `/is admin show`.
Send me a screenshot of the output of the command as well.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue still occurs, let me know
