### ISSUE TITLE
Error when creating a mission

### ISSUE THREAD

**Issue by ShopHunter1212** [BG-Software-LLC/SuperiorSkyblock2#1852]
### Minecraft's Version

1.20.1

### Plugin's Version

SuperiorSkyblock2-2023.2-b72

### Describe the bug

When I make a custom mission it does not sort them to the right place even though I have entered the required tasks.

### To Reproduce

Make a new mission and restart the server and then you will see that it does not sort out

**Comment by OmerBenGera** [comment]
Use the `weight` section in order to sort your missions as you wish.
You can find more useful information on the wiki. If you need further help, as on the discord server.

**Comment by ShopHunter1212** [comment]
how can I set the weight I do not quite understand where I have to enter the in the missions

**Comment by OmerBenGera** [comment]
https://wiki.bg-software.com/superiorskyblock/overview/missions
