### ISSUE TITLE
Stacking blocks fast for island levels misses some blocks

### ISSUE THREAD

**Issue by ValdemarF20** [BG-Software-LLC/SuperiorSkyblock2#1853]
### Minecraft's Version

1.17.1 Purpur

### Plugin's Version

1.9.0-b579

### Describe the bug

If I place 64 blocks to increase island level quickly. Then after all are placed and gone from the inventory, the stack does not contain them all, some blocks are just gone.  In my latest test I placed 64 and then there were 43 actual blocks when they were gone from my inventory.

### To Reproduce

Place valuable blocks that increase island level / blocks that can be stacked, as quick as possible.

**Comment by ValdemarF20** [comment]
It seems that some of the blocks placed, after they have been removed are still calculated for the island levels, even though they have disappeared completely.

**Comment by OmerBenGera** [comment]
Do you talk about the stacking-blocks mechanism of the plugin itself, or a third-party plugin?
Also, please take a video of the issue and upload it to an online streaming service (youtube, for example) and send a link to it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ValdemarF20** [comment]
Sorry, I'm talking about the stacking-blocks mechanism of the plugin itself.

**Comment by OmerBenGera** [comment]
I used an auto clicker and all the blocks were placed for me.
Do you mind taking a video of the issue? Upload it to YT or any other online streaming service and send a link to it here (GIF is also possible)

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue persists, let me know
