### ISSUE TITLE
SuperiorWorld wont change

### ISSUE THREAD

**Issue by daoshii** [BG-Software-LLC/SuperiorSkyblock2#1856]
### Minecraft's Version

1.20.1 Paper build 108 AND 163 (latest)

### Plugin's Version

Latest Stable 2023.2, And latest dev #73

### Describe the bug

SuperiorSkyblock world is always created and used.

```
# Set the name of the islands world.
  world-name: skyblock
```
  
 I've deleted 'backup', 'datastore', all worlds except my hub named 'piratehub'. Not sure if related but also deleted 'cache' in server root. And then I start server back up and 'SuperiorSkyblock' world reappears but NOT 'skyblock' world.
 
 I've also attempted following the steps above and also creating my own MV void world named skyblock, However SuperiorSkyblock was still generated and used for islands.

### To Reproduce

Install SuperiorSkyblock on a test server containing only the most essential plugins used by servers - "CMI, FAWE, LuckPerms, Multi-Verse, PackListenerAPI, PlaceholderAPI, ProtocolLib, Vault, WorldGuard, WorldGuardExtraFlags"
and attempt to change the island world.

### Additional Information

https://pastebin.com/kf2gqnek

**Comment by OmerBenGera** [comment]
Try it on a server with only SSB installed. Make sure you delete the datastore folder inside SSB's folder, and change the world name to whatever you'd like. Let me know if it works.

**Comment by daoshii** [comment]
It did not work, heres the new log with only SuperiorSkyblock, I deleted datastore, all world files, and changed config as follows before starting.
`world-name: skyblock`
```
[06:37:20 INFO]: [SuperiorSkyblock2] Enabling SuperiorSkyblock2 v2023.2
[06:37:20 INFO]: Preparing start region for dimension minecraft:superiorworld
```
https://pastebin.com/77iCQMPJ

**Comment by OmerBenGera** [comment]
Make sure you update to latest dev build.
It works fine for me.

**Comment by daoshii** [comment]
At the time of my OP build #73 was the latest...... I also tested with the STABLE release as you can see in the OP. Also with multiple paper versions as stated in the OP.
As of 30 minutes ago their was a new dev build but I can test that as well.
It does not work fine for me.
https://pastebin.com/FWPgm1BZ

**Comment by daoshii** [comment]
Heres a new error, after regenerating the entire SuperiorSkyblock folder and attempting to change the world. After this point, it doesnt matter how many time i delete the datastore folder, it ignored 'world-name' in config and is cached somewhere because the error never gets thrown again, unless I regenerate the entire SuperiorSkyblock folder again.
https://pastebin.com/3kAdc3ZQ

**Comment by OmerBenGera** [comment]
> Heres a new error, after regenerating the entire SuperiorSkyblock folder and attempting to change the world. After this point, it doesnt matter how many time i delete the datastore folder, it ignored 'world-name' in config and is cached somewhere because the error never gets thrown again, unless I regenerate the entire SuperiorSkyblock folder again. https://pastebin.com/3kAdc3ZQ

This error occurs after you successfully changed the world name.
This is because you kept the spawn location in the SuperiorWorld world, which doesn't exist anymore.

**Comment by daoshii** [comment]
After deleting and regenerating the entire SuperiorSkyblock folder, and updating the "spawn location" in the config to the new world name, all works well.
But it is cached/stored somewhere other than the datastore folder.

**Comment by OmerBenGera** [comment]
The world's name is only saved in the db, nowhere else (unless you have MySQL DB, then it would be saved in the remote DB)
I am closing this for now.
