### ISSUE TITLE
Islands calculation produces incorrect results when chunks are not loaded

### ISSUE THREAD

**Issue by ArDiDEx** [BG-Software-LLC/SuperiorSkyblock2#1857]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/48607042/ded588a8-4144-4faa-917c-1f298795aad5)
(default configs)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/48607042/3d53983a-b881-492e-86e5-bbc4e767837a)
(default configs)

### Describe the bug

When recalculating an island and chunks are unloaded incorrect results show up in the /is blocks afterwards

### To Reproduce

- create an island and place for example 6 hoppers
- /is recalc just to be sure
- /is blocks, on the menu you have 6 hoppers placed which is correct
- move far away so the chunks aren't loaded anymore
- /is recalc
- /is blocks, on the menu you wont have 6 hoppers anymore but a random number or none

### Additional Information

https://streamable.com/w5zp5t

**Comment by OmerBenGera** [comment]
It works just fine for me.
Also, does it happen only with hoppers?

**Comment by ArDiDEx** [comment]
happens with every block, seems like the island recalculation with offline chunks sometimes takes an older version of the chunk to do the calculation (not sure how?)

**Comment by OmerBenGera** [comment]
Try it on a Paper server with only SSB installed, as it seems to work just fine for me.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ArDiDEx** [comment]
> Try it on a Paper server with only SSB installed, as it seems to work just fine for me.

Just did it with only ssb and viaversion (which shouldnt influence the results at all)
Still works for me
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/48607042/ee4dbf03-0750-4d6b-ae78-d138b18a552f)

Before trying the bug i described above try setting your island border size to the max value you can (for me its 200)
then place a few hoppers or chests on your island, go to the furthest corner, do /is recalc then /is blocks and you should see a value thats not correct (atleast for me it does)

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
Are you able to take a video of the issue?

**Comment by ArDiDEx** [comment]
> I can't seem to replicate the issue Are you able to take a video of the issue?

https://streamable.com/y49gqp
here is a vid of me doing it on a server with default paper settings, and close to default settings on superior too (modified worth&level and default block limits)
I have an island with a border size of 200 on the vid

**Comment by ArDiDEx** [comment]
oh and yeah at the end I removed a chest and did /is recalc and then it seemed like the chest amount was correct again but hoppers were still not correct
the bug is very strange

**Comment by ArDiDEx** [comment]
https://streamable.com/vnqycy
did a vid from scratch this time (so like with no island at the start)
though on this one spamming recalc seemed to fix the issue bit by bit

**Comment by OmerBenGera** [comment]
Run the following commands:
`/is admin debug calculate_island`
`/is admin debug chunk_calculation`
Then, run `/is recalc` from the corner of the border, and check the console for logs.
Send me these logs once the recalculation task is finished

**Comment by ArDiDEx** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/48607042/40b0dc93-d41c-453e-8b28-2c8a35ba2eb4)
chest count was off by 4 (10 instead of 14) after the recalc

**Comment by OmerBenGera** [comment]
Are the missing chests in any of the chunks printed in there?

**Comment by ArDiDEx** [comment]
chests were in the chunks:
38 37
37 37

do you perhaps still have the test server open (the one that was for the module)? so i can try to do it there and show it to you ingame directly

**Comment by OmerBenGera** [comment]
Does it happen if you go to the spawn island and do it from there?

**Comment by ArDiDEx** [comment]
> Does it happen if you go to the spawn island and do it from there? Also, can you test it with latest version of Paper (for 1.20.1)

just tried with spawn and it works too
https://streamable.com/3wsmc4

gonna try with paper 1.20.1 now

**Comment by ArDiDEx** [comment]
https://streamable.com/ln6m51
works on 1.20.1

**Comment by OmerBenGera** [comment]
Upload your block values to pastebin

**Comment by ArDiDEx** [comment]
> Upload your block values to pastebin

https://pastebin.com/pmmDEiMu

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by ArDiDEx** [comment]
It works, thanks 👍
