### ISSUE TITLE
Island home sometimes teleports onto celing

### ISSUE THREAD

**Issue by Pjooo** [BG-Software-LLC/SuperiorSkyblock2#1858]
### Minecraft's Version

git-Purpur-2036 (MC: 1.20.1)

### Plugin's Version

2023.2-b73

### Describe the bug

Sometimes island home set under leaves / celing, it teleports them up, on the tree. 

For example, as on screen. When /is setteleport is set on the red wool, command /is home teleports player up on the leaves.

Sometimes it works fine. 3 blocks left, it works no issues. It's random bug, some other combinations, and other islands also experience it.

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/36714891/9f54ce75-5722-4b78-a34b-be78c75adb71)

### To Reproduce

Build the same tree, and set home under it.

**Comment by OmerBenGera** [comment]
If the home location is considered "not safe" (not on a full block, another block is blocking the home, etc), it will attempt to find a better place for the teleportation - in your case, that ceiling block was the first block it found.

Do you have any block below that red wool?

**Comment by Pjooo** [comment]
Yes, there is block below red wool. This location is 100% safe, it should teleport directly there.

On 1.19.4 version of your plugin this exact location was safe, and player was teleported right there.

**Comment by OmerBenGera** [comment]
> Yes, there is block below red wool. This location is 100% safe, it should teleport directly there.
> 
> On 1.19.4 version of your plugin this exact location was safe, and player was teleported right there.

Create a new island and find out how to replicate the issue.

**Comment by Pjooo** [comment]
Issue is apparent on my custom island schematic. After updating to 1.20 your plugin spawns player on top of the tree. Before updating, on 1.19.4, player after creating island was spawned under the tree in corect place.

I can send you schematic on priv. Where do you want it.

**Comment by OmerBenGera** [comment]
You can use `/is admin debug find_safe_teleport` to find out why the plugin thinks your teleport location is not safe.
(If you had already teleported, then the plugin saved the new location as the new home, therefore you'll need to recreate your island for it to find a new safe spot)

**Comment by OmerBenGera** [comment]
I looked into it again and saw some behaviors that I didn't like.
I recoded the system and hopefully it works as intended now.
Check out latest dev build, let me know if it is better.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Pjooo** [comment]
Newest version fixed it. Thanks!
