### ISSUE TITLE
Generators dont work after key optimization

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1859]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b76

### Describe the bug

Generators dont generate blocks after key optimization update

### To Reproduce

Build cobble gen and break block

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Run `/is admin show <island>`, let me know what the rates are.
(A screenshot is the best)

**Comment by exzolink** [comment]
https://imgur.com/yRhJiti

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by exzolink** [comment]
Ok, thank you, i'll write back later.

**Comment by exzolink** [comment]
Yes, works as it should, thanks
