### ISSUE TITLE
Is recalculation does not take minecarts into account

### ISSUE THREAD

**Issue by ArDiDEx** [BG-Software-LLC/SuperiorSkyblock2#1860]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/48607042/90903089-1160-4ed8-b993-de79e83fc3ba)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/48607042/b154a522-51f9-4957-96fe-6f0748213b3f)

### Describe the bug

is recalculation does not take minecarts into account and breaks the hopper furnace, tnt, command_block and chest limits

### To Reproduce

- place a hopper
- place a minecart hopper
- /is blocks shows 2 hoppers
- /is recalc
- /is blocks now shows 1 hopper
- breaking the minecart now makes your island drop to 0 placed hoppers until the next recalc

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
