### ISSUE TITLE
Entity limits feature does not work on unloaded chunks

### ISSUE THREAD

**Issue by ForesterPL** [BG-Software-LLC/SuperiorSkyblock2#1862]
### Minecraft's Version

Purpur 1.20.1

### Plugin's Version

2023.2 stable

### Describe the bug

With enabled entity limits plugin is able to check entities only on loaded chunks, when players are nearby.
For example: I have an island in normal world and in Nether. In config I set the maximum limit of pigs to 5. When I am the only one person standing on my island in normal world, I can have only 5 pigs. When I go to the Nether island and again I am the only one there, I can still summon 5 pigs. However, if another player visits my island and they are in opposite world (i.e. me in normal, they in Nether), entity limit system takes both worlds into account, so when I have 5 pigs in normal world, I am unable to spawn another one in Nether as I could before. 

### To Reproduce

1. `entity-limits: true` in /modules/upgrades/config.yml
2. In `default-values.entity-limits` put `- 'PIG:5'` in main config.yml
3. `world.nether.enabled: true` in main config.yml
4. Create an island and unlock Nether world.
5. Summon 5 pigs in normal world on your island. You can see that you are unable to exceed this limit.
6. Go to the Nether. There you can summon another 5 pigs.
7. Kill every spawned pig (in normal and Nether world). Teleport another player on your island. They have to stay in normal world and you have to stay in the Nether. If you summon 5 pigs in your current location, another player is unable to spawn another one.

**Comment by OmerBenGera** [comment]
Entity limit work only on loaded chunks, that's intended.
I'll look into what can be done regarding this.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by ForesterPL** [comment]
Sorry for delay, it seems like it's working now
