### ISSUE TITLE
Opening container in vanish resets offline time

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1863]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

77

### Describe the bug

Opening any container in vanish resets offline time (SuperVanish plugin)

### To Reproduce

Type /v
Open chest
Check /is team

**Comment by OmerBenGera** [comment]
What is `/v`?

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.
I am in vanish mode (SuperVanish) and I open a chest in my island, it seems to work fine.

**Comment by OmerBenGera** [comment]
As I said, it doesn't occur for me.
I enter vanish mode, wait a few seconds, open a chest, and the timer continues.

Find out how to replicate the issue on a server with only SSB and SuperVanish installed. Make sure you provide exact steps on how to replicate it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by exzolink** [comment]
Didn't tested yet

**Comment by OmerBenGera** [comment]
Let me know once you did.

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue persists let me know
