### ISSUE TITLE
Broken level calculation (again)

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SuperiorSkyblock2#1864]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-61 (MC: 1.19.3)

### Plugin's Version

b-77

### Describe the bug

In the latest beta, the same bug that you previously fixed re-occurred.

### To Reproduce

https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1744

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/b34d46d7-d099-41db-9a16-011dbb57efa8)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/4876fe7a-52de-49af-9214-b91db983eb2a)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/c85bd35c-8614-4e6b-a8fc-7707eed0d258)

**Comment by OmerBenGera** [comment]
Hold an Iron Golem spawner in your hand, then type `/is value`, check what it says.

**Comment by Evalutik** [comment]
btw i also have a lot of problems with the level of the island and its cost, often when I place blocks it is calculated incorrectly or does not change. Still can’t get around to writing an issue.

**Comment by OmerBenGera** [comment]
> btw i also have a lot of problems with the level of the island and its cost, often when I place blocks it is calculated incorrectly or does not change. Still can’t get around to writing an issue.

This is not related to this issue.
Open a new bug report regarding this.

**Comment by Distolfix** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/b9270086-4f4e-45c9-86c3-37d6fd9f623b)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/73421268/023223d1-bb6e-4404-a9e0-e0bbf1852389)

**Comment by Distolfix** [comment]
In the beta 51 the level is 30 
in the beta 84 no value

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by Distolfix** [comment]
work
