### ISSUE TITLE
Low chance blocks in generator are not spawning

### ISSUE THREAD

**Issue by WaterArchery** [BG-Software-LLC/SuperiorSkyblock2#1868]
### Minecraft's Version

1.16.5 but also happens in 1.18.2

### Plugin's Version

Latest dev build #77 I also tried with #52 and latest stable version. All of them are not working.

### Describe the bug

In island generators if you set the generate block chance to below 1 like 0.5, it is not spawning that block. Instead of spawning that block, it spawns another random block.

### To Reproduce

You can set generator rates in upgrades.yml to this in one upgrade

     generator-rates:
       normal:
         STONE: 97
         COAL_ORE: 0.5
         IRON_ORE: 0.5
         LAPIS_ORE: 0.5
         GOLD_ORE: 0.5
         EMERALD_ORE: 0.5
         DIAMOND_ORE: 0.5

and mine the blocks in island generator. It will spawn cobblestone block always.

Also, other than this issue if you set generator block to COBBLESTONE instead of STONE it is not spawning at all. In latest dev builds after #52 spawning cobblestone block in generators is broken too.

**Comment by exzolink** [comment]
You can set only integer values

**Comment by OmerBenGera** [comment]
0.5 is not a valid chance.
The value you put there is the rate of the block to be spawned, not its percentage.
This means that the percentage of each block is calculated as the rate of the block divided by the total rates.
In your case, it's 0 / 97, which is 0.
