### ISSUE TITLE
Spawner value/level is not going onto the island value/worth

### ISSUE THREAD

**Issue by Swoochy** [BG-Software-LLC/SuperiorSkyblock2#1870]
### Minecraft's Version

1.19.4 Paper

### Plugin's Version

latest dev build (this this post)

### Describe the bug

setting the value/level of spawner is not doing anything towards the islands value, does not show in the /is top menu either

### To Reproduce

simply adding spawner value/level to the file

**Comment by OmerBenGera** [comment]
It works fine for me and other people, so you must be doing something wrong.
How did you configure a worth value for your spawners?

**Comment by Swoochy** [comment]
i have tried the following
MOB_SPAWNER:IRON_GOLEM: 10000
'MOB_SPAWNER:IRON_GOLEM': 10000
SPAWNER:IRON_GOLEM: 10000
'SPAWNER:IRON_GOLEM': 10000

none of these seem to be working

**Comment by OmerBenGera** [comment]
This is a known bug, looking into fixing it rn.

**Comment by Swoochy** [comment]
thank you.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.

**Comment by Swoochy** [comment]
can confirm it works with the layout of 

- SPAWNER:IRON_GOLEM: 10000

**Comment by Swoochy** [comment]
this maybe a sperate issue but this is now showing in the console when i place them

- [17:58:26 WARN]: Skipping Entity with id

**Comment by Distolfix** [comment]
it's not related to plugin. it's a simple warn of server

**Comment by Swoochy** [comment]
> it's not related to plugin. it's a simple warn of server

any way to remove this? - happens when island is disbanded also.

**Comment by Distolfix** [comment]
Use ConsoleSpamFix and put it in the config. They are useless spam, which you can avoid

**Comment by Swoochy** [comment]
how do i do this, i have never had this issue with that spam before


> Use ConsoleSpamFix and put it in the config. They are useless spam, which you can avoid

**Comment by Distolfix** [comment]
https://www.spigotmc.org/resources/console-spam-fix.18410/

**Comment by Swoochy** [comment]
> https://www.spigotmc.org/resources/console-spam-fix.18410/

what would i type in the config to stop the spam?

**Comment by OmerBenGera** [comment]
As @Distolfix said, this is not related to the plugin.
I am closing this for now :)
