### ISSUE TITLE
obsidian to lava on a foreign island

### ISSUE THREAD

**Issue by xsweetly** [BG-Software-LLC/SuperiorSkyblock2#1872]
### Minecraft's Version

Current: git-Purpur-1985 (MC: 1.19.4)*

### Plugin's Version

2023.2-b84

### Describe the bug

on a foreign island, you can make lava from obsidian if you click on it with an empty bucket.

### To Reproduce

click with empty bucket on obsidian on a foreign island.

**Comment by OmerBenGera** [comment]
I cannot replicate the issue.
Do you have `/is admin bypass` enabled maybe? Make sure you disable it before trying it.

**Comment by xsweetly** [comment]
> I cannot replicate the issue. Do you have `/is admin bypass` enabled maybe? Make sure you disable it before trying it.

bypass is not enabled.

**Comment by OmerBenGera** [comment]
> > I cannot replicate the issue. Do you have `/is admin bypass` enabled maybe? Make sure you disable it before trying it.
> 
> bypass is not enabled.

Are you able to do that on the spawn island as well?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue persists let me know
