### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by 4bxn** [BG-Software-LLC/SuperiorSkyblock2#1874]
### Minecraft's Version

Paper 1.20.1

### Plugin's Version

SuperiorSkyblock2-2023.2

### Describe the bug

04.09 03:42:06 [Server] WARN Plugin 'SuperiorSkyblock2' is creating timing 'Plugin: SuperiorSkyblock2 v2023.2 Event: DynamicRegisteredListener::IslandSchematicPasteEvent(IslandSchematicPasteEvent)' - this is deprecated behavior, please report it to the authors: Ome_R
04.09 03:42:06 [Server] INFO [SuperiorSkyblock2] Registered mission explorer_1
04.09 03:42:06 [Server] WARN Plugin 'SuperiorSkyblock2' is creating timing 'Plugin: SuperiorSkyblock2 v2023.2 Event: DynamicRegisteredListener::IslandSchematicPasteEvent(IslandSchematicPasteEvent)' - this is deprecated behavior, please report it to the authors: Ome_R

### To Reproduce

No idea it just appeared after a while

**Comment by OmerBenGera** [comment]
Can be ignored.
