### ISSUE TITLE
Island Admin Visit not working

### ISSUE THREAD

**Issue by MinecraftMan1013number2** [BG-Software-LLC/SuperiorSkyblock2#1875]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70504198/144be18a-f327-4549-964f-96e9f3775827)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70504198/fbcfbcf5-3f05-49c5-890c-85150ad65946)

### Describe the bug

The command `/island admin visit` is not working, even though I have permission for it.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70504198/79494df6-359c-4e4c-889a-b848991edef9)

### To Reproduce

Type `/island admin visit <name>`

### Additional Information

Don't know if this is related or not, but when I use the admin visit command it sends the deny message twice, and the normal is visit command only sends it once
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70504198/9ee62302-679a-48f8-97ed-9f503ce7b89b)![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70504198/59430c25-de8d-4300-86ee-14ed12d3e747)

**Comment by OmerBenGera** [comment]
Use `/is admin bypass`

**Comment by MinecraftMan1013number2** [comment]
Is that the only way to do it? I would like my mods to be able to visit locked islands, but not modify them.

**Comment by OmerBenGera** [comment]
> Is that the only way to do it? I would like my mods to be able to visit locked islands, but not modify them.

https://wiki.bg-software.com/superiorskyblock/overview/commands-and-permissions/permissions#superior.admin.bypass.less-than-island_privilege-greater-than
In your example, you want to give them `superior.admin.bypass.close_bypass`.
For other questions regarding permissions, join the discord server and ask for help in there
