### ISSUE TITLE
Use of ink sacs on sign on other's islands 

### ISSUE THREAD

**Issue by Tom18314** [BG-Software-LLC/SuperiorSkyblock2#1877]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.2

### Describe the bug

When a players warps to an island (not his own island). He can use glowing ink sacs on signs to make them glow.

### To Reproduce

1. Warp someone's island
2. Click with glowing ink sac on sign
3. Sign is now glowing (no permission required)

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it fixes itself.

**Comment by OmerBenGera** [comment]
Do you have all the sign types included in your `interactables.yml` file?
Only blocks inside the interactables file are checked for protection.
