### ISSUE TITLE
How to disable members from spawning bosses on islands?

### ISSUE THREAD

**Issue by FireKiller258** [BG-Software-LLC/SuperiorSkyblock2#1878]
### Minecraft's Version

1.12.2

### Plugin's Version

1.12.2

### Describe the bug

If you can mr ome_r send me a new jar and try disable bosses from spawning on islands. Can send you something from the boss developer that may help! He said "You'd have to reach out to that plugin developer and ask him kindly to cancel our BossEggEvent when on the island. You can send him Boss jar for this." 
[Boss-3.9.7 (3).zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/12536452/Boss-3.9.7.3.zip)

### To Reproduce

When players gain a boss spawn egg they are able to spawn it on islands

**Comment by OmerBenGera** [comment]
The boss egg item is a custom spawn egg that spawns a mob or a different item that acts as a spawn egg?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
