### ISSUE TITLE
Potato and carrot mission not working

### ISSUE THREAD

**Issue by titidelaff** [BG-Software-LLC/SuperiorSkyblock2#1879]
### Minecraft's Version

paper 1.20.1

### Plugin's Version

2023.2-b85

### Describe the bug

Farmer mission not working for carrot and potato

### To Reproduce

break carrot crop or potato crop, not counting for farmer mission

**Comment by titidelaff** [comment]
I tried singular and plural

**Comment by OmerBenGera** [comment]
FarmerMission counts progress when crops **grow**, not when breaking them.
Make aure you plant the crops on your own and it will work.
