### ISSUE TITLE
Oraxen Value

### ISSUE THREAD

**Issue by ohAndre** [BG-Software-LLC/SuperiorSkyblock2#1880]
### Minecraft's Version

1.19.3+

### Plugin's Version

Last

### Describe the bug

Hello, i want to do a is value with oraxen blocks. I've tried with ORAXEN:(blockid); 5 (value) 
but this didn't work. Someone can help me?

### To Reproduce

..

**Comment by OmerBenGera** [comment]
It seems that I haven't added support for custom block values.
I will look into this ( waiting for Uxon to give me access to the plugin)

I will let you know once I add support.

**Comment by ohAndre** [comment]
ty

**Comment by Distolfix** [comment]
@OmerBenGera While you're at it, why don't you add support for itemsadder as well?

**Comment by OmerBenGera** [comment]
> @OmerBenGera While you're at it, why don't you add support for itemsadder as well?

Sure,
what is your Discord? I'll open a ticket for you and we will discuss regarding this in there

**Comment by Distolfix** [comment]
"whiteombrah" is my discord

**Comment by ELIAS7281** [comment]
i too would love to use my custom oraxen blocks in the generator

**Comment by OmerBenGera** [comment]
> i too would love to use my custom oraxen blocks in the generator

You can do that already.
Use "ORAXEN:<type>" as a block type

**Comment by OmerBenGera** [comment]
@Distolfix @ohAndre This was implemented in latest dev build
Let me know how if it works.

**Comment by ELIAS7281** [comment]
what is the correct way to add items adder custom blocks in the generator ?

**Comment by OmerBenGera** [comment]
> what is the correct way to add items adder custom blocks in the generator ?

Use `ITEMS_ADDER:<item-adder-name>` as a block, and it will be spawned

**Comment by ELIAS7281** [comment]
I did ITEMS_ADDER:ruby_ore: 50 but didn’t work, was that the right way ?

**Comment by OmerBenGera** [comment]
Closing this for now
