### ISSUE TITLE
Console Error when place RoseStacker Spawner

### ISSUE THREAD

**Issue by titidelaff** [BG-Software-LLC/SuperiorSkyblock2#1881]
### Minecraft's Version

Paper version git-Paper-169 (MC: 1.20.1)

### Plugin's Version

SuperiorSkyblock2  version  2023.2-b85 

### Describe the bug

https://pastebin.com/uVRBmGBm

### To Reproduce

Place RoseStacker Spawner

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build, let me know if it fixes the issue.

**Comment by titidelaff** [comment]
No error with the latest dev build.
Ty.
