### ISSUE TITLE
invalid warp category item

### ISSUE THREAD

**Issue by KoalaDevelopment** [BG-Software-LLC/SuperiorSkyblock2#1883]
### Minecraft's Version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### Plugin's Version

2023.2-b91

### Describe the bug

If your /is setwarp test type and then /is warp or /is warps then gives me the error 

### To Reproduce

If your /is setwarp test type and then /is warp or /is warps then gives me the error 

### Additional Information

Error:https://pastebin.com/Cty3QuQN
Clip: https://medal.tv/games/minecraft/clips/1urb9fXlRsF9lN/d1337veQFRx6?invite=cr-MSxpNWosNTgxMzg5MjQs

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
