### ISSUE TITLE
Too many islands loaded

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1884]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15186 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 082d551 on paper_upstream)

### Plugin's Version

  [Thu 14:09:47 INFO ] [92mSuperiorSkyblock2[97m version .2
  [Thu 14:09:47 INFO ] Feature packed Skyblock core.
  [Thu 14:09:47 INFO ] Website: [92mhttps://bg-software.com/
  [Thu 14:09:47 INFO ] Author: Ome_R

### Describe the bug

On server startup a very large number of worlds/islands are loaded, and takes multiple minutes to start.
Additionally, this takes a huge performance toll, dropping the server to 15 tps with basically no players online. On the spark profiler it always shows that the main tick issues are chunk related ones.

### To Reproduce

Have a large number of islands and start server. The server will rarely get to a high tps.

**Comment by OmerBenGera** [comment]
Check out latest dev build of SSB, let me know if it works

**Comment by DuneSciFye** [comment]
TPS is perfect! Thank you!
