### ISSUE TITLE
Hi, "WARP_CATEGORY_ILLEGAL_NAME:" error.

### ISSUE THREAD

**Issue by Ancienty** [BG-Software-LLC/SuperiorSkyblock2#1889]
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/30762071/f8224f29-b458-40e7-9d9e-885ae25e9c60)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/30762071/bb7029ca-9c42-46c0-a0c9-4e4785c73791)

### Describe the bug

So whenever someone tries to create a warp sign (by writing [HOSGELDIN] on the sign), they get this error:

WARP_CATEGORY_ILLEGAL_NAME:

Of course they get the translated version of it but just to make everything even clearer, this is the error message in the lang.yml

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/30762071/661eaa02-fb97-4067-8917-983784f12bd8)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/30762071/a3b94b1a-bd66-4b4f-ae29-23dd589e2f2a)
(This error is the translated version of WARP_CATEGORY_ILLEGAL_NAME)

### To Reproduce

Well, just setting the island creation warp text to [HOSGELDIN] is enough to reproduce this I believe.

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/30762071/3ee3708a-0007-4623-8bd6-a533812edccd)

**Comment by OmerBenGera** [comment]
You need to write the name of the warp in the second line.

**Comment by Ancienty** [comment]
Oh that makes sense, terribly sorry for reporting this lmao.
