### ISSUE TITLE
Update Error Message

### ISSUE THREAD

**Issue by realSimon157** [BG-Software-LLC/SuperiorSkyblock2#1890]
### Minecraft's Version

1.18.2 purpur

### Plugin's Version

Latest (v2023.3)

### Describe the bug

When I join all the plugins alert me to update to the v2023.2 version when I have the latest (v2023.3) version.

### To Reproduce

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/89704731/3b634f4d-44f7-4ca9-8356-bc1fd086380f)
Join and the message appears!

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/89704731/67b5d01c-cbd7-400d-898a-f25fc269329b)

**Comment by OmerBenGera** [comment]
Will be fixed on Wednesday
