### ISSUE TITLE
Compatibility issue with FunGames

### ISSUE THREAD

**Issue by BlueWolf310199** [BG-Software-LLC/SuperiorSkyblock2#1892]
### Minecraft's Version

1.19.2 - Paper

### Plugin's Version

SuperiorSkyblock2-2023.2-b56

### Describe the bug

The error is provided in screenshot

Default world name in server.properties is set to " world "
No other plugin loads the map before it except basic Minecraft

I have the problem after adding plugins, but none that could pose a compatibility problem

### To Reproduce

Just start my server

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/108906964/c7b06f7a-42dd-49eb-aa0d-5c5b2fbb345b)

**Comment by OmerBenGera** [comment]
Send me entire session logs

**Comment by OmerBenGera** [comment]
It seems like FunGames loads the world SuperiorWorld.
I will look into what can be done regarding this.

**Comment by OmerBenGera** [comment]
> Thank you very much, I look forward to hearing from you so that I can restart the server as soon as possible!

Temp fix can be adding FunGames to the `load-before` inside the plugin's jar. It can be opened as it was a zip file.

**Comment by OmerBenGera** [comment]
I talked with MyShimado and he told me this:
```
Hello, in the new version of the plugin I have added a function to force worlds to be loaded by their name. Let it update and turn it off if it is on.

Forced loading of worlds: true (disable it)
Worlds to force load: []
```

Let me know if it works

**Comment by OmerBenGera** [comment]
Then do what I wrote to you above.
Let me know if it fixes the issue.

**Comment by Shimado** [comment]
Hi! Write to my discord channel, not here. -> https://discord.gg/ahDTQRX6Fb

**Comment by OmerBenGera** [comment]
Great,
Closing this for now
