### ISSUE TITLE
Stack block feature

### ISSUE THREAD

**Issue by hiiamken** [BG-Software-LLC/SuperiorSkyblock2#1893]
### Minecraft's Version

paper-1.20.1-196

### Plugin's Version

2023.3

### Describe the bug

Stack block feature

### To Reproduce

I cannot use the stack block feature as configured

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/142149960/2b035b4a-b187-4ecd-be48-fa01ce5f0b4c)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/142149960/25f29989-3ce8-4156-aa91-23007e03b1c1)

https://controlc.com/113aeb84

**Comment by hiiamken** [comment]
can y fix this bug?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
