### ISSUE TITLE
Circular plugin load issue due to softdepend on CMI (vs. MyWorlds)

### ISSUE THREAD

**Issue by bergerkiller** [BG-Software-LLC/SuperiorSkyblock2#1894]
### Minecraft's Version

1.20.1

### Plugin's Version

I assume latest (not specified by OP)

### Describe the bug

MyWorlds is set to load before CMI because CMI requires worlds to be loaded before it starts. Superiorskyblock2 is depending on CMI as well. This clashes and caused weird plugin loading bugs.

### To Reproduce

Install MyWorlds (or Multiverse, probably same issue there), CMI and SuperiorSkyBlock2

### Additional Information

I dont know why CMI is a softdepend of this plugin. Original issue: https://github.com/bergerhealer/MyWorlds/issues/51

I'll copy my response verbatum:

Ah so that explains the weird issues some people had. The problem is, there was a reason and need to loadbefore for CMI to work, so I dont know what a good way around this is now. Thats why I have a **classdepend** feature btw, its so I can make use of other plugins APIs without altering the dependency load order.

CMI wants worlds to have been loaded before it starts, so idk if superiorskyblock can really softdepend on cmi. Since that conflicts with that intention. Im fairly sure CMI also, itself, soft-depends on multiverse. Since they didnt softdepend on myworlds and their support is....special, I opted to add a loadbefore on my end.

Ideally superiorskyblock does a class-depend instead of softdepend, issue is, [the hacks needed to achieve this for Spigot are pretty complicated to set up](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/internal/logic/PluginLoaderHandlerSpigot.java#L59). On paper this is natively supported with [paper-plugin.yml dependencies format](https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/resources/paper-plugin.yml#L9).

Best would be if superiorskyblock devs could opt to include a paper-plugin.yml file with a dependency on cmi that doesnt alter load order. Then do some detection of cmi enabling late (PluginEnableEvent) and enable integrations lazily instead of at startup. This would at least fix the issue on Paper servers.

For this purpose I personally use a self-written [SoftDependency](https://github.com/bergerhealer/SoftDependency) library, like here where I use it in [TrainCarts](https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/TrainCarts.java#L159) to enable/disable components that require other plugins as they enable/disable. It automatically handles everything, including the case of a dependency already being enabled when your plugin enables.

**Comment by bergerkiller** [comment]
I'll need to review if its possible to drop SuperiorSkyBlock2 as a soft-depend. If myworlds is loading worlds with SSB2 as the generator plugin then this isn't possible. Does SSB2 initiate loading of SSB2 worlds by itself?

**Comment by OmerBenGera** [comment]
I looked af your solution again and I might implement it.

**Comment by bergerkiller** [comment]
Disabling it won't help, on spigot a circular depend will cause erratic load orders, including plugins loading in the wrong order causing errors. It must be fixed one way or another.

If there's something I can change on my end (like dropping the softdepend for superiorskyblock2 if that wont break everything) then let me know

**Comment by OmerBenGera** [comment]
It works flawlessly fine on Spigot's loading system.
The hack that BKCommonLib uses is also not a good solution - they just remove the warning from console.
I can also do that with console filters to gain the same effect

**Comment by bergerkiller** [comment]
> It works flawlessly fine on Spigot's loading system. The hack that BKCommonLib uses is also not a good solution - they just remove the warning from console. I can also do that with console filters to gain the same effect

On paper theres a more sophisticated solution (for when the new loading system was introduced). Its just that spigot doesnt really check what plugins can access what other plugins, so nothing more difficult is needed than silencing the warnings :p

**Comment by OmerBenGera** [comment]
I am not gonna add the `paper-plugin.yml`, but will only get rid of the soft-depend list in favor of the silence approach.
My plugin handles its dependencies on the first tick of the server, therefore it doesn't really matter what the plugin order is. The only thing matters is that SSB should load before any worlds management plugin, as it must load its own worlds.

**Comment by bergerkiller** [comment]
> I am not gonna add the `paper-plugin.yml`, but will only get rid of the soft-depend list in favor of the silence approach. My plugin handles its dependencies on the first tick of the server, therefore it doesn't really matter what the plugin order is. The only thing matters is that SSB should load before any worlds management plugin, as it must load its own worlds.

Keep in mind that myworlds now has a feature to disable autoloading worlds automatically. Ive used this for iris worlds where iris generates its own worlds too. That would probably be a good idea anyway. https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/WorldConfig.java#L160

**Comment by OmerBenGera** [comment]
> > I am not gonna add the `paper-plugin.yml`, but will only get rid of the soft-depend list in favor of the silence approach. My plugin handles its dependencies on the first tick of the server, therefore it doesn't really matter what the plugin order is. The only thing matters is that SSB should load before any worlds management plugin, as it must load its own worlds.
> 
> Keep in mind that myworlds now has a feature to disable autoloading worlds automatically. Ive used this for iris worlds where iris generates its own worlds too. That would probably be a good idea anyway. https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/WorldConfig.java#L160
> 
> That said, I guess the same issue exists with multiverse? And I guess because CMI also needs worlds, whether ssb2 loads before or after myworlds it wont make much of a difference then. By loading before MW/MV you fix it for all other plugins that need worlds automatically

I already load before MyWorlds.
And it doesn't matter if you have feature to disable auto loading of worlds, it requires the user to do that manually or me adding a custom support for MyWorlds.

**Comment by OmerBenGera** [comment]
Btw, why does MyWorlds depend on SuperiorSkyblock?

**Comment by bergerkiller** [comment]
Main reason was that world management plugins need to depend on chunk generator plugins, in the absence of a depend from chunk generator plugins side. I added it because of that fact.

Nowadays its more murky because chunk generator plugins themselves decide what worlds to load/generate on startup, too. So it gets messy.

**Comment by bergerkiller** [comment]
> > Main reason was that world management plugins need to depend on chunk generator plugins, in the absence of a depend from chunk generator plugins side. I added it because of that fact. Its indeed for loading on startup.
> > Nowadays its more murky because chunk generator plugins themselves decide what worlds to load/generate on startup, too. So it gets messy.
> > Another approach that is common is that chunk generator plugins tell world management plugins (like multiverse) what options to configure for a loaded world. Rather than loading the world themselves. That Bukkit lacks a basic API to tell what chunk generator options are used for a chunk generator of a world is a crime in of itself.
> 
> What code do you have that hooks into SSB? Otherwise, you can just remove it, as SSB already has a `load-before` to `My_Worlds`.

Yeah it can be removed, as there is no such hook. The only quasi-hook is createWorld(<generator>) where the generator must be available at startup. As youre loading the world before myworlds does, theres no need for that.

**Comment by OmerBenGera** [comment]
> > > Main reason was that world management plugins need to depend on chunk generator plugins, in the absence of a depend from chunk generator plugins side. I added it because of that fact. Its indeed for loading on startup.
> > > Nowadays its more murky because chunk generator plugins themselves decide what worlds to load/generate on startup, too. So it gets messy.
> > > Another approach that is common is that chunk generator plugins tell world management plugins (like multiverse) what options to configure for a loaded world. Rather than loading the world themselves. That Bukkit lacks a basic API to tell what chunk generator options are used for a chunk generator of a world is a crime in of itself.
> > 
> > 
> > What code do you have that hooks into SSB? Otherwise, you can just remove it, as SSB already has a `load-before` to `My_Worlds`.
> 
> Yeah it can be removed, as there is no such hook. The only quasi-hook is createWorld(generator) where the generator must be available at startup. As youre loading the world before myworlds does, theres no need for that.
> 
> I think I added it because back then in 2021 the loadbefore didnt exist in ssb2 yet. [bergerhealer/MyWorlds@dfb48b7](https://github.com/bergerhealer/MyWorlds/commit/dfb48b765c589bd637a39ef0c7148d0797f6070a)

This will probably fix all issues as well.

**Comment by bergerkiller** [comment]
> > > > Main reason was that world management plugins need to depend on chunk generator plugins, in the absence of a depend from chunk generator plugins side. I added it because of that fact. Its indeed for loading on startup.
> > > > Nowadays its more murky because chunk generator plugins themselves decide what worlds to load/generate on startup, too. So it gets messy.
> > > > Another approach that is common is that chunk generator plugins tell world management plugins (like multiverse) what options to configure for a loaded world. Rather than loading the world themselves. That Bukkit lacks a basic API to tell what chunk generator options are used for a chunk generator of a world is a crime in of itself.
> > > 
> > > 
> > > What code do you have that hooks into SSB? Otherwise, you can just remove it, as SSB already has a `load-before` to `My_Worlds`.
> > 
> > 
> > Yeah it can be removed, as there is no such hook. The only quasi-hook is createWorld(generator) where the generator must be available at startup. As youre loading the world before myworlds does, theres no need for that.
> > I think I added it because back then in 2021 the loadbefore didnt exist in ssb2 yet. [bergerhealer/MyWorlds@dfb48b7](https://github.com/bergerhealer/MyWorlds/commit/dfb48b765c589bd637a39ef0c7148d0797f6070a)
> 
> This will probably fix all issues as well.

Maybe some of it, but my softdepend and your loadbefore basically have the exact same effect, so I think thats unlikely. You added it a month later https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/cad34ad4bbca789d51f56f5b8ed2428b33a9c7d1 so in a way they both just say the same thing. But spigots loading system is fucky so who knows, maybe it changes some behaviors lol

**Comment by OmerBenGera** [comment]
> > > > > Main reason was that world management plugins need to depend on chunk generator plugins, in the absence of a depend from chunk generator plugins side. I added it because of that fact. Its indeed for loading on startup.
> > > > > Nowadays its more murky because chunk generator plugins themselves decide what worlds to load/generate on startup, too. So it gets messy.
> > > > > Another approach that is common is that chunk generator plugins tell world management plugins (like multiverse) what options to configure for a loaded world. Rather than loading the world themselves. That Bukkit lacks a basic API to tell what chunk generator options are used for a chunk generator of a world is a crime in of itself.
> > > > 
> > > > 
> > > > What code do you have that hooks into SSB? Otherwise, you can just remove it, as SSB already has a `load-before` to `My_Worlds`.
> > > 
> > > 
> > > Yeah it can be removed, as there is no such hook. The only quasi-hook is createWorld(generator) where the generator must be available at startup. As youre loading the world before myworlds does, theres no need for that.
> > > I think I added it because back then in 2021 the loadbefore didnt exist in ssb2 yet. [bergerhealer/MyWorlds@dfb48b7](https://github.com/bergerhealer/MyWorlds/commit/dfb48b765c589bd637a39ef0c7148d0797f6070a)
> > 
> > 
> > This will probably fix all issues as well.
> 
> Maybe some of it, but my softdepend and your loadbefore basically have the exact same effect, so I think thats unlikely. You added it a month later [cad34ad](https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/cad34ad4bbca789d51f56f5b8ed2428b33a9c7d1) so in a way they both just say the same thing. But spigots loading system is fucky so who knows, maybe it changes some behaviors lol

This is a bit of a philosophical discussion, but Bukkit's loading system has been like this since they created the API. Any changes that were made by Paper broke everything, and we can't blame Bukkit for Paper's changes.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/MyWorlds/250/

**Comment by bergerkiller** [comment]
> This is a bit of a philosophical discussion, but Bukkit's loading system has been like this since they created the API. Any changes that were made by Paper broke everything, and we can't blame Bukkit for Paper's changes.

True, I do think papers hamfisted way of isolating classloaders made things more unstable when there are circular dependencies. Spigot at least allowed it and seemed to come to some sort of solution. Would be better if Paper came up with some consistent loading order for circular deps, maybe based on name or something, and left it a warning.

**Comment by OmerBenGera** [comment]
This is fixed from my testings.
If the issue continues let me know
