### ISSUE TITLE
cobbelstone gen bugh

### ISSUE THREAD

**Issue by Solkongen** [BG-Software-LLC/SuperiorSkyblock2#1900]
### Minecraft's Version

1.20

### Plugin's Version

2023,3

### Describe the bug

fire spreads even if we have disabled it in settings.
the cobbelstone generator we can't see the block we need to mine lead in right click on the innocent block and we can see it and mine it.

### To Reproduce

[Uploading 2023-10-15 15-14-45.zip…]

**Comment by OmerBenGera** [comment]
```
fire spreads even if we have disabled it in settings.
```
I cannot replicate the issue myself. Make sure you turn off fire spread and not lava flow or anything like that.

```
the cobbelstone generator we can't see the block we need to mine lead in right click on the innocent block and we can see it and mine it.
```
I don't understand what the issue is. Please better explain it, as well as provide more information regarding it

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
