### ISSUE TITLE
Task

### ISSUE THREAD

**Issue by teraluboyt** [BG-Software-LLC/SuperiorSkyblock2#1901]
### Minecraft's Version

1.20.1

### Plugin's Version

latest

### Describe the bug

Does not pass the tasks in the farm category and when I unlock the last task in Slayer, I cannot collect the end and nether rewards

### To Reproduce

?

**Comment by OmerBenGera** [comment]
I don't understand what the issue is.
Please better explain it, as well as provide more information regarding the issue you're having.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues, let me know
