### ISSUE TITLE
Lighting bug for bigger islands

### ISSUE THREAD

**Issue by MedusaPlayzz** [BG-Software-LLC/SuperiorSkyblock2#1904]
### Minecraft's Version

1.20.1, paper-spigot

### Plugin's Version

2023.3 30/09/2023

### Describe the bug

When I will teleport to my new created island, all is dark until 1 chunk,. My cutom island is 128x128 blocks (its very big).

### To Reproduce

I don't know :(

### Additional Information

A screenshot from the problem:

![2023-10-21_13 56 37](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/133903193/a171ade8-e2d5-46a9-afbb-4f7f571680cd)

**Comment by OmerBenGera** [comment]
Enable lights-update in the config file

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue continues, let me know
