### ISSUE TITLE
/is blocks

### ISSUE THREAD

**Issue by Kubuusiek1910** [BG-Software-LLC/SuperiorSkyblock2#1908]
### Minecraft's Version

1.18.2 - serwer and minecraft

### Plugin's Version

Stable version

### Describe the bug

Why are the same spawners added to /is block twice?>

### To Reproduce

.

### Additional Information

![image-1](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/149273837/94573e15-6da9-4b96-baf2-2a143e60a54c)

**Comment by OmerBenGera** [comment]
One probably counts all the spawners, and one counts specific spawners.

**Comment by OmerBenGera** [comment]
Closing this for now :)
Questions regarding the plugin should be asked on the discord server for faster responses.
