### ISSUE TITLE
Oneblock bug

### ISSUE THREAD

**Issue by SemperAmici** [BG-Software-LLC/SuperiorSkyblock2#1909]
### Minecraft's Version

[23:39:17 INFO]: [97mThis server is running Paper version git-Paper-256 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: c6fac38)

### Plugin's Version

23:41:20 INFO]: [92mSuperiorSkyblock2[0m version [92m2023.3-b107

### Describe the bug

When a new Oneblock island gets created the block with then start randomly changing between various different blocks as of their being broken. If a block is placed above the oneblock the Oneblock doesn’t change at all and works normally.

### To Reproduce

Create a new oneblock island using SSBOneBlock-2023.3-b45.jar and SuperiorSkyblock2-2023.3-b107.jar

**Comment by OmerBenGera** [comment]
Already reported on OneBlock's github issues tracker.

**Comment by yooniks** [comment]
Was it fixed?
