### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1913]
### Minecraft's Version

1.20.1 pufferfish

### Plugin's Version

b110

### Describe the bug

Issue on startup : https://pastebin.com/SV8rcTDA

### To Reproduce

Idk

### Additional Information
I updated from superior b67 that worked well

**Comment by OmerBenGera** [comment]
You configured `default-values.entity-limits` incorrectly.
Show me how you configured it.

**Comment by WarnDa** [comment]
Hello
Here is my file : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/5e279e9a-901c-49ed-93de-6843cf6640da)
the best line is with or without the space after the : ?

**Comment by OmerBenGera** [comment]
You should remove the spaces after the `:`

**Comment by WarnDa** [comment]
Thanks it worked ! :)
