### ISSUE TITLE
Lack of entity limit message

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1915]
### Minecraft's Version

1.19.4 pufferfish

### Plugin's Version

b110

### Describe the bug

There is currently in config a **REACHED_BLOCK_LIMIT** but there is not an **REACHED_ENTITY_LIMIT**, so currently if a player try to spawn a mob using an egg, the mob just don't spawn, and player get no info why (so they complain and think the server bug)

### To Reproduce

- setup a mob limit (like 5 pig)
- spawn 5 pigs
- try to spawn another pig with an egg, it will just do nothing

**Comment by OmerBenGera** [comment]
Added in latest dev build
Let me know if it works

**Comment by WarnDa** [comment]
Hello, it works fine when you spawn mobs with an egg !

Is it possible to also send it when you try to reproduce mobs and they don't appear due to the limit ? Or it would cause issues ?

**Comment by OmerBenGera** [comment]
Check out latest dev build, should have messages when breeding entities as well

**Comment by WarnDa** [comment]
> Check out latest dev build, should have messages when breeding entities as well

Working great, thanks :)
