### ISSUE TITLE
Cant change slots of missions

### ISSUE THREAD

**Issue by Saadi43** [BG-Software-LLC/SuperiorSkyblock2#1919]
### Minecraft's Version

1.8.8

### Plugin's Version

latest

### Describe the bug

So i want to change the slot for missions in the modules/missions/config.yml and when i reload the plugin it dont work even restarting the server dont work and they can be open if we click under the slot like i have make 27 slot gui and make the slots in 2 line it will still open on the slots where they are orignal 

### To Reproduce

change the mission slot in module /missions/config.yml to 11 13 15 then also in menu / missions change the slots to 11 13 15 
then reload /restart it will work if you click under it 

### Additional Information

![ScreenShot Tool -20231124190158](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/129317864/61b10ce5-478f-4791-8387-fb8e37d07dcb)
![ScreenShot Tool -20231124190131](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/129317864/29b24d1c-ebd1-46cb-9476-346e74d74851)

**Comment by Saadi43** [comment]
https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/129317864/0b369e4f-2237-4f90-b4a7-56c1662cad56

**Comment by OmerBenGera** [comment]
It seems to work fine for me after a restart.
Do you mind uploading your missions config file, as well as the missions menu file so I can try replicating it myself?

**Comment by Saadi43** [comment]
[archive-2023-11-24T165145Z.tar.gz](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/13461142/archive-2023-11-24T165145Z.tar.gz)

**Comment by OmerBenGera** [comment]
Seems fine for me.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Saadi43** [comment]
No it's fixed it was just a plugin which was giving error
