### ISSUE TITLE
Quests Reset

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#192]
**Minecraft's Version**
1.16.5

**Plugin's Version**: -
SuperiorSkyblock-b107

**Describe the bug**

**To Reproduce**
Create a quests file
Have the quests file improperly load

**Additional information**
So based off my testing here, if the quests file loads improperly either due to yml screwups or just wrong format then certain times quests will reset either in progress or completely.

Is there a way to remedy this or is this more a "be more careful in the future" situation?
https://screenshots.skizzles.me/wAnA3/MowOGerU09.png

**Comment by OmerBenGera** [comment]
If you edit missions and they are removed, the plugin doesn't save the progress anymore - waste of memory and space.
Don't edit missions on a live server, or just test them before you make changes.

**Comment by Skizzles** [comment]
![image](https://user-images.githubusercontent.com/30563757/113159428-728e3400-91f1-11eb-8158-e62e374f2923.png)
