### ISSUE TITLE
Duplicated blocks in the menu

### ISSUE THREAD

**Issue by mario414x** [BG-Software-LLC/SuperiorSkyblock2#1921]
### Minecraft's Version

purpur-1.19.4-1985

### Plugin's Version

SuperiorSkyblock2-2023.3

### Describe the bug

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/103279766/47afdc03-b4dd-4be5-83c7-2a9f151e4d9b)
Island Blocks Counts are duplicated

### To Reproduce

open island blocks counts menu

**Comment by OmerBenGera** [comment]
Does this happen with latest dev build?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issues continue, let me know
