### ISSUE TITLE
OneBlock module broken for months

### ISSUE THREAD

**Issue by EditChris** [BG-Software-LLC/SuperiorSkyblock2#1923]
### Minecraft's Version

Paper Spigot for 1.20.2, Build 309

### Plugin's Version

SuperiorSkyBlock2: 2023.3-b121
OneBlock module: 2023.3-b45

### Describe the bug

I know this is for SuperiorSkyBlock2 and not just the OneBlock module, but the 3 first items on the issues list in the OneBlock repository are about this bug, and people have been waiting for a solution for months now. In the most recent item there's even a proposed solution to the problem made 2-3 weeks ago. We would like for this to be fixed already because the OneBlock module has been straight unusable for too long now.

https://github.com/BG-Software-LLC/SSB-OneBlock/issues/

### To Reproduce

- Create a new game of OneBlock.
- After doing literally nothing or breaking one or a few blocks, the game will instantly continue generating all the next blocks or entities to spawn in that phase. It stops whenever it wants, sometimes in the same phase, or sometimes it continues to the next one, again, until it wants to stop. All phases are affected.

**Comment by OmerBenGera** [comment]
I replied to the opened issue on OneBlock's module.
