### ISSUE TITLE
Cactus growth issue

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1925]
### Minecraft's Version

Current: git-Purpur-2030 (MC: 1.20.1)*
Previous: git-Purpur-1996 (MC: 1.20.1)
* You are 32 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

2023.3

### Describe the bug

People who make automatic cactus farms don't see their cactus fall over.

### To Reproduce

1. make cactus farm
2. wait growth

**Comment by SwartZCoding** [comment]
More details. seem the barrier (and other blocks maybe) didn't cancel the growth of the cactus.

**Comment by OmerBenGera** [comment]
SuperiorSkyblock does not affect the way blocks grow.
I doubt this is an issue with the plugin.

Try it on a server with only SSB installed, let me know if it still occurs.

**Comment by SwartZCoding** [comment]
> SuperiorSkyblock does not affect the way blocks grow. I doubt this is an issue with the plugin.
> 
> Try it on a server with only SSB installed, let me know if it still occurs.

Issue is related to https://github.com/PaperMC/Paper/pull/8564.

Paper have this issue since 2022 and this not be PR ... If someone have this issue. Just reset your cactus modifiers on spigot.yml by 100. I close.
