### ISSUE TITLE
Issue with "interact:" permission

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1926]
### Minecraft's Version

1.20.1 pufferfish

### Plugin's Version

b121

### Describe the bug

If a player has "interact:" permission, he can right click on a stacked barrel to withdraw 1 item, even if he can't break the barrel, so they can still people because "interact" is used for traps or other classic things

### To Reproduce

- use wildstacker barrel feature
- stack blocks
- set "interact" permission to visitors
- ask a visitor to right_click on your barrel
- he can withdraw 1 item by 1 item

### Additional Information

And it happens even on "valuable_break" blocks like diamond_blocks.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works.
(P.S: Make sure you update WildStacker as well, otherwise you'll face a dupe glitch)

**Comment by WarnDa** [comment]
Fixed thanks ! :)
