### ISSUE TITLE
Can't see banned people from the island

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1927]
### Minecraft's Version

1.21 pufferfish

### Plugin's Version

b121

### Describe the bug

If you banned people from your island (by error or if an old member banned them before leaving) you got no way to see the banlist.
So unless the banned player contact you, you can't unban him, and it's a bit weird

### To Reproduce

Ban someone from your island
you can't know you banned him

### Additional Information

X

**Comment by OmerBenGera** [comment]
Added in latest dev build
