### ISSUE TITLE
Sign edit on island

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1928]
### Minecraft's Version

1.20.1 Purpur

### Plugin's Version

2023.3

### Describe the bug

User with is not on their island can edit sign by right clicking on it.

### To Reproduce

put a sign in a island.
Use other account which is not on this island and tp on
right click on sign with it.

**Comment by OmerBenGera** [comment]
Add all types of signs to the interactables.yml file.
