### ISSUE TITLE
placeholder %superior_island_bank_raw% return an empy string

### ISSUE THREAD

**Issue by SpadaccinoNero7** [BG-Software-LLC/SuperiorSkyblock2#1929]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.3

### Describe the bug

i created a math placeholder that includes %superior_island_bank_raw% but it gives error when the player doesn't have money in his bank (before creating an island)

[15:17:14 WARN]: [PlaceholderAPI] [math] Invalid Placeholder detected!
[15:17:14 WARN]: [PlaceholderAPI] [math] Placeholder: %math_{vault_eco_balance}+{superior_island_bank_raw}%
[15:17:14 WARN]: [PlaceholderAPI] [math] Cause:       '1000+' is not a valid Math expression.

### To Reproduce

just use %math_{vault_eco_balance}+{superior_island_bank_raw}% placeholder

**Comment by OmerBenGera** [comment]
This happens when players don't have an island.
You can change the default placeholder value in the configuration file, as follows:
```
default-placeholders:
  - 'superior_island_bank_raw:0'
  - 'superior_island_bank:0.00'
```

Let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
I am closing this as I provided a solution above
If the issue continues let me know
