### ISSUE TITLE
Hologram bug

### ISSUE THREAD

**Issue by SkyWaves123** [BG-Software-LLC/SuperiorSkyblock2#1930]
### Minecraft's Version

This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 v2023.1 stable build

### Describe the bug

Upon block ores stacking, by using a method , there will be broken holograms floating around.

### To Reproduce

By stacking for example, 20 blocks of gold, upon right clicking very fast so the block unstack, there will remain a broken hologram.

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/122482979/029202ba-21ca-4acc-8dd1-02203277b7d1)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by SkyWaves123** [comment]
So i didnt try the newest dev build but it actually was a visual bug and it was only visible to me. Thanks for the help!
