### ISSUE TITLE
 Could not pass event BlockBreakEvent

### ISSUE THREAD

**Issue by SrMonsterYT** [BG-Software-LLC/SuperiorSkyblock2#1931]
### Minecraft's Version

Pufferfish version git-Pufferfish-27 (MC: 1.20.1)

### Plugin's Version

SuperiorSkyblock2 v2023.3-b121

### Describe the bug

https://mclo.gs/nrzyqgL

### To Reproduce

happened after I updated to version 121 of the plugin

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
Does it happen on a server with only WildStacker & SuperiorSkyblock installed?
If so, what version of WildStacker do you use? Also, what Java version does your server run on?

**Comment by SrMonsterYT** [comment]
> I cannot replicate the issue myself. Does it happen on a server with only WildStacker & SuperiorSkyblock installed? If so, what version of WildStacker do you use? Also, what Java version does your server run on?

java 17
WildStacker-2023.3-b26.jar

the bug happens after a few hours, when someone is breaking blocks inside the skyblock island, I did the test and I couldn't replicate it, but after a few hours it started to happen every time a player broke 1 block inside the island

**Comment by OmerBenGera** [comment]
Switch to Paper, this will probably fix the issue.

**Comment by SrMonsterYT** [comment]
> Switch to Paper, this will probably fix the issue.

pufferfish is more optimized and better :,(

**Comment by OmerBenGera** [comment]
> > Switch to Paper, this will probably fix the issue.
> 
> pufferfish is more optimized and better :,(

Test it on Paper, check if it fixes the issue.
If so, report it over them. If it still occurs, let me know.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs let me know
