### ISSUE TITLE
/island command not registered

### ISSUE THREAD

**Issue by aarushbhutra** [BG-Software-LLC/SuperiorSkyblock2#1932]
### Minecraft's Version

1.20.1 Purpur

### Plugin's Version

Dev Build #121

### Describe the bug

Plugin not registereing the /island or /is command. Nothing comes when I use /help either. Reset config still occurs

### To Reproduce

Run Server

**Comment by OmerBenGera** [comment]
Upload your session logs (from latest.log file) to pastebin and send a link to it here.

**Comment by aarushbhutra** [comment]
[latest (1).log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/13694718/latest.1.log)

**Comment by OmerBenGera** [comment]
The plugin was loaded just fine, which means you lack the permission to use `/island`, or you configured it to be a different command in the config file.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
