### ISSUE TITLE
Error "is creating timing"

### ISSUE THREAD

**Issue by wotan179352468** [BG-Software-LLC/SuperiorSkyblock2#1933]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.3 30/09/2023 20:51:38

### Describe the bug

when I start the server I get this error

Plugin 'SuperiorSkyblock2' is creating timing 'Plugin: SuperiorSkyblock2 v2023.3 Event: DynamicRegisteredListener::IslandSchematicPasteEvent(IslandSchematicPasteEvent)' - this is deprecated behavior, please report it to the authors: Ome_R

### To Reproduce

just install the plugin and launch it

**Comment by OmerBenGera** [comment]
Can be ignored, nothing harmful.
