### ISSUE TITLE
ItemsAdder x Superior Generator issue

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1935]
### Minecraft's Version

Current: git-Purpur-2030 (MC: 1.20.1)*
Previous: git-Purpur-1996 (MC: 1.20.1)

You are 32 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

2023.3

### Describe the bug

When a custom ore spawns in the generator, it is not pushed by pistons because it is a jukebox in itemsadder.

### To Reproduce

1. Make a generator with a custom ore in.
2. try to piston it

**Comment by OmerBenGera** [comment]
Does it work fine if you place a custom block from ItemsAdder manually?

**Comment by SwartZCoding** [comment]
> Does it work if you place a custom block from ItemsAdder manually?

I don't know but the piston got destroyed when i try to push the block.

**Comment by OmerBenGera** [comment]
> > Does it work if you place a custom block from ItemsAdder manually?
> 
> I don't know but the piston got destroyed when i try to push the block.

I believe this is because ItemsAdder have their blocks set as a Jukebox, therefore you cannot push or pull them using pistons.
This has nothing to do with SuperiorSkyblock

**Comment by SwartZCoding** [comment]
> > > Does it work if you place a custom block from ItemsAdder manually?
> > 
> > 
> > I don't know but the piston got destroyed when i try to push the block.
> 
> I believe this is because ItemsAdder have their blocks set as a Jukebox, therefore you cannot push or pull them using pistons. This has nothing to do with SuperiorSkyblock

https://github.com/PluginBugs/Issues-ItemsAdder/issues/3211.

Yes ItemsAdder confirm the issue. I close.
