### ISSUE TITLE
Mission auto-reward doesn't work on required-missions completition

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1936]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15552 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: a357d04 on fix/logging)

### Plugin's Version

2023.3-b100

### Describe the bug

Option `auto-reward` on the mission is set to `true`
Player completes a mission but doesn't complete pre-requsities (option `required-missions`)
Player completes all pre-requsities (missions stated in `required-missions`)
Player is not automatically granted rewards and has to manually claim the mission reward

### To Reproduce

1. Set an `auto-reward` option on one mission to `true`
2. Complete mission without completing `required-missions` first
3. Complete pre-requsities stated in `required-missions`
4. Open mission menu and see how the mission is not completed and is in `can-complete` state

**Comment by OmerBenGera** [comment]
In general, you should not get progress on missions that you cannot complete (in this case, missions that have required-missions).
What mission type are these missions?

**Comment by Davisiiiik** [comment]
Statistic missions

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Davisiiiik** [comment]
Thank you, it works just fine, but I discovered another possible scenario:

There is a `Statistic Player mission` with autocomplete and `Island mission`.
This `Island mission` is a requirement for `Statistic Player mission`.
`Island mission` is completed on an island.
New player joins the island and has required statiscs to complete the `Statistic Player mission`.
In this scenario the autocomplete is not triggered for the `Statistic Player mission`.

**Comment by OmerBenGera** [comment]
Do you mind uploading these missions to pastebin and send a link to them here?
This way I can easily replicate the issue and fix it.

**Comment by Davisiiiik** [comment]
Sure, my example missions:

[Island Mission](https://pastebin.com/EWtqFk8W)
[Statistics Player Mission](https://pastebin.com/yBph9JDY)

I use it mostly when I want to give all players on island permission (even newcommers later on), when they have completed some specific mission, because I didn't think about any other possible solution. I hope you won't see it as misuse.

**Comment by OmerBenGera** [comment]
Your IslandMission is of type `StatisticsMissions` - is this intentional?

**Comment by Davisiiiik** [comment]
Yes, I have multiple types of the required island missions for different players missions. This example I shared has `StatisticsMissions`.

**Comment by Davisiiiik** [comment]
I found another issue, my StatisticsMissions was completed automatically even when I had `auto-reward` set to `false`

**Comment by Davisiiiik** [comment]
I was able to come up with my own solution. I used `IslandMissions` with `MissionCompleteEvent` and `IslandJoinEvent` event listeners and it works just as I need.

I have a last request regarding this issude:
- Please, revert the change you did in commit [#e1d167e](https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/e1d167ebf04284df9a152cd1eac2521760674123), because there are problems witch I commented in previous message. After that you can close this issue. I am sorry for wasting your time.

**Comment by OmerBenGera** [comment]
> I was able to come up with my own solution. I used `IslandMissions` with `MissionCompleteEvent` and `IslandJoinEvent` event listeners and it works just as I need.
> 
> I have a last request regarding this issude:
> 
> * Please, revert the change you did in commit [#e1d167e](https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/e1d167ebf04284df9a152cd1eac2521760674123), because there are problems witch I commented in previous message. After that you can close this issue. I am sorry for wasting your time.

What issues does it bring?

**Comment by Davisiiiik** [comment]
As I wrote before, it completes even the missions with `auto-reward` option set to `false`:

> I found another issue, my StatisticsMissions was completed automatically even when I had `auto-reward` set to `false`

**Comment by OmerBenGera** [comment]
> As I wrote before, it completes even the missions with `auto-reward` option set to `false`:
> 
> > I found another issue, my StatisticsMissions was completed automatically even when I had `auto-reward` set to `false`

Should be fixed in latest dev build

**Comment by Davisiiiik** [comment]
Tested. It works now, thank you!
