### ISSUE TITLE
Island upgrade chests not unlocking in GUI.

### ISSUE THREAD

**Issue by findbottest** [BG-Software-LLC/SuperiorSkyblock2#1937]
### Minecraft's Version

1.20.1 paper.

### Plugin's Version

2023.2

### Describe the bug

when using chest update command via admin, the slots do not unlock in the gui

  chest-limit:
    '1':
      price: 70000.0
      commands:
      - island admin setupgrade %player% chest-limit 1
      - island admin setchestrow %player% 1 1
      - island admin msgall %player% &a&l✔ &8| &7Your community chest limit increased
        by 1 chest!
    '2':
      price: 70000.0
      commands:
      - island admin setupgrade %player% chest-limit 2
      - island admin setchestrow %player% 1 2
      - island admin msgall %player% &a&l✔ &8| &7Your community chest limit increased
        by 1 chest!
    '3':
      price: 70000.0
      commands:
      - island admin setupgrade %player% chest-limit 3
      - island admin setchestrow %player% 1 3
      - island admin msgall %player% &a&l✔ &8| &7Your community chest limit increased
        by 1 chest!
    '4':
      price: 70000.0
      commands:
      - island admin setupgrade %player% chest-limit 4
      - island admin setchestrow %player% 1 3
      - island admin msgall %player% &a&l✔ &8| &7Your community chest limit increased
        by 1 chest!
    '5':
      price: 70000.0
      commands:
      - island admin msg %player% &e&l⫹⫺ &8| &7You have reached the maximum upgrade
        for island chest limit.

### To Reproduce

use the chest upgrade in upgrades 

### Additional Information

![Screenshot_31](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/135071501/d1dce813-2e4f-4bc8-bfd2-bc1e32794104)

**Comment by OmerBenGera** [comment]
You only increase the first chest's amount of slot rows.
The first number in the `is admin setchestrow` is the index of chest you edit, and the second one is the amount of rows you unlock for this chest.

**Comment by findbottest** [comment]
correct, so level 1 is 
island admin setchestrow %player% 1 6
level 2 is
island admin setchestrow %player% 2 6
level 3 is
island admin setchestrow %player% 3 6
level 4 is
island admin setchestrow %player% 4 6

but only slot 1 chest 1 unlocks at 1 chest, 6 slots, purchasing more updates doesn't unlock anymore chests
