### ISSUE TITLE
Compatibility issues with EcoEnchants

### ISSUE THREAD

**Issue by PixelSur** [BG-Software-LLC/SuperiorSkyblock2#1938]
### Minecraft's Version

server : purpur1.20.2

### Plugin's Version

version: 2023.3-b121

### Describe the bug

When using the EcoEnchants plug-in with the SuperiorSkyblock2 plug-in, all enchantments will not be loaded.

### To Reproduce

After adding EcoEnchants and SuperiorSkyblock2 to the server there is a problem

**Comment by PixelSur** [comment]
Probably caused by EcoEnchants updating their api.

**Comment by OmerBenGera** [comment]
SuperiorSkyblock does not interact with EcoEnchants in any way.
Contact them for support.
