### ISSUE TITLE
brewing mission

### ISSUE THREAD

**Issue by SpadaccinoNero7** [BG-Software-LLC/SuperiorSkyblock2#1941]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.3

### Describe the bug

i cannot figured out how to set more than one potion at the same mission

### To Reproduce

just try add more than one potion in the mission's file

### Additional Information

i tried this setup but it's not working as i expect (it's not tracking the right potion setted before in the file)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/117306394/cde8e71f-5330-4a3b-bbe3-7c7fefcbd4f5)

**Comment by OmerBenGera** [comment]
Upload your entire brewing mission to pastebin, so I can look into it myself.

**Comment by SpadaccinoNero7** [comment]
# The mission file to use
mission-file: BrewingMissions

# Whether the mission should be given when completing all requirements.
auto-reward: true

# Should block counts of players get reset when completing the mission?
reset-after-finish: true

# Rewards given when completing the mission.
rewards:
  commands:
    - 'eco give %player% 1000'
    - 'is admin msg %player% &e&lAlchimista Supremo | &7Completata con successo la missione Alchimista Supremo II!'
    - 'is admin msg %player% &e&lAlchimista Supremo | &7&oDigita &f/is missions &7per vedere la prossima missione'
required-missions:
  - 'alchimistasupremo_1'
# List of all required blocks must be gathered in order to complete the mission.
required-potions:
  '1':
    potions:
      '1':
        type: SPEED
        upgraded: true
        extended: false
        splash: false
    amount: 15
  '2':
    potions:
      '2':
        type: POISON
        upgraded: true
        extended: false
        splash: true
    amount: 15
# Icons used in the menus.
icons:
  not-completed:
    type: BREWING_STAND
    name: '&aAlchimista Supremo II'
    lore:
      - '&7La durata aumenta...'
      - ''
      - '&6Pozioni richieste:'
      - '&8 - &7x15 Velocità II'
      - '&8 - &7x15 Avvelenamento II lanciabile'
      - ''
      - '&6Ricompensa:'
      - '&8 - &71000 €'
      - ''
      - '&6Pozioni di Velocità distillate: &7{1}/15'
      - '&6Pozioni di Avvelenamento distillate: &7{2}/15'
      - ''
      - '&6Progresso: &7{0}%'
      - ''
      - '&c&l ✘ &7Non completato'
  can-complete:
    type: BREWING_STAND
    name: '&aAlchimista Supremo II'
    lore:
      - '&7La durata aumenta...'
      - ''
      - '&6Pozioni richieste:'
      - '&8 - &7x15 Velocità II'
      - '&8 - &7x15 Avvelenamento II lanciabile'
      - ''
      - '&6Ricompensa:'
      - '&8 - &71000 €'
      - ''
      - '&6Pozioni di Velocità distillate: &715/15'
      - '&6Pozioni di Avvelenamento distillate: &715/15'
      - ''
      - '&6Progresso: &7100%'
      - ''
      - '&a&l ✔ &7Clicca per riscattare'
    enchants:
      DURABILITY: 1
    flags:
      - HIDE_ENCHANTS
  completed:
    type: BREWING_STAND
    name: '&aAlchimista Supremo II'
    lore:
      - '&7La durata aumenta...'
      - ''
      - '&6Pozioni richieste:'
      - '&8 - &7x15 Velocità II'
      - '&8 - &7x15 Avvelenamento II lanciabile'
      - ''
      - '&6Ricompensa:'
      - '&8 - &71000 €'
      - ''
      - '&6Pozioni di Velocità distillate: &715/15'
      - '&6Pozioni di Avvelenamento distillate: &715/15'
      - ''
      - '&6Progresso: &7100%'
      - ''
      - '&a&l ✔ &7Già ottenuto'

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
However, it looks like the placeholders in the items you configured are wrong.
You should use the following placeholders to get the amount of potions brewed:
`{value_speed;true;false;false}` for the speed potion requirement and `{value_poison;true;false;true}` for the poison potion requirement.

The format of the placeholder is pretty simple:
`{<value/percentage>_<PotionType>;<upgraded>;<extended>;<splash>}`

**Comment by OmerBenGera** [comment]
Closing this for now as it seems to be a config-related bug
If the issue continues let me know

**Comment by SpadaccinoNero7** [comment]
hello, i cannot find the correct way to set up the brewing mission file for some potions type
i tried using this website https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html and this one https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html but i can't figure it out why
can you please help me??

**Comment by SpadaccinoNero7** [comment]
[alchimistasupremo_4.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/15370893/alchimistasupremo_4.txt)
