### ISSUE TITLE
Problem with bedrock players

### ISSUE THREAD

**Issue by ChicoIdeal** [BG-Software-LLC/SuperiorSkyblock2#1943]
### Minecraft's Version

1.20.1

### Plugin's Version

SuperiorSkyblock2-2023.3-b120

### Describe the bug

When inviting a bedrock player to the island, he can accept correctly but when we try to expel him from the island it appears that he has never joined the island, it does not allow me to change the role or anything related as a member of the island, it appears that he never joined the island.

### To Reproduce

Use the command /is invite *Lokigame6207, the player accepts the command /is accept, then I try to use the command /is remove *Lokigame6207, it does not let me because the player is not a member of the island.

### Additional Information

https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/110360668/98817d43-1fa1-4dca-b49e-b3c8682b4069

**Comment by OmerBenGera** [comment]
Is this still relevant?
I tried replicating it myself and I can't seem to get it working. I have my bedrock alt account with a `.` at the start of his name, and it works just fine - the plugin treats him as a different account than the Java account.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, let me know
