### ISSUE TITLE
Please fix hook with cloudspawner

### ISSUE THREAD

**Issue by Saadi43** [BG-Software-LLC/SuperiorSkyblock2#1945]
### Minecraft's Version

1.12.2

### Plugin's Version

2023.3

### Describe the bug

So in my config.yml i set it to AUTO for stacking and when i set a block limit to 10 for mobspawner and then i place it it dont work and count it as the pig spanwer.Please fix this or add a hook for it. and when i place the spawner in the area and remove it then i cant place more spawners it just say you reached the limit for the plugin.Add me on discord if you want to test the plugin or need its api 

https://builtbybit.com/threads/%E2%98%81%EF%B8%8F-cloudspawners-%E2%98%81%EF%B8%8F-1-8-1-18-%E2%9C%A8-upgradable-spawners-%E2%9C%A8-discord-bot-logging-%E2%98%81%EF%B8%8F-15.671465/

### To Reproduce

create a new block limit for mobspawner
and in config.yml set the stacking support to AUTO 
then  restart and place spawners it will not work
first it will exceed the limit and then it will say you reached the limit for pig spawner even i placed snowman

**Comment by OmerBenGera** [comment]
Seems like CloudSpawners needs to add support for SuperiorSkyblock.
Contact them for support regarding this; there are plenty of examples on how they can do it on the wiki, as well as within the source code of SuperiorSkyblock.

CloudSpawners is a premium resource, thus I cannot do it myself.
