### ISSUE TITLE
OneBlock bug

### ISSUE THREAD

**Issue by yooniks** [BG-Software-LLC/SuperiorSkyblock2#1946]
### Minecraft's Version

1.20.1 purpur

### Plugin's Version

2023.3 SuperiorSkyblock2

### Describe the bug

When players mines a "oneblock" block a few times and then stops, then the block is automatically changing about 4 times and then it stops. Looks like blocks is mining itself.

### To Reproduce

When players mines a "oneblock" block a few times and then stops, then the block is automatically changing about 4 times and then it stops. Looks like blocks is mining itself.

**Comment by OmerBenGera** [comment]
Already been reported on OneBlock's issues tracker.
