### ISSUE TITLE
/is visit can be used to skip warmup for /is (home teleport) or /is (warp)

### ISSUE THREAD

**Issue by Evalutik** [BG-Software-LLC/SuperiorSkyblock2#1947]
### Minecraft's Version

PurPur 1.20.2

### Plugin's Version

2023.3 30/09/2023 20:51:38

### Describe the bug

I have warmup in the config for teleport on the island and teleports to waps, but players just use /is visit <nick> to teleport withount any warmup on any island. Pleas, add warmup for /is visit command.

### To Reproduce

set warmup in the config for home teleport 10000 ms
use /is visit <your nick>
u will be teleported on your island without any delays

**Comment by OmerBenGera** [comment]
Added visit-warmup in latest dev build
Let me know if it works.

**Comment by OmerBenGera** [comment]
Closing this as it was added in latest dev build
If the issue continues let me know
