### ISSUE TITLE
Signs are being edited

### ISSUE THREAD

**Issue by dshimen** [BG-Software-LLC/SuperiorSkyblock2#1948]
### Minecraft's Version

1.20.2 purpur build 2095

### Plugin's Version

#124 build of ssb2

### Describe the bug

Signs are beinged edited by players even when world guard protection is on.

### To Reproduce

Just use worldguard, some signs and build #124

### Additional Information
Maybe that's the problem:
BukkitExecutor.sync(() -> {
            BlockState blockState = e.getBlock().getState();
            if (blockState instanceof Sign) {
                Sign sign = (Sign) blockState;
                for (int i = 0; i < signLines.length; ++i)
                    sign.setLine(i, signLines[i]);
                sign.update();
            }
        }, 1L);
        It's one of your commits
_No response_

**Comment by OmerBenGera** [comment]
You should add all sign types to the interactables file.

I will keep it opened so I remember to add them to the default files as well.

**Comment by dshimen** [comment]
I added:
- 'SIGN'
- 'OAK_SIGN'
- 'SPRUCE_SIGN'
- 'BIRCH_SIGN'
.
.
.
But players still can edit signs (tested on OAK SIGN)

**Comment by OmerBenGera** [comment]
https://bg-software.com/material

**Comment by dshimen** [comment]
I have added all before:
https://pastebin.com/hjWPv7yi
Just didn't post the entire file.
After i changed 
BukkitExecutor.sync(() -> {
BlockState blockState = e.getBlock().getState();
if (blockState instanceof Sign) {
Sign sign = (Sign) blockState;
for (int i = 0; i < signLines.length; ++i)
sign.setLine(i, signLines[i]);
sign.update();
}
}, 1L);

To the old version (only that), it's started working corectly. 

Ps. correct link for materials
https://bg-software.com/materials

**Comment by WarnDa** [comment]
I deleted the file interactables.yml and it fixed the issue for me.

**Comment by OmerBenGera** [comment]
> I have added all before: https://pastebin.com/hjWPv7yi Just didn't post the entire file. After i changed BukkitExecutor.sync(() -> { BlockState blockState = e.getBlock().getState(); if (blockState instanceof Sign) { Sign sign = (Sign) blockState; for (int i = 0; i < signLines.length; ++i) sign.setLine(i, signLines[i]); sign.update(); } }, 1L);
> 
> To the old version (only that), it's started working corectly.
> 
> Ps. correct link for materials https://bg-software.com/materials

You are missing many of sign blocks in your interactables file.
As @WarnDa suggested, just regenerate the interactables file and you'll be good to go.

**Comment by dshimen** [comment]
The problem was solved on clean server(not like before), i can't get it working on main server but it only means the problem is with smth diff now.
