### ISSUE TITLE
Nether/End portals

### ISSUE THREAD

**Issue by ZappySK** [BG-Software-LLC/SuperiorSkyblock2#195]
If i want to set, when players create end/nether portal, how i set to teleport them to world_nether and world_the_end (not skyblock islands)

**Comment by ZappySK** [comment]
@OmerBenGera

**Comment by WolverStones** [comment]
He wrote at Discord yesterday that he would no longer be as active as before. 

Quotes:
```
As I promised a long time ago, I am gonna quit the industry, and this day has came. From tomorrow, I am not gonna be active as I used to be anymore, and I will hardly be able to fix bugs and answer questions. I hope the developers in the community will help to contribute to the projects and fix bugs that still exist in the plugins.
Questions will still be answered by the amazing @💻 Support Team 💻  in the public channels. I will do my best to get online once a week to catch up with bugs and maybe even fix some, but I can't promise anything.
```

Anyway, i will try using Multiverse plugin addon Nether Portals. But i don't know if it will work.
https://dev.bukkit.org/projects/multiverse-netherportals

**Comment by Skizzles** [comment]
> If i want to set, when players create end/nether portal, how i set to teleport them to world_nether and world_the_end (not skyblock islands)

You could use Multiverse for this, currently there is not a way to do this within the plugin. If you want to see this as a feature please open a feature request.
