### ISSUE TITLE
Some bugs with missions

### ISSUE THREAD

**Issue by petrkeram** [BG-Software-LLC/SuperiorSkyblock2#1952]
### Minecraft's Version

1.20.2

### Plugin's Version

newest

### Describe the bug

some missions not working, some didnt pay rewards and after /is admin relaod all missions and progress here will reset
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/99331219/85fbbc3b-6ab4-47f9-a976-b87e50725daa)
![image22](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/99331219/5136f926-0b31-4e49-965d-db888d30e60f)

### To Reproduce

umm

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs let me know
