### ISSUE TITLE
Many bugs in Missions 

### ISSUE THREAD

**Issue by pjindras** [BG-Software-LLC/SuperiorSkyblock2#1953]
### Minecraft's Version

1.20.2 purpur spigot, always lastest

### Plugin's Version

I tried more version, 2023.3 (last stable) #124 last dev build #121 etc.

### Describe the bug

Missions are total bugged:
-> data isn't saved to mysql
-> plugin re-regenerates missions many times and always after reload
-> some missions and its quests arent working, for example farmer 2 and some rewards arent given properly

### To Reproduce

Install the plugin and try the missions, restart server and they are gone.

### Additional Information

Startup log: https://paste.gg/p/anonymous/a6db2820f96c4dfaba078eae5b13ea5b

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it fixes the issue

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs let me know
