### ISSUE TITLE
Is close bug

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#1954]
### Minecraft's Version

Current: git-Purpur-2030 (MC: 1.20.1)*
Previous: git-Purpur-1996 (MC: 1.20.1)
* You are 32 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

2023.3

### Describe the bug

when a player teleports to an island that is not his own and later the owner closes his island with /is closed even if the player is at spawn or on his own island he receives a message that he was on an island that has been closed and gets teleported to spawn. The same bug occurs when an island enables pvp.

### To Reproduce

1. a player teleports to an island
2. he's leaving
3. the owner closes his island or switches it to pvp mode
4. He recieve a message and got tp

**Comment by Ammutadori075** [comment]
same here

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
How does the player leave the island?
Do you have by any chance the teleport or move events disabled on your server?

**Comment by OmerBenGera** [comment]
Does it happen if you try it on another server with only SuperiorSkyblock installed?

**Comment by SwartZCoding** [comment]
To give more informations :

- /is expel <tab complete> continue to give player name kicked after an /is close.

**Comment by OmerBenGera** [comment]
> i cant test on a test server cause i need more people to test it. Since its a thing related to teleport, maybe have some similarities to my other issue i report on #1964

Both of you probably have PlayerTeleportEvent / PlayerMoveEvent not functioning correctly, which might cause this.
Are you able to replicate it on a Paper server with only SSB installed?

**Comment by SwartZCoding** [comment]
> I think i solve the problem anyways. If i found any other issue, ill report.

Bro explain how you fix ?

**Comment by SwartZCoding** [comment]
> > i cant test on a test server cause i need more people to test it. Since its a thing related to teleport, maybe have some similarities to my other issue i report on #1964
> 
> Both of you probably have PlayerTeleportEvent / PlayerMoveEvent not functioning correctly, which might cause this. Are you able to replicate it on a Paper server with only SSB installed?

I just tried with as few plugins as possible and I still have the same problem.

Just have LuckPerms, PAPI, ProtocolLib, spark, SuperiorSkyblock2, Tab-BRIDGE, Vault, Votifier.

Si i confirm it's an SSB 2 issue @OmerBenGera. I have removed 1 by 1 all my plugins to test.

**Comment by SwartZCoding** [comment]
> > > I think i solve the problem anyways. If i found any other issue, ill report.
> > 
> > 
> > Bro explain how you fix ?
> 
> by remoning close command and only use permission

Yes so you don’t fix it 😅

**Comment by OmerBenGera** [comment]
> > > i cant test on a test server cause i need more people to test it. Since its a thing related to teleport, maybe have some similarities to my other issue i report on #1964
> > 
> > 
> > Both of you probably have PlayerTeleportEvent / PlayerMoveEvent not functioning correctly, which might cause this. Are you able to replicate it on a Paper server with only SSB installed?
> 
> I just tried with as few plugins as possible and I still have the same problem.
> 
> Just have LuckPerms, ProtocolLib, spark, SuperiorSkyblock2, Vault
> 
> Si i confirm it's an SSB 2 issue @OmerBenGera. I have removed 1 by 1 all my plugins to test.

Does it occur if you use Paper?

**Comment by SwartZCoding** [comment]
> > > > i cant test on a test server cause i need more people to test it. Since its a thing related to teleport, maybe have some similarities to my other issue i report on #1964
> > > 
> > > 
> > > Both of you probably have PlayerTeleportEvent / PlayerMoveEvent not functioning correctly, which might cause this. Are you able to replicate it on a Paper server with only SSB installed?
> > 
> > 
> > I just tried with as few plugins as possible and I still have the same problem.
> > Just have LuckPerms, ProtocolLib, spark, SuperiorSkyblock2, Vault
> > Si i confirm it's an SSB 2 issue @OmerBenGera. I have removed 1 by 1 all my plugins to test.
> 
> Does it occur if you use Paper?

I don’t know i use purpur

**Comment by OmerBenGera** [comment]
> > > > > i cant test on a test server cause i need more people to test it. Since its a thing related to teleport, maybe have some similarities to my other issue i report on #1964
> > > > 
> > > > 
> > > > Both of you probably have PlayerTeleportEvent / PlayerMoveEvent not functioning correctly, which might cause this. Are you able to replicate it on a Paper server with only SSB installed?
> > > 
> > > 
> > > I just tried with as few plugins as possible and I still have the same problem.
> > > Just have LuckPerms, ProtocolLib, spark, SuperiorSkyblock2, Vault
> > > Si i confirm it's an SSB 2 issue @OmerBenGera. I have removed 1 by 1 all my plugins to test.
> > 
> > 
> > Does it occur if you use Paper?
> 
> I don’t know i use purpur

Try it on Paper then, let me know if it still occurs.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by whoisalee** [comment]
With the dev-build this is fixed, I had the same problem when having the stable.

**Comment by OmerBenGera** [comment]
@whoisalee good to know :) 
@SwartZCoding any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this for now due to lack of response
If the issue still occurs, let me know
