### ISSUE TITLE
Players die from falling during void tp

### ISSUE THREAD

**Issue by Ammutadori075** [BG-Software-LLC/SuperiorSkyblock2#1956]
### Minecraft's Version

1.20.1 Tested on Pufferfish, Purpur and Paper

### Plugin's Version

Superiorskyblock 2023.3 and dev versions too.

### Describe the bug

Even if I set the teleport in case of fall on the void, once teleported to your island you die from a fall.

void-teleport:
  members: true
  visitors: true

### To Reproduce

fall from your island and die when teleported

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Ammutadori075** [comment]
Sorry, same thing , plus a loto of errors on startup with the missions:

[15:12:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading mission data for miner_1:
[15:12:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getJarEntry(String)" because "this.jar" is null
[15:12:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading mission data for miner_2:
[15:12:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getJarEntry(String)" because "this.jar" is null
and more

**Comment by OmerBenGera** [comment]
> Sorry, same thing , plus a lot of errors on startup with the missions:
> 
> [15:12:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading mission data for miner_1: [15:12:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getJarEntry(String)" because "this.jar" is null [15:12:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading mission data for miner_2: [15:12:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getJarEntry(String)" because "this.jar" is null and more

Update to latest dev build, hopefully it fixes these errors

**Comment by OmerBenGera** [comment]
> i still die on lastest version i actually remove fall damage with worldguard to fix this

Does it happen on a server where you only have SuperiorSkyblock installed?

**Comment by Ammutadori075** [comment]
> > Sorry, same thing , plus a lot of errors on startup with the missions:
> > [15:12:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading mission data for miner_1: [15:12:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getJarEntry(String)" because "this.jar" is null [15:12:09 ERROR]: [SuperiorSkyblock2] An unexpected error occurred while loading mission data for miner_2: [15:12:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.util.jar.JarFile.getJarEntry(String)" because "this.jar" is null and more
> 
> Update to latest dev build, hopefully it fixes these errors

Still having warning with missions and still dying from fall.

[11:59:35 WARN]: [SuperiorSkyblock2] The mission category minatore doesn't have missions, skipping...
[11:59:35 WARN]: [SuperiorSkyblock2] The mission category killer doesn't have missions, skipping...
[11:59:35 WARN]: [SuperiorSkyblock2] The mission category agricoltore doesn't have missions, skipping...
[11:59:35 WARN]: [SuperiorSkyblock2] The mission category pescatore doesn't have missions, skipping...
[11:59:35 WARN]: [SuperiorSkyblock2] The mission category boscaiolo doesn't have missions, skipping...

**Comment by OmerBenGera** [comment]
@Ammutadori075 @SkyDude0 Check out latest dev build, let me know if it works

**Comment by Ammutadori075** [comment]
Hi @OmerBenGera , the problem is solved only in overworld islands, in nether and end island is still present.

**Comment by Ammutadori075** [comment]
@OmerBenGera I would like to add that the players tell me that with the latest dev the island missions are all reset.

**Comment by OmerBenGera** [comment]
The bug of taking damage from void teleport is fixed in latest dev build
Regarding missions, open a new issue regarding this and provide more information.

**Comment by Ammutadori075** [comment]
I confirm the fix for the bug of taking damage from void teleport.
