### ISSUE TITLE
Island deleted alone.

### ISSUE THREAD

**Issue by LenyzDev** [BG-Software-LLC/SuperiorSkyblock2#1957]
### Minecraft's Version

1.20

### Plugin's Version

2023.3-b113

### Describe the bug

The island was destroyed alone while the player was offline, when using the /is command it appeared that he did not have an island. And when he went to it with the /home command the island was destroyed.

### To Reproduce

I don't know, the player entered and the island had been destroyed.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70076720/ae56b130-370c-4fbb-a630-f63fb4be7102)

**Comment by OmerBenGera** [comment]
Either one of his friends trolled him or the world was corrupted.
Because he is longer part of the island, I suspect he gave access to players to disband and destroy his island.

If it happens with other players as well, reopen the bug report.
