### ISSUE TITLE
Interact with 1.16 things.

### ISSUE THREAD

**Issue by TheMartyCZ** [BG-Software-LLC/SuperiorSkyblock2#196]
**Minecraft's Version**
SSSpigot 1.16.5

**Plugin's Version**: -
1.6.0

**Describe the bug**
If you have a crooked door, a crooked button, a crimson door on an island ... they can be controlled by another player.

**To Reproduce**
1. Establishment of the island
2. Build a warped door ..
3. Teleport to the island from another account
4. See if you can open the door.

**Additional information**
Nothing

**Comment by ElBananaa** [comment]
> **Minecraft's Version**
> SSSpigot 1.16.5
> 
> **Plugin's Version**: -
> 1.6.0
> 
> **Describe the bug**
> If you have a crooked door, a crooked button, a crimson door on an island ... they can be controlled by another player.
> 
> **To Reproduce**
> 
> 1. Establishment of the island
> 2. Build a warped door ..
> 3. Teleport to the island from another account
> 4. See if you can open the door.
> 
> **Additional information**
> Nothing

In `/plugins/SuperiorSkyblock2/interactables.yml` add these materials, and it'll solve your issue.

**Comment by OmerBenGera** [comment]
A list of new interactable materials needs to be added to the interactables file by default.
If someone can do that it would be awesome  :)

**Comment by OmerBenGera** [comment]
Fixed in latest build
