### ISSUE TITLE
Island Chests' content not loading after updating the plugin..

### ISSUE THREAD

**Issue by JakkitDE** [BG-Software-LLC/SuperiorSkyblock2#1960]
### Minecraft's Version

paper 1.19.4 #550

### Plugin's Version

SuperiorSkyblock2-2023.1-b18.jar

### Describe the bug

After updating from SuperiorSkyblock2-2023.1-b18.jar to SuperiorSkyblock2-2023.3.jar the island chests'content disappeared.. There is no error in console, only "skipping island chest .... "

### To Reproduce

Use the given versions, fill up some island chests and then update should reproduce the error.

**Comment by JanReich** [comment]
[20:39:08 WARN]: [SuperiorSkyblock2] Cannot load island chest with invalid contents for 69a8ef8b-1c75-48fe-9913-4d307079bd01, skipping...

**Comment by OmerBenGera** [comment]
@JakkitDE Please send me the entire session logs.

@JanReich Are you associated with @JakkitDE ?

**Comment by JanReich** [comment]
Yes we are working together

[logs.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/13924140/logs.txt)

That is a log from our test-Server. This log is not from the newest build from SuperiorSkyBlock, but we also reproduced this bug with the Version b-124.

**Comment by OmerBenGera** [comment]
Do you mind uploading your database file (zip it before doing so)?

**Comment by JanReich** [comment]
[database.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/13929596/database.zip)

Here is the SQLite Database-Zipfile with the newest Playerdata

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by JanReich** [comment]
It works perfectly fine all players that are online have access at thier sky chest content. Thank you for fixing this issue
