### ISSUE TITLE
Island chunk bug crash

### ISSUE THREAD

**Issue by keepmeside** [BG-Software-LLC/SuperiorSkyblock2#1963]
### Minecraft's Version

1.20.1

### Plugin's Version

SuperiorSkyblock2-2023.3-b124

### Describe the bug

There is a member's island that crash 

### To Reproduce

There is crash log: https://appdevtools.com/pastebin/iBjlRz

**Comment by OmerBenGera** [comment]
Report it over UniverseSpigot.
The plugin uses the Bukkit API and it crashed your server.
Nothing wrong on our side.
