### ISSUE TITLE
[ BUG ] Effect bug

### ISSUE THREAD

**Issue by SkyDude0** [BG-Software-LLC/SuperiorSkyblock2#1964]
### Minecraft's Version

1.18.2

### Plugin's Version

Dev build #124

### Describe the bug

Island effect remain active when you teleport out of the island

### To Reproduce

Go to island where effect buff are active and tp out

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
How do you get out of the island?
Also, does it happen on Paper 1.20.4?

**Comment by OmerBenGera** [comment]
What spigot jar do you use?

**Comment by OmerBenGera** [comment]
Which version of Pufferfish exactly?
Send me the output of `/version`
