### ISSUE TITLE
COBBLESTONE GENERATOR | JETS MİNİON

### ISSUE THREAD

**Issue by JasperRuiz96** [BG-Software-LLC/SuperiorSkyblock2#1966]
### Minecraft's Version

Purpur 1.18.2

### Plugin's Version

SS2 version 2023.3  latest
JetsMinion version 7.10.0 latest

### Describe the bug

I am using superiorskyblock2 with jetsminion. And when I updated the plugins they were completely broken.

When you put a jetsminion in front of the **Cobblestone generator,** after the minion breaks the blocks, the blocks do not form again because the lava does not flow.

**NOTE:**
There was no such problem in previous jetsminion and superiorskyblock versions.

Please it needs to be fixed as soon as possible.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126576073/55cba19a-0a58-441d-9dda-ae3e172b1597)

### To Reproduce

The cobblestone generator broke with the last version.

### Additional Information

There was no such problem in previous jetsminion and superiorskyblock versions.

**Comment by OmerBenGera** [comment]
Does it happen if you only have JetsMinions installed and you try it on a regular world?
I suspect its JetsMinions code not updating the blocks properly, which makes the lava to not flow.

**Comment by JasperRuiz96** [comment]
> Does it happen if you only have JetsMinions installed and you try it on a regular world? I suspect its JetsMinions code not updating the blocks properly, which makes the lava to not flow.

I will explain everything step by step. All I've done and tried.

 * cobblestone generator is working. (without minions) (with SuperiorSkyblock)

 * cobblestone generator not working. (with minion) (with SuperiorSkyblock)
  ----- 
 * cobblestone generator is working. (with petite) (without SuperiorSkyblock) (I did not try this. The producers of JetsMinions sent it as a media file.)
  ------- 

* This happened after I upgraded to the latest pl versions. Strangely, when you put a minion in front of the SuperiorSkyblock generator, after the first blocks are broken. The lava must flow and turn into stone. But after the stones are broken, lava does not flow and there is no regeneration. If the minion breaks the blocks and the lava does not flow, I pick up the minion from the ground and put stones in between, and when I break it with the pickaxe, it works normally.

(When I convey this to the minion makers, we are fine, my friend. They say look, it works normally. I will forward the video they sent me.)


* I tried deleting and resetting files such as paper and spigot, but it didn't work. 

* I reset the SuperiorSkyblock file and it didn't work.

![Screenshot_20240112_195408_Discord](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126576073/d58f9f4b-c0fd-40cf-89db-7f07f497ee99)


https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126576073/461e151d-314e-4231-b3e8-b8fcdd3d59c7

![Screenshot_20240112_195629_Discord](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126576073/0dc086c7-309a-4258-a880-870c30c8b53f)

https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/126576073/d8cb7aa1-6367-40f7-a64e-2258408dafc9

**Comment by OmerBenGera** [comment]
I will contact Jet and look into it.

**Comment by OmerBenGera** [comment]
I have latest versions of SuperiorSkyblock and JetsMinions and it seems to work just fine.
Does it happen for you on a server with only both plugins installed?

**Comment by JasperRuiz96** [comment]
> I have latest versions of SuperiorSkyblock and JetsMinions and it seems to work just fine. Does it happen for you on a server with only both plugins installed?


I tested it cleanly on localhost and yes, we had the problem.
I don't understand why it happened.

I'm sorry I bothered you too.

**Comment by OmerBenGera** [comment]
> > I have latest versions of SuperiorSkyblock and JetsMinions and it seems to work just fine. Does it happen for you on a server with only both plugins installed?
> 
> I tested it cleanly on localhost and yes working, we had the problem. I don't understand why it happened.
> 
> I'm sorry I bothered you too.

So it works fine on a clean setup?
If so, try adding plugins one by one until it happens again.
It might also be something related to your spigot jar / spigot configuration, so try using them as well.

Let me know when you find the cause.

**Comment by JasperRuiz96** [comment]
> > > I have latest versions of SuperiorSkyblock and JetsMinions and it seems to work just fine. Does it happen for you on a server with only both plugins installed?
> > 
> > 
> > I tested it cleanly on localhost and yes working, we had the problem. I don't understand why it happened.
> > I'm sorry I bothered you too.
> 
> So it works fine on a clean setup? If so, try adding plugins one by one until it happens again. It might also be something related to your spigot jar / spigot configuration, so try using them as well.
> 
> Let me know when you find the cause.


I found what broke it.
I updated LoneLib.jar and it was fixed.
So it's the core plugin of Itemsadder.
yeah working ^^
