### ISSUE TITLE
Mob/Blocs count twice

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1968]
### Minecraft's Version

1.20.1 paper

### Plugin's Version

b124

### Describe the bug

Since I updated from #b67 to #b124 (I upgraded my server from 1.19.3 to 1.20.1) players complain that all their island levels/mobs count twice, and when they recalc their island it fixes this.
But after some times, it counts again twice all the blocks (so the is level)

### To Reproduce

I don't know... :/

### Additional Information

Didn't get any issue on b67 before

**Comment by OmerBenGera** [comment]
I need more information than this.
Find out how to replicate the issue.

**Comment by WarnDa** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/5347e4c1-7d90-478a-998c-74f9762d079a)
Some blocks are showed twice into the levels gui

Don't get time currently to work on it, will do in 2-3 weeks .

**Comment by OmerBenGera** [comment]
Try replicating it on a server with only SSB installed, default files.

**Comment by Hysteriox** [comment]
Hi ! I have the same problem on my server
Version Server: 1.16.5 (Java 16)
Version Plugin : 2023.3

**Comment by WarnDa** [comment]
So an update between dev build 67 and dev build 100 created the issue
But it's hard to know how to reproduce this. But at least we know it's a change between these 30 builds

**Comment by Hysteriox** [comment]
Personally, the bug occurred when I changed the plugin version from 1-11-1 to 2023.3.

**Comment by OmerBenGera** [comment]
`/is recalc` or `/is admin recalc <island>` will recalculate all the blocks - does it fix the issue?

**Comment by WarnDa** [comment]
> `/is recalc` or `/is admin recalc <island>` will recalculate all the blocks - does it fix the issue?

Yes it still counts twice the blocks

**Comment by LoneWolf22lr** [comment]
@OmerBenGera I am having this same issue where blocks are counting twice. Sometimes /is recalc will fix this or a reboot of the server. But this seems to be a larger issue that I can not resolve. 

Can you please give some insight to this issue and how we can fix it. This is really inconvenient for a players experience on a server.

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself
Try replicating it on a server with only SSB installed (using your own configuration files)
Let me know if you managed to do so

**Comment by LoneWolf22lr** [comment]
I believe this is something to do with how levels and worth are being calculated all together.  There is times when my players are randomly dropping in levels after logging on, when nothing has changed about their islands. This is a much bigger issue than just blocks duplicate on /is blocks

@WarnDa @Hysteriox The blocks that you find duplicating on /is blocks, are these blocks that you have specified levels for in block value configs?
And do you guys have Sell/Buy prices to calculate Worth setup?
_I want to try to track what things are in common_

**Comment by OmerBenGera** [comment]
If one of you can send me a copy of their SSB setup, it would be great.
This means the entire SSB folder, and if you use SGP for prices - their config as well.

(We'll do it over Discord, privately)

**Comment by WarnDa** [comment]
EDIT ! Found that the issue appear ONLY on block that do not get the same value in levels.yml and worth.yml !!

**Comment by WarnDa** [comment]
As it only happens on server load, and it’s fixed after an island recalc (until next restart)
Is it possible to get debug when it loads islands and calculate their level on startup ?

**Comment by OmerBenGera** [comment]
> As it only happens on server load, and it’s fixed after an island recalc (until next restart) Is it possible to get debug when it loads islands and calculate their level on startup ?

It does not recalculate their level on startup
The island level and worth are saved upon shutdown, and loaded when start up.

**Comment by WarnDa** [comment]
> > As it only happens on server load, and it’s fixed after an island recalc (until next restart) Is it possible to get debug when it loads islands and calculate their level on startup ?
> 
> It does not recalculate their level on startup The island level and worth are saved upon shutdown, and loaded when start up, including the block counts.

So on shutdown it may save them incorrectly, but hard to figure out why as there is no debug

**Comment by flo0s** [comment]
I just do test,
I found that the bug starts at the dev version 77

https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/aa5aeb8a64c2c8c48504a79eaac62ecbab4e19ef

I know it's surprising but i try v76 no problem and the v77 has the problem

**Comment by flo0s** [comment]
Ok I've just tested and the bug does come from the dev 77 https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/aa5aeb8a64c2c8c48504a79eaac62ecbab4e19ef version, I've got the latest development version, I've modified the Keys code to put in the code from before v77 and the bug is fixed.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is fixed

Tried to reproduce the bug 4-5 times, didn't get the bug.
So the issue seems fixed (for blocks at least)

**Comment by OmerBenGera** [comment]
Mobs tracker is broken, related to all the limits issues.
Closing this :)
