### ISSUE TITLE
Island deleted alone

### ISSUE THREAD

**Issue by LenyzDev** [BG-Software-LLC/SuperiorSkyblock2#1969]
### Minecraft's Version

1.20.4

### Plugin's Version

2023.3-b113

### Describe the bug

The error of islands deleting itself occurred again, apparently a friend of the player left the island using /is leave and his island was deleted, there were 3 other cases of islands disappearing both from the game and from MySQL, they simply disappeared as if they were deleted by the player himself, but through the console I saw that there was no command of this type being triggered.

### To Reproduce

I don't know, the player entered and the island had been destroyed.

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70076720/353cda1a-f424-4f7f-8675-bf03941b0097)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70076720/c1bc396d-ed6f-4dcb-adcc-8326de156859)

**Comment by OmerBenGera** [comment]
This looks like a chunk corruption to me.
Is this hole aligned with the chunk grid?

**Comment by LenyzDev** [comment]
> This looks like a chunk corruption to me. Is this hole aligned with the chunk grid?

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70076720/1980688c-8018-481e-ac15-4ed6d79e3afd)
Na verdade está na borda das chunks, mas a ilha não foi deletada só do jogo mas no mysql também.

**Comment by OmerBenGera** [comment]
> > This looks like a chunk corruption to me. Is this hole aligned with the chunk grid?
> 
> ![image](https://private-user-images.githubusercontent.com/70076720/298396314-1980688c-8018-481e-ac15-4ed6d79e3afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODkzMjksIm5iZiI6MTcwNjc4OTAyOSwicGF0aCI6Ii83MDA3NjcyMC8yOTgzOTYzMTQtMTk4MDY4OGMtODAxOC00ODFlLWFjMTUtNGVkNmQ3OWUzYWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ODkyMzY1ZmZmMjdiOGE0NGNkY2E1NTFlOTZlNzViZDJmNDNjYmZlNjk2NGMyMGJhZTViNzZkYTUyMGVkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFOhBgLDpguMPqzaThLhEqAIHAOYLfaVtIQU50vSV9w) It is on the edge of the chunks, but the island was not only deleted from the game but from MySQL as well.

If it was deleted from the database, then it was disbanded by another player.

**Comment by OmerBenGera** [comment]
> > > > This looks like a chunk corruption to me. Is this hole aligned with the chunk grid?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/70076720/298396314-1980688c-8018-481e-ac15-4ed6d79e3afd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODkzMjksIm5iZiI6MTcwNjc4OTAyOSwicGF0aCI6Ii83MDA3NjcyMC8yOTgzOTYzMTQtMTk4MDY4OGMtODAxOC00ODFlLWFjMTUtNGVkNmQ3OWUzYWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDEyMDM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ODkyMzY1ZmZmMjdiOGE0NGNkY2E1NTFlOTZlNzViZDJmNDNjYmZlNjk2NGMyMGJhZTViNzZkYTUyMGVkNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFOhBgLDpguMPqzaThLhEqAIHAOYLfaVtIQU50vSV9w) It is on the edge of the chunks, but the island was not only deleted from the game but from MySQL as well.
> > 
> > 
> > If it was deleted from the database, then it was disbanded by another player.
> 
> So how to solve this? Because another player wasn't supposed to be able to delete the island, I tested it even with the leader role and I couldn't undo it.

They probably gave each other the right permissions to disband the island or something.
I don't know what happened in this particular event, but if it happens with other players, then report it again - as it doesn't seem like a bug to me.

**Comment by LenyzDev** [comment]
In this case, how do I show the images there? It happened with 2 different games, and also with another one that I don't have an image of.

**Comment by OmerBenGera** [comment]
> In this case it happened with 2 different players, and also with another player who I don't have an image of.

Let me know how to replicate the issue then.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
