### ISSUE TITLE
Guest Can Break/Place/Interact any storage etc.

### ISSUE THREAD

**Issue by Zsomi** [BG-Software-LLC/SuperiorSkyblock2#1971]
### Minecraft's Version

1.20.2-Purpur(2095)

### Plugin's Version

SuperiorSkyblock2-2023.3-b129.jar

### Describe the bug

Essentially, if they visit someone's island they can demolish it, open the containers etc.

### To Reproduce

1. Put the SLimeworldmanager server.jar + plugin + swm module
2. start the server
3. visit the island (guest role)

Files= https://drive.google.com/drive/folders/1SmxxY5JGmyqu1ZjbsQcXDwCLuF1MgOLZ?usp=sharing

### Additional Information

The slimeworldmanager module has been rewritten to the purpur fork slimeworldmanager.

You can only destroy if you don't have an island

**Comment by OmerBenGera** [comment]
I cannot destroy or place blocks in other islands as a guest.
I am using latest SSB, latest SSBSlimeWorlds module and ASP for Paper.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by Zsomi** [comment]
Yes, unfortunately it is still relevant.

**Comment by OmerBenGera** [comment]
Does it work for you on a server with only the plugins I stated above installed?
I cannot replicate the issue myself.

**Comment by Zsomi** [comment]
Essentially a server restart might solve it now I have a problem that I can't set the island size in the config file.

**Comment by OmerBenGera** [comment]
> Essentially a server restart might solve it now I have a problem that I can't set the island size in the config file.

If you have upgrades, the default sections in the config file is technically useless
You should use upgrades to set up your default values.

**Comment by Zsomi** [comment]
I don't know why but when I set up the island it creates a 750x750 island.

**Comment by OmerBenGera** [comment]
> I don't know why but when I set up the island it creates a 750x750 island.

You can ask for help in the discord server.
Probably something related to your configuration.

Closing this as the original issue was fixed.
