### ISSUE TITLE
Island close kicks non-present players on other islands to the spawn

### ISSUE THREAD

**Issue by minemalia** [BG-Software-LLC/SuperiorSkyblock2#1972]
### Minecraft's Version

Pufferfish version git-Pufferfish-"979d3a2" (MC: 1.20.1)

### Plugin's Version

SuperiorSkyblock2 2023.3

### Describe the bug

 The plugin is sometimes considering players are still in an island when in fact they moved out. This can cause players who are in their own island to get kicked to spawn after someone else on another island they visited used /island close. It can also be heavily abused if someone keeps spam closing/reopening their island to kick another player.

Secondly, somewhat related: It seems like /island expel is also impacted by this random bug, since a player mentioned that he is able to tab-complete usernames of players that were on the island but left, which means it might also be an impacted command in this issue. Since Player1 can be kicked from an Player2's island and be teleported to the spawn when Player1 is not anymore on Player2's island.

### To Reproduce

Player1 visits Player2's island
Player1 goes back to his own island.
Player2 closes his island.
Player1 gets teleported to the spawn. (BUG, since Player1 was already on his own island)

This does not happen always, but the proof in the additional information shows that it happens

### Additional Information

https://youtu.be/0hOrTrs9NQw

This video shows what happens as the bug occurs.

**Comment by OmerBenGera** [comment]
First, update to latest dev build.
If the issue still occurs, try replicating it on a server with only SSB installed.

**Comment by Ammutadori075** [comment]
For me the problem is resolved with last dev build.

**Comment by OmerBenGera** [comment]
> For me the problem is resolved with last dev build.

Interesting.
@minemalia Try it, let me know if it works.

**Comment by LoneWolf22lr** [comment]
I am having this exact issue. I am currently using version 2023.3
Is it safe to put in the latest Dev build on a live server? or Is there config changes that I need to be aware of? 
@OmerBenGera

**Comment by OmerBenGera** [comment]
> I am having this exact issue. I am currently using version 2023.3 Is it safe to put in the latest Dev build on a live server? or Is there config changes that I need to be aware of? @OmerBenGera

It should be plug&play

**Comment by minemalia** [comment]
It is quite safe to try, but for me there were more issues created then solved with the latest dev build. So we downgraded from the dev build back to the stable build, and we 'solved' this issue by blocking the island close command and island expel command.

**Comment by LoneWolf22lr** [comment]
> It is quite safe to try, but for me there were more issues created than solved with the latest dev build. So we downgraded from the dev build back to the stable build, and we 'solved' this issue by blocking the island close command and island expel command.

Yeah, I have heard this as well. Disappointing really

**Comment by LoneWolf22lr** [comment]
@OmerBenGera Can you give insight on the current issues with the latest dev build? Update to the latest build isn't an option if it is going to break more than it is fixing.

**Comment by OmerBenGera** [comment]
> @OmerBenGera Can you give insight on the current issues with the latest dev build? Updating to the latest build isn't an option if it is going to break more than it is fixing.

You can take a look at the opened issues yourself.
Most of the bugs exist in the stable version as well, so you have nothing to lose.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
