### ISSUE TITLE
Access SSB3

### ISSUE THREAD

**Issue by ELIAS7281** [BG-Software-LLC/SuperiorSkyblock2#1973]
### Minecraft's Version

1.20.4

### Plugin's Version

latest

### Describe the bug

Hi OMAR ive had ssb2 for a long time. And i hear you have ssb3 , in testing or in the works. i was wondering if i could be 1 to test and report. ty

### To Reproduce

as above

### Additional Information

done

**Comment by OmerBenGera** [comment]
I dont know what you talk about.
Maybe you mean the proxy-bridge module?
