### ISSUE TITLE
Cannot create colored sign on islands and spawn

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1975]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15703 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 5c2494e on paper_upstream)

### Plugin's Version

2023.3-b133

### Describe the bug

When I create a colored sign using `&` symbol on an island or SSB2 spawn location, coloring is not made.

I have set spawn to 256 and created two signs on the edge to demonstrate the problem.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79375965/b21f4874-5b3a-4c64-90cc-ac494dfe683f)

### To Reproduce

Try to create a CMI colored sign in the skyblock world (spawn or island)

### Additional Information

Maybe a connection with #1916?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
