### ISSUE TITLE
Can't customise command in top-islands

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1976]
### Minecraft's Version

1.20.1 paper

### Plugin's Version

b134

### Describe the bug

In the gui "top-islands", we can't customise the click action (left or right) for every island.
But I want to change the click to open a custom gui in deluxemenus (where I display some useful information about each islands)

### To Reproduce

Tried to add a custom "section" command, doesn't work
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/682f78fb-ca89-4afb-9143-dd9f60161476)

**Comment by leon37921** [comment]
hey, are you sure, that this is the right format?
I have it like this: 
![grafik](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/157528016/1af91be8-e16e-4bcd-8e16-307127760569)

**Comment by WarnDa** [comment]
> The format for commands in the top island is a bit different:
> 
> ```
> commands:
>   '#':
>     island:
>     - broadcast Test
> ```
> 
> This should work.

Thanks this work, but what is the placeholder to return the island ?

**Comment by OmerBenGera** [comment]
> > The format for commands in the top island is a bit different:
> > ```
> > commands:
> >   '#':
> >     island:
> >     - broadcast Test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should work.
> 
> Thanks this work, but what is the placeholder to return the island ?

This is sadly not a feature as of now.
You can create a ticket tho and I'll look into adding support for it.
