### ISSUE TITLE
Biome generation when creating a new island is not working properly.

### ISSUE THREAD

**Issue by leon37921** [BG-Software-LLC/SuperiorSkyblock2#1978]
### Minecraft's Version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
Previous version: git-Paper-515 (MC: 1.19.4)

### Plugin's Version

SuperiorSkyblock2 version 2023.3-b134
last version: b107

### Describe the bug

The island biome is not uniform. There are two biomes mixed together. This happens with all schematics (2).

### To Reproduce

Simply create a new island.

### Additional Information

The biome boundaries are identical to the chunk boundaries.
I highlighted the biomes with worldedit to better see the boundaries. Plains = yellow wool, Forest = lime wool.
The biome change with /is biome works normal. The only problem is with the island creation.
main config.yml https://pastebin.com/uieQbh2P
island-creation.yml menu https://pastebin.com/QceRgQAc
![grafik](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/157528016/67d97cd7-62b1-4a4d-92c7-d88452292c40)

**Comment by OmerBenGera** [comment]
I cannot replicate the issue.
Are you able to replicate it on a server with only SSB installed?

**Comment by leon37921** [comment]
yes, same problem.
only Paper version git-Paper-550 (MC: 1.19.4)
+ SSB dev b137
I copied all the settings + database from the main-Server, deleted my island and created a new one.

The default biome for the world is plains, the schematic's biome is taiga.

**Comment by OmerBenGera** [comment]
I looked at it again and it seems that server-side the biomes are correct, however they are not synced with the player correctly.
The bug seems to occur in 1.19.4 and 1.20.4 (haven't tested any other versions), and sadly I cannot do anything in that manner on my side.

**Comment by OmerBenGera** [comment]
Hey, check out latest dev build -
I might have found a solution for this.

**Comment by leon37921** [comment]
tested with b291. Fixed. Thank you 👍

**Comment by leon37921** [comment]
@OmerBenGera the bug is back. I don't know since when, but I just noticed it. It was definitely fixed.
AdvancedSlimePaper version 1.21.7-16778-main@06e861f
SuperiorSkyblock2 version 2025.2.1-b793
SSBSlimeWorlds 2025.2

**Comment by OmerBenGera** [comment]
> [@OmerBenGera](https://github.com/OmerBenGera) the bug is back. I don't know since when, but I just noticed it. It was definitely fixed. AdvancedSlimePaper version 1.21.7-16778-main@06e861f SuperiorSkyblock2 version 2025.2.1-b793 SSBSlimeWorlds 2025.2

Open a new bug report please
