### ISSUE TITLE
Circular load order

### ISSUE THREAD

**Issue by ValdemarF20** [BG-Software-LLC/SuperiorSkyblock2#1980]
### Minecraft's Version

1.19.4

### Plugin's Version

SuperiorSkyblock2-2023

### Describe the bug

When using WildStacker, MythicMobs and MultiVerse I have this issue because of circular loading order:

https://paste.helpch.at/zonibomiro.md

### To Reproduce

Start server with WildStacker, MythicMobs and MultiVerse without using "-Dpaper.useLegacyPluginLoading=true"

### Additional Information

I know it technically works with "-Dpaper.useLegacyPluginLoading=true" but it's just a bit stupid to use that.

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it works

**Comment by ValdemarF20** [comment]
Testing tomorrow

**Comment by OmerBenGera** [comment]
https://bg-software.com/superiorskyblock/
https://hub.bg-software.com/view/Dev%20Builds/job/SuperiorSkyblock2%20-%20Dev%20Builds/

**Comment by ValdemarF20** [comment]
Hey! This seems to work now, but found another. You need to remove loadbefore for multiverse core
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79463502/5bbc3e85-a8da-4575-9581-b771f7d97f18)

**Comment by OmerBenGera** [comment]
> Hey! This seems to work now, but found another. You need to remove loadbefore for multiverse core ![image](https://private-user-images.githubusercontent.com/79463502/303062927-5bbc3e85-a8da-4575-9581-b771f7d97f18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODIxMzQsIm5iZiI6MTcwODA4MTgzNCwicGF0aCI6Ii83OTQ2MzUwMi8zMDMwNjI5MjctNWJiYzNlODUtYThkYS00NTc1LTk1ODEtYjc3MWY3ZDk3ZjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDExMTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDZmM2UzMGM3NzYyNWRhNWFhNGQ3MzcxMDUzOGM5YTQ4NzUxYjc2NzFmMGE1ZjlkZDczZDA3NmFjNDI1NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KsxFIH216ntvyrlW8DqAzljVKEL1F2GD_t8IRYdSf2Q)

SuperiorSkyblock2 must be loaded before MultiverseCore.
Contact ItemsAdder developers to get this fixed, or use the legacy plugins loading argument.
