### ISSUE TITLE
Withdraw message in chat

### ISSUE THREAD

**Issue by ValdemarF20** [BG-Software-LLC/SuperiorSkyblock2#1983]
### Minecraft's Version

1.19.4

### Plugin's Version

Latest

### Describe the bug

Whenever you withdraw from island bank the message event is not cancelled and therefore also sent to the entire server.
![F3B77598-A647-4B40-B7C9-E0C948B8C941](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79463502/baa4dcb0-fca1-41c2-bc46-979b95d10571)

### To Reproduce

Withdraw money from island bank

**Comment by OmerBenGera** [comment]
I cannot replicate the issue, and I suspect another plugin conflicts with SuperiorSkyblock.
Test it on a server with only SSB installed, let me know if you can replicate it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know
