### ISSUE TITLE
Generator Ore Issue

### ISSUE THREAD

**Issue by Casper-570** [BG-Software-LLC/SuperiorSkyblock2#1984]
### Minecraft's Version

1.20.4
paper-1.20.4-405

### Plugin's Version

2023.3-b134

### Describe the bug

When you level up on the Miner mission and get the upgraded generator for iron, it generates as redstone instead and you get no iron at all. 

https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/65895238/982c328b-2491-4308-8699-63cdf55ac350

### To Reproduce

Create a cobblestone generator and complete miner mission 1.

**Comment by OmerBenGera** [comment]
Check your generator rates using `/is admin show <player-name>`, do you see iron ore or redstone ore in there?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue continues let me know
