### ISSUE TITLE
Island Rename Global Announcement

### ISSUE THREAD

**Issue by TheWylot** [BG-Software-LLC/SuperiorSkyblock2#1985]
### Minecraft's Version

Paper 1.20.2

### Plugin's Version

Latest Dev Build

### Describe the bug

on Island Rename, the rename announcement goes for all of the online players.

### To Reproduce

just use island rename. see chat with another online player

**Comment by OmerBenGera** [comment]
Right, this is why it is an announcement - it is announced to all online players.

**Comment by TheWylot** [comment]
okey, i want to disable it, but there is no option.

**Comment by OmerBenGera** [comment]
> okey, i want to disable it, but there is no option.

Set the message to be empty
