### ISSUE TITLE
Animations of Custom Minions Stop Working on SuperiorSkyblock2 Islands - Armor Stand issue

### ISSUE THREAD

**Issue by VinceSMC** [BG-Software-LLC/SuperiorSkyblock2#1986]
### Minecraft's Version

**Minecraft version:** 1.20.4
**Paper version:** git-Paper-405

### Plugin's Version

**Plugin version:** SuperiorSkyblock2-2023.3-b134

### Describe the bug

After using my custom minions plugin with SuperiorSkyblock2, it has been observed that the animations for the minions cease to function after an undefined period. The issue appears to be linked to how SuperiorSkyblock2 interacts with armor stands, potentially marking them as 'dead' or altering their state in a way that interferes with the animation processes. This behavior is not observed when the minions are placed in worlds not managed by SuperiorSkyblock2, where their animations continue to work as expected.

### To Reproduce

This bug is encountered within a custom plugin we are developing. It can be reproduced by creating animations for an armor stand on a SuperiorSkyblock2 managed island, where, after some time, the animations cease to work, mirroring the issue we've observed with our minions.

### Additional Information

**Possible Causes:**
- SuperiorSkyblock2 may be altering the state of armor stands used by the minions plugin, potentially marking them as 'dead' or changing their properties in a way that halts the animations.
- There might be a conflict in how event handling or entity management is performed between SuperiorSkyblock2 and the custom minions plugin.

**Comment by OmerBenGera** [comment]
Maybe your island has limit for armor stands?
Otherwise, I can't think about a reason why it wouldn't work.

**Comment by VinceSMC** [comment]
Thanks for your quick response. I've thoroughly checked, and it's clear that an armor stand limit on the island (which, by the way, was created by SuperiorSkyblock) isn’t the issue we're facing. Could you provide some insight into how your plugin specifically manages entities? I'm beginning to suspect that this might be at the heart of our problem.

**Comment by OmerBenGera** [comment]
> @OmerBenGera Thanks for your quick response. I've thoroughly checked, and it's clear that an armor stand limit on the island (which, by the way, was created by SuperiorSkyblock) isn’t the issue we're facing. Could you provide some insight into how your plugin specifically manages entities? I'm beginning to suspect that this might be at the heart of our problem.

It only interacts with entities for limits.

**Comment by VinceSMC** [comment]
That could be where the problem lies. Is it possible to introduce an option to disable these entity limits?

**Comment by VinceSMC** [comment]
> > @OmerBenGera Thanks for your quick response. I've thoroughly checked, and it's clear that an armor stand limit on the island (which, by the way, was created by SuperiorSkyblock) isn’t the issue we're facing. Could you provide some insight into how your plugin specifically manages entities? I'm beginning to suspect that this might be at the heart of our problem.
> 
> It only interacts with entities for limits.

That could be where the problem lies. Is it possible to introduce an option to disable these entity limits?

**Comment by OmerBenGera** [comment]
> > > @OmerBenGera Thanks for your quick response. I've thoroughly checked, and it's clear that an armor stand limit on the island (which, by the way, was created by SuperiorSkyblock) isn’t the issue we're facing. Could you provide some insight into how your plugin specifically manages entities? I'm beginning to suspect that this might be at the heart of our problem.
> > 
> > 
> > It only interacts with entities for limits.
> 
> That could be where the problem lies. Is it possible to introduce an option to disable these entity limits?

The server owners can configure the entity limits.
However, SSB ignore entity limits for armor stands that are "vanished". Isn't this the case for your animations?

**Comment by OmerBenGera** [comment]
You can hook into the API of SuperiorSkyblock and register your own EntitiesProvider.
This interface contains a single method, `shouldTrackEntity`, which tells the plugin whether to track a specific entity.

You can register your own EntitiesProvider and return false for your animation entities within `shouldTrackEntity`, and it will fix the issue.

**Comment by VinceSMC** [comment]
> You can hook into the API of SuperiorSkyblock and register your own EntitiesProvider.
> 
> This interface contains a single method, `shouldTrackEntity`, which tells the plugin whether to track a specific entity.
> 
> 
> 
> You can register your own EntitiesProvider and return false for your animation entities within `shouldTrackEntity`, and it will fix the issue.

I can’t find the EntitiesProvider. Could you share an example of how to use it? I appreciate the help on this!

**Comment by OmerBenGera** [comment]
> > You can hook into the API of SuperiorSkyblock and register your own EntitiesProvider.
> > This interface contains a single method, `shouldTrackEntity`, which tells the plugin whether to track a specific entity.
> > You can register your own EntitiesProvider and return false for your animation entities within `shouldTrackEntity`, and it will fix the issue.
> 
> I can’t find the EntitiesProvider. Could you share an example of how to use it? I appreciate the help on this!

It is an API of the dev builds.
You can find the API jar on jenkins (https://hub.bg-software.com/) and build against it.
Hopefully it will be out as an official API soon.

**Comment by VinceSMC** [comment]
So I just tested it but it doesn't seem to work. I added a debug message to see when it detect and doesn't detect the minions and it seems that the detection of the minion stop as soon as I go to my island. When I join the server in a different world it does detect our minions.

The "should track found minion <----" is shown when I join the server in a different world, and the "should track not found minion" message is gives as soon as I join the island.

`   public boolean shouldTrackEntity(Entity entity)
    {
        if () # is minion check
        {
            Bukkit.broadcastMessage("should track found minion <--------------------");
            return false;
        }
        Bukkit.broadcastMessage("should track not found minion");
        return true;
    }`

**Comment by OmerBenGera** [comment]
> Could be that the issue lies somewhere else. The thing is that the ArmorStand from the minions are marked as dead as soon as I leave the island/server. That's when the animations stop working.

Weird.
I don't think SSB does that, I don't remember setting dead any entity at any point.
