### ISSUE TITLE
Island Missions Issue

### ISSUE THREAD

**Issue by YT-Duckyyy** [BG-Software-LLC/SuperiorSkyblock2#1987]
### Minecraft's Version

Client: 1.20.2
Server Jar: 1.20.2

### Plugin's Version

Devbuild #134

### Describe the bug

Can we please get is missions linked up for the island rather than a player? Currently it logs only the player development, not the island development as a whole, meaning only the players that complete it are able to do it. Please fix this.

### To Reproduce

Do is missions on 2 separate accounts on same island, it doesn't link up like it should

**Comment by Davisiiiik** [comment]
Have you tried adding `island: true` into the mission config file?

Citing [SSB2 Missions Wiki page](https://wiki.bg-software.com/superiorskyblock/overview/missions) (which you have surely honestly read):
> island: Whether or not the mission should be an islands mission (mission that is synced with all island members).
