### ISSUE TITLE
Chunk expansion problem

### ISSUE THREAD

**Issue by Fargus5** [BG-Software-LLC/SuperiorSkyblock2#199]
**Minecraft's Version**
Paper 1.16.5

**Plugin's Version**: -
dev build b111

I would like to modify the expansion system...
I'm trying to looking for something in the config file that let me set the expansion of the building area is done with chunk and not directional in a fair way

Is it possibile ?

**Comment by OmerBenGera** [comment]
No, sorry - that's not possible atm.
You can always request it to be added in discussions
