### ISSUE TITLE
Island missions statistic are reset on upgrade

### ISSUE THREAD

**Issue by Ammutadori075** [BG-Software-LLC/SuperiorSkyblock2#1991]
### Minecraft's Version

1.20.1 Tested on Pufferfish, Purpur and Paper

### Plugin's Version

Every last duild and dev build.

### Describe the bug

With each plugin update the island's mission files are overwritten, resetting all statistics.

### To Reproduce

do some missions, update superiorskyblock and when you restart the mission stats are at 0

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue continues let me know
