### ISSUE TITLE
Can't run command with island placeholder in TOP

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#1997]
### Minecraft's Version

paper 1.20.4

### Plugin's Version

b138

### Describe the bug

This issue is the continuation of : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/1976
In the "top-islands" gui, there is no placeholder to execute a command with the island owner in it.

I got a custom system on my side for island values per island, and can't open the gui from this top-islands, as I would need to execute : 

```
commands:
  '#':
    island:
    - openguiplayer {island}
  ```

**Comment by OmerBenGera** [comment]
Checkout latest dev build. I added the following placeholders:
`%island%` for the island's name
`%owner%` for the island owner's name

**Comment by WarnDa** [comment]
> Checkout latest dev build. I added the following placeholders: `%island%` for the island's name `%owner%` for the island owner's name

Working great thanks
