### ISSUE TITLE
The server crashed for unknown reasons. After a collapse, one player's island will appear to be disbanded and then teleport them back to their spawn point!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2003]
### Minecraft's Version

[15:33:08 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-15776 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 6e7ceea on paper_upstream)
Unknown version
Previous version: git-SlimeWorldManager-15766 (MC: 1.20.4)

### Plugin's Version

[15:33:25 INFO]: SuperiorSkyblock2 version 2023.3-b144
[15:33:25 INFO]: Feature packed Skyblock core.
[15:33:25 INFO]: Website: https://bg-software.com/
[15:33:25 INFO]: Author: Ome_R

### Describe the bug

The server crashed for unknown reasons. Upon collapse, a player's island will appear to disband, then teleport them back to their spawn point!Then I can only enter mysql and change the generated_schematics in the islands table from 15 to 12 to restore that player's island!

### To Reproduce

Every time the server crashes for unknown reasons! Below is the log from when the server crashed!

### Additional Information

Logs when a server crashes.:https://mclo.gs/Mu6XDqP
When the generated_schematic of island in mysql is 15:https://mclo.gs/IhuiuM2
When the generated_schematic of island in mysql is 12:It runs normally without any error, and then it will automatically change to 15 when it crashes next time, and then it will loop with errors.

**Comment by OmerBenGera** [comment]
Check if the island was saved to DB.
If it wasn't, then there's nothing to do.

**Comment by wlm1455925277** [comment]
> 检查岛屿是否已保存到数据库中。 如果不是，那就没什么可做的了。

In the database

**Comment by wlm1455925277** [comment]
> 检查该岛是否已保存到 DB。如果不是，那就无事可做。

I have tested the problem when you use the Slem Worlds module and then open the nether and the end in the configuration file and use the command /is admin tp [island name] nether and /is admin tp [island name] the_end to open the end and hell. After adjusting the island size to 60, this island will report an error!

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by wlm1455925277** [comment]
> 有这方面的消息吗？

This issue has been fixed by you, thank you for your work!

**Comment by wlm1455925277** [comment]
> 有这方面的消息吗？

I am from China and I am talking to you using translation software. I may speak strangely, but what I want to express is that this problem has been fixed by you. Thank you for maintaining this plug-in! I love this plugin!

**Comment by OmerBenGera** [comment]
Glad it works now :)
