### ISSUE TITLE
Players who become invincible

### ISSUE THREAD

**Issue by Jeawyn** [BG-Software-LLC/SuperiorSkyblock2#2004]
### Minecraft's Version

1.20.1

### Plugin's Version

Latest Stable

### Describe the bug

Players become invincible in an unknown condition, but it seems that this is mainly when they join an island, in co-op for example, even after a /spawn they keep their invincibility etc...

### To Reproduce

Players become invincible in an unknown condition, but it seems that this is mainly when they join an island, in co-op for example, even after a /spawn they keep their invincibility etc...

**Comment by OmerBenGera** [comment]
I dont believe it is related to the plugin, as it does not handle the world in any way.
What spigot jar do you use?

**Comment by Jeawyn** [comment]
I use the Paper 1.20.1

**Comment by Jeawyn** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/131651945/2667e4fb-1156-42e6-8542-e772b4eb0638)

**Comment by OmerBenGera** [comment]
Try it on a server with only SSB installed, you have many plugins here that may break it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know
