### ISSUE TITLE
Vehicle limit message does not show

### ISSUE THREAD

**Issue by anhcraft** [BG-Software-LLC/SuperiorSkyblock2#2006]
### Minecraft's Version

git-Tuinity-91cefbf (MC: 1.16.5)

### Plugin's Version

latest dev build

### Describe the bug

When the vehicle limit reaches, the boat is removed, however, no message is shown to the player.

### To Reproduce

1. Place boats until it is impossible to place further
2. No message is shown, even though the message exists in the locale file

### Additional Information

https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/0b8f57c5018485060dcd09ea6282249c3d654f3d/src/main/java/com/bgsoftware/superiorskyblock/module/upgrades/type/UpgradeTypeEntityLimits.java#L193

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by anhcraft** [comment]
> Check out latest dev build, let me know if it is fixed

Still not working

**Comment by OmerBenGera** [comment]
How do you put the minecart or boat?
It seems to work fine for me.

**Comment by anhcraft** [comment]
> How do you put the minecart or boat? It seems to work fine for me.

I made a fresh installation using the dev build. Configure the boat limit. Deop myself to prevent bypass permission. When putting the boat above the limit, no message is shown.

```yaml
default-values:
  island-size: 20
  block-limits:
    HOPPER: 8
  entity-limits:
    MINECART: 4
    BOAT: 4
```

**Comment by OmerBenGera** [comment]
Maybe you're in creative?
I disabled messages in creative mode (I don't know why, will change it)

**Comment by anhcraft** [comment]
> Maybe you're in creative? I disabled messages in creative mode (I don't know why, will change it)

ah you are right, I was in creative. Tested again today and it works well (survival mode)

**Comment by OmerBenGera** [comment]
Awesome :)
In latest dev build it should also work in creative mode
