### ISSUE TITLE
Bug with generator

### ISSUE THREAD

**Issue by Rap3erka** [BG-Software-LLC/SuperiorSkyblock2#2011]
### Minecraft's Version

1.19.4

### Plugin's Version

2023.3 20/01/2024 10:51:42

### Describe the bug

Every now and then you can't mine the cobblestone generator because it stops

### To Reproduce

Build a generator on the island and dig non-stop for a while

**Comment by OmerBenGera** [comment]
The plugin only changes the blocks that are generated, not the physics of how they generate.
Try updating to latest dev build of the plugin and use Paper, it will probably fix the issue.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs let me know
