### ISSUE TITLE
command cmdall not working properly

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2012]
### Minecraft's Version

1.20.4 paper

### Plugin's Version

b134

### Describe the bug

I can't run a command for ALL islands member, it only execute it on online players.
Even when they login, the command I did when they were offline isn't send

### To Reproduce

Here I try to put it false or true for the offline option : 
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/7294784b-1012-4c66-b94a-2b722fc927fd)

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/bb0f4c18-83b1-45fe-856d-2a4edb5ba899)

**Comment by OmerBenGera** [comment]
Thats intended.
The command will run only for the current online players of the island.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is fixed

Fixed thanks :D
