### ISSUE TITLE
Member-role/manage menu titles missing placeholder

### ISSUE THREAD

**Issue by Srcsm** [BG-Software-LLC/SuperiorSkyblock2#2014]
### Minecraft's Version

1.20.2

### Plugin's Version

2023.3-b148

### Describe the bug

Both menus [member-manage.yml](https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/src/main/resources/menus/member-manage.yml) and [member-role.yml](https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/src/main/resources/menus/member-role.yml) have only the following default titles:
```YML
title: '&8&l{}'
```
In-game these don't get replaced with the members name that you're attempting to edit.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/11580870/9d1d0d73-b03e-4081-86ed-39b61f08b483)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/11580870/619db349-24c1-47df-a96f-6644e247021b)

### To Reproduce

- Load up a server with SSB2
- Create/join island
- Invite member to island
- Manage members through `/is members`

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Srcsm** [comment]
They work perfect now. thank you Ome_R! :)
