### ISSUE TITLE
Regarding the issue of server crash caused by public teleport points after installing the Slime Worlds module

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2018]
### Minecraft's Version

[00:34:57 INFO]: Current: git-SlimeWorldManager-30 (MC: 1.20.4)*
Previous: git-SlimeWorldManager-15783 (MC: 1.20.4)
* Unknown version

### Plugin's Version

[00:35:11 INFO]: SuperiorSkyblock2 version 2023.3-b148
[00:35:11 INFO]: Feature packed Skyblock core.
[00:35:11 INFO]: Website: https://bg-software.com/
[00:35:11 INFO]: Author: Ome_R

### Describe the bug

When you install the Slime Worlds module, if the public teleport point Slime Worlds is not loaded, the server will crash!

### To Reproduce

Install the Slime Worlds module and then set up a public teleport point on your island. Then use the command to uninstall Slime Worlds and click to teleport the public teleport point. The server will crash!

**Comment by OmerBenGera** [comment]
Already opened on the slime worlds module repo
