### ISSUE TITLE
Brushing on other islands

### ISSUE THREAD

**Issue by JanReich** [BG-Software-LLC/SuperiorSkyblock2#2019]
### Minecraft's Version

1.20.4

### Plugin's Version

2023.3

### Describe the bug

Player can brush on other Players island

### To Reproduce

Visit a island from an other player where you dont have any permission and try to brush suspicious materials

**Comment by OmerBenGera** [comment]
Fixed on latest dev build
You can use the `Brush` permission, and it is assigned to coops by default (make sure you add it to your config file, as well as check out the default permissions menu file)

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs let me know
