### ISSUE TITLE
When Island is create there is everything in shadows (black

### ISSUE THREAD

**Issue by bronzzze** [BG-Software-LLC/SuperiorSkyblock2#2022]
### Minecraft's Version

1.20.4-R0.1-SNAPSHOT

### Plugin's Version

2023.3

### Describe the bug

When There is new Island created there is all in shadows(black). When I interact with blocks it fixes brigtness of this area I clicked. 
![Screenshot_10](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/10884035/695fc2c9-9b48-4dd1-90a2-65bbd21034a7)
![Screenshot_9](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/10884035/0c90433f-f399-4e69-bab9-5cabc959d629)

### To Reproduce

Creating new island

**Comment by OmerBenGera** [comment]
Enable lights update in the config file and use Paper.
