### ISSUE TITLE
Island chunks not fully initializing after their initial generation

### ISSUE THREAD

**Issue by airoons** [BG-Software-LLC/SuperiorSkyblock2#2028]
### Minecraft's Version

1.20.4

### Plugin's Version

One of dev versions with some additional patches on top of it, but not relevant

### Describe the bug

Hey, I noticed entities are not counted again after server reboots in chunks where they spawned.

https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/listener/ChunksListener.java#L49

This line is only run with the initial chunk generation (the e.isNewChunk() blocks it) - I am 95% sure it should run on all chunk loads.

### To Reproduce

See above

**Comment by OmerBenGera** [comment]
Not a duplication of the issue, but already been somewhat reported here: #1988 

I need to completely redesign this system as it really doesn't work well at this moment.
