### ISSUE TITLE
SkinsRestorer error on join

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#203]
**Minecraft's Version**
Tuinity 1.16.5 (proxy BotFilter (bungeecord))

**Plugin's Version**: -
1.6.0

**Describe the bug**
Console error on server join with skinsrestorer and bungeecord installed
https://pastebin.com/DY19XT3h

**To Reproduce**
Join the bungeecord server with skinsrestorer

**Comment by OmerBenGera** [comment]
Duplicate of #154
