### ISSUE TITLE
ERROR REGARDING "DISABLED-COMMANDS"

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/SuperiorSkyblock2#2031]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-46 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: fb16f9c on HEAD)
You are on the latest version!
Previous version: git-Pufferfish-44 (MC: 1.20.4)

### Plugin's Version

b147

### Describe the bug

After disabling the "IS HELP" command, an error appears when someone types something incorrectly.

Why did I turn off IS HELP? I created my own IS HELP in another plugin to be able to fully customize under myself.

### To Reproduce

disabled-commands:
- help

You should so set in config.yml, and then on the server enter a command that does not exist, for example /is spawn

**Comment by OmerBenGera** [comment]
What do you expect to happen if `/is help` does not exist? just nothing?

**Comment by Aides123** [comment]
Yes. I created a help in another plugin regarding SKYBLOCK and that's where the /is help command is.

**Comment by Aides123** [comment]
So that's why it was turned off in SuperiorSkyBlock because it's unnecessary and confusing (On my server) however, it can't be turned off because it throws errors in the console :p

**Comment by OmerBenGera** [comment]
So the other plugin just overrides SSB's `/is help` command?
Because the plugin have some cases where it forces a player to run `/is help`

**Comment by Aides123** [comment]
"So the other plugin just overrides SSB's /is help command?" yes

https://pastebin.com/Mex8iiBZ

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Aides123** [comment]
The error no longer appears :)

However, when a player uses a command incorrectly he gets no notification. There is an option to add a message like: You used a command incorrectly, try /is help.

**Comment by Aides123** [comment]
Unfortunately, there is still nothing

**Comment by OmerBenGera** [comment]
The plugin makes the plugin execute `/is help` if the command is disabled.
Do you have a plugin that overrides that command?

**Comment by OmerBenGera** [comment]
Well, the plugin forces the player to run `/is help`.
From this point, nothing can be done on my end.
