### ISSUE TITLE
Cannot create islands in the nether

### ISSUE THREAD

**Issue by hiiamken** [BG-Software-LLC/SuperiorSkyblock2#2033]
### Minecraft's Version

This server is running Paper version git-Paper-454 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 99a6416)
You are running the latest version
Previous version: git-Paper-450 (MC: 1.20.4)

### Plugin's Version

2023.3-b148

### Describe the bug

I cannot enter the Nether

### To Reproduce

1. Create an island
2. Create a nether portal
3. Entering, the nether world is empty

### Additional Information

https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/142149960/b595c029-843b-42d3-9c57-750906f70672

**Comment by OmerBenGera** [comment]
Do you have nether enabled in the config file of thr plugin? Also, is it unlocked for your island?

Also, try it on a server with only SSB inatalled

**Comment by hiiamken** [comment]
I have turned it on in the config. Currently, some people can create this wall, some people can't? Please tell me how to delete island data in the nether and the end without losing island data in SuperiorWorld

**Comment by OmerBenGera** [comment]
When you teleported to the nether, you received "you have reached the edge of the world".

I believe you configured the nether world's size to be too small. Make sure the world size is not small so players can teleport to their nether island.

**Comment by OmerBenGera** [comment]
> I have turned it on in the config. Currently, some people can create this wall, some people can't? Please tell me how to delete island data in the nether and the end without losing island data in SuperiorWorld

You can delete the nether or end world only by deleting the world files.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by hiiamken** [comment]
I deleted world and reinstalled everything from scratch, everything is working fine

**Comment by OmerBenGera** [comment]
Great.
If you have any more issues, make sure you open a new bug report :)
