### ISSUE TITLE
An unexpected error occurred while enabling the plugin

### ISSUE THREAD

**Issue by pjindras** [BG-Software-LLC/SuperiorSkyblock2#2035]
### Minecraft's Version

1.20.4, Java 21

### Plugin's Version

dev build 155 09/03/2024 17:16:10

### Describe the bug

Server cannot start, plugin cannot start.

### To Reproduce

Use Java 21

### Additional Information

https://paste.gg/p/anonymous/8cbc47d2da3544c8b6dc7d14060605bb

**Comment by OmerBenGera** [comment]
What version of Spigot do you use?
The exqct output of `/version` please

**Comment by pjindras** [comment]
Current: git-Purpur-2160 (MC: 1.20.4)*
Previous: git-Purpur-2159 (MC: 1.20.4)

**Comment by pjindras** [comment]
> What version of Spigot do you use? The exqct output of `/version` please

But I tried also the same on Leaf and its not working too there.

**Comment by OmerBenGera** [comment]
Does it happen if you use Paper?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
