### ISSUE TITLE
generator block spawning invisible bug

### ISSUE THREAD

**Issue by YavuzKarapinar** [BG-Software-LLC/SuperiorSkyblock2#2039]
### Minecraft's Version

1.20.1

### Plugin's Version

latest

### Describe the bug

when you make cobblestone generator is producing the block but its not visible when you try to break the block its breaking the block its behind. I added screenshot to additional information. But if you right click to produced block you can see and break the block. Other than that you cant break or see the block.

### To Reproduce

you just need to make cobblestone generator

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/57010842/40dc0fb9-cd8f-4e31-9da4-6c364a54e83a)

**Comment by OmerBenGera** [comment]
Try using Paper 1.20.4 and only latest dev build of SSB on your server.
Does this still occur?

**Comment by YavuzKarapinar** [comment]
i tried with paper 1.20.4 and spigot 1.20.4 with the latest dev build now its working but its not working with 1.20.1 and 1.20.2 with latest stable build of ssb.

**Comment by OmerBenGera** [comment]
> i tried with paper 1.20.4 and spigot 1.20.4 with the latest dev build now its working but its not working with 1.20.1 and 1.20.2 with latest stable build of ssb.

It works fine for me on all versions using latest dev build of SSB
