### ISSUE TITLE
Tourists place boats on other people's islands even though they have no rights

### ISSUE THREAD

**Issue by tncc2k** [BG-Software-LLC/SuperiorSkyblock2#2040]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

SuperiorSkyblock2-2023.3

### Describe the bug

Tourists place boats on other people's islands even though they have no rights

### To Reproduce

Place the boat on someone else's island

**Comment by OmerBenGera** [comment]
This was fixed in later dev build versions.
Check out latest dev build, let me know if it still occurs

**Comment by tncc2k** [comment]
It still happens (SuperiorSkyblock2-2023.3-b159.jar)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by tncc2k** [comment]
Has been fixed
