### ISSUE TITLE
Ender Dragon not spawning End Portal or Dragon Egg

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#2042]
### Minecraft's Version

1.18.2

### Plugin's Version

[18:59:45 INFO]: This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)

### Describe the bug

After killing the dragon it doesn't wanna spawn an end portal or dragon egg, I even tried it with the default schematic.

### To Reproduce

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/41546701/019def99-4106-4cd7-98b1-941fdafadffd)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/41546701/32b94264-5fbd-45a7-ada8-0f9d89b5701c)

**Comment by Superalex0102** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/41546701/227b0a4b-f717-4531-9b16-c4821c78ac02)
I even tried with a built portal

**Comment by OmerBenGera** [comment]
There are plenty of issues with the ender dragon mechanism.
I need to completely recode it.

There are already opened issues regarding this, so I am closing this for now
