### ISSUE TITLE
When you use the "/is level" command after placing a block in the nether, it does not count the last blocks placed.

### ISSUE THREAD

**Issue by giantfurkii** [BG-Software-LLC/SuperiorSkyblock2#2049]
### Minecraft's Version

1.20.4

### Plugin's Version

Dev Builds
#163 06/04/2024 13:48:17

### Describe the bug

When you use the "/is level" command after placing a block in the nether, it does not count the last blocks placed.

### To Reproduce

When you use the "/is level" command after placing a block in the nether, it does not count the last blocks placed.

### Additional Information

When you use the "/is level" command after placing a block in the nether, it does not count the last blocks placed.

**Comment by giantfurkii** [comment]
I took a video to show the error.
https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/78488589/d086131d-f39b-4c38-9cd2-7280f381b017

**Comment by giantfurkii** [comment]
https://youtube.com/shorts/Uqy70q2RJv0?feature=share

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue
I placed some gold blocks in the overworld and in the nether, then typed `/is level` and they are all counted correctly.

Are you able to replicate it on a server with only SSB installed, default config files (make sure you enable the nether world)?

**Comment by giantfurkii** [comment]
https://mclo.gs/YmOZgvG My configuration file is like this.

**Comment by OmerBenGera** [comment]
> "SuperiorWorld" There is no problem in this world. The problem I am talking about is "SuperiorWorld_nether" in this world.

As I said, I placed blocks in the nether, then ran `/is level` and they are all counted.

**Comment by giantfurkii** [comment]
How can you not approve even though you see the error?

**Comment by OmerBenGera** [comment]
> How can you not approve even though you see the error?

I cannot replicate the issue on my own server.

**Comment by giantfurkii** [comment]
How can I turn off the blocks placed on the Nether island from giving points?

**Comment by giantfurkii** [comment]
and I don't want it to calculate automatically when the player puts a block. I just want the level to be calculated with the "/is level" command.

**Comment by OmerBenGera** [comment]
> How can I turn off the blocks placed on the Nether island from giving points?

Not possible.

> and I don't want it to calculate automatically when the player puts a block. I just want the level to be calculated with the "/is level" command.

Not possible neither sadly

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
