### ISSUE TITLE
Mob drops duplication glitch

### ISSUE THREAD

**Issue by MZhenkM** [BG-Software-LLC/SuperiorSkyblock2#205]
**Minecraft's Version**
1) 1.12.2 Taco
2) 1.12.2 Taco

**Plugin's Version**: -
1) Last Dev 106
2) Last Dev 106

**Describe the bug**
1) It happens that the loot of mobs, by default, is doubled when you kill them, for example, if you kill a spider, it usually gives you one or two spider eyes, but, it happens that when you kill it, it gives you 4.

Another example, when you throw a sword or any item at a zombie and kill it, it gives you double. If you throw an enchanted full pick, it will give you 2 enchanted full picks.

2) I think they said they had patched it, if I remember correctly, but it happens that when the skeletons are stacked and you start to kill them, only the one in the first row has a bow, the others do not.

**To Reproduce**
1) Kill any mob
2) kill a stacked skeleton

**Additional information**
(BUG 1)
1) in discord they said that this is solved by changing values, but try the two differently and it doesn't work.
1) https://gyazo.com/97e5be76eca34e5d7b71b1c7ed30a2f1
1) https://gyazo.com/21f55f5f36d789f5f4221b809cf743fc

(BUG 2)
2) https://gyazo.com/30a7ebd4a7ea2f5160915cf4ff1ed343
2) https://gyazo.com/3773f375c62d696e4c5b49a9cfb5b867

**Comment by MZhenkM** [comment]
https://www.youtube.com/watch?v=55aLgcrDZ_c

Would you be so kind to watch the whole video? it doesn't take long

**Comment by MZhenkM** [comment]
So...? Any idea?

**Comment by OmerBenGera** [comment]
Check out latest build, it should be fixed

**Comment by MZhenkM** [comment]
fixed
