### ISSUE TITLE
Error Skyblock

### ISSUE THREAD

**Issue by zLestDev** [BG-Software-LLC/SuperiorSkyblock2#2050]
### Minecraft's Version

Paper 1.8.8

### Plugin's Version

2023.3

### Describe the bug

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70295826/a033d21c-df30-4248-9409-e64ebbebc7ba)

### To Reproduce

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/70295826/597c9371-d6f7-4010-9cd1-658123b65dba)

**Comment by OmerBenGera** [comment]
What version of ProtocolLib do you use?

**Comment by zLestDev** [comment]
4.3.0

**Comment by zLestDev** [comment]
updated this Protocol and resolved. Tanks
