### ISSUE TITLE
Bug pls speed answer

### ISSUE THREAD

**Issue by Coreli0** [BG-Software-LLC/SuperiorSkyblock2#2052]
### Minecraft's Version

1.20

### Plugin's Version

I dont know server is on 1.20

### Describe the bug

I have a problem because I bugged on the island killing myself with an arrow and now the owner of the island has banned me and keeps opening and closing the island which makes me teleport to spawn, can I fix myself somehow?

### To Reproduce

Go on island and kill yourself and respawn now the owner need to ban you form island and close and open island

**Comment by OmerBenGera** [comment]
After being killed on an island, you should respawn in the spawn island, unless it is your own island - then, you will reapawn on your own island again.

Can you upload a YT video that showcase the bug?

**Comment by Scorbunny10** [comment]
I can't but I can send a video with the teleporting to spawn

**Comment by OmerBenGera** [comment]
> I can't but I can send a video with the teleporting to spawn

If that can help, sure

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
