### ISSUE TITLE
Island Size bug

### ISSUE THREAD

**Issue by ardse** [BG-Software-LLC/SuperiorSkyblock2#2053]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

Latest stable build
#163 06/04/2024 13:48:17
#154 09/03/2024 17:13:25

All of them

### Describe the bug

I have a problem, the size of my starting island can't go below 25x25 anymore, whereas before I could easily set it to 5x5. You can see the video, I tested it on a server with only SBB and FAWE. 
https://www.youtube.com/watch?v=v05zjUSeVl0&ab_channel=Antoooiiinnneee

### To Reproduce

Do same as the video

**Comment by OmerBenGera** [comment]
If you have upgrades, then you should edit them instead of the default values in the config file.

**Comment by OmerBenGera** [comment]
You welcome :)
