### ISSUE TITLE
missing message

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2054]
### Minecraft's Version

git-Paper-459 (MC: 1.20.4)

### Plugin's Version

b163

### Describe the bug

When recheaching the limit of minecart or armor_stand, you don't get any message

### To Reproduce

Add in config :
```
  entity-limits:
    MINECART: 4
    ARMOR_STAND: 4
```
Place 5 minecart an 5 armor_stand : 
https://youtu.be/Qb_zMIjTbik

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
It’s good it works thanks !
