### ISSUE TITLE
error launching version 2023.3 in minecraft 1.20.4

### ISSUE THREAD

**Issue by Lele289** [BG-Software-LLC/SuperiorSkyblock2#2055]
### Minecraft's Version

purpur-1.20.4-2172

### Plugin's Version

2023.3

### Describe the bug

I inserted the plugin in the predestined folder and when the server starts it sends me this error, that the version is not supported, however on the spigot site, it tells me that all versions 1.20.+ are supported

### To Reproduce

install the purpur version 1.20.4, any is fine and then put the plugin in the default folder, then it gives the error when the machine starts

### Additional Information

https://pastebin.com/VUmm2ZJJ (error log)

**Comment by OmerBenGera** [comment]
Update to latest dev build
