### ISSUE TITLE
Islands are not created correctly

### ISSUE THREAD

**Issue by whoisalee** [BG-Software-LLC/SuperiorSkyblock2#2057]
### Minecraft's Version

1.20.1

### Plugin's Version

2023.3-b155

### Describe the bug

The error is simple. When trying to create the islands, my users get an error which does not allow them to go to them, when they forcefully go to them the area is empty, that is, it is not created correctly and the user cannot go. Additionally, several users have been reporting that their islands become corrupted, breaking a defined area of blocks or other cases.

### To Reproduce

The user has around 300 constant people throughout the day, when restarting the server the users can create islands normally, but after a random number of hours the error occurs and they continue to be spammed in the console

### Additional Information

https://pastebin.com/dRriiDLp

**Comment by OmerBenGera** [comment]
I haven't managed to replicate the issue myself, but I tried to fix it anyways.
Check out latest dev build, let me know if it is fixed

**Comment by whoisalee** [comment]
Hello, the error is no longer in the console. However, when trying to create an island, it is not created directly, that is, they remain in the processing request message.

**Comment by OmerBenGera** [comment]
> Hello, the error is no longer in the console. However, when trying to create an island, it is not created directly, that is, they remain in the processing request message.

Use `/is admin debug` in order to debug the island creation process.
You can use `LOAD_CHUNK`, `CREATE_ISLAND` and `PASTE_SCHEMATIC` to see exactly what doesn't work or gets stuck.

**Comment by OmerBenGera** [comment]
Also, check out #2051 - do you have the same issue?

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
