### ISSUE TITLE
new players die when creating a new island / or island preview

### ISSUE THREAD

**Issue by indogamercraft** [BG-Software-LLC/SuperiorSkyblock2#2058]
### Minecraft's Version

1.20.4

### Plugin's Version

#163 06/04/2024 13:48:17

### Describe the bug

Player dies when teleported to a new island or during island preview it says "left the confiens of this world", Previously it was fine, I didn't change anything

![2024-04-21_15](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/38981368/7207cdc3-cb3f-4b1b-90e3-862ebe39f9f8)

### To Reproduce

when a new player wants to create a new island and see the preview of the island, he dies with the words left the confiens of this world

**Comment by indogamercraft** [comment]
and I tried to destroy the block in is member and it couldn't be destroyed, even though it was already admin bypass

**Comment by AnakTentara** [comment]
Your Spawn and player Island world are the same. Set the world-border to false and the size to 0 in spawn config settings on config.yml. sorry for my english.

**Comment by indogamercraft** [comment]
> Your Spawn and player Island world are the same. Set the world-border to false and the size to 0 in spawn config settings on config.yml. sorry for my english.
> 
> edit: and try /worldborder damage amount 0 in random player island

its work thanks
