### ISSUE TITLE
Advanced Slime World Islands nether and the_end they are not recognized as such

### ISSUE THREAD

**Issue by xSavior-of-God** [BG-Software-LLC/SuperiorSkyblock2#206]
**Minecraft's Version**
1.16.5

**Plugin's Version**: 
1.6.0-DEVb112

**Describe the bug**
**To Reproduce**
When you create the island of the nether or the end it is not possible to place the blocks inside it
**REASON**: "You cannot build outside of your protection range."

**Additional information**
but the world is recognized as `isIslandWorld,` so I assume the problem is here
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/f753c49092b2ec637de6c8dea96beaad06a26e50/src/main/java/com/bgsoftware/superiorskyblock/handlers/GridHandler.java#L339

**Comment by OmerBenGera** [comment]
I published a new version, let me know if it works for you

**Comment by xSavior-of-God** [comment]
https://pastebin.com/pTtLeTcp

**Comment by xSavior-of-God** [comment]
it doesn't work, throw error as soon as I create the island, and cancel the creation of the island.... I tried to investigate... but nothing, to me the method returns _true_ when used, so I honestly don't know, maybe the initial declaration of the plugin instance is made too soon?
At least it is the only thing that comes to my mind and that can be the cause of this error... in case, can you try it to change the method like this one?
```java
    public Island add(UUID uuid, Island island){
        Location islandLocation = island.getCenter(World.Environment.NORMAL);
        islandsByPositions.add(IslandPosition.of(islandLocation), island);

        if(SuperiorSkyblockPlugin.getPlugin().getProviders().hasCustomWorldsSupport()){
            runWithCustomWorld(islandLocation, island, World.Environment.NETHER,
                    location -> islandsByPositions.add(IslandPosition.of(location), island));
            runWithCustomWorld(islandLocation, island, World.Environment.THE_END,
                    location -> islandsByPositions.add(IslandPosition.of(location), island));
        }

        islandsByUUID.add(island.getUniqueId(), island);

        return super.add(uuid, island);
    }
```

**Comment by xSavior-of-God** [comment]
reviewing the code as well, I can tell you with certainty that I am right, since you declare of the class `private final ProvidersHandler providersHandler = new ProvidersHandler(this);` is before the instantiating of the plugin variable... 
so if you do as I wrote before, the problem should be solved.

**Comment by xSavior-of-God** [comment]
Fixed, thanks
![image](https://user-images.githubusercontent.com/66216419/114315546-b7726e80-9aff-11eb-8855-d4789cea45bb.png)
