### ISSUE TITLE
SkyBlock Placeholder Update Issue Report

### ISSUE THREAD

**Issue by leonm-cloud** [BG-Software-LLC/SuperiorSkyblock2#2060]
### Minecraft's Version

1.20.4

### Plugin's Version

2023.3-b163.jar

### Describe the bug

When you depart from or dissolve an island, the placeholder fails to update to 'Guest' as intended, resulting in the SkyBlock not refreshing. In the image, my role should display as 'Guest' rather than 'Leader'...

After a server restart, the SuperiorPlayerRole placeholder resets to 'Guest'...

[Image](https://media.discordapp.net/attachments/554282577322704896/1232370129044639815/image.png?ex=6629359f&is=6627e41f&hm=c4330eea5b7b037eb5f583a6df7b51f3658b5a125546f0ef65ceb4a2286b7d7d&=&format=webp&quality=lossless&width=704&height=126)

### To Reproduce

On island leave/disband/kick placeholder value doesn't upddate to guest, and stays on the previous role.

### Additional Information

N/A

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by leonm-cloud** [comment]
The issue has been resolved.
