### ISSUE TITLE
Kick on dimension change

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#2061]
### Minecraft's Version

SlimeWorldManager version git-SlimeWorldManager-15796 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7b0ee15 on paper_upstream)

### Plugin's Version

2023.3-b167

### Describe the bug

When there are multiple players on island and one of them enter nethers, all the other players get lag and then are kicked with following message: `ReadTimeoutException : null`

When they reconnect, Nether dimension (where the 1st player went) will unload all chunks and player cannot move as seen in the next pictures:
![2024-04-23_20 59 18](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79375965/5007999c-2340-472b-accd-211054989819)
Changes to this:
![2024-04-23_20 59 04](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/79375965/305fcbf6-f0e2-472f-8640-a9983e885773)

### To Reproduce

1. Create island with nether portal
2. Go to island with multiple accounts (they dont need to be members, nor coop)
3. Go with one account to the Nether

### Additional Information

This bug occured first in version 2023.3-b167, 2023.3-b166 worked just fine.
This bug also occured on server WITHOUT ASWM.

**Comment by Davisiiiik** [comment]
Occasionally this error in console is shown alongside the issue:
```yaml
[19:10:30 ERROR]: [ChunkFullTask] Expected poi chunk to be loaded with chunk for task ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkFullTask, for world: island_0c2b9883-5296-46b4-9390-de0b0e55feea_normal, chunk: (-2,-1), hashcode: 772996886, priority: COMPLETING, status: minecraft:full, scheduled: true}
```

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue with two players.
I had one account in the island, and using the second one I went to the nether, and everything seems to be fine.

How many players do you need to replicate the issue?
Also, are you able to replicate it on a server with only SSB installed?

**Comment by wlm1455925277** [comment]
> 我似乎无法用两个玩家复制这个问题。我在岛上有一个账户，用第二个账户去了下界，一切似乎都很好。
> 
> 您需要多少玩家才能复制该问题？另外，您是否能够在仅安装了 SSB 的服务器上复制它？

Please do not use normal island to try. You can try it using other islands. For example, desert and mycel will only have this problem!

**Comment by wlm1455925277** [comment]
> 我似乎无法用两个玩家复制这个问题。我在岛上有一个账户，用第二个账户去了下界，一切似乎都很好。
> 
> 您需要多少玩家才能复制该问题？另外，您是否能够在仅安装了 SSB 的服务器上复制它？

Also requires the latest purpur core 1.20.4

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Davisiiiik** [comment]
Works great on latest version, thanks a lot!
