### ISSUE TITLE
Island category doesn't support :offset_-48: for custom GUI

### ISSUE THREAD

**Issue by ardse** [BG-Software-LLC/SuperiorSkyblock2#2062]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

Dev builds
SuperiorSkyblock2-2023.3-b163

### Describe the bug

In my missions config files inside modules, when I set : 
categories:
  collectionneur:
    name: ':27_mission:'
    slot: 0
    
It works great, but if I put this instead

categories:
  collectionneur:
    name: ':offset_-48::27_mission:'
    slot: 0
    
   It doesn't work anymore, I can’t open the menu
   
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/157892928/35b2c6a6-fbba-4617-8a2e-dbb49e17b6c7)

### To Reproduce

I have already put several menus without problem in the plugin, it is only there that the :offset_x: doesn't work.
I use itemsadder for all my GUIs

**Comment by OmerBenGera** [comment]
What is this offset attribute?

**Comment by ardse** [comment]
As you can see in the image, the GUI is offset from the menu. The offset allows it to be positioned correctly

**Comment by ardse** [comment]
up

**Comment by ardse** [comment]
Okay, I found. 
categories:
  collectionneur:
    name: ':offset_-49:§x§F§F§F§F§F§F去'
    slot: 0
  divers:
    name: ':offset_-48:§x§F§F§F§F§F§F去'
    slot: 1
  paysan:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 2
  mineur:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 3
  bucheron:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 4
  builder:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 5
  pecheur:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 6
  chasseur:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 7
  forgeron:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 8
  bricoleur:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 9
  tailleur:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 10
  cuisinier:
    name: ':offset_-51:§x§F§F§F§F§F§F去'
    slot: 11



If I create a menu with the same names, only one of the menus will works. For example, with this setup, only the "cuisnier" menu will work; the "tailleur" menu won't open. Instead, if I set in "tailleur" : name: ':offset_-32:§x§F§F§F§F§F§F去'—so **-32** instead of **-51** then the menu will open. I feel like if I use the **same value in the menu, it messes everything up**.

**Comment by OmerBenGera** [comment]
the `categories` section is for listing categories, not to edit the menu. The `name` in there is the name of the category of the mission, not the category's item. If you open the `missions.yml` menu file, you can edit there the item names of the categories. If you put the `offset` placeholder in there, hopefully, it should work.

**Comment by ardse** [comment]
The mission.yml allows us to edit the lore of each items category but not the title of each category

**Comment by OmerBenGera** [comment]
All that offset thingy is for items in menus. You can edit the item of the category in the `missions.yml` file.
The name of the category is not used in menus, but it is used internally only.

**Comment by ardse** [comment]
I think we're not understanding each other well. I only want to modify the titles of each category.

**Comment by OmerBenGera** [comment]
You can edit the menu's title directly. Check out `missions-category.yml` menu file, there you'll find a `title` section. You can use `{0}` as a placeholder for the category's name. You should be able to use the `offset` value in there as well, without changing the names of the categories.

**Comment by ardse** [comment]
Perfect, it works great here ! It was quite confusing but thank you for the help

**Comment by OmerBenGera** [comment]
> Perfect, it works great here ! It was quite confusing but thank you for the help

Took me some time to understand what you meant there
Glad it works :)
