### ISSUE TITLE
IslandMissions.jar issue

### ISSUE THREAD

**Issue by iDistopy** [BG-Software-LLC/SuperiorSkyblock2#2063]
### Minecraft's Version

 git-Purpur-2176 (MC: 1.20.4)

### Plugin's Version

Dev Build 158

### Describe the bug

I only setup the jar, start the server _(crash btw)_ and setup de db.
[errors.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/15137463/errors.txt)

### To Reproduce

Download and setup the plugin

**Comment by OmerBenGera** [comment]
The plugin doesn't seem to be able to access some files.
Put it under a directory that it has access to, and the path to the server files has no utf-8 chars.

Not really a bug, so I am closing this. You can get further support on discord if you need.
