### ISSUE TITLE
Upgrades doesnt change when changed in the document?

### ISSUE THREAD

**Issue by Qekker** [BG-Software-LLC/SuperiorSkyblock2#2064]
### Minecraft's Version

1.20.4

### Plugin's Version

SuperiorSkyblock2-2023.3-b171

### Describe the bug

So i changed some of the upgrades in the document in the modules folder. But they dont change in game for my players, what could be the issue here?

### To Reproduce

I just changed the procentages for ore generator as a start and then hoppers and team member limit.

### Additional Information

[upgrades-config.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/15141669/upgrades-config.zip)

**Comment by Qekker** [comment]
Hello again.
Do you know what i did wrong or what i can do to fix this?

**Comment by OmerBenGera** [comment]
It will be updated to all islands, unless their limits are not synced anymore.
You can use `/is admin show` to find out whether their limits are synced (there's a green symbol next to the value of the limit). You can sync the limits again using `/is admin syncupgrades`.

Not a bug, closing this.
