### ISSUE TITLE
Add permission for chorus teleport

### ISSUE THREAD

**Issue by DextralityNetwork** [BG-Software-LLC/SuperiorSkyblock2#2065]
### Minecraft's Version

Pufferfish 1.20.4

### Plugin's Version

SuperiorSkyblock2-2023.3-b167.jar

### Describe the bug

Several servers we have seen the possibility of adding this permission because certain users tend to want to deny this use of teleportation, whether chorus or enderpearl, so that other people can leave the zone of the stores that they assign.

### To Reproduce

Use chorus 
and teleport

**Comment by OmerBenGera** [comment]
Already exists - `CHORUS_FRUIT` is the privilege.

**Comment by OmerBenGera** [comment]
Closing this as it already exists in the plugin
If you need anything else, let me know

**Comment by DextralityNetwork** [comment]
https://prnt.sc/GA5rW11sFbWn
dont works in my case
https://prnt.sc/t1zMvu2Blbr7
https://prnt.sc/GjdV3vViUG7m

**Comment by DextralityNetwork** [comment]
ok right now works
