### ISSUE TITLE
SmoothTimber

### ISSUE THREAD

**Issue by fortunatas1** [BG-Software-LLC/SuperiorSkyblock2#2068]
### Minecraft's Version

Server version 1.20.1

### Plugin's Version

2023.3-b163

### Describe the bug

Players can destroy wood in protected skyblock islands using SmoothTimber plugin (https://www.spigotmc.org/resources/smoothtimber.39965/)

### To Reproduce

Players can destroy wood in protected skyblock islands using SmoothTimber plugin (https://www.spigotmc.org/resources/smoothtimber.39965/)

**Comment by OmerBenGera** [comment]
Report it over to them.

**Comment by fortunatas1** [comment]
https://github.com/SourceWriters/SmoothTimber/issues/85

**Comment by OmerBenGera** [comment]
> [SourceWriters/SmoothTimber#85](https://github.com/SourceWriters/SmoothTimber/issues/85)

They closed it.
Sadly, I cannot do anything on my end. They already do it with many other plugins, and they should add support SSB or change their listener priority.

I'd recommend to switch SmoothTimber with another plugin if they refuse to fix it.

**Comment by OmerBenGera** [comment]
I will make you an addon that fixes it.
They for no reason don't want to fix it on their end.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, let me know
