### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by Aarontjee050** [BG-Software-LLC/SuperiorSkyblock2#2069]
### Minecraft's Version

1.20.4

### Plugin's Version

Latest dev build

### Describe the bug

If i want to the commands without op its says unkown command. But i did all the commands in Luckperms so i dont understand 

### To Reproduce

I did /island = unkown command 
------
All the commands i did in Luckperms

### Additional Information

.

**Comment by OmerBenGera** [comment]
Give yourself the right permissions `superior.island.*`

Not a bug. For further help join the discord

**Comment by Aarontjee050** [comment]
It will say unkown command

**Comment by OmerBenGera** [comment]
Join the discord and ask for help.
