### ISSUE TITLE
Custom IslandPrivileges / role settings not getting saved

### ISSUE THREAD

**Issue by JakkitDE** [BG-Software-LLC/SuperiorSkyblock2#2074]
### Minecraft's Version

paper-1.20.4-496.jar

### Plugin's Version

SuperiorSkyblock2-2024.1.jar Stable build

### Describe the bug

I am registering an IslandPrivilege in my plugin. It registers in onEnable() method. Everything works fine. I also inserted it into permissions.yml menu. I can setup the role permissions for it. No problem.

But after restarting the server the role permissions of my IslandPrivilege have been reset. I also made SuperiorSkyblock2 a softdepend in my plugin.yml. On startup I am getting following error: 

`[12:58:56 WARN]: [SuperiorSkyblock2] Cannot load role permissions with invalid permission for 0f818889-f551-4de4-95a7-799116952787, skipping...`

### To Reproduce

Write a test plugin, register an IslandPrivilege. Run a server. You will be able to setup the role permission for the IslandPrivilege but the role permissions will be reset after rebooting the server. (Clean stop and start, not /reload!).

The SuperiorSkyblock2 ist a clean installation on the test server. There are no other plugins despite of my plugin I am currently working on.

**Comment by OmerBenGera** [comment]
Send me the entire session files.
I suspect your plugin loads after SSB is loading, and therefore it doesn't recognize your custom IslandPrivilege.

**Comment by JakkitDE** [comment]
> Send me the entire session files. I suspect your plugin loads after SSB is loading, and therefore it doesn't recognize your custom IslandPrivilege. You should add `SuperiorSkyblock2` to your `loadbefore` section, and then listen to `PluginInitializeEvent`. Or, even better, just use the modules system for that.

I do not know how to work with the modules system but go it working after your discord ticket answer. So thats not a bug, just was a stupid me 😁 Thank you.
