### ISSUE TITLE
Spawner limits not working

### ISSUE THREAD

**Issue by ItzSave** [BG-Software-LLC/SuperiorSkyblock2#2076]
### Minecraft's Version

1.19.4 

### Plugin's Version

2024.1 and 2023.3

### Describe the bug

With SuperiorSkyblock2 block limits don't work correctly with spawners and rose stacker.

It does not check the spawner type when attempting to place or when using the set limit command

### To Reproduce

Set a limit for a spawner type in the default section then attempt to remove

### Additional Information

Tested with RoseStacker 1.5.20

**Comment by ItzSave** [comment]
No there is nothing in the console

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself
Do you have RoseStacker set as your `spawners-provider`?

**Comment by ItzSave** [comment]
Yes have it set as spawner provider in the config

**Comment by OmerBenGera** [comment]
Do you see "Using RoseStacker as spanwers provider" in the console, after the server has started up?

**Comment by ItzSave** [comment]
No from what I can tell it only says it's using it as a stacked-blocks provider

**Comment by ItzSave** [comment]
Sorry my bad yes it does indeed log that

**Comment by ItzSave** [comment]
Yes, the spawner limit is displayed in that command.

Also on another note I made my own workaround with a custom plugin and learned that RoseStacker does not correctly report EntityType in the BlockPlaceEvent I had to use a method from RoseStacker to fetch the spawner type.

**Comment by OmerBenGera** [comment]
Using SSB (v2024.1.196) and RoseStacker (v1.5.20), on 1.19.4 Paper (Paper version git-Paper-550 (MC: 1.19.4)), and I cannot seem to replicate it.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by ItzSave** [comment]
No, I was able to make my own workaround system.
