### ISSUE TITLE
The players are beyond the border

### ISSUE THREAD

**Issue by malpii** [BG-Software-LLC/SuperiorSkyblock2#2078]
### Minecraft's Version

1.20

### Plugin's Version

SuperiorSkyblock2-2024.1.jar

### Describe the bug

When transferring files to a new machine, some (most) players cannot build, destroy, open chests, etc. on their island. Interestingly, they can only do anything at the spawn point (/is go). I think the border of the island has moved and I can't fix it.

In the picture shown, the player can build to the right, but not to the left.

### To Reproduce

.

### Additional Information

![Uploading plik.png…]()

**Comment by OmerBenGera** [comment]
I don't know what you've done, but if you moved files and nothing was changed, then nothing would break.
I suspect you somehow got the files to be corrupted (mainly the DB), or you changed something that is broken.

Check if the islands in the DB are the same as before, and that the world wasn't changed. Other than that, I don't see how I can help, sadly.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
