### ISSUE TITLE
The player is resurrected

### ISSUE THREAD

**Issue by Nanyu123456** [BG-Software-LLC/SuperiorSkyblock2#2079]
### Minecraft's Version

1.20.1

### Plugin's Version

b191

### Describe the bug

The player can only respawn at 0 100 0 after dying on the island, and there is no command to respawn on the island, or to respawn in other worlds in the MV

### To Reproduce

kill

**Comment by OmerBenGera** [comment]
When a player dies, he will respawn according to what is configured in the config file.
By default, the player will first get teleported to his island. If he doesn't have an island, he will be teleported to spawn.
You can also configure BED_TELEPORT or VANILLA - check out `player-respawn` in the config file.
You can also configure the spawn location to be whereever you want, even in other worlds.
