### ISSUE TITLE
Warp menu not working

### ISSUE THREAD

**Issue by Leyji** [BG-Software-LLC/SuperiorSkyblock2#208]
**Minecraft's Version**
Paper 1.12.2

**Plugin's Version**: -
SuperiorSkyblock2-b112

**Describe the bug**
Warp menu is not working (doesn't show warps)

**To Reproduce**
Open /is warps menu

**Additional information**
Error: https://pastebin.com/f5KxND66

**Comment by OmerBenGera** [comment]
There's a warp with an invalid icon or something like that

**Comment by Leyji** [comment]
How can something like that happen? How can I find the warp?

**Comment by nivcoo** [comment]
You can look into your logs files

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
