### ISSUE TITLE
Upgrades are free

### ISSUE THREAD

**Issue by MarkGamez1** [BG-Software-LLC/SuperiorSkyblock2#2081]
### Minecraft's Version

1.20.4, Paper

### Plugin's Version

SuperiorSkyblock2-2024.1

### Describe the bug

All my upgrades say they are available even though they arent, I dont have the materials required and I just started.

### To Reproduce

Theres not really a way to reproduce, I just started playing.

### Additional Information

There was no way to access the island command without being in op, and i thought that was the problem so i installed "LuckPerms" so i could play without being in op and the problem still occured.

**Comment by OmerBenGera** [comment]
Upgrades are purchasable, you dont need any materials. You probably have enough money or you didnt set up your economy plugin correctly.

Regarding LuckPerms, give yourself `superior.island.*`. For further support, ask on the discord server for help
