### ISSUE TITLE
Placing spawners with WildStacker requires Spawner Break permissions

### ISSUE THREAD

**Issue by RVSkeLe** [BG-Software-LLC/SuperiorSkyblock2#2083]
### Minecraft's Version

1.16.5

### Plugin's Version

2023.3-b124

### Describe the bug

A player cannot place spawners next to already existing stacked spawners if he doesn't have Spawner Break permissions, which is a major security flaw.

### To Reproduce

Get coop in another player's island -> disable spawner break privilege -> place spawners in radius to add to existing ones (increase them) -> enable spawner break privilege -> can add spawners to stacked ones.

**Comment by OmerBenGera** [comment]
Hey,
I can't seem to replicate it. I assume you use SuperiorSkyblock + WildStacker to trigger this issue?
Try updating both plugins to their latest versions, let me know if you still manage to replicate it

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by RVSkeLe** [comment]
> Check out latest dev build, let me know if it is fixed

Hello Omer, the issue isn't fixed, but I figured I haven't explained properly the issue, I recorded a video to explain better the problem (I do not use the WS menus): https://youtu.be/FuDWFtw8aAg

**Comment by OmerBenGera** [comment]
Yeah that's intended, right clicking a spawner requires the `SPAWNER_BREAK` privilege.
I can think about changing it to only require the `INTERACT` privilege (as long as you added spawner to the interactable blocks list), but that might also be weird that you can open the spawner menu but you don't have access to break or place spawners...

**Comment by RVSkeLe** [comment]
> Yeah that's intended, right clicking a spawner requires the `SPAWNER_BREAK` privilege. I can think about changing it to only require the `INTERACT` privilege (as long as you added spawner to the interactable blocks list), but that might also be weird that you can open the spawner menu but you don't have access to break or place spawners...

Now I get it, because I dont use the menu in WS, could it be possible to add a check if the spawners menus are enabled? I think that this could be a great solution

**Comment by OmerBenGera** [comment]
Remove mob spawners from the interacables list (it has its own file)

**Comment by RVSkeLe** [comment]
> Remove mob spawners from the interacables list (it has its own file)

Thank you, I didnt know they were interactable, that worked and fixed the issue!

**Comment by OmerBenGera** [comment]
Awesome, glad it works :)
Closing this for now
