### ISSUE TITLE
High ram usage from tracking block placement/removal

### ISSUE THREAD

**Issue by xsorencoolx** [BG-Software-LLC/SuperiorSkyblock2#2086]
### Minecraft's Version

1.18.2

### Plugin's Version

dev build 200 SuperiorSkyblock2 

### Describe the bug

there is memory leak issue on SuperiorSkyblock plugin

### To Reproduce

just run server with players on it

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/51112473/9c4286d4-53d6-4a92-8b23-a33f2aee6f37)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is better

**Comment by OmerBenGera** [comment]
Mind sending me the profiler file instead of a screenshot?

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be better
I also found an issue with the way blocks were serialized that should be fixed

**Comment by OmerBenGera** [comment]
> good job omer it got fixed thank you very much

Awesome!
Please send me a heap profiler, I'd like to see the improvement :)

**Comment by OmerBenGera** [comment]
FarmingMissions seems to also take high ram usage
I will look into it as well

**Comment by OmerBenGera** [comment]
Check out latest dev build, you should see another improvement
Also, send me the heap profiler using this version :)

**Comment by OmerBenGera** [comment]
Much better now :)
I'll close this for now, I will also implement more improvements in the near future, and hopefully you'll see even more improvements on that matter (schematics, stacked blocks...)

Closing this for now :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, stacked blocks & schematics should be optimized
Also, please upload a new heap dump :)

**Comment by WarnDa** [comment]
To easily track placed block there is this plugin :
https://modrinth.com/plugin/blocktracker/

We added it to all our plugins (Jobs, beasttokens, Quests, private ones)
Here is an exemple of the hook : https://github.com/Zrips/Jobs/pull/1743
Or quests : https://github.com/LMBishop/Quests/tree/master/bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/playerblocktracker

**Comment by OmerBenGera** [comment]
> To easily track placed block without having a big hashmap or a database there is this plugin : https://modrinth.com/plugin/blocktracker/
> 
> We added it to all our plugins (Jobs, beasttokens, Quests, private ones) Here is an exemple of the hook : [Zrips/Jobs#1743](https://github.com/Zrips/Jobs/pull/1743) Or quests : https://github.com/LMBishop/Quests/tree/master/bukkit/src/main/java/com/leonardobishop/quests/bukkit/hook/playerblocktracker

SSB has the same implementation for blocks tracking internally
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/core/collections/Chunk2ObjectMap.java
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/core/collections/Location2ObjectMap.java

**Comment by OmerBenGera** [comment]
@xsorencoolx Have you had the chance to look into this?

**Comment by OmerBenGera** [comment]
> ye i use SuperiorSkyblock2-2024.1-b231.jar https://www.mediafire.com/file/bbtqogyhduyc2ud/heap-2024-07-15_15.43.01.hprof.gz/file

Looking really good now, thanks for the help!
I am closing this now
