### ISSUE TITLE
Fire Spread

### ISSUE THREAD

**Issue by mat37dev** [BG-Software-LLC/SuperiorSkyblock2#2087]
### Minecraft's Version

Minecraft Version: 1.20.1
Paper: git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Plugin's Version

2024.1 stable build 11/05/2024 19:46:51

### Describe the bug

when I deactivate fire propagation with the settings, the fire spreads to a nearby block but does not break the block. Maybe its just a visual bug

### To Reproduce

take lava, take wood and disable fire Spread in is setting

**Comment by OmerBenGera** [comment]
This is how it is, not possible to be fixed
This is a limit of Spigot
