### ISSUE TITLE
Water spread

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2091]
### Minecraft's Version

1.20.4 paper fork

### Plugin's Version

b200

### Describe the bug

When disabling water flowing but placing it on soul-sand, it spread 1 block (see video)

### To Reproduce

https://youtu.be/5qRLtji8mvQ

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/ce38d750-a579-4c01-8e99-382079e4be7f)

working thanks
