### ISSUE TITLE
Disable raid on other people's islands

### ISSUE THREAD

**Issue by OmerBenGera** [BG-Software-LLC/SuperiorSkyblock2#2093]
### Discussed in https://github.com/BG-Software-LLC/SuperiorSkyblock2/discussions/2092

<div type='discussions-op-text'>

<sup>Originally posted by **HicSuntLeon3s** May 31, 2024</sup>
Hi, can you add a way to prevent that players with the bad omen effect are able to trigger a raid on other people's islands when they have it? For example an is permission. Thanks in advance</div>

**Comment by OmerBenGera** [comment]
@HicSuntLeon3s Check out latest dev build, let me know if it is fixed

**Comment by HicSuntLeon3s** [comment]
Hi, thanks for your fast answer and fix! Now it looks perfect.
