### ISSUE TITLE
Zombie Reinforcements

### ISSUE THREAD

**Issue by Bragos24** [BG-Software-LLC/SuperiorSkyblock2#2095]
### Minecraft's Version

Paper 1.20.1

### Plugin's Version

2024.1-b203

### Describe the bug

Hi, even though I disabled the natural mob spawning in the island settings, the Zombie Reinforcements continue to spawn when I hit zombies spawned by Mob Spawner.  I wonder if there is a way to fix it, thanks in advance

### To Reproduce

Disable natural mob spawning and hit zombies spawned by Mob Spawner. I recommend doing it in The End.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed.
The island flag `NATURAL_MONSTER_SPAWN` should prevent them from spawning
