### ISSUE TITLE
Going to islands crashes the entire server.

### ISSUE THREAD

**Issue by naudwuar** [BG-Software-LLC/SuperiorSkyblock2#2097]
### Minecraft's Version

paper 1.20.6 

### Plugin's Version

SuperiorSkyblock2-2024.1-b213

### Describe the bug

Anytime a player goes to their island, the server crashes. 

And since server crashes while we are on the island, we cannot join or else the server just keeps crashing.

[crash-2024-06-01_11.10.47-server (1).txt](https://github.com/user-attachments/files/15522588/crash-2024-06-01_11.10.47-server.1.txt)

### To Reproduce

I couldn't tell you the exact steps leading up to this issue because it was working great, we went to bed, server did its daily restart the following morning and that's when everything started going wrong.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, let me know
