### ISSUE TITLE
Can't recalc island

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2098]
### Minecraft's Version

1.20.4 paper

### Plugin's Version

b216

### Describe the bug

Error when I try to recalc : https://paste.gg/p/anonymous/367bd78ea7394a2ab83b6137aaf68a0b

### To Reproduce

/

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
Working thanks
