### ISSUE TITLE
Sparks of the plugin at +200 players

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2099]
### Minecraft's Version

1.20.4 paper fork

### Plugin's Version

b218

### Describe the bug

I see you are currently working on optimizations and other things, but it's sometimes hard to see the impact.
So as I opened my new version and get a lot of players, I'll provide sparks so you can see by yourself :

### To Reproduce

/

### Additional Information

here are sparks on latest dev build : 
- https://spark.lucko.me/uIpMdmQnH0
- https://spark.lucko.me/dujtw5bRrb
- https://spark.lucko.me/I9ClVA7ZEQ
- https://spark.lucko.me/FdM2YaI2GE

Some spark on older build : 
- https://spark.lucko.me/z3SA9TOWgr
- https://spark.lucko.me/al4GsXwGv4
- https://spark.lucko.me/2SsETdKoir
- https://spark.lucko.me/uOYHD4AcKL

Thread and alloc (also on older build)
- https://spark.lucko.me/d3czvmJ96n
- https://spark.lucko.me/9SYQ7m1jCM

**Comment by WarnDa** [comment]
Some other spark with --only-tick-over 50 at 260 players : https://spark.lucko.me/u0xWLFrJZO

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is better
Also upload a new spark profiler if possible :)

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is better Also upload a new spark profiler if possible :)

Here it is : https://spark.lucko.me/K3c1WqMCH7

**Comment by OmerBenGera** [comment]
much better :)
In the following updates I plan to implement more optimizations related to data-structures and hopefully it will help with performance a bit more
