### ISSUE TITLE
Bad Bee count for island limit

### ISSUE THREAD

**Issue by AlmostPanda** [BG-Software-LLC/SuperiorSkyblock2#2101]
### Minecraft's Version

Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 862299b)

### Plugin's Version

2024.1-b216

### Describe the bug

When you do `/papi parse me %superior_island_entity_count_bee%` while a bee is out of hive it counts without any issue, but right when the bee gets back to Beehive or Bee Nest the placeholder resolves 0.

### To Reproduce

1. Spawn Bee
2. Do /papi parse me %superior_island_entity_count_bee%
3. Wait till bee went to Beehive/Bee Nest
4. Execute the placeholder again

**Comment by OmerBenGera** [comment]
I am not sure if that's a bug tbh
When the bees are inside the bee hive, they are technically not there anymore
Also, if I add support for such thing, entities recalculation in unloaded chunks will be pain in the ass.

**Comment by AlmostPanda** [comment]
I understand that, the problem accures when all bees are inside hives so placeholder outputs 0 and because of that you can spawn even more bees, but if its pain to do that just leave it 😄
its not that important

**Comment by OmerBenGera** [comment]
It should not let the other bees get out of the hives, or despawn them.
You should not be able to exceed the bees limit, but if you can - then it's a bug.

**Comment by AlmostPanda** [comment]
Can't get over the limit, but still after updating to latest dev build Im able to let all bees get back to hives and let few of them out so I can breed them and get even more, but yes.
Even though I breed them once they enter hive again I have 0 bees and can breed them again and again.
And yes, if I reach max limit, other bees cant get out of hive, but they will still exist.

**Comment by AlmostPanda** [comment]
Can't get over the limit, but still after updating to latest dev build Im able to let all bees get back to hives and let few of them out so I can breed them and get even more, but yes.
Even though I breed them once they enter hive again I have 0 bees and can breed them again and again.
And yes, if I reach max limit, other bees cant get out of hive, but they will still exist.

**Comment by OmerBenGera** [comment]
They exist in the hive, but cant get out. Thats fine by me.
Closing this as a solution cant really be made as of today.
