### ISSUE TITLE
Challenge Miner stucked 

### ISSUE THREAD

**Issue by Cuchticka** [BG-Software-LLC/SuperiorSkyblock2#2106]
### Minecraft's Version

1.20.6

### Plugin's Version

2024.1

### Describe the bug

After completing the first miner challenge instead of iron level we got the redstone one and after my girlfriend finished it as well we got to level 3 and got the iron one. But now we are both stuck on the miner 2 challenge because the mined cobblestone wont count.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/92445639/87b84829-b79d-4ce5-9613-607f8a80a488)

### To Reproduce

1. Make an island
2. Invite a friend 
3. Do the first miner challenge and get to level 2 generator
4. Let your friend do the first challenge as well and get to level 3 generator
5. Try to get to level 4
6. Good luck ☺

### Additional Information

plugins we use:

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/92445639/993dc4a8-5891-4788-bfcf-f64c12ac0793)

**Comment by OmerBenGera** [comment]
You can configure the mission and upgrades however you want. Not sure what the bug is tbh

**Comment by Cuchticka** [comment]
The issue was that the stone mined wasnt counting even tho we mined more then enough. My friend had to manually complete the challenge then it worked fine.

**Comment by OmerBenGera** [comment]
> The issue was that the stone mined wasnt counting even tho we mined more then enough. My friend had to manually complete the challenge then it worked fine.

By default, only stone generated naturally counts.
You either broke stone that was manually placed by players, or you have a plugin that conflicts with SSB. Another option might be that you dont have all the requirements to complete the mission.

Does it happen to other players on your server?

**Comment by Cuchticka** [comment]
It worked fine on the first quest and works fine now but on the second it was stuck for me and for my friend, list of plugins is in this thread.

**Comment by OmerBenGera** [comment]
As I said before, there are many situations why it won't count progress towards the mission.

I don't think this is a bug.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
