### ISSUE TITLE
Is Missions reset after /is leader command

### ISSUE THREAD

**Issue by Bragos24** [BG-Software-LLC/SuperiorSkyblock2#2107]
### Minecraft's Version

Paper 1.20.1

### Plugin's Version

2024.1-b218

### Describe the bug

Hi, if a player types /is leader and passes ownership of the island to another player, his ongoing missions are reset.
The missions completed at 100% remain so and are not reset but the others he is doing (for example at 30 or 50%) are reset. 
The same thing happens with the /is disband (Already completed missions remain anyway, only the missions in progress are reset), maybe this is intended.

### To Reproduce

1) Start a mission and get to 1-99% completion
2) Type /is leader and passes ownership of the island to another player
3) The previous mission returns to 0%

**Comment by OmerBenGera** [comment]
Please upload the configuration of a mission that resets

**Comment by SpadaccinoNero7** [comment]
[LQx2nYSj.txt](https://github.com/user-attachments/files/15785225/LQx2nYSj.txt)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Bragos24** [comment]
Hi Omer, thank you very much for your speed in resolving the issue.
Now missions in progress no longer reset after the /is leader command, but they still reset after /is disband.
If this is intended, you can close this issue, thanks again

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed as well
