### ISSUE TITLE
Self made island wont create

### ISSUE THREAD

**Issue by zycong2** [BG-Software-LLC/SuperiorSkyblock2#2108]
### Minecraft's Version

mc 1.20.4
paper: git-Paper-496

### Plugin's Version

2024.1

### Describe the bug

so i made a custom island for my server when i tried to create a island with it just nothing happend no error message nothing in chat just absolutly nothing... 
when i tried to make a island with one of the premade islands it worked fine

### To Reproduce

just create a island and try to use /is create

**Comment by Srcsm** [comment]
Did you add the custom island to your `island-creation.yml` as the [wiki guide says](https://wiki.bg-software.com/superiorskyblock/overview/schematics#adding-your-own-schematic)?

**Comment by OmerBenGera** [comment]
Upload the schematic and send a link to it here

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
