### ISSUE TITLE
Level count worth + level

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2109]
### Minecraft's Version

1.20.4 paper fork

### Plugin's Version

b228

### Describe the bug

I upgraded from b218 to b228 and now every island get their worth instead of their level

### To Reproduce

Set a different worth and level
recalc your island
check that your level is now false

**Comment by OmerBenGera** [comment]
I cannot replicate the issue
I place a few blocks, run `/is recalc`, and it seems just fine.

Please take a screenshot or a video of the incorrect levels

**Comment by Bragos24** [comment]
Hi, I have a similar problem with b228.
If I run /is value with any block the value is always 0 (I don't use Worth but only Level)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Bragos24** [comment]
Hi, for me it is fixed, thank you.

**Comment by WarnDa** [comment]
Not working for me
If I set all my block into "levels.yml" to 0.01 but all my blocks into "worth.yml" into 1
the /is level tell me the worth and not the levels.

**Comment by OmerBenGera** [comment]
> Not working for me If I set all my block into "levels.yml" to 0.01 but all my blocks into "worth.yml" into 1 the /is level tell me the worth and not the levels.

Do you have sync-worth enabled?

**Comment by WarnDa** [comment]
> > Not working for me If I set all my block into "levels.yml" to 0.01 but all my blocks into "worth.yml" into 1 the /is level tell me the worth and not the levels.
> 
> Do you have sync-worth enabled?

Nop

**Comment by OmerBenGera** [comment]
> > > Not working for me If I set all my block into "levels.yml" to 0.01 but all my blocks into "worth.yml" into 1 the /is level tell me the worth and not the levels.
> > 
> > 
> > Do you have sync-worth enabled?
> 
> Nop

I can't seem to replicate the issue
I removed all worth values, all level values, and set worth of diamond_block to 1, then its level to 0.01. Then I executed `/is level` while having a diamond block on my island, and it seemed to work just fine

**Comment by WarnDa** [comment]
> > > > Not working for me If I set all my block into "levels.yml" to 0.01 but all my blocks into "worth.yml" into 1 the /is level tell me the worth and not the levels.
> > > 
> > > 
> > > Do you have sync-worth enabled?
> > 
> > 
> > Nop
> 
> I can't seem to replicate the issue I removed all worth values, all level values, and set worth of diamond_block to 1, then its level to 0.01. Then I executed `/is level` while having a diamond block on my island, and it seemed to work just fine

Found why lol
I am usign 0 as level and not 0.01
So as it doesn't detect the : 0 level it uses the worth.

But If I set the level to 0.01 it works fine

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is fixed

Fixed thanks !
