### ISSUE TITLE
Chat spammed when recalc

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2110]
### Minecraft's Version

1.20.4 paper fork

### Plugin's Version

b228

### Describe the bug

When you recalc your island (or on auto recalc at 00:00) it spams every block you try to mine
(the spammed message is "ISLAND_BEING_CALCULATED:")

On big island with a lot of blocks, it send up to 40 messages until the recalc finish

### To Reproduce

Create a big island (so it's longer to recalc)
recalc is while mining
you'll get spammed

**Comment by OmerBenGera** [comment]
You cant break or place blocks when recalc occurs, this is not a bug. Do you get more than one message for each block that you break?

**Comment by WarnDa** [comment]
> You cant break or place blocks when recalc occurs, this is not a bug. Do you get more than one message for each block that you break?

1 message per block you break yes

**Comment by OmerBenGera** [comment]
> > You cant break or place blocks when recalc occurs, this is not a bug. Do you get more than one message for each block that you break?
> 
> 1 message per block you break yes

So yeah, thats intended. Its always been like that.
You cannot break or place blocks while the island is recalculating.

**Comment by OmerBenGera** [comment]
Is this still relevant?

**Comment by WarnDa** [comment]
> > > You cant break or place blocks when recalc occurs, this is not a bug. Do you get more than one message for each block that you break?
> > 
> > 1 message per block you break yes
> 
> So yeah, thats intended. Its always been like that. You cannot break or place blocks while the island is recalculating.

Oh my bad I forgot
But send only 1 message while the island is recalculating instead of spamming

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by WarnDa** [comment]
Perfect thank you :)
