### ISSUE TITLE
CustomTimingsHandler Issue

### ISSUE THREAD

**Issue by Galaxy-VN** [BG-Software-LLC/SuperiorSkyblock2#2111]
### Minecraft's Version

1.20.4 and Leaf software

### Plugin's Version

Dev Build #228

### Describe the bug

Well i want to use the [Leaf](https://github.com/Winds-Studio/Leaf) software with this but its seems like this patch remove the org.spigotmc.CustomTimingsHandler at [here](https://github.com/Winds-Studio/Leaf/blob/ver/1.20.6/patches/api/0005-Remove-Timings.patch) well and its say _Completely remove the Timings, since it wastes too much performance. Use Spark instead._ 

So do you think you can make it work with that patch using Spark, or is there a different way it's possible? Thank you.

### To Reproduce

Install plugin on fork of Paper [Leaf ](https://github.com/Winds-Studio/Leaf/releases)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Galaxy-VN** [comment]
> Check out latest dev build, let me know if it works

Ye i think its work now its bootup haven't testing out yet but tysm~
