### ISSUE TITLE
IslandEnterPortalEvent issue

### ISSUE THREAD

**Issue by AlmostPanda** [BG-Software-LLC/SuperiorSkyblock2#2114]
### Minecraft's Version

Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 862299b)

### Plugin's Version

2024.1-b231

### Describe the bug

When someone enter to Nether through Nether Portal this error appears in console https://pastebin.com/KwCnwzXs
but everything seems to work fine, without any problem.

I think the issue is associated with our IslandMission where we use this event to check if a player gets to the nether to complete a mission (we also use that thing for our end mission)
```
# List of events that will trigger the mission.
events:
  - IslandEnterPortalEvent

# Requirement of the event to complete the mission.
#success-check: 'event.getSchematic().endsWith("_nether")'
success-check: 'event.getPortalType().name() == "NETHER"'
```

### To Reproduce

1. Create a mission with IslandEnterPortalEvent
2. Restart server
3. Went to nether through Nether Portal

**Comment by OmerBenGera** [comment]
`event.getSchematic` may be null, and it occurred when you had this `success-check` enabled.
The other `success-check` will never work as you use `==` for comparing strings - instead, use the `equals` method.

**Comment by AlmostPanda** [comment]
like this?
```
# List of events that will trigger the mission.
events:
  - IslandEnterPortalEvent

# Requirement of the event to complete the mission.
success-check: 'event.getPortalType().name().equals("NETHER")'
```
if so, the error still occures in console when someone tries to go to the nether by portal, want me to send the error?

**Comment by OmerBenGera** [comment]
> like this?
> 
> ```
> # List of events that will trigger the mission.
> events:
>   - IslandEnterPortalEvent
> 
> # Requirement of the event to complete the mission.
> success-check: 'event.getPortalType().name().equals("NETHER")'
> ```
> 
> if so, the error still occures in console when someone tries to go to the nether by portal, want me to send the error?

Sure.
You might have another mission that uses event#getSchematic

**Comment by AlmostPanda** [comment]
https://pastebin.com/6zqmDg9N
We have only these 2 missiosn which use IslandEnterPortalEvent

mission for nether
```
# List of events that will trigger the mission.
events:
  - IslandEnterPortalEvent

# Requirement of the event to complete the mission.
success-check: 'event.getPortalType().name().equals("NETHER")'
```

mission for end
```
# List of events that will trigger the mission.
events:
  - IslandEnterPortalEvent

# Requirement of the event to complete the mission.
success-check: 'event.getPortalType().name().equals("ENDER")'
```

**Comment by OmerBenGera** [comment]
> https://pastebin.com/6zqmDg9N We have only these 2 missiosn which use IslandEnterPortalEvent
> 
> mission for nether
> 
> ```
> # List of events that will trigger the mission.
> events:
>   - IslandEnterPortalEvent
> 
> # Requirement of the event to complete the mission.
> success-check: 'event.getPortalType().name().equals("NETHER")'
> ```
> 
> mission for end
> 
> ```
> # List of events that will trigger the mission.
> events:
>   - IslandEnterPortalEvent
> 
> # Requirement of the event to complete the mission.
> success-check: 'event.getPortalType().name().equals("ENDER")'
> ```

Update to latest dev build, let me know if it still occurs.
I see errors regarding Timings which should have been fixed.

**Comment by AlmostPanda** [comment]
looks fine on test server, no more error in console
will implement it on live server and let you know after restart, which will be in 3h

**Comment by AlmostPanda** [comment]
tested on live server and everything seems to work smooth
thank you, can close the issue
