### ISSUE TITLE
Visitors can take books out of lecterns

### ISSUE THREAD

**Issue by nhanledev** [BG-Software-LLC/SuperiorSkyblock2#2115]
### Minecraft's Version

Paper 1.20.4 build 497

### Plugin's Version

Stable build 2024.1

### Describe the bug

Visitors can open a lectern that has book on it, can read, and can take the book out of the lectern.

### To Reproduce

- Put a lectern
- Put a book with content
- Use a visitor player to right-click and read the book. There is a take book button there.

### Additional Information

This has been an issue in the past #1670 but now it happens again

**Comment by Bragos24** [comment]
Visitors can also take books from the chiseled bookcases

**Comment by OmerBenGera** [comment]
Add LECTER as an interactable block

**Comment by nhanledev** [comment]
Hello, adding both items into interactable item list fixed this issue. Thank you so much
