### ISSUE TITLE
chorus can go outside the border

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2118]
### Minecraft's Version

1.20.4 paper fork

### Plugin's Version

b231

### Describe the bug

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/31826333/f09494f1-015b-4eb1-9445-e5d8521637c3)

### To Reproduce

Plant chorus near the border, wait for it to growth, sometimes it will go behind the border

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
Fixed ! thanks
