### ISSUE TITLE
Bug in economys types in upgrade islands

### ISSUE THREAD

**Issue by AffonsoGames** [BG-Software-LLC/SuperiorSkyblock2#2119]
### Minecraft's Version

1.8.9

### Plugin's Version

SuperiorSkyBlock2 2024.1-b228

### Describe the bug

I'm trying to use an external economy in the plugin in the upgrade center and it doesn't work

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/44729611/bd88c1a9-00e8-4ae1-af3c-ae0f6dbb6859)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/44729611/b2290f85-d74f-43c7-a117-1d8a7a79e147)

i try /papi parse in this variable don't work:
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/44729611/1c4d5136-8ab6-46cd-bd74-331f6c825c3c)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/44729611/2200727a-a7e8-4f49-9570-6bfc660572c0)

### To Reproduce

/modules/upgrade/

upgrades:
  crop-growth:
    '1':
      price: 100.0
      price-type: 'placeholders'
      placeholder: 'yeconomias_yeconomias-cash_amount_raw'
      withdraw-commands:
      - 'cash remove %player% %amount%'
      crop-growth: 20
      commands:
      - 'plot admin setupgrade %player% crop-growth 2'
      - 'plot admin msgall %player% &2&lEVOLUIU &AO Tickspeed do plot foi evoluído para &f40.'
    '2':
      price: 100.0
      price-type: 'placeholders'
      placeholder: 'yeconomias_yeconomias-cash_amount_raw'
      withdraw-commands:
      - 'cash remove %player% %amount%'
      crop-growth: 40
      commands:
      - 'plot admin setupgrade %player% crop-growth 3'
      - 'plot admin msgall %player% &2&lEVOLUIU &AO Tickspeed do plot foi evoluído para &f60.'

**Comment by OmerBenGera** [comment]
I am pretty sure you need to add the prefix and suffix of placeholders (`%`) to the placeholder.

**Comment by AffonsoGames** [comment]
It's incorrect on the wiki, if you could correct it it would be better for everyone and avoid issues of this type, thank you! it worked here using "%"
THX.

**Comment by OmerBenGera** [comment]
> It's incorrect on the wiki, if you could correct it it would be better for everyone and avoid issues of this type, thank you! it worked here using "%" THX.

Awesome, glad it works
Will fix it on the wiki as well :)
