### ISSUE TITLE
 Cannot read field "vanillaChunkHolder"

### ISSUE THREAD

**Issue by Wupin** [BG-Software-LLC/SuperiorSkyblock2#2121]
### Minecraft's Version

This server is running Paper version 1.21-28-master@812701d (2024-06-23T13:13:32Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-4-090775e (MC: 1.21)

### Plugin's Version

2024.1-b240, AcidIslands dev version BG-Software-LLC/SSB-AcidIslands#8

### Describe the bug

Im getting [this](https://pastebin.com/VtGyrD3K) error after creating the island.

### To Reproduce

just create an acid island

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Wupin** [comment]
Fixed!
