### ISSUE TITLE
Still able to disband island when disband-count is set to 0

### ISSUE THREAD

**Issue by VinceSMC** [BG-Software-LLC/SuperiorSkyblock2#2122]
### Minecraft's Version

Paper 1.21

### Plugin's Version

SuperiorSkyblock2-2024.1-b240

### Describe the bug

When disband-count is set to 0, players can still disband their island, despite the comment that it should be disabled at this number.

### To Reproduce

Set disband-count: to 0 and disband island.

**Comment by OmerBenGera** [comment]
You probably changed the `disband-count` in the config file to 0 after you had players already joined the server.
The `disband-count` value is only applied to new players, not existing ones. For changing disbands to existing players, you can use the `/is admin setdisbands` command.

**Comment by VinceSMC** [comment]
> You probably changed the `disband-count` in the config file to 0 after you had players already joined the server. The `disband-count` value is only applied to new players, not existing ones. For changing disbands to existing players, you can use the `/is admin setdisbands` command.

I tested the issue with both new players and existing players on the server, but it still doesn't seem to work. Additionally, with the latest version, setting the `disband-count` to 5 allows me to disband my island, but nothing actually happens—it only says that my island has been removed, but it hasn't. I tried resetting the entire database and removing the skyblock world to start with a clean database and world, but the issue persists.

Even when setting the `disband-count` to 0 and starting with a clean database, the problem remains. I don't receive any denial message when trying to disband my island. When I click confirm, it states that my island has been removed, but it hasn't.

**Comment by OmerBenGera** [comment]
Look for errors in console

**Comment by VinceSMC** [comment]
There are no errors whatsoever.

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue, everything works fine for me
I am limited to the amount of disband counts, and when I reach 0 - I cannot disband anymore.
Also, when I disband my island, it gets deleted from the DB and I get teleported to spawn as I should.

Make sure you use latest dev build.

**Comment by VinceSMC** [comment]
Apologies, I just discovered that one of our plugins was interfering with the disband event, causing the issue. Everything works fine now.

P.S. Could you please look at this request? #2126 I would really appreciate it if it could be added.
