### ISSUE TITLE
Berries issues

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2125]
### Minecraft's Version

1.20.4 paper

### Plugin's Version

b243

### Describe the bug

You can farm glow berries and sweet berries without any permissions on other islands

### To Reproduce

/

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue
Make sure you have `SWEET_BERRY_BUSH` in the interactables file list.

**Comment by OmerBenGera** [comment]
I found out `CAVE_VINES_PLANT` was missing from the default interactables list, so I added it as well in latest dev build
Make sure you add it manually as well

**Comment by WarnDa** [comment]
Okay yes players reported me badly and it was only for glow berries, but it's fixed now, thanks :)
