### ISSUE TITLE
OneBlock addon problem

### ISSUE THREAD

**Issue by ZappySK** [BG-Software-LLC/SuperiorSkyblock2#213]
I updated to the latest dev build of SSB, and I get lot of errors from SSBOneBlockAddon, and after server restarts, all player data was resetted (I mean OneBlock progress data)

**Comment by ZappySK** [comment]
https://pastebin.com/iuMYDVTa
https://pastebin.com/uSxwCxah

**Comment by ZappySK** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
This is not related to the plugin, you are more than welcome to open an issue on the github of the addon.
Also, addons are not updated unless someone wants to work on them

**Comment by ZappySK** [comment]
This happen, when I updated to latest dev build of SSB..

**Comment by OmerBenGera** [comment]
The error is fixed in latest dev build
