### ISSUE TITLE
Unload Chunk Event Error

### ISSUE THREAD

**Issue by Nat392** [BG-Software-LLC/SuperiorSkyblock2#2133]
### Minecraft's Version

CraftBukkit version 4226-Spigot-146439e-2889b3a
MC version : 1.21

### Plugin's Version

Version 2024.1-b253
Dev Build : yes

### Describe the bug

Hello,

While trying your plugin, we were confronted with a spam error. I searched here if it had already been reported, and I saw that you would have fixed it in a dev build, but I have the error.
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/54687432/16a91d14-c300-4b83-8056-7c16080b135c)

### To Reproduce

Just walking around his island

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
This is a bug in Spigot technically.
I access the chunk in the ChunkUnloadEvent, however it says it is already been unloaded.

You should either contact them for help, or just switch to Paper.

**Comment by OmerBenGera** [comment]
> > This is a bug in Spigot technically. I access the chunk in the ChunkUnloadEvent, however it says it is already been unloaded.
> > You should either update your Spigot, contact them for help, or just switch to Paper.
> 
> I've asked around, and people on Spigot tell me that the error comes from your plugin, not spigot... I don't know if it matters, but I use Geyser too.

It happens because I access the chunk in the ChunkUnloadEvent, which should be totally fine, however it faults on Spigot. Use Paper instead.
