### ISSUE TITLE
Void to /is home fall damage

### ISSUE THREAD

**Issue by syremc** [BG-Software-LLC/SuperiorSkyblock2#2135]
### Minecraft's Version

git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

### Plugin's Version

Version 2024.1-b240

### Describe the bug

When a player is on their island and accidentally falls onto the void… before reaching the bottom of the void a players first instinct is to type /is home so either 1. They don’t have to fall all the way to the bottom of the void before teleporting to their island again, or 2. They think they will die to the void so they quickly teleport to the island to prevent their death. 
When they type /is home before reaching the bottom of the void, the player takes fall damage and dies when they teleport back to their island with the command. 

### To Reproduce

I would still like fall damage to take effect in the island world but not in this situation. But if it’s not possible, the chance to disable fall damage in the world would be another fix for the issue. 

### Additional Information

No additional information is really required unless you need video proof of this happening

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by syremc** [comment]
Yes it has been fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by syremc** [comment]
Thank you!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
