### ISSUE TITLE
Non Members able to spawn armor stands/mobs

### ISSUE THREAD

**Issue by iCodeYT** [BG-Software-LLC/SuperiorSkyblock2#2136]
### Minecraft's Version

This server is running Paper version git-Paper-"f4c7d37" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: f4c7d37)

### Plugin's Version

SuperiorSkyblock2-2024.1-b260.jar

### Describe the bug

Non Island Members are able to spawn Armor Stands and Mobs with mob eggs.

### To Reproduce

Visit an island that you're not part of and place armor stands/ spawn mobs with mob eggs

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by iCodeYT** [comment]
Just tested, seems to be working.
