### ISSUE TITLE
No nether access

### ISSUE THREAD

**Issue by JustSimplyGaming** [BG-Software-LLC/SuperiorSkyblock2#2137]
### Minecraft's Version

1.21

### Plugin's Version

devbuild SuperiorSkyblock2-2024.1-b260

### Describe the bug

Entering the nether is not Possible. Not the normal nether, and not the island Nether.
When i activate the nether via Unlock it just keep saying:
The Nether world is not unlocked yet!

I just want to use the normal Nether when not on an Island.

### To Reproduce

I cant say how, its just installed without any config, just trying to activate the nether.

### Additional Information

![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/101293611/cedfdc9e-adc9-43e1-9a81-dc951771147b)
![image](https://github.com/BG-Software-LLC/SuperiorSkyblock2/assets/101293611/79e825ba-a816-48e3-8f29-7beb87d3489a)

**Comment by OmerBenGera** [comment]
You should use `/is admin unlockworld` in order to unlock the nether world for an island.
If you want it to be unlocked by default, set `unlock: true` in the config file.

**Comment by JustSimplyGaming** [comment]
Its not solved, its still not possible to use the normal nether from the overworld!
