### ISSUE TITLE
Stacked blocks are not counted after /is recalc

### ISSUE THREAD

**Issue by Bragos24** [BG-Software-LLC/SuperiorSkyblock2#2139]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

2024.1-b260

### Describe the bug

Hi, if you place stacked blocks using /is toggle blocks and then you run /is recalc, the counter of the block on /is blocks return to 1.
Even if you don't run the /is recalc command, it still happens sometimes.
I dont'use Worth but only Level on my server.
Thank you in advance.

PS: with 2024.1 stable build it works fine.

### To Reproduce

1) Run /is toggle blocks and place and stack for example 128 Diamond Blocks.
2) If you run /is blocks, counter and level are ok (128)
3) Do /is recalc
4) If you run /is blocks, the Diamond Block counter and level are 1.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Bragos24** [comment]
Hi, thank you very much. It is fixed.
