### ISSUE TITLE
SSB SlimeWorldManager - Errors

### ISSUE THREAD

**Issue by DarkOakHD** [BG-Software-LLC/SuperiorSkyblock2#214]
**Minecraft's Version**
PaperSpigot 1.8.8

**Plugin's Version**:
SSB 1.6.0

**Describe the bug**
After doing /is disband and confirming it, i get errors.
https://pastebin.com/MLGSxUz6

**Comment by OmerBenGera** [comment]
issues with addons should be opened under the addons githubs, as this has nothign to do with the plugin itself.

**Comment by DarkOakHD** [comment]
How is "Could not pass event ChunkUnloadEvent to SuperiorSkyblock2 v1.6.0" not related to SSB ?
