### ISSUE TITLE
No normal nether access

### ISSUE THREAD

**Issue by JustSimplyGaming** [BG-Software-LLC/SuperiorSkyblock2#2140]
### Minecraft's Version

1.21

### Plugin's Version

devbuild SuperiorSkyblock2-2024.1-b260

### Describe the bug

Entering the nether is not Possible. i mean the normal nether not the one of the Plugin.
It just keep saying:
The Nether world is not unlocked yet!

I just want to use the normal Nether when not on an Island.

And please dont just close the Issue instant like the last one without reading the whole thing!

### To Reproduce

Install it and try

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue
I made a nether portal in the overworld (not the island world), then entered it - I got teleported to the normal nether world.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
