### ISSUE TITLE
After updating to the latest development version, the hell on the island cannot be entered and it prompts that the hell has not been unlocked!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2142]
### Minecraft's Version

> version
[00:29:17 INFO]: Checking version, please wait...
[00:29:18 INFO]: Current Purpur Version: 1.21-2258-ff19bcc (MC: 1.21)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2256-de2e7a7 (MC: 1.21)

### Plugin's Version

> version SuperiorSkyblock2
[00:29:14 INFO]: SuperiorSkyblock2 version 2024.1-b260
[00:29:14 INFO]: Feature packed Skyblock core.
[00:29:14 INFO]: Website: https://bg-software.com/
[00:29:14 INFO]: Author: Ome_R

### Describe the bug

After updating to the latest development version, the hell on the island cannot be entered and it prompts that the hell has not been unlocked!And the configuration has been set to unlock Hell and the End by default!

### To Reproduce

Update to the latest development version!

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by wlm1455925277** [comment]
The issue has been fixed!
