### ISSUE TITLE
If a player is in Sky Island Hell and then mines all the blocks, the player will not be able to teleport to Hell again!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2143]
### Minecraft's Version

> version
[08:54:25 INFO]: Checking version, please wait...
[08:54:26 INFO]: Current Purpur Version: 1.21-2258-ff19bcc (MC: 1.21)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2256-de2e7a7 (MC: 1.21)

### Plugin's Version

> version SuperiorSkyblock2
[08:54:22 INFO]: SuperiorSkyblock2 version 2024.1-b260
[08:54:22 INFO]: Feature packed Skyblock core.
[08:54:22 INFO]: Website: https://bg-software.com/
[08:54:22 INFO]: Author: Ome_R

### Describe the bug

If a player is in Sky Island Hell and then mines all the blocks, the player will not be able to teleport to Hell again!

### To Reproduce

Hollow out your own island hell

### Additional Information

I know I've posted this before but this is definitely a must! I don't think this is the best solution. You should provide a config that allows the player to enter the island and check for empty blocks in the spawn config! I think spawning a block of stone is the best option! Instead of asking us to place bedrock in the schematic because your default schematic doesn't have bedrock!

**Comment by OmerBenGera** [comment]
That can be easily abused by players.
Place a bedrock in your schematic or something.
