### ISSUE TITLE
Server automatically shuts down when turned on (The error disappears after removing the plugin)

### ISSUE THREAD

**Issue by UhcWolfe** [BG-Software-LLC/SuperiorSkyblock2#2144]
### Minecraft's Version

1.20.4

### Plugin's Version

SuperiorSkyblock2-2024.1-b260

### Describe the bug

I start the server and after it finishes loading it turns off itself (the problem disappears after deleting the SuperiorSkyBlock2 file)

![image](https://github.com/user-attachments/assets/e7d0204e-56cb-4d64-b75b-14073b7aa4ff)

### To Reproduce

![image](https://github.com/user-attachments/assets/e7d0204e-56cb-4d64-b75b-14073b7aa4ff)

### Additional Information

![image](https://github.com/user-attachments/assets/e7d0204e-56cb-4d64-b75b-14073b7aa4ff)

**Comment by OmerBenGera** [comment]
Look for warnings in console

If the plugin shuts down the server, it means you didnt set it up properly and it couldnt let the server start up
