### ISSUE TITLE
item loose when reaching entity limit

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#2147]
### Minecraft's Version

1.20.4 paper

### Plugin's Version

b265

### Describe the bug

When you reproduce an entity but have reached the entity limit, it consumes your food but does not spawn the entities, so you lose your food.
When you get a wildstacker and spawn a huge stack, you can lose 2000 foods, that's a lot.
Maybe you could detect the event cancellation and return the food ?

### To Reproduce

- Get the maximal entity limit (of cow for example)
- Give them wheat to reproduce
- It will take the wheat, and do not spawn baby as you reached the limit
- Your wheat is gone

### Additional Information

I completely understand that's is a very small issue and maybe hard/useless to fix.

But player reported me this issue so I also report it.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it is fixed

Yes and no, it gave me items but 64 wheat instead of the good amount : 
https://youtu.be/zbfw2rDFs8c

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by WarnDa** [comment]
> Check out latest dev build, let me know if it works

Working great thanks :)
