### ISSUE TITLE
Stacked blocks disappear after server restart

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/SuperiorSkyblock2#2148]
### Minecraft's Version

1.20.4 Purpur 2176

### Plugin's Version

B266

### Describe the bug

After server restart all stacked blocks on islands disapear. 

### To Reproduce

Restart server
It happened only 1 time (I updated plugin 2 days ago)

**Comment by OmerBenGera** [comment]
Are there any errors in console when you place stacked blocks, or when the plugin is loading?
Also, is the stacked block in the DB?

**Comment by Envqu** [comment]
No there is no errors in console. It happened one time after server restart.
I using local database included in plugin

**Comment by OmerBenGera** [comment]
Check if the stacked blocks are inside the database
Also, please provide me with your session logs that the stacked blocks didn't load properly
