### ISSUE TITLE
The console spams me Could not pass eventBlockFromToEvent to SuperiorSkyBlock2 v2024.1-b266

### ISSUE THREAD

**Issue by Atrosik** [BG-Software-LLC/SuperiorSkyblock2#2150]
### Minecraft's Version

1.21 SuperiorSkyblock2-2024.1-b266 (1)

### Plugin's Version

SuperiorSkyblock2-2024.1-b266 

### Describe the bug

The console spams me Could not pass eventBlockFromToEvent to SuperiorSkyBlock2 v2024.1-b266 I even have a memory leak on the server and I know it's superiorskyblock. Can you help me?

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Regarding the error, upload the entire stack trace to pastebin and send a link here.
Regarding the memory leak, open a new issue. Make sure you also upload a heap dump so I can investigate it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
