### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by jaydenmcil** [BG-Software-LLC/SuperiorSkyblock2#2151]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15679 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 66139b6 on develop)
Unknown version
Previous version: git-Paper-497 (MC: 1.20.4)

### Plugin's Version

2024.1 (latest)

### Describe the bug

Hello, I'm using this plugin with the SlimeWorlds addon and everything and its all working properly except for the fact chunks dont load on people's worlds at all, there's always missing chunks when creating an island and you can jump through them it's not just a visual issue.

Also I have a question while I'm here, If I have a small playerbase is it practical to use multiple worlds on my server? It's a decently good server plan. If it's not practical and I should be using multiple servers  for per-player worlds then to avoid this can I put large schematics in one world? I'm trying to find a not so expensive solution.

### To Reproduce

Create an island and teleport to it

### Additional Information

![image](https://github.com/user-attachments/assets/5002adca-42d6-466e-bfbd-8b8d5124f458)

There was this in the console too, though it might not be related. Not too sure:

[05:40:34 ERROR]: [ChunkFullTask] Expected poi chunk to be loaded with chunk for task ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkFullTask, for world: island_792f93e2-c9d7-4624-a7a6-56c0e8445bcc_normal, chunk: (0,0), hashcode: 964928123, priority: COMPLETING, status: minecraft:full, scheduled: true}

**Comment by OmerBenGera** [comment]
You should report it to ASP, this is not related to the module
Because you have a small playerbase, I don't recommend using the module, just use a regular world - no need to multiple servers setup or multiple worlds setup.
