### ISSUE TITLE
Plains biome around the island

### ISSUE THREAD

**Issue by Wupin** [BG-Software-LLC/SuperiorSkyblock2#2152]
### Minecraft's Version

This server is running Paper version 1.21-97-master@e71c1df (2024-07-19T11:57:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-81-ceeb8c1 (MC: 1.21)

### Plugin's Version

2024.1-b243

### Describe the bug

After generating the island there is a ring of PLAINS biome even though I set worlds.normal.biome to WARM_OCEAN. it only happens after generating the island, nowhere else are these biomes in this world. I'm using this [world-generator](https://github.com/Wupin/IslandGenerator), but it should have no effect on this.
![image](https://github.com/user-attachments/assets/123e5295-2840-4b6a-b711-4ce639b0f5bc)

### To Reproduce

Generate island while having installed this [World Generator](https://github.com/Wupin/IslandGenerator) and worlds.normal.biome: WARM_OCEAN

**Comment by OmerBenGera** [comment]
Set your schematic's biome to warm_ocean as well

**Comment by Wupin** [comment]
It's not helping. The bug still occurs...

**Comment by leon37921** [comment]
could be this problem
#1978

**Comment by OmerBenGera** [comment]
Does it still happens if you use `/is biome` to change the biome?

**Comment by Wupin** [comment]
No it does NOT.

**Comment by OmerBenGera** [comment]
It might be related to #1978 
I see you're a developer - try making a small plugin that justs prints the biome you stand in, and use it while standing in these chunks

**Comment by Wupin** [comment]
https://www.youtube.com/watch?v=ByKwTlMN04E

**Comment by OmerBenGera** [comment]
> https://www.youtube.com/watch?v=ByKwTlMN04E
> 
> if you think it's client-side, it's not.

I will look into it, thanks

**Comment by OmerBenGera** [comment]
Use latest dev build, then try replicating the issue
Check if you see warning in console. An example for such warning:
```
Setting biome WARM_OCEAN to non-existing chunk:
```

**Comment by Wupin** [comment]
yes, it spammed the console with [SuperiorSkyblock2] Setting biome WARM_OCEAN to non-existing chunk: ...........

**Comment by OmerBenGera** [comment]
> yes, it spammed the console with [SuperiorSkyblock2] Setting biome WARM_OCEAN to non-existing chunk: ...........

And these were the chunks that are not plains, right?

**Comment by Wupin** [comment]
not sure, it printed like 670x times

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Wupin** [comment]
I generated 10 islands and in 1 scenario no plains were generated. And noticed that if I pregenerate the chunks, no "Setting biome WARM_OCEAN to non-existing chunk" is printed but still theres plains biomes

**Comment by Wupin** [comment]
and in the pre-generated areas, if I create a island it will bugs and generate such weird corners also with PLAINS biomes

![image](https://github.com/user-attachments/assets/d8308cfd-8ff1-4140-93be-489f9f85e63e)

**Comment by OmerBenGera** [comment]
I don't know regarding the world-generation errors,
but try latest dev build for the biomes.

**Comment by OmerBenGera** [comment]
> yes biomes are fixed!

Awesome!
I am closing this issue for now, if the issue with the generator still occurs, let me know by opening a new bug report.
