### ISSUE TITLE
Loading Entity NBT task warn

### ISSUE THREAD

**Issue by AlmostPanda** [BG-Software-LLC/SuperiorSkyblock2#2154]
### Minecraft's Version

Paper version git-Paper-485 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 862299b)

### Plugin's Version

2024.1-b267

### Describe the bug

Since update from dev build 239 to latest 267 this warn appears everytime server starts, dont know if its important or not

here is a link https://pastebin.com/6cLARL3b

### To Reproduce

1. Use build 239
2. Update to build 267

probably

**Comment by AlmostPanda** [comment]
after updating to latest build 269 warn doesnt show up, probably fixed?
don't know what the warning was supposed to refer to

**Comment by OmerBenGera** [comment]
> after updating to latest build 269 warn doesnt show up, probably fixed? don't know what the warning was supposed to refer to

Yes, forgot to update you here - my bad.
Closing this as it seems to be fixed :)
