### ISSUE TITLE
FarmingMissions bug?

### ISSUE THREAD

**Issue by AlmostPanda** [BG-Software-LLC/SuperiorSkyblock2#2155]
### Minecraft's Version

Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

### Plugin's Version

2024.1-b269

### Describe the bug

Don't know if that count as bug, but since build 239 Farming missions doesnt seem to work properly

If you plant a crop like pumpkin, cactus or sugar cane and leave it grow for quest it works fine, but right after server restarts and I join a server those crops doesnt seem to count for mission, dont know why.

However, I've tried same thing with same build (latest) on test server and everything seems to work without any problem.

Any idea what could cause this??
There are no error

### To Reproduce

1. Plant a crop (pumpkin, cactus, sugar cane)
2. After it grow up check mission if it counts
3. Restart server
4. Let the same crop grow again and check mission if it counts

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself
Are you able to replicate it on a server with only SSB installed, default config files?

**Comment by AlmostPanda** [comment]
Can't replicate it on default, but I don't know why. Any idea what could have cause it?

**Comment by OmerBenGera** [comment]
> Can't replicate it on default, but I don't know why. Any idea what could have cause it?

Not really.
Try using your config files, check if it still occurs.
If it does, we know it's something related to your config files and not another plugin. then, try adding files one by one until it occurs again.
If it does not, it means that another plugin is conflicting. then, try adding plugins one by one until you find the conflicting plugin

**Comment by AlmostPanda** [comment]
Alright, I'll try, thanks for an advice.

**Comment by AlmostPanda** [comment]
Im hopeless, can you take a look at the mission please? If I upload this mission and let already existing pumpkin stem generate new pumpkin it doesnt count.

I've tried to change the `required-plant` from PUMPKIN to different plant it counts

I've tried the default farmer_2 where is PUMPKIN and it counts, I've add my PumpkinFarmer mission to farmer category and it doesnt count. What's wrong with it?

Even if I have farmer_2 and PumpkinFarmer mission in same category both uncompleted and then generate new pumpkin from already existing pumpkin stem it only counts for the farmer_2 and not from PumpkinFarmer.
Then I had an idea to complete farmer_2, because what if it counts only for the first one and not the second, but even after completing farmer_2 the PumpkinFarmer won't count pumpkins.

Hope you'll have better luck them me and find what's the issue.

[PumpkinFarmer.zip](https://github.com/user-attachments/files/16475165/PumpkinFarmer.zip)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by AlmostPanda** [comment]
OMG its working, I'm crying. Thank you so much for that fix.
I'll take it as a gift to my birthday.
