### ISSUE TITLE
block values not updating properly and mooshroom spawner not being read by confog

### ISSUE THREAD

**Issue by TomcatHD** [BG-Software-LLC/SuperiorSkyblock2#2156]
### Minecraft's Version

1.20.1

### Plugin's Version

2024.1 (latest stable build)

### Describe the bug

1. bugg: mooshroom spawners not being read by the config, island worth value isnt changing

2. bugg: spawners in general not being updated when using an egg on a spawner (plugin doesnt update worth values)
plugin only removes worth values when spawner  is being destroyed

### To Reproduce

1. place normal spawner on ground
2. use egg to change spawner type (value not being added)
3. destroy spawner (value only being removed )

**Comment by OmerBenGera** [comment]
About the mooshroom spawners - make sure you use the correct block key.
Use `/is value` while holding a mooshrom spawner, it will show you the exact name you should use.

Regarding the second bug, confirmed and will be fixed.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by TomcatHD** [comment]
> Check out latest dev build, let me know if it is fixed

latest dev build isnt working on 1.20.1

**Comment by TomcatHD** [comment]
> About the mooshroom spawners - make sure you use the correct block key. Use `/is value` while holding a mooshrom spawner, it will show you the exact name you should use.
> 
> Regarding the second bug, confirmed and will be fixed.

it detects it as a normal pig spawner.

**Comment by OmerBenGera** [comment]
> > About the mooshroom spawners - make sure you use the correct block key. Use `/is value` while holding a mooshrom spawner, it will show you the exact name you should use.
> > Regarding the second bug, confirmed and will be fixed.
> 
> it detects it as a normal pig spawner.

What plugin are you using for handling spawners?

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it is fixed
> 
> latest dev build isnt working on 1.20.1

Right, you should update to 1.20.4

**Comment by TomcatHD** [comment]
> Member

economyshopgui

**Comment by TomcatHD** [comment]
i wish i could just update to 1.20.4

**Comment by OmerBenGera** [comment]
I am sadly cannot help you if you're not using latest dev build.
Even if I patch it, you'll have to update the plugin.
The plugin is open source, you can add support to 1.20.1 and then update it.
