### ISSUE TITLE
MergedSpawner count issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#216]
Hello, i use SuperiorSkyblock2-b115.jar in 1.12.2 with mergedspawner, when i place 3 stacked spawners i have 3 spawner in my /is count, but when i do /is recalc, i have 4 spawners : maybe the placed spawner. So can you check that to fix this issue ? Thx

**Comment by nivcoo** [comment]
I use MergedSpawner-13.7.1

**Comment by OmerBenGera** [comment]
Weird, I can't seem to replicate the issue

**Comment by nivcoo** [comment]
I will do video

**Comment by nivcoo** [comment]
https://pics.revolis.fr/2021-04/15/12-22_mQwT.mp4 look

**Comment by OmerBenGera** [comment]
ok, so the issue is with the global mob spawner, not with the pig spawner itself - gotcha.
gonna check that again

**Comment by nivcoo** [comment]
Yes I misspoke, with the "count *" it has pigspawner x3 and mob spawner x4

**Comment by nivcoo** [comment]
Did you manage to reproduce the issue ?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by nivcoo** [comment]
It works fine, thx :p
