### ISSUE TITLE
World normal is not unlocked?

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/SuperiorSkyblock2#2160]
### Minecraft's Version

1.20.4 Purpur 2176

### Plugin's Version

b262

### Describe the bug

Island worlds are blocked but in config they not.
I enabled nether and the_end world via command but I cant enable normal world.
Player cant go back thru portal from nether.
![image](https://github.com/user-attachments/assets/a74766ac-76c6-441b-b707-ac5de61f6394)
![image](https://github.com/user-attachments/assets/7dc5831f-3a93-492a-9c6d-ef642fba2031)
I also tried command /is admin unlockworld * oneblock true

### To Reproduce

Downgrade plugin 4 versions from 266.
I have to because latest version and 266 not work properly!

**Comment by OmerBenGera** [comment]
Does this happen in latest dev build?

**Comment by Envqu** [comment]
It doesnt, thanks for fix
