### ISSUE TITLE
Unable to enter the nether, errors on console. 

### ISSUE THREAD

**Issue by martyr420** [BG-Software-LLC/SuperiorSkyblock2#2162]
### Minecraft's Version

1.21 Purpur 2271

### Plugin's Version

b271

### Describe the bug

not able to enter the nether, console is spammed with this error when i go through a portal

nether is enabled in the config and schematics for it are present - i've also tried to use the island admin command to unlock the nether no luck with that either

[message.txt](https://github.com/user-attachments/files/16325641/message.txt)

### To Reproduce

Go through an end portal.

**Comment by martyr420** [comment]
bump.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue still occurs, let me know
