### ISSUE TITLE
Error during island creation and server crash while trying to go to the island

### ISSUE THREAD

**Issue by RigerCrows** [BG-Software-LLC/SuperiorSkyblock2#2163]
### Minecraft's Version

AdvancedSlimePaper - 1.20.6

### Plugin's Version

Dev Builds
#271 

### Describe the bug

I create an island with /island create, but it looks like the island is being formed but it is not.
If I try to go to the island with the /island go command, the server crashes and shuts down.

**İsland Create / Crash Server:**
https://pastebin.com/yCTPCsPL

**2. Error:**
https://pastebin.com/Yh7LXWc9

### To Reproduce

**As a result of my research, I think the following is what needs to be done.**

**1. Error:**
**FIX:** isDimensionEnabled returns empty, definition needs to be made.

**2. Error:**
**FIX:** getIslandsWorldDimension returns empty, definition needs to be made.

### Additional Information

No response

**Comment by OmerBenGera** [comment]
Check out https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/issues/55
