### ISSUE TITLE
Can't keep up!Is the server overloaded?

### ISSUE THREAD

**Issue by banwang123** [BG-Software-LLC/SuperiorSkyblock2#2164]
### Minecraft's Version

Paper - 1.20.1

### Plugin's Version

2023.2

### Describe the bug

When I running this plugins on the server
The console will print out "Can't keep up!Is the server overloaded?"
I checked the timings report and guess may be this plugin caused it.

### To Reproduce

Put this plugins in the folder "Plugins" and running it(when many players online)

### Additional Information

Timings report: https://timings.aikar.co/dev/?id=50d27e5ea75b49ab8f86cd89962cd8fc

**Comment by OmerBenGera** [comment]
I am closing this for now
If you still think it is related to the plugin, take a spark profiler and send a link to it here
