### ISSUE TITLE
break slab take lvl from the placeholder

### ISSUE THREAD

**Issue by Vasco-Brito** [BG-Software-LLC/SuperiorSkyblock2#2165]
### Minecraft's Version

1.20.4 (paper-1.20.4-497)

### Plugin's Version

SuperiorSkyblock2-2024.1

### Describe the bug

Hello, i dont know im dumb or anything like that but i had a trouble using the SuperiorSkyblock when i have xp on slab, for example 1 of xp on it, and then the user add 2 of them to make a double the value that appears on the PAPI (PlaceholderAPI) decrease in the value of xp, like if player instead of add removes it, and when he break the double slab he loses xp for 2 slabs

### To Reproduce

Add xp to a slab, use a plugin to be able to see the placeholder, place a slab down, look at the xp of island, place another on top, recheck, the value will decrease, then brake the "double slab", and the value of island will decrease by 2*(slab level).
The /is recalc fix this but is anoying

### Additional Information

I created a ticket on discord (Tazinho) and there i post the video cause i couldn't set it here.

_No response_

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Vasco-Brito** [comment]
Hello i've tested, and it seems to be working.
Thank you! :)
