### ISSUE TITLE
SkyBlock Placeholder Update Issue Report

### ISSUE THREAD

**Issue by leonm-cloud** [BG-Software-LLC/SuperiorSkyblock2#2168]
### Minecraft's Version

1.20.4

### Plugin's Version

SuperiorSkyblock2-2024.1-b271.jar

### Describe the bug

After departing from or dissolving an island, the `%superior_island_location_exists%` placeholder does not update to 'No' as expected. This failure causes the placeholder to remain unchanged, failing to refresh properly. Following a server restart, the placeholder correctly resets to 'No', indicating the absence of a superior island location. However, the issue arises specifically when leaving or dissolving an island, where the placeholder fails to reflect the updated state.

### To Reproduce

When leaving, disbanding, or removing a member from an island, the placeholder value fails to update to 'No' and remains stuck on the previous role.

**Comment by OmerBenGera** [comment]
If you run `/papi parse me %superior_island_location_exists%`, is it updated?
I suspect its your scoreboard or something caching the value

**Comment by leonm-cloud** [comment]
I've attached a video to better show you what's happening.

http://i.lushmc.fun/u/NPCgzb.mp4

**Comment by leonm-cloud** [comment]
Update, it just says "Yes" for people who don't even have an island.

**Comment by OmerBenGera** [comment]
> Update, it just says "Yes" for people who don't even have an island.

The placeholder returns "Yes" if players are standing inside an island, not if they are part of one.
The spawn island is also considered an island, so when you're standing in the island, it will return "Yes"
