### ISSUE TITLE
Item glow and flags don't work on paper 1.20.6

### ISSUE THREAD

**Issue by Lavahh** [BG-Software-LLC/SuperiorSkyblock2#2169]
### Minecraft's Version

Minecraft version vanilla 1.20.6
Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS) Host: Windows 11 10.0 (amd64)

### Plugin's Version

2024.1

### Describe the bug

1. It is impossible to hide the description and characteristics of items (for example, a sword) using [flags](https://wiki.bg-software.com/superiorskyblock/overview/menus#editing-items-in-the-menu:~:text=in%20its%20lore.-,flags,-A%20list%20of) in the menu. 

2. When using the glow of an item, the menu does not open.

### To Reproduce

1. Install server
2. Install SuperiosSkyblock2 v2024.1
3. Install LuckPerms v5.4.134
4. Get * perms

Bug 1:
I try flags like in this menu ([pastebin](https://pastebin.com/vLf5VtD6)). The sword keeps the description.

Bug 2:
1. Use /is top
2. Get error ([pastebin](https://pastebin.com/MkFeDrCX))

### Additional Information

Also, when starting, a warning appears "deprecated behavior" ([pastebin](https://pastebin.com/HRd7VQe3))

**Comment by OmerBenGera** [comment]
Update to latest dev build, this should been fixed already in them

**Comment by Lavahh** [comment]
> Update to latest dev build, this should been fixed already in them

The errors have disappeared, but the swords still display their stats. The glow is also not displayed, although there are no errors.

New errors also appeared. [This error](https://pastebin.com/vpF2Tqf6) is shown when you break (BlockPlaceEvent when you place a block) a block.
Here is [another error](https://pastebin.com/Up2C5AfY) when using the command '/is admin reload'

**Comment by OmerBenGera** [comment]
> > Update to latest dev build, this should been fixed already in them
> 
> The errors have disappeared, but the swords still display their stats. The glow is also not displayed, although there are no errors.
> 
> New errors also appeared. [This error](https://pastebin.com/vpF2Tqf6) is shown when you break a block (BlockPlaceEvent when you place a block). Here is [another error](https://pastebin.com/Up2C5AfY) when using the command '/is admin reload'
> 
> I tried builds 271 and 276.

Make sure you restart the server.
It seems the mission files are no longer loaded into the server or something

**Comment by Lavahh** [comment]
> Make sure you restart the server. It seems the mission files are no longer loaded into the server or something

I always restart the server using '/stop'.

When starting the server there are no errors with missions, errors appear only when reloading the plugin using the command '/is admin reload'.

What should I do with the glow of objects? Maybe I'm using the wrong syntax?

**Comment by OmerBenGera** [comment]
Open a new issue regarding the `/is admin reload` issue. Not related to this issue at all
Glow enchantment is not supported in 1.20.6 due to Minecraft's limitations.
It is supported in 1.20.4 or 1.21.
