### ISSUE TITLE
Cannot create is

### ISSUE THREAD

**Issue by vSKAH** [BG-Software-LLC/SuperiorSkyblock2#217]
**Minecraft's Version**
This server is running Purpur version git-Purpur-1056 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 2 version(s) behind
Previous version: git-Tuinity-"a0aa5ab" (MC: 1.16.5)

**Plugin's Version**: -
1.6.0-DEVb121

**Describe the bug**
![image](https://user-images.githubusercontent.com/68877411/114886614-fb1eee00-9e07-11eb-912f-e69bed54ae25.png)

**To Reproduce**
/is create SKAH normal

**Additional information**
Basic config file / not edited.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
