### ISSUE TITLE
missions

### ISSUE THREAD

**Issue by MillsUnited** [BG-Software-LLC/SuperiorSkyblock2#2170]
### Minecraft's Version

1.21

### Plugin's Version

SuperiorSkyblock2-2024.1-b271

### Describe the bug

missions is bugged and sends really big errors

### To Reproduce

break blocks that count towards missions

**Comment by OmerBenGera** [comment]
Upload the error you receive to pastebin and send a link to it here

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response
If the issue still occurs, let me know
