### ISSUE TITLE
Regarding the problems that occurred in the End World and Hell World after updating the plug-in version!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2172]
### Minecraft's Version

[23:26:15 INFO]: Checking version, please wait...
[23:26:19 INFO]: Current Purpur Version: 1.21-2273-61b63b1 (MC: 1.21)*
* You are 2 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21-2271-032697e (MC: 1.21)

### Plugin's Version

[23:26:42 INFO]: SuperiorSkyblock2 version 2024.1-b271
[23:26:42 INFO]: Feature packed Skyblock core.
[23:26:42 INFO]: Website: https://bg-software.com/
[23:26:42 INFO]: Author: Ome_R

### Describe the bug

First question
Even if the allow-nether configuration in bukkit.yml and server.properties is set to false, you can enter the empty hell and the end normally, but after updating the plugin, you can't enter normally without turning on these two settings!

Second question
This problem is the name of the world of the end. After updating the plugin, the plugin will generate a new end world SuperiorWorld_end, but the previous end world is SuperiorWorld_the_end, so this makes it impossible to enter the end. Because if the player who generated the end before, because of the wrong world name, generates a new world, his end has no blocks in it, so he can't enter! Its correct name should be SuperiorWorld_the_end written in the configuration instead of SuperiorWorld_end!

### To Reproduce

The description of the error is clear enough!

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if the issues are fixed

**Comment by OmerBenGera** [comment]
Closing this as it seems to be fixed
If the issue still occurs, let me know
