### ISSUE TITLE
Coop status incorrectly removed when island owner goes offline

### ISSUE THREAD

**Issue by leon37921** [BG-Software-LLC/SuperiorSkyblock2#2177]
### Minecraft's Version

[00:04:36 INFO]: This server is running Paper version git-Paper-484 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 4445d23)

### Plugin's Version

[00:05:12 INFO]: SuperiorSkyblock2 version 2024.1-b236
[00:05:12 INFO]: Feature packed Skyblock core.
[00:05:12 INFO]: Website: https://bg-software.com/
[00:05:12 INFO]: Author: Ome_R

### Describe the bug

The Coop status of a player gets removed when the island owner goes offline.

### To Reproduce

1. Player_A enters the command /is coop Player_B.
2. Player_B can build on Player_A's island.
3. Player_A goes offline.
4.Player_B can no longer build.

### Additional Information

in config.yml:
coop-members: true
auto-uncoop-when-alone: false

**Comment by OmerBenGera** [comment]
I cannot seem to replicate the issue
Please upload your config file to pastebin and send a link to it here

**Comment by leon37921** [comment]
https://pastebin.com/7cFmGTz6

**Comment by OmerBenGera** [comment]
Still works fine for me
Can you take a video showcasing the issue?

**Comment by leon37921** [comment]
hey, I tryed to make a video and realised, that this feature works fine. The coop player can still build and interact with chests etc. when the island owner goes offline.
BUT we found out that the coop status gets removed, when the cooped player goes offline once. - Can I disable this, so the player has permanent access to that island until the owner removed the player as coop?

**Comment by OmerBenGera** [comment]
You can do that using the `/is permissions` system
