### ISSUE TITLE
console warn on island create

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2184]
### Minecraft's Version

1.21

### Plugin's Version

2024.1-b280 + ONEBLOCK MODULE dev #56

### Describe the bug

This kind of console warn spam while creating new island

[04:55:02 WARN]: [SuperiorSkyblock2] Setting biome DESERT to non-existing chunk: SuperiorWorld, 50, 50

### To Reproduce

create new island

**Comment by OmerBenGera** [comment]
Ignore it, just a debug message that I will remove soon.
