### ISSUE TITLE
all missions except Explorer have big console errors

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2185]
### Minecraft's Version

This server is running Paper version 1.21-111-master@66165f7 (2024-07-27T14:44:39Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugin's Version

2024.1-b280

### Describe the bug

All missions except Explorer do not work... I open menu /is missions -> choose category -> empty menu opens and error spam in console

![obraz](https://github.com/user-attachments/assets/73f59f5e-9133-4d2a-9239-0b775da617fd)

ERROR LOG:
https://pastebin.com/0S2AWxeb

### To Reproduce

 /is missions -> choose category -> empty menu opens and error spam in console

**Comment by OmerBenGera** [comment]
This may happen after `/is admin reload`
Restart and will be fixed, and I will look into fixing it.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

seems to be working fine :) Thanks!

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

would you like to answer one question as you are active here on github...
- does slimeworlds support work for 1.21 paper server?
