### ISSUE TITLE
Serializer Bug

### ISSUE THREAD

**Issue by JanReich** [BG-Software-LLC/SuperiorSkyblock2#2187]
### Minecraft's Version

1.20.4

### Plugin's Version

SuperiorSkyblock2 v2024.1-b236

### Describe the bug

Here is the log for the console exception on startup

https://mclo.gs/H9XF4PH

### To Reproduce

Start the Server

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it still occurs
I can't seem to replicate it myself.

**Comment by leon37921** [comment]
hi, I'm working with Jan.
I tryed updating to build 285 but the server is shutting down.
(same database and config files, but with a different set of plugins)

https://pastebin.com/G8gQed1R

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by leon37921** [comment]
fixed. No errors with b288

**Comment by OmerBenGera** [comment]
Awesome :)
Closing this for now
