### ISSUE TITLE
Every leaf rapidly decays on uisl

### ISSUE THREAD

**Issue by jaydenmcil** [BG-Software-LLC/SuperiorSkyblock2#2193]
### Minecraft's Version

This server is running Pufferfish+ version git-PufferfishPlus-45 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: eb69634 on HEAD)

### Plugin's Version

2024.1

### Describe the bug

When creating the schematic for my island, i make sure all the leaves have their persistent setting set to false, so that they decay, but when i create an island they all decay rapidly, even if they follow minecraft's leaf decay rules with creating custom trees
![image](https://github.com/user-attachment
![image](https://github.com/user-attachments/assets/d6f515a4-853b-4df8-8006-378296fe37d0)
s/assets/3ef229b3-68f4-4cc8-8dff-51663af6e72b)

### To Reproduce

Create a tree, set persistent to false and load in an island

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed.
Sadly, you'll have to re-create the schematic again.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
