### ISSUE TITLE
Openmenu command not work

### ISSUE THREAD

**Issue by Envqu** [BG-Software-LLC/SuperiorSkyblock2#2194]
### Minecraft's Version

1.20.4 purpur 2176

### Plugin's Version

b285

### Describe the bug

/is admin openmenu Envqu MenuCounts
/is admin menu Envqu MenuCounts

These commands do nothing.
Nothing happens. No errors in console

### To Reproduce

/is admin openmenu Envqu MenuCounts
/is admin menu Envqu MenuCounts

**Comment by OmerBenGera** [comment]
Hey, the command should only be used to open custom menus registered by other plugins.
You should instead make the player execute `/is counts`, which will open the counts menu for him.

**Comment by Envqu** [comment]
> Hey, the command should only be used to open custom menus registered by other plugins. You should instead make the player execute `/is counts`, which will open the counts menu for him.

Okay I see. It is possible to allow players use /is counts only for their own island? Somehow disable `/is counts <nick>` and allow `/is count`

**Comment by OmerBenGera** [comment]
> > Hey, the command should only be used to open custom menus registered by other plugins. You should instead make the player execute `/is counts`, which will open the counts menu for him.
> 
> Okay I see. It is possible to allow players use /is counts only for their own island? Somehow disable `/is counts <nick>` but allow `/is counts`

Currently all players can use /is counts on other islands.
You can make a feature request under the discussions tab to get it changed
