### ISSUE TITLE
glow items in menu when selected are not working

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2196]
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21-16202-HEAD@88f6d33 (2024-07-26T04:53:29Z) (Implementing API version 1.21-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock 2024.2-b297

### Describe the bug

showing glow on items in menu does not work (for example on biomes/top)

on 1.21:
![obraz](https://github.com/user-attachments/assets/f50b1d7f-2eb9-49e5-ba19-4519ed6f7f98)
![obraz](https://github.com/user-attachments/assets/4713dbad-5978-4050-9654-582e2df4de56)

on 1.20.1:
![obraz](https://github.com/user-attachments/assets/44c6a171-7967-4f27-8aa3-bc213258f0b3)
![obraz](https://github.com/user-attachments/assets/63337bcd-8327-422c-8cd6-a45674b36be4)

### To Reproduce

.

**Comment by OmerBenGera** [comment]
Heada cannot be glow.
You can see that the diamond is glowing on the other hand.

**Comment by OmerBenGera** [comment]
I don't know about heads (which I think do not support glow enchantment), but I am using your exact same spigot jar, and I can see the items in the `/is top` menu glowing.

**Comment by homerek111** [comment]
> I don't know about heads (which I think do not support glow enchantment), but I am using your exact same spigot jar, and I can see the items in the `/is top` menu glowing.

@OmerBenGera I use all the latest versions and this weired situation happens
- glow is not glowing (to compare how it should look i put glowing iron ingots in my inventory - screenshot)
- when glow should be visible on item it's lore becomes purple "I" (marked in the circle on screenshot) (if i disable glowing feature in menu options this lore bug does not happen)

![obraz](https://github.com/user-attachments/assets/50c87e9b-dadf-4c90-80c0-ff55aa6d1fa5)

**Comment by OmerBenGera** [comment]
What version of your MC client do you use?
I suspect it's related to ViaVersion or ViaBackwards and not the plugin

**Comment by homerek111** [comment]
> What version of your MC client do you use? I suspect it's related to ViaVersion or ViaBackwards and not the plugin

I tested it on 1.21 / 1.21.1 and 1.20.1 - its broken at all versions (as i noticed in my last message lore looks a little bit different on 1.21 and 1.20.1)
- Right now I even tested it without viaversions/backwards and it still happens 
- Right now i tested it without ALL other plugins and it still happens

**Comment by Srcsm** [comment]
Do you happen to have internal shaders enabled? This used to cause this issue.

**Comment by homerek111** [comment]
> Do you happen to have internal shaders enabled? This used to cause this issue.

I do not - I have vanilla Minecraft

**Comment by AlmostPanda** [comment]
Hi, don't know if my issue is related to this, but if I click on an item in `/is top` to sort the item I click on gets an empty line in lore
screenshot:
![image](https://github.com/user-attachments/assets/32371392-2065-40b5-b5fe-95accd7414de)

its not a big problem but it may confuse some people if you have an item with lore:
![image](https://github.com/user-attachments/assets/b2921310-62ed-499f-9e34-8f6c463e337c)

this is the item in `top-islands.yml`
'&':
    type: PLAYER_HEAD
    sorting-type: 'PLAYERS'
    name: '&6Seřadit podle aktuálního'
    lore:
      - '&6počtu hráčů na ostrově'
      
PS: using version 2024.2-b300
Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

**Comment by Srcsm** [comment]
> > Do you happen to have internal shaders enabled? This used to cause this issue.
> 
> I do not - I have vanilla Minecraft

Your glint settings (specifically Glint Speed) are above 0% in your video settings? It says they affect item glow, and setting Glint Speed to 0 on vanilla, with a vanilla client and SSB, is the only way I can replicate this.

**Comment by homerek111** [comment]
> > > Do you happen to have internal shaders enabled? This used to cause this issue.
> > 
> > 
> > I do not - I have vanilla Minecraft
> 
> Your glint settings (specifically Glint Speed) are above 0% in your video settings? It says they affect item glow, and setting Glint Speed to 0 on vanilla, with a vanilla client and SSB, is the only way I can replicate this.

nope. my glint speed is 50% and items in my superiorskyblock gui don't have glow effect at all + this empty line in lore comes (when it should be glowed)

**Comment by OmerBenGera** [comment]
> > > > Do you happen to have internal shaders enabled? This used to cause this issue.
> > > 
> > > 
> > > I do not - I have vanilla Minecraft
> > 
> > 
> > Your glint settings (specifically Glint Speed) are above 0% in your video settings? It says they affect item glow, and setting Glint Speed to 0 on vanilla, with a vanilla client and SSB, is the only way I can replicate this.
> 
> nope. my glint speed is 50% and items in my superiorskyblock gui don't have glow effect at all + this empty line in lore comes (when it should be glowed)

This empty line means SSB added the enchantment to the item

**Comment by AlmostPanda** [comment]
> I do not - I have vanilla Minecraft

do you use classic minecraft launcher or any mods like optifine and so on?
also found out that setting graphic to fancy/fast or brightness can cause it

**Comment by homerek111** [comment]
> > I do not - I have vanilla Minecraft
> 
> do you use classic minecraft launcher or any mods like optifine and so on? also found out that setting graphic to fancy/fast or brightness can cause it

100% vanilla - classic launcher + 0 mods

**Comment by homerek111** [comment]
> Any news regarding this?

nothing changed - still not glowing

**Comment by OmerBenGera** [comment]
> > Any news regarding this?
> 
> nothing changed - still not glowing

Let me know how I can replicate it on a clean setup.
Give me the exact version you use of Spigot and the exact version of SuperiorSkyblock you use.

**Comment by homerek111** [comment]
> > > Any news regarding this?
> > 
> > 
> > nothing changed - still not glowing
> 
> Let me know how I can replicate it on a clean setup. Give me the exact version you use of Spigot and the exact version of SuperiorSkyblock you use.

oh now it seems to be fixed (using the newest superior dev build)
problem resolved i think

**Comment by OmerBenGera** [comment]
Great.
If it happens again, let me know
