### ISSUE TITLE
crops-growth upgrading does not work at all

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2197]
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21-16202-HEAD@88f6d33 (2024-07-26T04:53:29Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugin's Version

2024.2-b298

### Describe the bug

as i am testing this feature and it does not work even with value crop-growth: 100
yes i have crops-interval: 5 - not 0

tried with reloging / restarting the server / creating a new island / upgrading via command and upgrades panel

### To Reproduce

grow some crops...

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

seems to be working :)
