### ISSUE TITLE
Error in console due to system type.

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#2201]
### Minecraft's Version

This server is running WineSpigot version 1_8_R3 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 2024.2-b300

### Describe the bug

Issue in console.

### To Reproduce

I don't know what the issue is. I did read the console and it shows ds.store which are invisible files os system and i think only apple generates these for what the reason is i don't know but i had an issue similar to this on another plugin by another author and he coded a hardfix for to ignore this type of file and it fixed it. Over the years so far what i've seen job well done on all your plugins for the most part.

### Additional Information

https://pastebin.com/VhXQYiP7

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by DebuffPvP** [comment]
Yes it's fixed. i seen this also on console it's auto generated by superior idk what it means though
[03:29:36 ERROR]: [SuperiorSkyblock2] [config.yml] Couldn't convert rewards.items.1 into an itemstack. Check type & data sections!

**Comment by OmerBenGera** [comment]
The item stack in that file is not valid. If you update the plugin to latest dev build, it should print the full path to the config file as well.
