### ISSUE TITLE
getIslandMembers method returns only online players

### ISSUE THREAD

**Issue by m-surowiec** [BG-Software-LLC/SuperiorSkyblock2#2204]
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21-16202-HEAD@88f6d33 (2024-07-26T04:53:29Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugin's Version

 SuperiorSkyblock2-2024.2-b300.jar

### Describe the bug

When using the plugin's api and the `getIslandMembers(true)` method, it returns only active players

### To Reproduce

get the list and print it

**Comment by OmerBenGera** [comment]
`getIslandMembers` returns all the island members of the island. If you pass `true` as an argument, the leader will be returned as well.

**Comment by m-surowiec** [comment]
I parsed the returned members as players, not offline players. Fixed
