### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Aknyzor** [BG-Software-LLC/SuperiorSkyblock2#2205]
### Minecraft's Version

1.21.1 Paper 40

### Plugin's Version

2024.2-b302

### Describe the bug

When I try to create an island, the following error appears in console:
https://pastebin.com/pGyTcwtV

### To Reproduce

When I try to type command /is create [island name]

**Comment by al3xwarrior** [comment]
Also having this issue.
https://mcpaste.io/c0a86a1c7dc341c2

Using Pufferfish 1.21.1

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by Aknyzor** [comment]
Everything is working as it should, thank you!
