### ISSUE TITLE
Island bank mechanism don't work

### ISSUE THREAD

**Issue by Pegazorro** [BG-Software-LLC/SuperiorSkyblock2#2208]
### Minecraft's Version

1.20.6

### Plugin's Version
2024.1

I can't check

### Describe the bug

The island bank has only paid me money a few times since the island was created. I've been playing here for 106 days and the island should have paid me some money 106 times and it did 11 times. This mechanic works fine for others but it doesn't work for me. The payment dates are also random so I don't know what the problem is here.

### To Reproduce

- /is deposit amount
- wait xxx days
- check bank logs, or bank balance (for me amount don't change)

**Comment by OmerBenGera** [comment]
Aren't you the owner of the server? Why can't you find the version of SuperiorSkyblock?

**Comment by Pegazorro** [comment]
> Aren't you the owner of the server? Why can't you find the version of SuperiorSkyblock?

I'm not the owner. But I found it.

**Comment by OmerBenGera** [comment]
> > Aren't you the owner of the server? Why can't you find the version of SuperiorSkyblock?
> 
> I'm not the owner. But I found it.

Report it to the staff team of the server, and if there is a real bug with the plugin - they should report it.
This is because it really depends on how they configured the plugin, maybe it is intended, or maybe it is a config fault.

Closing this for now

**Comment by OmerBenGera** [comment]
> > > > Aren't you the owner of the server? Why can't you find the version of SuperiorSkyblock?
> > > 
> > > 
> > > I'm not the owner. But I found it.
> > 
> > 
> > Report it to the staff team of the server, and if there is a real bug with the plugin - they should report it. This is because it really depends on how they configured the plugin, maybe it is intended, or maybe it is a config fault.
> > Closing this for now
> 
> Already reported to the staff team of the server, they don't change config or anything with island bank, I'm pretty sure that's plugin fault and it's not intended because It works for almost everyone so.

Ask them to open a bug report.
