### ISSUE TITLE
Missions crashes from time to time

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#221]
**Minecraft's Version**
Tuinity 1.16.5 #224

**Plugin's Version**: -
Dev build #126

**Describe the bug**
Players can't progress in there island personnal missions. It works for sometimes after a restart and then stops working for no reason.

**To Reproduce**
Just try to do missions (maybe without being OP) and you'll see that sometimes it stops working. It seems more common to have the errror with a mission where you have to break wheats.

**Additional information**
It would maybe work better if the plugin used the MYSQL database to save missions and not using the data.yml file which seems to be way behind in terms of actual data saving.

**Comment by Skizzles** [comment]
Am experiencing similar issues, had a player not be able to progress on specific objectives until after restart.

**Comment by Skizzles** [comment]
@banicola 

Could you provide an example of what quests are having issues? Also are they resetting the progress or?

**Comment by OmerBenGera** [comment]
Show me your mission please from the file that fails to work.

**Comment by banicola** [comment]
Here is a mission with breaking cactus that did the same thing today, it worked at the start (player get it's count increase by 7 cactus broken) but then stopped for no reason letting players blocked at the level they were at.

https://pastebin.com/c6PMgb4E

**Comment by banicola** [comment]
I will replace it with ItemsMissions it's not the same process to accomplish but at least it seems like it's working more often without issues

**Comment by OmerBenGera** [comment]
Might be because they placed the cactus or something and it was considered as a non-natural-block

**Comment by OmerBenGera** [comment]
Try replicating the issue yourself and let me know if that's the issue

**Comment by banicola** [comment]
> Try replicating the issue yourself and let me know if that's the issue

Of course if it was that I would have told them, it's not the issue, it's completely natural spawned blocks and still doesn't work, and if you set non natural blocks to true it doesn't solve this either I already tried 2 weeks ago

**Comment by OmerBenGera** [comment]
> 
> 
> > Try replicating the issue yourself and let me know if that's the issue
> 
> Of course if it was that I would have told them, it's not the issue, it's completely natural spawned blocks and still doesn't work, and if you set non natural blocks to true it doesn't solve this either I already tried 2 weeks ago

Try replicaing the issue yourself so we know what causes it to happen

**Comment by OmerBenGera** [comment]
Try using latest dev build, I fixed an issue with missions and it might fix this issue as well

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by banicola** [comment]
It seems like it's working with your change, I haven't tested it extensively but if no one else seems to report the issue it should be fixed.
