### ISSUE TITLE
The item stack in that file is not valid

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#2214]
The item stack in that file is not valid. If you update the plugin to latest dev build, it should print the full path to the config file as well.

_Originally posted by @OmerBenGera in https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/2201#issuecomment-2310975638_

The issue still remains even in the new dev build and i reset the supriorskyblock folder the plugin generates and it still appears in the console

[15:03:42 ERROR]: [SuperiorSkyblock2] [config.yml] Couldn't convert rewards.items.1 into an itemstack. Check type & data sections!

**Comment by OmerBenGera** [comment]
Fix it manually.
