### ISSUE TITLE
/is ban command teleports player from his own island

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2216]
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21.1-16283-develop@0c68d84 (2024-08-21T16:50:37Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

311

### Describe the bug

You are on your own island and some player is on his own island 

You can execute /is ban <his_nick> command to ban him on your island and he gets teleported to spawn (from his island) 
- so you can just troll people and send them to spawn even when they are not standing on your island 

### To Reproduce

As described above

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

seems to be fixed
