### ISSUE TITLE
Admin Spy Issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#222]
Hello, i use SuperiorSkyblock2-b126 in 1.12.2 i can't see /is chat <message> with /is admin spy. I can only see the message in chat mode. Thx

**Comment by OmerBenGera** [comment]
I tested it and it seems to work fine for me...
Maybe I didn't understand the bug correctly?

**Comment by nivcoo** [comment]
When player do /is chat <message> i can't show it with /is admin spy

**Comment by OmerBenGera** [comment]
It works fine for me - when players talk in /is chat, you receive messages if you have /is admin spy enabled.
Make sure you have a message set for the spy messages

**Comment by nivcoo** [comment]
Sorry i think you don't understand correctly. When player send "/is chat" and after that enter message it works, i can see the message but if player send "/is chat hello it's me" i cannot see the message in the /is admin spy

**Comment by Skizzles** [comment]
@OmerBenGera He means that when the player runs "/is chat (message)" then it does not show with admin spy. Only when the chat is toggled and players are talking back in forth does it display.

**Comment by nivcoo** [comment]
Yes it's that thx :p

**Comment by OmerBenGera** [comment]
Ahhh I understand, gonna check that out hopefully this week :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
