### ISSUE TITLE
items can be removed from containers outside of the island-border

### ISSUE THREAD

**Issue by leon37921** [BG-Software-LLC/SuperiorSkyblock2#2220]
### Minecraft's Version

This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)

### Plugin's Version

SuperiorSkyblock2 version 2024.2-b315

### Describe the bug

Players can remove items from chests, barrels, furnaces (can interact with containers) that are placed outsite the island-border.

### To Reproduce

1. create island
2. toggle island-border off and go outside
3. open container e.g. barrel and remove items

### Additional Information

The schematic is bigger than the border-size at the beginning. You can expand the border to unlock new islands with chests and barrels on them.

This also applies to deleted islands if there are still barrels outside, because when an island is deleted only the area within the border is deleted.

https://github.com/user-attachments/assets/b0bd8367-fc4f-4e9f-baa8-226e385fce5f

**Comment by OmerBenGera** [comment]
Can they interact with them on other islands as well?

**Comment by leon37921** [comment]
> Can they interact with them on other islands as well?

The player can interact with containers outsite of his own island
The player can't interact with containers outsite of other players islands
The player can interact with containers outsite of deleted islands (the outer parts of the island-schematic doesn't get deletet when entering the command /is delete. Only the parts inside the border.

**Comment by OmerBenGera** [comment]
Are you able to interact with containers inside other islands?

**Comment by OmerBenGera** [comment]
Are they able to place or break blocks there?
The plugin prevents any interaction outside of islands, similar to how it is done on other islands that you don't have access to.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by leon37921** [comment]
fixed. Perfect.
Thank you!
