### ISSUE TITLE
member join/leave the server message bug

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2221]
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21.1-16283-develop@0c68d84 (2024-08-21T16:50:37Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.2-b315

### Describe the bug

Before the leave message there is join message (it shouldn't pop up as the player is leaving not joining)

![obraz](https://github.com/user-attachments/assets/7b205730-dd68-4138-acec-35bc0aae8b39)

### To Reproduce

Just be the member of the same island with another account and leave the server (tested with OP on the leaving account)

**Comment by OmerBenGera** [comment]
I think it's because of vanish player status.
When player vanishes it also says "player left the game", and when player unvanishes it says "player joined the game".
Probably a mixture of player leaving and changing his vanish status caused this.

Use `/is admin debug send_message` and `/is admin debug show_stacktrace` and then replicate the issue. You should see stack traces in console - send me these.

**Comment by homerek111** [comment]
> I think it's because of vanish player status. When player vanishes it also says "player left the game", and when player unvanishes it says "player joined the game". Probably a mixture of player leaving and changing his vanish status caused this.

You are right - I have skript for executing "/essentials:vanish off" command each time administrator leaves the server and that's causing this message issue... (even when player was not vanished)

I tried this debugs things but there is no extra information in console at all:
![obraz](https://github.com/user-attachments/assets/550b4ee3-1c77-4e4b-a5e3-62813201a200)

**Comment by OmerBenGera** [comment]
> > I think it's because of vanish player status. When player vanishes it also says "player left the game", and when player unvanishes it says "player joined the game". Probably a mixture of player leaving and changing his vanish status caused this.
> 
> You are right - I have skript for executing "/essentials:vanish off" command each time administrator leaves the server and that's causing this message issue... (even when player was not vanished)
> 
> I tried this debugs things but there is no extra information in console at all: ![obraz](https://private-user-images.githubusercontent.com/93496464/363439286-550b4ee3-1c77-4e4b-a5e3-62813201a200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjU0MzIsIm5iZiI6MTcyNTE2NTEzMiwicGF0aCI6Ii85MzQ5NjQ2NC8zNjM0MzkyODYtNTUwYjRlZTMtMWM3Ny00ZTRiLWE1ZTMtNjI4MTMyMDFhMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0MzIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZDBiOTRiMDg0MTYwNzQyYzBjNDZlYzUyMmQ2ZjcwYzc0MGZkNmU0ZDUwMDExNWEzODA1MjJlYjIwNDEyNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f5xXjSK1C3IqOOsr-wVot5upS3k-Bvume2nb7H2ratg)

Anyways,
The skript causes this to occur.
Closing this
