### ISSUE TITLE
Warps problem

### ISSUE THREAD

**Issue by Coreli0** [BG-Software-LLC/SuperiorSkyblock2#2228]
### Minecraft's Version

[21:54] This server is running Paper version 1.20.6-148-ver/1.20.6@20f5165 (2024-07-02T15:37:33Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

### Plugin's Version

2024.01

### Describe the bug

![javaw_r6UKg804m8](https://github.com/user-attachments/assets/63fd92c6-b564-4628-8834-6521d9e101c5)
![Code_FjNMmh45Ut](https://github.com/user-attachments/assets/08cb4883-9b22-44b3-a1c4-795ed952d5fa)
How to make warp sign have warp name in second line like visitor warp

### To Reproduce

Place two signs

**Comment by OmerBenGera** [comment]
You can use `{0}` for a placeholder of the warp's name
