### ISSUE TITLE
Mobs can be renamed with nametags on others islands

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#223]
**Minecraft's Version**
1.16.5 Yatopia

**Plugin's Version**: -
b126

**Describe the bug**
Mobs can be renamed with nametags on others islands

**To Reproduce**
go on another persons island and try to rename the mob

**Additional information**
https://www.youtube.com/watch?v=1rRnAOZZZ_k

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build :)
