### ISSUE TITLE
Report bug

### ISSUE THREAD

**Issue by Alex11e** [BG-Software-LLC/SuperiorSkyblock2#2234]
### Minecraft's Version

1.18.2

### Plugin's Version

2024.3 

### Describe the bug

that's why I always get stuck in some wall, and there is no wall

### To Reproduce

that's why I always get stuck in some wall, and there is no wall

### Additional Information

that's why I always get stuck in some wall, and there is no wall

**Comment by OmerBenGera** [comment]
Use Paper, not related to the plugin.
