### ISSUE TITLE
player disconnect on biome change (while standing on the island)

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2235]
### Minecraft's Version

This server is running Paper version 1.21.1-83-master@2aaf436 (2024-09-17T15:10:44Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

### Plugin's Version

2024.3-b323

(im not using slimeworlds anymore - as it's so buggy i had to resign from using it...)

### Describe the bug

change island biome and stand on the island - you are getting instantly disconnected from the server with this title screen:
```
[23:04:58 INFO]: _homerek issued server command: /is admin setbiome _homerek basalt_deltas
[23:04:59 INFO]: _homerek lost connection: Disconnected
[23:04:59 INFO]: ← _homerek
```

![obraz](https://github.com/user-attachments/assets/6474798c-8fbc-40c7-9d01-17dbd684d0b0)

### To Reproduce

as described above

**Comment by homerek111** [comment]
i have no idea why but now it does not happen anymore...

**Comment by OmerBenGera** [comment]
> i have no idea why but now it does not happen anymore...

Weird.
If it happens again, let me know. For now, closing this

**Comment by homerek111** [comment]
> > i have no idea why but now it does not happen anymore...
> 
> Weird. If it happens again, let me know. For now, closing this

@OmerBenGera as i reported before it still happens sometimes - my players reported that to me and i also issued that. When there is a phase change (+ biome change with that) sometimes players of this island gets kicked from the server with that "Network Protocol Error"

**Comment by OmerBenGera** [comment]
Do you use ViaVersion / ViaBackwards / ProtocolLib?
Are you able to replicate it on a server with only SSB installed?

**Comment by homerek111** [comment]
> Do you use ViaVersion / ViaBackwards / ProtocolLib? Are you able to replicate it on a server with only SSB installed?

I do use all 3 via/viaback/protocollib 
i might try to test that in the evening on test server...

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by homerek111** [comment]
> Any news regarding this?

not happening anymore (i think - not sure)

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
