### ISSUE TITLE
No fall damage

### ISSUE THREAD

**Issue by GsTio86** [BG-Software-LLC/SuperiorSkyblock2#2238]
### Minecraft's Version

Spigot 1.20.2

### Plugin's Version

SuperiorSkyblock2 version 2024.3

### Describe the bug

First of all, I found that the fall damage disappeared. When I first logged into the server, the fall damage still existed. It was not until I died and reborn that the fall damage disappeared. Then I started to find which plug-in had the problem. Finally, I pointed to SuperiorSkyblock, which makes all worlds fall. The fall damage is all 0, which confuses me

### To Reproduce

First in a non-SuperiorWorld, then cause falling damage

I guess it was caused by this commit https://github.com/BG-Software-LLC/SuperiorSkyblock2/commit/b0a62871e89760a9375ab59629f2da33e7ed622e
Maybe it should be limited to Island World?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
You should not get fall damage after the plugin teleports you for 2 seconds, other than that you should get fall damage.
