### ISSUE TITLE
When  player first join, ther are not teleport to the skyblock

### ISSUE THREAD

**Issue by AkariH** [BG-Software-LLC/SuperiorSkyblock2#2239]
### Minecraft's Version

1.21.1

### Plugin's Version

SuperiorSkyblock2 version 2024.

### Describe the bug

When  player first join, ther are not teleport to the skyblock, but the default world " world"

### To Reproduce

install the plugin and start the server, when player first join, they will teleport to the default level world

**Comment by OmerBenGera** [comment]
Not a bug.
SuperiorSkyblock does not set up the spawn as spawnpoint.
Install a spawn plugin to do that
