### ISSUE TITLE
Material Problem

### ISSUE THREAD

**Issue by BadsGirl** [BG-Software-LLC/SuperiorSkyblock2#2246]
### Minecraft's Version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4) You are running the latest version

### Plugin's Version

2024.3-b333

### Describe the bug

When I open the **Mission > Fisherman** section, I get an error in the console, and the fisherman tasks do not display **Fisherman 1**.

Error Code:   https://hastebin.com/share/izalujuwoz.css

### To Reproduce

Yes, it's another I-İ problem... There's no issue in the text inside the file; it says TROPICAL_FISH, but there's still an error.

**Comment by OmerBenGera** [comment]
You are right, its an i-I problem.
Its somewhere in the placeholders of the mission item. Other than that, I cant help further more. You can see how it is read by the plugin.

**Comment by OmerBenGera** [comment]
You are right.
I used toUpperCase without providing it without specifing a Locale:  https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/ab241e67b0e532daffe9bdd0ee9b6f1c1f622e0a/Core/src/main/java/com/bgsoftware/superiorskyblock/missions/common/Placeholders.java#L44

I will fix it, hopefully it will work afterwards.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by BadsGirl** [comment]
Yes, this issue has been fixed, and the {value_iron_ore} or {value_pumpkin} has also been corrected.
I was resolving this value issue as {value_IRON_ORE}

And additionally, let me mention another issue:

`enchants:
      DURABILITY: 1`

This causes an error in the console, and I fix it by setting `SHARPNESS: 1`

**Comment by OmerBenGera** [comment]
Thanks for letting me know.
I am closing this for now :)
