### ISSUE TITLE
Nether generator no longer works

### ISSUE THREAD

**Issue by Bragos24** [BG-Software-LLC/SuperiorSkyblock2#2247]
### Minecraft's Version

Paper 1.20.4

### Plugin's Version

2024.3-b330

### Describe the bug

Hi, I recently updated to the latest version (previously 2024.1) and my basalt generator now produces the same blocks as the overworld cobblestone generator instead of the nether blocks.
The same thing happens with the End generator, which now produces the same blocks as the overworld (before it only produced cobblestone because I didn't set it).

Thanks in advance.

If I type /is admin show, I get data from both the Cobblestone and Basalt generators.

### To Reproduce

make a basalt generator in the nether and get the same blocks as the overworld cobblestone generator

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
Does it still occur on a server with only SuperiorSkyblock installed?

**Comment by Bragos24** [comment]
Yes I tried and it still occur if you set "match-generator-world: false" and make a basalt generator in the Nether (it generates Stone)

If match-generator-world is true, it works and it generates Basalt (and in the Overworld it generates Stone)

For me the issue is solved if I toggle this to "true" so you can close this issue, but it seems to me to be the opposite of this:

# Right now, toggling this to true will make the basalt generator to always generate nether rates, no matter
# in which world it's generating blocks.

**Comment by Bragos24** [comment]
Perfect, it is fixed.
Thank you
