### ISSUE TITLE
Island protect

### ISSUE THREAD

**Issue by redradit** [BG-Software-LLC/SuperiorSkyblock2#225]
Sometimes when you leave the island or you leave the server and then return to your island you can't do anything completely, as soon as you try to break something "protected island" you try to disband the island? "protected island" try to promote "protected island" you can't even leave the island

**Comment by Skizzles** [comment]
@redradit please provide what version of the plugin you are on and what server software you use.

Example:
Dev-b116
Paper-116

**Comment by OmerBenGera** [comment]
Protected island only occurs when you try to break/place blocks, interact with them etc, not when you execute commands.
You probably don't have access to that island or something...
Anyways, this issue wasn't responded and due to the lack of information, I am closing this for now
