### ISSUE TITLE
I have problem with starting server with SuperiorSkyblock

### ISSUE THREAD

**Issue by shinnnzu** [BG-Software-LLC/SuperiorSkyblock2#2250]
### Minecraft's Version

1.20.2

### Plugin's Version

#334 29/09/2024 20:42:53 

SuperiorSkyblock2-2024.3-b334

### Describe the bug

https://prnt.sc/kOzJbkfhdgtt

### To Reproduce

The server simply won't turn on, crashes every time, is there a plugin version that suits me?

**Comment by OmerBenGera** [comment]
Update to 1.20.4

**Comment by shinnnzu** [comment]
Okey, now it's okay
