### ISSUE TITLE
chat color 

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2251]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b334

### Describe the bug

superiorskyblock makes all players allow using color codes on global chat

superior.chat.color permission works only for island chat so i can't prevent using colors on global chat with that

i deleted superiorskyblock and restarted the server and the problem stopped 

i also tried to prevent it by using superiorsb permissions but it didnt work :/

### To Reproduce

use plugin + write something on the chat

plugins i use for chat:
essentials chat: 2.21.0-dev+106-8b08a8f
multichat 1.9.6

i use all these plugins on more servers and only on the one with superiorskyblock there is this color issue so im sure it is something wrong here

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

fixed
