### ISSUE TITLE
island chat messages are triggered by DiscordSRV plugin (some event cancel mistake i think)

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2253]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b334

DiscordSRV: 1.28.0

### Describe the bug

DiscordSRV plugin that connects minecraft chat with discord chat sends private messages from island's chat into discord. All other plugins with some island / land / plot chats I use on my other servers avoid that. (these chats should not be seen by discordsrv plugin)

I think there might be something wrong with cancelling messages event on island chat... please take a look at that

### To Reproduce

enable your island chat using ``/is chat`` command and then write some message -> it will be visible on discord channel using DiscordSRV 1.28.0 connection

**Comment by homerek111** [comment]
i also use multichat for bungee global chat and this island chat also is being sent into another servers like a normal chat message

**Comment by OmerBenGera** [comment]
All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEcent on Paper.
https://docs.papermc.io/paper/dev/chat-events

**Comment by homerek111** [comment]
> All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEvent on Paper. https://docs.papermc.io/paper/dev/chat-events

What can I do to prevent it from happening in that case…

**Comment by homerek111** [comment]
> All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEvent on Paper. https://docs.papermc.io/paper/dev/chat-events

@OmerBenGera What can I do to prevent it from happening in that case…

**Comment by OmerBenGera** [comment]
> > All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEvent on Paper. https://docs.papermc.io/paper/dev/chat-events
> 
> @OmerBenGera What can I do to prevent it from happening in that case…

Report it to them.

**Comment by homerek111** [comment]
> > > All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEvent on Paper. https://docs.papermc.io/paper/dev/chat-events
> > 
> > 
> > @OmerBenGera What can I do to prevent it from happening in that case…
> 
> Report it to them.

But it seems a little bit weired that only your plugin has that problem… similar projects avoid that issue :/ 

I think it would be much harder to fix it on their side as your plugin is an exception with that bug

**Comment by OmerBenGera** [comment]
> > > > All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEvent on Paper. https://docs.papermc.io/paper/dev/chat-events
> > > 
> > > 
> > > @OmerBenGera What can I do to prevent it from happening in that case…
> > 
> > 
> > Report it to them.
> 
> But it seems a little bit weired that only your plugin has that problem… similar projects avoid that issue :/
> 
> I think it would be much harder to fix it on their side as your plugin is an exception with that bug

The other plugins do not properly use Paper's API.

**Comment by homerek111** [comment]
> > > > > All of the mentioned plugins that listen to AsyncPlayerChatEvent should also listen to AsyncChatEvent on Paper. https://docs.papermc.io/paper/dev/chat-events
> > > > 
> > > > 
> > > > @OmerBenGera What can I do to prevent it from happening in that case…
> > > 
> > > 
> > > Report it to them.
> > 
> > 
> > But it seems a little bit weired that only your plugin has that problem… similar projects avoid that issue :/
> > I think it would be much harder to fix it on their side as your plugin is an exception with that bug
> 
> The other plugins do not properly use Paper's API. Changing messages within the AsyncPlayerChatEvent is deprecated and will cause your chat to not be "signed" in 1.20+. Thats why developers should use AsyncChatEvent instead.

In that case I’m fcked up with that as multichat plugin is not supported anymore :/ It requires me to disable island chat…

**Comment by OmerBenGera** [comment]
I'll try to make it configurable.

**Comment by homerek111** [comment]
> I'll try to make it configurable.

That would be great :)) Thanks
- I found out that discordsrv has it configurable as well - but still i have a problem with mulitchat - so it would help me :)

**Comment by OmerBenGera** [comment]
> > I'll try to make it configurable.
> 
> Hello, any chance of adding this island chat feature soon? :) (i reported some other bugs in other issues as well)

Check out latest dev build.
You'll find in the config file `chat-signing-support` section - set it to false and it should work.

**Comment by homerek111** [comment]
> > > I'll try to make it configurable.
> > 
> > 
> > Hello, any chance of adding this island chat feature soon? :) (i reported some other bugs in other issues as well)
> 
> Check out latest dev build. You'll find in the config file `chat-signing-support` section - set it to false and it should work.

fixed
