### ISSUE TITLE
Generator bug

### ISSUE THREAD

**Issue by fortunatas1** [BG-Software-LLC/SuperiorSkyblock2#2254]
### Minecraft's Version

1.20.4

### Plugin's Version

2024.1

### Describe the bug

https://github.com/user-attachments/assets/ab61bd4d-3269-4c29-ab5f-76d09f9cba4f

My all upgrades is max, but when i'm clicking on upgrade, they take my money.

### To Reproduce

Check video and scoreboard.

### Additional Information

`  generator-rates:
    '1':
      price: 25000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 80
          COAL_ORE: 5
          IRON_ORE: 5
          COPPER_ORE: 5
          GOLD_ORE: 5
      commands:
        - 'island admin setupgrade %player% generator-rates 2'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 2!'
    '2':
      price: 75000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 70
          COAL_ORE: 5
          IRON_ORE: 5
          COPPER_ORE: 5
          GOLD_ORE: 5
          LAPIS_ORE: 5
          EMERALD_ORE: 5
      commands:
        - 'island admin setupgrade %player% generator-rates 3'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 3!'
    '3':
      price: 150000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 60
          COAL_ORE: 5
          IRON_ORE: 5
          COPPER_ORE: 5
          GOLD_ORE: 5
          LAPIS_ORE: 5
          EMERALD_ORE: 5
          DIAMOND_ORE: 5
          REDSTONE_ORE: 5
      commands:
        - 'island admin setupgrade %player% generator-rates 4'
        - 'island admin msgall %player% &e&lSuperiorSkyblock &7Your generator was upgraded to level 4!'
    '4':
      price: 300000.0
      price-type: "Money"
      generator-rates:
        normal:
          STONE: 54
          COAL_ORE: 5
          IRON_ORE: 5
          COPPER_ORE: 5
          GOLD_ORE: 5
          LAPIS_ORE: 5
          EMERALD_ORE: 5
          DIAMOND_ORE: 5
          REDSTONE_ORE: 5
          LAPIS_ORE: 5
          ANCIENT_DEBRIS: 1
      commands:
        - 'island admin msg %player% &e&lSuperiorSkyblock &7You have reached the maximum upgrade for generator.'`

**Comment by Srcsm** [comment]
The final upgrade price should be `0`. 
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/ec02c2d111d8dc2392b130d76d133800e0a335fe/src/main/resources/modules/upgrades/config.yml#L241

**Comment by OmerBenGera** [comment]
As @Srcsm said, the price should be set to 0
