### ISSUE TITLE
Wind charge interactions on another islands

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2255]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z)

### Plugin's Version

Dev #334. 

### Describe the bug

You can use wind_charge item to push players / move boats / mobs / etc on another islands 

### To Reproduce

Use wind_charge

**Comment by OmerBenGera** [comment]
Check out latest dev build, I added WIND_CHARGE island privilege.
You might want to reset your permissions menu file as well, and update in the config file so COOP players will have this privilege by default.

**Comment by homerek111** [comment]
> Check out latest dev build, I added WIND_CHARGE island privilege. You might want to reset your permissions menu file as well, and update in the config file so COOP players will have this privilege by default.

fixed
