### ISSUE TITLE
/is blocks display of some items errors

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2256]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b334

### Describe the bug

some of items do not have their icon to display in /is blocks menu. For example all ``POTTED_FLOWERXYZ`` items or ``LAVA_CAULDRON`` or ``WATER_CAULDRON`` - these items' prices defined in ``/block-values/worth.yml `` are counted correctly but they can't be displayed in statistics menu + get error in console each time they are being counted

worth.yml example:
```
POTTED_ACACIA_SAPLING: 7.5
POTTED_ALLIUM: 15.0
POTTED_AZALEA_BUSH: 10.0
POTTED_AZURE_BLUET: 15.0
POTTED_BAMBOO: 21.0
POTTED_BIRCH_SAPLING: 7.5
POTTED_BLUE_ORCHID: 15.0
POTTED_BROWN_MUSHROOM: 15.0
POTTED_CACTUS: 56.9
POTTED_CHERRY_SAPLING: 7.5
POTTED_CORNFLOWER: 15.0
POTTED_CRIMSON_FUNGUS: 37.0
POTTED_CRIMSON_ROOTS: 30
POTTED_DANDELION: 3.0
POTTED_DARK_OAK_SAPLING: 7.5
POTTED_DEAD_BUSH: 3.0
POTTED_FERN: 3.2
POTTED_FLOWERING_AZALEA_BUSH: 50.0
POTTED_JUNGLE_SAPLING: 7.5
POTTED_LILY_OF_THE_VALLEY: 3.0
POTTED_MANGROVE_PROPAGULE: 50.0
POTTED_OAK_SAPLING: 7.5
POTTED_ORANGE_TULIP: 15.0
POTTED_OXEYE_DAISY: 15.0
POTTED_PINK_TULIP: 15.0
POTTED_POPPY: 3.0
POTTED_RED_MUSHROOM: 15.0
POTTED_RED_TULIP: 15.0
POTTED_SPRUCE_SAPLING: 7.5
POTTED_TORCHFLOWER: 30
POTTED_WARPED_FUNGUS: 37.0
POTTED_WARPED_ROOTS: 30
POTTED_WHITE_TULIP: 15.0
POTTED_WITHER_ROSE: 160
```

error example:
https://pastebin.com/Ud0gs95a

### To Reproduce

-

**Comment by homerek111** [comment]
these kind of items need some custom display like spawners have

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed
