### ISSUE TITLE
Executing /is recalculate command needed to fix island value

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2257]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b334

### Describe the bug

Sometimes island’s value is not properly refreshing itself. New placed blocks are adding value properly, but there are situations that some blocks that don’t exist anymore are still being counted and are adding value (for example some spawners or end portal frames)

To fix that it is needed to execute /is recalculate command

would that be possible to make it updating itself every X time to avoid situations like the one on the screenshots below (player had 56 end portal frames counted on his island because of oneblock module multiple portal creation (after end phase) - in fact he had only 8 of these. His island was top1 in value toplist because of these “fake portals”)

![2024-10-14_14 50 42](https://github.com/user-attachments/assets/a104e69f-60a3-4f3e-b5b8-d0a3dd22aed6)
![2024-10-14_14 50 48](https://github.com/user-attachments/assets/eb79223e-eae4-468c-aa49-d043756a572e)

### To Reproduce

Place valuable blocks and destroy them - sometimes they are still counted

**Comment by homerek111** [comment]
Nvm there is such an option in config XD

**Comment by homerek111** [comment]
Oh… I have just checked your discord and you said there many times that ``calc-interval:`` option is not recommended… 

in that case what should I do? 😅

**Comment by OmerBenGera** [comment]
This sounds like a conflict with another plugin.
You have a plugin that overrides breaking of spawners and end portal frames, and it does not let SSB know about the block changes.
You should find the plugin and report it over them. They need to either add direct support to SSB or call the BlockBreakEvent again.

I'll keep this issue opened so you can report back what plugin caused this

**Comment by homerek111** [comment]
> This sounds like a conflict with another plugin. You have a plugin that overrides breaking of spawners and end portal frames, and it does not let SSB know about the block changes. You should find the plugin and report it over them. They need to either add direct support to SSB or call the BlockBreakEvent again.
> 
> I'll keep this issue opened so you can report back what plugin caused this

Hmmm plugin that creates end portal frames is oneblock module from ssb2 - it creates it after finishing end phase. When someone reaches end phase again portal gets created one more time at the same place and it multiplies count of end portal frames I think…

**Comment by OmerBenGera** [comment]
> > This sounds like a conflict with another plugin. You have a plugin that overrides breaking of spawners and end portal frames, and it does not let SSB know about the block changes. You should find the plugin and report it over them. They need to either add direct support to SSB or call the BlockBreakEvent again.
> > I'll keep this issue opened so you can report back what plugin caused this
> 
> Hmmm plugin that creates end portal frames is oneblock module from ssb2 - it creates it after finishing end phase. When someone reaches end phase again - portal gets created one more time at the same place and it multiplies count of end portal frames I think…

Interesting, I will look into it.

**Comment by OmerBenGera** [comment]
@homerek111 Check out latest dev build of OneBlock, let me know if it still occurs

**Comment by homerek111** [comment]
> @homerek111 Check out latest dev build of OneBlock, let me know if it still occurs

issue with multicounting end portal frames seems to be fixed after update

**Comment by homerek111** [comment]
@OmerBenGera i found one more bug how to glitch value of an island...

You can use WIND_CHARGE on any breakable block/spawner on your island and it automatically is deleted from ``/is blocks`` and it is not adding value anymore (these blocks are not being broken - they are still standing on the island but not counting) it is needed to do recalculation to add them back to the value

1 more thing with end portal frames - now when i place it manually it does not count to ``/is blocks`` automatically and i need to recalculate to add it there...

**Comment by OmerBenGera** [comment]
The first two issues (wind charge + end portal frames) are fixed in latest dev build.
Please open a separate issue regarding the compatibility with SilkSpawners and I will look into it.

**Comment by homerek111** [comment]
> The first two issues (wind charge + end portal frames) are fixed in latest dev build. Please open a separate issue regarding the compatibility with SilkSpawners and I will look into it.

first 2 bugs are fixed - confirming

**Comment by OmerBenGera** [comment]
Awesome, closing this for now
