### ISSUE TITLE
(PreCreatureSpawnEvent) Is it normal to load?

### ISSUE THREAD

**Issue by SurvivorsDev** [BG-Software-LLC/SuperiorSkyblock2#2265]
### Minecraft's Version

This server is running AdvancedSlimePaper version 1.21.1-16387-paper_upstream@0f29848 (2024-10-17T20:28:35Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-2024.3-b341
SSBSlimeWorldManager-2024.1-b27

### Describe the bug

[IslandFlagsListener.java](https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/ec02c2d111d8dc2392b130d76d133800e0a335fe/src/main/java/com/bgsoftware/superiorskyblock/listener/IslandFlagsListener.java)

I formed 2 islands.
![{F2EA0A16-94B5-414D-819F-FCD3261258BE}](https://github.com/user-attachments/assets/bff66485-a72c-4773-ad8f-51b89e93419c)
![{20171B38-7CB5-4F6F-BB02-6387949B451E}](https://github.com/user-attachments/assets/cd28435c-bd29-4c47-9134-349ef1b4aa8e)

SuperiorSkyblock2::Combined Totalcount(1850010)  total(2.42% 1.676s, 0.14% of tick)avg(0.00ms per - 0.07ms/77.08 per tick)
SuperiorSkyblock2::Event: com.bgsoftware.superiorskyblock.listener.IslandFlagsListener$PaperListener (PreCreatureSpawnEvent)
![{D9073D08-E627-4EEB-84D7-D1C54B0B9307}](https://github.com/user-attachments/assets/04b5d2de-3a2f-432d-85a0-3ea988ff42d2)
![{D193A63C-D2FA-4ADF-813D-B2084A4DF622}](https://github.com/user-attachments/assets/1907aed8-44fa-4c88-bf1d-e08e592740df)

### To Reproduce

![{E69166CD-EEEA-497B-B281-FE5C7EB1F959}](https://github.com/user-attachments/assets/67ed0845-6060-49d2-9e9e-58e1226782d5)

**Comment by OmerBenGera** [comment]
Take a spark profiler and send a link to it here.

**Comment by SurvivorsDev** [comment]
https://spark.lucko.me/Mz00pvJJoS
https://timings.aikar.co/dev/?id=206211fca36348c2a8f7ae13d0605871

**Comment by OmerBenGera** [comment]
I cant load the spark profiler you sent.

**Comment by SurvivorsDev** [comment]
https://spark.lucko.me/p7Dkneo3Wg

**Comment by OmerBenGera** [comment]
Still the same.
"Unable to load the data. Perhaps it expired? Are you using a recent version?"

**Comment by SurvivorsDev** [comment]
https://spark.lucko.me/muE6agOyLQ
What part exactly are you looking at? I can take a screenshot.

This server is running AdvancedSlimePaper version 1.21.1-16387-paper_upstream@0f29848 (2024-10-17T20:28:35Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

**Comment by OmerBenGera** [comment]
> https://spark.lucko.me/muE6agOyLQ What part exactly are you looking at? I can take a screenshot.
> 
> This server is running AdvancedSlimePaper version 1.21.1-16387-paper_upstream@0f29848 (2024-10-17T20:28:35Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

Are you able to open the link you sent me...?
I still get the same error.
