### ISSUE TITLE
Cannot set slot in DISPENSER/DROPPER inventory types

### ISSUE THREAD

**Issue by Srcsm** [BG-Software-LLC/SuperiorSkyblock2#2267]
### Minecraft's Version

Paper version 1.21.1-123-master@aebbdc9 (2024-10-16T14:15:18Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2-2024.3-b342

### Describe the bug

When trying to use the inventory types DISPENSER or DROPPER, I cannot set the final slot (slot 8?).
Using the default files and only changing `type:` and `pattern:` to 
```YML
title: '&lCreate a new island...'
type: DROPPER
previous-menu: true

pattern:
  - '@ ) ) ( ^ ) ( ( $'
  ```
  You can see here I'm hovering my mouse over the slot but nothing is there, and clicking does nothing.
![image](https://github.com/user-attachments/assets/1144db08-10a8-4484-962a-7b569300999c)
There's nothing in the console when loading suggesting any issue with the menu, and nothing when clicking the blank slot.

### To Reproduce

Start server with SSB2 installed.
Modify `island-creation.yml`, changing the fields `type:` and `pattern:` to what's shown above
`/is admin reload`
Open the menu to see that all the slots have been set except the final slot.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Srcsm** [comment]
Working now, thank you!
