### ISSUE TITLE
The configuration error that limits the number of times a player can delete an island!

### ISSUE THREAD

**Issue by wlm1455925277** [BG-Software-LLC/SuperiorSkyblock2#2268]
### Minecraft's Version

[08:57:59 INFO]: Checking version, please wait...
[08:58:00 INFO]: Current Purpur Version: 1.21.1-2327-4b57bed (MC: 1.21.1)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugin's Version

[08:58:18 INFO]: SuperiorSkyblock2 version 2024.3-b342
[08:58:18 INFO]: Feature packed Skyblock core.
[08:58:18 INFO]: Website: https://bg-software.com/
[08:58:18 INFO]: Author: Ome_R

### Describe the bug

Setting the following configuration to 0 or -1 in the plugin configuration will cause the player to be able to delete islands indefinitely, which is obviously unreasonable? I think setting it to 0 means that the player can't delete the island, and -1 means that the player can delete the island indefinitely! Anyway, I think the logical setting to 0 should not allow the player to delete his island!

### To Reproduce

# The amount of times a player can disband an island.
# If you want to disable this feature, set it to 0.
disband-count: 0

### Additional Information

no

**Comment by Srcsm** [comment]
I don't think this is an error in the config. You have the ability in the config to list commands you want to disable, since all you want to do is remove players ability to delete their islands then you should disable the disband command.
