### ISSUE TITLE
Mob Drop Dupe Glitch

### ISSUE THREAD

**Issue by adrianisepic** [BG-Software-LLC/SuperiorSkyblock2#227]
**Minecraft's Version**
1.16.5 Paper

**Plugin's Version**: -
1.6.0

**Describe the bug**
When Mob drops are increased, and you drop an item to a piglin and it picks it up. The item will be duplicated when the mob is killed.

**To Reproduce**
Increase mob drops multiplier (this bug was reported to us using x4 Drops). Drop an item (ex. gold) to a Piglin and kill it. The item in hand will be duplicated.

**Additional information**
n/a

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue

**Comment by OmerBenGera** [comment]
Any news regarding this?
