### ISSUE TITLE
silkspawners changing spawner type using egg - recalculation needed to count it

### ISSUE THREAD

**Issue by homerek111** [BG-Software-LLC/SuperiorSkyblock2#2272]
### Minecraft's Version

This server is running Paper version 1.21.1-100-master@20ec622 (2024-09-26T23:53:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Plugin's Version

2024.3-b347

### Describe the bug

when you change spawner type using mob egg - spawner does not get automatically updated in /is blocks and i need to recalculate it (i use wildstacker + silkspawners https://www.spigotmc.org/resources/silkspawners-%E2%98%85-ready-to-rock-1-8-8-1-21-supported-%E2%98%85.7811/)

### To Reproduce

-

**Comment by homerek111** [comment]
> Check out latest dev build, let me know if it is fixed

@OmerBenGera ``/is recalc`` is still needed to update spawner type in island statistics

**Comment by OmerBenGera** [comment]
> > Check out latest dev build, let me know if it is fixed
> 
> @OmerBenGera `/is recalc` is still needed to update spawner type in island statistics

Hmm?
Changing spawners using spawn eggs is detected automatically now

**Comment by homerek111** [comment]
> > > Check out latest dev build, let me know if it is fixed
> > 
> > 
> > @OmerBenGera `/is recalc` is still needed to update spawner type in island statistics
> 
> Hmm? Changing spawners using spawn eggs is detected automatically now

should be but as a im testing it right now it is not updating

**Comment by OmerBenGera** [comment]
Do you have SilkSpawners set as your spawners-provider?

**Comment by homerek111** [comment]
> What is your spawners-provider set in config file?

in superiorskyblock config i have: ``spawners-provider: WildStacker``
i think i made it this way because some feature from wildstacker were not working properly with superiorskyblock when i had it on silkspawners...

**Comment by homerek111** [comment]
@OmerBenGera i tested it again with ``spawners-provider: SilkSpawners`` and now i remember what the bug was:

1. place stacked spawners (for example 5x chicken)
2. run ``/is recalc`` command
3. 5 stacked spawners are now counted as 1 (but they are in fact still 5x stacked placed)

this bug happens with ``spawners-provider: SilkSpawners`` but does not happen with ``spawners-provider: WildStacker``

that's why i have ``spawners-provider: WildStacker`` option enabled

(with ``spawners-provider: SilkSpawners`` egg issue is fixed btw - but i can't have it because the second bug)

**Comment by OmerBenGera** [comment]
You should use `spawners-provider: WildStacker` if you want stacked spawners support from WildStacker.
I will change it so the detection of changing spawner eggs using SilkSpawners will still work even if the spawners-provider is not configured to be SilkSpawners.

**Comment by homerek111** [comment]
> You should use `spawners-provider: WildStacker` if you want stacked spawners support from WildStacker. I changed it so the detection of changing spawner eggs using SilkSpawners will still work even if the spawners-provider is not configured to be SilkSpawners in latest dev build, so check it out

seems to be fixed, thanks!
