### ISSUE TITLE
schem not working with ia blocks

### ISSUE THREAD

**Issue by Bali0531-RC** [BG-Software-LLC/SuperiorSkyblock2#2274]
### Minecraft's Version

1.20.4

### Plugin's Version

2024.3

### Describe the bug

The island generation is not working with ItemsAdder custom blocks. 

### To Reproduce

Create a island schem of and island with IA block on it, create the island, and the block will be reversd to the base block.

**Comment by OmerBenGera** [comment]
Not supported.
You can make a feature request if you wish to see it in the plugin
