### ISSUE TITLE
GUI Problem in Mission Category [/is missions]

### ISSUE THREAD

**Issue by YodaZen** [BG-Software-LLC/SuperiorSkyblock2#2276]
### Minecraft's Version

1.19.4-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2 - 2024.3

### Describe the bug

The build-in mission category works fine opening the individual categories on click of the icons, but if you change the pattern (`missions.yml`) of the GUI the inventory click is not registered.

### To Reproduce

Change the pattern from this:
```
pattern:
  - '$ $ $ $ $ $ $ $ $'
  - '$ * * * * * * * $'
  - '$ * # @ % ^ & * $'
  - '$ * * * * * * * $'
  - '$ $ $ $ $ $ $ $ $'
  ```
  
  to this:
  ```
  pattern:
  - '$ * * * * * * * $'
  - '$ * # @ % ^ & * $'
  - '$ * * * * * * * $'
  ```

**Comment by OmerBenGera** [comment]
You must update the mission categories file in the missions module
