### ISSUE TITLE
Schematic mobs error

### ISSUE THREAD

**Issue by Yiiitt** [BG-Software-LLC/SuperiorSkyblock2#2284]
### Minecraft's Version

1.20.6

### Plugin's Version

Latest release

### Describe the bug

I created a schematic with two cows in it using the /is admin schematic but when a player loads the schematic to create an island, the cows do not appear.

### To Reproduce

Use the /is admin schematic command to create a schematic and include two cows in it.
Save the schematic.
Have a player create an island using this schematic.
Observe that the cows are missing on the player's island.

**Comment by Yiiitt** [comment]
Still same 
Im using slimeworlds too

**Comment by OmerBenGera** [comment]
Can you send me a copy of your schematic? I can't seem to replicate it even with SlimeWorlds module

**Comment by Yiiitt** [comment]
[normal.schematic.zip](https://github.com/user-attachments/files/17965869/normal.schematic.zip)

**Comment by OmerBenGera** [comment]
It seems to work fine for me. 
Are you able to replicate it on a server with only SSB installed?

**Comment by Yiiitt** [comment]
https://youtu.be/Ij4j_jafhtU
Created a new schematic with cows included.
Deleted the current island.
Stopped the server.
Renamed the schematic name test123.schematic to normal.schematic.
Started the server.
Opened a new island.
The cows still did not spawn on the new island. Using only SuperiorSkyblock, no SlimeWorld modules installed.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Yiiitt** [comment]
Fixed
