### ISSUE TITLE
Loading Island wrongly

### ISSUE THREAD

**Issue by JanReich** [BG-Software-LLC/SuperiorSkyblock2#2285]
Also view this issue at here: [SlimeWorldManager Issue 70](https://github.com/BG-Software-LLC/SSB-SlimeWorldManager/issues/70)

### Minecraft's Version

1.21.1

### Plugin's Version

SuperiorSkyblock2 2024.3-b334
SSBSlimeWorldManager-2024.1-b27

This server is running AdvancedSlimePaper version 1.21.1-16377-paper_upstream@e46bebe (2024-09-30T02:20:22Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21.1-16338-9ad4b57 (MC: 1.21.1)

### Describe the bug

Changes that made to the island are in the following case not saved/correctly loaded:
- Goto your slime island and make some changes
- Unload your island with `/aswm unload <island_name>`
- Go back to your island with `/island`
- Changes are not saved...

On a normal slime world the following does happen:
- Goto SlimeWorld and make changes
- Unload the world with `/aswm unload <world_name>`
- Load World with `/aswm load <world_name>`
- Goto world and view that the changes are saved/loaded correctly

That is why I am assuming the loading from SSB2 is not done correct

### To Reproduce

Look at the description

### Additional Information

I have rewritten my Plugin for our server and one module of the plugin is a home system. When I am loading the island with my homesystem the changes are visible and the island is correctly loaded.

The teleport method for player I am using:
```java
public static boolean teleportPlayer(final @NonNull Player player, final @NonNull String worldName, final double x,
                                         final double y, final double z, final float yaw, final float pitch) {
      World world = Bukkit.getWorld(worldName);
      if (world != null) {
          return teleportPlayer(player, new Location(world, x, y, z,
                  yaw == Float.MAX_VALUE ? player.getYaw() : yaw,
                  pitch == Float.MAX_VALUE ? player.getPitch() : pitch));
      }
      
      ServiceRegistry serviceRegistry = ServiceRegistry.getServiceRegistry();
      DependencyService dependencyService = (DependencyService) serviceRegistry.getService(DependencyService.class);
      assert dependencyService != null;
      if (!dependencyService.isSlimeWorldEnabled()) {
          return false;
      }
      return SlimeUtils.teleportPlayer(player, worldName, x, y, z, yaw, pitch);
}
 ```
 
 The loading method for the slime world I am using:
 ```java
 public static boolean teleportPlayer(final @NonNull Player player, final @NonNull String worldName, final double x,
                                         final double y, final double z, final float yaw, final float pitch) {
        World world = Bukkit.getWorld(worldName);
        if (world != null) {
            return PlayerUtils.teleportPlayer(player, new Location(world, x, y, z,
                    yaw == Float.MAX_VALUE ? player.getYaw() : yaw,
                    pitch == Float.MAX_VALUE ? player.getPitch() : pitch));
        }

        ServiceRegistry serviceRegistry = ServiceRegistry.getServiceRegistry();
        DependencyService dependencyService = (DependencyService) serviceRegistry.getService(DependencyService.class);
        assert dependencyService != null;
        if (!dependencyService.isSlimeWorldEnabled()) {
            return false;
        }

        FileLoader fileLoader = new FileLoader(new File("slime_worlds"));
        AdvancedSlimePaperAPI advancedSlimePaperAPI = dependencyService.getAdvancedSlimePaperAPI();
        try {
            SlimeWorld readWorld = advancedSlimePaperAPI.readWorld(fileLoader, worldName, false, new SlimePropertyMap());
            if (readWorld == null)
                return false;

            advancedSlimePaperAPI.loadWorld(readWorld, true);
            return PlayerUtils.teleportPlayer(player, new Location(Bukkit.getWorld(readWorld.getName()), x, y, z,
                    yaw == Float.MAX_VALUE ? player.getYaw() : yaw,
                    pitch == Float.MAX_VALUE ? player.getPitch() : pitch));
        } catch (UnknownWorldException | NewerFormatException | CorruptedWorldException | IOException e) {
            e.printStackTrace();
            return false;
        }
    }
 ```
 
 I would love to see if you could fix this loading bug.

**Comment by OmerBenGera** [comment]
I saw your report on the SWM's issues tracker, will look into it - don't worry.
