### ISSUE TITLE
Error on every entitydeathevent in console

### ISSUE THREAD

**Issue by zReinLefty** [BG-Software-LLC/SuperiorSkyblock2#2289]
### Minecraft's Version

1.21-127-master@4e6a2a1

### Plugin's Version

2024.4

### Describe the bug

Spams console with out of range error on every entitydeathevent

### To Reproduce

no idea. My guess is, its related to WildStacker plugin i am running.

### Additional Information

[superiorbug.txt](https://github.com/user-attachments/files/18052902/superiorbug.txt)

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by zReinLefty** [comment]
this was fixed
