### ISSUE TITLE
Island creation issue

### ISSUE THREAD

**Issue by JediM4ster** [BG-Software-LLC/SuperiorSkyblock2#229]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
Paper 1.16.5 70d697e6e

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
Superior skyblock 1.6.0

**Describe the bug**
Island creation sends an error when I've used my own schematic. I have used the built in schematic tool and have regular world edit. I've also tried it with fawe and it still gives me the same error. In game it says "an error has occurred please contact the admin to resolve this issue." I'm not sure if this is just me doing something wrong or not.

**To Reproduce**
Steps to reproduce the bug.
Use the island schematic creator. Add it to the gui. Try to create the island.

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

I can upload a clip if needed.
**Error from the config:**
23.04 23:03:34 [Server] INFO _The_Jedi_ issued server command: /is create Broski
23.04 23:03:39 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 3
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.island.SIsland.lambda$getTeleportLocations$40(SIsland.java:720)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.utils.threads.SyncedObject.readAndGet(SyncedObject.java:63)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.island.SIsland.getTeleportLocations(SIsland.java:717)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.island.data.SIslandDataHandler.executeInsertStatement(SIslandDataHandler.java:457)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.handlers.DataHandler.insertIsland(DataHandler.java:368)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.handlers.GridHandler.lambda$createIsland$4(GridHandler.java:177)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.schematics.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:195)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.utils.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:74)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$finishLoad$2(ChunksProvider.java:88)
23.04 23:03:39 [Server] WARN at java.lang.Iterable.forEach(Iterable.java:75)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.finishLoad(ChunksProvider.java:88)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$null$0(ChunksProvider.java:80)
23.04 23:03:39 [Server] WARN at com.bgsoftware.superiorskyblock.hooks.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:963)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)
23.04 23:03:39 [Server] WARN at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1027)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1074)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1055)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1231)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$9(MinecraftServer.java:1330)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:118)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1329)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
23.04 23:03:39 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
23.04 23:03:39 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by WolverStones** [comment]
Try latest build https://hub.bg-software.com/job/SuperiorSkyblock2/127/

**Comment by yakovliam** [comment]
Reproduced with exact same conditions, except using `pl3x Purpur 1060 5674cdc`

**Comment by JediM4ster** [comment]
> 
> 
> Try latest build https://hub.bg-software.com/job/SuperiorSkyblock2/127/

Seems to have worked to use the newest build.
