### ISSUE TITLE
Raids cancelled outside of Island worlds

### ISSUE THREAD

**Issue by Srcsm** [BG-Software-LLC/SuperiorSkyblock2#2291]
Responding to a user on the discord, we noticed that raids are cancelled outside the islands world making using SSB on a server also trying to use a survival type world result in having raids being cancelled in the survival world.

![image](https://github.com/user-attachments/assets/5f62767c-8e4a-4f96-a9a3-db5a4e8086e4)
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/94290a131fee0a962cb35c82d64ccd79f503ddd9/src/main/java/com/bgsoftware/superiorskyblock/listener/ProtectionListener.java#L629

Ideally, it would be nice if there were a config setting perhaps to list the world(s) to allow/restrict raids on, that way raids can still be allowed on a survival type world on the same server as SSB when the player isn't inside an island world. Otherwise, an added island setting to enable/disable raids maybe would help achieve the same goal?

_Originally posted by @Srcsm in https://github.com/BG-Software-LLC/SuperiorSkyblock2/discussions/2290_

**Plugin version:** _SuperiorSkyblock2-2024.4-b368.jar_
**Server version:** _Paper version 1.21.1-128-master@d348cb8 (2024-10-21T16:23:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)_

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Srcsm** [comment]
Apologies, I can confirm raids are working outside of the islands worlds now. Thank you!
