### ISSUE TITLE
Stacked blocks hologram not showing

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#2293]
### Minecraft's Version

1.20.4 (Pufferfish)

### Plugin's Version

SuperiorSkyblock b369 and WildStacker b108

### Describe the bug

Stacked blocks hologram doesn't update, you have to break one to actually get the hologram loaded:

https://i.imgur.com/1nylZZS.gif

### To Reproduce

Simply unloading the chunk and then loading it again, you won't be able to see any hologram on the stacked blocks

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by ArefyNetwork** [comment]
> Check out latest dev build, let me know if it is fixed

It's fixed now, thanks Omer, much appreciated!
