### ISSUE TITLE
Premium-drops upgrade affects armor stand drops

### ISSUE THREAD

**Issue by zReinLefty** [BG-Software-LLC/SuperiorSkyblock2#2295]
### Minecraft's Version

1.21-127-master@4e6a2a1

### Plugin's Version

2024.4-b370

### Describe the bug

Upgrading the premium-drops upgrade seems to affect armor stand drops aswell so any armor peices on the armor stand is affected. I'd suggest using upgrade level 5 if need to reproduce the bug.

### To Reproduce

/is upgrades > Premium Drops upgrade > Get it to like level 4 atleast > Place armor peices on the armor stand and break it

### Additional Information

That should be all the information needed

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by zReinLefty** [comment]
This was fixed.
