### ISSUE TITLE
problems with version 2024.4, it doesn't load

### ISSUE THREAD

**Issue by Lele289** [BG-Software-LLC/SuperiorSkyblock2#2297]
### Minecraft's Version

Minecraft version: 1.21.3
jar: https://api.papermc.io/v2/projects/paper/versions/1.21.3/builds/81/downloads/paper-1.21.3-81.jar

### Plugin's Version

Plugin version: 2024.4 and 2024.4-b379

### Describe the bug

I was starting the server configuration, when I go to insert the plugin it gives me an error, as if the version was not updated, even though I tried to use the latest dev version

### To Reproduce

start the paper or purpur .jar file and place the plugin file in the plugins folder, it should return the same error

### Additional Information

Error log:
https://pastebin.com/3UguSuK8

**Comment by OmerBenGera** [comment]
It seems to work fine for me using b379 and your exact paper version.
I recommend doing the following:
A) Make sure the hash of the file is correct - mine is 2A4AC57D1A98D200B9760B9379FD6218 (md5)
B) Delete `.paper-remapped` in plugins folder and let the plugin re-mapped again
C) Test it on a server with only SSB installed on a different setup, check if it still occurs

**Comment by Lele289** [comment]
ok perfect, now it works, but I had a question, if it was possible to map only some plugins and some not, since some come into conflict during remapping even if they are updated to the latest version.

I ask here since you are the only support that has answered me for now even though I know it is not inherent in the problem

**Comment by OmerBenGera** [comment]
The remapping process is done by Paper itself, nothing that SSB can really do anything about
It is must be done to plugins compiled against spigot mapping (any plugin that needs to support Spigot will be compiled against spigot mapping), therefore I don't think it is possible to disable it for some plugins, unless the plugins you download are compiled against mojang mapping (paper-only plugins may do so)

Closing this for now :)
