### ISSUE TITLE
Problem with /is chat

### ISSUE THREAD

**Issue by Rap3erka** [BG-Software-LLC/SuperiorSkyblock2#2300]
### Minecraft's Version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version

### Plugin's Version

SuperiorSkyblock2-2024.4

### Describe the bug

When I switch /is chat, the message is sent to general chat and is chat

### To Reproduce

Command /is chat -> write on chat

**Comment by OmerBenGera** [comment]
This is because of your chat plugin
You can disable chat signing support in the config file and it will probably be fixed
