### ISSUE TITLE
 Adding an alias assigned to a disabled command

### ISSUE THREAD

**Issue by Lemvs** [BG-Software-LLC/SuperiorSkyblock2#2304]
### Minecraft's Version

1.21.1

### Plugin's Version

2024.4

### Describe the bug

I disabled the 'warp' command and created an alias 'warp' for the 'visit' command. When I type /is it displays the 'warp' argument, but I can't use this command because it displays the island help (I want to use visitors sign as warps, so I need to set it up like this)

### To Reproduce

Add 'warp' to disabled-commands and create an alias 'warp' for the 'visit' command in the config

### Additional Information

![image](https://github.com/user-attachments/assets/db2a1139-2189-48b8-8d7f-2a4c2705a637)
![image](https://github.com/user-attachments/assets/1b8108c5-36f9-4173-95ae-2bedf1c27c3e)

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed

**Comment by Lemvs** [comment]
What I wanted to do already works, but now the disabled-commands option has stopped working - when you add a command there, you can still use it, it is only not visible in the help and as a hint when entering a command

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed as well

**Comment by Lemvs** [comment]
Now it works fine, thanks
