### ISSUE TITLE
Rating own island

### ISSUE THREAD

**Issue by Lemvs** [BG-Software-LLC/SuperiorSkyblock2#2305]
### Minecraft's Version

1.21.1

### Plugin's Version

2024.4

### Describe the bug

When we rate an island and then join it, our rating is not removed even though the rate-own-island option is disabled in the config

### To Reproduce

Set rate-own-island to false in config, rate the island, then join it

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed

**Comment by Lemvs** [comment]
Now it works fine, thanks
