### ISSUE TITLE
Visitors sign

### ISSUE THREAD

**Issue by Lemvs** [BG-Software-LLC/SuperiorSkyblock2#2311]
### Minecraft's Version

1.21.1

### Plugin's Version

2024.4

### Describe the bug

If I destroy a block that has a visitor sign placed on it, the visitor location will still exist and you will be able to move to it even if the sign is not there, the visitor location will be removed once the sign is placed again and destroyed properly

### To Reproduce

Place a visitor sign on the wall/floor and destroy the wall/floor block

### Additional Information

https://imgur.com/a/dvJr25w

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Lemvs** [comment]
It's fixed now, thanks
