### ISSUE TITLE
Error when clearing generator

### ISSUE THREAD

**Issue by Leyji** [BG-Software-LLC/SuperiorSkyblock2#232]
**Minecraft's Version**
1.12.2 PaperSpigot

**Plugin's Version**: -
SuperiorSkyblock2-b112

**Describe the bug**
Error occured when using the /island admin cleargenerator command.

**To Reproduce**
The generator stopped working for one player so I tried to reset it with the /island admin cleargenerator command but instead of clearing the generators, it showed up an error.

**Additional information**
/is admin info shows Generator Rates x3: https://ctrlv.link/GLI8
generator upgrade configuration: https://pastebin.com/EV8ixthA
Error: https://pastebin.com/dU3aaHCt

**Comment by PortableGames** [comment]
lmao .. pure truth

**Comment by OmerBenGera** [comment]
@PortableGames I will fix the error, however let's focus on the generator issue - what happened when they "didn't work"?
The cobblestone wasn't generated at all (or any of the generated ores) or only cobble was generated?

**Comment by PortableGames** [comment]
possibly damaged player data file created at the moment of lag or server crash

**Comment by Leyji** [comment]
> @PortableGames I will fix the error, however let's focus on the generator issue - what happened when they "didn't work"?
> The cobblestone wasn't generated at all (or any of the generated ores) or only cobble was generated?

only cobble was generated

**Comment by OmerBenGera** [comment]
> 
> 
> > @PortableGames I will fix the error, however let's focus on the generator issue - what happened when they "didn't work"?
> > The cobblestone wasn't generated at all (or any of the generated ores) or only cobble was generated?
> 
> only cobble was generated

Did /is admin show showed the correct values?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Leyji** [comment]
> Any news regarding this?

Nope, tried to completly delete player's island, then I gave him money so he can upgrade his generators. Bug was still occurring over and over again, so I created a command, which will manualy set his gen rates when he types it (when the generator gets reset to basic cobblestone)

**Comment by OmerBenGera** [comment]
What does /is admin info show when it happens...?

**Comment by OmerBenGera** [comment]
What does /is admin info show when it happens...?

**Comment by OmerBenGera** [comment]
Any news regarding this?
