### ISSUE TITLE
Right Clicking Slabs+Stairs with a Bucket cause Island level to Decrease

### ISSUE THREAD

**Issue by SecretarySami** [BG-Software-LLC/SuperiorSkyblock2#234]
```
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
Server Jar - Yatopia
Minecraft Version - 1.16.5

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
SuperiorSkyblock2-b126.jar

**Describe the bug**
A clear and concise description of what the bug is.
When Right clicking slabs or stairs with a bucket in your hand it decreases your island level
**To Reproduce**
Steps to reproduce the bug.
1. Hold bucket in hand
2. Right click slab or stair
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
https://www.youtube.com/watch?v=Bwg_3yzZR5s
```

**Comment by OmerBenGera** [comment]
I can't replicate the issue.

**Comment by SecretarySami** [comment]
So, we changed server jars to Purpur from yatopia, currently it's still an issue, is there any other info I can provide that might help ?

**Comment by OmerBenGera** [comment]
> 
> 
> So, we changed server jars to Purpur from yatopia, currently it's still an issue, is there any other info I can provide that might help ?

Probably due to another plugin somehow breaking it.
Try replicaitng the issue on another server with only SSB installed

**Comment by Skizzles** [comment]
Tested with just SSB on purpur, checking it with paper spigot.

**Comment by Skizzles** [comment]
From my testing this still happens on paper, it seems like some sort of plugin conflict but I am unsure at this time. Will test and update on it.

**Comment by OmerBenGera** [comment]
It works fine without any plugins, therefore without finding the plugin it will never get fixed.

**Comment by OmerBenGera** [comment]
Any news regarding this?
