### ISSUE TITLE
Reuse space after island disband to reduce world filesize

### ISSUE THREAD

**Issue by Baterka** [BG-Software-LLC/SuperiorSkyblock2#235]
Plugin clears chunks after island is disbanded by player, but empty space is not reused aftewards leaving behind ~2MB region each time. I was hoping that SS2 will have this feature, because I was using BentoBox and my world had 100GB after a while.

Any chance this will get implemented?

**Comment by OmerBenGera** [comment]
That's not a bug, that's intended.

**Comment by Baterka** [comment]
Its more of feature request. Why is it intended? What is the purpose of not reusing space?

**Comment by OmerBenGera** [comment]
> 
> 
> Its more of feature request. Why is it intended? What is the purpose of not reusing space?

Reusing the space can cause some issues.
Anyways, you can ask for new features at the discussions area :)
