### ISSUE TITLE
islands not saving upon server restart

### ISSUE THREAD

**Issue by voidaye** [BG-Software-LLC/SuperiorSkyblock2#236]
**Minecraft's Version**
CraftBukkit version 3056-Spigot
Minecraft 1.16.5

**Plugin's Version**: -
1.6.0

**Describe the bug**
When the server restarts, everyone's islands appear to be deleted.

**To Reproduce**
Restart the server.

**Additional information**
can provide whatever you need.

**Comment by voidaye** [comment]
update *
it looks like the islands aren't being deleted, but the owners are auto disbanding (maybe).

**Comment by YegRec** [comment]
I have exactly the same problem, I am configuring my server and I noticed that bug, I will continue configuring other things while I wait for it to be fixed

**Comment by WolverStones** [comment]
try latest dev build https://hub.bg-software.com/job/SuperiorSkyblock2/

**Comment by OmerBenGera** [comment]
Are you talking about the blocks in the islands being deleted, or /is show shows that the players don't have an island?

**Comment by OmerBenGera** [comment]
Any news regarding this?
