### ISSUE TITLE
Chunk Provider heavy task

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#248]
**Minecraft's Version**
Paper 1.12.2

**Plugin's Version**: -
1.6.0

**Describe the bug**
Chunk provider is an heavy task on the server, maybe with a spark you can see and try to optimise

**Additional information**
https://spark.lucko.me/h4wNeJEQmE

![Screenshot_3554](https://user-images.githubusercontent.com/31826333/117788473-b8560780-b247-11eb-8fa1-f1721508c95d.png)

**Comment by OmerBenGera** [comment]
Loading chunks is lagging your server... Nothing I can do to fix that.
