### ISSUE TITLE
Visit signs broken

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#249]
**Minecraft's Version**
Paper 1.16.5
**Plugin's Version**: -
Dev Build 133
**Describe the bug**
Bug with the visit feature:

- When you place a sign with [Welcome] to define an area for the /is visit command, it does set the teleport position but doesn't change the sign color (open/close).

- If you remove the sign it doesn't remove the old position from your island and players can still use /is visit to teleport to a previous visitor area of your island.

**To Reproduce**
- Start a new island
- Place a sign with [Welcome] on your island (sign doesn't show if it is open/close)
- Break the sign to "remove" the visitor area (doesn't remove it)

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue.

**Comment by CustomEntity** [comment]
> I can't seem to replicate the issue.

The same on my side

Do you have a plugin that handles signs for example ServerSigns?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by banicola** [comment]
I use ColorSigns and SudoSigns.

**Comment by OmerBenGera** [comment]
They probably interface with the plugin. Try removing them and check if the issue still persists.

**Comment by OmerBenGera** [comment]
Any news regarding this?
