### ISSUE TITLE
Crop Growth value issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#250]
**Minecraft's Version**
PaperSpigot 1.12.2

**Plugin's Version**: -
SuperiorSkyblock2-b133.jar

**Describe the bug**
Hello after the restart the value of cropGrowth changes by itself.

**To Reproduce**
Do /is admin setcropgrowth USERNAME 1.10 for example and restart the server, after that look the value in /is admin info and you can look the value will become like the pics

**Additional information**
https://pics.revolis.fr/2021-05/12/16-57_belB.png

**Comment by OmerBenGera** [comment]
Don't use crop growth of 1.1, it's literally the same as 1...
Anyways, the value you shown is just due to rounding of decimals, nothing to be worried about.

**Comment by nivcoo** [comment]
Yes but i use the placeholder result so i use == 1.10 and it works correctly with mob drop for exemple, can you fix the issue ? Thx

**Comment by OmerBenGera** [comment]
Let me know how to replicate it, as the plugin doesn't change the values unless you do /is admin setcropgrowth

**Comment by nivcoo** [comment]
Do /is admin setcropgrowth USERNAME 1.10 for example and restart the server, after that look the value in /is admin info

**Comment by OmerBenGera** [comment]
Ahm it works fine for me. Try setting the crop growth, and then look in the database if it sets it with that ugly value

**Comment by nivcoo** [comment]
Yes i will see that

**Comment by nivcoo** [comment]
So, look my screen https://pics.revolis.fr/2021-05/14/14-53_ZSow.png i have only set 1.20 and 1.10 not 1.29999995231628

**Comment by OmerBenGera** [comment]
It seems like something to do with how your MySQL/SQLite parses doubles

**Comment by nivcoo** [comment]
Look https://pics.revolis.fr/2021-05/14/15-08_xYvY.png i haven't the issue with mob drops

**Comment by OmerBenGera** [comment]
mob drops are parsed to ints, that's probably why.

**Comment by OmerBenGera** [comment]
Weird, they are saved in the same way
