### ISSUE TITLE
Failed to execute query UPDATE

### ISSUE THREAD

**Issue by WolverStones** [BG-Software-LLC/SuperiorSkyblock2#251]
**Minecraft's Version**
This server is running Paper version git-Paper-652 (MC: 1.16.5)

**Plugin's Version**: -
SuperiorSkyblock2 version 1.6.0-DEVb133

Storage type: MySQL

  useSSL: false
  allowPublicKeyRetrieval: true

Error:
https://gist.github.com/WolverStones/547eaa86168c7466d255af0530dc6926

**Comment by OmerBenGera** [comment]
Your database is broken, this is not an issue with the plugin.
Your table is missing a column.
