### ISSUE TITLE
NoSuchFieldError: chunkKey

### ISSUE THREAD

**Issue by Casheh** [BG-Software-LLC/SuperiorSkyblock2#254]
**Minecraft's Version**
Paper 1.12.2

**Plugin's Version**: -
Dev build 

**Describe the bug**
Any time ChunkLoadEvent or ChunkUnloadEvent event is called, this error is thrown out in console:

![LwK70](https://user-images.githubusercontent.com/44023561/118345944-ff712080-b505-11eb-9f8d-b30a6ef254d7.png)

As it says in the image, a NoSuchFieldException is being thrown. I've already checked the code from the build however and the field is definitely there for the appropriate NMS class. This error is preventing users from creating or disbanding islands.

**To Reproduce**
Run paper 1.12.2 and attempt to create an island.

**Comment by OmerBenGera** [comment]
Weird. Does a restart help?

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build :)
