### ISSUE TITLE
Plugin glitched?

### ISSUE THREAD

**Issue by SamIsOnMC** [BG-Software-LLC/SuperiorSkyblock2#256]
**Minecraft's Version**
1.16.5 on Paper
**Plugin's Version**: -
1.6.0 Dev

**Describe the bug**
I got an huge error when trying to create an island with the plugin, and then the whole plugin and server glitches out and sometimes even crashes! 

**To Reproduce**
Just throw it in on an 1.16.5 server running on paper with Java 8

**Additional information**
errorcode: 12.05 10:32:05 [Server] WARN java.lang.ArrayIndexOutOfBoundsException: 3
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.island.SIsland.lambda$getTeleportLocations$40(SIsland.java:720)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.utils.threads.SyncedObject.readAndGet(SyncedObject.java:63)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.island.SIsland.getTeleportLocations(SIsland.java:717)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.island.data.SIslandDataHandler.executeInsertStatement(SIslandDataHandler.java:457)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.handlers.DataHandler.insertIsland(DataHandler.java:368)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.handlers.GridHandler.lambda$createIsland$4(GridHandler.java:177)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.schematics.SuperiorSchematic.lambda$pasteSchematic$1(SuperiorSchematic.java:195)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.utils.blocks.BlockChangeTask.lambda$submitUpdate$4(BlockChangeTask.java:74)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$finishLoad$2(ChunksProvider.java:88)
12.05 10:32:05 [Server] WARN at java.lang.Iterable.forEach(Iterable.java:75)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.finishLoad(ChunksProvider.java:88)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.utils.chunks.ChunksProvider.lambda$null$0(ChunksProvider.java:80)
12.05 10:32:05 [Server] WARN at com.bgsoftware.superiorskyblock.hooks.AsyncProvider_Paper.lambda$loadChunk$0(AsyncProvider_Paper.java:16)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:963)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:943)
12.05 10:32:05 [Server] WARN at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1027)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1074)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1055)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1231)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$9(MinecraftServer.java:1330)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:118)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1329)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
12.05 10:32:05 [Server] WARN at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
12.05 10:32:05 [Server] WARN at java.lang.Thread.run(Thread.java:748)

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it works.

**Comment by SamIsOnMC** [comment]
How do i get the latest build?

**Comment by OmerBenGera** [comment]
https://bg-software.com/superiorskyblock/
You can find there the latest dev build

**Comment by SamIsOnMC** [comment]
The latest dev build fixed it for me! Thanks!
