### ISSUE TITLE
We can't use our own upgrades anymore

### ISSUE THREAD

**Issue by ElBananaa** [BG-Software-LLC/SuperiorSkyblock2#257]
**Minecraft's Version**
```
This server is running Purpur version git-Purpur-1111 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1102 (MC: 1.16.5)
```

**Plugin's Version**: -
SSB2 Build 139

**Describe the bug**
Since the latest update, it is not possible to remove some upgrades anymore. Everytime you try it and reload the plugin, your config gets overwritten, and gets replaced with the default one.

**To Reproduce**
- Remove an upgrade (like generator-rates), and create new upgrades (In my case, I tried with `normal-generator-rates` and `nether-generator-rates`. Then reload the plugin (or restart the server. I tried both, it didn't change anything), and reopen the file. It'll get overwritten by the default config, and will remove any custom upgrade.

**Additional information**
Here's the config I used in `/plugins/SuperiorSkyblock2/modules/upgrades/config.yml` : https://paste.gg/p/anonymous/47c1ea3154fb49edb98fafbf3530f907

**Comment by OmerBenGera** [comment]
Check latest dev build, let me know if it works

**Comment by ElBananaa** [comment]
> Check latest dev build, let me know if it works

Hey,
It looks like it's fixed now. Unfortunately, this completely removed all the previous upgrades from the database, which is a bit annoying, but nvm, thanks. :)

**Comment by ElBananaa** [comment]
Sorry for the double post, but for some reason, after a server restart, island upgrades aren't saved, they're not correctly saved to the database (I'm using a mysql database).

**Comment by OmerBenGera** [comment]
> 
> 
> Sorry for the double post, but for some reason, after a server restart, island upgrades aren't saved, they're not correctly saved to the database (I'm using a mysql database).

open a new issue, this is not related to the original issue
