### ISSUE TITLE
(2 bugs) Island not save upon server restart and a weirr bug

### ISSUE THREAD

**Issue by MynamisTG** [BG-Software-LLC/SuperiorSkyblock2#258]
**Minecraft's Version**
Spigot 1.8.x

**Plugin's Version**: -
1.6.0 - #139

**Describe the bug**
Bug1:  Island not save upon server restart (After restart, my island has been disappear but it not be delete, when im teleport to that xyz of my old island before i restart the serrver, it still there) but after restart it tell me dont have island
Bug2: https://gyazo.com/fef5f5047ad1def8054d6af80946b712
Im still in the island of my friend,but i can spam create island and can not leave and disband!!

**Additional information**
Bug2: https://gyazo.com/fef5f5047ad1def8054d6af80946b712

**Comment by MynamisTG** [comment]
no error spam in log!

**Comment by OmerBenGera** [comment]
When you create an island, you cant open new ones. Probably an error that causes both issues. Look for errors in console

**Comment by MynamisTG** [comment]
nothing error in console about superiorskyblock2

**Comment by OmerBenGera** [comment]
I really don't know what happens then. Let me know if you manage to replicate the issue on another server.

**Comment by MynamisTG** [comment]
U can see in the gif, im not leader of the island, error only cause by some players have that problem, when i join island of that player, im will be error and can not leave or disband! and that error player too (when i spam create new island, it alway show leader not me, it show that error player is leader) 
Some detail of that error i had founded before: 
We have me and 2 players are (A and B)
When i disband island of player A (the player have that error), player B will lost island (player B will be tell "u dont have island" but not deleted island) and then i do /is admin join (Players B) and .....im cannot leave disand or more.. only can spam create island like a gif :(
Do u think it about database?

**Comment by OmerBenGera** [comment]
Reset your database file. It sounds like a corruption to me.
Maybe you have a plugin that somehow changes UUIDs of players (plugins that let premium players keep their UUID on offline servers, for example)

**Comment by MynamisTG** [comment]
can u fix it in new version or recommed some plugin UUID hook with SSB2 (im using UUIDSpoof-Fix)? the old version of SSB 2 dont have that problem
And my 300 players are playing, i cant not reset their the database file

**Comment by OmerBenGera** [comment]
> 
> 
> can u fix it in new version or recommed some plugin UUID hook with SSB2 (im using UUIDSpoof-Fix)? the old version of SSB 2 dont have that problem
> And my 300 players are playing, i cant not reset their the database file

it's not possible to fix it. Plugins shoudl never change uuid of players, the purpose of the uuids is a way to track players, and if they are changed it can cause issues.
You can delete the data of specific players that are glitched.

**Comment by ElBananaa** [comment]
> > can u fix it in new version or recommed some plugin UUID hook with SSB2 (im using UUIDSpoof-Fix)? the old version of SSB 2 dont have that problem
> > And my 300 players are playing, i cant not reset their the database file
> 
> it's not possible to fix it. Plugins shoudl never change uuid of players, the purpose of the uuids is a way to track players, and if they are changed it can cause issues.
> You can delete the data of specific players that are glitched.

I actually have the same issue. Just reported it in. The server is in offline mode due to the usage of Velocity, but I enabled online mode on velocity's side. I can guarantee that the server is still using online uuids. I started using velocity 2 or 3 weeks ago, this never happened before. I also reported this issue in #257

**Comment by OmerBenGera** [comment]
> 
> 
> > > can u fix it in new version or recommed some plugin UUID hook with SSB2 (im using UUIDSpoof-Fix)? the old version of SSB 2 dont have that problem
> > > And my 300 players are playing, i cant not reset their the database file
> > 
> > 
> > it's not possible to fix it. Plugins shoudl never change uuid of players, the purpose of the uuids is a way to track players, and if they are changed it can cause issues.
> > You can delete the data of specific players that are glitched.
> 
> I actually have the same issue. Just reported it in. The server is in offline mode due to the usage of Velocity, but I enabled online mode on velocity's side. I can guarantee that the server is still using online uuids. I started using velocity 2 or 3 weeks ago, this never happened before. I also reported this issue in #257

it's not even the same bug, what are you talking about?
He can create new islands after he already creates one, your issue is related to upgrades not saved correctly
totally two different issues that are not related to each other

**Comment by ElBananaa** [comment]
> > > > can u fix it in new version or recommed some plugin UUID hook with SSB2 (im using UUIDSpoof-Fix)? the old version of SSB 2 dont have that problem
> > > > And my 300 players are playing, i cant not reset their the database file
> > > 
> > > 
> > > it's not possible to fix it. Plugins shoudl never change uuid of players, the purpose of the uuids is a way to track players, and if they are changed it can cause issues.
> > > You can delete the data of specific players that are glitched.
> > 
> > 
> > I actually have the same issue. Just reported it in. The server is in offline mode due to the usage of Velocity, but I enabled online mode on velocity's side. I can guarantee that the server is still using online uuids. I started using velocity 2 or 3 weeks ago, this never happened before. I also reported this issue in #257
> 
> it's not even the same bug, what are you talking about?
> He can create new islands after he already creates one, your issue is related to upgrades not saved correctly
> totally two different issues that are not related to each other

My bad, thought it was somehow the same issue.

**Comment by exzolink** [comment]
> 
> 
> can u fix it in new version or recommed some plugin UUID hook with SSB2 (im using UUIDSpoof-Fix)? the old version of SSB 2 dont have that problem
> And my 300 players are playing, i cant not reset their the database file

Read info on spigot about this plugin https://www.spigotmc.org/resources/uuidspoof-fix.26948/
