### ISSUE TITLE
Server crashing until you remove "warpCategories/warps" columns

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#259]
**Minecraft's Version**
1.8.8 paper

**Plugin's Version**: -
Latest jenkins "b140"

**Describe the bug**
After a daily restart, the server won't open cause this issue:
https://pastebin.com/DqamCPth

It keeps restarting and it can't be opened until you remove table "warpCategories", "warps" from the database

**To Reproduce**
Don't know how to reproduce it, but I guess it's something with is warps creation "I've categories disabled"

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

**Comment by OmerBenGera** [comment]
Check out latest dev build

**Comment by OmerBenGera** [comment]
Any news regarding this?
