### ISSUE TITLE
Island upgrades aren't saved to database

### ISSUE THREAD

**Issue by ElBananaa** [BG-Software-LLC/SuperiorSkyblock2#260]
**Minecraft's Version**
```
This server is running Purpur version git-Purpur-1111 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1102 (MC: 1.16.5)
```

**Plugin's Version**: -
SSB2 Build 141

**Describe the bug**
Since the latest update, after each server restart, island upgrades aren't saved in the database. Basically, if I upgrade my generator to the lvl3, after a restart, it gets back to the 1st level.

**To Reproduce**
- Upgrade you island with a custom upgrade, restart the server, and the upgrade is gone.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
