### ISSUE TITLE
Command /island admin setupgrade does not work

### ISSUE THREAD

**Issue by nicolo-rancan** [BG-Software-LLC/SuperiorSkyblock2#261]
**Minecraft's Version**
1.16.5 Paper

**Plugin's Version**: -
1.6.0-Dev latest spigot

**Describe the bug**
Command /is admin setupgrade does not work, it returns the available subcommands of /is admin 

![unknown](https://user-images.githubusercontent.com/61580994/118476111-67458800-b70d-11eb-8d21-1b6b7b93ec84.png)

**To Reproduce**
Just installed the plugin. Tested with a configured version and with a blank installation.

**Comment by OmerBenGera** [comment]
/is admin setupgrade is a command, unless ypu have the upgrades module disabled.
