### ISSUE TITLE
Server can't start due to an NPE with latest dev build

### ISSUE THREAD

**Issue by ElBananaa** [BG-Software-LLC/SuperiorSkyblock2#264]
**Minecraft's Version**
```
This server is running Purpur version git-Purpur-1117 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1111 (MC: 1.16.5)
```

**Plugin's Version**: -
SSB2 Build 142 & Build 143

**Describe the bug**
Since the latest update, my server refuses to start, I guess, du to the following NPE : https://paste.gg/p/anonymous/80c1a5428ecc463faff2119496848f1d.
When using Build 141, the server is starting again, without any issues.

**To Reproduce**
- I have no idea at all.

**Comment by JackPlays93** [comment]
Can confirm this is the same for my server.

**Comment by exzolink** [comment]
Same

**Comment by OmerBenGera** [comment]
For now downgrade to another dev build.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by exzolink** [comment]
Yes, the error is gone
