### ISSUE TITLE
Illegal Reflective Error

### ISSUE THREAD

**Issue by HyperSetups** [BG-Software-LLC/SuperiorSkyblock2#266]
**Server Version:**
Hyalus version git-Hyalus-202 (MC: 1.16.5) (Implementing API version 1.16.
5-R0.1-SNAPSHOT)

**Plugins:**
FastAsyncWorldEdit (WorldEdit), NoCheatPlus, ProtocolLib, SlimeWorldManager, SSBSlimeWorldManager, SuperiorSkyblock2

**Plugin Version**:
SuperiorSkyblock2 Build #143

**Description:**
It gives an error on server starting: https://srcb.in/HjEASjlJ11

**Additional Information:**
All configurations are default and fresh. I want to understand what is the problem.

**Comment by OmerBenGera** [comment]
You can ignore it.
