### ISSUE TITLE
Creating Island Makes Lag

### ISSUE THREAD

**Issue by HyperSetups** [BG-Software-LLC/SuperiorSkyblock2#267]
**Server Version:**
Hyalus version git-Hyalus-202 (MC: 1.16.5) (Implementing API version 1.16.
5-R0.1-SNAPSHOT)

**Plugins:**
FastAsyncWorldEdit (WorldEdit), NoCheatPlus, ProtocolLib, SlimeWorldManager, SSBSlimeWorldManager, SuperiorSkyblock2

**Plugin Versions:**
SuperiorSkyblock2 Build #143
SSBSlimeWorldManager 1.5.2 (Fork of Paul19988, Maintainer of Advanced Slime World Manager)

**Description:**
It makes lag when I create an island: https://timings.aikar.co/?id=c0ac0386bfe94fcb89718830fde9712e

**Comment by OmerBenGera** [comment]
Chunk loading is causing lag, nothing to do on the plugin's side.
