### ISSUE TITLE
The worth/level of island alway go down!

### ISSUE THREAD

**Issue by MynamisTG** [BG-Software-LLC/SuperiorSkyblock2#268]
Minecraft's Version
Spigot 1.8.x

Plugin's Version: -
#143

Describe the bug:
Auto decrease worth and level of island 1 minutes
After i used to ./is admin recalc, it will back to correct worth/level but then it will auto decrease again

Additional information
https://gyazo.com/a066496acd707cb2a15fc246c2f9972b

**Comment by OmerBenGera** [comment]
It means that blocks are broken... you can use `/is admin debug Action: Block Break, Island: <island-owmer>` to find out what causes it and adjust your configs so it wont happen.
