### ISSUE TITLE
Please add My_Worlds to the loadBefore list

### ISSUE THREAD

**Issue by MinexusNetwork** [BG-Software-LLC/SuperiorSkyblock2#269]
**Minecraft's Version**
Latest (at the time)

**Plugin's Version**: -
Latest (at the time)

**Describe the bug**
I attempted to switch from Iridium to Superior last month and was extremely unsuccessful. I believe the issue was due to Superior wanting to load worlds before My_Worlds (my world management plugin of choice) and if this condition was not met, the server would enter an endless crash cycle.

**To Reproduce**
Install My_Worlds and SuperiorSkyblock2 and start the server, once loaded, restart the server.

**Additional information**
I spent a couple days narrowing down the issue to this incompatibility, I contacted the dev for My_Worlds and they explained the cause to me. I am now reaching out to you guys to add My_Worlds to the loadBefore list.

You can view the discussion here: https://pastebin.com/SfsUKuii

**Comment by OmerBenGera** [comment]
Hey, thanks for letting me know about the issue.
It's fixed in latest dev build.
Next time, after you report the issue, you can just edit the plugin.yml of the plugin yourself so you have a temp fix for the issue :)
