### ISSUE TITLE
light update problem

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#273]
**Minecraft's Version**
Yatopia-1.16.5

**Plugin's Version**: -
Dev-build 141

**Describe the bug**
Light doesn't update on island creation

**To Reproduce**
Just create an island, and check the light sources

**Additional information**
I don't use FAWE,
I enabled 
# Should lights get updated when pasting schematics?
# Enabling this can drop performance a bit.
lights-update: true

![Screenshot_3794](https://user-images.githubusercontent.com/31826333/119198921-72404580-ba8a-11eb-96cd-e993b91edb73.png)

**Comment by OmerBenGera** [comment]
Make sure that when you create your schematic, the lights are updated correctly, as the schematic saves the lights of the blocks, and then applies them to the world

**Comment by OmerBenGera** [comment]
Seems to not work for me as well, gonna check that out

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
