### ISSUE TITLE
Engine Bugs

### ISSUE THREAD

**Issue by Dqgs** [BG-Software-LLC/SuperiorSkyblock2#276]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.16.5
**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
b152
**Describe the bug**
Bunch of errors for all engines

Rino: https://mcpaste.io/f45640011130008b
Nashron: https://mcpaste.io/1de25ad983725679
GraalVM: https://mcpaste.io/74014a61196820e3
**To Reproduce**
Steps to reproduce the bug.
Just Upgraded from 1.12 to 1.16

![image](https://user-images.githubusercontent.com/52899751/119238326-e113b200-bb0f-11eb-9f81-fb0c8e20406a.png)
That is all my plugins 

Here is the full list of the logs https://mcpaste.io/e09d1eebd1b16c56
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

**Comment by OmerBenGera** [comment]
What's the java version that you use btw?

**Comment by Dqgs** [comment]
15 i think how do i check

**Comment by OmerBenGera** [comment]
> 
> 
> 15 i think how do i check

Open cmd/terminal and run java -version

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it will work (use Nashorn/Rhino, not GraalVM)

**Comment by Dqgs** [comment]
![image](https://user-images.githubusercontent.com/52899751/119238768-97789680-bb12-11eb-80d3-db5923574318.png)
it says that is my java version but i don't think 1.16 will even run unless you are in java 11 or above. Im running with it through intellij and its 15. Also still getting errors https://mcpaste.io/ea4697a7da2d4ea9 even with the new build

**Comment by OmerBenGera** [comment]
If you were using java 8, you could use the default plugin without any issues regarding the Javascript engine.

**Comment by Dqgs** [comment]
What do you mean by default plugin?

**Comment by OmerBenGera** [comment]
Send me the entire logs file please (you can find it in the logs folder, file called "latest.log") - upload it to pastebin

**Comment by OmerBenGera** [comment]
> 
> 
> What do you mean by default plugin?

I meant that you wouldn't have to use any modules to get it working

**Comment by Dqgs** [comment]
https://mcpaste.io/86eddc8e3f04d742 That is the full logs and i already tried that https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/274

**Comment by OmerBenGera** [comment]
you're using java11, which means that the default javascript engine will work.
I am not sure why it doesn't work on your machine, or why my fix doesn't work as well
Also, another weird thing is that java -version shows one version, but your server is running on another version of Java

Too many weird things are happening here, and I suspect that it has nothing to do with the plugin but something with your machine.

**Comment by Dqgs** [comment]
I mean i could give you all the files to my server if you wanna try it yourself to see if there is a issue for you

**Comment by OmerBenGera** [comment]
This has nothing to do with the server, as I said - it's probably something with the machine you run your server on.

**Comment by Dqgs** [comment]
Then do you got any idea how i could fix this?

**Comment by OmerBenGera** [comment]
> 
> 
> Then do you got any idea how i could fix this?

No, as it's something bugged with your java.

**Comment by OmerBenGera** [comment]
Try reinstalling java and it's jdk, maybe it will help

**Comment by Dqgs** [comment]
Reinstalled java when i do java -version now 
![image](https://user-images.githubusercontent.com/52899751/119239939-9ea3a280-bb1a-11eb-810e-c498996a2ed0.png)
I still got the same error and when i removed it still getting errors. Which is really weird

**Comment by Dqgs** [comment]
https://mcpaste.io/4592b8dd80931e11 That is the logs without Rhino

https://mcpaste.io/5efa0279a0d494e0 Full log with Rhino

**Comment by OmerBenGera** [comment]
I really don't know what's wrong with your machine and why it doesn't work, it works fine for everyone else.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed
If the issue persists, make sure you let me know here
