### ISSUE TITLE
Error when a player join the server

### ISSUE THREAD

**Issue by SharkblackFr** [BG-Software-LLC/SuperiorSkyblock2#278]
Hello, 
every time a player joins I have this error 
[Error](https://paste.gg/p/anonymous/573006e1a4ad4d3ba06ad4b5e36acd6b) , 
even if i also put SkinsRestorer in the plugins folder (I use it in bungeecord, but i also have the jar on the bukkit server)

**Comment by OmerBenGera** [comment]
Duplicate of #154 
Sadly, there's nothing to do on my end, the issue is with how SkinsRestorer works when it's on Bungee.
