### ISSUE TITLE
Placeholders for items mission

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/SuperiorSkyblock2#280]
**Minecraft's Version**
_The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)_
Purpur 1.16.5 build 1086

**Plugin's Version**: -
_The version of the plugin. If you use a dev build, mention which dev build you use._
SuperiorSkyblock build 133

**Describe the bug**
_A clear and concise description of what the bug is._
To be totally honest I'm not fully sure if this is a bug or not but whenever you try to use {value_<block>} for a placeholder in an items quest it doesn't work and just displays the placeholder. So if you have multiple items in a quest and you want to track each one the placeholder doesn't work and of course using {1} only works for the first objective and not the rest. 

**To Reproduce**
_Steps to reproduce the bug._
1. Create an ItemsMissions mission
2. Assign multiple item requirements
3. Try using placeholder {value_<block>} to track each items progress
4. Once the mission is fully setup, load it up and check out the quest, it will display the placeholder instead of the value.

**Additional information**
_Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome._
https://i.imgur.com/UJ1LuLn.png - Screenshot of an itemsmissions quest using the placeholders
Let me know if there's anything else you need and I'll try to get it, we're trying to reformat our quests but unfortunately the new format doesn't really work well when some of the quests can't use the placeholders. (Example of the new format we're looking into using: https://i.imgur.com/IFV6xx9.png)

**Comment by OmerBenGera** [comment]
The ItemsMissions doesn't have such thing, sorry.
You can use BlocksMissions instead.
