### ISSUE TITLE
IslandCreateEvent triggering double times

### ISSUE THREAD

**Issue by Obliviated** [BG-Software-LLC/SuperiorSkyblock2#284]
**Minecraft's Version**
PaperSpigot 1.8.8 4c7641d

**Plugin's Version**: -
1.6.0-DEV b156

**Describe the bug**
IslandCreateEvent triggering double times when any player create an island.

**To Reproduce**
I listening this event using a skript. (it isn't a skript bug im sure.)
https://pastebin.ubuntu.com/p/j7pxVjvR39/

**Additional information**
result of the skript code.
![image](https://user-images.githubusercontent.com/36128276/120083302-71359680-c0d0-11eb-9a8b-e29dd6e6d7a5.png)

this is not a skript bug.

**Comment by OmerBenGera** [comment]
It's called only once, probably a bug with skript.
I don't know why it happens with Skript, but when I tried it in Java it worked just fine.
