### ISSUE TITLE
Nether Generator SuperiorSkyblock

### ISSUE THREAD

**Issue by Faobi69** [BG-Software-LLC/SuperiorSkyblock2#286]
**Minecraft's Version**
Paper 1.16.5

**Plugin's Version**: -
1.6.0-Dev

**Describe the bug**
Hello sorry for the inconvenience I have also encountered a problem with the nether generator, unfortunately the custom generators only work in the normal island or in the end but not in the nether, can you check please? thank you

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
  # A list of default generator percentages for new islands.
  # Example: 'DIAMOND_BLOCK:50' will set 50% chance for diamond block.
  # You can find a list of materials here: https://bg-software.com/materials/
  generator:
    normal:
    - COBBLESTONE:5
    - COAL_ORE:10
    - DIAMOND_ORE:85
    nether:
    - COBBLESTONE:5
    - COAL_ORE:10
    - GOLD_ORE:85
    the_end:
    - COBBLESTONE:5
    - COAL_ORE:10
    - EMERALD_ORE:85

**Comment by OmerBenGera** [comment]
Unless you dont have a plugin that lets you place water, it will not work, thats how the nether works
