### ISSUE TITLE
Farmer NPC are dropping/duplicating Seeds and Wheat like crazy each second in some instance

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#288]
**Minecraft's Version**
Paper 1.16.5 (latest dev build)

**Plugin's Version**: -
Dev build 156

**Describe the bug**
Farmer Villager are dropping thousands of seeds and wheat on the ground each second.
![2021-06-01_23 50 27](https://user-images.githubusercontent.com/25954399/120541276-f929e200-c3e9-11eb-87d2-64b09b0bdaf5.png)
![2021-06-02_00 08 39](https://user-images.githubusercontent.com/25954399/120541288-fb8c3c00-c3e9-11eb-8b0e-fc642fcd03c2.png)

**To Reproduce**
Upgrade your island's crop growth (For example level 3/4 of the base config). Place Villagers near a farm and some composters for it to be even more effective I think it's even better to place less composters than Villagers so that some Villagers are still without a job.

**Additional information**
I removed **ALL** my plugins except SuperiorSkyblock2 and the problem is still there. That's why I'm sure it's coming from this plugin in a way or an other.

**Comment by OmerBenGera** [comment]
Send here a link to the plugin of the NPCs.
If its a paid one, ask the mods to open a ticket for you so you can send a copy of it there.
(You can show them my message here)

**Comment by OmerBenGera** [comment]
Send here a link to the plugin of the NPCs.
If its a paid one, ask the mods to open a ticket for you so you can send a copy of it there.
(You can show them my message here)

**Comment by banicola** [comment]
> Send here a link to the plugin of the NPCs.
> If its a paid one, ask the mods to open a ticket for you so you can send a copy of it there.
> (You can show them my message here)

Sorry I used the wrong word, I should have use Villager instead of NPC. It's the default one no plugin used.

**Comment by banicola** [comment]
I copied the island world on a server without superiorskyblock2 to have the same farm setup and there's not the issue from what I see

**Comment by banicola** [comment]
You might need to have more than 20 villagers in your farm. Removing the composters seems to help to remove the drops, at least in the most part.

**Comment by OmerBenGera** [comment]
I forgot to update you, but I couldn't replicate the issue
