### ISSUE TITLE
Reading of the variable

### ISSUE THREAD

**Issue by nejmik242** [BG-Software-LLC/SuperiorSkyblock2#291]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)

**Plugin's Version**: -

SuperiorSkyblock2-b157

**Describe the bug**
Screenshot: https://imgur.com/a/wngouqJ

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
This bug is in the /is bank command

**Comment by OmerBenGera** [comment]
Install PlaceholderAPI.
You can't use papi placeholders when you don't have it installed
