### ISSUE TITLE
Schematic bug 1.16

### ISSUE THREAD

**Issue by AirCraze** [BG-Software-LLC/SuperiorSkyblock2#294]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.16 paper
**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
Latest (not dev build)
**Describe the bug**
I am running 1.16 (latest) paper.

I have a new schematic file (with a sign). When typing /is create <name>
And selecting the block that creates the island I chose. I got this error: https://pastebin.com/PnkFT9PY

In-game error states:
`An error occurred while creating your island. Please contact a staff member to investigate the issue.`
**To Reproduce**
Steps to reproduce the bug.
 https://pastebin.com/PnkFT9PY
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

**Comment by OmerBenGera** [comment]
Use latest dev build. If it still occurs, send a new stack trace from this version

**Comment by AirCraze** [comment]
Worked. However, this time. I got a new issue with no warning or error in console!

I created a new island. However, it didn't spawn me where I put the spawn point by schematic. It spawned me somewhere else.

**Comment by AirCraze** [comment]
Another issue, I have currently found is the title. "&k" and "&n" does not want to work!

**Comment by OmerBenGera** [comment]
> Worked. However, this time. I got a new issue with no warning or error in console!
> 
> I created a new island. However, it didn't spawn me where I put the spawn point by schematic. It spawned me somewhere else.

Thats probably because of a delay in the placement of the schematic, caused the plugin to look for another place to spawn you

**Comment by OmerBenGera** [comment]
> Another issue, I have currently found a issue with BIOME MENU. The nether block doesn't appear on the screen. No errors in console about this

Probably because of incorrect usage of the block material / nether biome name. Can be fixed by updating the menu file

**Comment by OmerBenGera** [comment]
Anyways, I am closing this for the time being :)
