### ISSUE TITLE
Withdraw issue

### ISSUE THREAD

**Issue by Faceless0102** [BG-Software-LLC/SuperiorSkyblock2#295]
**Minecraft's Version**
1.12.2

**Plugin's Version**: -
1.6.0-Dev

**Describe the bug**
So if you use CMI (not essentials) and withdraw all the money from the bank while having the maximum balance limit by CMI, you lose that money and no warning messages at all.

**Comment by OmerBenGera** [comment]
I'll need a copy of CMI to check this out.
What is your discord? I will open a ticket for you so you can send a copy there.

**Comment by OmerBenGera** [comment]
I received a copy of the latest version of CMI, and it worked fine for me.

**Comment by OmerBenGera** [comment]
I found an issue with losing money when depositing money to banks that after the transaction they exceed the bank limit.
It should be fixed, so let me know if it fixes your issue as well

**Comment by nivcoo** [comment]
Hello i think you have created issue with this fix : https://pics.revolis.fr/2021-06/13/13-59_PrNG.png after the restart i've this deposit from console with 10 percent of bank value

**Comment by nivcoo** [comment]
And after all restart of my server i've this deposit https://pics.revolis.fr/2021-06/13/14-03_5qBx.png

**Comment by OmerBenGera** [comment]
> Hello i think you have created issue with this fix : https://pics.revolis.fr/2021-06/13/13-59_PrNG.png after the restart i've this deposit from console with 10 percent of bank value

Thats the bank interest.

**Comment by nivcoo** [comment]
Ok i saw the issue, it's because you have migrate the bank file so it set "enabled: true". It's good thx
