### ISSUE TITLE
Suggestion, not an isssue.

### ISSUE THREAD

**Issue by PedroMPagani** [BG-Software-LLC/SuperiorSkyblock2#296]
Instead of pasting schematics for every island(When in usage of SWM), you might want to have an pattern world file with the schematic already done, then you just copy the propperties using the propper SWM api which can be "copied" of cloneWorld command, it will prevent from lagging the server everytime when generating an new island, i've heard that on ASWM discord and I am here to suggest, if needed i can help with it.
This will prevent the TPS from going down a lot.

**Comment by OmerBenGera** [comment]
This is not related to SSB. You are more than welcome to make a PR for SWM for that tho
