### ISSUE TITLE
Error appears when I create island [1.17]

### ISSUE THREAD

**Issue by LeAnhTuan0810** [BG-Software-LLC/SuperiorSkyblock2#298]
https://sourceb.in/kP8yftyz8A

**Comment by OmerBenGera** [comment]
Try updating both Spigot and SSB, as I can't seem to replicate the issue

**Comment by OmerBenGera** [comment]
I managed to replicate the issue.

**Comment by OmerBenGera** [comment]
Try latest dev build, I think it's fixed in this version

**Comment by LeAnhTuan0810** [comment]
ok it's fixed

**Comment by LeAnhTuan0810** [comment]
https://sourceb.in/DTlqfVEnzo

sorry, it throws the error again (1.17)

**Comment by LeAnhTuan0810** [comment]
I use version 1.7.0 on spigot

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build (176)
Let me know if it works for you

**Comment by OmerBenGera** [comment]
The issue seems to be fixed, so I am closing this issue for now.
If it still occurs, feel free to reopen the issue :)
