### ISSUE TITLE
Island upgrade has been reset when upgrades config has been misconfigured

### ISSUE THREAD

**Issue by Peeraboon** [BG-Software-LLC/SuperiorSkyblock2#299]
**Minecraft's Version**
This server is running Purpur version git-Purpur-1169 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Plugin's Version**: -
SuperiorSkyblock2 version 1.6.0-DEVb160

**Describe the bug**
When the modules/upgrades/config.yml is misconfigured, the player island upgrade will be reset when join the server(but player who not join during misconfigured upgrade config will not be reset)

**To Reproduce**
Upgrade the island upgrade then
misconfig the modules/upgrades/config.yml file and join the server.

**Additional information**
modules/upgrades/config.yml file that I'm using: https://pastebin.com/DaJ2VLkQ

file that i got error and island upgrade has been reset: https://pastebin.com/RKkx572Y

I just want to add spawner block limit upgrade.

**Comment by OmerBenGera** [comment]
I don't quite understand the issue

**Comment by Peeraboon** [comment]
> I don't quite understand the issue

For example,
B has a border-size upgrade level 3
when I config the module/upgrades/config.yml wrong in SuperiorSkyblock2. border-size of player B will be reset to 1.

**Comment by OmerBenGera** [comment]
> 
> 
> > I don't quite understand the issue
> 
> For example,
> B has a border-size upgrade level 3
> when I config the module/upgrades/config.yml wrong in SuperiorSkyblock2. border-size of player B will be reset to 1.

Maybe the upgrade is not loaded?

**Comment by Peeraboon** [comment]
> > > I don't quite understand the issue
> > 
> > 
> > For example,
> > B has a border-size upgrade level 3
> > when I config the module/upgrades/config.yml wrong in SuperiorSkyblock2. border-size of player B will be reset to 1.
> 
> Maybe the upgrade is not loaded?

Not sure but the problem is when I undo the config file to the correct one. The player upgrade are still 1 not change back to 3 and players who join during wrong config have to upgrade it again

**Comment by OmerBenGera** [comment]
> 
> 
> > > > I don't quite understand the issue
> > > 
> > > 
> > > For example,
> > > B has a border-size upgrade level 3
> > > when I config the module/upgrades/config.yml wrong in SuperiorSkyblock2. border-size of player B will be reset to 1.
> > 
> > 
> > Maybe the upgrade is not loaded?
> 
> Not sure but the problem is when I undo the config file to the correct one. The player upgrade are still 1 not change back to 3 and players who join during wrong config have to upgrade it again

As I said, if the config fails to load and the upgrades don't load, when you save the game the islands will not have the upgrades anymore
You should not change the config as it can break, and if you do - at least do it on a testing server before uploading to production.

**Comment by Peeraboon** [comment]
> > > > > I don't quite understand the issue
> > > > 
> > > > 
> > > > For example,
> > > > B has a border-size upgrade level 3
> > > > when I config the module/upgrades/config.yml wrong in SuperiorSkyblock2. border-size of player B will be reset to 1.
> > > 
> > > 
> > > Maybe the upgrade is not loaded?
> > 
> > 
> > Not sure but the problem is when I undo the config file to the correct one. The player upgrade are still 1 not change back to 3 and players who join during wrong config have to upgrade it again
> 
> As I said, if the config fails to load and the upgrades don't load, when you save the game the islands will not have the upgrades anymore
> You should not change the config as it can break, and if you do - at least do it on a testing server before uploading to production.

Okay thank you. understood now

**Comment by OmerBenGera** [comment]
I will look if this can be changed so at least the progress will be saved.

**Comment by OmerBenGera** [comment]
Fixed in dev build 177
