### ISSUE TITLE
Island is not there after creating it in 1.8 with FAWE

### ISSUE THREAD

**Issue by MedicOP** [BG-Software-LLC/SuperiorSkyblock2#300]
**Minecraft's Version**
Spigot 1.8

**Plugin's Version**: -
Latest dev build
Latest 1.8 compatible FAWE build

**Describe the bug**
After typing /is and selecting a schematic, you get warped to your island. The blocks are visible but they're not actually there, as soon as you click any block or re-log, they disappear.

**To Reproduce**
After creating the island and warping the player, IslandUtils.resetChunksExcludedFromList is called which calls NMSBlocks.deleteChunk which empties the entire chunk. WorldEditSchematic.getLoadedChunks() just returns an empty set. I don't get it?

**Additional information**

**Comment by OmerBenGera** [comment]
Dont use FAWE for creating islands, and update your server to at least 1.8.8
