### ISSUE TITLE
SkinRestorer hook error

### ISSUE THREAD

**Issue by Obliviated** [BG-Software-LLC/SuperiorSkyblock2#305]
**Minecraft's Version**
PaperSpigot-"4c7641d" (MC: 1.8.8)

**Plugin's Version**: -
1.6.0-dev b160

**Describe the bug**
The plugin prints error about SkinRestorer API.

**To Reproduce**
use latest skin restorer version and latest superior skyblock

**Additional information**
error log: https://pastebin.ubuntu.com/p/rfxYQYVBZS/

**Comment by WolverStones** [comment]
#100

**Comment by WolverStones** [comment]
#293 etc This has been addressed several times.

**Comment by Obliviated** [comment]
i just wanna a kind of disable button.
