### ISSUE TITLE
Full log. (new skyblock plugin update issue)

### ISSUE THREAD

**Issue by AirCraze** [BG-Software-LLC/SuperiorSkyblock2#306]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.16 Paper
**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
b166 (latest)
**Describe the bug**
Unable to enable the plugin without having error spam
**To Reproduce**
Steps to reproduce the bug.
1. Legit just put it in your plugins folder
**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
https://pastebin.com/tpmbD5yG

**Comment by ElBananaa** [comment]
Hey!
I can confirm I could reproduce this issue under both Purpur 1.16.5 & Spigot 1.17.
Both were running under a completely fresh install, and OpenJDK 16.0.1.
The error appears to be the same one in both cases : https://paste.gg/p/anonymous/5cac647e3db8433f865889eac8356448

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
