### ISSUE TITLE
SuperiorSkyblock2 Spawner Value Broken

### ISSUE THREAD

**Issue by DJDan21** [BG-Software-LLC/SuperiorSkyblock2#310]
**Minecraft's Version**
Paper-778 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugin's Version**: -
SuperiorSkyblock2-b161.jar

**Describe the bug**
Spawners not showing any value on island top

**To Reproduce**
1. Enabled wildstacker hook in its config using build 137 of wildstacker
2. Followed correct format of spawner value in levels.yml
3. Create an island
4. Place iron golem spawner down 
5. Check /is top on your island

**Additional information**
Current WildStacker Config https://pastebin.com/HTZpRAbG
Current levels.yml https://pastebin.com/hkE6vCL7
Current SuperiorSkyblock Config: https://pastebin.com/4YspygA1

**Comment by OmerBenGera** [comment]
In 1.16.5, the block type of spawner is "SPAWNER" and not "MOB_SPAWNER"
Make sure you test your blocks using this site: https://bg-software.com/materials/
