### ISSUE TITLE
/Island level and other commands used to calculate the level or the worth of an island reset these values

### ISSUE THREAD

**Issue by ElBananaa** [BG-Software-LLC/SuperiorSkyblock2#311]
**Minecraft's Version**
```
This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Purpur-1169 (MC: 1.16.5)
```

**Plugin's Version**
SuperiorSkyblock2 b169

**Describe the bug**
Basically, each time a player uses the `/is level` command, his island level is set to 0 for an unknown reason, even tho he has a lot of valuable blocks on his island.

**To Reproduce**
I don't know, I guess it's somehow related to the plugin version since this wasn't happening before.

**Additional information**
Both the nether and the overworld are enabled. And both have their schematic-offset option set to true. There's no bonus defined in the island creation menu, and the nether isn't unlocked by default. The server runs under OpenJDK 16.0.1.

Here are two screens, one before placing valuable blocks, and the same screen right after placing valuable blocks on the island.
![2021-06-21_01 06 14](https://user-images.githubusercontent.com/53318613/122691108-c8d9a480-d22d-11eb-81ad-95e4539efb11.png)
![2021-06-21_01 07 30](https://user-images.githubusercontent.com/53318613/122691110-cb3bfe80-d22d-11eb-90f5-ee23cfbf71a5.png)

I also noticed another error that seems to appears randomly. Idk if I should open another issue for it since I have no infos about it, so here it is https://paste.gg/p/anonymous/d3fb2dc298dc4d27b3f28863cd29ce09

**Comment by WarnDangerous** [comment]
I can confirm that, I tried default config on latest dev build, graalvm-16 with rhino engine and nashorn engine, my island level is 0 when doing /is recalc

**Comment by banicola** [comment]
I can confirm the same behaviour. I did a /is admin recalc and all island has seen there level drop significantly, some islands dropped to 0 level.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
