### ISSUE TITLE
Build 169 not working coming from 130, infinite restart loop (already downloaded Nashorn jar)

### ISSUE THREAD

**Issue by Kamology** [BG-Software-LLC/SuperiorSkyblock2#312]
**Minecraft's Version**
Paper 1.16.5 build ~750

**Plugin's Version**: -
b169

**Describe the bug**
So, I was initially on build 130, and went to upgrade, only to realize I was met with an infinite crash and restart loop. I was about to submit a report, checked the log, only to realize it said I needed to download the Nashorn jar. I am indeed on Java 16, so I did that, tried again, met with the same result, just with a more generic crash vs the specific Nashorn warning. I've included the logs of a normal build 130 startup log, vs the current 169 startup log.

**To Reproduce**
Be on build 130 and upgrade to 169

**Additional information**
[b130.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6686314/b130.log)
[b169.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6686315/b169.log)

**Comment by Kamology** [comment]
Alright, after much hair pulling, an extremely observant person on the Discord pointed out it may be Geyser causing the issue, as hinted to by the `[SuperiorSkyblock2] Loaded class org.objectweb.asm.Type from Geyser-Spigot v1.4.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.` message. I almost scoffed at this initially because errors like that pop up all the time, but sure enough, disabling Geyser fixes this. I'm not really sure who's end it's on to fix this, so I'll leave this open until a response, and go let the people over there know if it's on them.

**Comment by OmerBenGera** [comment]
> Alright, after much hair pulling, an extremely observant person on the Discord pointed out it may be Geyser causing the issue, as hinted to by the `[SuperiorSkyblock2] Loaded class org.objectweb.asm.Type from Geyser-Spigot v1.4.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.` message. I almost scoffed at this initially because errors like that pop up all the time, but sure enough, disabling Geyser fixes this. I'm not really sure who's end it's on to fix this, so I'll leave this open until a response, and go let the people over there know if it's on them.

Hmm interesting. Does it still occur if you only leave Geyser installed, or it only happens when both plugins are installed?
Also, what Geyser is exactly, and why is it interacting with ASM?

**Comment by Kamology** [comment]
> > Alright, after much hair pulling, an extremely observant person on the Discord pointed out it may be Geyser causing the issue, as hinted to by the `[SuperiorSkyblock2] Loaded class org.objectweb.asm.Type from Geyser-Spigot v1.4.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.` message. I almost scoffed at this initially because errors like that pop up all the time, but sure enough, disabling Geyser fixes this. I'm not really sure who's end it's on to fix this, so I'll leave this open until a response, and go let the people over there know if it's on them.
> 
> Hmm interesting. Does it still occur if you only leave Geyser installed, or it only happens when both plugins are installed?
> Also, what Geyser is exactly, and why is it interacting with ASM?

It's only when both are installed. As to what Geyser is; black magic is really the best way I can describe it. Essentially is a translation layer for Bedrock -> Java. Blows my mind it's able to work. https://geysermc.org/

Also, I don't even know what ASM is so I can't help much with that question lol

**Comment by DuneSciFye** [comment]
Hello, I also have this problem. Everything is the same except I'm on 1.17, and the errors are the same. When I removed Geyser however, it worked without any errors and ran fine.

**Comment by OmerBenGera** [comment]
Contact the developer of Geyser.
I will keep this opened if there are any quesrions, but I dont see how I can really fix it unless he tells me what to do

**Comment by Camotoy** [comment]
Hi! We just fixed this on our end. From what I understand, it's always a good idea to relocate your dependencies in the event that other plugins also use them. I would recommend implementing a similar fix to what we did in the event another plugin forgets to relocate, but this issue can be considered closed as this plugin will no longer cause an issue with Geyser.

**Comment by OmerBenGera** [comment]
> 
> 
> Hi! We just fixed this on our end. From what I understand, it's always a good idea to relocate your dependencies in the event that other plugins also use them. I would recommend implementing a similar fix to what we did in the event another plugin forgets to relocate, but this issue can be considered closed as this plugin will no longer cause an issue with Geyser.

I don't understand what you mean by that..
