### ISSUE TITLE
Not working for 1.17, requires Java 16

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#314]
**Minecraft's Version**
PaperMC 1.17

**Plugin's Version**: -
Version 1.7.0

**Describe the bug**
I recently tried updating my server to 1.17, got the server.jar, and the plugins, and when starting the server after updating this plugin to latest stable version, it gave me multiple errors in the console.  I've attached the 2 messages in text files. I posted it in the discord support channel and I was told that the plugin doesn't support Java 16.

**To Reproduce**
Use PaperMC 1.17 as server.jar and use Latest Stable Release

**Additional information**
[error1.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6689986/error1.txt)
[error2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6689987/error2.txt)

**Comment by WolverStones** [comment]
Try use dev builds https://hub.bg-software.com/job/SuperiorSkyblock2/

**Comment by DuneSciFye** [comment]
I used the latest build, 166, still didn't work. Same errors

**Comment by OmerBenGera** [comment]
Install the jar that it tells you to install.
There are clear instructions with what to do.

**Comment by DuneSciFye** [comment]
Hello, I installed the SuperiorSkyblock2-NashornEngine.jar latest release from https://github.com/BG-Software-LLC/SuperiorSkyblock2-NashornEngine/releases/tag/1.0.2 and put it in the modules folder using the latest dev build, 169. It still gave me the following errors: 
[error1.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6694973/error1.txt)
[error2.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6694979/error2.txt)

**Comment by OmerBenGera** [comment]
This seems like an error with Nashron and your Java version. Try googling about the error and find a solution.

**Comment by DuneSciFye** [comment]
This has been fixed by Geyser. The error was made by installing both Geyser and SuperiorSkyblock2. Geyser has fixed it on their side so it no longer causes an issue. I think it is safe to close this issue along with the infinite restart loop issue as that is the same issue as this one.

**Comment by Skizzles** [comment]
Confirmed resolved with person reporting. Closed
