### ISSUE TITLE
top islands placeholders are broken until a player performs /island top

### ISSUE THREAD

**Issue by castiel01x** [BG-Software-LLC/SuperiorSkyblock2#317]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.8.8 Paper (latest build)

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
v1.7.0

**Describe the bug**
%superior_island_top_level_value_<#>%,  %superior_island_top_level_leader_<#>% placeholders return incorrect values until
a player performs /is top command

**To Reproduce**
Steps to reproduce the bug.
have multiple islands that have value, restart the server & then see what value the placeholder (%superior_island_top_level_leader_1%) return, if it doesn't return the top 1 island leader then try /is top then see what the placeholder returns again

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

https://gyazo.com/ca15076385201eac1a26b005b7d8876f

**Comment by OmerBenGera** [comment]
This is an intended behavior. You are more than welcome to make the islands get sorted more often, however this can result lag.
