### ISSUE TITLE
Can't use nametags on islands if you are not the owner

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#318]
**Minecraft's Version**
Tuinity 1.16.5

**Plugin's Version**: -
Dev build 169

**Describe the bug**
When you tried to use a nametag on an entity but you are not the island owner it says: "This island is protected".

**To Reproduce**
Join an island and use any rank (except owner). Try to click with a nametag on an entity. You should then get "This island is protected" error.

**Additional informations**
There's no permission in the permission menu to change this behaviour, it might be needed.

**Comment by OmerBenGera** [comment]
Add "NAME_ENTITY" to the default role permissions, and the island owners should add that aswell to their members.
I will also add this to the default config so there's no confusion.
