### ISSUE TITLE
Players cannot create an island 

### ISSUE THREAD

**Issue by Zepyxll** [BG-Software-LLC/SuperiorSkyblock2#322]
**Minecraft's Version**
tuinity-paperclip.jar
1.16.5

**Plugin's Version**: -
1.7.0

**Describe the bug**
Cannot create an island/cell have tried re-generating the config file and attempted to make an island/cell with the default schematics however had the same result. Also there are no errors in console, and the issues only happens on our main server and not our dev server.

**To Reproduce**

**Additional information**

https://i.gyazo.com/thumb/1200/44a0a310ef4176ebb00e15275800fa44-png.jpg << When creating an island/cell

**Comment by OmerBenGera** [comment]
Are there any errors in console?

**Comment by Skizzles** [comment]
Tested this on dev build 173 and receive:
https://pastebin.com/45jFQW4P

**Comment by Skizzles** [comment]
On dev build 175 it creates however the server seems to run out of memory or something after this task?

[13:17:32 INFO]: KenwaysJackdaw issued server command: /is
[13:17:33 INFO]: You have given starter to KenwaysJackdaw
>....[141.875s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[141.889s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[13:17:34 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
[13:17:34 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
[13:17:34 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
[13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
[13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
[13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[13:17:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by MassiveLag** [comment]
> On dev build 175 it creates however the server seems to run out of memory or something after this task?
> 
> [13:17:32 INFO]: KenwaysJackdaw issued server command: /is
> [13:17:33 INFO]: You have given starter to KenwaysJackdaw
> 
> > ....[141.875s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
> > [141.889s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
> > [13:17:34 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
> > [13:17:34 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
> > [13:17:34 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> > [13:17:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> 
> Odd as server continues normal function though.

What happens is that ssb2 is trying to teleport the player while it's not pasted the schematic yet

**Comment by OmerBenGera** [comment]
> 
> 
> On dev build 175 it creates however the server seems to run out of memory or something after this task?
> 
> [13:17:32 INFO]: KenwaysJackdaw issued server command: /is
> [13:17:33 INFO]: You have given starter to KenwaysJackdaw
> 
> > ....[141.875s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
> > [141.889s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
> > [13:17:34 WARN]: Exception in thread "Craft Async Scheduler Management Thread" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
> > [13:17:34 WARN]:        at java.base/java.lang.Thread.start0(Native Method)
> > [13:17:34 WARN]:        at java.base/java.lang.Thread.start(Thread.java:800)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:939)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1007)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
> > [13:17:34 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> > [13:17:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> 
> Odd as server continues normal function though.

Your server ran out of memory, simple as that.
Give more ram to your server

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build (176)
Let me know if it works for you

**Comment by OmerBenGera** [comment]
The issue seems to be fixed, so I am closing this issue for now.
If it still occurs, feel free to reopen the issue :)
