### ISSUE TITLE
Colorchat do not apply in island chat

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#328]
**Minecraft's Version**
Airplane 1.16.5

**Plugin's Version**: -
Superior 173

**Describe the bug**
I use "ChatControl Red" for my chatcolor system, so player get a chat color in the chat, but in "/is chat" they do not get this color.

**Additional information**
I'm using ChatControl red 10.4.9
I can send you in private the .jar so you can get into the API because as written on 
https://github.com/kangarko/ChatControl-Red/wiki/API

You need to .jar to get the API inside.

(I don't use the "channel system" from chatcontrolred, so maybe it will change something for your hook, I don't know)

**Comment by Skizzles** [comment]
Confirmed this, standard color codes work but not the chc menu selection:
https://screenshots.skizzles.me/wAnA3/Talemipo00.mp4

Unsure if this is CHC or SSB problem.

**Comment by OmerBenGera** [comment]
@kangarko, mind helping me with that?
How can I add support for the colors feature? The code of the island team chat can be found here:
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/src/main/java/com/bgsoftware/superiorskyblock/listeners/PlayersListener.java#L372

**Comment by OmerBenGera** [comment]
Try changing the priority of the chat listener in your ChatControl's config from HIGH to LOW or LOWEST, both should work.
NORMAL might work as well, not sure about that tho.

I am closing this issue for now
