### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#329]
**Minecraft's Version**
Airplane 1.16.5

**Plugin's Version**: -
Superior b172

**Describe the bug**
I got this error in console on plugin disable :
https://pastebin.com/cUu7QLL4

I'm using Graalvm EE 21.1.0 Java 16

**Comment by OmerBenGera** [comment]
Check out b173, I think its already fixed

**Comment by WarnDangerous** [comment]
Still the same error in 173
https://pastebin.com/Gvz6vHYC

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
