### ISSUE TITLE
Is admin disband error

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#330]
**Minecraft's Version**
1.17 Purpur 1229

**Plugin's Version**: -
SuperiorSkyblock dev 173

**Describe the bug**
Is admin disband throws an error, also it forces the user who issuing the command to have their chat no longer work (Possibly similar to when island disband sent user into the void), island is still there and does not actually disband. Error is thrown below.

**To Reproduce**
/is admin disband an island and you can see this issue occurring.

**Additional information**
Error:
https://pastebin.com/zbakQ0qH

Clip:
https://screenshots.skizzles.me/wAnA3/PoGexePI80.mp4

**Comment by Skizzles** [comment]
Also occurs with normal disband, essentially nuking anyone who is not a member:

Screenshot showing similar situation when I am standing on the island:
https://screenshots.skizzles.me/wAnA3/TIroXolo57.png

Error:
https://pastebin.com/5EXDHW7Q

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Skizzles** [comment]
@OmerBenGera This resolves both disband types.
