### ISSUE TITLE
Island level error

### ISSUE THREAD

**Issue by Aven1x** [BG-Software-LLC/SuperiorSkyblock2#333]
**Minecraft's Version**
Paperspigot 1.16.5

**Describe the bug**
After using /is admin recalc , levels of all islands were set to 0
in /is blocks all blocks are counted, but after using /is recalc or /is level , almost all of blocks are not counted in island level.
**Additional information**
Config file :
[config.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6756764/config.zip)

**Comment by OmerBenGera** [comment]
This issue is already fixed in latest dev build.
You can find it on https://bg-software.com/superiorskyblock :)
