### ISSUE TITLE
spammed

### ISSUE THREAD

**Issue by russianpeanut** [BG-Software-LLC/SuperiorSkyblock2#334]
**Minecraft's Version**
Paper 1.16.5

**Plugin's Version**: -
Latest 1.7.0

**Describe the bug**
i am getting spammed with this error 
https://pastebin.com/vnPuu0EV

**To Reproduce**
.

**Additional information**

**Comment by OmerBenGera** [comment]
Seems like more than one program is interacting with a jar file, nothing to do with the plugin itself.
