### ISSUE TITLE
/is bank - when depositing having the error message "ERROR | success." displayed in chat!

### ISSUE THREAD

**Issue by shirinox** [BG-Software-LLC/SuperiorSkyblock2#337]
**Minecraft's Version**
Paper 1.17

**Plugin's Version**: -
SuperiorSkyblock2-b177

**Describe the bug**
When trying to deposit any money in the /is bank, I'm given the following message. [ERROR | success]

**To Reproduce**
I've attached a video below.

https://user-images.githubusercontent.com/75865669/124369162-b42de100-dc1d-11eb-9e86-e3bd1f02700a.mp4

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.

**Comment by OmerBenGera** [comment]
What plugin are you using for economy?

**Comment by shirinox** [comment]
https://www.spigotmc.org/resources/theosiseconomy.93430/

**Comment by OmerBenGera** [comment]
> 
> 
> https://www.spigotmc.org/resources/theosiseconomy.93430/

There is an issue with this plugin - for no reason, when the transaction successes, it sets the failure reason to "success", instead of leaving it blank / null.
Contact the developer of that plugin and tell him to change that.
