### ISSUE TITLE
'visitors' has bug about cancelled teleports.

### ISSUE THREAD

**Issue by Obliviated** [BG-Software-LLC/SuperiorSkyblock2#338]
**Minecraft's Version**
1.8.8 Paper 4c7641d

**Plugin's Version**: -
1.6.0 b160
**Describe the bug**
when a visitor teleporting to an island, Superior adding the visitor to island visitors but if teleport is cancelled the visitor can not removing from visitor list.

![image](https://user-images.githubusercontent.com/36128276/124374883-6a89d880-dca7-11eb-8b35-dd48af9e3689.png)
we tried /is close, /is expell but but not works.

**To Reproduce**
make a plugin that is cancel teleport event.
teleport an island.
make cancel the teleport

**Additional information**
this issue are not need it.

**Comment by Obliviated** [comment]
this bug is included /is close event.

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed (make sure you cancel the teleport event in a priority below HIGHEST)

**Comment by OmerBenGera** [comment]
Have you tested it?

**Comment by Obliviated** [comment]
Sorry i know. I'm late but news are good. Fixed thanks.
