### ISSUE TITLE
Error when creating island

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#339]
**Minecraft's Version**
Airplane 1.16.5

**Plugin's Version**: -
Superior Dev build 177

**Describe the bug**
When I create an island I get this error :
https://pastebin.com/RJhjzVft

**To Reproduce**
Create an island

**Additional information**
I get a crystal_end on my island (as you see on the error)

**Comment by WolverStones** [comment]
Great, but obviously you sent the wrong link link to pastebin is a link only to the main page :D @WarnDangerous.

**Comment by WarnDangerous** [comment]
Ahah sorry I edited, thanks :p 

> Great, but obviously you sent the wrong link link to pastebin is a link only to the main page :D @WarnDangerous.

**Comment by OmerBenGera** [comment]
Seems like you don't have enough ran or something else blocks creation of threads.
Fix it and it will work again.

**Comment by WarnDangerous** [comment]
I got 20gb of allocated memory,
I also tried with 50gb, same issue.

I didn't get the issue on older plugin version, so it's more an issue on your side
(I also tried without any flags, on openJDK 16, so no graalvm, still the error.)

**Comment by WarnDangerous** [comment]
Tried on Superior 1.7.0, can't reproduce the issue, so it's on your side.

**Comment by OmerBenGera** [comment]
As I said before, threads cannot be created, probably not due to ram if you have 20gb ram.
Look for the reason for that and fix it.
