### ISSUE TITLE
Island create error on 1.17

### ISSUE THREAD

**Issue by wonyoungb** [BG-Software-LLC/SuperiorSkyblock2#347]
**Minecraft's Version**
The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)
1.17 Spigot-R0.1-SNAPSHOT

**Plugin's Version**: -
The version of the plugin. If you use a dev build, mention which dev build you use.
SuperiorSkyblock2-b177

**Describe the bug**
Keep getting error when creating new island also can't preview island biome

**To Reproduce**
Steps to reproduce the bug.
/is create ~~

**Additional information**
Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome.
ERROR LOG: https://pastebin.com/Rzuj0FKh

**Comment by OmerBenGera** [comment]
This seems like an issue that occurs when you log in and load chunks in your vanilla world, as it throws errors regarding villager outposts and such, which don't exist in the islands worlds.
Therefore, I am closing this issue for now. I recommend switching to Paper, which will probably solve the issue.

**Comment by wonyoungb** [comment]
Same on Paper-1.17.1-R01-SNAPSHOT 
When keep seeing void on Island also can't making island.

**Comment by OmerBenGera** [comment]
Upload the new error that you receive

**Comment by wonyoungb** [comment]
[2021-07-08-3.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6787175/2021-07-08-3.log)
there is no error on it but keep can't preview island and get void map
![2021-07-09_05 47 07](https://user-images.githubusercontent.com/48880431/124988834-74ca1f00-e079-11eb-8982-4ecb95375ba7.png)
![2021-07-09_04 50 17](https://user-images.githubusercontent.com/48880431/124988850-78f63c80-e079-11eb-9d2f-e658a2ec0486.png)
![2021-07-09_05 44 35](https://user-images.githubusercontent.com/48880431/124988860-7b589680-e079-11eb-9750-87ce210eb8f6.png)

**Comment by OmerBenGera** [comment]
about preview - make sure you set the teleport location to a location where you actually placed a copy of the islands schematic.
about the island creation - it isn't working?

**Comment by wonyoungb** [comment]
oh got it for preview but void map can't understand well.

**Comment by OmerBenGera** [comment]
I don't understand what void map you're talking about

**Comment by wonyoungb** [comment]
like second pic and first pic users keep falling or only have one bedrock to stand when tp/create island before they remake island

**Comment by OmerBenGera** [comment]
You can change the spawn location in your config.
I am closing this issue as it doesn't seem like there are any issues with the plugin.
If you have any further questions, you are more than welcome to ask them on the discord server
