### ISSUE TITLE
Can't create islands on Spigot 1.17.1

### ISSUE THREAD

**Issue by Kamology** [BG-Software-LLC/SuperiorSkyblock2#351]
**Minecraft's Version**
Spigot 1.17.1

**Plugin's Version**: -
187

**Describe the bug**
Can't create islands, throws this error https://hastebin.com/agesiletag.sql

**To Reproduce**
Install said versions, try to create island

**Additional information**
This server is an exact mirror (minus databases/user data and stuff) of another server it currently works fine on, except the other server is Paper build 91, and this is Spigot. Why on Earth would I use Spigot instead of Paper? Currently Paper is absolutely massacring our servers performance for no apparent reason so we wanted to try Spigot. So... it seems we're currently at a crossroads of not being able to use either configuration lol. With the luck I've been having, if I swap jars again back to Spigot for a 4th time, it'll probably magically work, but, yeah...

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it works or not

**Comment by Kamology** [comment]
Yep seems to be good now, thank you.
