### ISSUE TITLE
lights-update property does not work

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#352]
### Minecraft's Version

1.17.1

### Plugin's Version

latest build 1.7.0-devb188

### Describe the bug

When schematic is pasted, all light sources are buggy.
lights-update in config.yml is true

### To Reproduce

When schematic is pasted, all light sources are buggy.
lights-update in config.yml is true

**Comment by OmerBenGera** [comment]
Did you create your schematic on your own or it's a built in schematic?

**Comment by SbirTeo** [comment]
I created it with /is admin schem

Il giorno ven 9 lug 2021 alle ore 21:59 Ome_R ***@***.***> ha
scritto:

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, mind taking a video of you creating the schematic and then creating an island using it?

**Comment by SbirTeo** [comment]
https://www.mediafire.com/file/u0qvgus6146mv7r/Minecraft_1.17.1_-_Multigiocatore_%2528server_di_terze_parti%2529_2021-07-10_10-35-04.mp4/file

**Comment by SbirTeo** [comment]
https://www.mediafire.com/file/tdwoozp1dlv2tmx/Minecraft_1.17.1_-_Multigiocatore_%2528server_di_terze_parti%2529_2021-07-10_10-36-09.mp4/file

**Comment by OmerBenGera** [comment]
Upload the video to youtube or any other streaming service, I am not downloading files from unknown sources.

**Comment by SbirTeo** [comment]
https://youtu.be/q9nDQCz0sI4

Il giorno sab 10 lug 2021 alle ore 10:53 Ome_R ***@***.***>
ha scritto:

**Comment by OmerBenGera** [comment]
You put the video on private and therefore I can't access it.

**Comment by SbirTeo** [comment]
Try now.

**Comment by OmerBenGera** [comment]
Don't create a copy of the schematic that was placed by SSB, as if it had issues, re-creating it will not fix lights etc.
Create a schematic where you place blocks or something, and check if it works.

**Comment by SbirTeo** [comment]
Nothing changed... i tried creating an island from the beginning

**Comment by OmerBenGera** [comment]
> 
> 
> Nothing changed... i tried creating an island from the beginning

It worked fine for me, I don't know why it doesn't work for you.
Mind sharing with me the schematic that you created?
Upload it to mediafire or something
