### ISSUE TITLE
Biome selected - glowing property in menu not working

### ISSUE THREAD

**Issue by SbirTeo** [BG-Software-LLC/SuperiorSkyblock2#356]
### Minecraft's Version

1.17.1

### Plugin's Version

latest 1.7.0 devb188

### Describe the bug

http://prntscr.com/19zly8k

### To Reproduce

http://prntscr.com/19zly8k

**Comment by OmerBenGera** [comment]
If you use skulls as items, then they can't glow because of minecraft restriction.
From my testings it works fine :)
