### ISSUE TITLE
End portal in the nether

### ISSUE THREAD

**Issue by PatatjeMC** [BG-Software-LLC/SuperiorSkyblock2#357]
### Minecraft's Version

1.16.5 (Tuinity)

### Plugin's Version

1.7.0-DEVb185

### Describe the bug

You can't have a end portal in the nether since a new update I have a end portal generated in the nether that people can unlock so people can't get into the end before they are in the nether and some more reasons but since a new update people can't enter it they just get send back to the overworld

### To Reproduce

Place a end portal in the nether and enter it

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
