### ISSUE TITLE
Ssb2 miscounting island blocks, hopper issue

### ISSUE THREAD

**Issue by GunacP40** [BG-Software-LLC/SuperiorSkyblock2#359]
### Minecraft's Version

This server is running Airplane-Purpur version git-Airplane-2 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Purpur-1169 (MC: 1.16.5)

### Plugin's Version

SuperiorSkyblock2 version 1.7.0-DEVb187

### Describe the bug

ssb2 is not properly count island blocks. specifically hoppers, players break hoppers and when they try to place it again it says they've reached their limit, but they haven't

### To Reproduce

i'm not sure how to. i think this issue is happening because of the old level bug that miscounted blocks and levels I guess

### Additional Information

this is one of my players /is counts menu https://imgur.com/a/ukDMwHd
it says his island has 185 hoppers when the maximum hopper upgrade has been 150 since day one: https://hastebin.com/rikorabeke.yaml
this is my plugin list https://hastebin.com/qucirilewe.md

**Comment by OmerBenGera** [comment]
This is because of a plugin probably that overrides hopper breaking, and it doesnt let SSB know about it.
First try replicating the issue when only SSB is installed, and if it still occurs reopen the issue.

**Comment by GunacP40** [comment]
i have already told you i have no plugins that limit entities, blocks or any other thing
i thought the issue was solved but a user that I had previously asked to remove ALL hoppers and place them again has been able to place more hoppers than the maximum upgrade allowws
https://imgur.com/a/qaptk0D

his island has more than 400 hoppers when the maximum limit is 150

**Comment by GunacP40** [comment]
i no longer believe the plugin is miscounting hoppers but the upgrades are not working properly

**Comment by GunacP40** [comment]
this is my upgrades config file https://hastebin.com/uciyudexaq.yaml

**Comment by GunacP40** [comment]
bump

**Comment by GunacP40** [comment]
players just can keep placing more hoppers.. https://imgur.com/a/qYLywwt

**Comment by OmerBenGera** [comment]
Make sure the islands have a limit for hoppers with /is admin show.
If they have a limit and they can still place hoppers, open a new issue with all the information possible regarding the issue, as it doesn't seem like an issue with counting hoppers.
