### ISSUE TITLE
Default Language & schematic offset does not work

### ISSUE THREAD

**Issue by OctaZix** [BG-Software-LLC/SuperiorSkyblock2#360]
### Minecraft's Version

1.16.5

### Plugin's Version

SuperiorSkyblock2-b196

### Describe the bug

Creating an island, the starting values counts the schematic blocks value too.
In the config.yml, schematic-offset is set to true.

The default language is: fr-FR but the messages are always in en-US

### To Reproduce

.

**Comment by OmerBenGera** [comment]
About the lang - the custom language will only be applied if the followings are met:
- Player has never played before and joins for the first time (or at least doesn't have data tracked for him by SSB)
- The language is actually valid
Make sure you have all of the requirements met.

About the schematic-offset: It should be working on your version, however I will check it out again and update here if I manage to replicate it or not. It might take some time (might only be next Saturday)

**Comment by OmerBenGera** [comment]
I couldn't seem to replicate the issue.
Have you faced that issue again since the report was opened?

**Comment by OmerBenGera** [comment]
Any news regarding this?
