### ISSUE TITLE
Is lvl reset

### ISSUE THREAD

**Issue by SkessyTTV** [BG-Software-LLC/SuperiorSkyblock2#361]
### Minecraft's Version

1.16.5

### Plugin's Version

SuperiorSkyblock2-1.7.0

### Describe the bug

when player type  **/is level**  the island level resets

### To Reproduce

![unknown](https://user-images.githubusercontent.com/66589714/125282211-67ca5b80-e317-11eb-8679-ddc2547bd28f.png)
![island before](wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww)

**Comment by OmerBenGera** [comment]
Use latest dev build, 1.7.0 is known to have that bug, however it's already fixed in the dev builds
