### ISSUE TITLE
Exception generated in dev build 196

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#362]
### Minecraft's Version

Tuinity 1.16.5

### Plugin's Version

Dev Build 196

### Describe the bug

Error in the console (can't say why it happened)

### To Reproduce

I don't know how to reproduce it. It might have something to do with the spawners of Rosestacker.

### Additional Information

https://pastebin.com/raw/ucJFr7rW

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
