### ISSUE TITLE
the island during creation appears and disappears instantly

### ISSUE THREAD

**Issue by SharkblackFr** [BG-Software-LLC/SuperiorSkyblock2#363]
### Minecraft's Version

Paper 1.12.2

### Plugin's Version

Last #196

### Describe the bug

Hi, 
When I create an island is appear and instantly disappeears.
But when I use the version #171 all is good except the calculation of island levels

https://user-images.githubusercontent.com/19607299/125383510-ccc59600-e397-11eb-8804-a8856d664369.mp4

### To Reproduce

https://user-images.githubusercontent.com/19607299/125383565-dfd86600-e397-11eb-90e6-15b8b15b7462.mp4

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue - it seems like something is blocking the plugin from placing blocks.
Does it happen if you have only SuperiorSkyblock enabled on a 1.12.2 Paper/Spigot server?

**Comment by SharkblackFr** [comment]
> I can't seem to replicate the issue - it seems like something is blocking the plugin from placing blocks.
> Does it happen if you have only SuperiorSkyblock enabled on a 1.12.2 Paper/Spigot server?
I tested with SuperiorSkyblock and WorldEdit (for my schematics) on version 209, and the same problem is ocurring

**Comment by OmerBenGera** [comment]
> > I can't seem to replicate the issue - it seems like something is blocking the plugin from placing blocks.
> > Does it happen if you have only SuperiorSkyblock enabled on a 1.12.2 Paper/Spigot server?
> 
> I tested with SuperiorSkyblock and WorldEdit (for my schematics) on version 209, and the same problem is ocurring

Dont use WE for schematics - lmk if it works without it.

**Comment by SharkblackFr** [comment]
> > > I can't seem to replicate the issue - it seems like something is blocking the plugin from placing blocks.
> > > Does it happen if you have only SuperiorSkyblock enabled on a 1.12.2 Paper/Spigot server?
> > 
> > 
> > I tested with SuperiorSkyblock and WorldEdit (for my schematics) on version 209, and the same problem is ocurring
> 
> Dont use WE for schematics - lmk if it works without it.

[](https://pastebin.com/axRZ1V9D)
When I execute the /is level command with SuperiorSkyblock b209, i have got this error

```
######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

# Here you can set all the level values for your blocks.
# To set specific spawner types, use 'MOB_SPAWNER:<ENTITY>': <AMOUNT>
# If no level is found, the formula from config will be used.

OBSIDIAN: 15
DIAMOND_BLOCK: 10
GOLD_BLOCK: 8
IRON_BLOCK: 5
GOLD_ORE: 3
IRON_BLOCK: 1
DIAMOND_ORE: 1
COBBLESTONE: 0.1
STONE: 0.01
```

**Comment by OmerBenGera** [comment]
> > > > I can't seem to replicate the issue - it seems like something is blocking the plugin from placing blocks.
> > > > Does it happen if you have only SuperiorSkyblock enabled on a 1.12.2 Paper/Spigot server?
> > > 
> > > 
> > > I tested with SuperiorSkyblock and WorldEdit (for my schematics) on version 209, and the same problem is ocurring
> > 
> > 
> > Dont use WE for schematics - lmk if it works without it.
> 
> https://pastebin.com/axRZ1V9D
> When I execute the /is level command with SuperiorSkyblock b209, i have got this error
> 
> ```
> ######################################################
> ##                                                  ##
> ##                SuperiorSkyblock 2                ##
> ##                Developed by Ome_R                ##
> ##                                                  ##
> ######################################################
> 
> # Here you can set all the level values for your blocks.
> # To set specific spawner types, use 'MOB_SPAWNER:<ENTITY>': <AMOUNT>
> # If no level is found, the formula from config will be used.
> 
> OBSIDIAN: 15
> DIAMOND_BLOCK: 10
> GOLD_BLOCK: 8
> IRON_BLOCK: 5
> GOLD_ORE: 3
> IRON_BLOCK: 1
> DIAMOND_ORE: 1
> COBBLESTONE: 0.1
> STONE: 0.01
> ```

Its a known issue, for now revert to an older version

**Comment by SharkblackFr** [comment]
> > > > > I can't seem to replicate the issue - it seems like something is blocking the plugin from placing blocks.
> > > > > Does it happen if you have only SuperiorSkyblock enabled on a 1.12.2 Paper/Spigot server?
> > > > 
> > > > 
> > > > I tested with SuperiorSkyblock and WorldEdit (for my schematics) on version 209, and the same problem is ocurring
> > > 
> > > 
> > > Dont use WE for schematics - lmk if it works without it.
> > 
> > 
> > https://pastebin.com/axRZ1V9D
> > When I execute the /is level command with SuperiorSkyblock b209, i have got this error
> > ```
> > ######################################################
> > ##                                                  ##
> > ##                SuperiorSkyblock 2                ##
> > ##                Developed by Ome_R                ##
> > ##                                                  ##
> > ######################################################
> > 
> > # Here you can set all the level values for your blocks.
> > # To set specific spawner types, use 'MOB_SPAWNER:<ENTITY>': <AMOUNT>
> > # If no level is found, the formula from config will be used.
> > 
> > OBSIDIAN: 15
> > DIAMOND_BLOCK: 10
> > GOLD_BLOCK: 8
> > IRON_BLOCK: 5
> > GOLD_ORE: 3
> > IRON_BLOCK: 1
> > DIAMOND_ORE: 1
> > COBBLESTONE: 0.1
> > STONE: 0.01
> > ```
> 
> Its a known issue, for now revert to an older version

**The level is issue occurs on versions > to 203. But on 203 version, when I do /is level, the level is automatically resetting to level 0. (I tried different level formulas, such as 2, {} * 2 and I also tried with no formula at all)**

**Comment by OmerBenGera** [comment]
I am closing this as it seems an issue with WE schematics.
About the levels issue, it's fixed on latest dev build.
