### ISSUE TITLE
Must use Protochunk constructor (New Paper Change)

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#364]
### Minecraft's Version

1.17.1 Purpur dev 1265

### Plugin's Version

dev 196

### Describe the bug

Sent on Island creation

### To Reproduce

https://github.com/PaperMC/Paper/commit/a4880d832bc467a9929ce3af95fb57a74e024df4

### Additional Information

https://pastebin.com/VKEYFS4E

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
