### ISSUE TITLE
Nashron engine causing errors

### ISSUE THREAD

**Issue by Stoiky20** [BG-Software-LLC/SuperiorSkyblock2#371]
### Minecraft's Version

1.17.1 paperspigot

### Plugin's Version

b196 dev build

### Describe the bug

When I place a glass this error happens
<html>
<body>

1 | [11:59:15] [Craft Scheduler Thread - 19/ERROR]: Could not pass event IslandWorthUpdateEvent to SuperiorSkyblock2 v1.7.0-DEVb196
-- | --
2 | java.lang.IllegalAccessError: failed to access class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget from class org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator (org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator$JumpTarget is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6b7308ca; org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator is in unnamed module of loader com.bgsoftware.superiorskyblock.modules.ModuleClassLoader @1da99246)
3 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.createJumpTarget(LocalVariableTypesCalculator.java:419) ~[?:?]
4 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.getOrCreateJumpTarget(LocalVariableTypesCalculator.java:1196) ~[?:?]
5 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1234) ~[?:?]
6 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.jumpToLabel(LocalVariableTypesCalculator.java:1230) ~[?:?]
7 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:457) ~[?:?]
8 | at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
9 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
10 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterBinaryNode(LocalVariableTypesCalculator.java:461) ~[?:?]
11 | at org.openjdk.nashorn.internal.ir.BinaryNode.accept(BinaryNode.java:329) ~[?:?]
12 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpression(LocalVariableTypesCalculator.java:603) ~[?:?]
13 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.visitExpressionOnEmptyStack(LocalVariableTypesCalculator.java:598) ~[?:?]
14 | at org.openjdk.nashorn.internal.codegen.LocalVariableTypesCalculator.enterExpressionStatement(LocalVariableTypesCalculator.java:580) ~[?:?]
15 | at org.openjdk.nashorn.internal.ir.ExpressionStatement.accept(ExpressionStatement.java:81) ~[?:?]
16 | at org.openjdk.nashorn.internal.ir.Node.accept(Node.java:286) ~[?:?]
17 | at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:236) ~[?:?]
18 | at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
19 | at org.openjdk.nashorn.internal.ir.Block.accept(Block.java:507) ~[?:?]
20 | at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:405) ~[?:?]
21 | at org.openjdk.nashorn.internal.ir.LexicalContextNode$Acceptor.accept(LexicalContextNode.java:57) ~[?:?]
22 | at org.openjdk.nashorn.internal.ir.LexicalContextExpression.accept(LexicalContextExpression.java:47) ~[?:?]
23 | at org.openjdk.nashorn.internal.ir.FunctionNode.accept(FunctionNode.java:57) ~[?:?]
24 | at org.openjdk.nashorn.internal.codegen.CompilationPhase.transformFunction(CompilationPhase.java:618) ~[?:?]
25 | at org.openjdk.nashorn.internal.codegen.CompilationPhase$LocalVariableTypeCalculationPhase.transform(CompilationPhase.java:277) ~[?:?]
26 | at org.openjdk.nashorn.internal.codegen.CompilationPhase.apply(CompilationPhase.java:614) ~[?:?]
27 | at org.openjdk.nashorn.internal.codegen.Compiler.compile(Compiler.java:641) ~[?:?]
28 | at org.openjdk.nashorn.internal.runtime.Context.compile(Context.java:1528) ~[?:?]
29 | at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:1449) ~[?:?]
30 | at org.openjdk.nashorn.internal.runtime.Context.compileScript(Context.java:759) ~[?:?]
31 | at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:528) ~[?:?]
32 | at org.openjdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:517) ~[?:?]
33 | at org.openjdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:395) ~[?:?]
34 | at org.openjdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:151) ~[?:?]
35 | at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[java.scripting:?]
36 | at com.bgsoftware.superiorskyblock.scripts.NashornScript.eval(NashornScript.java:41) ~[?:?]
37 | at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:204) ~[?:?]
38 | at com.bgsoftware.superiorskyblock.missions.IslandMissions.tryComplete(IslandMissions.java:190) ~[?:?]
39 | at com.bgsoftware.superiorskyblock.missions.IslandMissions.onIslandWorthUpdate(IslandMissions.java:186) ~[?:?]
40 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor771.execute(Unknown Source) ~[?:?]
41 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-104]
42 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-104]
43 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-104]
44 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-104]
45 | at com.bgsoftware.superiorskyblock.utils.events.EventsCaller.callIslandWorthUpdateEvent(EventsCaller.java:193) ~[?:?]
46 | at com.bgsoftware.superiorskyblock.island.SIsland.lambda$saveBlockCounts$75(SIsland.java:2094) ~[?:?]
47 | at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-104]
48 | at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-104]
49 | at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-104]
50 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
51 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
52 | at java.lang.Thread.run(Thread.java:831) [?:?]
53 |  

</body>
</html>

### To Reproduce

place a glass block on your island

**Comment by OmerBenGera** [comment]
This happens because the javascript engine you have is for no reason broken.
You are not the first one to have it, and I have no solution for this atm.
Mind trying to use the other engine, [RhinoEngine ](https://hub.bg-software.com/job/SuperiorSkyblock%20Addons/job/RhinoEngine/) instead?

**Comment by Stoiky20** [comment]
Found out that it only happens when the missions are enabled, when them are turned off everything is fine

**Comment by OmerBenGera** [comment]
> 
> 
> Found out that it only happens when the missions are enabled, when them are turned off everything is fine

read what I wrote above.

**Comment by Stoiky20** [comment]
Yeah but with  RhinoEngine the server does not start at all

**Comment by OmerBenGera** [comment]
> Yeah but with RhinoEngine the server does not start at all

Weird, what error do you have?

**Comment by Redwolf223** [comment]
I'm having this problem with Rhino

https://pastebin.com/Znn29pU3

**Comment by ElBananaa** [comment]
Hey!
I ran some tests on my end to try to reproduce this issue, and I was unable to do so.
I thought this issue could be caused by the fact that some users may be using a different jar provider (Such as Amazon Coretto / Azul Zulu)

My tests were made under Java OpenJDK 17.0.1, Amazon Coretto Java JDK 17.0.1 & Azul Zulu Java JDK 17.0.1, and I was completely unable to reproduce the issue (missions were enabled).

However, I did notice something else : For some reason, the plugin didn't automatically download the NashornEngine addon, but still missions were working fine, as same as all the other features. This is caused by the fact that another one of my plugin already automatically downloads Nashorn.

It also seems like PurpurMC comes with the Rhino Engine, in which case, you don't need to download Nashorn specifically for the plugin, and, still with no errors.

I finally ran tests with PaperMC (to let the plugin download nashorn), with Java OpenJDK 17.0.1, Amazon Coretto Java JDK 17.0.1 & Azul Zulu Java JDK 17.0.1, and once again, I was unable to reproduce the issue.

Hope this helps a bit either finding the cause of the issue, or at least help some users fixing this issue (if it still occurs) ^^

**Comment by OmerBenGera** [comment]
> 

The plugin will not download a nashorn engine if it's already loaded or there's a different javascript engine available on the virtual machine.
Thanks for the help, appreciated.

**Comment by OmerBenGera** [comment]
The solution will be to install an external plugin that provides a nashorn engine - such as [NashornPlus ](https://bitbucket.org/kangarko/nashornplus/downloads/) or [NashornJS](https://www.spigotmc.org/resources/nashornjs-provider-and-cli.91204/)

**Comment by itslukemango** [comment]
> The solution will be to install an external plugin that provides a nashorn engine - such as [NashornPlus ](https://bitbucket.org/kangarko/nashornplus/downloads/) or [NashornJS](https://www.spigotmc.org/resources/nashornjs-provider-and-cli.91204/)

Using NashornPlus doesn't work, server starts and stops instantly as the done message appears - just using NashornJS doesn't fix the issue

**Comment by OmerBenGera** [comment]
> > The solution will be to install an external plugin that provides a nashorn engine - such as [NashornPlus ](https://bitbucket.org/kangarko/nashornplus/downloads/) or [NashornJS](https://www.spigotmc.org/resources/nashornjs-provider-and-cli.91204/)
> 
> Using NashornPlus doesn't work, server starts and stops instantly as the done message appears - just using NashornJS doesn't fix the issue

I also checked it out and NashornPlus is broken (it uses a broken nashorn version)

**Comment by ElBananaa** [comment]
> > > The solution will be to install an external plugin that provides a nashorn engine - such as [NashornPlus ](https://bitbucket.org/kangarko/nashornplus/downloads/) or [NashornJS](https://www.spigotmc.org/resources/nashornjs-provider-and-cli.91204/)
> > 
> > 
> > Using NashornPlus doesn't work, server starts and stops instantly as the done message appears - just using NashornJS doesn't fix the issue
> 
> I also checked it out and NashornPlus is broken (it uses a broken nashorn version)

NashornPlus was made for versions under 1.16.5 afaik, which explains this, I guess ^^
