### ISSUE TITLE
InventoryClick Event

### ISSUE THREAD

**Issue by iMasterYolo** [BG-Software-LLC/SuperiorSkyblock2#372]
### Minecraft's Version

 Paper version git-Paper-782 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 

### Plugin's Version

1.7.0-DEVb196

### Describe the bug

![image](https://user-images.githubusercontent.com/53452039/125966045-ac3b82cf-dd03-4d2a-9f0b-d6aec4d05176.png)

### To Reproduce

I think it's related to the biome menu (/is ibome, in menus > biomes.yml), if the biome is named "SWAMP", the error pops in console (named after spigot 1.17.1 api https://hub.spigotmc.org/javadocs/bukkit/ since the name is the same in 1.16.5)
I have 7 biomes in the menu and this one it's the only one creating problems.
![image](https://user-images.githubusercontent.com/53452039/125966575-1e21f1d2-a207-4bfd-8051-9a2a7ec7eaa8.png)

### Additional Information

Also, there's still a problem related to skin restorer, should I open a new issue for that, or the devs are aware of that? Thanks for your time <3

**Comment by OmerBenGera** [comment]
You have "SWAMPLAND" in the island creation menu somewhere.
The screenshot you took seems to be from the biomes menu if I am not wrong.
If that was the issue, make sure you close the issue and update me :)

**Comment by iMasterYolo** [comment]
> You have "SWAMPLAND" in the island creation menu somewhere.
Oh, dang, it actually was from that, whoopsie, my bad. I updated it and everything seems to be fine.
Thanks for your time <3
