### ISSUE TITLE
hopper limit issue

### ISSUE THREAD

**Issue by GunacP40** [BG-Software-LLC/SuperiorSkyblock2#374]
### Minecraft's Version

This server is running Airplane-Purpur version git-Airplane-2 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Purpur-1169 (MC: 1.16.5)

### Plugin's Version

SuperiorSkyblock2 version 1.7.0-DEVb187

### Describe the bug

players can place more hoppers than the maximum upgrade limit. my maximum hopper upgrade is 150 hoppers and i have a player with over 500 hoppers placed in their island

### To Reproduce

not sure how, i've tried myself to reproduce the bug and the limit stops me but other players can place hoppers above the limit

### Additional Information

this is one of my players /is counts menu https://imgur.com/a/qYLywwt

it says his island has +500 hoppers when the maximum hopper upgrade has been 150 since day one: https://hastebin.com/rikorabeke.yaml

this is my plugin list https://hastebin.com/qucirilewe.md

this is the /is admin show command showing one of the players island, it has the hopper-limit upgrade and it says that their hopper limit is 150: https://hastebin.com/oyemeqezum.yaml

this is my upgrades config file https://hastebin.com/edoqawiquf.yaml

**Comment by OmerBenGera** [comment]
Did you try to replicate the issue yourself?

**Comment by GunacP40** [comment]
as I said: “ not sure how, i've tried myself to reproduce the bug and the limit stops me but other players can place hoppers above the limit”

i’ve seen these players place the hoppers and seen the amount of hoppers on their islands as well as selected the area and done //count hopper to see how many hoppers are placed in their islands

**Comment by OmerBenGera** [comment]
> as I said: “ not sure how, i've tried myself to reproduce the bug and the limit stops me but other players can place hoppers above the limit”
> 
> i’ve seen these players place the hoppers and seen the amount of hoppers on their islands as well as selected the area and done //count hopper to see how many hoppers are placed in their islands

Well, I need to know how to replicate the issue. Also, if SSB counts correctly the hoppers, then I dont see how they can exceed it, as the limit is based on that.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
@GunacP40 any response to this for Omer?

**Comment by brasilcraft54** [comment]
https://www.youtube.com/watch?v=esv-RhziYR8

I made a video of how to replicate this bug is possible to do with all items that are in the block-limits settings this is my setting more and possible to have as many as you want just break everything.

block-limits:
  - HOPPER:50
  - REPEATER:60
  - COMPARATOR:60
  - OBSERVER:100
  - DISPENSER:100
  - DROPPER:100
  - HOPPER_MINECART:20

**Comment by GunacP40** [comment]
sorry for not answering i never got the notifications. i was never able to reproduce the bug myself but i have more than 2 users with the issue. glad brasilcraft54 was able to reproduce it. hope you can fix it Omer

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
