### ISSUE TITLE
/ptime and /pweather from CMI reset on World switch

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#375]
### Minecraft's Version

1.17.1 Purpur dev 1280

### Plugin's Version

dev 196

### Describe the bug

Using CMI's /ptime and /pweather commands are to set the players personal weather and time, with SSB installed it overrides these values on switching worlds even when not using always day/always night/weather related SSB settings

### To Reproduce

Attempt to set /ptime and /pweather
Switch Worlds
Notice how they reset

### Additional Information

https://github.com/Zrips/CMI/issues/5707

Tested this with and without SSB installed

Video:
https://screenshots.skizzles.me/wAnA3/MUKEVuRO46.mp4

**Comment by OmerBenGera** [comment]
Thats because of the settings of islands having the always day / night etc. They use the same mechanism, so it makes sense thats SSB overrides it.
I will check if its possible to change it, however I cant promise anything.

**Comment by OmerBenGera** [comment]
It doesn't seem like there's a way to do that with the API of CMI, therefore I am closing this
