### ISSUE TITLE
Biomes command doesn't work when using Java 16 + an engine

### ISSUE THREAD

**Issue by GunacP40** [BG-Software-LLC/SuperiorSkyblock2#376]
### Minecraft's Version

This server is running Airplane-Purpur version git-Airplane-2 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Unknown version
Previous version: git-Purpur-1169 (MC: 1.16.5)

### Plugin's Version

SuperiorSkyblock2 version 1.7.0-DEVb199

### Describe the bug

The biome command won't work, I've tried /is biome, /is biomes, /island biome, /island biomes. It either says unknown command or gives the superiorskyblock2 help guide.

### To Reproduce

Try running the plugin on java 16 + using an engine module. I have tested on my PC that has java 8 installed and it works perfectly. I've also reset the entire plugin's folder to test and it doesn't work

### Additional Information

you can see here when i do /is biomes or /is biome and it returns Unknown command and the superior command help: https://imgur.com/a/g9ej99p (USING THE PLUGIN'S DEFAULT CONFIG)

**Comment by OmerBenGera** [comment]
Sounds like you dont have permissions to /is biome.
You can confirm this by changing the no-permission to something else and youll see that it updates when you run the command.
