### ISSUE TITLE
Hologram Block Stack

### ISSUE THREAD

**Issue by HeadsShot** [BG-Software-LLC/SuperiorSkyblock2#377]
### Minecraft's Version

git-Paper-776 (MC: 1.16.5)

### Plugin's Version

b196

### Describe the bug

My player placed a stacked block and destroy it the hologram just stuck in the air without any stacked block below it
![safg](https://user-images.githubusercontent.com/41201881/126040820-9b0d7dec-5c75-4f9a-a23e-c5fe80f9b1e5.png)

### To Reproduce

ive tried few technic but i cannot reproduce it might just be bug on placing stacked block

**Comment by HeadsShot** [comment]
> 
> ### Minecraft's Version
> 
> git-Paper-776 (MC: 1.16.5)
> ### Plugin's Version
> 
> b196
> ### Describe the bug
> 
> My player placed a stacked block and destroy it the hologram just stuck in the air without any stacked block below it
> ![safg](https://user-images.githubusercontent.com/41201881/126040820-9b0d7dec-5c75-4f9a-a23e-c5fe80f9b1e5.png)
> ### To Reproduce
> 
> ive tried few technic but i cannot reproduce it might just be bug on placing stacked block
> ### Additional Information
> 
> _No response_

the hologram will disappeared if something update it

**Comment by OmerBenGera** [comment]
SuperiorSkyblock will remove holograms if it notices the block breaking, an update is caused to the hologram or if the chunk unloads.
There was another plugin probably being involved in the process of breaking that block, causing SSB to not know about the breaking task of the block.
Can you confirm/deny it?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
@HeadsShot any response to this for Omer?
