### ISSUE TITLE
/island create not creating island

### ISSUE THREAD

**Issue by vizard0912** [BG-Software-LLC/SuperiorSkyblock2#382]
### Minecraft's Version

spigot-1.17.1

### Plugin's Version

Dev build #199

### Describe the bug

No island is being created when I do /island create. It just spams console with error

### To Reproduce

Just do /island create

### Additional Information

Console Error: https://pastebin.com/qj6LV3jy

**Comment by OmerBenGera** [comment]
Use paper or Tuinity, let me know if it helps.

**Comment by vizard0912** [comment]
nop

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
