### ISSUE TITLE
bugged player spawn location

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#385]
### Minecraft's Version

git-paper-104 1.17.1

### Plugin's Version

SuperiorSkyblock2-b199.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

I create a schematic where the player stays in one position but when I reset the island he goes to another island but if he runs /is create name for the first time he goes to the right one but it happens when he types /is reset and creates another one he goes to the corner of the island at the coordinates 0, 100, 600 this happens only when I reset the island.

### To Reproduce

/is reset

### Additional Information

1° https://prnt.sc/1d3n9tj
2° https://prnt.sc/1d3nvdu

**Comment by brasilcraft54** [comment]
I found another bug when you create an island or delete the terrain it becomes dark with no light

1° https://prnt.sc/1dilzr1

another bug is also a delay to the server when you delete an island and there is only me on the server but still the server has a small delay see.

1° https://prnt.sc/1din7y8
2° https://prnt.sc/1dinisl
3° https://prnt.sc/1dinras

There is only me on the server and I have not built anything on the island, it is strange that this happens and my server is a dedicated one.

**Comment by OmerBenGera** [comment]
> I found another bug when you create an island or delete the terrain it becomes dark with no light
> 
> 1° https://prnt.sc/1dilzr1
> 
> another bug is also a delay to the server when you delete an island and there is only me on the server but still the server has a small delay see.
> 
> 1° https://prnt.sc/1din7y8
> 2° https://prnt.sc/1dinisl
> 3° https://prnt.sc/1dinras
> 
> There is only me on the server and I have not built anything on the island, it is strange that this happens and my server is a dedicated one.

This really has nothing to do with the bug above.
Dont mix multiple bugs in the same issue.

**Comment by brasilcraft54** [comment]
sorry I am new here so I don't understand much so I thought I would put everything into 1 question to be quicker for you.

**Comment by brasilcraft54** [comment]
but since you answered could you tell me how do I remove some upgrades that I don't like? There should be this option because it is annoying to have some upgrades that we don't want and I see that in discord there are many people asking about it

**Comment by brasilcraft54** [comment]
is there any way to get your support faster? because at discord the staff takes a long time to answer

**Comment by OmerBenGera** [comment]
> is there any way to get your support faster? because at discord the staff takes a long time to answer

You should ask for support *only*

**Comment by OmerBenGera** [comment]
> is there any way to get your support faster? because at discord the staff takes a long time to answer

You should ask for support **only** on discord, this is not the place to do so. The github is used to trqck bugs etc. For support, people or the staff team can help you on discord. There is no guarantee for support btw, as I dont have the time to do so.

**Comment by brasilcraft54** [comment]
ok more about the bug of being born wrong on the island do you know when it will be fixed?

**Comment by OmerBenGera** [comment]
> 
> 
> ok more about the bug of being born wrong on the island do you know when it will be fixed?

There's no eta. I am very busy and I work on bug fixes on my free time - hopefully soon I'll have time to work on that.

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it's fixed.

**Comment by WarnDangerous** [comment]
Hello,

I had the same issue, with latest dev build it seems better, but the player's rotation on '/is' is still changed : 
- I saved my schematic when facing : east
and sometimes it fails and the player is facing : south

**Comment by OmerBenGera** [comment]
> 
> 
> Hello,
> 
> I had the same issue, with latest dev build it seems better, but the player's rotation on '/is' is still changed :
> 
>     * I saved my schematic when facing : east
>       and sometimes it fails and the player is facing : south

Fixed in latest dev build
If it still occurs, open a new issue :)
