### ISSUE TITLE
/is command not working!

### ISSUE THREAD

**Issue by Aadi-mone** [BG-Software-LLC/SuperiorSkyblock2#388]
### Minecraft's Version

Papper 1.16.5

### Plugin's Version

1.6.0 and 1.7.0

### Describe the bug

/is command not working properly and not being teleported same problem on old and new version of the plugin.

Hope anyone could help.

Thanks :)

### To Reproduce

Help pls

**Comment by OmerBenGera** [comment]
Look for errors in console, or at least tell us what happens when you run /is..

**Comment by Aadi-mone** [comment]
@OmerBenGera  Okay, Thanks 

This happens when I execute /is command:

![2021-07-22_09 09 33](https://user-images.githubusercontent.com/87631878/126588385-931d2064-a28d-4ceb-97b6-1ba0aa20434c.png)

As well as somethings happens in my console:

https://mclo.gs/CGJFfhE

Thank you so much for helping me.

**Comment by OmerBenGera** [comment]
Use latest dev build, and install the Nashron engine - its an addon of the plugin for Java 16. You can find a tutorial on our wiki - https://wiki.bg-software.com
