### ISSUE TITLE
Entity Count Upgrades throwing errors

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#390]
### Minecraft's Version

1.17.1 Purpur dev 1288

### Plugin's Version

dev 199

### Describe the bug

When using an entity limit as an upgrade, when a spawner attempts to spawn mobs it ends up going over the limit and throwing an error.

### To Reproduce

Setup an entity limit
Place a spawner of that specific entity
Error is thrown and limit exceeded

### Additional Information

https://pastebin.com/8cVfiz5r

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
