### ISSUE TITLE
This is not A BUG!

### ISSUE THREAD

**Issue by Aadi-mone** [BG-Software-LLC/SuperiorSkyblock2#393]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

1.7.0

### Describe the bug

Hello,

I know this is not a BUG, But I feel to Say my issue here!

The plugin was on Spigot now its download is via External Site, Because of that Aternos Doesn't allow that plugin to download.

Please give a direct download option. Don't think your website is a waste because the WIKI is on your webpage so don't worry!

If you give a direct Download Option That will be really appreciated!

View the requirements here:

https://support.aternos.org/hc/en-us/articles/360052255311#h_01EPF9S3W42P6KV2P5YJ9FSF6T

Please consider Doing it please, That will be helpful for many users!

When you shifted your download to an external site Aternos Completely removed your plugin from their Plugins menu!

I can't upload your plugin because  Aternos doesn't support FTP or any kind of Upload For some reason!

Please consider Doing it please, That will be helpful : )

Thanks : )

### To Reproduce

Please give a direct download option

### Additional Information

![Screen](https://user-images.githubusercontent.com/87631878/126676782-319f7a3c-7685-4c3d-9f97-49b072b8cade.png)

**Comment by OmerBenGera** [comment]
Don't use Aternos.
