### ISSUE TITLE
Not pasting schematic correctly

### ISSUE THREAD

**Issue by gmovd** [BG-Software-LLC/SuperiorSkyblock2#401]
### Minecraft's Version

1.17

### Plugin's Version

#199

### Describe the bug

DIRTH_PATH missing on island creation
![2021-07-27_06 44 53](https://user-images.githubusercontent.com/50750719/127096772-fe14aaf0-2494-4fa3-b401-04f0da2ed76a.png)
![2021-07-27_06 44 48](https://user-images.githubusercontent.com/50750719/127096780-ce114375-3020-4760-9978-cb80c34fc1a5.png)

### To Reproduce

create a island from schematic with DIRTH_PATH

### Additional Information

nice plugin, best skyblock on market!

**Comment by OmerBenGera** [comment]
I tried to replicate the issue by creating a new schematic with dirt paths and it worked fine for me.
Update to 1.17.1 Spigot/Paper and try re-creating the schematics.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Rivils** [comment]
Tested this. It works fine after re-creating the schematics in 1.17.1.

**Comment by OmerBenGera** [comment]
great.
