### ISSUE TITLE
Missions do not get saved

### ISSUE THREAD

**Issue by collin12345432** [BG-Software-LLC/SuperiorSkyblock2#407]
### Minecraft's Version

1.17.1   paper-1.17.jar

### Plugin's Version

it is a dev build  Superiorskyblock2-b199.jar

### Describe the bug

so if i write new missions in the config file of the missions and I save the file and restart my server the file is back to the original missions an mine are gone.

### To Reproduce

i make missions save the file restart the server i go ingame and check if the missions are there and they are not there I check the file and it was as it has never been edited

### Additional Information

https://youtu.be/T6XLnr3mzqg

**Comment by OmerBenGera** [comment]
your missions need to be under a section called "missions"
Don't mess with the config, as it will forcely try to fix itself and can get your data deleted, as you have noticed.
Regenerate the missions file, check out the structure and follow it.
