### ISSUE TITLE
SuperiorSkyblock2 and EpicHoppers incompatibility

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#409]
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

SuperiorSkyblock2-b209.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

my island limit is 50 funnel when a player puts 50 funnel on 1 island but when he puts for example 45 normal funnel and 5 epichoppers if he removes the 5 epichoppers to change places he can't for more account as if he had the 50 still if he puts 50 epichoppers and removes and tries to place again it will say he has reached the limit the epichoppers are not leaving the island even removing them the upper skyblock2 does not remove them.

### To Reproduce

using the funnels of the epichoppers plugin in the islands

**Comment by OmerBenGera** [comment]
There's nothing I can do on my end. EpicHoppers handle breaking of their own hoppers, however they don't let other plugins to know about it (unless they added an event regarding this). Therefore, the solution is to contact their developers and ask them to hook into SSB directly, or add an event that SSB can listen to.

**Comment by brasilcraft54** [comment]
even if I remove epichoppers the funnels are still counted there

**Comment by brasilcraft54** [comment]
even patch the plugin it still detects the funnels there, so i believe the problem is in superiorskyblock it should detect it as 1 normal funnel.

**Comment by AustinFRG** [comment]
There's a SpawnerBreakEvent in the EpicSpawners API. It was added about 7 months ago :)
