### ISSUE TITLE
SuperiorSkyblock2 and EpicHoppers incompatibility

### ISSUE THREAD

**Issue by AustinFRG** [BG-Software-LLC/SuperiorSkyblock2#412]
### Minecraft's Version

purpur-1.17.1-1297.jar

### Plugin's Version

SuperiorSkyblock2-b209.jar and SuperiorSkyblock2-NashornEngine

### Describe the bug

my island limit is 50 funnel when a player puts 50 funnel on 1 island but when he puts for example 45 normal funnel and 5 epichoppers if he removes the 5 epichoppers to change places he can't for more account as if he had the 50 still if he puts 50 epichoppers and removes and tries to place again it will say he has reached the limit the epichoppers are not leaving the island even removing them the upper skyblock2 does not remove them.

### To Reproduce

using the funnels of the epichoppers plugin in the islands

### Additional Information

Hey, about this issue- EpicSpawners' API has a SpawnerBreakEvent. It was added about 7 months ago, let me know if you have any questions. (I'm a Support Rep on Songoda)
![jHkU7tD5](https://user-images.githubusercontent.com/18236516/127748418-e769ad01-8b33-4393-96e2-69122e014d3b.png)

I copied all of the other info from the other issue.

**Comment by AustinFRG** [comment]
I'm an idiot, I looked at EpicSpawners instead of EpicHoppers- anyway, uh yeah

**Comment by brasilcraft54** [comment]
> Eu sou um idiota, olhei para EpicSpawners em vez de EpicHoppers- de qualquer maneira, uh sim

a person already reported this on your website on June 20th you didn't even respond or anything.

**Comment by AustinFRG** [comment]
> > Eu sou um idiota, olhei para EpicSpawners em vez de EpicHoppers- de qualquer maneira, uh sim
> 
> a person already reported this on your website on June 20th you didn't even respond or anything.

A Songoda Developer is currently looking into it, there should be a fix soon.

**Comment by brasilcraft54** [comment]
> > > Eu sou um idiota, olhei para EpicSpawners em vez de EpicHoppers- de qualquer maneira, uh sim
> > 
> > 
> > a person already reported this on your website on June 20th you didn't even respond or anything.
> 
> A Songoda Developer is currently looking into it, there should be a fix soon.

it's been a month since i've been listening if this month arrives on the 20th and it doesn't resolve itself in 2 months songoda doesn't care if the plugins are affecting others they just want money we all know that.
can jot down ae for you to see how it takes 1-3 months for them to update 1 issue.

**Comment by OmerBenGera** [comment]
> > > > Eu sou um idiota, olhei para EpicSpawners em vez de EpicHoppers- de qualquer maneira, uh sim
> > > 
> > > 
> > > a person already reported this on your website on June 20th you didn't even respond or anything.
> > 
> > 
> > A Songoda Developer is currently looking into it, there should be a fix soon.
> 
> it's been a month since i've been listening if this month arrives on the 20th and it doesn't resolve itself in 2 months songoda doesn't care if the plugins are affecting others they just want money we all know that.
> can jot down ae for you to see how it takes 1-3 months for them to update 1 issue.

He told you they look into it, what else do you want from them?
Give them time to add a way to get this thing working out, and dont attack them here, as thats not the place to do so.
