### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Pandas0** [BG-Software-LLC/SuperiorSkyblock2#413]
### Minecraft's Version

Minecraft 1.17.1
Jar Paper-1.17.1-132

### Plugin's Version

Dev Build 209 + NashornEngine

### Describe the bug

During testing, a player did /is go and it crashed the server.

Sorry for being vague, not really sure how to describe it more

### To Reproduce

I am not exactly sure how to reproduce it, I will provide the crash log in Addition Information.

### Additional Information

https://pastebin.com/gyk4tg2N

**Comment by Pandas0** [comment]
Just an addon, I went back to the version I was using previously Dev Build 199 and it has yet to crash, including when I had the same player attempt the same thing he said he did.

**Comment by OmerBenGera** [comment]
> Just an addon, I went back to the version I was using previously Dev Build 199 and it has yet to crash, including when I had the same player attempt the same thing he said he did.

Interesting, I will look into that when I am back home

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it works for you.

**Comment by OmerBenGera** [comment]
I've been told it's fixed.
If it still occurs for you, let me know here.
