### ISSUE TITLE
Cannot limit the number of Villager per island

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#416]
### Minecraft's Version

Tuinity 1.17.1

### Plugin's Version

Dev Build #209 

### Describe the bug

We tried to limit the number of villager per island but we can still spawn villager with egg above the limit

### To Reproduce

Set a limit of villager on the island and use eggs to go above the limit you set.

**Comment by Zoiter7** [comment]
Hello, I have the same issues the villager limit by default is set for 10, maybe is coded by default in the code.
If you change it in the config in the **entity-limits** section not works.

**Comment by OmerBenGera** [comment]
I just tested it by setting a limit for villagers and it seems to work fine for me.

**Comment by OmerBenGera** [comment]
We moved the discussion regarding this issue to #478
