### ISSUE TITLE
Negative Island Level

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/SuperiorSkyblock2#419]
### Minecraft's Version

>....=>.... [15:15:09 INFO]: Checking version, please wait...
>.... [15:15:09 INFO]: This server is running Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 65 version(s) behind
Previous version: git-Paper-629 (MC: 1.16.5)

### Plugin's Version

SuperiorSkyBlock #209, Lastest dev build

### Describe the bug

When you create  an island, it gives you on /is top "Level: 1".
When you do and /is recalc or /is admin recalc, it goest at -2,000 level.

I placed an like 1,000 diamond blocks, and did /is recalc,  and i still have -2,000 level.
When you add more blocks, then level is okay.

/is top BEFORE RECALC: https://i.imgur.com/JeggNaJ.png
/is top AFTER RECALC: https://i.imgur.com/hge0AqC.png

EDIT: I tried with clean config, removed  plugin files, with all default configs,
but its all the same.

### To Reproduce

/is recalc

### Additional Information

I really need fast help. Thank you for great plugin.

**Comment by OmerBenGera** [comment]
There are problems with /is level, they are known and will be fixed soon.
