### ISSUE TITLE
Stacked Blocks Hologram disappear on restart

### ISSUE THREAD

**Issue by SenPr** [BG-Software-LLC/SuperiorSkyblock2#422]
### Minecraft's Version

Paper-778 (1.16.5)

### Plugin's Version

SuperiorSkyblock2 (b209) with RhinoEngine

### Describe the bug

Stacked blocks hologram gets removed on restart, stacked blocks still functional.
No holograms appear when trying to update by placing down new blocks on the stacks.

### To Reproduce

Place down stacked blocks on island, restart the server, see the stacked blocks have no holograms.

### Additional Information

default config files, no modification made

**Comment by OmerBenGera** [comment]
Try replicating the issue on a Paper/Spigot server with only SSB installed

**Comment by SenPr** [comment]
Tested it with just Paper/Spigot. Worked fine with no issues.

Likely an incompatibility with another plugin then. Sorry!

**Comment by OmerBenGera** [comment]
> Tested it with just Paper/Spigot. Worked fine with no issues.
> 
> Likely an incompatibility with another plugin then. Sorry!

Let me know if you find the plugin, I might be able to fix it

**Comment by SenPr** [comment]
Tried replicating it on a fresh server with all the same plugins (unconfigured and modified), still working fine.

On my production server however the bug is consistent. Unsure how this is happening

**Comment by SenPr** [comment]
Learned something, this happens when the chunk gets unloaded, and loaded again. The hologram does not appear.

**Comment by SenPr** [comment]
Found a solution, although still very much unsure what caused it.
Deleting my SuperiorWorld and SuperiorSkyblock2 folder fixed it.

My only reason I could think of is I installed Nashorn and GraalVM beforehand before changing to Rhino. Unsure how this would do anything?

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, it works fine for me.
There shouldn't be an issue with changing the engine mid-game, and it shouldn't affect holograms at all.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SenPr** [comment]
nothing so far, sorry. Seems like a false report for now.

**Comment by OmerBenGera** [comment]
If it happens again, let me know
