### ISSUE TITLE
IslandWorthUpdateEvent fail

### ISSUE THREAD

**Issue by FrancyMak** [BG-Software-LLC/SuperiorSkyblock2#423]
### Minecraft's Version

Tuinity .16.5-RO01-SNAPSHOT

### Plugin's Version

1.7.0-Dev209

### Describe the bug

IslandWorthUpdateEvent fail

### To Reproduce

Use java16 and NashronEngine as addon, when you place a block in the island you should get this error

**Comment by OmerBenGera** [comment]
Duplicate of #371
