### ISSUE TITLE
Cobblestone Generator & Leaf Decay

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/SuperiorSkyblock2#424]
### Minecraft's Version

>.... [21:30:07 INFO]: This server is running Tuinity version git-Tuinity-"9f3435b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

Lastest dev build 30/07

### Describe the bug

Cobblestone generator sometimes does not spawn an block.
You need to place block between and destroy it and works again but thats broken.

And I think that it gives this error:
https://paste.gg/p/anonymous/cd6c82416b43403d987bd963d2328c30

Leaf does not decay, I have on worldguard leaf-decay ALLOW but nothing..

### To Reproduce

//

### Additional Information

//

**Comment by OmerBenGera** [comment]
About the gens bug: will look into that.
About the leaf bug: if these are the leaf of the schematic, then yea - they are not decaying as otherwise the will decay almost instantly.

**Comment by rentexfamily** [comment]
Okay, please prioritize some high level bugs and try to fix it. Thank you for your plugin.

**Comment by OmerBenGera** [comment]
> Okay, please prioritize some high level bugs and try to fix it. Thank you for your plugin.

I will do my best to fix all the bugs as soon as possible.

**Comment by OmerBenGera** [comment]
Show me the ore gen values you have please.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.
