### ISSUE TITLE
Duplication of worth/value in spawners (ghost levels) 

### ISSUE THREAD

**Issue by radchazzyboy7** [BG-Software-LLC/SuperiorSkyblock2#429]
### Minecraft's Version

1.12.2 paperspigot

### Plugin's Version

1.7.0

### Describe the bug

You can place a spawner down then pick it up and your levels stay until you do /is level

### To Reproduce

Place a spawner, pick it up.

### Additional Information

https://youtu.be/oo_l5RebB74

**Comment by OmerBenGera** [comment]
Sounds like an issue with another plugin handling spawner breaking ans not letting SSB know about it.
Find the plugin that causes it and try it qgain without it.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by radchazzyboy7** [comment]
Nope. I tried checking spawner plugin and doesnt have anything to change that

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue with only SSB installed?

**Comment by radchazzyboy7** [comment]
Oh sorry my message didnt send. It still does it with ssb only I think.

**Comment by OmerBenGera** [comment]
test it for me please and let me know what the results are

**Comment by MineagePvP** [comment]
This issue occurs for not just spawners but sometimes blocks as well

**Comment by radchazzyboy7** [comment]
Yeah sometimes it happens with blocks but thats rare for me

**Comment by OmerBenGera** [comment]
What is this spawners plugin that you use?
It's probably not supported and therefore the counts are incorrect.

**Comment by radchazzyboy7** [comment]
I use XSpawners

**Comment by OmerBenGera** [comment]
Do you have a link for that plugin?

**Comment by JamesSmily** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by radchazzyboy7** [comment]
Its a discord bought thing

**Comment by OmerBenGera** [comment]
> 
> 
> Its a discord bought thing

I understand.
Well, the developer of that plugin needs to add support for his plugin. He can see an example of how to do it [here](https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/src/main/java/com/bgsoftware/superiorskyblock/hooks/SpawnersProvider_RoseStacker.java).
I am closing this as I can't do anything regarding this on my end :)
