### ISSUE TITLE
Island recalculation

### ISSUE THREAD

**Issue by TheMartyCZ** [BG-Software-LLC/SuperiorSkyblock2#431]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/45405349/128701831-e1b2cc10-357f-464d-b747-9c1de6d7971c.png)

### Plugin's Version

![image](https://user-images.githubusercontent.com/45405349/128701872-971a5e41-86ac-4479-859a-b27a62a44a0e.png)

### Describe the bug

When the island recalculation begins, all but one of the islands are recalculated. The player then cannot kick or build. He tells him that the island is still being recalculated, even though it is over. 

![image](https://user-images.githubusercontent.com/45405349/128702376-487c68da-ba9e-469d-a560-88d0f21ef028.png)

[superior.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6954314/superior.txt)

https://pastebin.com/WrPMtKrN

https://pastebin.com/u2aCZn2J

### To Reproduce

i dont know

**Comment by OmerBenGera** [comment]
Duplicate of #411
