### ISSUE TITLE
Players notified when a vanished player uses their island warps

### ISSUE THREAD

**Issue by MythricHD** [BG-Software-LLC/SuperiorSkyblock2#435]
### Minecraft's Version

Paper 1.12.2

### Plugin's Version

1.7.0 b199

### Describe the bug

When I am in vanish, the plugin supports certain aspects like not tabbing, etc but one that is missing is to hide when a vanished player warps to an island warp
https://cdn.discordapp.com/attachments/873610744275566592/875062914501980210/unknown.png

I'm using premium vanish. I assume this was just forgotten when vanish support was added

### To Reproduce

Use a vanish plugin and warp to a player's island warp. They will get notified that the vanish player warped to their island.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
