### ISSUE TITLE
visitor can right click sweet berries

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#436]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b209

### Describe the bug

Visitor can harvest/collect sweet_berries with right clicking them, without any permission, with default config.

### To Reproduce

Create an island, ask a visitor to harvest sweet_berries

**Comment by OmerBenGera** [comment]
A temp fix would be to add sweet barries to the interactable blocks list until it's patched.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
