### ISSUE TITLE
Bank Logs Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#438]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

SuperiorSkyBlock Dev build #209

### Describe the bug

When i use the player sorting or any of the other sorting in /is bank for some reason it does not sort and i tried it with only 2 players in the data and it still doesn't. In this gif you'll see two users debuffpvp and piggybacon69 but when i right click on debuffpvp it doesn't sort that name with all the logs first and doesn't put piggybacon last it just remains unsorted.

### To Reproduce

Look at all the info i have provided idk what else to state here

### Additional Information

https://gyazo.com/4125c2520122c38d3530c6ff31dbe516

This is my 2 stuff i changed which is the bank-logs.yml and island-bank.yml which i see that both don't have any issues so it has to do with the plugin
https://pastebin.com/pFH62nUk

**Comment by OmerBenGera** [comment]
Looks like you set the button to time-sort instead of money-sort.

**Comment by MineagePvP** [comment]
I mean this seems right to me what is wrong in it?


######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

title: '&3Bank Logs'
previous-menu: true

pattern:
  - '@ @ @ @ @ @ @ @ @'
  - '@ @ @ @ @ @ @ @ @'
  - '@ @ @ @ @ @ @ @ @'
  - '@ @ @ @ @ @ @ @ @'
  - '$ $ $ ! $ - $ $ $'
  - '$ $ % $ * $ ^ $ $'

slots: '@'
previous-page: '%'
current-page: '*'
next-page: '^'

time-sort: '!'
money-sort: '-'

items:
  '@':
    type: PAPER
    name: '&3&l&n{1}&r &8[&f#{0}&8]'
    lore:
      - '&f'
      - '&8&m------------------------'
      - '&6&lInfo'
      - '&7Status: &f{2}'
      - '&7Time: &f{3}'
      - '&7Amount: &f${4}'
      - '&8&m------------------------'
      - '&f&lRight-Click to filter logs'
      - '&f&lby this &a&lPlayer'
  '%':
    type: PAPER
    name: '{0}&fPrevious Page'
  '*':
    type: BOOK
    name: '&fPage {0}'
    lore: []
  '^':
    type: PAPER
    name: '{0}&fNext Page'
  '$':
    type: STAINED_GLASS_PANE
    data: 15
    name: '&f'
  '!':
    type: WATCH
    name: '&6Creation Time Sorter'
  '-':
    type: GOLD_INGOT
    name: '&6Transaction Sorter'

sounds:
  '@':
    type: BLOCK_CHEST_OPEN
    volume: 0.8
    pitch: 1

**Comment by OmerBenGera** [comment]
Upload your bank logs menu to pastebin and send it here so I can try replicating it myself

**Comment by MineagePvP** [comment]
https://pastebin.com/4NSWWgLR

**Comment by MineagePvP** [comment]
Island-bank.yml https://pastebin.com/tMmi3GRn

**Comment by OmerBenGera** [comment]
I looked at the gif again and the logs are sorted by money, am I missing something?

**Comment by MineagePvP** [comment]
look again https://gyazo.com/14ebadd4102dc9afcca18787e5d313a2 so there's debuffpvp on the first 2 logs papers and the rest is piggybacon69 and when i try to sort by transaction or creation time or right click to sort by that player in the menu which is also a feature on your plugin it doesn't do it and no errors or anything appear on console so it should work fine but it doesn't

**Comment by OmerBenGera** [comment]
> 
> 
> look again https://gyazo.com/14ebadd4102dc9afcca18787e5d313a2 so there's debuffpvp on the first 2 logs papers and the rest is piggybacon69 and when i try to sort by transaction or creation time or right click to sort by that player in the menu which is also a feature on your plugin it doesn't do it and no errors or anything appear on console so it should work fine but it doesn't

From my testings, it worked fine in terms of the creation time and money sorts. Do you have a video showing that it's inaccurate? Are you able to replicate the issue yourself on a server with only SSB installed? If so, I recommend doing that with smaller values so it's easier to see the issue, and not with such big numbers.

**Comment by MineagePvP** [comment]
ok i will try tomorrow as i am going to sleep now and as soon as i do i will let you know

**Comment by MineagePvP** [comment]
btw if i wanna look at past conversations from github issues i made is there a way on here?

**Comment by MineagePvP** [comment]
just to rephrase what my issue is it happens that the two buttons that sort actually do work but when you right click as the default lore shows you have that feature it doesn't do anything as seen in this gif of the default plugin untouched files
https://gyazo.com/c248b01fb713022b250af4edf97b12b7

**Comment by OmerBenGera** [comment]
I understand the issue now, sorry for the inconvenience.
I will look into that as soon as possible.

**Comment by MineagePvP** [comment]
ok thanks i appreciate it

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
