### ISSUE TITLE
Cobble Generator Mission. 

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#440]
### Minecraft's Version

1.16.5 Purpur

### Plugin's Version

209

### Describe the bug

It doesn't seem to listen to the bucket empty event OR I could have done something wrong. 

### To Reproduce

  cob-gen:
    mission-file: BlocksMissions
    island: false
    auto-reward: true
    disband-reset: true
    rewards:
      commands:
      - eco give %player% 500
      - lp user %player% permission set mission.gearup1 true
      - is admin msg %player% &e&lMission | &7Successfully finished the mission CobGen!
    required-blocks:
      '1':
        types:
        - ICE
        - LAVA_BUCKET
    blocks-placement: true
    reset-after-finish: false
    only-natural-blocks: false
    only-show-if-required-completed: false
    icons:
      not-completed:
        type: PAPER
        name: '&aCobble Gen'
        lore:
        - '&7Create a Cobble Generator.'
        - ''
        - '&6Required Materials:'
        - '&8 - &7x1 Cobble Generator'
        - ''
        - '&6Rewards:'
        - '&8 - &7$500'
        - ''
        - '&6Progress: &7100%'
        - '&6Times Completed: &7{2}/1'
      can-complete:
        type: PAPER
        name: '&aCobble Gen'
        lore:
        - '&7Create a Cobble Generator.'
        - ''
        - '&6Required Materials:'
        - '&8 - &7x1 CobbleGen'
        - ''
        - '&6Rewards:'
        - '&8 - &7$500'
        - ''
        - '&6Progress: &7100%'
        - '&6Times Completed: &7{2}/1'
        enchants:
          DURABILITY: 1
        flags:
        - HIDE_ENCHANTS
      completed:
        type: MAP
        name: '&aCobble Gen'
        lore:
        - '&7Create a Cobble Generator.'
        - ''
        - '&6Progress: &7100%'
        - '&6Times Completed: &71/1'
        - '&a&l ✔ &7Already Claimed.'

**Comment by OmerBenGera** [comment]
The BlocksMissions listens to block interactions, nothing else (aka when a block is broken or placed).
If you want another mission to listen to other events, feel free to create your own jar or request a developer to do that for you.
You can't break/place "LAVA_BUCKET", and therefore this mission will not work for you.
