### ISSUE TITLE
Upgrades Issues

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#441]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Dev Build #215

### Describe the bug

I've been trying to work on this all night and cannot seem to fix it but i'm trying to set the limit of hoppers per island to 8, 16, 48 and 64 but for some reason it gives double that limit for each and i cannot seem to make it work and it doesn't just do this for hoppers but everything in that config

    '1':
      price: 100000.0
      price-type: "Money"
      block-limits:
        HOPPER: 8
      commands:
        - 'island admin setupgrade %player% hoppers-limit 2'
        - 'island admin msg %player% &c&l[!] &6$100,000 has been taken from your account'
    '2':
      price: 300000.0
      price-type: "Money"
      block-limits:
        HOPPER: 16
      commands:
        - 'island admin setupgrade %player% hoppers-limit 3'
        - 'island admin msg %player% &c&l[!] &6$300,000 has been taken from your account'
    '3':
      price: 500000.0
      price-type: "Money"
      block-limits:
        HOPPER: 32
      commands:
        - 'island admin setupgrade %player% hoppers-limit 4'
        - 'island admin msg %player% &c&l[!] &6$500,000 has been taken from your account'
    '4':
      price: 1000000.0
      price-type: "Money"
      block-limits:
        HOPPER: 48
      commands:
        - 'island admin setupgrade %player% hoppers-limit 5'
        - 'island admin msg %player% &c&l[!] &6$1,000,000 has been taken from your account'
    '5':
      price: 0.0
      price-type: "Money"
      block-limits:
        HOPPER: 64
      commands:
        - 'island admin msg %player% &8[&3Sky&6Block&8] &cYou are already at the max tier'

### To Reproduce

na

### Additional Information

na

**Comment by OmerBenGera** [comment]
When you run /is admin show, does it show twice the limit?

**Comment by MineagePvP** [comment]
it's like entirely screwed up idk how to explain it to be honest i've spent 6 hours on just this file alone tonight
like also here as you can see i set the upgrades to those island sizes but it makes them beyond those sizes

    '1':
      price: 300000.0
      price-type: "Money"
      border-size: 100
      commands:
        - 'island admin setupgrade %player% border-size 2'
        - 'island admin msg %player% &c&l[!] &6$300,000 has been taken from your account'
    '2':
      price: 800000.0
      price-type: "Money"
      border-size: 150
      commands:
        - 'island admin setupgrade %player% border-size 3'
        - 'island admin msg %player% &c&l[!] &6$800,000 has been taken from your account'
    '3':
      price: 1000000.0
      price-type: "Money"
      permission: 'upgrade.size.donor'
      border-size: 200
      commands:
        - 'island admin setupgrade %player% border-size 4'
        - 'island admin msg %player% &c&l[!] &6$1,000,000 has been taken from your account'
    '4':
      price: 2000000.0
      price-type: "Money"
      border-size: 250
      commands:
        - 'island admin setupgrade %player% border-size 5'
        - 'island admin msg %player% &c&l[!] &6$2,000,000 has been taken from your account'
    '5':
      price: 0.0
      price-type: "Money"
      border-size: 250
      commands:
        - 'island admin msg %player% &8[&3Sky&6Block&8] &cYou are already at the max tier'

**Comment by MineagePvP** [comment]
is it level based and we cannot change the size cause that's what it seems like and i've tried effortlessly and for some it seems as if it multiplies the numbers by what digit i don't know

**Comment by OmerBenGera** [comment]
I dont understand what the issue is... you first talked about issues with hopper limits, now the issue is with the border size?
Please give a more clear description of the issue.

**Comment by MineagePvP** [comment]
so to start of when i set those upgrade for islands to be that radius around it doubles it and triples and so forth it doesn't set them as what's shown

**Comment by MineagePvP** [comment]
when i set the hopper limits per island it does the exact same thing double, triples and so forth and also hoppers don't use the default limit in the main superiorskyblock config.yml

**Comment by OmerBenGera** [comment]
> 
> 
> when i set the hopper limits per island it does the exact same thing double, triples and so forth and also hoppers don't use the default limit in the main superiorskyblock config.yml

Upgrade your island to hopper limit #2, run /is admin show and send me what it shows.

**Comment by MineagePvP** [comment]
well i guess the hopper thing not working including upgrades and placement randomly happens especially when deleting islands and remaking them sometimes

**Comment by MineagePvP** [comment]
as far as border size goes those values still do not give the size that they show

**Comment by MineagePvP** [comment]
i figured out one major issue your plugin does not reset the world border sometimes when you do /is delete and remake that same island

**Comment by MineagePvP** [comment]
So the issue is with your plugin apparently when an island gets deleted or a player deletes their own island the border remains the same and this is my config so basically whenever you do reset it starts with the size displayed in upgrade '1'
then when i upgrade it charges me 1 mil but gives me upgrade size from '2' then i upgrade again it charges me 2 mil which belongs to '2' and gives me upgrade '3' and then when i upgrade again it charges me 3 mil and sends me to the max level category since there's no more levels but still charges me 3 mil which belongs to category '3'











    '1':
      price: 1000000.0
      price-type: "Money"
      border-size: 75
      commands:
        - 'island admin setupgrade %player% border-size 2'
        - 'island admin msg %player% &c&l[!] &6$1,00,000 has been taken from your account'
    '2':
      price: 2000000.0
      price-type: "Money"
      border-size: 100
      commands:
        - 'island admin setupgrade %player% border-size 3'
        - 'island admin msg %player% &c&l[!] &6$2,00,000 has been taken from your account'
    '3':
      price: 3000000.0
      price-type: "Money"
      border-size: 125
      commands:
        - 'island admin setupgrade %player% border-size 4'
        - 'island admin msg %player% &c&l[!] &6$3,000,000 has been taken from your account'
    '4':
      price: 0.0
      price-type: "Money"
      border-size: 125
      commands:
        - 'island admin msg %player% &8[&3Sky&6Block&8] &cYou are already at the max tier'

**Comment by MineagePvP** [comment]
but like i said it keeps using the border size from '1' every time i delete and start a new island

**Comment by OmerBenGera** [comment]
> but like i said it keeps using the border size from '1' every time i delete and start that same island again and do the same thing with all the island and then all those islands keep on starting with 150 block radius even though the default for all islands is 101

According to your upgrade file, the default border size is 75 blocks radius - aka, 150 blocks in size. I think you dont understand how the upgrades work - every island starts with upgrade level 1, and the price of upgrade 1 is the price to upgrade to the next level, and not the price to upgrade to that level (so 2mil is to upgrade from upgrade 2 to 3, and not from 1 to 2)

**Comment by NameIsCam** [comment]
I wanted to get in on this conversation, as it was a discussion on the discord talking about this. Even I didn't understand how the system was working, and why the default value of hoppers (for example) is 16, but if you want to "reset" someone's upgrades, you would be setting the hoppers-limit to 1 (upgrade). This is actually setting the hopper limit of a player's island to the number that is specified in the upgrades menu. A fix would be to set the first upgrade to the default value and go on from there. I believe this would fix the situation, as I just tested it and it seems it did. 

On a side note, if possible you could add a /island admin setupgrade <name> <upgrade> <number/reset>, and it clears the upgrades from the island and sets the hopper limit back to the default settings in the config.yml. Just a thought, granted saying something is a lot easier than doing it.

**Comment by OmerBenGera** [comment]
> 
> 
> I wanted to get in on this conversation, as it was a discussion on the discord talking about this. Even I didn't understand how the system was working, and why the default value of hoppers (for example) is 16, but if you want to "reset" someone's upgrades, you would be setting the hoppers-limit to 1 (upgrade). This is actually setting the hopper limit of a player's island to the number that is specified in the upgrades menu. A fix would be to set the first upgrade to the default value and go on from there. I believe this would fix the situation, as I just tested it and it seems it did.
> 
> On a side note, if possible you could add a /island admin setupgrade <number/reset>, and it clears the upgrades from the island and sets the hopper limit back to the default settings in the config.yml. Just a thought, granted saying something is a lot easier than doing it.

there's no way to clear an upgrade level from an island - any island must have an upgrade level. The default level for all islands is 1. If you want to read more about upgrades, open the wiki page and you'll find there more information, including the information I mentioned above.

**Comment by OmerBenGera** [comment]
Also, here's the note for the default-values section, which can be found in the config, right above the section:
```
# All the default values for new islands that are created.
# Please note: Upgrades with built-in values (upgrades that don't run commands to update values),
# will override all the values here. For example, if I set an upgrade that changes generator rates,
# there's no need to touch the default generator rates here, as new islands will get the rates from
# the upgrade, and not from here.
```
As stated, if you have set upgrades for a specific value, the upgrade value will override the default value, as it's useless in this matter.

**Comment by MineagePvP** [comment]
ya you can close this now i figured it out myself anyways but i appreciate the reply and there's not sufficient documentation for players so i thought i'd ask here cause the staff on there also give short answers
