### ISSUE TITLE
Duplication bug 

### ISSUE THREAD

**Issue by kizoukun** [BG-Software-LLC/SuperiorSkyblock2#443]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

WildStacker Version 3.6.0-DEVb171
SuperiorSkyblock2 1.7.0-DEVb209

### Describe the bug

Duplication bug, with is upgrade SuperiorSkyblock2

### To Reproduce

/is upgrade SuperiorSkyblock2 Premium mob drops and kill Llama with a chest on it and put item inside the chest and when you kill the Llama it multiplied by the amount your island mob drops

### Additional Information

Only work when using WildStacker i tested with only SuperiorSkyblock doesn't work not sure with other plugins

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
