### ISSUE TITLE
Bow can destroy chorus flower

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#444]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b215

### Describe the bug

On 1.16, if you shot an arrow on a chorus flower, it breaks it.

Even without any permission, a visitor can break your chorus flower with a bow.

### To Reproduce

Go on an island as a visitor, shot an arrow on a chorus flower

### Additional Information

(it happens on 1.16 since mojang changed that)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
