### ISSUE TITLE
End portal count issue

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#445]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

Superior b215

### Describe the bug

When you place an end portal frame
it counts as 1 (using %superior_island_count_end_portal_frame%), so it's normal.
<img width="960" alt="Screenshot_5593" src="https://user-images.githubusercontent.com/31826333/129420938-8b9e76a5-b808-4e52-88ed-34fa23f09b89.png">

But if you place an ender eye on it, it will count as 2
<img width="1042" alt="Screenshot_5594" src="https://user-images.githubusercontent.com/31826333/129421036-b827b81e-a272-4a1b-b76d-6599c1488ebc.png">

And if I do /is recalc, it counts now 1.

<img width="1040" alt="Screenshot_5595" src="https://user-images.githubusercontent.com/31826333/129421101-567dc1c4-1622-47fe-a58b-10f49192ae63.png">
("ton ile est niveau XX" means "your island is level XX", as I recalculate my island.)

It's a problem for me as I got a quest "get 12 ender portal frame on your island" but player can cheat this quest.

### To Reproduce

Place a portal frame, place an ender eye on it, it will count as 2 portal frame until you recalculate your island

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
