### ISSUE TITLE
Island Hoppers Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#446]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

DEVb215

### Describe the bug

I seen someone reported it earlier as well but sometimes hoppers are able to be place regardless of max amount allowed

### To Reproduce

Try the configs i gave you cause i have done nothing wrong on them

### Additional Information

GIF: https://gyazo.com/773670f60b92193574f24a4eb9b8e039    Those were all placed within 2 hours and it randomly allows to place so not every time so you just have to be lucky

**Comment by OmerBenGera** [comment]
Check out latest dev build, I fixed an issue related to that that might fix your issue as well.

**Comment by MineagePvP** [comment]
Mark this as solved the issue was fixed
