### ISSUE TITLE
Block Break Mission Bypass

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#447]
### Minecraft's Version

1.17 Purpur

### Plugin's Version

Dev build 199

### Describe the bug

For the island missions block break one, you can use pistons to push blocks and it will count as breaking it.

### To Reproduce

Have a block break mission. Use a piston to push the block.

### Additional Information

Here is a link to a video since the video is too big: https://www.mediafire.com/file/2bhqcxjb4drlr4r/video.mp4/file

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
