### ISSUE TITLE
Island Warp Editing Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#452]
### Minecraft's Version

[18:12:50 INFO]: This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Dev build #221

### Describe the bug

When editing a warp and changing its values like name location and status it does not update them in the placeholders within that changing menu

### To Reproduce

NA

### Additional Information

https://gyazo.com/ff519f20e58d3ecac829ee6911c4d121

**Comment by MineagePvP** [comment]
NVM i found it in the language file but you might wanna add this since not everyone will know and assume it's an issue if it ever does happen

**Comment by OmerBenGera** [comment]
Thats intended, as players need to know how the placeholders look like so they can use them if they want to.
