### ISSUE TITLE
Can pickup items on others islands even without permission

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#453]
### Minecraft's Version

1.17.1 Purpur 1330

### Plugin's Version

dev b215

### Describe the bug

This issue popped up after updating from 209 to 215, could not find what could possibly be related. Players are able to pickup items on others islands regardless of island settings/permissions.

### To Reproduce

Simply attempt to pickup items on another persons island when their permissions are set to deny pickup.

### Additional Information

https://youtu.be/TrU91wBJoq0

**Comment by OmerBenGera** [comment]
I can't replicate the issue, seems to work fine for me

**Comment by Skizzles** [comment]
@OmerBenGera 

Tested with just SSB and Vault installed and still had the issue. https://screenshots.skizzles.me/wAnA3/defEwUlo98.mp4

**Comment by OmerBenGera** [comment]
Try it using Paper instead of Purpur, maybe that's the cause of the issue

**Comment by JamesSmily** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by OmerBenGera** [comment]
I had an idea what could cause it - Paper has another event to pickup items, called "PlayerAttemptPickupItemEvent", which is called before PlayerPickupItemEvent. WildStacker for example uses this event to give items to players, and it might have conflicted with SSB.

Try latest dev build, I added support for that event, hopefully it will be fixed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
my issue seems resolved in latest, gonna close this
