### ISSUE TITLE
Island Coop Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#454]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Dev #221

### Describe the bug

I got an error in console when i did sent a coop request to a player

### To Reproduce

NA

### Additional Information

https://pastebin.com/gPMAKExf

**Comment by OmerBenGera** [comment]
Something with your coops menu. Make sure all the items in the menu are correct and valid.

**Comment by MineagePvP** [comment]
fixed this issue mark it as solved idk why i had to reset the config for it to work but i know i didn't do anything wrong it was weird
