### ISSUE TITLE
Island Coops Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#455]
### Minecraft's Version

[05:34:35 INFO]: This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

build #221

### Describe the bug

For some reason island coop keeps making a player leader when i coop them when it's supposed to be guest by default in the plugin i presume

### To Reproduce

Na

### Additional Information

https://gyazo.com/81ae64c122ef2829bd57036d6b70ce17

**Comment by OmerBenGera** [comment]
that's a visual bug, they are not the actual leader of the island, don't worry.

**Comment by OmerBenGera** [comment]
You an remove the role from the coop menu, as it shows the role of the player in their island. all the roles for all the coop members is undefined, as they are not members of the island.
