### ISSUE TITLE
Plugin shuts down server nashron not working 

### ISSUE THREAD

**Issue by Sefovski** [BG-Software-LLC/SuperiorSkyblock2#458]
### Minecraft's Version

1.8.8 Default Spigot

### Plugin's Version

Latest dev build

### Describe the bug

I just staryed u the server with neshron in modules folder and i got this
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6988089/latest.log)

### To Reproduce

I just staryed u the server with neshron in modules folder and i got this
[latest.log](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6988089/latest.log)

### Additional Information

Nope.

**Comment by OmerBenGera** [comment]
upload the file to pastebin or something similar to that.

**Comment by Sefovski** [comment]
https://www.mediafire.com/file/i1v56hvg477sfky/spigot.jar/file

**Comment by OmerBenGera** [comment]
Please upload the logs file to pastebin, I have nothing to do with your spigot jar, not to mention that I am not downloading files from untrusted sources.

**Comment by Sefovski** [comment]
https://pastebin.com/2ZrtYeru

**Comment by OmerBenGera** [comment]
The engine jar that you installed seems to be corrupted.
Redownload it from github and use it instead of the jar you have now.

**Comment by Sefovski** [comment]
Still same thing

**Comment by OmerBenGera** [comment]
You are running version 1.8.8 of minecraft, why are you even using the nashron engine?
You can't use Java 15/16 for that version, so there's no need to use the nashron engine neither.
Get rid of it as it will not work on 1.8.8, as it's not designed to work with that version.
Let me know if it works

**Comment by Sefovski** [comment]
Does not work if i get rid of it do i install lower java version?

**Comment by OmerBenGera** [comment]
> 
> 
> Does not work if i get rid of it do i install lower java version?

You need to install a lower java version, as 1.8.8 doesn't support newer versions anyways.

**Comment by OmerBenGera** [comment]
I am closing this as there doesn't seem to be a bug here.
