### ISSUE TITLE
Calculations Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#459]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

build #221

### Describe the bug

The plugin does not calculate the exact values for blocks and spawners placed on islands in the gif it shows 7,999 for the hopper but it's actually 8,000

### To Reproduce

try it yourself

### Additional Information

https://gyazo.com/e4963a161f83277f55ebbac9361bef5c

**Comment by OmerBenGera** [comment]
sounds like an issue with rounding, which means it's probably fine.

**Comment by MineagePvP** [comment]
Is it possible you could fix it? cause wether i turn off rounding or enable it, it still does the same thing

**Comment by OmerBenGera** [comment]
I don't understand the issue tho, the values are fine - 7999 and 8000 is literally the same.

**Comment by OmerBenGera** [comment]
also the gif doesn't show anything, only that it shows 7,999 as the worth value of the island...

**Comment by MineagePvP** [comment]
for some reason now it works fine with this new build idk i think it randomly happens

**Comment by MineagePvP** [comment]
also what's the difference between island counts, worth and level for items?

**Comment by OmerBenGera** [comment]
> 
> 
> also what's the difference between island counts, worth and level for items?

/is counts shows all the blocks in your island that have a value or a limit. worth is the worth of the block and level is the level of the block, which can all be configured in the files under block-values folder.
