### ISSUE TITLE
You can grab mobs with fishing rod

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#460]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b221

### Describe the bug

When you are visitor on an island, if you can fish, you can also grab mobs with the fishing rod and kill them.

### To Reproduce

https://www.youtube.com/watch?v=QgHT2au7o1U

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
