### ISSUE TITLE
RoseStacker stacked blocks don't give value. 

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#461]
### Minecraft's Version

1.16.5 Purpur. 

### Plugin's Version

SuperiorSkyblock2-b221.jar

Rosestacker 1.3

### Describe the bug

When stacking blocks with rosestacker instead of superiorskyblock it doesn't give value (it used to ?).

### To Reproduce

Stack value blocks on your island with the help of rosestacker. Disable blockstacking on superiorskyblock. 

Rosestacker config: https://pastebin.com/cikp8y9p
SBB config: https://paste.gg/p/anonymous/b37aa733c55e400bac62b0df55b73f77

**Comment by OmerBenGera** [comment]
Do your stacked blocks have a value when running /is value and holding them in your hand?

**Comment by Pikaronga** [comment]
> 
> 
> Do your stacked blocks have a value when running /is value and holding them in your hand?

when I place the blocks normally they give value. And they show in the is value. But when placed into a stack they don't give value.

**Comment by OmerBenGera** [comment]
I've just tested it and it works flawlessly fine.

**Comment by Pikaronga** [comment]
> 
> 
> I've just tested it and it works flawlessly fine.

Is there any problems in my files then? or what could be causing it? wtf

**Comment by OmerBenGera** [comment]
> 
> 
> > I've just tested it and it works flawlessly fine.
> 
> Is there any problems in my files then? or what could be causing it? wtf

this has nothing to do with your files.
In /is counts, do you see your blocks there?

**Comment by Pikaronga** [comment]
> 
> 
> > > I've just tested it and it works flawlessly fine.
> > 
> > 
> > Is there any problems in my files then? or what could be causing it? wtf
> 
> this has nothing to do with your files.
> In /is counts, do you see your blocks there?

I see the physical blocks. But not the ones that are in the stacks. if you understand what I mean.

**Comment by OmerBenGera** [comment]
> 
> 
> > > > I've just tested it and it works flawlessly fine.
> > > 
> > > 
> > > Is there any problems in my files then? or what could be causing it? wtf
> > 
> > 
> > this has nothing to do with your files.
> > In /is counts, do you see your blocks there?
> 
> I see the physical blocks. But not the ones that are in the stacks. if you understand what I mean.

Do you see the correct amount of blocks in /is counts or not

**Comment by Pikaronga** [comment]
i see the blocks that are not in the stack. So for example if I have one stack with 100 it counts 1 and disregards the stacked ones.  so the answer would be no.

**Comment by OmerBenGera** [comment]
> 
> 
> i see the blocks that are not in the stack. So for example if I have one stack with 100 it counts 1 and disregards the stacked ones. so the answer would be no.

if you run /is level, does it help?

**Comment by Pikaronga** [comment]
no

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue with only SuperiorSkyblock and RoseStacker installed on your server?

**Comment by Pikaronga** [comment]
yeah odd. It seems to not happen. Will try to find the culprit & see what we can do about it

**Comment by Pikaronga** [comment]
ofcourse it's one of advancedplugins plugins lmao </3

**Comment by OmerBenGera** [comment]
> ofcourse it's one of advancedplugins plugins lmao </3

Do you know which one exactly? I might be able to add support.

**Comment by Pikaronga** [comment]
AdvancedSpawners

**Comment by OmerBenGera** [comment]
I think I know what the issue is - the plugin sees that AdvancedSpawners is installed, and therefore skips RoseStacker hook, and therefore it's not working.
I will see what can be done regarding this.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Pikaronga** [comment]
> 
> 
> Fixed in latest dev build

It's partly fixed as the GUI adding now adds value. But now when placing normal value blocks / placing them into the stack it doesn't give value at all.

**Comment by Pikaronga** [comment]
But when executing /is level it calculates the stack + the placed blocks. And it starts counting the new placed blocks to ?? no idea how that happened.

**Comment by Pikaronga** [comment]
Okay so i figured some other things out. When stacking blocks and then breaking the stacks either by sneak breaking or gui breaking. The value doesn't get removed. This is fixed upon a recalc but it should update live as it usually does as this leaves a option for players to abuse this and get unlimited value in no time and climb the ranks just until a restart or a recalc is forced. Which could cause confusion.

**Comment by OmerBenGera** [comment]
> 
> 
> Okay so i figured some other things out. When stacking blocks and then breaking the stacks either by sneak breaking or gui breaking. The value doesn't get removed. This is fixed upon a recalc but it should update live as it usually does as this leaves a option for players to abuse this and get unlimited value in no time and climb the ranks just until a restart or a recalc is forced. Which could cause confusion.

I'll check what can cause it.

**Comment by OmerBenGera** [comment]
From my testings, it seems you get an additional block when running /is calc.
However, when placing the first item into the stack, it doesn't count it.
I will fix both issues, hopefully it will fix the issues you mentioned as well.

**Comment by OmerBenGera** [comment]
I found another issue when using the destroy button that the plugin doesn't detect this action.
This is an issue with RoseStacker, there doesn't seem to be any event that is fired when it happens, causing SSB to not know about this action.
I contacted their developers regarding this.

**Comment by Esophose** [comment]
The destroy button thing has been fixed in RoseStacker v1.3.1 which has just been released on Spigot.

**Comment by OmerBenGera** [comment]
> 
> 
> The destroy button thing has been fixed in RoseStacker v1.3.1 which has just been released on Spigot.

Thanks.
@Pikaronga , mind checking it now? Let me know if there are more issues regarding this.

**Comment by Pikaronga** [comment]
> 
> 
> > The destroy button thing has been fixed in RoseStacker v1.3.1 which has just been released on Spigot.
> 
> Thanks.
> @Pikaronga , mind checking it now? Let me know if there are more issues regarding this.

seems to work as it should now. Thanks for the fast fixes!
