### ISSUE TITLE
Superior SkyBlock DS Error

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#462]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

build #221

### Describe the bug

So it gives the ds store error since i am running my server on a mac server tower system and it's a mac file so i cannot do anything about it cause osx makes them and the owner of a plugin called chatcontrol also fixed this issue before if you know of that plugin

### To Reproduce

NA

### Additional Information

https://pastebin.com/n5vEu0uR

**Comment by MineagePvP** [comment]
It won't let me or the players join the server

**Comment by OmerBenGera** [comment]
ignore it / get rid of that file

**Comment by MineagePvP** [comment]
can't the os generates them

**Comment by MineagePvP** [comment]
could you possibly add a fix for it?

**Comment by OmerBenGera** [comment]
I will look into that.
Anyways, I don't recommend running your server on a MAC machine.

**Comment by MineagePvP** [comment]
well before i had a 600 player server running on a mac server tower back in the day and never had any issues with connection or lag pc is trash in my opinion it's just people hate mac cause it's too overpriced and only gamers hate mac tbh

**Comment by OmerBenGera** [comment]
> 
> 
> well before i had a 600 player server running on a mac server tower back in the day and never had any issues with connection or lag pc is trash in my opinion it's just people hate mac cause it's too overpriced and only gamers hate mac tbh besides mac came before windows

Is it a troll? tf?

**Comment by OmerBenGera** [comment]
I checked the code and besides showing an error, it does nothing, therefore you can safely ignore the error.

**Comment by MineagePvP** [comment]
no it causes me not to be able to join nothing will happen on your end cause you're not on os but on mine it does cause ds stores are used as a storage and transfer system to communicate between the system and files

**Comment by OmerBenGera** [comment]
> 
> 
> no it causes me not to be able to join nothing will happen on your end cause you're not on os but on mine it does cause ds stores are used as a storage and transfer system to communicate between the system and files

why would it not let players join the server, if it only prints an error? Maybe that's something different that causes them to not join?

**Comment by OmerBenGera** [comment]
Check out latest dev build, I made it so the plugin will only try to register jar files - let me know if it helps.

**Comment by MineagePvP** [comment]
mark this as solved cause it got fixed with the new build and thanks
