### ISSUE TITLE
lol you need to add another msg for this

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#463]
### Minecraft's Version

1.8.8

### Plugin's Version

Dev #224

### Describe the bug

when doing /is value piggybacon69  which is a player name it says the block piggybacon69 is worthless there should be a message added that says please enter a block id or name or block does not exist lol

https://gyazo.com/e59ace26f687cc6c20ee36394076b815

### To Reproduce

na

**Comment by OmerBenGera** [comment]
There can be custom block ids, therefore its not possible to be added.
