### ISSUE TITLE
Island Values Not Being Calculated

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#464]
### Minecraft's Version

1.8.8

### Plugin's Version

Build #224

### Describe the bug

idk if this is an issue but i hooked up shopguiplus and when i place blocks it doesn't add to the value or level for spawners 
or would i need to add every block with the level and value manually?

also the default island level value for spawners where does it get that from cause i never added that? https://gyazo.com/336534ad79d6b192fe0147fd06a4b375

### To Reproduce

na

**Comment by MineagePvP** [comment]
Also could you please not close this until i say mark as solved so i can actually take the time to read your response so i don't ask questions later and don't miss your answer please

**Comment by OmerBenGera** [comment]
Look for the following section:
```
# Should the worth values be synced with other prices providers?
# You can set the following values: NONE (disabled), BUY (buy prices), SELL (sell prices)
# Supported Providers: ShopGUIPlus
sync-worth: NONE
```
Set it to "BUY" if you want buy prices of SGP or "SELL" if you want sell prices of SGP.
then, you'll see the values of SGP for your blocks using /is value - however, make sure you don't have manually set worth values in the worth file, as it will override the values of SGP.
about the gif you shown - every island has a schematic, which contains blocks, aka values to your island. You can check the blocks on your island using /is counts. If you want to offset the values to match the schematic values (in other words, start at level 0 and worth level 0), you can do that by setting the schematic-offset section in the config for your worlds to true.

I am closing this as there's no bug in this thread. If you want to further discuss about anything, feel free to ask in the discord, and I am sure someone will help you there. Also, even if I close the issue, you can still send messages, so there's no need to keep this issue opened. You are confused between tickets that used to be on the discord and issues on github - issues on github are only for reporting bugs, and even if I close them, you can still send messages there. However, they are not used for getting support from me, and therefore I kindly ask you to stop opening issues for every question you have.
