### ISSUE TITLE
Tnt block recognized as installed block after explosion

### ISSUE THREAD

**Issue by Dot0420** [BG-Software-LLC/SuperiorSkyblock2#465]
### Minecraft's Version

Paper 1.12.2

### Plugin's Version

1.7.0-DEVb167

### Describe the bug

SuperiorSkyblock2 plug-in folder config.yml limited TNT blocks 10 times in block-limits and limited tnt installation, but after exploding tnt, the block was restricted.

### To Reproduce

Look at all the info i have provided idk what else to state here

### Additional Information

https://www.youtube.com/watch?v=zPzEbZ5Fa1w
https://pastebin.com/rwDhdRk2

**Comment by Dot0420** [comment]
> ### 마인크래프트 버전
> 종이 1.12.2
> 
> ### 플러그인 버전
> 1.7.0-DEVb167
> 
> ### 버그 설명
> SuperiorSkyblock2 플러그인 폴더 config.yml은 블록 제한 및 제한된 tnt 설치에서 TNT 블록을 10회 제한했지만 tnt를 폭발시킨 후 블록이 제한되었습니다.
> 
> ### 재현하기 위해
> 내가 idk에 제공한 모든 정보를 보십시오.
> 
> ### 추가 정보
> https://www.youtube.com/watch?v=zPzEbZ5Fa1w

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
