### ISSUE TITLE
Warps Editing

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#466]
### Minecraft's Version

1.8.8

### Plugin's Version

#224

### Describe the bug

So i wanna remove this off the gui https://gyazo.com/94e4fadb79b604cb08b7e8da0006e4ba so that people can't go into the 3rd menu and the plugin allows me to do the same thing by removing the items off the guis but for this certain feature it doesn't and gives me this error https://pastebin.com/amU61tfW so essentials i don't wanna remove
the location set, rename warp or warp status buttons just that so people can't access the last menu could you please implement that?

items:
  '!':
    type: SIGN
    name: '&6&lRename Warp'
    lore: []
  '~':
    type: ENDER_PEARL
    lore:
      - '&f '
      - '&f&l{0} is used for the warp &a&lName'
      - '&f&l{2} is used for the warp &a&lStatus'
      - '&f&lClick to edit the &a&l&nIcon'
  '$':
    type: IRON_PLATE
    name: '&6&lWarp Location Set'
    lore: []
  '%':
    type: IRON_FENCE
    name: '&6&lWarp Status'
    lore: []
  '+':
    type: STAINED_GLASS_PANE
    data: 15
    name: '&f'
    lore: []

### To Reproduce

na

**Comment by OmerBenGera** [comment]
Feature requests should be submitted under the discussions section, not the issues one.
