### ISSUE TITLE
SuperiorSkyblock2 and JetMinions and CloudCollectors incompatibility

### ISSUE THREAD

**Issue by brasilcraft54** [BG-Software-LLC/SuperiorSkyblock2#468]
### Minecraft's Version

purpur-1.17.1 last version

### Plugin's Version

SuperiorSkyblock2-b227 and SuperiorSkyblock2-NashornEngine

### Describe the bug

it seems to me that superiorskyblock when it has a plugin chunk collector or minions it crashes the server somehow I have these 2 plugins in another skyblock server 1.12. 2 and I don't have this problem and this only happens with superiorskyblock it seems that it works with these plugins as entities and this generates the lag until the server crashes. I already contacted the author of jetminions and cloudcollectors and they both told me the same thing that the problem is superiorskyblock and how it deals with the entities, see my timings when I put cloudcollectors or jetminions on superiorskyblock.

https://timings.pl3x.net/?id=21212d3e9e9c42e69d7262bfad3e0cb7

photo -> https://prnt.sc/1pr1o05

they have already sent me several different jar and nothing solved the problem is in the superiorskyblock somehow it is dealing with entities or something.

### To Reproduce

add cloudcollectors or jetminions to servers with superiorskyblock2.

**Comment by brasilcraft54** [comment]
with jetminions the problem takes about 5-6 hours but with cloudcollectors is fast just put the chunk collector on the ground let accumulate about 100k mobs grouped by rosestacker and kill, then just keep killing and ready in a matter of 10 minutes the server drops tps from 20 to 10 then 4 to fall.

**Comment by OmerBenGera** [comment]
Take a spark profiler when you experience lag issues and send the result here.
It's not possible to tell what is the source of the lag from timings, as it shows too many lag sources but it cannot tell exactly what causes it.

**Comment by brasilcraft54** [comment]
https://pastebin.com/9bpREebw

**Comment by brasilcraft54** [comment]
https://feedback.songoda.com/t/epichoppers

This is the biggest proof that you don't support anyone.

**Comment by OmerBenGera** [comment]
Install the plugin "spark", then run /spark sampler when the lag occurs for a few seconds, then run /spark sampler --stop, and send the link that it gives you.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by MineagePvP** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by JamesSmily** [comment]
Jesus died cause of the fucking scum bag jews that killed him and i'm glad hitler murdered those scum bags like omre and his family. Boy got mad cause i said jesus got killed by the jews which he is also jewish and banned me from the discord and that is why the jews got killed cause of being scum like him. No money poor af living in a poor country relying on minecraft for money but even that didn't work so he quit cause he's depressed.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this as of now.
If the issue still persists, let me know
