### ISSUE TITLE
Value / Level

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#471]
### Minecraft's Version

1.16.5

### Plugin's Version

227

### Describe the bug

Level / Value is wrong with stacked blocks. As described in [#461](https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/461) 

### To Reproduce

#461

**Comment by Pikaronga** [comment]
(Close this one and reopen the other one)

**Comment by CayeOficial** [comment]
i have the same problem
