### ISSUE TITLE
Island value going down when breaking blocks placed by the Slimefun block placer

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#473]
### Minecraft's Version

1.17.1 Purpur 1331

### Plugin's Version

Dev Build 224

### Describe the bug

When placing blocks with Slimefun's block placer, those will not count towards the island value. When you now break those blocks, instead of the island level staying the same aswell and zeroing out, the value of the block will be substracted from the island value, causing the island value to be able to drop below 0.

### To Reproduce

Step 1: Place a block down with a block placer and watch the island value not changing.
Step 2: Break the block that was placed in step 1 and watch the island level go down.

### Additional Information

https://www.youtube.com/watch?v=9_s8MA-riUk
0:20 - 0:35

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
