### ISSUE TITLE
Clicking with buckets on slabs and stairs removes island value

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#474]
### Minecraft's Version

1.17.1 Purpur 1331

### Plugin's Version

Dev Build 224

### Describe the bug

Whenever you rightclick any slabs or stairs that have a set island value with an empty bucket, the island value will go down.

### To Reproduce

Step 1: Place down any slab or stair that has an island value
Step 2: Grab an empty bucket, rightclick the block from step 1 and watch the island level go down

### Additional Information

https://youtu.be/UtL3qQE8vC8

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
However, this seems to be an issue with Paper as well, so I am gonna make a report on their github.
