### ISSUE TITLE
Island Calculation Without WS issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#475]
### Minecraft's Version

1.12.2

### Plugin's Version

b227-b228

### Describe the bug

Hello, since the version b227 the island level stay -148 level, if i user b226 it works correctly, i think the spawner feature in b227 is the issue.

### To Reproduce

SS2 without WS + /is level
It works correctly with WS.

**Comment by OmerBenGera** [comment]
I have a bug with counting spawners, so I'll try to fix that and hopefully it will fix everything.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
