### ISSUE TITLE
BlocksMissions can easily be completed using Slimefuns block placers

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#477]
### Minecraft's Version

1.17.1 Purpur 1331

### Plugin's Version

Dev Build 224

### Describe the bug

If you break blocks placed by Slimefun's block placer, it will count towards the completion of "BlocksMissions" quests. With using silk touch, this makes players easily able to complete quests that should normally take them a while as they can repedeately do it. This should not be the case as blocks placed by the player also dont count towards quests.

### To Reproduce

Step 1: Set up a BlocksMissions quest
Step 2: Set up a block placer and let it place the block required in step 1
Step 3: Check the quest progress, break the block and check it again - the progress went up

### Additional Information

https://youtu.be/5DsuLO3agHQ

**Comment by OmerBenGera** [comment]
You'll have to create a new mission that supports Slimefun's blocks placer, as the BlocksMissions is just an example of how to make a mission, and only contains basic features and functionality.
If you don't know how to do that yourself, you are more than welcome to ask for someone else to do that for you in the discord server.

**Comment by Skizzles** [comment]
@OmerBenGera This issue also happens with Silktouch which is how the ores are obtained. Ideally I feel the default jar could benefit from having checks for silktouch usage or an option for silktouch so people can not place break place break and complete quests.

**Comment by OmerBenGera** [comment]
> @OmerBenGera This issue also happens with Silktouch which is how the ores are obtained. Ideally I feel the default jar could benefit from having checks for silktouch usage or an option for silktouch so people can not place break place break and complete quests.

If a placer places a block, it will not registered as a valid block for the missions if you have natural-blocks enabled for that mission.
If you believe it doesnt work this way, open a new issue.
