### ISSUE TITLE
Entity Limit Issue

### ISSUE THREAD

**Issue by MineagePvP** [BG-Software-LLC/SuperiorSkyblock2#478]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Build #228

### Describe the bug

I seen an issue request on this issue tracker for this and tested to see if it exists and apparently they are right that villager limit from entity-limit on the config.yml does not limit villagers at all wether it's from spawners or eggs and bypasses wether i'm op or not

### To Reproduce

NA

**Comment by MineagePvP** [comment]
so basically i just tested if you set the entity limit by command it does set the limit but it's not reading the entity listed in the config is what's the issue and also if you remember the last issue i made where the hoppers were limited but if i kept placing it randomly bypasses it and you fixed it looks like you also need to do that with the entity eggs as well cause when i set the limit with the command and i randomly clicked with eggs it'll bypass sometimes and i think you fixed that hopper issue with this last one i believe Changed the way blocks are detected when a structure is generated (trees, etc)

**Comment by MineagePvP** [comment]
just trying to make sure you know what i'm talking about

**Comment by MineagePvP** [comment]
Also apparently it is not detecting not just villagers but all mob types in the entity-limit in the config

**Comment by OmerBenGera** [comment]
I am not sure if that's the exact same issue as of #416 , and therefore I'll keep this opened as a separate issue.
When it's fixed I'll ask them there if it's fixed on their side as well.

Btw, next time, don't post two bugs at the same issue page, as one of them be skipped easily and not get fixed.

**Comment by MineagePvP** [comment]
It's exactly the same issue but they forgot to test if it's just that mob or all mobs and probably didn't test via spawners either and they also haven't replied at all which most likely is cause they were new to the using the plugin and probably stopped using it or they changed the mob for a mob that doesn't require a limit cause villagers can be too op thus require it but yes like i said it's the same issue but like i said their issue and mine and some extra issues are as mentioned up there ^^^^

**Comment by OmerBenGera** [comment]
I tested it and it works fine for me.
You probably have an upgrade that changes limits of entities, and therefore it overrides the default entity limits in the config, as stated above the default-values section:
```
# All the default values for new islands that are created.
# Please note: Upgrades with built-in values (upgrades that don't run commands to update values),
# will override all the values here. For example, if I set an upgrade that changes generator rates,
# there's no need to touch the default generator rates here, as new islands will get the rates from
# the upgrade, and not from here.
```

**Comment by MineagePvP** [comment]
No i do not have an upgrade for entity limit i'm simply using the one in the config

**Comment by OmerBenGera** [comment]
> 
> 
> No i do not have an upgrade for entity limit i'm simply using the one in the config

Send me a screenshot of /is admin show <your island>

**Comment by MineagePvP** [comment]
https://gyazo.com/c6400f2cb767ea180fc67f290895ce57

**Comment by OmerBenGera** [comment]
> https://gyazo.com/c6400f2cb767ea180fc67f290895ce57

You only have a Minecart limit set to 4.

**Comment by OmerBenGera** [comment]
Share with me your config file please

**Comment by MineagePvP** [comment]
https://pastebin.com/

**Comment by MineagePvP** [comment]
i'm limiting mobs specifically villagers not minecarts

**Comment by OmerBenGera** [comment]
You sent a link to the pastebin website instead to your paste.

**Comment by MineagePvP** [comment]
Screw all of this i said in here i just made a video in regards to the issues that exist which you will clearly see i'm exporting it rn and gonna upload and send the link but listen and watch it throughly please cause i will explain and show multiple issues that pertain to some of these tickets that happen

**Comment by MineagePvP** [comment]
https://youtu.be/CXglzFzCqj0

**Comment by MineagePvP** [comment]
https://pastebin.com/MWbLxd4K

**Comment by MineagePvP** [comment]
bro why did you just ban me i didn't do anything

**Comment by OmerBenGera** [comment]
> 
> 
> bro why did you just ban me i didn't do anything if it was cause of the jesus things i'm sorry if that offended you it wasn't meant in that way if you are jewish

you're a racist, ignorant and you can't listen to what I say. You do whatever you want, you don't listen to anybody, and it's impossible to assist you - you just resist to get support.
You have one week to send all the information necessary in all the reported issues you have, and meanwhile I'll think if I want to help you or not.
