### ISSUE TITLE
PreSpawnerSpawnEvent from Paper can bypass settings of islands

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#487]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

Wildstacker b185, superior b239, upgradeablespawners 2.3.3

### Describe the bug

If I got listen-paper-pre-spawn-event: true, when a mob is spawned from the spawner (exemple cow), even if I disable the "animals' spawner spawn" in "/is settings" of superior, mobs will continue to spawn until the stack is full.

So listen-paper-pre-spawn-event: true doesn't check if the "/is settings" for mob spawning via spawner is on or off

### To Reproduce

Place a spawner, wait for the spawner to spawn a mob, then disable spawner spawning in /is settings, check the mobs stack count increasing

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
