### ISSUE TITLE
Lack of translation

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#488]
### Minecraft's Version

1.16.5

### Plugin's Version

b240

### Describe the bug

We can't translate border color (for the message when your border is updated ?)

I'm a french server, and in the message
```BORDER_PLAYER_COLOR_UPDATED: 'changed island border color to {0}.'```
it's "green/red/blue" and I can't translate the colors.

same for island permissions/settings, I can't translate the permissions/settings' names

### Additional Information

It's not a real "bug" but a missing thing, so I placed it there instead of "discussion" thread.

**Comment by OmerBenGera** [comment]
It's not really possible as these must be hard-coded, however I fixed it for the border colors.
