### ISSUE TITLE
Island Mission SPAM

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#489]
### Minecraft's Version

1.12.2

### Plugin's Version

b240

### Describe the bug

Hello, idk how to reproduce exactly the issue but look the pics : https://pics.revolis.fr/2021-08/20/20-28_OiOq.png (this message is the message : MISSION_NO_AUTO_REWARD). Thx

### To Reproduce

Complete mission without auto reward

**Comment by OmerBenGera** [comment]
It tells you what mission you completed, therefore you can find the cause of it

**Comment by nivcoo** [comment]
Yes but the message is sent a lot of times

**Comment by nivcoo** [comment]
While there is only one mission completed

**Comment by OmerBenGera** [comment]
> 
> 
> While there is only one mission completed

If you have met the requirements (for example, mined 100 cobble), and you still mine cobble, you'll get notified more times.

**Comment by nivcoo** [comment]
AHH ok i understand now

**Comment by OmerBenGera** [comment]
:)

**Comment by Dzygius** [comment]
Is there a way to stop notifying player?

**Comment by OmerBenGera** [comment]
> Is there a way to stop notifying player?

Yes, you can make it so the missions are automatically rewarded. If you don't want that, by setting the message to '' may also work.
