### ISSUE TITLE
Bank interest counts every restart

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#521]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b244

### Describe the bug

Bank interest counts every restart, even if in the config its set to 24h for example

### To Reproduce

Setup insterest and restart server

**Comment by OmerBenGera** [comment]
I tested it and it seems to work fine for me.
Check if the last interest time is saved to the database correctly

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by exzolink** [comment]
Yes, everything works as it should. Sorry for the long response.

Can i ask offtop question?
Is it possible to convert SQLite db to MySQL?

**Comment by OmerBenGera** [comment]
> 
> 
> Yes, everything works as it should. Sorry for the long response.
> 
> Can i ask offtop question?
> Is it possible to convert SQLite db to MySQL?

You can do that using an online tool or something like that.
Not recommended, but possible.
