### ISSUE TITLE
Entity Limits Bug

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#523]
### Minecraft's Version

Minecraft's Version
Flamepaper 1.8.8

### Plugin's Version

The dev version #244

### Describe the bug

The entity limits are not working
Snapshot: https://gyazo.com/5084fabdf0111c290f1387fabc0e7013
IS Admin Show: https://gyazo.com/a5d8ffbe1bbc887be85a067681f96162
Config: https://pastebin.com/vBWSjbj1
Upgrades: https://pastebin.com/UBW1g967

### To Reproduce

Try to limit entities in the config and make sure to reset the whole skyblock folder and add a mob type in the entity limits and it will not limit it from spawners, eggs or when spawning directly using commands from essentials.

**Comment by OmerBenGera** [comment]
You don't have an entity limit for villagers - you have for minecarts.
That's because of your "minecarts-limit" upgrade, which your island has and therefore it overrides the default-values from the config.

**Comment by DebuffPvP** [comment]
Ya i know the default entity-limit has a minecart but also add villager on entity limit but no upgrade with it and try and do it yourself and you'll see that it won't work

**Comment by OmerBenGera** [comment]
> 
> 
> Ya i know the default entity-limit has a minecart but also add villager on entity limit but no upgrade with it and try and do it yourself and you'll see that it won't work

You have an upgrade with an entity limits, and therefore it overrides the default values.
It doesn't matter if you don't have villagers in this upgrade.

**Comment by DebuffPvP** [comment]
ok so how do i make a limit of 10 villagers on an island without an option of upgrades then couod you possiboy pastebin me a config for 1.8.8 that limits it to 10?

**Comment by OmerBenGera** [comment]
> 
> 
> ok so how do i make a limit of 10 villagers on an island without an option of upgrades then couod you possiboy pastebin me a config for 1.8.8 that limits it to 10?

That's what you need to do.
I can't make an example for you, you are more than welcome to follow the tutorial on the wiki.

**Comment by DebuffPvP** [comment]
That's exactpy what i've done i put VILLAGER:10 in the entity-limits: below it and no upgrade with it just a base of 10 max and it does not limit not just that but any mob name and amount for it i may place in there

**Comment by DebuffPvP** [comment]
Could you please try it yourself possibly add a mob with a limit amount and no upgrades for it and it will not work so essentially the entity-limits: option is not working at all

**Comment by OmerBenGera** [comment]
> 
> 
> That's exactpy what i've done i put VILLAGER:10 in the entity-limits: below it and no upgrade with it just a base of 10 max and it does not limit not just that but any mob name and amount for it i may place in there

I already told you what the issue is and how to fix it, you just refuse to listen, as usual.
Don't use the default values section, use the upgrades system instead.

**Comment by DebuffPvP** [comment]
You probably worded it differently and i didn't understand so it was a misunderstanding. So entity-limits: to limit entities there must be an upgrade for it otherwise entities won't limit just based of the entity listed in that section is what you're saying correct?

**Comment by OmerBenGera** [comment]
> You probably worded it differently and i didn't understand so it was a misunderstanding. So entity-limits: to limit entities there must be an upgrade for it otherwise entities won't limit just based of the entity listed in that section is what you're saying correct?

Right, unless you disable the upgrades and then you can use the default values section.

**Comment by DebuffPvP** [comment]
If you want to allow it to be used without an upgrade is that possible if you wanted to modify the feature to add support for that?

**Comment by DebuffPvP** [comment]
?
