### ISSUE TITLE
Dupe with mob drops multiplier upgrade

### ISSUE THREAD

**Issue by D3adhkwen** [BG-Software-LLC/SuperiorSkyblock2#524]
### Minecraft's Version

Airplane 1.17.1

### Plugin's Version

1.7.0-DEVv244

### Describe the bug

Items dupe when killing piglin holding the item

### To Reproduce

1. Upgrade mob drop multiplier
2. Throw any item to piglin (preferably baby piglin)
3. Kill the piglin in 1 hit
4. Items dupe according to level of multiplier upgrade

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, are you able to take a video?

**Comment by D3adhkwen** [comment]
https://user-images.githubusercontent.com/38313757/130354648-830b0cf9-3766-4f39-a919-3364034525ed.mp4

I have done more testing, it seems to be related to mcMMO Swords ability - Stab (Level 1 gives 2.5 damage, Level 2 gives 4.0 damage)
After testing, I figured out that your base damage (from sword) cannot kill the piglin in 1 hit. For example, baby piglin has 16 health. Your sword damage can only go up to 15.5 damage, therefore the extra damage from Stab will kill the baby piglin and dupes item.
Example:
Netherite Sword (Base damage 8) + Critical (4 damage) + Stab (4 damage) = 16 damage (dupe)
Netherite Sword (Base damage 8) + Sharpness 6 (3.5 damage) + Critical (4 damage) + Stab (4 damage) = 19.5 damage (dupe)
Netherite Sword (Base damage 8) + Sharpness 7 (4 damage) + Critical (4 damage) = 16 damage (does not dupe because Stab is not needed for 1 hit kill)

Therefore, I have made the conclusion that this is either SuperiorSkyblock not hooking into mcMMO's Stab well, causing item to dupe
or
mcMMO is firing wrong events for the Stab ability.

**Comment by OmerBenGera** [comment]
I tried it with sharpness 500 - are you able to replicate it using this level of enchantment?

**Comment by D3adhkwen** [comment]
https://user-images.githubusercontent.com/38313757/130355629-c7cec0a2-d9e3-4aea-9f7e-2052035f5b79.mp4

additional video that could be helpful

sharpness 500 doesn't work. maximum damage from sword u can get is 12 because of stab giving 4 damage

**Comment by OmerBenGera** [comment]
I understand.
I will install mcMMO and try reproducing it again.

**Comment by OmerBenGera** [comment]
Before I do that, try using latest dev build, I might have found the cause of the issue.

**Comment by D3adhkwen** [comment]
Seems like it is fixed on latest dev build

**Comment by OmerBenGera** [comment]
Perfect :)
