### ISSUE TITLE
Entity can't spawn on spawn island

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#525]
### Minecraft's Version

1.12.2

### Plugin's Version

B248

### Describe the bug

Hello after the feature of paper i can't spawn animal or monster in the spawn island : i have this default settings : NATURAL_ANIMALS_SPAWN,  SPAWNER_ANIMALS_SPAWN. With the version b241 it works. I've tried to remove the settings and reload or set the monster settings but llama/cow/pig are animals.

### To Reproduce

Run with latest version and try to place enetity on spawn island+

**Comment by nivcoo** [comment]
https://github.com/BG-Software-LLC/SuperiorSkyblock2/pull/526 it's fixed here

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
