### ISSUE TITLE
Cropsgrowth save issue

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#529]
### Minecraft's Version

1.12.2

### Plugin's Version

B251

### Describe the bug

Hello, after the restart i've allways this issue withb cropsgrowth https://pics.revolis.fr/2021-08/22/18-06_X9Pl.png i set only 1.10 but after the plugin set lot of numbers.

### To Reproduce

/is admin setcropgrowth username 1.10 and restart the server and look.

**Comment by OmerBenGera** [comment]
Don't use decimals for crop growth - only ints are supported.
Crop growth 1.1 is the same as 1.
