### ISSUE TITLE
Lag when creating an island from schem

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#534]
### Minecraft's Version

1.17.1 Purpur 1343

### Plugin's Version

dev 244

### Describe the bug

Massive tps loss on /is create

### To Reproduce

/is create and see the tps loss occur

### Additional Information

https://spark.lucko.me/UzeIz0DdcX

**Comment by OmerBenGera** [comment]
Lag seems to be due to the hook with Slimefun.
I will look into that.

**Comment by OmerBenGera** [comment]
There is nothing to do regarding this, unless Slimefun will give us a better solution to find all custom blocks in a chunk.
