### ISSUE TITLE
error block stacking

### ISSUE THREAD

**Issue by hungvipso10** [BG-Software-LLC/SuperiorSkyblock2#535]
### Minecraft's Version

paper 1.16.5

### Plugin's Version

Superiorskyblock #252

### Describe the bug

when i put stack block block DIAMOND_BLOCK .... Quickly it happens that some stacking block is lost , then i break the stack block and i see the level of that disappearing stack increase level , i have to use /is level it returns to 0

### To Reproduce

.

### Additional Information

https://www.youtube.com/watch?v=81aBSrdQSp0

**Comment by OmerBenGera** [comment]
So it seems like the 3 missing diamond blocks were counted towards the worth value of the island, but are missing in the stacked block itself, so when breaking it the worth value stays.
I will look into that.

**Comment by OmerBenGera** [comment]
Closing this for now, as I can't seem to replicate it.
If it happens to someone, make sure you let me know.
