### ISSUE TITLE
Issue in island schematics

### ISSUE THREAD

**Issue by Pro-Nil** [BG-Software-LLC/SuperiorSkyblock2#546]
### Minecraft's Version

paper 1.16.5

### Plugin's Version

b259

### Describe the bug

I wanted to add custom islands so I created a few islands then created their schematics using /is admin schematic . The normal islands loaded properly as intended and all but whenever am trying to select desert/mycel islands ,it just get stuck on creating your island , and if I try to create again it shows you already have a island creation process ongoing .

### To Reproduce

already described in "describe the bug'

**Comment by Pro-Nil** [comment]
yes , those are custom made by me

**Comment by OmerBenGera** [comment]
Mind sending them here so I can test them as well?

**Comment by Pro-Nil** [comment]
can I send those to you in dc dm ? coz I dont wanna leak those schematics

**Comment by OmerBenGera** [comment]
What is your discord? I will open a private ticket for you and me.

**Comment by Pro-Nil** [comment]
! Pro_Nil#7777

**Comment by OmerBenGera** [comment]
Fixed :)
