### ISSUE TITLE
bank can't type amount withdraw/deposit

### ISSUE THREAD

**Issue by xxmethaa** [BG-Software-LLC/SuperiorSkyblock2#547]
### Minecraft's Version

1.16.5-1.17

### Plugin's Version

1.7.0-DEVb251

### Describe the bug

bank can't type amount withdraw/deposit

### To Reproduce

bank can't type amount withdraw/deposit

### Additional Information

![image](https://user-images.githubusercontent.com/87219470/131154858-55443b3d-92b8-4515-a60e-ca40e633f077.png)

**Comment by xxmethaa** [comment]
sure
![image](https://user-images.githubusercontent.com/87219470/131219614-f7047488-d354-40ce-b2b8-d7a712099c0f.png)

**Comment by xxmethaa** [comment]
Bank Config

######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

enabled: true

# Set the divider for the island bank money in the total island worth.
# You can set it to 0 to disable island bank money to be calculated in island worth.
bank-worth-rate: 0

# Should island bank balance be refunded upon island disband?
# When set to 100, all the balance will be refunded.
# When set to 0, no balance will be refunded.
disband-refund: 0

# Should transaction logs of the island bank be saved to database?
# Warning: There may be a lot of transactions, and can increase database.
bank-logs: false

# All settings related to bank interest.
# This feature is a money-generator for the islands.
# As long as the island members are online, they will earn money.
bank-interest:
  # Should the feature be enabled?
  enabled: true
  # The interval to give the interest reward (in seconds).
  interval: 86400
  # The percentage out of the bank that will be given.
  # If it's 10, then 10% out of the bank balance will be given.
  percentage: 5
  # The maximum time that the island owner can be offline in order to be rewarded (in seconds).
  # Can be -1 in order to disable this restriction.
  recent-active: 86400

**Comment by OmerBenGera** [comment]
> 
> 
> sure
> ![image](https://user-images.githubusercontent.com/87219470/131219614-f7047488-d354-40ce-b2b8-d7a712099c0f.png)

I don't know why it happens tbh, seems to work fine for me.
Does /is deposit 5000 work for you?

**Comment by xxmethaa** [comment]
> > sure
> > ![image](https://user-images.githubusercontent.com/87219470/131219614-f7047488-d354-40ce-b2b8-d7a712099c0f.png)
> 
> I don't know why it happens tbh, seems to work fine for me.
> Does /is deposit 5000 work for you?

Yes it work
can i send you my config?

**Comment by OmerBenGera** [comment]
> 
> 
> > > sure
> > > ![image](https://user-images.githubusercontent.com/87219470/131219614-f7047488-d354-40ce-b2b8-d7a712099c0f.png)
> > 
> > 
> > I don't know why it happens tbh, seems to work fine for me.
> > Does /is deposit 5000 work for you?
> 
> Yes it work
> can i send you my config?

There's no need for your config.
You have a plugin that adds white color to your chat, and confusing the plugin (as you can see, the 5000 is white instead of being gray)

**Comment by OmerBenGera** [comment]
Find the plugin and report it to them.
I am closing this for now
