### ISSUE TITLE
Failed to Executes [SuperiorSkyBlock2]

### ISSUE THREAD

**Issue by SirCraftypants** [BG-Software-LLC/SuperiorSkyblock2#550]
### Minecraft's Version

1.17.1

### Plugin's Version

b265

### Describe the bug

I just updated from b251 to b265 and restarted my Server, got 2 fails to executes.

https://paste.helpch.at/ukapevejex.md

### To Reproduce

I just updated from b251 to b265

**Comment by OmerBenGera** [comment]
Do you have database-bkp.db file?

**Comment by SirCraftypants** [comment]
I did a completely fresh install after visiting your discord and seeing that 262+ is a completely new revamp. 

Fixed, thanks
