### ISSUE TITLE
Monsters spawning

### ISSUE THREAD

**Issue by LilSadPanda** [BG-Software-LLC/SuperiorSkyblock2#553]
### Minecraft's Version

1.16.5

### Plugin's Version

#277

### Describe the bug

monsters spawn while its disabled in the island settings

### To Reproduce

N/A

### Additional Information

N/A

**Comment by OmerBenGera** [comment]
It works fine for me - I disable natural spawning of monsters and no monsters spawn.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by LilSadPanda** [comment]
Hey @OmerBenGera Sorry Ive stopped testing the dev versions. Needed to get a stable version for my server :D
