### ISSUE TITLE
superiorskyblock error console restart

### ISSUE THREAD

**Issue by hungvipso10** [BG-Software-LLC/SuperiorSkyblock2#555]
### Minecraft's Version

paper 1.16.5

### Plugin's Version

SuperiorSkyblock2-b277

### Describe the bug

I restarted it gave me an error

### To Reproduce

.

### Additional Information

![unknown](https://user-images.githubusercontent.com/77562992/131629401-ff1bd2b0-94ef-4a9c-921a-764f608294ff.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
