### ISSUE TITLE
schematic error chest

### ISSUE THREAD

**Issue by hungvipso10** [BG-Software-LLC/SuperiorSkyblock2#557]
### Minecraft's Version

paper 1.16.5

### Plugin's Version

SuperiorSkyblock2-b278

### Describe the bug

- i don't know if it's the schematics or the config error because i installed another schematic island i checked the chest but didnt see anything in the chest

- I tried true, false, in config and then I reload command [/ is admin reload ]. Then I reset the new map island and I check the chest there is nothing

### To Reproduce

.

### Additional Information

![image](https://user-images.githubusercontent.com/77562992/131718118-645733d0-bfe2-4b4e-9965-1d44e05ebeec.png)
![image](https://user-images.githubusercontent.com/77562992/131718311-ff6b0a60-8286-449c-9d57-5bb3a4e29960.png)
![image](https://user-images.githubusercontent.com/77562992/131719423-27737637-7bc0-4db7-b2c8-da791e22f7c1.png)

**Comment by OmerBenGera** [comment]
Best way is to put the items in the chest and then create the schematic, so all the chest contents are saved in the schematic.
Anyways, I will look into that.

**Comment by hungvipso10** [comment]
i tried to create schema with item saved in chest then i put in schematic on superiorskyblock replace normal to other normal schema i did but its not working when creating island

**Comment by OmerBenGera** [comment]
> i tried to create schema with item saved in chest then i put in schematic on superiorskyblock replace normal to other normal schema i did but its not working when creating island

The system works fine, make aure you disable the cpnfig option and that you create the schematic with items inside your chest.

**Comment by OmerBenGera** [comment]
Both issues are fixed in latest dev build
