### ISSUE TITLE
WS spawner count (Not latest update of SS2 - b261)

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#558]
### Minecraft's Version

1.12.2

### Plugin's Version

b261

### Describe the bug

Hello when i placed 2 spawners of parrot (for exemple) and many other plugin but the count of parrot after /is recalc isn't correct (I've placed 2 parrot spawners and after /is recalc i have 9 spawners of parrot into /is count).

I know i don't use the latest so idk if the bug still present in the latest version but if you think that is present could you fix that ? Thx 

### To Reproduce

Place many spawners with ws spawner provider. Do /is recalc and look /is count

**Comment by OmerBenGera** [comment]
Check if it happens using latest dev build. If you are worried about your data, you can try it on another server.

**Comment by OmerBenGera** [comment]
I am closing this as it doesn't seem to happen for me
If it still occurs for you on latest dev build, let me know here
