### ISSUE TITLE
Coop and invite bug

### ISSUE THREAD

**Issue by Olek012** [BG-Software-LLC/SuperiorSkyblock2#561]
### Minecraft's Version

AirplanePurpur22 (1.17.1)

### Plugin's Version

Superior skyblock 2 dev build b278

### Describe the bug

When you add a user with /is coop to your island and then invite him to the island and he joins he cannot break blocks, it remains as in adventure mode without being able to break, when the user leaves the island and creates a new one, he still cannot build

### To Reproduce

./is coop user2
./is invite user2
*user2 accepts invite*

**Comment by OmerBenGera** [comment]
I don't know why your players get adventure mode, because I don't remember the plugin changes that.
However, I fixed players can be coops and members at the same time, so maybe this fixes the issue.

**Comment by Olek012** [comment]
My skyblock server is not open to the public yet, it was a bug that I found testing it. Nothing about the adventure mode my bad, it's just not being able to break blocks etc, thanks for solving it.

**Comment by OmerBenGera** [comment]
> My skyblock server is not open to the public yet, it was a bug that I found testing it. Nothing about the adventure mode my bad, it's just not being able to break blocks etc, thanks for solving it.

Is it working now?

**Comment by Olek012** [comment]
I haven't tried the latest version yet. Did you already add it?

**Comment by OmerBenGera** [comment]
> I haven't tried the latest version yet. Did you already add it?

Yes.

**Comment by OmerBenGera** [comment]
Any news regarding this? Have you tested it?

**Comment by Olek012** [comment]
Yes, i tried right now. Solved thanks

**Comment by OmerBenGera** [comment]
Great :)
