### ISSUE TITLE
Islands got deleted

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#562]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b278

### Describe the bug

I updated from superior b241 to b278

It updated dabatase well, no issues at all (I had 37 islands, it's a test server), and after 10 restarts, 35 islands were deleted, only 2 islands remains

I don't get any informations in logs :/

### To Reproduce

Use MySQL
Upgrade your server to latest dev build
Restart multiple times

### Additional Information

I'm using MySQL storage

**Comment by OmerBenGera** [comment]
Check if the islands are in the database, look for errors, check maybe if the old database converter for no reason interrupted with it...
You barely gave any information about the bug, and in the current state its impossible to fix it.

**Comment by Peeraboon** [comment]
I also have this issue **but every island** was deleted. When I upgraded from b261 to b278 (haven't tried on latest build yet).
At first everything was normal but after the server restarted, every island was deleted.

**but I use SQLite.**

**Comment by OmerBenGera** [comment]
> 
> 
> I also have this issue **but every island** was deleted. When I upgraded from b261 to b278 (haven't tried on latest build yet).
> At first everything was normal but after the server restarted, every island was deleted.
> 
> 1.16.5 Paper
> 
> **but I use SQLite.**

Were there any messages regarding the converting of islands after you upgraded?
Also, make sure you use latest dev build.

**Comment by banicola** [comment]
I just got the same issue. All islands deleted...

**Comment by OmerBenGera** [comment]
> 
> 
> I just got the same issue. All islands deleted...

You had a completely different issue, don't mix between them so I don't get confused.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it's fixed.

**Comment by WarnDangerous** [comment]
No issue on latest dev build for me.

**Comment by OmerBenGera** [comment]
Great, I am closing this for now
If it occurs again, make sure you let me know
