### ISSUE TITLE
Islands are long to load

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#563]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b278

### Describe the bug

There might be a problem with the new database system and island loading.

With 32 islands it takes 7 seconds to load
[17:30:22 INFO]: [SuperiorSkyblock2] Starting to load islands...
[17:30:29 INFO]: [SuperiorSkyblock2] Finished islands!

I tried another time
[17:38:50 INFO]: [SuperiorSkyblock2] Starting to load islands...
[17:38:56 INFO]: [SuperiorSkyblock2] Finished islands!

### To Reproduce

Starts the server with new database system

### Additional Information

(it's not during conversion, I restarted 2-3 times since I upgraded to latest dev build)

Before it was less than 1 second

I'm using MySQL storage

**Comment by OmerBenGera** [comment]
Its 6 seconds, thats fine.
Its because there are multiple databases to load data from, unlike the old database which all the data used to be in one table.
