### ISSUE TITLE
Boat Glitch

### ISSUE THREAD

**Issue by ItchyDitchy** [BG-Software-LLC/SuperiorSkyblock2#566]
### Minecraft's Version

1.8.8 - SpaceDeltaSpigot

### Plugin's Version

1.7.0-DEVb167

### Describe the bug

You can ride a boat to get out of an island border.

### To Reproduce

Place a boat on an island -> Ride boat -> Move towards the border -> Unride boat -> Ride boat, repeat until you are outside the border.

**Comment by OmerBenGera** [comment]
Go to your config, and enable the stop-leave option.
Players can go out of the world border by disabling it as well, and also in vanilla there are plenty of bugs to get out of it.
