### ISSUE TITLE
Island delete issue

### ISSUE THREAD

**Issue by LilSadPanda** [BG-Software-LLC/SuperiorSkyblock2#567]
### Minecraft's Version

1.16.5

### Plugin's Version

#280

### Describe the bug

Islands being deleted after restart.

### To Reproduce

convert old db to new structure and create a new island with a new user.

### Additional Information

Use a old db and let the plugin convert it to the new structure. Everything works like old islands etc. But once a new user creates an island it removes the old islands.

**Comment by LilSadPanda** [comment]
If you need the DB files. Ping me in the support server @LilSadPanda#9989 and I'll send the database after conversion. and the database after a user created a new island on the new db

**Comment by OmerBenGera** [comment]
I'll try first replicating it myself and I will get back to you.
When do the islands get removed? When you create the new island, or when a restart occurs?

**Comment by LilSadPanda** [comment]
Islands work after restart (if no one creates a new island) But once someone create an island and restart the server only their island works

**Comment by OmerBenGera** [comment]
> 
> 
> Islands work after restart (if no one creates a new island) But once someone create an island and restart the server only their island works

So just to make sure: it only deletes their island if someone new creates an island and a restart occurs, right?
Without an additional restart, everything will work, right?

**Comment by LilSadPanda** [comment]
yes

**Comment by LilSadPanda** [comment]
After restart all old islands get reset/deleted except the users who created an island after the db migration

**Comment by OmerBenGera** [comment]
Seems to work fine for me.
The island that was converted alongside of the island that was created after the migration are both still valid.

**Comment by LilSadPanda** [comment]
Can I send you my databases then you check it out?

**Comment by OmerBenGera** [comment]
> 
> 
> Can I send you my databases then you check it out?

Sure, send it via discord

**Comment by LilSadPanda** [comment]
### Minecraft's Version

1.16.5
Java 16

### Plugin's Version

#280

### Describe the bug

Islands being deleted after restart.

### To Reproduce

Use an old db from #261 and lower with an island created. Update the plugin to #280 and let the plugin update the old database to the new database. Once its done. Join with the profile what you used previously to create the island on #261 and youll notice all your stuff is there. Now use another profile(mc acc) to create a new island. if the island is created with the second account. Restart the server. After restart Only the second profile's island will be there and the first profile's island will be gone

### Additional Information

N/A

**Comment by OmerBenGera** [comment]
> 
> ### Minecraft's Version
> 
> 1.16.5
> Java 16
> ### Plugin's Version
> 
> #280
> ### Describe the bug
> 
> Islands being deleted after restart.
> ### To Reproduce
> 
> Use an old db from #261 and lower with an island created. Update the plugin to #280 and let the plugin update the old database to the new database. Once its done. Join with the profile what you used previously to create the island on #261 and youll notice all your stuff is there. Now use another profile(mc acc) to create a new island. if the island is created with the second account. Restart the server. After restart Only the second profile's island will be there and the first profile's island will be gone
> ### Additional Information
> 
> N/A

As I said, it works fine for me.

**Comment by LilSadPanda** [comment]
Okay I tried. ¯\_(ツ)_/¯

**Comment by OmerBenGera** [comment]
Try replicating with a completely new database, don't use old databases

**Comment by OmerBenGera** [comment]
You can run `/is admin debug Action: Database` and check all calls of the plugin to the database. Check if there are any delete queries being executed.

**Comment by LilSadPanda** [comment]
when a user letes their island https://mclo.gs/UozvGn2

**Comment by OmerBenGera** [comment]
> 
> 
> when a user letes their island https://mclo.gs/UozvGn2

that's because they delete their island, of course it happens
I meant you need to check it when a new island is created, not when people delete their island...

**Comment by LilSadPanda** [comment]
When the user deleted the island and server restarted all islands also got whiped

**Comment by OmerBenGera** [comment]
> 
> 
> When the user deleted the island and server restarted all islands also got whiped

But all these messages are from deleting this own island.
Look for queries related to the other islands

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.

**Comment by OmerBenGera** [comment]
Let me know if it's fixed or not

**Comment by OmerBenGera** [comment]
I'd guess it's fixed due to lack of response.
If it's still an issue, comment here and let me know about it.
