### ISSUE TITLE
Upgrades do not apply with the latest dev builds (at least since #277)

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#568]
### Minecraft's Version

Airplane 1.17.1

### Plugin's Version

Dev build 280

### Describe the bug

Upgrades do not apply in game. For example, mob drop upgrade doesn't increase the mob drop.

### To Reproduce

Try it on the latest dev build with a large mob drop increase for example to be sure to see the change in drops amount.

### Additional Information

It was working before the update to latest dev builds (at least 277)

**Comment by OmerBenGera** [comment]
Do you see the data correctly by running /is admin show?

**Comment by banicola** [comment]
![image](https://user-images.githubusercontent.com/25954399/132020969-f4876480-8de7-49df-b7ee-76159c2888bd.png)

**Comment by OmerBenGera** [comment]
And what about the multipliers themselves? were they applied too?

**Comment by banicola** [comment]
i asked to multiple players and all of them reported at the same time a decrease in mob-drops and crop-growth speed. I don't play myself to compare to before but all the people use to it told me it do no longer applies.

**Comment by OmerBenGera** [comment]
> 
> 
> i asked to multiple players and all of them reported at the same time a decrease in mob-drops and crop-growth speed. I don't play myself to compare to before but all the people use to it told me it do no longer applies.

Were the multipliers applied to the islands or not?

**Comment by banicola** [comment]
Oh sorry, no it says 0.0

![image](https://user-images.githubusercontent.com/25954399/132021940-72645a4b-d301-4e96-ad2c-7d16702a305f.png)

**Comment by OmerBenGera** [comment]
> 
> 
> Oh sorry, no it says 0.0
> 
> ![image](https://user-images.githubusercontent.com/25954399/132021940-72645a4b-d301-4e96-ad2c-7d16702a305f.png)

Show me your upgrades file please.

**Comment by banicola** [comment]
https://pastebin.com/raw/GL7KgDWJ

**Comment by banicola** [comment]
It was working before the update I did last night

**Comment by OmerBenGera** [comment]
What about the border? Does it work well or not?

**Comment by banicola** [comment]
Yes it works

**Comment by banicola** [comment]
Maybe its only the multiplicator then

**Comment by OmerBenGera** [comment]
kk, I will look into that

**Comment by OmerBenGera** [comment]
I tested it out and it works fine for me

**Comment by banicola** [comment]
Strange since the plugin sees the upgrade for me but do not apply the multiplicators from the config. With that issue and the other one I have it seems like some things were changed in the database no?

**Comment by banicola** [comment]
I just tried /is admin setupgrade clipsy1 mob-drops 4 (for my island) and it still shows the multiplicator at 0

![image](https://user-images.githubusercontent.com/25954399/132025791-45db35cf-4d03-44ea-9030-e302db3e05af.png)

**Comment by banicola** [comment]
Oh I found something, I just used the command /is admin setupgrade clipsy1 mob-drops 3 and now I have the multiplicators:
![image](https://user-images.githubusercontent.com/25954399/132026283-b1b7577e-5098-4ca7-9c02-463df2d057d7.png)

**Comment by banicola** [comment]
And now I did the upgrade to level 4 again and I have the multiplicators... So strange

**Comment by banicola** [comment]
But I can't do that for every single island...

**Comment by OmerBenGera** [comment]
Let me know how to replicate the issue, as it seems that upgrades load just fine.

**Comment by banicola** [comment]
I don't know where to start, I'm using mysql, We upgrades from an older version and they at the first start the multiplicator were all at 0.0. If I then downgrade an upgrade it will update all the multiplicators (and not only the one I changed) I even tried with an other upgrade (members-limit) and it updated the multiplicators

**Comment by banicola** [comment]
But there's only by downgrading an island upgrade that it works, not by increasing it

**Comment by OmerBenGera** [comment]
> 
> 
> I don't know where to start, I'm using mysql, We upgraded from an older version and then at the first start the multiplicator were all at 0.0. If I then downgrade an upgrade it will update all the multiplicators (and not only the one I changed) I even tried with an other upgrade (members-limit) and it updated the multiplicators

Try it on another server with only SSB installed, try upgrading the database etc and check if it still occurs.
If you don't know how to replicate it, how would I know how to do that or how to fix it?

**Comment by banicola** [comment]
By looking at the code behind the behavior? And how it is even physically possible to get the multiplicators back by downgrading an island upgrade but not by increasing it?

**Comment by OmerBenGera** [comment]
> 
> 
> By looking at the code behind the behavior? And how it is even physically possible to get the multiplicators back by downgrading an island upgrade but not by increasing it?

That's not gonna be easy to find a bug just by looking at the code.
Find how it happens and report back.

**Comment by godtojang** [comment]
![image](https://user-images.githubusercontent.com/90055406/132029019-e333a7b1-4066-46ae-a6da-1f06e2816390.png)

**Comment by OmerBenGera** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/90055406/132029019-e333a7b1-4066-46ae-a6da-1f06e2816390.png)
> /is admin show is not available

How is it related to the issue?
It seems like you have another plugin that has /is, these are not commands of the plugin.
If you don't have anything to do with the reported issue, don't comment here.

**Comment by godtojang** [comment]
sorry
![image](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png)
The upgrade works well. but after reboot. and reset !

**Comment by OmerBenGera** [comment]
> 
> 
> sorry
> ![image](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png)
> The upgrade works well. but after reboot. and reset !

Are they changed to 1 after a restart?

**Comment by godtojang** [comment]
> > [죄송합니다 ![image](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) ](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) 업그레이드가 잘 작동합니다.  하지만 재부팅 후. 및 재설정!
> 
> 다시 시작한 후 1로 변경되었습니까?

Yeah, that's right!

**Comment by OmerBenGera** [comment]
> 
> 
> > > [죄송합니다 ![image](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) ](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) 업그레이드가 잘 작동합니다.  하지만 재부팅 후. 및 재설정!
> > 
> > 
> > 다시 시작한 후 1로 변경되었습니까?
> 
> Yeah, that's right!

Open a new issue, as this is not related to this issue.

**Comment by godtojang** [comment]
> > > > [죄송합니다 ![image](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) ](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) 업그레이드가 잘 작동합니다.  하지만 재부팅 후. 및 재설정!
> > > 
> > > 
> > > 다시 시작한 후 1로 변경되었습니까?
> > 
> > 
> > Yeah, that's right!
> 
> Open a new issue, as this is not related to this issue.

where is it?

**Comment by OmerBenGera** [comment]
> 
> 
> > > > > [죄송합니다 ![image](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) ](https://user-images.githubusercontent.com/90055406/132029380-45174483-3507-45b9-9d12-d7836c869ffd.png) 업그레이드가 잘 작동합니다.  하지만 재부팅 후. 및 재설정!
> > > > 
> > > > 
> > > > 다시 시작한 후 1로 변경되었습니까?
> > > 
> > > 
> > > Yeah, that's right!
> > 
> > 
> > Open a new issue, as this is not related to this issue.
> 
> where is it?

On the issues tab.
Please stop commenting here as we're spamming this issue.

**Comment by banicola** [comment]
Ok I tried to replicate it from an new island on the latest dev build 280:
- Create an island
- Upgrade the island for example with mob-drops to 4
(Mutliplicators should work there)
- Restart the server
- Do /is admin show <island> -> Then the mutiplicators are reset to 0.0 for me

**Comment by banicola** [comment]
I think I was on an update before the build that changed the database (262)

**Comment by OmerBenGera** [comment]
> 
> 
> I think I was on an update before the build that changed the database (262) and the issue appears when I convert came with this upgrade

From the message before this one, you haven't said anything regarding the data migration.
Is it related to it or not?

**Comment by banicola** [comment]
When I tried with the new island, no it was all on the latest build. But the database was migrated from an older version to a new one prior to this

**Comment by OmerBenGera** [comment]
> 
> 
> When I tried with the new island, no it was all on the latest build. But the database was migrated from an older version to a new one prior to this

I don't understand anything.
Does it involve the migration or not?
Does it happen when creating a new island?

**Comment by banicola** [comment]
I try to give you all I know, I was on a build previously (I think build 221) which was before the new database changes you made (build 262) and since I upgraded to build 277 last night I have the issue. Now does it come from a wrongly converted DB or is it an issue with the latest build I can't tell for now, I have to set up a new server to try that.

**Comment by banicola** [comment]
But other than this information, yes it happens when I restart the server with the latest build, when I create a new island or on older islands

**Comment by banicola** [comment]
New island everything is normal:

![image](https://user-images.githubusercontent.com/25954399/132038960-34f369fc-ac7e-4087-b5d1-c971182a6a3c.png)

Then after the restart:

![image](https://user-images.githubusercontent.com/25954399/132039136-43498ac7-930d-4491-a27b-7b529544c63f.png)

**Comment by banicola** [comment]
Then I can upgrade my island, for example the mob-drops upgraded to 2, it does nothing:

![image](https://user-images.githubusercontent.com/25954399/132039335-fa7f98b5-ab95-44c2-8478-6579885eb63e.png)

But when I downgrade it (here mob-drops from 2 to 1), the multiplicators goes back:
![image](https://user-images.githubusercontent.com/25954399/132039467-8a476093-da7a-4df7-92dd-371870f4d6bd.png)

until a restart where it disappears again

**Comment by OmerBenGera** [comment]
So it has nothing to do with the migration process.
I don't know currently why it happens to you, it seems to work fine for me atm
I will try to further investigate the issue.

Try it on another server with only SSB installed using default files, lmk if you can replicate it.
There's no need for pictures, just let me know if you are able to replicate it or not

**Comment by banicola** [comment]
With a fresh start and using SQLite it is working fine, but when I switch to MySql (I my case I use Mariadb), the issue appears

**Comment by OmerBenGera** [comment]
> 
> 
> With a fresh start and using SQLite it is working fine, but when I switch to MySql (in my case I use Mariadb), the issue appears

so it seems to only occur with MySQL?

**Comment by banicola** [comment]
Yes

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
