### ISSUE TITLE
Default behaviour of the /is command changed for every player with latest devbuild

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#569]
### Minecraft's Version

Airplane 1.17.1

### Plugin's Version

Dev build 280

### Describe the bug

We put the parameter to open the panel by default with the /is command 6 months ago (default-toggled-panel: true), it worked fine until the update the the latest build. Since then the command teleports every player on their island (all of them not just the old players). After using the command to set back the /is to open the panel, it works but there is still something that changed the setting of every player. I didn't try to restart the server yet to see if it resets the behaviour again by loading the data.

### To Reproduce

Update from an older version of the plugin with the toggle panel to true and see if it changes the default setting to teleport players on their island.

**Comment by OmerBenGera** [comment]
Seems to work fine for me, can't replicate the issue
Are you able to replicate it on another server?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by banicola** [comment]
It changed the value for everyone with the database conversion from the old version, I told my players yhe command to change the behavior themselves and the new players never complained so... I'll close this, if no one else had the issue when updating to the new database.
