### ISSUE TITLE
After upgrading the island, rebooting the server will reset the upgrade.

### ISSUE THREAD

**Issue by godtojang** [BG-Software-LLC/SuperiorSkyblock2#570]
### Minecraft's Version

1.12.2

### Plugin's Version

Development Builds

### Describe the bug

Just as the title says.

### To Reproduce

upgrade island. and upgrade upgrade upgrade. and rebooting server.
all ~ upgrade is reset.
![image](https://user-images.githubusercontent.com/90055406/132031436-0d2f3a20-09f9-433a-a116-6e3d90c48a71.png)
2 >>> rebooting >>> 1

**Comment by OmerBenGera** [comment]
What is the version that you use of the plugin?

**Comment by godtojang** [comment]
> 플러그인을 사용하는 버전은 무엇입니까?

maybe 1.7.0

**Comment by OmerBenGera** [comment]
> 
> 
> > 플러그인을 사용하는 버전은 무엇입니까?
> 
> maybe 1.7.0

Try updating to latest dev build and let me know if the issue still occurs

**Comment by OmerBenGera** [comment]
Check out latest dev build, I fixed an issue regarding upgrades that might fix your issue as well.

**Comment by OmerBenGera** [comment]
Any news regarding this? Have you tried it?

**Comment by Oskaris25** [comment]
This issue also occurs on SuperiorSkyblock2-b302.jar

logs: https://pastebin.com/zjtUWsmB

**Comment by OmerBenGera** [comment]
> This issue also occurs on SuperiorSkyblock2-b302.jar
> 
> logs: https://pastebin.com/zjtUWsmB
> 
> If you upgrade the island and turn off the server with the / stop command, then after turning on the border it returns to its basic size.

Run /is admin show and check if the birder upgrade level is different.

**Comment by Oskaris25** [comment]
![adminshow](https://user-images.githubusercontent.com/90521869/132962817-febeaacc-454c-469c-89c4-9d953c7c35ae.PNG)

**Comment by Oskaris25** [comment]
![adminshow](https://user-images.githubusercontent.com/90521869/132962836-8c77843c-1172-4399-af59-9c4e8dad6c14.PNG)

**Comment by OmerBenGera** [comment]
@Oskaris25 check out #604

**Comment by Oskaris25** [comment]
Before stop server
![Zrzut ekranu (5)](https://user-images.githubusercontent.com/90521869/133324682-d8bd74ef-8f99-447a-8300-c77b5e098897.png)
and after start 
![Zrzut ekranu (3)](https://user-images.githubusercontent.com/90521869/133324842-b21c7961-8f57-4caa-a133-9bd679cb0ee2.png)

**Comment by Oskaris25** [comment]
ok, i found something if after reboot we type / is admin syncupgrades * border increased to what it should be.

**Comment by OmerBenGera** [comment]
> ok, i found something if after reboot we type /is admin syncupgrades * border increased to what it should be.

Yeah makes sense.
I will look into that as soon as possible :)

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it's fixed in this version

**Comment by Oskaris25** [comment]
now, it's ok
