### ISSUE TITLE
Islands were deleted with one of the latest dev build

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#572]
### Minecraft's Version

Airplane 1.17.1

### Plugin's Version

Dev build 282

### Describe the bug

Since the update to this dev build to fix the mysql issue, the plugin says there is no island available, for all players it says that they have no island...

Hope it's just an issue with loading the data because if I lost everything that is stored on the database It would be horrible.

### To Reproduce

Use Mysql and the latest dev build

### Additional Information

I tried to went back to dev build 280 and still "no island found" for everyone...

**Comment by banicola** [comment]
Error I just saw from this morning when I did the database conversion: https://pastebin.com/raw/yArY9fCJ

**Comment by OmerBenGera** [comment]
Latest dev build will fix the issue.
Let the migration re-run again by deleting the new tables and rename the old tables to not have "bkp" in their names anymore.

**Comment by banicola** [comment]
Hey, the same error was sent again this morning during the migration re-run. At least I got my islands back but for example some island chests were deleted from what players told me.

**Comment by OmerBenGera** [comment]
What are the structures of the `island_chests` and `island_warps` tables?

**Comment by banicola** [comment]
island_chests:
![image](https://user-images.githubusercontent.com/25954399/132094056-45ad14e8-344d-47d9-b025-ea2fad1f80b4.png)

island_warps:
![image](https://user-images.githubusercontent.com/25954399/132094073-5ee22a9b-5d77-4af6-9baf-e8c18a24cfba.png)

**Comment by OmerBenGera** [comment]
Do you have a warp name with a longer than 30 chars?

**Comment by banicola** [comment]
Hum, yes after looking at it, I see a warp with the name: unishopchat459e2528de41dfb467d3f9384872ca (41 characters)

**Comment by OmerBenGera** [comment]
> 
> 
> Hum, yes after looking at it, I see a warp with the name: unishopchat459e2528de41dfb467d3f9384872ca (41 characters)

I see - I am currently working on a fix for it, will update you once it's published.

**Comment by OmerBenGera** [comment]
Check out latest dev build, make sure you do the same process of deleting tables etc again.

**Comment by banicola** [comment]
There error for the island_warps seems to be gone but not the one for the chests: https://pastebin.com/raw/PAktPRWf

**Comment by OmerBenGera** [comment]
> 
> 
> The error for the island_warps seems to be gone but not the one for the chests: https://pastebin.com/raw/PAktPRWf

Oh I missed this one, will look into that.
Weird, there shouldn't be any limit for this column...

**Comment by OmerBenGera** [comment]
Apparently there seems to be a limit for the column of around 60k chars, so I changed the column's type to LONGTEXT, which can hold around 4 billion chars. This should do the trick. If the issue still occurs, send me the structure of the `islands_chest` table again.

Also, make sure you reset tables etc so the migration will occur again.

**Comment by banicola** [comment]
I took a quick look and at least one island (maybe the largest one with 5 chests) has a content length of 102339 characters

**Comment by OmerBenGera** [comment]
Have you checked it out?

**Comment by banicola** [comment]
Yes I re-runned the conversion and everything seems to be working fine now. I did a restart after the conversion to be sure and there's no issue visible. Thanks for the fixes.

**Comment by OmerBenGera** [comment]
You welcome.
There might be more bugs with MySQL due to how they limit column types with the length they can hold things, and hopefully I'll be able to fix them all asap :)

Closing this for now.
