### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by jack201819** [BG-Software-LLC/SuperiorSkyblock2#573]
### Minecraft's Version

Paper_1.16.5_Java11.jar

### Plugin's Version

SuperiorSkyblock2-b276.jar

### Describe the bug

WARN HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@229eb765 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value. this happens after a server restart or when players and admins like myself. 

### To Reproduce

none

### Additional Information

https://pastebin.com/gxKFqpuQ here is my config is where my database has been setup this may help you but what the console was showing was only mysql errors

**Comment by OmerBenGera** [comment]
Does it affect anything? It seems like a warning that can be ignored for me...

**Comment by OmerBenGera** [comment]
I added support for configurable wait-timeout and max-lifetime for MySQL.
Configure them to meet your MySQL server and the warnings will be gone.
