### ISSUE TITLE
Island reset after restart

### ISSUE THREAD

**Issue by chromaseth** [BG-Software-LLC/SuperiorSkyblock2#574]
### Minecraft's Version

purpur-1.16.5-1171.jar

### Plugin's Version

SuperiorSkyblock2-b286.jar

### Describe the bug

I found an issue, that whenever you disband your island, and then accept invite from other player as their island member, the other player island will be disbanded after server restart.. it also happen when you just disband your island and you visit other player island via warps, it will also get disband after restart...

but somehow, after a player disband his island and idk what the exact time until database get updated... and the player visit your island, it stay safe after server restart.

other experiment is, I just disband my island, and restart the server, after server started, accept island invite as member... it doesn't cause any problem.
so I think it's caused by database is not immediately get update after island disband

### To Reproduce

user1 /is create
user2 /is create

user1 /is disband
user2 /is invite user1
user1 /is accept

server restart

user2&user1 no island

**Comment by OmerBenGera** [comment]
This is a known issue, and I have published a potential fix moments ago.
Let me know if it works for you

**Comment by chromaseth** [comment]
All good in latest build

SuperiorSkyblock2-b287.jar



<br class="Apple-interchange-newline">
</body>
</html>
