### ISSUE TITLE
Non-solid blocks with a limit are not counted if block below broken

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#575]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b280

### Describe the bug

Non-solid blocks with a limit are not counted if block below broken

### To Reproduce

Set limit for repeaters (for example), place it and break block below repeater

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
