### ISSUE TITLE
Restart disable borders

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#576]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b288

### Describe the bug

After every restart, islands border are toggled OFF

### To Reproduce

Turn ON islands border, restart, check them, they are OFF

### Additional Information

I'm using MySQL

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
