### ISSUE TITLE
SS2 doesn't support v1_16_R3  and has been disabled the server

### ISSUE THREAD

**Issue by RookieAND** [BG-Software-LLC/SuperiorSkyblock2#577]
### Minecraft's Version

Paper 1.16.5 (build 788, lastest build)

### Plugin's Version

SuperiorSkyblock2-b295 (lastest build at 2021/09/06)

### Describe the bug

Server has been disabled when I load my server.

[23:14:10 INFO]: [SuperiorSkyblock2] Loading SuperiorSkyblock2 v1.7.0-DEVb295
[23:14:10 INFO]: [SuperiorSkyblock2] SuperiorSkyblock doesn't support v1_16_R3 - shutting down...

### To Reproduce

It seems SS2 doesn't support 1.16.5. So plz fix this error 

### Additional Information

There's no log of this problem. only **[SuperiorSkyblock2] SuperiorSkyblock doesn't support v1_16_R3 - shutting down... is the hint.

**Comment by Skizzles** [comment]
@RookieAND please provide more details, usually SSB has more in logs to help determine the issue.

In the meantime, did you install a Javascript engine module which is required for later builds?

**Comment by OmerBenGera** [comment]
It seems to work fine for me
Try re-downloading the plugin and try again.

**Comment by RookieAND** [comment]
> @RookieAND please provide more details, usually SSB has more in logs to help determine the issue.
> In the meantime, did you install a Javascript engine module which is required for later builds?

Sorry for my poor request. I solve this problem because of config mistake. I truly appreciate to help this problem.
