### ISSUE TITLE
War-Manager.yml Issue

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#579]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

Build #295

### Describe the bug

https://pastebin.com/n8Snxes3

When removing anything from here and all other menus in the plugin they can be removed from the gui with no issue but when removing this '~': from the settings or the pattern it causes an error to happen

######################################################
######################################################

title: '&3Island Warp: {0}'
previous-menu: true

pattern:
  - '+ + + + + + + + +'
  - '+ + + + ~ + + + +'
  - '+ + ! + % + $ + +'
  - '+ + + + + + + + +'
  - '+ + + + + + + + +'

success-update-sound:
  type: ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 0.2
  pitch: 0.2

warp-rename: '!'
warp-icon: '~'
warp-location: '$'
warp-private: '%'

items:
  '~':
    type: ENDER_PEARL
    lore:
      - '&f '
      - '&f&l{0} is used for the warp &a&lName'
      - '&f&l{2} is used for the warp &a&lStatus'
      - '&f&lClick to edit the &a&l&nIcon'
  '!':
    type: SIGN
    name: '&6&lRename Warp'
    lore: []
  '$':
    type: IRON_PLATE
    name: '&6&lWarp Location Set'
    lore: []
  '%':
    type: IRON_FENCE
    name: '&6&lWarp Status'
    lore: []
  '+':
    type: STAINED_GLASS_PANE
    data: 15
    name: '&f'
    lore: []

### To Reproduce

Remove the ~ one from the pattern map and the issue will happen

### Additional Information

So that i can disable editing that warps lores and so forth when right clicking that item and if it's not there there's no way to do that just like i was able to make it so some of the other things like categories and all the plugin offers

**Comment by OmerBenGera** [comment]
You cant remove this, simple as that.

**Comment by DebuffPvP** [comment]
So how do you make it so people can't access warp editing?
