### ISSUE TITLE
Islands bank rounding

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#580]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b296

### Describe the bug

Sometimes when I deposit money into the bank, instead of deposit "1 685 000" it will deposit "1 684 999.99", it happens randomly.

### To Reproduce

Spam "/is deposit 1685000"

### Additional Information
I'm using MySQL

It's in french but it tells "Warn deposited XXX$ into the island bank"
(Look at the last message, it's not the good amount)
![Screenshot_6096](https://user-images.githubusercontent.com/31826333/132342588-4e077e26-ca6a-439e-b6ac-900cb50f1313.png)

**Comment by OmerBenGera** [comment]
What economy plugin are you using?

**Comment by OmerBenGera** [comment]
I tried to replicate the issue using Essentials as an economy plugin but it seems to work fine

**Comment by WarnDangerous** [comment]
I'm using essentialsX and vault.

Did you also try on MySQL ? 

On a fresh new config with SQL I didn't get the issue

**Comment by OmerBenGera** [comment]
> I'm using essentialsX and vault.
> 
> Did you also try on MySQL ?
> 
> On a fresh new config with SQL I didn't get the issue

I will check it with MySQL and get back to you

**Comment by OmerBenGera** [comment]
I tried it using MySQL and I can't seem to replicate the issue.

**Comment by WarnDangerous** [comment]
I didn't get the issue before, but that's not a big issue, so I'll close it and reopen one if I get more informations
