### ISSUE TITLE
Enchanting mission bug

### ISSUE THREAD

**Issue by chromaseth** [BG-Software-LLC/SuperiorSkyblock2#581]
### Minecraft's Version

purpur-1.16.5-1171.jar

### Plugin's Version

SuperiorSkyblock2-b295.jar

### Describe the bug

player mission - enchanting mission can be claim infinitely after enchanting all armor with protection IV

### To Reproduce

enchant all armor with protection IV

claim mission

doesn't change it to completed and still give reward to player

**Comment by OmerBenGera** [comment]
Send me the mission from your missions file.

**Comment by chromaseth** [comment]
[https://pastebin.com/gwgH0DVF](url) just the basic config from the plugin itself

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Mind taking a video showcasing the bug?

**Comment by chromaseth** [comment]
oh nvm, I test it again and it work fine now
