### ISSUE TITLE
SkinsRestorer not working with player heads

### ISSUE THREAD

**Issue by RinNiko** [BG-Software-LLC/SuperiorSkyblock2#583]
### Minecraft's Version

Purpur 1.16.5

### Plugin's Version

SuperiorSkyblock2-b251

### Describe the bug

So don't know why all skull from my menu not show owner skull 
![image](https://user-images.githubusercontent.com/49575027/132501241-52c7f557-4db8-44e5-8277-9af67ec9ace7.png)

### To Reproduce

Just try use /is top and it not show your heads texture

**Comment by OmerBenGera** [comment]
Do you have your server on offline mode?

**Comment by RinNiko** [comment]
> Do you have your server on offline mode?
Yes is that problem ?

**Comment by OmerBenGera** [comment]
> Yes is that problem ?
> and I already have skinrestorer lastest version

I will look into that.
If you have SkinsRestorer you should be good.

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Do you have maybe BungeeCord?

**Comment by RinNiko** [comment]
Yes I'm currently use BungeeCord

**Comment by OmerBenGera** [comment]
> 
> 
> Yes I'm currently use BungeeCord

Well, if you have SkinsRestorer installed as a BungeeCord, then you technically don't have SkinsRestorer installed on your servers, therefore no skins will be restored.
It's a known issue with the way SkinsRestorer works and there's nothing I can do regarding this.
I am closing this for now
