### ISSUE TITLE
Infinite Value Dupe Glitch when using Sponge

### ISSUE THREAD

**Issue by ClickErrorxD** [BG-Software-LLC/SuperiorSkyblock2#584]
### Minecraft's Version

MC-Version: 1.16.5
Jar: paper-1.16.5.jar

### Plugin's Version

SuperiorSkyblock2-b239.jar

### Describe the bug

Basically, if your server uses Sponge(s) as a value block for /is top, you can infinite get free levels by the following steps:
1. Have a sponge.
2. Have a large water area.
3. Place the sponge,turning it into a wet sponge.
4. Break the wet sponge
5. you then break it, which gives you the sponge back but lets you keep the levels it added to your island.

### To Reproduce

1. Have a sponge.
2. Have a large water area.
3. Place the sponge,turning it into a wet sponge.
4. Break the wet sponge
5. you then break it, which gives you the sponge back but lets you keep the levels it added to your island.

### Additional Information

https://youtu.be/63Zhuo1Ox2s

**Comment by OmerBenGera** [comment]
I will look into that, thanks for reporting.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
