### ISSUE TITLE
Spawner Block limits

### ISSUE THREAD

**Issue by NameIsCam** [BG-Software-LLC/SuperiorSkyblock2#585]
### Minecraft's Version

paperMC, 1.16.5

### Plugin's Version

1.7.0-DEVb295

### Describe the bug

(Don't know if this is a bug, discord tried to help but no luck) You can do "/is admin setblocklimit <name> SPAWNER:VILLAGER 100" and it will limit the number of spawner blocks of a villager but if I set it via the config it does not work (I can place over 100).
  
CONFIG:

  block-limits:
  - HOPPER:8
  - SPAWNER:VILLAGER:100

### To Reproduce

N/A

**Comment by NameIsCam** [comment]
Potential fix: Instead of setting "SPAWNER:VILLAGER:#" in the config, you can create an upgrade for it. "SPAWNER:VILLAGER: 200" which does work.

**Comment by OmerBenGera** [comment]
> Potential fix: Instead of setting "SPAWNER:VILLAGER:#" in the config, you can create an upgrade for it. "SPAWNER:VILLAGER: 200" which does work..
> 
> Still feel like it should work in the main config but I may be wrong.

It might be a parsing issue, therefore I will look into that.
In general, the default-values section in the config should be used only if there are no upgrades for an island, so if thats not the case, then it makes sense it doesnt work

**Comment by OmerBenGera** [comment]
I tried to look into that, and I found an issue with detection of default block limits.
I fixed it, and checked if it's possible to set limits for specific spawner types and it worked.
Check out latest dev build, let me know if it works for you

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by NameIsCam** [comment]
Sorry, I have not tested it yet. I have been busy, with little time to get around to it. If I have time this weekend, I'll try and get it checked.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
> 
> 
> Hey! I just tested it it, and it works. The config for that section:
> 
> block-limits:
> - 'HOPPER:8'
> - 'SPAWNER:VILLAGER:100'

It works as intended now?

**Comment by NameIsCam** [comment]
Yes, it works as intended. Thank you!
