### ISSUE TITLE
/is level calculation timed out

### ISSUE THREAD

**Issue by juancruzdal** [BG-Software-LLC/SuperiorSkyblock2#586]
### Minecraft's Version

git-PaperSpigot-"4c7641d" (MC: 1.8.8)

### Plugin's Version

1.7.0-DEVb296

### Describe the bug

When my players do /is level receive the "Error:the calculation task has timed out. try again later..." message, and in the console theres no errrors

### To Reproduce

do /is level

### Additional Information

This happened after the database migration

**Comment by OmerBenGera** [comment]
Making a calculation task takes a lot of time and it times out. This can be because the plugin cannot load the chunk due to lag of server or something like that.

Do you have an idea what can make the task delayed?

**Comment by juancruzdal** [comment]
my server is not laggy, i think this is happening only to the islands who was migrated, the new islands level calculation works fine

**Comment by juancruzdal** [comment]
[database.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7137667/database.zip)
this is my database file, try it

**Comment by CryLegende** [comment]
I have the same problem
Since I have updated to the new database system, many players get stuck because of that
Once they make /is level, the calculation process never end and the player can't do anything anymore on his island until the server restart

**Comment by OmerBenGera** [comment]
> 
> 
> my server is not laggy, i think this is happening only to the islands who was migrated, the new islands level calculation works fine

There's no difference between migrated islands and old islands in terms of island calculations.

**Comment by CryLegende** [comment]
> There's no difference between migrated islands and old islands in terms of island calculations.

Maybe there is one "difference"
The stacked blocks don't get migrated well to the new database, so maybe the island calculation try to calculate stacked block and fail

**Comment by OmerBenGera** [comment]
> 
> 
> > There's no difference between migrated islands and old islands in terms of island calculations.
> 
> Maybe there is one "difference"
> The stacked blocks don't get migrated well to the new database, so maybe the island calculation try to calculate stacked blocks and fail

I don't know about any failure in the migration.
If you believe there is, then open an issue on github.
Anyways this is not related to this issue, and even if it fails to migrate stacked blocks, it has nothing to do with the islands calculation.

**Comment by nivcoo** [comment]
I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay

**Comment by nivcoo** [comment]
The issue appear in b284 changes, it works correctly in b283

**Comment by OmerBenGera** [comment]
> 
> 
> I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay

Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.

**Comment by nivcoo** [comment]
> > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> 
> Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.

I will try

**Comment by nivcoo** [comment]
> > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> 
> Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.

Nothing append https://pics.revolis.fr/2021-09/10/17-37_nRBb.png

**Comment by OmerBenGera** [comment]
> 
> 
> > > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> > 
> > 
> > Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.
> 
> Nothing happened https://pics.revolis.fr/2021-09/10/17-37_nRBb.png

Do you have WildStacker installed?

**Comment by nivcoo** [comment]
> > > > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> > > 
> > > 
> > > Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.
> > 
> > 
> > Nothing happened https://pics.revolis.fr/2021-09/10/17-37_nRBb.png
> 
> Do you have WildStacker installed?

Yes

**Comment by OmerBenGera** [comment]
> 
> 
> > > > > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> > > > 
> > > > 
> > > > Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.
> > > 
> > > 
> > > Nothing happened https://pics.revolis.fr/2021-09/10/17-37_nRBb.png
> > 
> > 
> > Do you have WildStacker installed?
> 
> Yes

Try deleting it, let me know if it works by any chance

**Comment by nivcoo** [comment]
> > > > > > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> > > > > 
> > > > > 
> > > > > Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.
> > > > 
> > > > 
> > > > Nothing happened https://pics.revolis.fr/2021-09/10/17-37_nRBb.png
> > > 
> > > 
> > > Do you have WildStacker installed?
> > 
> > 
> > Yes
> 
> Try deleting it, let me know if it works by any chance

I will try now

**Comment by nivcoo** [comment]
> > > > > > I've the same issue, before new database system the /is level works correctly, i use now the b296 (before b256) and i've this issue the level calculation loading stay
> > > > > 
> > > > > 
> > > > > Run `/is admin debug Action: Block Place` and then run `/is admin recalc <player-name>`, and let me know if something is printed to screen.
> > > > 
> > > > 
> > > > Nothing happened https://pics.revolis.fr/2021-09/10/17-37_nRBb.png
> > > 
> > > 
> > > Do you have WildStacker installed?
> > 
> > 
> > Yes
> 
> Try deleting it, let me know if it works by any chance

Without ws i've big error after the command : https://hastebin.com/ajupihoziz.properties

**Comment by nivcoo** [comment]
(I think it's the debug message after the restart)

**Comment by OmerBenGera** [comment]
> 
> 
> (I think it's the debug message after the restart)

Check out latest dev build, the error should be fixed.

**Comment by nivcoo** [comment]
It works :p

**Comment by OmerBenGera** [comment]
> 
> 
> It works :p

So calculation works without WildStacker, right?

**Comment by nivcoo** [comment]
> > It works :p
> 
> So calculation works without WildStacker, right?

Yes and also with ws

**Comment by OmerBenGera** [comment]
> 
> 
> > > It works :p
> > 
> > 
> > So calculation works without WildStacker, right?
> 
> Yes and also with ws

Wait, calculation works now as it should?
The issue is fixed for you?

**Comment by nivcoo** [comment]
For me it works

**Comment by OmerBenGera** [comment]
@juancruzdal Mind checking latest version? I made some changes that may have fixed the issue

**Comment by OmerBenGera** [comment]
Any news regarding this?
