### ISSUE TITLE
block limits doesn't work

### ISSUE THREAD

**Issue by CryLegende** [BG-Software-LLC/SuperiorSkyblock2#587]
### Minecraft's Version

PaperSpigot 1.12.2 latest build
(git-Paper-dd8679b)

### Plugin's Version

SuperiorSkyblock2-b296.jar

### Describe the bug

The block limit doesn't work (config part and with command)

### To Reproduce

Just try to bypass the block limits

### Additional Information

block-limits:
  - HEADS:15
  - HOPPER:4
  - BANNER:60
  - FURNACE:40
  - BURNING_FURNACE:1
  - ENDER_CHEST:20
  - JUKEBOX:50
  - DISPENSER:32
  - DROPPER:32
  - OBSERVER:50
  - NOTEBLOCK:100
  - ENCHANTMENT_TABLE:50
  - BEACON:24
  - FLOWER_POT:40
  - BREWING_STAND:20
  - SLIME_BLOCK:100
  - DAYLIGHT_DETECTOR:10
  - DAYLIGHT_DETECTOR_INVERTED:10
  - CHEST:100
  - TRAPPED_CHEST:50
  - SIGN:100
  - WALL_SIGN:100
  - SIGN_POST:300

**Comment by OmerBenGera** [comment]
When you run /is admin show, do you have the limits shown in the message?

**Comment by CryLegende** [comment]
No, only that
![image](https://user-images.githubusercontent.com/25080946/132713650-50af6e07-e0f1-4256-9cb1-2bc0943d16bc.png)

**Comment by CryLegende** [comment]
Here is my exact block-limits list
![image](https://user-images.githubusercontent.com/25080946/132714521-8e112bb6-9523-4f02-ba07-de060929e978.png)

**Comment by OmerBenGera** [comment]
It seems like you have an upgrade for block limits, where you set "Example Block" to have a limit of 5
Am I wrong?

**Comment by CryLegende** [comment]
> It seems like you have an upgrade for block limits, where you set "Example Block" to have a limit of 5
> Am I wrong?

No, I don't have any "Example Block" upgrade
In fact, I have no upgrade at all since I disabled the upgrades module

**Comment by CryLegende** [comment]
config.yml from SS2/modules/upgrades
![image](https://user-images.githubusercontent.com/25080946/132865956-29cefc93-2be9-493a-bb00-50671eb33fee.png)

**Comment by OmerBenGera** [comment]
you have a blocks-limit upgrade, therefore the block-limits in default-values isn't working.
You need to create an upgrade with the limits you want, so islands will have these applied.

**Comment by CryLegende** [comment]
I'm- what ?
> you have a blocks-limit upgrade
Where ? I don't see any blocks-limit upgrade

> therefore the block-limits in default-values isn't working.
I don't want to have block-limits upgrade, I only want to have the default-values

> You need to create an upgrade with the limits you want, so islands will have these applied.
I don't want the limits to be upgraded, but I still have to create upgrades ?

**Comment by OmerBenGera** [comment]
> 
> 
> I'm- what ?
> 
> > you have a blocks-limit upgrade
> 
> Where ? I don't see any blocks-limit upgrade
> 
> > therefore the block-limits in default-values isn't working.
> 
> I don't want to have block-limits upgrade, I only want to have the default-values working
> 
> > You need to create an upgrade with the limits you want, so islands will have these applied.
> 
> I don't want the limits to be upgraded, but I still have to create upgrades ?

Literally the first upgrade is a blocks-limit upgrade: hoppers-limit.

**Comment by OmerBenGera** [comment]
> 
> 
> I'm- what ?
> 
> > you have a blocks-limit upgrade
> 
> Where ? I don't see any blocks-limit upgrade
> 
> > therefore the block-limits in default-values isn't working.
> 
> I don't want to have block-limits upgrade, I only want to have the default-values working
> 
> > You need to create an upgrade with the limits you want, so islands will have these applied.
> 
> I don't want the limits to be upgraded, but I still have to create upgrades ?

And yes, you need to have an upgrade for your default limits if you already have a blocks-limit upgrade.
I recommend reading the comments in the config next time.

**Comment by CryLegende** [comment]
As you can see at the top of the screen, the upgrade config is disabled
![image](https://user-images.githubusercontent.com/25080946/132870858-d91e600d-e572-478a-a349-a1b5c3592e57.png)

**Comment by CryLegende** [comment]
For the hoppers-limit, this is the default one, if I delete it (since I don't use it, that why I disabled the upgrade module) I will be able to use the default block-limits values ?

**Comment by OmerBenGera** [comment]
Let me take another look into that.

**Comment by OmerBenGera** [comment]
There was an issue with detecting the default blocks limit.
It should be fixed in latest dev build, let me know if it works for you.

**Comment by CryLegende** [comment]
The fix is half working, now I see the list in /island admin show but I still can bypass these limits
![image](https://user-images.githubusercontent.com/25080946/132948455-117a974b-5d03-4193-884a-ef622ccd56ae.png)

**Comment by OmerBenGera** [comment]
> 
> 
> The fix is half working, now I see the list in /island admin show but I still can bypass these limits
> ![image](https://user-images.githubusercontent.com/25080946/132948455-117a974b-5d03-4193-884a-ef622ccd56ae.png)

Are you able to bypass all the limits?
Also, does it happen also on a new island?

**Comment by CryLegende** [comment]
I have tester the head, hopper, Furnace, ender chest, slime block and beacon
I've also try with item frames and it doesn't work either so I'm assuming the entity-limit doesn't work too
I didn't try on a new island, I'll try

**Comment by CryLegende** [comment]
It doesn't work on a new island

**Comment by nivcoo** [comment]
It works fine for me (after and before /is reset), are you an operator ? Or do you have bypass permission ?

**Comment by OmerBenGera** [comment]
> 
> 
> It doesn't work on a new island

When you place one block that has a limit and you run /is counts, do you see it there?

**Comment by CryLegende** [comment]
> > It doesn't work on a new island
> 
> When you place one block that has a limit and you run /is counts, do you see it there?

Yes, I have 42 furnace in the /is counts gui and in /is admin show the limit is 40 furnace
(same with other blocs)

**Comment by OmerBenGera** [comment]
> > > It doesn't work on a new island
> > 
> > 
> > When you place one block that has a limit and you run /is counts, do you see it there?
> 
> Yes, I have 42 furnace in the /is counts gui and in /is admin show the limit is 40 furnace
> (same with other blocs)

And you still can place furnaces..?
Try running `/is admin debug Action: Block Place`,  and then place a furnace, check what is printed to console and report back.

**Comment by CryLegende** [comment]
No matter what blocks my players uses, the amount in the console is always 1
![image](https://user-images.githubusercontent.com/25080946/132962943-b03b80c4-eb4e-419a-ac6b-9d90c35a6ca1.png)

**Comment by CryLegende** [comment]
[00:16:11 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: UserName778877, Block: FURNACE:3, Amount: 1
[00:16:11 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: UserName778877, Block: FURNACE:4, Amount: 1
[00:16:12 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: UserName778877, Block: FURNACE:3, Amount: 1

**Comment by OmerBenGera** [comment]
> 
> 
> No matter what blocks my players uses, the amount in the console is always 1
> ![image](https://user-images.githubusercontent.com/25080946/132962943-b03b80c4-eb4e-419a-ac6b-9d90c35a6ca1.png)

That's fine, as you can only place one block at a time (unless you use WildStacker for example and place a stacked spawner, etc) - so that's fine.
I will look into that anyways and check why it occurs.

**Comment by CryLegende** [comment]
Thank you for your help

**Comment by OmerBenGera** [comment]
I found out an issue when running `/is admin level` in legacy versions which I will check out.

**Comment by OmerBenGera** [comment]
Check out latest dev build - make sure you run 1/is admin level <player-name>` before you try it.

**Comment by CryLegende** [comment]
/is admin level return nothing and I can still bypass the limit

**Comment by CryLegende** [comment]
And my /is counts has duplicated some blocks
![image](https://user-images.githubusercontent.com/25080946/133421267-3ed176be-f07c-42d7-b49b-5fd1b210d8db.png)

**Comment by nivcoo** [comment]
He meant recalc not level i think

**Comment by CryLegende** [comment]
It's the same command ^^

**Comment by CryLegende** [comment]
/island admin level still doesn't work and only show me "calculating..." with the latest build, maybe that can be related ?

**Comment by OmerBenGera** [comment]
> /island admin level still doesn't work and only show me "calculating..." with the latest build, maybe that can be related ?

Weird, seems like the calculation cannot process, which is not related.
Try it on another server with only SSB installed, let me know if it works

**Comment by CryLegende** [comment]
Is there a way to debug the /is admin level command to see why she doesn't work please ?

**Comment by CryLegende** [comment]
It's work fine on a fresh server with only SSB installed
The problem is here since I updated to the new database system

**Comment by OmerBenGera** [comment]
@CryLegende Does it still occur?

**Comment by CryLegende** [comment]
Yes, I'll try the latest build tonight

**Comment by CryLegende** [comment]
Little recap of the situation on my server with the latest build:
/is level is working fine
/is counts still show most blocks in duplicate (not all)
![image](https://user-images.githubusercontent.com/25080946/134757921-d5eb76b3-d7a7-4b15-872b-3422b91978e0.png)
/island admin level return nothing
![image](https://user-images.githubusercontent.com/25080946/134757946-2dfc281b-140c-465b-a747-887560af2e8d.png)
I can still bypass the limits (with a new account without permission) even if they are correctly displayed in the /island admin show

Thank you for your help

**Comment by OmerBenGera** [comment]
Focus on block limits. Anything else is not related to this issue.
I dont see any blocks in your counts that have a limit... The screenshot is not helpful. Also, you havent checked `/is admin show`, so neither of us know even if your island has any limits.

**Comment by CryLegende** [comment]
The /is counts screen was from my own island, not from one of the test island
Here is an /is counts and an /is admin show from a fresh new test island:
![image](https://user-images.githubusercontent.com/25080946/134769117-38766f3a-e966-4889-9787-a3e4e941c298.png)
Grass, sand, bedrock... all those blocks are from the default schematic but they are duplicated too in the /is counts menu. All I added to the island is 122 Slime blocks, 50 furnaces and 40 droppers so I bypassed 3 limits. I can try with more limits if you want
/is admin show:
![image](https://user-images.githubusercontent.com/25080946/134769227-b695f109-fa31-47b2-894d-b0f926a13b38.png)

**Comment by OmerBenGera** [comment]
> 
> 
> The /is counts screen was from my own island, not from one of the test island
> Here is an /is counts and an /is admin show from a fresh new test island:
> ![image](https://user-images.githubusercontent.com/25080946/134769117-38766f3a-e966-4889-9787-a3e4e941c298.png)
> Grass, sand, bedrock... all those blocks are from the default schematic but they are duplicated too in the /is counts menu. All I added to the island is 122 Slime blocks, 50 furnaces and 40 droppers so I bypassed 3 limits. I can try with more limits if you want
> /is admin show:
> ![image](https://user-images.githubusercontent.com/25080946/134769227-b695f109-fa31-47b2-894d-b0f926a13b38.png)

Are you sure you're using latest dev build? I have fixed this already...

**Comment by CryLegende** [comment]
I'm using the build 316 but I will upgrade to the 318 in 2h30 hours

**Comment by OmerBenGera** [comment]
> I'm using the build 316 but I will upgrade to the 318 in 2h30 hours

Thats fine.
I will try to replicate it in 1.12.

**Comment by CryLegende** [comment]
Thank you for your help

**Comment by OmerBenGera** [comment]
Seems to work fine for me on 1.12.2.
Are you able to replicate the issue with only SSB installed, using default files, on 1.12.2?
Try only creating an island, setting a limit using `/is admin setblocklimit` and then place furnaces in different directions, and see if it still occurs.

**Comment by CryLegende** [comment]
I think the problem come from my database that may be corrupted since the migration to the new db system so that normal that you can't replicate the problem with a fresh new config
If you want I can give you my database.db

**Comment by OmerBenGera** [comment]
> 
> 
> I think the problem come from my database that may be corrupted since the migration to the new db system so that normal that you can't replicate the problem with a fresh new config If you want I can give you my database.db

This has nothing to do with anything related to your database.

**Comment by CryLegende** [comment]
The /is counts menu work fine since the latest builds
I can also bypass the /is admin setblocklimit with a new island

**Comment by OmerBenGera** [comment]
> 
> 
> The /is counts menu work fine since the latest builds I can also bypass the /is admin setblocklimit with a new island, I even have the limits in my database ![image](https://user-images.githubusercontent.com/25080946/135698432-eace9dab-ebbb-40df-8cdf-50623cee4a4a.png)

You can still bypass it?

**Comment by CryLegende** [comment]
Yes, I have no message, nothing, I can just bypass the limits even those set via the setblocklimit command with build 324

**Comment by OmerBenGera** [comment]
> 
> 
> Yes, I have no message, nothing, I can just bypass the limits even those set via the setblocklimit command with build 324

Do you see your limits in `/is admin show`?
Also, how did you set your limits? Using `/is admin setblocklimit` or using upgrade/default block limits?

**Comment by CryLegende** [comment]
• Upgrades are disabled
• I'm using the block-limits option in the config for my limits
• The bug is here with the setblocklimit command too
• `/is admin show` show the limits set with the setblocklimit command and the block-limits limits so there is no problem here
• The limits are saved in my sqlite database only when set with the setblocklimit command, the block-limits limits aren't in my database (that seems normal but I am specifying)

I have no message, nothing, I can just bypass the limits even those set via the setblocklimit command

**Comment by OmerBenGera** [comment]
> 
> 
> • Upgrades are disabled • I'm using the block-limits option in the config for my limits • The bug is here with the setblocklimit command too • `/is admin show` show the limits set with the setblocklimit command and the block-limits limits so there is no problem here • The limits are saved in my sqlite database only when set with the setblocklimit command, the block-limits limits aren't in my database (that seems normal but I am specifying)
> 
> I have no message, nothing, I can just bypass the limits even those set via the setblocklimit command

Run `/is admin debug Action: Block Place` and check what debug message is printed to console when you place a block that has a limit.

**Comment by CryLegende** [comment]
`[17:47:03 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: Cry_Legende, Block: STONE:0, Amount: 1
[17:47:03 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: Cry_Legende, Block: STONE:0, Amount: 1
[17:47:04 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: Cry_Legende, Block: STONE:0, Amount: 1
[17:47:04 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: Cry_Legende, Block: STONE:0, Amount: 1
[17:47:04 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: Cry_Legende, Block: STONE:0, Amount: 1`

**Comment by CryLegende** [comment]
The debug command output the thing from the last time :

> No matter what blocks my players uses, the amount in the console is always 1 ![image](https://user-images.githubusercontent.com/25080946/132962943-b03b80c4-eb4e-419a-ac6b-9d90c35a6ca1.png)

**Comment by OmerBenGera** [comment]
After you place a block, does its counts increase in `/is counts`?

**Comment by CryLegende** [comment]
On a fresh new install I think it's working fine

**Comment by OmerBenGera** [comment]
> 
> 
> On a fresh new install I think it's working fine

Ok, now try adding plugins one by one until you find what breaks it.

**Comment by OmerBenGera** [comment]
After some thinking, I am gonna keep block-limits as part of upgrades.
Will probably add the ability to disable certain features in upgrades in the future so you'll be able to use it even if other parts of upgrades are disabled.
