### ISSUE TITLE
Island Top

### ISSUE THREAD

**Issue by ThinkRusty87** [BG-Software-LLC/SuperiorSkyblock2#589]
**Minecraft's Version**
1.17.1

**Plugin's Version**
SuperiorSkyblock2-b293

**Describe The Bug**
When you create a island it will show 0 worth and level in /is top. 

If you have a island and place blocks, they are not being taken into account in /is top, even if they are added to the worth.yml file. 

If you type /is recalc, /is level or /is admin recalc it either resets both and shows it as 0.

**Additional Information**
I notice that when you create a new island, you start with negative worth if you have "schematic-offset" set to true. 
As you delete blocks off your island, it keeps going way down. 

If you have "negative-worth" set to false in the config file, it wont go past 0 when you type /is top because your so far in the negatives.

One solution would be to update the worth.yml file and add all of the block types especially for version 1.17 and 1.17.1 so more blocks are registered.

**Comment by OmerBenGera** [comment]
Try running `/is admin debug Action: Block Place`, and then run /is recalc. Let me know if you see any debug messages in console

**Comment by ThinkRusty87** [comment]
09.09 16:34:19 [Server] INFO ThinkRusty87 issued server command: /is admin debug
09.09 16:34:36 [Server] INFO ThinkRusty87 issued server command: /is admin debug Action: Block Place
09.09 16:34:50 [Server] INFO ThinkRusty87 issued server command: /is recalc
09.09 16:34:50 [Server] INFO [DEBUG] Action: Block Place, Island: ThinkRusty87, Block: DIRT, Amount: 100
09.09 16:34:50 [Server] INFO [DEBUG] Action: Block Place, Island: ThinkRusty87, Block: FURNACE, Amount: 2
09.09 16:34:50 [Server] INFO [DEBUG] Action: Block Place, Island: ThinkRusty87, Block: CHEST, Amount: 12

**Comment by OmerBenGera** [comment]
The plugin counted 100 dirt blocks, 2 furnaces and 12 chests on your island
Do you have more blocks than that?

**Comment by ThinkRusty87** [comment]
As you can see in the screenshot, it still shows the island worth as 0 regardless.
 
To anwser your question, yes there are more blocks and it doesn't count them. 

Also, when someone does /is recalc or /is level it resets it back to 0.

**Comment by OmerBenGera** [comment]
> 
> 
> To anwser your question, yes there are more blocks and it still doesn't count them.
> 
> As you can see in the screenshot, it still shows the island worth as 0 regardless of what blocks are registered.
> 
> Also, when someone does /is recalc or /is level it resets it back to 0.

Are you able to replicate the issue using default files and on another server with only SSB installed?

**Comment by ThinkRusty87** [comment]
Yes

**Comment by OmerBenGera** [comment]
> 
> 
> Yes, I can.

I understand. I have another question for you - do you have WildStacker installed?

**Comment by ThinkRusty87** [comment]
No I do not.

**Comment by OmerBenGera** [comment]
> 
> 
> No I do not. I do have RoseStacker though.

Does it still occur if you run it on a new island?

**Comment by ThinkRusty87** [comment]
Yes it does

**Comment by OmerBenGera** [comment]
> 
> 
> Yes it does

I understand.
I uploaded a new version, please install it. Then, run the following commands:
`/is admin debug Action: Chunk Calculation`
`/is admin recalc <player-name>`
It should print to console all the chunks that are being calculated. Make sure all of the island chunks are there (the ones that have blocks at least)

**Comment by ThinkRusty87** [comment]
11.09 01:51:10 [Server] INFO ThinkRusty87 issued server command: /is admin debug Action: Chunk Calculation
11.09 01:51:14 [Server] INFO ThinkRusty87 issued server command: /is admin recalc ThinkRusty87
11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 37, 36
11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 37, 37
11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 37, 38
11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 38, 36
11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 38, 37
11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 38, 38

**Comment by OmerBenGera** [comment]
> 
> 
> 11.09 01:51:10 [Server] INFO ThinkRusty87 issued server command: /is admin debug Action: Chunk Calculation
> 11.09 01:51:14 [Server] INFO ThinkRusty87 issued server command: /is admin recalc ThinkRusty87
> 11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 37, 36
> 11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 37, 37
> 11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 37, 38
> 11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 38, 36
> 11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 38, 37
> 11.09 01:51:14 [Server] INFO [DEBUG] Action: Chunk Calculation, Island: ThinkRusty87, Chunk: islands, 38, 38
> 
> ![Screenshot 2021-09-09 183912](https://user-images.githubusercontent.com/90370562/132776205-0096c855-66fb-404d-adcb-456bf31dcc96.png)
> ![Screenshot 2021-09-09 191829](https://user-images.githubusercontent.com/90370562/132778909-c2027369-0292-4efd-9271-315f0a48cd04.png)

So it seems like the correct chunks are calculated, however the plugin doesn't calculate worth correctly.
If you run /is counts, does it show the correct blocks there or not?
(Again, only blocks that have worth value are calculated, not all blocks in the world)

**Comment by ThinkRusty87** [comment]
Yes, when you do /is counts it shows properly and the correct blocks.

**Comment by FaZeRasputin** [comment]
I'm having the same problem

**Comment by FaZeRasputin** [comment]
https://gyazo.com/c0f5be1b823f42e0532a88ce228ae5e4?token=ef24a5d0ea95425af74ceae2fb0875b1

https://gyazo.com/47c11e24a3d640bb4bafeadb80037bab

**Comment by ThinkRusty87** [comment]
All of the worth values are from the worth.yml file.

One solution would be to update the worth.yml types so more blocks are registered.  Especially 1.1.7 and 1.17.1 blocks.

Another good idea is to make it so every member starts at 0 island worth and level regardless of blocks on the schematic.

Then make it to were blocks are not subtracted when they are deleted off the schematic, only if a block is placed and then deleted.

**Comment by ThinkRusty87** [comment]
Updated

**Comment by ThinkRusty87** [comment]
Updated

**Comment by FaZeRasputin** [comment]
updated???

**Comment by OmerBenGera** [comment]
> I'm having the same problem

Answer my last question please (check it above)
The OP seems to not respond and therefore I havent looked at it yet

**Comment by ThinkRusty87** [comment]
All of the worth values are from the worth.yml file.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if there's any difference.

**Comment by ThinkRusty87** [comment]
No change.

**Comment by OmerBenGera** [comment]
> No difference.
> 
> One solution would be to update the worth.yml types so more blocks are registered. Especially all of the 1.17 and 1.17.1 blocks.

You know that the plugin only counts blocks that have a worth value, right?

**Comment by ThinkRusty87** [comment]
One solution would be to update the worth.yml file and add all of the block types especially on version 1.17 and 1.17.1 so more blocks are registered.

**Comment by OmerBenGera** [comment]
> 
> 
> One solution would be to update the worth.yml file and add all of the block types especially for version 1.17 and 1.17.1 so more blocks are registered.

I don't understand what you want
The plugin only counts blocks that have a worth value, island level or a block limit. Otherwise, it will not count them in /is counts

**Comment by OmerBenGera** [comment]
there's no bug then?
