### ISSUE TITLE
Island worth Issue

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#590]
### Minecraft's Version

1.8.8

### Plugin's Version

Build #296

### Describe the bug

So i set the worth of the blocks and i also tried it without setting worths of the blocks and when placing one on the island such as the spawner in the gif the is top shows the wrong worth for it and it should be 4 million for that example and it's not. I also did /is recalc, /is admin recalc and restarted the server and tried to place and replace and do the same commands but it still remained the same.

### To Reproduce

i could send you my configs again if you'd like

### Additional Information

https://gyazo.com/d2e70ab67b0429d1c78e11eaff59c876

**Comment by OmerBenGera** [comment]
Hold the spawner in your hand and run /is value
Does it show 4M as the worth value?

**Comment by DebuffPvP** [comment]
for some reason i just got this error and won't let me launch the server https://pastebin.com/dbJGg4pm

**Comment by DebuffPvP** [comment]
Hey you can close this ticket i believe it happens randomly so idrc

**Comment by DebuffPvP** [comment]
Apparently though spawners are not shown in the island worth unless the spawners are added in the worths file in block values that's another issue

**Comment by OmerBenGera** [comment]
> 
> 
> Apparently though spawners are not shown in the island worth unless the spawners are added in the worths file in block values that's another issue

That's intended....
Why would the plugin count spawners that don't have any limits, block value or levels?
There's no point in that.

**Comment by DebuffPvP** [comment]
well i have no blocks in the worths file and their values show and are in shopguiplus and spawners are in shopguiplus too so why wouldn't they show?

**Comment by OmerBenGera** [comment]
> 
> 
> well i have no blocks in the worths file and their values show and are in shopguiplus and spawners are in shopguiplus too so why wouldn't they show?

Do they have a worth value?
If you run /is value while holding a spawner, do they have a value?

**Comment by FaZeRasputin** [comment]
The same issue with /is level

**Comment by DebuffPvP** [comment]
IS level work for me faze it's not happening on there you must add them like this in the levels.yml
######################################################
##                                                  ##
##                SuperiorSkyblock 2                ##
##                Developed by Ome_R                ##
##                                                  ##
######################################################

# Here you can set all the level values for your blocks.
# To set specific spawner types, use 'MOB_SPAWNER:<ENTITY>': <AMOUNT>
# If no level is found, the formula from config will be used.

'MOB_SPAWNER:PIG': 10
'MOB_SPAWNER:COW': 20
'MOB_SPAWNER:SKELETON': 30
'MOB_SPAWNER:ENDERMAN': 40
'MOB_SPAWNER:BLAZE': 50
'MOB_SPAWNER:CREEPER': 80
'MOB_SPAWNER:IRON_GOLEM': 100

**Comment by FaZeRasputin** [comment]
I have things in my level.yml

**Comment by DebuffPvP** [comment]
what version u on

**Comment by FaZeRasputin** [comment]
I have the new stable version and I’m also using blocks not spawners

**Comment by DebuffPvP** [comment]
Omre https://gyazo.com/d9a82ab473246699b2f5a83325e401da this explains all of it and i have nothing in worths.yml but it should be able to grab prices from shopguiplus and it's not

**Comment by FaZeRasputin** [comment]
Like diamond Blocks and emerald

**Comment by DebuffPvP** [comment]
oh so they're not working

**Comment by FaZeRasputin** [comment]
No

**Comment by FaZeRasputin** [comment]
I put all of it in and it shows up just fine I run /is level or /is recalc it goes to 0 and I can’t add anything

**Comment by DebuffPvP** [comment]
you got discord?

**Comment by FaZeRasputin** [comment]
yes

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if there's any difference.

**Comment by DebuffPvP** [comment]
same thing look https://gyazo.com/2caef3fc83a8163a4b11d8ce6785a378

**Comment by OmerBenGera** [comment]
> same thing look https://gyazo.com/2caef3fc83a8163a4b11d8ce6785a378

The plugin detects this spawner as a Pig Spawner, not an Iron Golem Spawner. What spawners plugin are you using?

**Comment by DebuffPvP** [comment]
i am using silkspawners the latest version from here and what i was holding is an iron golem the same one from shop https://www.spigotmc.org/resources/silkspawners-★-ready-to-rock-1-8-1-17-supported-★.7811/

**Comment by OmerBenGera** [comment]
> i am using silkspawners the latest version from here and what i was holding is an iron golem the same one from shop [https://www.spigotmc.org/resources/silkspawners-★-ready-to-rock-1-8-1-17-supported-★.7811/](https://www.spigotmc.org/resources/silkspawners-%E2%98%85-ready-to-rock-1-8-1-17-supported-%E2%98%85.7811/)

I dont think its supported

**Comment by DebuffPvP** [comment]
what in your plugin or must i contact the owner of silkspawners? cause silkspawners is what 99% of servers use

**Comment by OmerBenGera** [comment]
> what in your plugin or must i contact the owner of silkspawners? cause silkspawners is what 99% of servers use

This is a replica of the original SilkSpawners plugin.
If it wasnt added until now, probably not many use it.
Contact the developer
