### ISSUE TITLE
Breaking dragon eggs isn't tracked correctly

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#592]
### Minecraft's Version

1.8.8

### Plugin's Version

build #296

### Describe the bug

the same issue that was happening before is happening again when the server restarts the value and level remain but appears to happen with dragon egg only

### To Reproduce

Set the buy price of dragon egg to 12,000,000 in shopguiplus and set the block level to 500 in levels.yml in block values. create an island place the egg do /is top, break the egg do /is top and stop the server and restart and do /is top

**Comment by OmerBenGera** [comment]
Mind explaining what the issue is...?

**Comment by DebuffPvP** [comment]
so when i place the dragon egg it adds the value when i remove it and restart the server the value remains there

**Comment by OmerBenGera** [comment]
> 
> 
> so when i place the dragon egg it adds the value when i remove it, it remains there and restart the server the value still remains there

So the issue seems like removing dragon eggs is not tracked correctly.
You break it using a torch or something like that, right?

**Comment by DebuffPvP** [comment]
dragon eggs teleport when clicked but i made it so it's breakable using iron diamond and gold pickace or drops from explosions wether it's from throwable creeper egg, creeper egg and tnt

**Comment by DebuffPvP** [comment]
and yes to your answer

**Comment by OmerBenGera** [comment]
> dragon eggs teleport when clicked but i made it so it's breakable using iron diamond and gold pickace or drops from explosions wether it's from throwable creeper egg, creeper egg and tnt

So you probably dont let SSB know about it, as ypu cancel the interact event and break the block manually without calling BlockBreakEvent or using the Island#handleBlockBreak method.

If the issue is due to that, then youll have to add support, as it has nothing to do with the plugin itself.

**Comment by DebuffPvP** [comment]
so basically without my plugin i can break dragon eggs by shift clicking and breaking it in creative mode and the plugin does remove it from the value but when im using my plugin value remains there so i don't really know how to add support but as far as if i get a developer to do it could you tell me what i should say to him?

**Comment by OmerBenGera** [comment]
> so basically without my plugin i can break dragon eggs by shift clicking and breaking it in creative mode and the plugin does remove it from the value but when im using my plugin value remains there so i don't really know how to add support but as far as if i get a developer to do it could you tell me what i should say to him?

You need to get the Island object at the location of the block, and then use Island#handleBlockBreak when you break the block. Use the API of the plugin for that.
