### ISSUE TITLE
Some bugs and delays

### ISSUE THREAD

**Issue by tncc2k** [BG-Software-LLC/SuperiorSkyblock2#593]
### Minecraft's Version

Spigot 1.12.2

### Plugin's Version

SuperiorSkyblock2-b296  (#296 07/09/2021 11:56:39)
SuperiorSkyblock2-1.7.0  (1.7.0 19/06/2021 12:55:14)

### Describe the bug

* SuperiorSkyblock2-1.7.0  (1.7.0 19/06/2021 12:55:14)
/is level
When using the command above level + worth reverts back to 0

* SuperiorSkyblock2-b296  (#296 07/09/2021 11:56:39)
Delay when sending money to island bank
Version "SuperiorSkyblock2-1.7.0" deposit money and hovering the menu immediately shows the amount
And the "SuperiorSkyblock2-b296" version must esc and reopen the menu to show the amount.
One more thing I don't know if it's my fault
When I use / as admin reload
then I use / is team
console spam error, island hangs
Also other commands work normally
In version "SuperiorSkyblock2-1.7.0" I don't see this happening

### To Reproduce

.

### Additional Information

https://hastebin.com/aresitejot.sql

**Comment by OmerBenGera** [comment]
Why are you putting like 100 bugs in a single report?
Open separate issues for each reported bug.

**Comment by OmerBenGera** [comment]
I fixed the /is team error you had.
For the rest of the errors, please provide more details on separate issues.
I am closing this one
