### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#594]
### Minecraft's Version

1.8.8 - Paperspigot

### Plugin's Version

Superiorskyblock2-b296

### Describe the bug

Hey, I'm having a saving issue with latest dev build of superiorskyblock, it doesn't save anything

with SuperiorSkyblock2-b276 works fine
but with latest is giving that error above

### To Reproduce

Just stopping the server

### Additional Information

https://pastebin.com/Npk3Umuq

**Comment by OmerBenGera** [comment]
There seems to be an issue unrelated to the plugin.
It tries to save data into the database, but there's an I/O error (no permissions, not enough storage space, etc), causing it to not work.
Find what can cause it, fix it and everything will work again.
If you struggle with it, I recommend switching to MySQL in that case so issues with I/O cannot occur.

I will also try to google it, maybe I can somehow fix it on my end, but I can't promise anything.
Therefore, I am keeping this opened until we find what can cause it.

**Comment by OmerBenGera** [comment]
I read about it on google and found that it's probably due to a permissions issue with the files.
Try giving to SSB's folder the delete permission for all users, let me know if it works.

**Comment by OmerBenGera** [comment]
I am closing this for now.
If the issue continues, let me know
