### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/SuperiorSkyblock2#595]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b296

### Describe the bug

Since this morning, when I load my server, I get an error related to database conversion (and server stops).
But the database conversion was already done a week ago.

The error :
https://pastebin.com/D6d0VaVJ

### To Reproduce

No idea

### Additional Information

using MySQL

**Comment by OmerBenGera** [comment]
The plugin sees that you have a table called "stackedBlocks", and therefore it indicates about the old database.
However, it seems like columns of tables are from the new database, and it causes this error.

Fix it manually renaming the "stackedBlocks" table to something else, or by deleting the new tables from the new database and make the plugin to re-convert the old ones.
