### ISSUE TITLE
PvP not working with pvp setting on

### ISSUE THREAD

**Issue by ElFlyGod** [BG-Software-LLC/SuperiorSkyblock2#599]
### Minecraft's Version

1.17.1 Airplane

### Plugin's Version

b296

### Describe the bug

Enabling pvp island setting doesnt work, people are still unable to pvp

i used event debugger to see whats cancelling the pvp and it was superiorskyblock

the setting itself is enabling properly and it says pvp in island turned on and teleports people away.

### To Reproduce

Enable pvp setting and try hitting another player on the island, no damage.

**Comment by ElFlyGod** [comment]
Same issue on b302, also switching to mysql didnt fix this issue

**Comment by OmerBenGera** [comment]
> 
> 
> Target is a visitor but it also doesnt work if the person is a member of the island, where can i check if the damage is disabled?

Island members cannot hit each other unless they are in a "pvp world".
You can enable/disable visitors-damage in the config.

**Comment by ElFlyGod** [comment]
setting **visitors-damage: true** solved the issue

**Comment by OmerBenGera** [comment]
Do you think visitors should take pvp-damage even when taking damage is disabled for them?

**Comment by ElFlyGod** [comment]
Well even island members couldnt fight eachother until the visitor damage was enabled, yeah i think with the pvp setting on for islands visitors should be able to fight

**Comment by OmerBenGera** [comment]
> 
> 
> Well even island members couldnt fight eachother until the visitor damage was enabled, yeah i think with the pvp setting on for islands visitors should be able to fight

island-members cannot hurt each other if they are not in a world that is considered as a "pvp-world". This has nothing to do with visitors damage.
Anyways, I'll look into changing it, as it doesn't make sense to have pvp enabled but visitors cannot pvp.
