### ISSUE TITLE
/is admin teleport <player> not working with JUST the permission node superior.admin.teleport!

### ISSUE THREAD

**Issue by ClickErrorxD** [BG-Software-LLC/SuperiorSkyblock2#600]
### Minecraft's Version

Minecraft Version: 1.16.5
Software Version: Paper1.16.5.jar

### Plugin's Version

SuperiorSkyblock2-b239.jar

### Describe the bug

Basically, I gave the Moderator group of my server the "superior.admin.teleport" permission node. But when a mod tries to run /is admin teleport <username>, it tells the user the MISSING PERMISSION MESSAGE that's in the lang file of the plugin.

`NO_COMMAND_PERMISSION: '&6&lISLAND &eUnknown command. Please try &6/help&e or &6/rules&e.'`

### To Reproduce

Basically just give yourself the above node, and run the command that's listed in the above section.

### Additional Information

I've tried multiple permissions, non seem to work. What I am trying to do is allow moderators to use EssentialsX `/tp` command, but due to players having CLOSED or LOCKED islands, it sends the staff member to spawn.

![image](https://user-images.githubusercontent.com/87890013/132965841-17168e5f-be66-41d2-9e43-83bd6d339891.png)
I am using this permission node too, said by Ome_r back in 2020, and it just isn't working.

**Comment by OmerBenGera** [comment]
You must give them `superior.admin` as well.
