### ISSUE TITLE
The generator is coming too cobblestone

### ISSUE THREAD

**Issue by YuiDG** [BG-Software-LLC/SuperiorSkyblock2#602]
### Minecraft's Version

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.7.0-DEVb302

### Describe the bug

I noticed that a lot of cobblestones came from the generators, so I decided to put a netherrack (to break faster) with 100% chance and even more cobblestones came than the netherrack

![image](https://user-images.githubusercontent.com/73173641/132998246-0e131a90-ba8d-47e4-9245-af1dd3b85165.png)

I also took a look at **SuperiorSkyBlock2\config.yml** and set netherrack to 100%

![image](https://user-images.githubusercontent.com/73173641/132998299-6f83f4a1-3280-40c7-86e1-2a09a5d7cdf0.png)

### To Reproduce

1. Put some block with a 100% chance of coming to the ores generator in the upgrade settings
2. Then make a minerals generator and check that you are on the same upgrade as the generator that is in the upgrade settings
3. then break the ore generator blocks

Remembering that it is in 1.12.2

### Additional Information

NOTE: I tested a lot on my server using MY SETTINGS, and I used it using the plugin's original settings, just modified the chances of blocks coming in the generator and nothing else. and it's the same as in the video.

https://user-images.githubusercontent.com/73173641/132998492-cebee71b-3e10-409b-9397-fcbe86e6d643.mp4

**Comment by OmerBenGera** [comment]
Check your generator rates using `/is admin show` and make sure your rates dont contain cobblestone.

**Comment by YuiDG** [comment]
![image](https://user-images.githubusercontent.com/73173641/133294044-77599908-b2ae-47e2-9f5d-8cfab0ab7ae5.png)

**Comment by OmerBenGera** [comment]
Do you have your generators-module enabled?
You can check it by going to the generators config under the generators folder inside the modules folder.

**Comment by YuiDG** [comment]
![image](https://user-images.githubusercontent.com/73173641/133343509-1a0c27cf-6920-420e-9efb-fec7d31c92cc.png)

**Comment by OmerBenGera** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/73173641/133343509-1a0c27cf-6920-420e-9efb-fec7d31c92cc.png)

Seems like the generators module works.
Therefore, I believe one of the following reasons causing it to not work:
1) You have another plugin overriding generators somehow, causing SSB's ones to not work.
2) You have BlockFromToEvent disabled on your server, making the plugin to not be able to override the generators.

Are you able to test it on another server with only SSB installed?
If you can, please try it and report if it works or not.

**Comment by YuiDG** [comment]
I tested it only with the SSB and the generator still didn't work

https://user-images.githubusercontent.com/73173641/133509251-d1851aa0-b101-43db-84e2-e1765e3f6dc1.mp4

**Comment by YuiDG** [comment]
I just tested it on 1.16.5 on the same server with the same settings and the generator is fine
![image](https://user-images.githubusercontent.com/73173641/133510174-e70a7443-b97b-477c-a695-299036086bbb.png)

**Comment by OmerBenGera** [comment]
I will look into that, might be an issue with 1.12

**Comment by YuiDG** [comment]
ok

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
