### ISSUE TITLE
Border Size Upgrades

### ISSUE THREAD

**Issue by octavetoast** [BG-Software-LLC/SuperiorSkyblock2#604]
### Minecraft's Version

Paper on 1.17.1

### Plugin's Version

Dev-297

### Describe the bug

Island border size upgrades sometimes aren't applied, and require a moderator/admin to manually upgrade them with `/is admin setupgrade <player> border-size <level>`. Island border size can also sometimes be reset between reloads/restarts.

### To Reproduce

Upgrade the border size of your island using the GUI.

**Comment by OmerBenGera** [comment]
All upgrades are handled by commands, so I believe the islands have the upgrade, but the border itself isnt applied until you set the upgrade again.
Is this the case? You can check it using `/is admin show` and check that the upgrade is at the right level, but the border size is different.

**Comment by octavetoast** [comment]
Yeah, I can see they’re applied via the aame commands (a lot more
customizable, props), so that’s why I’m confused. I’ll now check to see if
the border size matches the upgrade.

**Comment by octavetoast** [comment]
Just tested, `/is admin show` reports the border upgrade at level 2, but the border doesn't expand. However, if you set it back to level 1 by using the command in-game (`/is admin setupgrade <player> border-size 1`), it will successfully increase the border size.

**Comment by Oskaris25** [comment]
@octavetoast try  /is admin syncupgrades *

**Comment by octavetoast** [comment]
Thanks, I’ll just make it run that command when they upgrade.

**Comment by OmerBenGera** [comment]
> Thanks, I’ll just make it run that command when they upgrade.

No, dont do that.

**Comment by octavetoast** [comment]
What should I do then?

**Comment by OmerBenGera** [comment]
> What should I do then?

Wait for me to fix the issue...

**Comment by octavetoast** [comment]
Well obviously, but why is it a bad idea to temporarily do that?

**Comment by OmerBenGera** [comment]
> 
> Well obviously, but why is it a bad idea to temporarily do that?

Because it shouldn't be ran that frequent, not to mention that you force many unnecessary calculations.
It's fine to run it once, but not everytime someone upgrades their border-size.

**Comment by octavetoast** [comment]
Good reason, thanks.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
If it doesn't work, run `/is admin syncupgrades *` and try it again.
It will be fixed for all new islands, however old ones might need the command above to be called.

**Comment by octavetoast** [comment]
Awesome, thanks!

**Comment by OmerBenGera** [comment]
No problem, make sure you report back if it works for you or not :)

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by octavetoast** [comment]
Nope, everything is working fine!
