### ISSUE TITLE
UltimateStacker causing Issues when calculating Island Level

### ISSUE THREAD

**Issue by MLGPenguin** [BG-Software-LLC/SuperiorSkyblock2#606]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

Dev build 302

### Describe the bug

When I type /is level on someone else's island (I.e. my island isn't loaded) it throws an error in the console and says "an unexpected error occurred while calculating your island".

this only happens if I have stacked spawners on my island (I have not set up a value for these spawners in the block-values)

### To Reproduce

Using UltimateStacker, Place a spawnerstack (of more than 1 spawner) on your island and then leave the island (unload the chunks). then type /is level.

### Additional Information

I am using the latest version of ultimate stacker (2.1.7)

The Console Error: https://hastebin.com/ilizefixad.yaml

**Comment by OmerBenGera** [comment]
Seems like UltimateStacker changed their API
I will look into fixing it :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
