### ISSUE TITLE
Island Top value sets to 0

### ISSUE THREAD

**Issue by Aarpn** [BG-Software-LLC/SuperiorSkyblock2#607]
### Minecraft's Version

1.8.8

### Plugin's Version

latest stable 1.7.0 and latest dev build tested but have same issue

### Describe the bug

Basically, when recalculating value, it puts the value to 0 and for it to calculate properly, you have to replace all blocks

### To Reproduce

just place value then do /is recalculate

### Additional Information

not really anything needed for this

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue on latest dev build (Build 307) on Paper 1.8.8

**Comment by OmerBenGera** [comment]
Any news regarding this?
