### ISSUE TITLE
Islands Corrupting (sometimes)

### ISSUE THREAD

**Issue by Aarpn** [BG-Software-LLC/SuperiorSkyblock2#611]
### Minecraft's Version

1.8.8

### Plugin's Version

latest dev B310

### Describe the bug

sometimes when restarting server and then you join all places etc and scoreboard break, i know its ss2 as i try /is and its like the command doesnt work as nothing is said in chat etc, but also you cant even do /is reset or anything

### To Reproduce

I guess just hope for best for it to work

### Additional Information

https://pastebin.com/SxsiJK6W - this is the startup log I get for ss2

**Comment by OmerBenGera** [comment]
Reset your border-color menu, I think it's corrupted.
Let me know if it works after that.

**Comment by Aarpn** [comment]
islands get created now, ill keep you updated if islands corrupt again

**Comment by OmerBenGera** [comment]
I am closing this for now
If it happens again, open a new issue with more details about the issue.
