### ISSUE TITLE
[Bug Report] Unable to convert database

### ISSUE THREAD

**Issue by D3adhkwen** [BG-Software-LLC/SuperiorSkyblock2#613]
### Minecraft's Version

Airplane version git-Airplane-"ec7d3d0" (MC: 1.17.1)

### Plugin's Version

SuperiorSkyblock2 1.8-DEV-b315

### Describe the bug

Error shows when launching the server with new version for the first time.
https://paste.gg/p/anonymous/a7a1517731ee4ad6b3fe5a911aed4745

New database will only be ~1mb on 2nd server start, backup database is ~10mb.

### To Reproduce

1. Put in version of SuperiorSkyblock2
2. Launch server

**Comment by OmerBenGera** [comment]
I fixed it in latest dev build, please update.
After you install the new version, delete the new database that was generated and rename the backup to "database.db", so the migration of data will happen again.
