### ISSUE TITLE
Island Protected issue

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#614]
### Minecraft's Version

1.8.8

### Plugin's Version

Build #315

### Describe the bug

When i opened up my server today and updated the jar prior it now says island is protected and won't let me place blocks even though the server spawn is in a non superiorskyblock world and someone on spigot apparently has the same issue https://gyazo.com/9c86be4f21e95b1633a7534edfec0398

### To Reproduce

my files i guess is all i can say to give you so idk what else.

**Comment by OmerBenGera** [comment]
You can disable spawn-protection in your config if you wish.

**Comment by DebuffPvP** [comment]
There is no option for that in the config.yml
