### ISSUE TITLE
Bug with parsing of placeholders

### ISSUE THREAD

**Issue by Gayytis** [BG-Software-LLC/SuperiorSkyblock2#615]
### Minecraft's Version

1.17.1,Paper #266

### Plugin's Version

1.8.b316

### Describe the bug

When using some placeholders (i don't know all of them but this one is "%superior_island_level%"), if the 1000 mark is exceeded it will show a square with NNBSP written inside it.

Will it be corrected ? Because it is a bit of a hassle for me.

![image](https://user-images.githubusercontent.com/65625456/134233955-6f74319c-aace-4a56-865c-42bea1776ffb.png)

### To Reproduce

Just using some placeholders with no formating.

**Comment by OmerBenGera** [comment]
You can change your numbers-format in your config so it will not show this unicode character.
Its not something to be fixed in the plugin.
