### ISSUE TITLE
Error converting islands

### ISSUE THREAD

**Issue by TheMartyCZ** [BG-Software-LLC/SuperiorSkyblock2#616]
### Minecraft's Version

Ssspigot 1.16.5

### Plugin's Version

stable 1.8

### Describe the bug

https://pastebin.com/iXX8J9Mu

### To Reproduce

start server withc 1.8 version on 1.16.5 ssspigot

**Comment by OmerBenGera** [comment]
This issue is fixed on latest dev build.
