### ISSUE TITLE
Spawner multiplier is not applied to all island dimensions.

### ISSUE THREAD

**Issue by octavetoast** [BG-Software-LLC/SuperiorSkyblock2#618]
### Minecraft's Version

Paper 1.17.1

### Plugin's Version

1.8 Stable

### Describe the bug

The spawner multiplier upgrade only applies to spawners in the Overworld, not in the Nether or The End. Currently using **WildStacker** as my spawner provider.

### To Reproduce

Make a new island and upgrade the spawner multiplier. Place a spawner in a Nether or End island, it will only yield a normal quantity of mobs.

**Comment by OmerBenGera** [comment]
It seems fine from the first look of the code.
Also, you know the spawners-rates multiplier only reduces the delay, not making more entities to spawn, right?

**Comment by octavetoast** [comment]
Oops, I misunderstood then. Thanks.

**Comment by OmerBenGera** [comment]
you welcome :)
