### ISSUE TITLE
Missions do not reset

### ISSUE THREAD

**Issue by Neeekss** [BG-Software-LLC/SuperiorSkyblock2#621]
### Minecraft's Version

Paper version git-Paper-278 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: d0a2193)

### Plugin's Version

SuperiorSkyblock2-b199

### Describe the bug

When I complete missions I can get rewards everytime I press on it until I reload the server and it gets fixed.

### To Reproduce

Check mission config

### Additional Information

[config (2).zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7227586/config.2.zip)

**Comment by OmerBenGera** [comment]
Upload your missions file to pastebin please.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Neeekss** [comment]
Yes, I fix it by uploading new SuperiorSkyblock2 files.
