### ISSUE TITLE
blocked-visitors-commands apply for coops

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#626]
### Minecraft's Version

1.16.5

### Plugin's Version

318

### Describe the bug

> # A list of commands that cannot be executed by visitors.
> blocked-visitors-commands:
> - /sethome
> - sethome

To work for **coop** player ?
I want coop player able to /sethome, but not visitors

### To Reproduce

Set 
> # A list of commands that cannot be executed by visitors.
> blocked-visitors-commands:
> - /sethome
> - sethome

Try as a coop, you won't be able to do it

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
