### ISSUE TITLE
/is leave command

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SuperiorSkyblock2#628]
### Minecraft's Version

This server is running Purpur version git-Purpur-1382 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6115484 on ver/1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.8

### Describe the bug

as a member of island only, when i do /is leave. it says "You cannot leave your island when you own it or You can transfer the ownership using /is transfer" I'm not even the owner of the island (Only Member)

### To Reproduce

Be a member of a player island and do /is leave

### Additional Information

![unknown](https://user-images.githubusercontent.com/69298936/134920220-475a2058-78e0-44e3-8444-a5d815b0645e.png)
![ddd](https://user-images.githubusercontent.com/69298936/134920318-1efab5d3-0132-4545-9954-8ab6e39e26cf.png)

**Comment by OmerBenGera** [comment]
Show me the results of `/is admin show`

**Comment by OmerBenGera** [comment]
Wait, I've just noticed you opened #629 - this is all related to that.
Closing this.
