### ISSUE TITLE
Waxed Copper Blocks unable to be stacked

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#630]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev 260

### Describe the bug

Even with permissions and config set up properly, you are unable to stack copper blocks (if you have admin perms, it still works like intended)

### To Reproduce

Set up the config & the permission node superior.island.stacker.waxed_copper_block so you can stack copper blocks, and try to stack them. Make sure you dont have any other admin permissions that bypasses the perm node

### Additional Information

perms set up correctly - https://screenshots.skizzles.me/wAnA3/qEzoVibI77.png
config set up properly - https://screenshots.skizzles.me/wAnA3/pEpOtakO84.png

clip of it happening - https://youtu.be/X-8DfgdZ1IQ

**Comment by OmerBenGera** [comment]
It works fine for me.

**Comment by marvjosh1** [comment]
Do you have any idea why it is not working then? I cannot see any mistake in setting up the stacked block for the set rank, it is the same one as in the clip. With admin permissions the block was able to be stacked, however not with a "normal player" who should have the permission aswell

**Comment by OmerBenGera** [comment]
> 
> 
> Do you have any idea why it is not working then? I cannot see any mistake in setting up the stacked block for the set rank, it is the same one as in the clip. With admin permissions the block was able to be stacked, however not with a "normal player" who should have the permission aswell

probably due to a permission issue.
Try debugging it and find what causes that.

**Comment by OmerBenGera** [comment]
Any news regarding this?
