### ISSUE TITLE
Able to bypass /island fly

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#631]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev 260

### Describe the bug

When tping to another player on another island with /island fly on, it will not be toggled off. This means you will be able to fly on other islans where you should not have permissions to. This will also work with /back etc.

### To Reproduce

1. Go to your island, and turn on /island fly
2. Teleport to a player on another island
3. Island fly will still be toggled on

### Additional Information

https://youtu.be/h_9yO2-jJSc

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by marvjosh1** [comment]
Seems to be working, thanks!
