### ISSUE TITLE
Stacked blocks hologram glitching

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#632]
### Minecraft's Version

1.17.1 purpur dev 1385

### Plugin's Version

dev 260

### Describe the bug

When quickly stacking blocks, sometimes a glitching hologram will be created where there isnt even a stacked block present but only air. 

### To Reproduce

1. Place down a block which is stackable
2. Quickly try to place blocks on it 
3. Glitched holograms over air will be created

### Additional Information

https://www.youtube.com/watch?v=cUtupfwiYn4

**Comment by OmerBenGera** [comment]
This is not a normal vanilla behavior, therefore it's not supported and not gonna be fixed.

**Comment by Skizzles** [comment]
https://screenshots.skizzles.me/wAnA3/TiLiTiQi32.mp4

reproduced without any autoclickers

**Comment by OmerBenGera** [comment]
I'll look into that.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
