### ISSUE TITLE
default-world

### ISSUE THREAD

**Issue by tncc2k** [BG-Software-LLC/SuperiorSkyblock2#634]
### Minecraft's Version

spigot 1.12.2

### Plugin's Version

SuperiorSkyblock2-1.8-b321

### Describe the bug

Error pre-generating world
(config.yml)
default-world: the_end
default-world: nether

### To Reproduce

I simply want the default when creating an island to be in nether or the_end
that works on version: SuperiorSkyblock2-1.7.0
but recent versions can't do that

### Additional Information

config: https://hastebin.com/esohonukal.yaml
Error: https://hastebin.com/kazagiloqu.css

Note: it works on version : SuperiorSkyblock2-1.7.0
Recent versions can't
If you don't want
default-world: nether
default-world: the_end
then delete it in the next update
If yes, can you fix it?

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
