### ISSUE TITLE
DISBAND ERROR

### ISSUE THREAD

**Issue by ConnorServers** [BG-Software-LLC/SuperiorSkyblock2#637]
### Minecraft's Version

1.8.9

### Plugin's Version

LATEST

### Describe the bug

When i disband my Island https://pastebin.com/1tuFvbCu

### To Reproduce

Disband confirming.

**Comment by OmerBenGera** [comment]
I'll need a copy of the jar so I can add support for it.
Seems like one of the NMS fields have a different name and therefore it breaks.

**Comment by ConnorServers** [comment]
Hi.
Here's a copy of the jar.
https://www.dropbox.com/s/koqpmn2p27p634u/SuperiorSkyblock2-1.8.jar?dl=0

**Comment by OmerBenGera** [comment]
> 
> 
> Hi. Here's a copy of the jar. https://www.dropbox.com/s/koqpmn2p27p634u/SuperiorSkyblock2-1.8.jar?dl=0

I need a copy of your spigot jar, not a copy of the plugin.
You're using a paid one if I am not wrong, therefore I can open a ticket for you so you can send it over privately.

**Comment by ConnorServers** [comment]
Hi, sorry about that.
https://www.dropbox.com/s/5vn69zcy1yo2rpd/server.zip?dl=0

Here's the jar!
Thank you.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by ConnorServers** [comment]
Uhm.
I used the dev build and it somehow fucked my whole release.
When a player created an island it wouldn't register. They'd be able to create another and another
and it'd still say they're not in an island.
17H later i switched to the official release jar and it was fixed. But of course with the disband error.

**Comment by OmerBenGera** [comment]
> Uhm. I used the dev build and it somehow fucked my whole release. When a player created an island it wouldn't register. They'd be able to create another and another and it'd still say they're not in an island. 17H later i switched to the official release jar and it was fixed. But of course with the disband error.

Weird. Were there any errors when creating the island?

**Comment by ConnorServers** [comment]
Error on /is go https://pastebin.com/wL2P2gLP
There was 50,000 lines of this https://pastebin.com/9xK2PcjN

**Comment by ConnorServers** [comment]
Also there's an issue with:
1. When a player places a Monthly Crate (Enderchest) it just places the enderchest on their island and doesn't activate.
- I'm using advancedmonthlycrates. Any idea on a workaround?

2. For some reason value-blocks (Sponges) aren't stacking.
- Any idea on how i can fix this?
