### ISSUE TITLE
Percentage of ores in generator upgrade

### ISSUE THREAD

**Issue by JLucassz** [BG-Software-LLC/SuperiorSkyblock2#642]
### Minecraft's Version

Minecraft 1.17.1
Paper

### Plugin's Version

SuperiorSkyblock2-1.8-b328.jar

### Describe the bug

Decimal numbers in config.yml in 'generator-rates' upgrade is not working. Ores only appear with integer values.

### To Reproduce

If you enter decimal values, the ores will not appear.

### Additional Information

![image](https://user-images.githubusercontent.com/76066285/135731559-cc3519db-e4c3-46d6-a4f8-783c5dfdb426.png)

**Comment by OmerBenGera** [comment]
You cant use decimals. The amount you set is not percentage, and its calculated as the value you set devided by the total amount of values for the ores.
So lets say you have two ores, one with 1 and the other with 3, the first ore will be 25% (1 / (1+3)).
