### ISSUE TITLE
island creation function is strange

### ISSUE THREAD

**Issue by bl9ckSapphire** [BG-Software-LLC/SuperiorSkyblock2#644]
### Minecraft's Version

minecraft version: 1.16.5

(bukkit = purpur)

### Plugin's Version

SuperiorSkyblock2-1.8-b328.jar

### Describe the bug

I created an island using the "/is create" command, but my island is not retained and can be created indefinitely.
I updated from "SuperiorSkyblock2-b296" to "SuperiorSkyblock2-1.8-b328" today,
In the b296 version, the "/is create , /island" function, which worked well, does not work.

### To Reproduce

1.) First, if you have an island, use the "/is admin disband" command to remove the island you own.

2.) Create an island with the "/is create" command

3.) When you enter the "/island" command or island-related commands "/is chest, level, sethome, etc...", you are notified that you do not have an island.

### Additional Information

https://youtu.be/TnTZ8H4lAX8

**Comment by OmerBenGera** [comment]
Send me your logs file please

**Comment by feinstein69** [comment]
im facing this issue too. 
When a new player creates an island
He is tp'ed to the new island
And if he does any island related commands it says he doesnt have an island
If he does /is , the island creation menu appears and they can create islands again and again.


It was working fine on version 322. All other version from that one till 328 is broken and have the same issue.

**Comment by bl9ckSapphire** [comment]
> Send me your logs file please

**Comment by OmerBenGera** [comment]
Its a known issue, downgrade for now.
