### ISSUE TITLE
Errors when getting spawner-types of AdvancedSpawners

### ISSUE THREAD

**Issue by Superbility** [BG-Software-LLC/SuperiorSkyblock2#650]
### Minecraft's Version

1.8

### Plugin's Version

1.8

### Describe the bug

Big errors in console when breaking and placing -  https://pastebin.com/EvFkLu8K

### To Reproduce

Break / place blocks

**Comment by OmerBenGera** [comment]
What version of AdcancedSpawners are you using?

**Comment by OmerBenGera** [comment]
GC fixed it on his end.
