### ISSUE TITLE
Database bug after manually adding data row

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#653]
### Minecraft's Version

This server is running Paper version git-Paper-274 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9460497)

### Plugin's Version

SuperiorSkyblock2-b199.jar

### Describe the bug

One of my players randomly lost their island, and since their physical island was still in the world, I went to one of my backups to retrieve their island data from the database. I looked at the current database folder and their island data was gone, so I planned to copy the row of data from the backup to the current one. I stopped the server, opened both databases, made a new row in the current database, and started to copy everything with CTRL + C to their corresponding columns. After I finished, I saved the current database and uploaded it. Then I started the server and an error continued to appear, causing the server to go in an infinite crash loop. Error: https://pastebin.com/GadCSPF6

### To Reproduce

Make an island
Somehow lose it (I'm not sure how this part happened) (But keep the existing physical island there)
Grab a backup from when the island still existed
Open both databases
Copy the island data exactly from the old database to the current one
Upload new database
Restart server

### Additional Information

Error: https://pastebin.com/GadCSPF6

**Comment by OmerBenGera** [comment]
The name column of the island must be an empty string, not NULL.
