### ISSUE TITLE
Nashornengine memory leak heapdump

### ISSUE THREAD

**Issue by Redwolf223** [BG-Software-LLC/SuperiorSkyblock2#654]
### Minecraft's Version

1.17.1

### Plugin's Version

1.8 stable version

### Describe the bug

Memory leak causing server to crash. Here is the screenshot of our heapdump.

![image](https://user-images.githubusercontent.com/58572866/136793883-0d620e47-2c49-431a-a518-596fcf64088f.png)

We also tried to change engine but it's not working.

https://pastebin.com/Znn29pU3

Thank you,
Redwolf

### To Reproduce

Using nashorn engine.

**Comment by Redwolf223** [comment]
No, we never use /reload.

**Comment by OmerBenGera** [comment]
> No, we never use /reload.

Weird, I am gonna look on google and try to find what may cause it.

**Comment by Redwolf223** [comment]
Thank you!

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Redwolf223** [comment]
Yes after removing the paper java flags the server is not crashing anymore.
