### ISSUE TITLE
Island Members Permissions are reset after restart

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#662]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b323

### Describe the bug

Island Members Permissions are reset after restart

### To Reproduce

Change Members Permissions and restart server

**Comment by OmerBenGera** [comment]
Seems to work fine for me on latest dev build

**Comment by exzolink** [comment]
Maybe same issue like with a bank interest?

**Comment by OmerBenGera** [comment]
> 
> 
> Maybe same issue like with a bank interest?

Maybe it's something with old database migration.
Mind testing it on a new fresh installation of the plugin?

**Comment by exzolink** [comment]
Yes, with latest builds works great. Thanks

**Comment by exzolink** [comment]
Hm, still occurs sometimes for some players (with old islands, before converting)

**Comment by exzolink** [comment]
> 
> 
> If it happens again lmk by commenting here

Hm, still occurs sometimes for some players (with old islands, before converting)

**Comment by OmerBenGera** [comment]
> 
> 
> > If it happens again lmk by commenting here
> 
> Hm, still occurs sometimes for some players (with old islands, before converting)

Use latest build, otherwise I can't help.

**Comment by exzolink** [comment]
Can I provide a database and tell the players' nicknames? Problem still exists

**Comment by exzolink** [comment]
> > > If it happens again lmk by commenting here
> > 
> > 
> > Hm, still occurs sometimes for some players (with old islands, before converting)
> 
> Use latest build, otherwise I can't help.

Can I provide a database and tell the players' nicknames? Problem still exists

**Comment by OmerBenGera** [comment]
Check if the permissions are in the database or not when server stops.

**Comment by exzolink** [comment]
Yes, modified perms in the database now, i will check after restart today

**Comment by exzolink** [comment]
> Check if the permissions are in the database or not when server stops.

It looks like sometimes the permissions are not written to the database and some of them deletes after restart

Before restart (many changed permissions dont exists in the database)
https://imgur.com/a/J70ZBQy

After restart
https://imgur.com/a/NtNFzUH

**Comment by OmerBenGera** [comment]
If they are not saved to the database, they will not stay after a restart.
Open the .session_logs file, check if you can see a "Database Execute" action when permissions that are not saved to db change.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
?
