### ISSUE TITLE
Menus do not open

### ISSUE THREAD

**Issue by infinitelow** [BG-Software-LLC/SuperiorSkyblock2#664]
### Minecraft's Version

Spigot 1.8.8

### Plugin's Version

1.8 - 1.8-DEVb330

### Describe the bug

Menus do not open. I know on the first restart, When everyone spawned on the island, there world boarders disappeared. When this plugin is enabled it broke  QuickBoard and changed the spawn to the default map which I hold for players inv. It was running fine for about 2-3 days. Then it just broken.

If I move my db file to a test server same things happen. I really want to say something happen with the db file I have now. Maybe corrupted on reset or something??? 

### To Reproduce

.

**Comment by OmerBenGera** [comment]
I recommend adding more information in the body of the issue, so I can actually understand what the issue is.
Even if I told you to open a new issue, you need to give information about it.

**Comment by infinitelow** [comment]
done , and sorry for taking so up so much of your time.

**Comment by OmerBenGera** [comment]
Upload your database file and send it here, so I can try replicate it myself using it.

**Comment by infinitelow** [comment]
Github doesn't support the file :/.

**Comment by OmerBenGera** [comment]
> 
> 
> Github doesn't support the file :/.

You need to upload it to a third-party website and send a link to it here.

**Comment by OmerBenGera** [comment]
It works fine for me.
Are you sure you able to replicate it on another server with same database, no other plugins installed?

**Comment by OmerBenGera** [comment]
Any news regarding this?
