### ISSUE TITLE
SuperiorSkyblock2 Error on disabling (stopping server)

### ISSUE THREAD

**Issue by Gladnii** [BG-Software-LLC/SuperiorSkyblock2#674]
### Minecraft's Version

1.8
[FlameSpigot.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7382838/FlameSpigot.zip)
(FlamePaper)
https://github.com/2LStudios-MC/FlamePaper

### Plugin's Version

1.8-DEVb333
(i remember i had issue with disbanding is, and then i tried this dev build and it fixed it)

### Describe the bug

well i dont know, it happens when i stop server

### To Reproduce

stop server

### Additional Information

Default config, everything default
https://pastebin.com/iLaaZS6y (error)
(using local host (SQLite) database)

**Comment by OmerBenGera** [comment]
The plugin cant interact with the database due to an i/o error. This is not related to the plugin. If it happens again after a restart, try deleting the database or switch to mysql.
