### ISSUE TITLE
Custom island schematics

### ISSUE THREAD

**Issue by hcte** [BG-Software-LLC/SuperiorSkyblock2#688]
### Minecraft's Version

1.12.2

### Plugin's Version

Lastest stable build

### Describe the bug

I have added the new schematics and when members try and teleport they get an error about there being no safe blocks - which blocks are classed as safe / is there a way I can add/change a "safe block" myself?

error: https://prnt.sc/1xezngf

### To Reproduce

Don't know if this is a bug because already tried chiseled stone brick and bedrock?

### Additional Information

n/a

**Comment by OmerBenGera** [comment]
Any news regarding this?
