### ISSUE TITLE
Island Level resets after recalculation commands

### ISSUE THREAD

**Issue by SliderKP** [BG-Software-LLC/SuperiorSkyblock2#691]
### Minecraft's Version

Purpur 1.16.5 latest

### Plugin's Version

Dev Build #338

### Describe the bug

i updated to the latest version of SS2, but when try the command /is admin recalc or /is level, the level resets to 0.

if i delete my island, and create again, all works fine, but... how i can reset all user island without island build loses D:?

### To Reproduce

just type /is admin recalc or /is level and island level downgrade to 0

i read in github issues, developer says: "try the plugin in a vanilla server and all works fine"

okey, nice, but my server has a lot of islands i cant just delete all user islands.

### Additional Information

i cant specify the reason when this problem start, maybe an update start this problem. 

i opened the database file to search diferences with old islands(where error exists) and new islands(where the error dont exist) and i dont find any diferences...

i personally think in some update, any little data change in any build, so islands created with the old build dont work properly with the command to calculate the island level, and for this reason, some users dont has this problem and others islands yes.

Thanks in advance, sorry for my bad english im speak spanish.

**Comment by SliderKP** [comment]
i cant use paper, in my server because it crashes maps, i tried but i cant :/

no way to recreate database for example without loses or something similar ?

**Comment by OmerBenGera** [comment]
> i cant use paper, in my server because it crashes maps, i tried but i cant :/
> 
> no way to recreate database for example without loses or something similar ?

Try it with Paper and put your server on whitelist or something... or even better, try replicating the issue on localhost.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SliderKP** [comment]
> Any news regarding this?
no news, im considering to totally reset my server and use new plugin, :/

i going to lose a lot of people...

**Comment by OmerBenGera** [comment]
Use latest build, play a bit until it occurs, and then send me your .session_logs file (it's a new file that logs everything related to the plugin).
After you do so, let me know what is the name of the leader of the island it happened to them, so I can take a look into that.
When you send the file, upload it to pastebin and send the link here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SliderKP** [comment]
https://mega.nz/file/60gEjRJJ#ltYWc1Ar-Foz0G5O4oWybbsCFo2pAC2g7Gnohl7-4O0

**Comment by OmerBenGera** [comment]
> https://mega.nz/file/60gEjRJJ#ltYWc1Ar-Foz0G5O4oWybbsCFo2pAC2g7Gnohl7-4O0

Upload it to pastebin please.

**Comment by OmerBenGera** [comment]
Did you run /is admin recalc and got the 0 message again?

**Comment by SliderKP** [comment]
> Did you run /is admin recalc and got the 0 message again?

this is the _sessionlog more small, in the end of text i write: HERE I GO TO A ISLAND WITH THIS BUG

Image with the is admin recalculate: https://i.imgur.com/lKjiRIS.png

In this image you can see, i placed two diamond blocks and "Valor Isla" or "Island Value" ascend to 100.
![image](https://user-images.githubusercontent.com/6493041/142788616-46a4ce2b-d6fa-4b76-8632-9e1247a4ad25.png)


Srry for delay to answer, im so busy, thanks for waiting and trying to help me.

**Comment by SliderKP** [comment]
@OmerBenGera i found the bug/problem/error are causing this bug in is level/is recalc

in the database, the columns worth_bonus and levels_bonus before are a decimal or number, and now is TEXT, and before in this cell saves at: 0.0, now as: 0, i replaced all 0.0 to 0 in this columns and now all works fine, and the new islands are created correctly, I hope I have helped you solve this problem in other servers that are a few that have it

thanks a lot for trying to help me, good luck with this amazing proyect !!

close when u read this :D

**Comment by OmerBenGera** [comment]
> @OmerBenGera i found the bug/problem/error are causing this bug in is level/is recalc
> 
> in the database, the columns worth_bonus and levels_bonus before are a decimal or number, and now is TEXT, and before in this cell saves at: 0.0, now as: 0, i replaced all 0.0 to 0 in this columns and now all works fine, and the new islands are created correctly, I hope I have helped you solve this problem in other servers that are a few that have it
> 
> thanks a lot for trying to help me, good luck with this amazing proyect !!
> 
> close when u read this :D

Wait, how were they saved as decimals?
They should indeed get saved as a text...
Do you know maybe how it happened?

**Comment by OmerBenGera** [comment]
> @OmerBenGera i found the bug/problem/error are causing this bug in is level/is recalc
> 
> in the database, the columns worth_bonus and levels_bonus before are a decimal or number, and now is TEXT, and before in this cell saves at: 0.0, now as: 0, i replaced all 0.0 to 0 in this columns and now all works fine, and the new islands are created correctly, I hope I have helped you solve this problem in other servers that are a few that have it
> 
> thanks a lot for trying to help me, good luck with this amazing proyect !!
> 
> close when u read this :D

Wait, how were they saved as decimals?
They should indeed get saved as a text...
Do you know maybe how it happened?

**Comment by SliderKP** [comment]
> 

no bro, im not sure :/

**Comment by OmerBenGera** [comment]
I understand.
Well, if it happens again, lmk so it can be fixed.
