### ISSUE TITLE
Upgrades don't work in custom menu.

### ISSUE THREAD

**Issue by KaBoom13** [BG-Software-LLC/SuperiorSkyblock2#694]
### Minecraft's Version

tested on paper/purpur 1.17.1

### Plugin's Version

latest version SuperiorSkyblock2-1.8-b338

### Describe the bug

the bug does not allow adding a new gui that will be able to improve block limits, plant growth rate and everything that is added to the settings in the upgrades folder.

### To Reproduce

1. Remove one parameter upgrade option from the upgrades.yml file.
2. create your own gui in which you will want to improve that parameter.
3. in gui, that parameter will not appear, and the console will display, for example, "The upgrade hopper-limit doesn't have an item in the menu."

### Additional Information

if more information is needed, he will add it.

**Comment by OmerBenGera** [comment]
You are more than welcome to change the upgrades menu however you want, and add whatever upgrades you want there. Make sure tho all the upgrades in the upgrades menu have an item in the pattern, otherwise it will display the warning.

If my answer isnt helpful, upload your upgrades.yml menu file and I will take a look at what you have done.
I dont think there is a bug here, and therefore I close the issue for now.

**Comment by OmerBenGera** [comment]
> 
> 
> I mean that if I want to create my menu in the "menus/custom" location and the upgrades in it, they do not work.

If you make a custom menu, you need to make that menu will make players execute `/is rankup` when they click your custom items, as it only happens automatically in the upgrades menu.
You probably want your upgrades menu to open the custom menu when clicking items, which you can do the same by making players execute commands.

**Comment by KaBoom13** [comment]
> Jeśli stworzysz niestandardowe menu, musisz sprawić, że gracze będą wykonywać po kliknięciu niestandardowych elementów, ponieważ dzieje się to automatycznie tylko w menu ulepszeń. Prawdopodobnie chcesz, aby menu ulepszeń otwierał niestandardowe menu podczas klikania przedmiotów, co możesz zrobić to samo, wykonując polecenia graczy.`/is rankup`

is it possible for each upgrade to update the upgrade description?

**Comment by OmerBenGera** [comment]
> 
> 
> > Jeśli stworzysz niestandardowe menu, musisz sprawić, że gracze będą wykonywać po kliknięciu niestandardowych elementów, ponieważ dzieje się to automatycznie tylko w menu ulepszeń. Prawdopodobnie chcesz, aby menu ulepszeń otwierał niestandardowe menu podczas klikania przedmiotów, co możesz zrobić to samo, wykonując polecenia graczy.`/is rankup`
> 
> is it possible for each upgrade to update the upgrade description?

You can edit the menus however you want.

**Comment by KaBoom13** [comment]
> You can edit the menus however you want.

I think I wrote a little wrong there. I meant that when, for example, a player upgrades to level 2, he will receive a different description of the item (which works as an upgrade), e.g. with a modified price, etc.

**Comment by OmerBenGera** [comment]
> 
> 
> > You can edit the menus however you want.
> 
> I think I wrote a little wrong there. I meant that when, for example, a player upgrades to level 2, he will receive a different description of the item (which works as an upgrade), e.g. with a modified price, etc.

This is possible using the upgrades menu, no?
