### ISSUE TITLE
already ongoing island creation task.

### ISSUE THREAD

**Issue by riderovsky** [BG-Software-LLC/SuperiorSkyblock2#698]
### Minecraft's Version

1.8.8

### Plugin's Version

338

### Describe the bug

When i trying to create an island its saying that i have already ongoing island creation task.

### To Reproduce

just loop creating and disbanding island

**Comment by OmerBenGera** [comment]
Are there any errors?

**Comment by riderovsky** [comment]
no errors

**Comment by OmerBenGera** [comment]
I can't replicate the issue, everything works fine for me.
The `already have an on going creation task` can happen if you try to create a second island while the first island is still being created.

**Comment by riderovsky** [comment]
maybe you can add some command that gona cancel it?

**Comment by OmerBenGera** [comment]
> maybe you can add some command that gona cancel it?

Before that, can you take a video of the issue?

**Comment by riderovsky** [comment]
riderovsky#6233 its my discord, just add me and will show u everything

**Comment by OmerBenGera** [comment]
> riderovsky#6233 its my discord, just add me and will show u everything

Upload it to youtube or any other streaming service

**Comment by riderovsky** [comment]
https://youtu.be/n64fSeCJnQg

**Comment by OmerBenGera** [comment]
Please use latest build, restart your server, and try it again.
Once it occurs, locate the ".session_logs" file (it's in the plugin's folder) and upload it to pastebin and send it here.

**Comment by OmerBenGera** [comment]
Any news regarding this?
