### ISSUE TITLE
Stacked Blocks Bug

### ISSUE THREAD

**Issue by Zsomi** [BG-Software-LLC/SuperiorSkyblock2#702]
### Minecraft's Version

1.16.5-Paper

### Plugin's Version

1.8-latest version

### Describe the bug

When I restart the server, the stacked blocks deposited by the players disappear. The one deposited block itself remains, only the hologram disappears. However, only 1 block remains there.

### To Reproduce

1. Restart the server.
2. When it starts, the stacked blocks will disappear.

### Additional Information

http://pastebin.fr/97282 - config.ym

![minezone2](https://user-images.githubusercontent.com/31018282/140566052-b9977cf1-aaa3-4b7a-a9e6-4bd5b214c21e.png)
![unknown](https://user-images.githubusercontent.com/31018282/140566060-cd58d596-362a-4b11-8499-4d2d33268e61.png)
l

**Comment by OmerBenGera** [comment]
Update to latest dev build please, this issue was already fixed in latest dev build
