### ISSUE TITLE
Random disappear Spawner block

### ISSUE THREAD

**Issue by MynamisTG** [BG-Software-LLC/SuperiorSkyblock2#703]
### Minecraft's Version

1.8.x

### Plugin's Version

b199

### Describe the bug

Im using Mobextras 
And i dont know why the spawner blocks of players are random disappear, but data of plugin still there
Can u add support for Mobextras?
https://gyazo.com/9975e8caabfb0d92f2804a6d068ac958

### To Reproduce

Place or break

### Additional Information

https://gyazo.com/9975e8caabfb0d92f2804a6d068ac958

**Comment by OmerBenGera** [comment]
This is not a bug with WildStacker.
Something is breaking/removing the spawner block without letting WildStacker know about it.
