### ISSUE TITLE
Database corrupts?

### ISSUE THREAD

**Issue by verxii** [BG-Software-LLC/SuperiorSkyblock2#707]
### Minecraft's Version

Minecraft version and server version are 1.8(spigot) 

### Plugin's Version

1.8

### Describe the bug

I find that after about 10 server restarts the /is command stops functioning and some other subcommands do to. Some others stay working. No errors to the console and the only fix I find is deleting the database.db which unfortunately resets everyone's island. Any fixes? Should I be on a later version of spigot?

### To Reproduce

Populate the database with a few islands and players, then restart a handful of times.

**Comment by OmerBenGera** [comment]
Upload latest.log file please.

**Comment by OmerBenGera** [comment]
Any news regarding this?
