### ISSUE TITLE
Convert from old missions file

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#708]
### Minecraft's Version

1.12.2

### Plugin's Version

b348

### Describe the bug

Hello when i use the previous missions files in i've this issue https://pics.revolis.fr/2021-11/06/21-25_rADX.png

### To Reproduce

Use old missions file and restart the server with latest build of ss2

**Comment by OmerBenGera** [comment]
Please upload your old missions file.

**Comment by nivcoo** [comment]
[config.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7492408/config.zip)
Yes

**Comment by OmerBenGera** [comment]
> [config.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7492408/config.zip) Yes

Upload them to pastebin

**Comment by nivcoo** [comment]
https://www.toptal.com/developers/hastebin/enuwocajow.sql

**Comment by OmerBenGera** [comment]
> https://www.toptal.com/developers/hastebin/enuwocajow.sql

I am not sure if this pastebin will stay until the weekend.
Please upload to pastebin.

**Comment by nivcoo** [comment]
https://pastebin.com/vm1qZS3j

**Comment by OmerBenGera** [comment]
What about the missions menu file?

**Comment by nivcoo** [comment]
https://pastebin.com/ZsdauLcs

**Comment by OmerBenGera** [comment]
Fixed in latest build
