### ISSUE TITLE
Cooper Stacked Blocks

### ISSUE THREAD

**Issue by cobrex1** [BG-Software-LLC/SuperiorSkyblock2#709]
### Minecraft's Version

Paper 1.17.1 release 369

### Plugin's Version

b344 and b260. I discovered this while using b260, so waited for the update and then also tried it with b344.

### Describe the bug

I have all the variations of the copper block in the stackable list in the config. When I stack 4 copper blocks and leave them until they change state to exposed copper. When I break the stack I only get 1 block back and loose the other three.

This happens at all stages of the copper block aging process. I also note that as the copper block changes state the Holo remains as its original and does not update.

The picture below shows it.

![copper](https://user-images.githubusercontent.com/44735826/140640129-a73da329-4ac4-4ec8-abe2-ed2aa3d6e90f.png)

### To Reproduce

Just add all copper blocks to your config, place and stack on your island, wait for the state to change and break the stack

**Comment by OmerBenGera** [comment]
I think I will just cancel stacked copper blocks from changing states, what do you think?

**Comment by cobrex1** [comment]
That actually may not be a bad idea. Stop copper, exposed and weathered stacked blocks from changing state. Oxidized is fine as that is the last stated and so are all the waxed versions as they do not change state.

**Comment by Skizzles** [comment]
> I think I will just cancel stacked copper blocks from changing states, what do you think?

I love this idea, then people don't need to wax the blocks either :)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
