### ISSUE TITLE
Bug of generator

### ISSUE THREAD

**Issue by Birsenberg** [BG-Software-LLC/SuperiorSkyblock2#712]
### Minecraft's Version

1.17.1

### Plugin's Version

348

### Describe the bug

https://paste.gg/p/anonymous/54498f326bc245e387ccb8674422fa33
I have this error of generator with the last cores of paper, airplane and other forks
But on tuinity it is work fine
Please fix this because the Tuinity has not been performed for a very long time.

### To Reproduce

island not generated with generator addon

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
