### ISSUE TITLE
New mission system doesn't display missions in correct order

### ISSUE THREAD

**Issue by Rivils** [BG-Software-LLC/SuperiorSkyblock2#715]
### Minecraft's Version

git-Purpur-1415 (MC: 1.17.1)

### Plugin's Version

version 1.8.1

### Describe the bug

Right now the missions do not display in the correct order. For example Farmer I,II, III missions are display like this in GUI - Farmer II shows first, Farmer I is second and Farmer III is last. If you have more missions that need to be completed in order the GUI looks like a mess.

### To Reproduce

use the newest version of the plugin.

**Comment by OmerBenGera** [comment]
It only occurs on Linux afaik, I will look into that.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build
