### ISSUE TITLE
Mysql Driver not found, Trying direct instantiation.

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#716]
### Minecraft's Version

1.17.1 Purpur dev 1423

### Plugin's Version

Dev 348

### Describe the bug

A commit from Paper a while ago bumped MySQL to 8 you can find that here:
https://github.com/PaperMC/Paper/pull/5474

Unsure if this affects database functionality at all, however, though I would let you know.

### To Reproduce

Connect up a good ole MySQL database in recent versions of Paper or its forks
See the WARN in console

### Additional Information

[04:09:02 WARN]: [com.bgsoftware.superiorskyblock.libs.hikari.util.DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.

**Comment by OmerBenGera** [comment]
Thanks for letting me know,
it shouldnt affect anything
