### ISSUE TITLE
After adding latest version my server has crashed and has bugged multiple plugins

### ISSUE THREAD

**Issue by SOLJAOVLS12** [BG-Software-LLC/SuperiorSkyblock2#717]
### Minecraft's Version

1.17.1

### Plugin's Version

1st added 2.11.1 it messed my server so tried  dev build #28 and same happens

### Describe the bug

after adding the plugin i had multiple warns from superiorskyblock2 and many other plugins didnt have any till i added latest version 

### To Reproduce

Not sure as all i did was add latest version

**Comment by OmerBenGera** [comment]
Upload the errors you recieved to pastebin and send them here

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SOLJAOVLS12** [comment]
Sorry ye was real busy seen many others having same issue so just went back a few updates and worked fine only problem I have now is island missions are stuck in alphabetical order when they used to be in order of missions

**Comment by OmerBenGera** [comment]
Update to latest version, first of all.
downgrading your plugin can lead to bad things, one of them is corrupting your database.
I will add a way to sort missions in other way.

**Comment by SOLJAOVLS12** [comment]
But what else can we do when your latest version is messed up that bad it crashes everyone's servers

**Comment by OmerBenGera** [comment]
> 
> 
> But what else can we do when your latest version is messed up that bad it crashes everyone's servers

No one have yet to provide me with a single logs that shows anything related to crashes.
Update to latest build, and if it crashes send me logs so I can actually fix it.
Otherwise, I'll have to close the ticket.
