### ISSUE TITLE
Block keys disappear when the island's worth is recalculated.

### ISSUE THREAD

**Issue by Tyguh** [BG-Software-LLC/SuperiorSkyblock2#718]
### Minecraft's Version

PaperSpigot 1.8.8

### Plugin's Version

1.8.1

### Describe the bug

Whenever the value of an island is recalculated whether it's by using /is recalc, /is level, or /is admin recalc all my custom block keys are no longer counted towards the island's value.

### To Reproduce

Essentially you just place down the block(s) registered as a custom block key, note their counts using /is counts. You then run either /is recalc, /is level, or /is admin recalc and check your /is counts again which will no longer contain the custom keys.

### Additional Information

BlockKeyProvider: https://www.toptal.com/developers/hastebin/poferisudu.kotlin

SpawnerKeyProvider: https://www.toptal.com/developers/hastebin/toveyoreki.kotlin
          
Method ran when adding the block:
`SuperiorSkyblockAPI.getIslandAt(e.getBlock().getLocation()).handleBlockPlace(e.getBlock(), 1, true);`

Method ran with removing the block:
`SuperiorSkyblockAPI.getIslandAt(e.getBlock().getLocation()).handleBlockBreak.(e.getBlock(), 1, true);`

Registering them in the onEnable:
`Bukkit.getScheduler().runTaskLater(this, () ->
   SuperiorSkyblockAPI.getBlockValues().registerKeyParser(new SpawnerKeyProvider(), Key.of("STACKED_SPAWNER")), 1L);
   Bukkit.getScheduler().runTaskLater(this, () ->
   SuperiorSkyblockAPI.getBlockValues().registerKeyParser(new BlockKeyProvider(), Key.of("STACKED_BLOCK")), 1L);`

**Comment by OmerBenGera** [comment]
Do you have a custom spawners provider?

**Comment by Tyguh** [comment]
I don’t think that’s the issue since the problem happens with stacked blocks too, but I do have one.
 
 https://www.toptal.com/developers/hastebin/adigufibot.swift

**Comment by OmerBenGera** [comment]
Does it happen with all the custom block keys?

**Comment by Tyguh** [comment]
Yes it happens with both spawners and stacked blocks

**Comment by OmerBenGera** [comment]
I'll look into that.

**Comment by OmerBenGera** [comment]
The issue might be because of how you register the key parsers.
Here is the documentation of `registerKeyParser`:
```
/**
 * Register a custom key parser.
 *
 * @param customKeyParser The custom key parser.
 * @param blockTypes      All the block types you want to check.
 */
```

You should put in blockTypes the blocks you want to check. In your case, it's all your stacked-block types or "MOB_SPAWNER". However, you put "STACKED_BLOCK" and "STACKED_SPAWNER" instead, which is probably why it doesn't work well when calculating the blocks.

Try changing it, hopefully that fixes the issue.

**Comment by Tyguh** [comment]
How would you register multiple blocks under one key parser?

`void registerKeyParser(CustomKeyParser customKeyParser, Key... blockTypes);`

This is the only registerKeyParser method I could find. The parameter for blockTypes is Key and I can’t see how you could register more the one block type within the Key.

`static Key of(Material material, short data){
        Preconditions.checkNotNull(material, "material parameter cannot be null.");
        return SuperiorSkyblockAPI.getSuperiorSkyblock().getKeys().getKey(material, data);
    }`

Which only accepts one material type not multiple.

**Comment by OmerBenGera** [comment]
> 
> 
> How would you register multiple blocks under one key parser?
> 
> `void registerKeyParser(CustomKeyParser customKeyParser, Key... blockTypes);`
> 
> This is the only registerKeyParser method I could find. The parameter for blockTypes is Key and I can’t see how you could register more the one block type within the Key.
> 
> `static Key of(Material material, short data){ Preconditions.checkNotNull(material, "material parameter cannot be null."); return SuperiorSkyblockAPI.getSuperiorSkyblock().getKeys().getKey(material, data); }`
> 
> Which only accepts one material type not multiple.

It accepts multiple keys as a parameter, not only one :)

**Comment by Tyguh** [comment]
Changed the Block Key Providers to match the way you requested above and the block keys now save on is recalc. However, the plugin has stacked blocks so the is recalc command was only counting one. I noticed that you had a StackedBlockProvider so I created that which can be seen down below

https://www.toptal.com/developers/hastebin/ipojoruket.swift

registering it

```
        Bukkit.getScheduler().runTask(plugin, () -> {

SuperiorSkyblockAPI.getSuperiorSkyblock().getProviders().setSpawnersProvider(new SpawnerProvider());
            SuperiorSkyblockAPI.getSuperiorSkyblock().getProviders().setStackedBlocksProvider(new StackedBlockProvider());

        });
```

this error is now thrown when the is recalc command is ran

https://www.toptal.com/developers/hastebin/enadeqayan.md

**Comment by OmerBenGera** [comment]
getBlocks should return a collection of pairs which their key values are Key objects and not Block objects.

I am closing this one, as it seems to work for you now :)
