### ISSUE TITLE
Co-op removes when server leave

### ISSUE THREAD

**Issue by KillerShark057** [BG-Software-LLC/SuperiorSkyblock2#722]
### Minecraft's Version

1.17.1 (Paper)

### Plugin's Version

SuperiorSkyblock2-1.8-b338.jar

### Describe the bug

When someone leaves the server and it's on co-op, admin, moderator, member, etc. with another person, that permission automaticaly removes.

### To Reproduce

1. Create an island.
2. Invite to co-op your friend in the server. /is coop [name].
3. Play normally with your friend.
4. Make your friend leave and re-join the server.
5. Realize that your friend has no more the co-op permissions. 

### Additional Information

I'll try to make a video, and edit this issue, but I'm not sure if that's possible.

**Comment by OmerBenGera** [comment]
That's how co-op works.
Co-op is a temporary permission and is revoked when the player leaves the island, or there are no members online that can revoke the permission later.

If you want to give permanent permissions to players, use `/is permissions` instead :)
