### ISSUE TITLE
Malware detection

### ISSUE THREAD

**Issue by bennettholasek** [BG-Software-LLC/SuperiorSkyblock2#725]
### Minecraft's Version

my server runs on paper 1.16.5

### Plugin's Version

build 362

### Session Logs

https://pastebin.com/uzKTp7mU

### Describe the bug

so i use mythic mobs with this plugin and it screws with the chunks and detects a virus me and my dev looked through the code and i guess it has a virus i love this plugin and i need it to work on my server i have spent hours on end making configs it would be awesome if you could check this out so i can get it up and running asap

### To Reproduce

well im not to sure all i know was when i was loading mythic mobs without the skyblock core it was fine then when i added it the plugins backdoor system detected malware or sum and it ends up disabling the plugin and i really like ur skyblock core and i really need it to work with mythic obs

### Additional Information

https://pastebin.com/uzKTp7mU

**Comment by OmerBenGera** [comment]
There is no backdoor or anything like that.
You are more than welcome to look through the code and check for backdoors, you will not find any.
Remove the plugin that disables SSB and you will be good
