### ISSUE TITLE
I have been getting the following error

### ISSUE THREAD

**Issue by sahilshinde** [BG-Software-LLC/SuperiorSkyblock2#726]
### Minecraft's Version

This server is running Paper version git-Paper-"eeb3dea" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: eeb3dea)

### Plugin's Version

SuperiorSkyblock2-1.8.1.jar

### Session Logs

https://mcpaste.io/8353eb2c642663ed

### Describe the bug

It Just Gives error on the console

### To Reproduce

No idea

**Comment by OmerBenGera** [comment]
Duplicate of #371
