### ISSUE TITLE
Plugin can't start after downgrading to old versions [Not a bug]

### ISSUE THREAD

**Issue by flamingomg** [BG-Software-LLC/SuperiorSkyblock2#727]
### Minecraft's Version

1.16.5

### Plugin's Version

362

### Session Logs

https://pastebin.com/vGUchFq8

### Describe the bug

So, because i updated to the lastest version, stacking blocks dissapeared, so I reverted back to the other version where I was, but it somehow fucked everything i dont know why since is a plugin version not a game version, and levels and islands dissapeared so i reverted back to the lastest and now i cant even startup the server closes inmediately after loading
[16:43:37 INFO]: [SuperiorSkyblock2] Detected crash. SuperiorSkyblock will attempt to save data...

### To Reproduce

downgrade from the last version to an older version of the plugin, then upgrade it to the lastest again

**Comment by OmerBenGera** [comment]
Never downgrade your plugin, especially if there are massive changes, for example - the way the database is saved.
Of course now the plugin is broken...

As I told you on the discord, delete the tables that break the plugin (the old tables) and start the server again.
It should fix everything.
