### ISSUE TITLE
Island Creation Error 

### ISSUE THREAD

**Issue by BeansBeanies** [BG-Software-LLC/SuperiorSkyblock2#731]
### Minecraft's Version

This server is running Paper version git-Paper-381 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: db0bff9)
You are running the latest version
Previous version: git-Paper-378 (MC: 1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.8.1

### Session Logs

[https://pastebin.com/0cKR7yXr](url) - Short Log
[https://pastebin.com/B2z06GEK](url) - Full Log

### Describe the bug

Every time one of my players creates an island I get these errors in the console 

### To Reproduce

Create an island

**Comment by OmerBenGera** [comment]
Show me your missions file please.

**Comment by BeansBeanies** [comment]
Mission file in modules or menus?

**Comment by OmerBenGera** [comment]
From the modules file.

**Comment by BeansBeanies** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/86257277/141684820-6ffa41ef-83a0-412b-8083-24adb280bab6.png)
![Screenshot_2](https://user-images.githubusercontent.com/8625
![Screenshot_4](https://user-images.githubusercontent.com/86257277/141684853-eef46bff-b462-46f4-bd1e-af6974a77df1.png)
![Screenshot_5](https://user-images.githubusercontent.com/86257277/141684854-64cc5313-ce9a-4f28-a506-192e16170b50.png)
![Screenshot_6](https://user-images.githubusercontent.com/86257277/141684855-1883f126-92d8-4cd7-86bf-b2464e3ee2e8.png)
7277/141684848-91da5a9a-7839-4393-afad-7f7f2ebde58c.png)
![Screenshot_3](https://user-images.githubusercontent.com/86257277/141684850-7628ba46-8dc4-4bca-8dc9-d2db68682c7e.png)

**Comment by BeansBeanies** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/86257277/141684868-7865f50b-5c67-4c3d-a95e-34dc57d5b242.png)

**Comment by OmerBenGera** [comment]
Upload the explorer mission files to pastebin and send them here please

**Comment by BeansBeanies** [comment]
explorer_1.yml
https://pastebin.com/F5RkyMMZ

explorer_2.yml
https://pastebin.com/ttLDxYcz

**Comment by BeansBeanies** [comment]
Just tested that and the issue is no longer happening

**Comment by OmerBenGera** [comment]
Perfect.
If it occurs again, make sure you let me know
