### ISSUE TITLE
Lava bug

### ISSUE THREAD

**Issue by Florens11** [BG-Software-LLC/SuperiorSkyblock2#736]
### Minecraft's Version

 This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

 SuperiorSkyblock2 version 1.8.1

### Session Logs

There's none in my superiorskyblock folder.

### Describe the bug

I placed some lava on signs then this error appeared in console.

### To Reproduce

Place lava on signs.

### Additional Information

Error: https://pastebin.com/ezRrSupr

**Comment by OmerBenGera** [comment]
What is the worth value you set to lava?
Also, show me the levels formula from your config file

**Comment by Florens11** [comment]
I want to disable worth but here it is: island-level-formula: '{} / 0'
There is no lava in my worth.yml

**Comment by OmerBenGera** [comment]
> I want to disable worth but here it is: island-level-formula: '{} / 0' There is no lava in my worth.yml

You cant divide by 0 in mathmatics.
Set the formula to 0 instead.

**Comment by OmerBenGera** [comment]
I am closing this as of now.
