### ISSUE TITLE
Block Keys don't register in certain chunks.

### ISSUE THREAD

**Issue by Tyguh** [BG-Software-LLC/SuperiorSkyblock2#737]
### Minecraft's Version

PaperSpigot 1.8.8

### Plugin's Version

1.8.1-b362

### Session Logs

https://pastebin.com/EiiXgscv

### Describe the bug

I noticed that some of my block keys don't register in certain chunks when placed, specifically end portal frames.

### To Reproduce

Place block keys that have end portal frames as the material in different chunks with /is admin debug toggled on. You'll notice that in different chunks, it'll add data after the material that was placed for example: `ENDER_PORTAL_FRAME:3` and some will return the proper block key name.

**Comment by Tyguh** [comment]
Also after changing the block keys to work how you mentioned in my previous issue report, they now save on recalc however they don't count accurately.

**Comment by OmerBenGera** [comment]
The data you mentioned is because of the direction you place the blocks in. I think the issue is because of how you register your stacked ender portal frame keys, as the directional frames dont recognize as stacked ones, causing your values to not register for them.

**Comment by Tyguh** [comment]
`    private static final class EnderPortalFrameParser implements CustomKeyParser {
        @Override
        public Key getCustomKey(Location location) {

            if (!location.getBlock().getType().equals(Material.ENDER_PORTAL_FRAME)) {

                return null;

            }

            return Data.get().getStackedBlocks().containsKey(LocationUtil.locationToString(location))
                    ? Key.of("STACKED_" + location.getBlock().getType().toString())
                    : Key.of(location.getBlock().getType().toString());
        }

        @Override
        public boolean isCustomKey(Key key) {
            return key.toString().contains("STACKED_ENDER_PORTAL_FRAME");
        }
    }`
    
    
`            SuperiorSkyblockAPI.getBlockValues().registerKeyParser(new EnderPortalFrameParser(), 
Key.of(Material.ENDER_PORTAL_FRAME, (short) 0));`

**Comment by OmerBenGera** [comment]
> ```
> private static final class EnderPortalFrameParser implements CustomKeyParser {
>     @Override
>     public Key getCustomKey(Location location) {
> 
>         if (!location.getBlock().getType().equals(Material.ENDER_PORTAL_FRAME)) {
> 
>             return null;
> 
>         }
> 
>         return Data.get().getStackedBlocks().containsKey(LocationUtil.locationToString(location))
>                 ? Key.of("STACKED_" + location.getBlock().getType().toString())
>                 : Key.of(location.getBlock().getType().toString());
>     }
> 
>     @Override
>     public boolean isCustomKey(Key key) {
>         return key.toString().contains("STACKED_ENDER_PORTAL_FRAME");
>     }
> }
> ```
> 
> ` SuperiorSkyblockAPI.getBlockValues().registerKeyParser(new EnderPortalFrameParser(), Key.of(Material.ENDER_PORTAL_FRAME, (short) 0));`

Use Key.of("ENDER_PORTAL_FRAME") so all the directions of the frames will be filtered and not only one direction (the 0 for the data is a direction)

**Comment by Tyguh** [comment]
This fixed my issue thank you so much!
