### ISSUE TITLE
Guest visitors on islands can access Barrels

### ISSUE THREAD

**Issue by dimpetrop** [BG-Software-LLC/SuperiorSkyblock2#739]
### Minecraft's Version

Pufferfish 1.17.1

### Plugin's Version

1.8.1.362

### Session Logs

[session_logs.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7549764/session_logs.zip)

### Describe the bug

Guest players are able to open and take items from Barrels

### To Reproduce

Chest-access permission is set to either Member or Coop. Visitors (players who have TPed) are still able to access Barrels.

### Additional Information

All relevant hopper access, Community Chest, Minecart Open, etc is set so that Guests are not able to open them.

**Comment by OmerBenGera** [comment]
Add "BARREL" to the interactables.yml file
