### ISSUE TITLE
 Error. 

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#740]
### Minecraft's Version

1.16.5 Paper

### Plugin's Version

v1.8.1.362

### Session Logs

can't it's 12k rows ;3 but the lower part, https://pastebin.com/TqvVJ8ef

### Describe the bug

Throws error: https://pastebin.com/zvcwdM2M

### To Reproduce

Error describes.

**Comment by OmerBenGera** [comment]
Duplicate of #371
