### ISSUE TITLE
Valuable block glitch

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#741]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b346

### Session Logs

*I'm not using latest, but doesn't matter*

### Describe the bug

If you set "dragon_egg" into valuable blocks, to avoid a player to break it, you can still do the "torch glitch" to get the egg.

### To Reproduce

![Screenshot_7068](https://user-images.githubusercontent.com/31826333/142518572-8ad30a0e-9a39-4933-b43b-c0a260231880.png)

### Additional Information

It would be heavier to check the block upper the current you break everytime..
But maybe you'll find a good way to patch it !

**Comment by OmerBenGera** [comment]
Fixed in latest build
