### ISSUE TITLE
Crash on startup in latest dev builds

### ISSUE THREAD

**Issue by rolfie12** [BG-Software-LLC/SuperiorSkyblock2#743]
### Minecraft's Version

[11:13:58] [Thread-35/INFO]: This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)

### Plugin's Version

Using the latest dev build 372, cannot send exact output of /version SuperiorSkyblock2 due to crash on startup.

### Session Logs

https://pastebin.com/8e8dJ2St

### Describe the bug

Crash on startup with the following errors:
https://pastebin.com/jHL42pGe
https://pastebin.com/61ebQada

Tried on a test server, and the same issue happens when using SQLite or MySQL storage options.
There's absolutely no issues when using build 366, however just upgrading to build 371 or 372 causes the issues.
Using dev build 366 works perfectly fine, 371 and 372 have the issue and did not test versions in between those.

### To Reproduce

Try using the latest dev builds on latest paper 1.17.1, the issue should happen on startup and would crash the server.

**Comment by OmerBenGera** [comment]
@rolfie12 What version of FAWE are you using?

**Comment by rolfie12** [comment]
[11:24:23] [Server thread/INFO]: FastAsyncWorldEdit version 1.17-192;0c9270d

**Comment by OmerBenGera** [comment]
Fixed in latest build
