### ISSUE TITLE
Island level and value

### ISSUE THREAD

**Issue by Zsomi** [BG-Software-LLC/SuperiorSkyblock2#744]
### Minecraft's Version

1.16.5-Paper

### Plugin's Version

1.8.1-b362

### Session Logs

There were no errors in the log file.

### Describe the bug

When I restart the server, the island value or level decreases. The / is admin recalc command sometimes improves, but players say they have lost a lot of value or level.

### To Reproduce

- Restart the server
- View island value and level

### Additional Information

![142719382-5b690726-9b27-41b6-bfad-3416d43edfd5](https://user-images.githubusercontent.com/31018282/142728221-ddc08892-68d7-4164-b2e1-2e0d78eefd6e.png)

![142719384-9b8bf7fc-057e-439d-9dfe-60e30a29799c](https://user-images.githubusercontent.com/31018282/142728212-2ebad691-6818-421c-9cd8-7775a767b42b.png)

**Comment by OmerBenGera** [comment]
When you run `/is level` or `/is admin level <player-name>`, it counts all the blocks from scratch and recalculates the worth.
Therefore, the result of the task is the actual worth value of the islands.

Btw, you look at holograms to check for island worth and values, which is not a good way to do so - use `/is admin show` instead.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Zsomi** [comment]
According to one of my players, it counts points correctly if all members are available on the island.  That's all I've learned so far.

**Comment by OmerBenGera** [comment]
The recalculation task doesn't do anything if there are no members in the island, and that it wasn't updated for at least 10 minutes before so. Therefore, even if you run /is admin recalc on that island but you didn't "update" it (even teleporting to it will refresh it's update state) it won't do anything.

**Comment by Zsomi** [comment]
I understand.  However, there were times when a couple of island members were available but sometimes when I updated nothing happened.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Zsomi** [comment]
Hi, solved the problem on the server side there was an error that somehow restored the previous backup. I'm sorry I haven't written so far. Thanks for the tip.
