### ISSUE TITLE
Session log issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#745]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b371

### Session Logs

Lol I can't upload it

### Describe the bug

My .session_logs file is 10GB in less than 24h after I updated superior (I didn't get this file before, I was using b345)
And now superior consumes way more cpu in spark

spark : 
https://spark.lucko.me/1XHGN2FefU

File : 
![Screenshot_14](https://user-images.githubusercontent.com/31826333/142744959-cd060c63-344a-47a0-b212-4903f8312a3c.png)

And it increse 1-2MB every second.

### To Reproduce

*

### Additional Information

- I'm using dedicated server
- Using MySQL
- 90-100 constant players

**Comment by OmerBenGera** [comment]
Send me the spark profiler as well.

**Comment by OmerBenGera** [comment]
Also, send me the file here please.
If you cant upload it, cut it into half or something and upload. I want to see which debug messages are spammed so I can reduce the amount of them.

**Comment by WarnDa** [comment]
The spark :
https://spark.lucko.me/XE1ZYbUxPX

I can't download the file, as I deleted it :/
But other people on discord as the same issue, you can ask them

**Comment by WarnDa** [comment]
The issue with the spark also appear on older superior version.
It appears since I turned ON upgrade (to fix islands limit that do not work)

**Comment by OmerBenGera** [comment]
If the spark is not related to the issue, open a new issue regarding this.

About the session logs, without them I cant do anything. You can forward this issue to the other people on discord so they can upload it to here.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WarnDa** [comment]
I'll update the plugin soon and try to download the file to upload it (now I got a very good connexion compared to before so I can.)

**Comment by WarnDa** [comment]
So, 
I tried to update to get the session logs.
In 6 minutes with 15 players I got 100MB logs : 
- The file itself : https://mega.nz/file/9k9T2aLS#AMxAe11u40rlF3IxJg5meWFfFbtV0JqRxJJ3ro0Wjic
-The file is too heavy to be pasted, so I pasted a part on a pastebin (can't use pastebin/hastebin as it's too heavy) : 
https://paste.helpch.at/obopijubep.sql

So the number of chunk loading/checking can also be related to the heavy task in the issue https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/747

**Comment by OmerBenGera** [comment]
I disabled session logs in latest logs.
