### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#746]
### Minecraft's Version

1.16.5 paper

### Plugin's Version

SuperiorSkyblock2 v1.8.1.376

### Session Logs

[session_logs(2).zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7577112/session_logs.2.zip)

### Describe the bug

console flooding

### To Reproduce

update island worth ig? 

### Additional Information

https://pastebin.com/G1HF11rY

**Comment by OmerBenGera** [comment]
Duplicate of #371
