### ISSUE TITLE
Visitors can interact on other player island. (Sellwand plugin issue)

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SuperiorSkyblock2#754]
### Minecraft's Version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1

### Plugin's Version

SuperiorSkyblock2 version 1.8.2

### Session Logs

its not letting me to paste on pastebin

### Describe the bug

I use a plugin called Sellwand plugin which is that plugin sells the items from the chest. and you need to right click it only the chest to sell it which is the problem here even its not your island and your not invited.  you can right click the chest and sell it 

### To Reproduce

Install a plugin called Sellwand then right click the chest that island your not invited

**Comment by OmerBenGera** [comment]
This is an issue with your Sellwand plugin.
Contact them regarding this.
