### ISSUE TITLE
Adventurer Mode Issue

### ISSUE THREAD

**Issue by pixelnw** [BG-Software-LLC/SuperiorSkyblock2#755]
### Minecraft's Version

flamepaper 1.8.8

### Plugin's Version

1.8.2 (latest)

### Session Logs

https://codeshare.io/9OYjo4

### Describe the bug

After entering Skyblock Island, I log out of the server and log back in. When I enter the server in another world, the game mode is like adventure mode, I can't build and break the block.

But the game mode is not an adventure mode because /gamemode 1 etc. Same thing happens when I do.

If I go to the island "/is go" this problem goes away.

### To Reproduce

- Enter the Skyblock island.
- Log out from the server while on the island
- Login to the server again, but the world you log into must be different.
- Something like the adventure mode I mentioned happens.

**Comment by OmerBenGera** [comment]
This is not related to the plugin.
About the errors you have, correct the sounds you have in your config files.

**Comment by pixelnw** [comment]
> This is not related to the plugin. About the errors you have, correct the sounds you have in your config files.

Spark Profile: https://spark.lucko.me/Ktmh2OwLY2
Config: https://www.toptal.com/developers/hastebin/tivevepote.yaml
