### ISSUE TITLE
CraftingsMissions and EnchantingMissions

### ISSUE THREAD

**Issue by JLucassz** [BG-Software-LLC/SuperiorSkyblock2#761]
### Minecraft's Version

This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
You are running the latest version
Previous version: git-Paper-386 (MC: 1.17.1)

### Plugin's Version

SuperiorSkyblock 1.8.2

### Session Logs

[18:14:06 WARN]: Caused by: com.bgsoftware.superiorskyblock.api.missions.MissionLoadException: Invalid crafting result [BREWING_STAND].

### Describe the bug

I'm having doubts about the right format to use in crafting and enchantment missions, could you help me? The way I'm doing this error is happening. What is the correct format? I can't find it anywhere.

### To Reproduce

![image](https://user-images.githubusercontent.com/76066285/143786658-b03ebf07-15bb-4c08-83ef-b0f8b902beda.png)

**Comment by OmerBenGera** [comment]
I cant find the correct material for you now, as I am not near computer.
You can look for the correct material yourself, or ask in the discord server for help.
