### ISSUE TITLE
Plugin won't register hopper removal

### ISSUE THREAD

**Issue by dimpetrop** [BG-Software-LLC/SuperiorSkyblock2#763]
### Minecraft's Version

Pufferfish 1.17.1

### Plugin's Version

1.8.2

### Session Logs

[session_logs (1).zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7617262/session_logs.1.zip)

### Describe the bug

Hopper removal on player islands is not registered, making players unable to place more hoppers

### To Reproduce

Steps to reproduce.
For a hopper limit of 8.

1. Place 8 hoppers 
2. Break 8 hoppers
3. Place 1 hopper

Step 3 outcome should be: "Hopper Placement"
Step 3 outcome is: "Reached limit"

**Comment by OmerBenGera** [comment]
You have a plugin that handles removal of hoppers on its own and conflicts with SSB.

**Comment by OmerBenGera** [comment]
Have you found the plugin?

**Comment by dimpetrop** [comment]
Hi,

Let's close this for now - the issue seems to be resolved after a restart. We haven't been able to reproduce it for some time now.
