### ISSUE TITLE
Issue with chest in valuable block

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#765]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b347

### Session Logs

*

### Describe the bug

I added "chest" into valuable block, but now player with "open_chests" permission can't open them if they don't get access to "valuable block".

But valuable block might be only for breaking, not opening.

### To Reproduce

- add chest to valuable block
- add someone the permission "open chest"
- he can't open it.

- add him "valuable block" perm
- now he can open/break it

**Comment by OmerBenGera** [comment]
Whats the difference between opening chests and taking items from it and breaking it..?

**Comment by WarnDa** [comment]
> Whats the difference between opening chests and taking items from it and breaking it..?

I also got special chests, so I want player be able to open chests but not break them

**Comment by OmerBenGera** [comment]
> > Whats the difference between opening chests and taking items from it and breaking it..?
> 
> I also got special chests, so I want player be able to open chests but not break them

I will look into that, even tho I still dont understand what the difference is
