### ISSUE TITLE
Missions - Registering 1 sugarcane instead of 2

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/SuperiorSkyblock2#766]
### Minecraft's Version

[12:42:57 INFO]: This server is running Paper version git-Paper-386 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e22a1a9)

### Plugin's Version

SuperiorSkyblock2-1.8.2-b382.jar

### Session Logs

[Uploading .session_logs.zip…]()

### Describe the bug

Sugar cane can grow up 2 more blocks and that is in total 3 blocks tall of sugar cane.

When farming an sugar cane, you destroy 1 block of sugar cane and block above that destroyed block destroys too because of gravity in minecraft.

In mission, you get 1 in progress insted of 2.

I used and "BlocksMissions" instead of "FarmingMissions" that you told me in previous issue.

In video, "Statistika" means "Statistics" in my language. And that is only important thing you need to read.

[VIDEO](https://streamable.com/4rituy)

### To Reproduce

Sugar cane farm, showed in video.

**Comment by OmerBenGera** [comment]
BlocksMissions is tracking only blocks that you break, not blocks that are broken due to the block you break.

You are more than welcome to make a PR that changes that.
