### ISSUE TITLE
Missions weight moves your available quests behind your completed ones.

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#767]
### Minecraft's Version

1.17.1

### Plugin's Version

Dev 376

### Session Logs

Not able to provide as its 500MB of logs and crashes when I try to download/upload them.

### Describe the bug

![image](https://user-images.githubusercontent.com/30563757/144179279-cada2717-d001-4dd5-9745-f51a436ca619.png)
As you can see the non completed mission gets sorted to the back when using weight values, it would be awesome if completed missions and non completed read weight and sorted differently somehow.

### To Reproduce

Assign weight values with ur first quests having earlier weight
Complete a few missions
See the sorting

### Additional Information

Ideally this has a negative effect on people who have hundreds of missions as users would have to go through multiple pages to see their new mission.

**Comment by OmerBenGera** [comment]
Fixed in latest build

**Comment by Skizzles** [comment]
Seems some work and some do not @OmerBenGera 
 ![image](https://user-images.githubusercontent.com/30563757/144707377-6be40769-0530-480f-8420-c5a389a89b95.png)
 https://screenshots.skizzles.me/wAnA3/YOfaVORO56.mp4/raw

**Comment by Skizzles** [comment]
https://screenshots.skizzles.me/wAnA3/zusIFIxe70.mp4

you can see the order is messed up here as it should go:
- Making a Composter (Not Completed)

Completed
- Welcome
- Getting Supplies
- Building a Multiblock
- Honestly Screw Multiblocks

**Comment by OmerBenGera** [comment]
Maybe it was completed already?

**Comment by Skizzles** [comment]
> Maybe it was completed already?

Happens even on a fresh island with data reset.

**Comment by OmerBenGera** [comment]
If you re-open the menu, does it fix itself?

**Comment by Skizzles** [comment]
> If you re-open the menu, does it fix itself?

It does not, I still have one where the order is incorrect.

**Comment by Skizzles** [comment]
managed to fix this, missed an option in my file
