### ISSUE TITLE
Citizens holograms (armor stand) bug

### ISSUE THREAD

**Issue by EnZiiK** [BG-Software-LLC/SuperiorSkyblock2#768]
### Minecraft's Version

1.17.1

### Plugin's Version

1.8.2

### Session Logs

I will add this after I came from work..

### Describe the bug

Im using plugin which spawns you npc on island when you create an island.. but when you restart a server holograms disappear from npc.. I though its problem from citizen or plugin what is adding npc itself but after hours of testing I found out its problem with ssb2.. I tested it on BentoBox BSkyBlock and there is no problem with that.. probably SSB2 is messing up with armor stands (holograms from citizens)

### To Reproduce

I just created an island, npc spawns then I just restart my server after that with npc on island I connect back to server and holograms dissapears and never come back only when I do /citizens reload but then after teleport from island and back are holograms again gone..

**Comment by OmerBenGera** [comment]
I doubt its something with SSB, however I will look into it.
Let me know how you create npcs with holograms using Citizens so I can try and replicate it myself.

**Comment by EnZiiK** [comment]
Here is plugin Im using you can look at it https://github.com/aglerr/IslandNPC

**Comment by OmerBenGera** [comment]
Please send me a copy of the jar here.

**Comment by EnZiiK** [comment]
There you go https://easyupload.io/61c9gx

**Comment by OmerBenGera** [comment]
Test latest build, hopefully it's fixed.
It sometimes worked for me, sometimes not, however in like 95% of the times it worked.
Let me know how is it doing on your server.

**Comment by OmerBenGera** [comment]
Have you tested it?

**Comment by EnZiiK** [comment]
Yes, I tested it today.. It was working after first 3 restarts but at 4th holo again disappear.

**Comment by OmerBenGera** [comment]
> Yes, I tested it today.. It was working after first 3 restarts but at 4th holo again disappear.

oof
I'll see what can be done in order to improve it.
At least it's better now...

**Comment by JoshuaPHYT** [comment]
is this fixed?

**Comment by OmerBenGera** [comment]
> is this fixed?

This only happens with Citizens, and as you can see, it is not yet fixed.

**Comment by Davisiiiik** [comment]
I think this could have same cause as #940. Do you have setting `afk-integrations.disable-spawning` set to true?

**Comment by OmerBenGera** [comment]
> I think this could have same cause as #940. Do you have setting `afk-integrations.disable-spawning` set to true?

I didnt have it. However, I will look into it again to make sure that is not the case

**Comment by OmerBenGera** [comment]
@EnZiiK Hey,
I recently fixed a bug when entities were removed when they weren't supposed to, which might fix this issue.
Are you able to replicate the issue using latest dev builds?

**Comment by abyss-xd** [comment]
I regret to tell this to you Omer, but Enzii's last known message was that he was extreamly sick with covid back in February. He never replied after. We tried reaching out to him via his email but he's been gone for 6 months.

**Comment by OmerBenGera** [comment]
> I regret to tell this to you Omer, but Enzii's last known message was that he was extreamly sick with covid back in February. He never replied after. We tried reaching out to him via his email but he's been gone for 6 months.

Oh gosh, I hope he's okay...
I will look into it myself and will update here if I find anything

**Comment by OmerBenGera** [comment]
I am closing this for the time being
If someone encounters a similar issue, please open a new issue
