### ISSUE TITLE
Issue with biome

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#772]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b382

### Describe the bug

When you change your island biome, sometimes it creates an issue and your island become VISUALLY your nether island.

But it's only visual, your island is still there, if you break blocks it's normal block of your normal island.
When you disonnect/reconnect it fixs the visual bug.

### To Reproduce

Change your biome, but there are more informations needed on how it produce, I'm not sure but see below I think I got the issue

### Additional Information

It seems happening : 
- when upgrades are enable
- and then a mob spawn
- so it loads all chunk to check for mobs in them (for limits)

Because with upgrades disabled (so no mob limit) I got no issue.

I got a session.log of the issue (3GB) I can upload and send it to you if needed

**Comment by WarnDa** [comment]
I compressed the session log to be less heavy, here is the link : 
https://mega.nz/file/Fs9GjI7J#dSXUIZ_hevARHIwGivepvDhg-uTUU_wtGeD_gr_axQw

**Comment by OmerBenGera** [comment]
Session logs are not necessary.
Please take a video of the issue.

**Comment by WarnDa** [comment]
https://www.youtube.com/watch?v=PLMUm9U8B1o&list=PL1lFBSIhaRE-0wJWhgOEy51Y_XzpDFheK&index=9&ab_channel=_DraZe

**Comment by OmerBenGera** [comment]
Does it still occur on Paper/Spigot?

**Comment by WarnDa** [comment]
I reproduced it on paper.

So it's exactly what I said : 
- You need nether to be unlocked
- You need to get a lot of blocks into nether (I set a radius of 1000x1000 in my nether and did a //cyl coal_block 1000)
- Then you need to spawn mob
- While mob spawn, change your biome
- Il will bug and show you the nether world.
It's just visual, and when you disconnect/reconnect it fixs the issue

And here you get the issue.
The video above show this.
I can do a full video tutorial if needed

(Edit : sorry I failed the record and we only see 50% of the screen)
https://youtu.be/63KgDns5pE4

**Comment by OmerBenGera** [comment]
Do you have your schematics placed with WorldEdit?

**Comment by OmerBenGera** [comment]
Try not to use WorldEdit, and instead use /fill or something.
Let me know if it still occurs, as I suspect the issue comes from WorldEdit.

**Comment by WarnDa** [comment]
I tried without worldedit, I don't get any issue.
I use worldedit for a plugin that place a farm schematic.

**Comment by OmerBenGera** [comment]
So its an issue with WorldEdit - I cant really do anything in order to fix it.

**Comment by OmerBenGera** [comment]
I am closing this as I can't really do anything with that.
I know that WorldEdit (especially FastAsyncWorldEdit) can break things related to chunk-sections, causing this weird glitch.
