### ISSUE TITLE
ModMod interfence with /v of superior skyblock

### ISSUE THREAD

**Issue by ComboLyfe** [BG-Software-LLC/SuperiorSkyblock2#780]
### Minecraft's Version

[11:57:01 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[Uploading server (1).zip…]()

### Plugin's Version

[11:58:18 INFO]: SuperiorSkyblock2 version 1.8.2
[11:58:18 INFO]: Feature packed Skyblock core.
[11:58:18 INFO]: Website: https://bg-software.com/
[11:58:18 INFO]: Author: Ome_R

### Describe the bug

I added a modmode from songoda (https://songoda.com/marketplace/product/modmode-18-1171-50-summer-sale-staff-mode.667) and it conflicts with something with superiorskyblock. Here is the error I get on console (https://pastebin.com/xFjtSnUk) when I do /v it send me that error or when I try to get out of staff mode.

### To Reproduce

- I join the server
- Staff mode activated even though I said it config to don't
- Do /v or /mod 
- Send the error of the pastebin to the console

### Additional Information

https://pastebin.com/xFjtSnUk

**Comment by OmerBenGera** [comment]
Essentials was triggered as your vanish provider, how is ModMode related to that?

**Comment by ComboLyfe** [comment]
it doesn't let me get out of /v or modmode, when I do either command it sends me that error to console

**Comment by OmerBenGera** [comment]
Does it still occur if you run `/essentials:vanish`?

**Comment by ComboLyfe** [comment]
Yes

**Comment by ComboLyfe** [comment]
if you're on minecraft I can show you. My discord is Cxmbo#7147

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
