### ISSUE TITLE
Making my Server TPS Low

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SuperiorSkyblock2#781]
### Minecraft's Version

[07:54:23 INFO]: This server is running Purpur version git-Purpur-"9a7a4dc" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a7a4dc on ver/1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.8.2

### Describe the bug

I saw my TPS went down to 11-16 then i did aikar flag. 
https://timings.aikar.co/?id=d6842827c6ec4d3590091cee83fcd723
SuperiorSkyblock2 is doing some heavy stuff

### To Reproduce

?

**Comment by OmerBenGera** [comment]
It doesn't look like related to SuperiorSkyblock.
What lags your server is your SuperiorWorld, which makes sense, as this is the world with all the activity on your server.
If you want to find out what exactly causes your TPS to drop, install spark and run `/spark sampler`, wait a few seconds, then `/spark sampler --stop` and send the generated link here.
For now, I am closing this.

**Comment by JoshuaPHYT** [comment]
https://spark.lucko.me/J7QLsmeL37

**Comment by JoshuaPHYT** [comment]
> It doesn't look like related to SuperiorSkyblock. What lags your server is your SuperiorWorld, which makes sense, as this is the world with all the activity on your server. If you want to find out what exactly causes your TPS to drop, install spark and run `/spark sampler`, wait a few seconds, then `/spark sampler --stop` and send the generated link here. For now, I am closing this.

https://spark.lucko.me/J7QLsmeL37

**Comment by OmerBenGera** [comment]
> > It doesn't look like related to SuperiorSkyblock. What lags your server is your SuperiorWorld, which makes sense, as this is the world with all the activity on your server. If you want to find out what exactly causes your TPS to drop, install spark and run `/spark sampler`, wait a few seconds, then `/spark sampler --stop` and send the generated link here. For now, I am closing this.
> 
> https://spark.lucko.me/J7QLsmeL37

Looks fine from SSB's side
