### ISSUE TITLE
No valid schematics

### ISSUE THREAD

**Issue by Mattyb0i** [BG-Software-LLC/SuperiorSkyblock2#785]
### Minecraft's Version

1.8.8 paperspigot

### Plugin's Version

1.8.2

### Describe the bug

I've created a schematic where it only contains one bedrock

Error in log: [https://pastebin.com/em0rNcFg](url)

### To Reproduce

1. Make a schematic where it only contains one bedrock
2. Add the schematic to /plugins/SuperiorSkyblock/schematics
2. Restart your server
3. Done. The server won't start

**Comment by OmerBenGera** [comment]
Dont use WE to create schematics, use the built-in system instead.
Tutorials can be found on our wiki page
