### ISSUE TITLE
SuperVanish support

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/SuperiorSkyblock2#786]
### Minecraft's Version

1.8.8 mSpigot

### Plugin's Version

401

### Describe the bug

The online menebr placeholder doesn't respect players in vanished 

### To Reproduce

Use SuperVanish and go in vanish. Have another account without perms and use the placeholder

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
