### ISSUE TITLE
Issue with detecting worth values of blocks

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#787]
### Minecraft's Version

1.17.1 paper

### Plugin's Version

SuperiorSkyblock2-1.8.2-b401

### Describe the bug

When placing blocks on the island first it counts them until you do a recalc of the island / islands and all value is set to 0. I don't know what causes this but that is what's happening. 

### To Reproduce

place blocks normally or stack blocks with rosestacker on your island. Then recalc the island or /is admin recalc and it returns 0 value. Level still works but doesn't add new blocks to the value.

**Comment by OmerBenGera** [comment]
Run `/is admin debug Action: Block Place` and then run `/is admin recalc <your-name>` - does it print something to screen?

**Comment by Pikaronga** [comment]
![bild](https://user-images.githubusercontent.com/72415100/146595224-23800705-6a0a-48aa-97b1-b07c38d25570.png)

**Comment by Pikaronga** [comment]
it prints 0 value and a high level. even tho i have everything defined in value file. So all the blocks that give level surely have a defined value.

**Comment by Pikaronga** [comment]
Added blocks to the stack. 
[19:07:08 INFO]: [SuperiorSkyblock2] [DEBUG] Action: Block Place, Island: xSwePlayz, Block: DIAMOND_BLOCK:0, Amount: 75

it prints that i added them but doesn't count any value at all.

**Comment by OmerBenGera** [comment]
When you hold a diamond block in your hand and run `/is value`, does it show the correct worth value?
It seems like it counts the blocks correctly, however there might be an issue with detection of worth values.

**Comment by Pikaronga** [comment]
It gives "The block Diamond Block worth 800. "

>

**Comment by OmerBenGera** [comment]
> It gives "The block Diamond Block worth 800. "
> 
> >

I see.
Try running `/is admin debug Action: Get Worth` and then `/is admin recalc <island-name>`, let me know if something is printed to console.

**Comment by Pikaronga** [comment]
https://pastebin.com/6PwTgXxC

"Your island worth is 0 [Level 30,690]"

**Comment by OmerBenGera** [comment]
It looks like it detects the worth value of the Diamond Blocks from your prices provider.
Does that sound correct?

**Comment by Pikaronga** [comment]
> f the Diamond Blocks from your prices provider.
> Does that sound correct?

Yes. It gets the worth from Shopgui+. But fails to calculate the worth of the island still.

**Comment by OmerBenGera** [comment]
> > f the Diamond Blocks from your prices provider.
> > Does that sound correct?
> 
> Yes. It gets the worth from Shopgui+. But fails to calculate the worth of the island still.

I see.
Mind updating to latest dev build and then run `/is admin debug Action: Get Worth`, `/is admin recalc <player-name>`
I added more info to the debug messages so hopefully it gives us a clue on what is going on there.
Sorry for all of that mess, hopefully will be fixed soon.

**Comment by Pikaronga** [comment]
https://pastebin.com/4s3wkMCt

okay np.

**Comment by OmerBenGera** [comment]
> https://pastebin.com/4s3wkMCt
> 
> okay np.

Seems like the worth is calculated correctly.
After you do `/is admin recalc`, run `/is admin show` and show me what it returned.

**Comment by Pikaronga** [comment]
![bild](https://user-images.githubusercontent.com/72415100/146687637-cd7472ed-b963-4bf4-b122-cfbd84816fad.png)

0 worth. even tho i have several stacks with diamond blocks.

**Comment by OmerBenGera** [comment]
You have a worth bonus of -1.7M...
Of course you have 0 worth.
Why did you set this low bonus? Is there a reason for it?

**Comment by Pikaronga** [comment]
> You have a worth bonus of -1.7M... Of course you have 0 worth. Why did you set this low bonus? Is there a reason for it?

i put the "schematic-offset: true" nothing else. So if that is the problem then it's the plugins fault for not being able to count blocks.

**Comment by Pikaronga** [comment]
and as i said this only happens after a recalc. So there is something with the recalc function that is broken. It seems to add some kinda negative bonus that adds ur value to 0 after a recalc. it's super wierd

**Comment by OmerBenGera** [comment]
Try creating a new island, then check your worth bonus.
Check if its still that high.

**Comment by Pikaronga** [comment]
> Try creating a new island, then check your worth bonus. Check if its still that high.

after recalculating it is that high. not before

**Comment by OmerBenGera** [comment]
> > Try creating a new island, then check your worth bonus. Check if its still that high.
> 
> after recalculating it is that high. not before

Calculation doesnt affect worth bonus.

**Comment by Pikaronga** [comment]
> 

well i don't know but that is what's happening

**Comment by Pikaronga** [comment]
Like i can't explain more than what i am experiencing. This is what's happening so there has to be somethin fucked with it.

**Comment by OmerBenGera** [comment]
Try running `/is admin debug Action: Set Bonus Worth` - it should print when the bonus-worth is changing.
Then, again, run `/is admin recalc <your island>` and check if something is printed to your console.

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by Pikaronga** [comment]
> Have you tried it?

Sorry for not responding! Yes i have tried it and i can't replicate it with the newer dev builds.
