### ISSUE TITLE
Big slime didn't split.

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#789]
### Minecraft's Version

Paper 1.12.2.

### Plugin's Version

Latest stable version of SS2 1.8.2 26/11/2021.
+
WildStacker

### Describe the bug

Slime didn't split themself when they got killed.

### To Reproduce

With WildStacker :

When big slime got killed, he don't split himself on medium size on SuperiorWorld.

Exemple : https://gyazo.com/250bba798a9683ff258678de230a7446

On other world not manage by Superior, i see the medium size slime but he instantly despawn.

Exemple : https://gyazo.com/4a433f4f73c2c13398e6dbf8ca15b5d5

When i remove WildStacker :

When big slime got killed, he don't split himself on medium size on SuperiorWorld.

Exemple : https://gyazo.com/741f8eb273d2d7388846a9a93b304bf2

On other world not manage by Superior, don't have this issue : 

Exemple : https://gyazo.com/03cd6db836347a4166f83569b6797d9e

**Comment by OmerBenGera** [comment]
H9w is it related to SuperiorSkyblock?

**Comment by SwartZCoding** [comment]
> 

On SuperiorWorld he don't respawn, but on other map it respawn. After my call with CustomEntity (Support on your discord), he suggest me to open a issues on SS2 repository.

**Comment by OmerBenGera** [comment]
> > 
> 
> On SuperiorWorld he don't respawn, but on other map it respawn. After my call with CustomEntity (Support on your discord), he suggest me to open a issues on SS2 repository.

Check if it happens on a server where you only have SSB installed using default files.

**Comment by OmerBenGera** [comment]
I tested it using `git-Paper-1618 (MC: 1.12.2)` and it works fine.
Maybe you have some kind of setting that disables slime splits for that world?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
I am closing this due to lack of response.
I believe it's something else causing this behavior to occur.
If it turns to be an issue with the plugin again, let me know by commenting here.
