### ISSUE TITLE
Block values dont get removed if you remove them from worth.yml

### ISSUE THREAD

**Issue by lunaiskey** [BG-Software-LLC/SuperiorSkyblock2#790]
### Minecraft's Version

This server is running Paper version git-Paper-99 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: cf621c5)

### Plugin's Version

1.8.2 #405 dev

### Describe the bug

When using "/island admin reload" if you remove an entry from worth.yml its worth doesnt get removed. if you keep the entry and change its worth then it updates just fine.

### To Reproduce

Open worth.yml and remove any entry, completely delete the line. (eg: DIRT: 10)
/island admin reload
break or place the block and the island worth is updated using the old value from before the reload.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
