### ISSUE TITLE
Island Creation

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/SuperiorSkyblock2#792]
### Minecraft's Version

1.16.5 Paper

### Plugin's Version

406

### Describe the bug

Error on island creation

**https://pastebin.com/x4WwBeYZ**

### To Reproduce

I have created a custom schematic and have the normal schematic, error occurs when using both

**Comment by YouSeeMeRunning2** [comment]
Just figured it out, the notes are pretty unclear :P

**Comment by OmerBenGera** [comment]
Any issues related to the nashorn engine are not solvable on plugin's side.
You can install an external plugin that provides nashorn engine and delete the nashorn engine module of the plugin.
