### ISSUE TITLE
Too Many TPS Drops

### ISSUE THREAD

**Issue by pixelnw** [BG-Software-LLC/SuperiorSkyblock2#793]
### Minecraft's Version

flamepaper 1.8.8

### Plugin's Version

1.8.2 (latest)

### Describe the bug

Since the day I have been using SuperiorSkyblock, there has been a constant decrease in tps values. When I look at the Timings report, it seems that there are many delays related to SuperiorSkyblock.

Timings report: https://timings.aikar.co/?id=724ec6db50684433a99dea236379f84c

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Please upload your config to pastebin and send it here.
The timings website isn't responding for me right now, I will look at the timings later.

**Comment by OmerBenGera** [comment]
Also, from what I can see, there is no lag from SuperiorSkyblock.
The main lag source is the world of islands, however this is not related to the plugin in any way.
Mind taking a spark profiler and upload the results here as well?

**Comment by pixelnw** [comment]
> Also, from what I can see, there is no lag from SuperiorSkyblock. The main lag source is the world of islands, however this is not related to the plugin in any way. Mind taking a spark profiler and upload the results here as well?

Spark Profile: https://spark.lucko.me/Ktmh2OwLY2
Config: https://www.toptal.com/developers/hastebin/tivevepote.yaml

**Comment by OmerBenGera** [comment]
> > Also, from what I can see, there is no lag from SuperiorSkyblock. The main lag source is the world of islands, however this is not related to the plugin in any way. Mind taking a spark profiler and upload the results here as well?
> 
> Spark Profile: https://spark.lucko.me/Ktmh2OwLY2 Config: https://www.toptal.com/developers/hastebin/tivevepote.yaml

I don't see anything wrong there.
Maybe you saw something that I missed that you want to point out?

**Comment by Skizzles** [comment]
@pixelnw 

A lot of the lag based off your timings seems to be from World Save and other sources. I recommend following this guide to optimizing your server:
https://www.spigotmc.org/threads/guide-server-optimization%E2%9A%A1.283181/

**Comment by OmerBenGera** [comment]
I am closing this as it doesn't seem like to be related to the plugin itself
