### ISSUE TITLE
Error Spam

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#794]
### Minecraft's Version

paper_1.12.2.jar

### Plugin's Version

SuperiorSkyblock2 version 1.8.2.415

### Describe the bug

https://pastebin.com/F0SaFpm6

### To Reproduce

startup

**Comment by OmerBenGera** [comment]
Weird. Mind looking at your database and find which island doesn't have it's block counts as an json array?
You are not the first one to have this, so I want to see how the data looks like so I can add a parser for it as well.
Probably and old format from one of the previous database versions.

**Comment by Superalex0102** [comment]
> Weird. Mind looking at your database and find which island doesn't have it's block counts as an json array? You are not the first one to have this, so I want to see how the data looks like so I can add a parser for it as well. Probably and old format from one of the previous database versions.

A lot of them are not in json format

![image](https://user-images.githubusercontent.com/41546701/147384413-f811f920-7255-4aa0-b8d7-49c1a6199f7d.png)

**Comment by Superalex0102** [comment]
Same for dirtychunks,

**Comment by OmerBenGera** [comment]
Send me an example of block counts and an example of dirty chunks via pastebin and I will fix it.

**Comment by Superalex0102** [comment]
block_counts: https://pastebin.com/KinVy9UD
dirty_chunks: https://pastebin.com/4Tyz6Dqn

**Comment by OmerBenGera** [comment]
I will release a fix soon.
Just so you know, this error will get some data to be gone, however it's not something that important and mainly used for optimizations - you should be good.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
Should also properly convert the data from old versions from now on.
