### ISSUE TITLE
issue with islands

### ISSUE THREAD

**Issue by Pro-Nil** [BG-Software-LLC/SuperiorSkyblock2#797]
### Minecraft's Version

Paper 1.16.5

### Plugin's Version

SSB2 1.8.2

### Describe the bug

Hey  there , I am having a issue on my server , when I am creating the island , it shows that , island created adn I can access my island too but whenever I restart my server , I cant interact with my island and it says I have no island .

Only thing I can see on console , which might be related to this :
[19:19:07 INFO]: [SuperiorSkyblock2] Changing UUID of Pro_Nil to a06942c8-8411-34b3-8d1d-1ace2b2a2c8b

Things I have tried :
Tried changing versions of ssb2
Tried with Sqlite as well as mysql 
Tried on a server only with SSB2

Informations : 
Current SSB2 version : 1.8.2
Java version : 11
Server version : 1.16.5

### To Reproduce

Already mentioned everything in Describe THe bug

**Comment by OmerBenGera** [comment]
Update SSB to latest dev build, let me know if it's better.

**Comment by Pro-Nil** [comment]
No , didn't work , same issue

**Comment by Superalex0102** [comment]
I also have this issue

**Comment by OmerBenGera** [comment]
> No , didn't work , same issue

What's causing your UUID to change?
It's not something that should occur.

**Comment by Pro-Nil** [comment]
What's causing your UUID to change?

I have the same question

Well , I have no plugin which might alter uuid .

Only thing regarding uuid change on console :
[19:19:07 INFO]: [SuperiorSkyblock2] Changing UUID of Pro_Nil to a06942c8-8411-34b3-8d1d-1ace2b2a2c8b

**Comment by OmerBenGera** [comment]
> What's causing your UUID to change?
> 
> I have the same question
> 
> Well , I have no plugin which might alter uuid .
> 
> Only thing regarding uuid change on console : [19:19:07 INFO]: [SuperiorSkyblock2] Changing UUID of Pro_Nil to a06942c8-8411-34b3-8d1d-1ace2b2a2c8b

Your server is in offline mode or something and it causes your UUID to change...
You must have a login plugin or something like that

**Comment by Pro-Nil** [comment]
Well , no , this is just a test server , where I am making the skyblock server . It is in offline mode , but it has no login plugins

**Comment by OmerBenGera** [comment]
> Well , no , this is just a test server , where I am making the skyblock server . It is in offline mode , but it has no login plugins

Every time you login to the server it prints this message..?

**Comment by Skizzles** [comment]
@Pro-Nil 

It may be useful to provide a plugin list so we can see what may be causing the issue. Could you provide one please?

**Comment by Pro-Nil** [comment]
> 

yea , it prints the message , when I join the server after a restart

**Comment by Pro-Nil** [comment]
> @Pro-Nil
> 
> It may be useful to provide a plugin list so we can see what may be causing the issue. Could you provide one please?

![image](https://user-images.githubusercontent.com/87724453/147596580-893572dc-a60e-4c8e-9412-66d291a0c332.png)

**Comment by Skizzles** [comment]
> > @Pro-Nil
> > It may be useful to provide a plugin list so we can see what may be causing the issue. Could you provide one please?
> 
> ![image](https://user-images.githubusercontent.com/87724453/147596580-893572dc-a60e-4c8e-9412-66d291a0c332.png)

I would try it with just SSB installed as you have a lot of plugins there that could be causing an issue. Or try removing some plugins one at a time to find the one causing the issue.

**Comment by Pro-Nil** [comment]
> 

I had already tried that

**Comment by OmerBenGera** [comment]
> > 
> 
> I had already tried that

Look in your database for your column and check what uuid is there.
Then, after you login and get that message, check if your uuid was changed in the database.

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
I tried changing my UUID and it seems to migrate data fine.

**Comment by OmerBenGera** [comment]
Any news regarding this?
