### ISSUE TITLE
SkinRestorer player heads not working

### ISSUE THREAD

**Issue by DGabriel13** [BG-Software-LLC/SuperiorSkyblock2#801]
### Minecraft's Version

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.8.2.412
SkinsRestorer version 14.1.10

### Describe the bug

When I use a placeholder **%superior_player_texture%** to show the heads of players using SkinRestorer, it just doesn't show

![image](https://user-images.githubusercontent.com/58773688/147420015-add7d85e-3026-4f97-9b61-ab99186912f3.png)

### To Reproduce

It has to have the **SkinsRestorer** version **14.1.10** plugin and I think it also needs the **PlaceHolderAPI** for the placeholder to work.

Then add in the control-panel file **skull: '%superior_player_texture%'** in Island Members like this:

Then turn on the server and use **/is panel** to check if the head texture worked

### Additional Information

Image config 
![image](https://user-images.githubusercontent.com/58773688/147420072-14854050-2782-4b65-aba8-c3935dedc7f6.png)

Config pastebin
https://pastebin.com/qMW9iifC

**Comment by OmerBenGera** [comment]
Do skulls work on other menus (for example, top-islands menu)?

**Comment by DGabriel13** [comment]
apparently not
![image](https://user-images.githubusercontent.com/58773688/147420445-051ddac4-309d-4a50-8690-946b61bba508.png)

**Comment by OmerBenGera** [comment]
I will look into that and get back to you.

**Comment by DGabriel13** [comment]
ok

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
Does a restart help?

**Comment by DGabriel13** [comment]
this is weird, i will restart help
