### ISSUE TITLE
Valuable Block break permission

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#804]
### Minecraft's Version

1.12.2

### Plugin's Version

b421

### Describe the bug

Hello,
I've set this valuable blocks (it works before). Now if i stack (Stacked block feature) any block of this list i can get block while I don't have permission to do that.
https://pics.revolis.fr/2021/12/27/19-22_bDqX.png

### To Reproduce

Set valuable block, place stacked block of one of this list, /is coop someone without valuable block break permission.

**Comment by OmerBenGera** [comment]
I think it is because I removed the restriction of interacting with valuable blocks.
I will look into that tho.

**Comment by nivcoo** [comment]
Thx

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
