### ISSUE TITLE
Blocklimit of Spawner is not working correctly

### ISSUE THREAD

**Issue by aaa8881** [BG-Software-LLC/SuperiorSkyblock2#808]
### Minecraft's Version

paper 1.17

### Plugin's Version

latest

### Describe the bug

Block limit Type Spawner is not correctly recognized by SSB. 

As we've discussed in the discord , 

`/is admin beug Action:BLOCK_PLACE` does not print debug message on Spawners. 

While, it is weird, that sometimes placing spawner does get block when

`island.setBlockLimit(Key.of(new ItemStack(Material.SPAWNER), count);` which shouldn't be done, but happened anyways. 
`island.setBlockLimit(Key.of("SPAWNER"), spawner);` doesn't do any job 

### To Reproduce

set spawner as the block limit

**Comment by OmerBenGera** [comment]
You should run `/is admin debug Action: Block Place`, not what you wrote.
Also, you should use `Key.of("SPAWNER")` and not using an ItemStack.

Do you have any plugin that handles spawners?

**Comment by aaa8881** [comment]
I've done the correct command `/is admin debug Action: Block Place`  , just copy pasted wrong one from discord chat history. thought u remember the issue. 

Yes, I've done Key.of("SPANWER") later.

Yes I have RoseStacker , but disabled at testing.

**Comment by OmerBenGera** [comment]
> I've done the correct command `/is admin debug Action: Block Place` , just copy pasted wrong one from discord chat history. thought u remember the issue.
> 
> Yes, I've done Key.of("SPANWER") later.
> 
> Yes I have RoseStacker , but disabled at testing.

Try it with RoseStacker, let me know if it works.

**Comment by OmerBenGera** [comment]
When you run `/is admin show` on your island, do you see there the spawner's limit?

**Comment by OmerBenGera** [comment]
Any news regarding this?
