### ISSUE TITLE
Mobs still spawn with 'mob spawning off' under /is settings

### ISSUE THREAD

**Issue by ReganWant** [BG-Software-LLC/SuperiorSkyblock2#81]
Mobs are still spawning on the island naturally despite the setting being set to off. No errors in console. Using dev build 68. however this issue was present in dev build 62 & 60, I have tried all three.

**Comment by OmerBenGera** [comment]
There are 4 types of mob spawning - natural animals spawn, natural monster spawn, spawner animals spawn and spawner monster spawn. Do you have the correct setting disabled?

**Comment by ReganWant** [comment]
I have the Natural Monster spawn disabled and they still spawn.

I've just tried and disabled all 4, and monsters still spawn.

**Comment by OmerBenGera** [comment]
> 
> 
> I have the Natural Monster spawn disabled and they still spawn.
> 
> I've just tried and disabled all 4, and monsters still spawn.

How do they spawn? What version of minecraft are you using? What version of SuperiorSkyblock are you using?

**Comment by ReganWant** [comment]
Dev build 68.
And I am using Spigot 1.16.5

**Comment by OmerBenGera** [comment]
I'll take a look at that

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue, maybe you have another plugin that handles mob spawning?

**Comment by OmerBenGera** [comment]
Any news regarding this?
