### ISSUE TITLE
SkinRestorer does not work with placeholder

### ISSUE THREAD

**Issue by N1kyZ** [BG-Software-LLC/SuperiorSkyblock2#812]
### Minecraft's Version

This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.8.3
SkinsRestorer version 14.1.10

### Describe the bug

**%superior_player_texture%** placeholder is not working in SSB menus. I tested using Paper 1.12.2 and Purpur 1.16.5 and they both have the same problem, I used an original account to test it and I changed its skin but in the menu I was still using the original skin and if I do it with a Cracked account she just keeps Steve's head

Replacing the skin with skinrestorer with the original account:
![image](https://user-images.githubusercontent.com/58773688/147709545-ee4dab05-05ba-4d3f-9686-8c8e8605c0fa.png)

Changing the skin with skinrestorer with the Cracked account:
![image](https://user-images.githubusercontent.com/58773688/147709721-a1744555-fd1e-4d4e-ae6b-7b3da15f5c0c.png)

### To Reproduce

Using the necessary plugins which is SkinRestorer and SSB, replace some menu item with
![image](https://user-images.githubusercontent.com/58773688/147710002-a2638443-9b3a-4606-a70c-821e465ee03a.png)

then turn on the server and check the menu you changed, then change your account skin using the skinrestorer and see if the menu changes as well. I recommend using paper 1.12.2 so it might not make any difference

### Additional Information

Config image
![image](https://user-images.githubusercontent.com/58773688/147709884-55cdeaa2-35e0-4eaa-bd0f-16dd34e20f78.png)

Config in pastebin
https://pastebin.com/G2nUMTmr

plugins used
![image](https://user-images.githubusercontent.com/58773688/147710157-e28d392d-c36f-4187-a679-22de052ca7e5.png)

NOTE: I used it with and without protocollib but nothing has changed so you can ignore
Goodnight ☕

Edit: no console error and happens with other SSB menus

**Comment by OmerBenGera** [comment]
Next time, do not open a new issue when you already have one opened.

**Comment by OmerBenGera** [comment]
Try latest dev build, let me know if it's better.

**Comment by N1kyZ** [comment]
Sorry for my mistake, and it's working now :)
