### ISSUE TITLE
Can't create island with ASWM

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#815]
### Minecraft's Version

This server is running Paper version git-Paper-398 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 244b392 on ver/1.17.1)

You are 6 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Purpur-"08dd6c7" (MC: 1.17.1)

### Plugin's Version

SuperiorSkyblock2 version 1.8.3.421
Feature packed Skyblock core.
Website: https://bg-software.com/
Author: Ome_R

SuperiorSkyblock-ASWM version 1.0.4
Authors: Ome_R and aglerr

### Describe the bug

When creating an island, it says "processing your request" and never finishes. When doing /is go, it says there are no safe blocks.

### To Reproduce

1. Have ASWM, SS2, and SS2-ASWM addon
2. Start the server and do /is create

### Additional Information

![image](https://user-images.githubusercontent.com/65089425/147833001-66c8ed9d-ef78-4dab-98f5-d7f0ce8f6d3f.png)
![image](https://user-images.githubusercontent.com/65089425/147833005-7fc44807-2d84-4f9b-9588-109045281a78.png)

**Comment by OmerBenGera** [comment]
This is not related to the plugin.
If it works fine on vanilla game, then the issue is with the plugin that handles the ASWM integration.
