### ISSUE TITLE
Default WorldBorder settings doesn't work

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#821]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b444

### Describe the bug

I got 
> # Should world borders be enabled by default for new players?
default-world-border: false

In config, but when player create an island, worldborder is ON

### To Reproduce

- set default-world-border: false
- create an island

**Comment by OmerBenGera** [comment]
A new player should join to the server for the first time so his borders will be disabled by default.
If players already joined, their personal settings are overriding this feature (so if it was enabled by default, it will be enabled for your players that already joined).
This has nothing to do with creation of islands or anything like that.
