### ISSUE TITLE
Close bypass do not work

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#822]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b444

### Describe the bug

Close bypass permission doesn't work since new version.
Even with OP and "*" permission (using luckperms) I can't access a closed island without the "/is admin bypass" turned ON.

I used before the b385 and it worked well

I also got theses permission : 
![image](https://user-images.githubusercontent.com/31826333/148391613-14d086a1-4dfd-421d-b95a-6e9d50ee8b9c.png)
(I also tried superior.admin.close.bypass)
And I don't want to give the bypass to my moderator, I just want them to access closed islands.

### To Reproduce

try to access a closed island without bypass ON

### Additional Information

worked well on b385

**Comment by OmerBenGera** [comment]
Try without LuckPerms, let me know if it works.

**Comment by WarnDa** [comment]
![image](https://user-images.githubusercontent.com/31826333/148459161-a6934631-c6d8-415c-a484-2b3e43f7da13.png)
As Opped, on paper 1.16.5, without LuckPerms, still the same issue

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/31826333/148459161-a6934631-c6d8-415c-a484-2b3e43f7da13.png) As Opped, on paper 1.16.5, without LuckPerms, still the same issue

You must have a permissions system and directly give yourself the permission.
The plugin checks for the permission without OP status.

**Comment by OmerBenGera** [comment]
There seems to be an issue with detection of permissions in LuckPerms.
I am looking into it and will release a fix soon.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
