### ISSUE TITLE
Generator - level

### ISSUE THREAD

**Issue by RequaizeN** [BG-Software-LLC/SuperiorSkyblock2#824]
### Minecraft's Version

1.8.8 TacoSpigot

### Plugin's Version

SuperiorSkyblock2-1.8.3-b450

### Describe the bug

When the blocks from the generator are broken, the island level decreases.

### To Reproduce

When the blocks from the generator are broken, the island level decreases.

**Comment by OmerBenGera** [comment]
Are you using the built-in generator system?

**Comment by RequaizeN** [comment]
Yes, I am not using any extra plugin.

**Comment by OmerBenGera** [comment]
When a block of the generator generates, it gives you levels. Then, when you break it, you'll lose it.
Is that what you're referring to?

**Comment by RequaizeN** [comment]
No. I guess the blocks created by the generator do not level and when those blocks are broken, the level of the island decreases.

**Comment by OmerBenGera** [comment]
> No. I guess the blocks created by the generator do not level and when those blocks are broken, the level of the island decreases.

Blocks generated by the plugin will increase your worth value.
Run `/is admin debug Action: Generate Block` and let a block generate from a generator. Is anything printed to console?

**Comment by RequaizeN** [comment]
[debug.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7830817/debug.txt)

**Comment by OmerBenGera** [comment]
You enabled every debug message of the plugin.
Enable only the ones related to the generator by executing the command above.

**Comment by RequaizeN** [comment]
[22:19:00] [Server thread/INFO]: [SuperiorSkyblock2] [DEBUG] Action: Generate Block, Island: RequaizeN, Block: STONE:0
[22:19:01] [Server thread/INFO]: [SuperiorSkyblock2] [DEBUG] Action: Generate Block, Island: RequaizeN, Block: STONE:0
[22:19:04] [Server thread/INFO]: [SuperiorSkyblock2] [DEBUG] Action: Generate Block, Island: RequaizeN, Block: STONE:0
[22:19:05] [Server thread/INFO]: [SuperiorSkyblock2] [DEBUG] Action: Generate Block, Island: RequaizeN, Block: COAL_ORE:0
[22:19:05] [Server thread/INFO]: [SuperiorSkyblock2] [DEBUG] Action: Generate Block, Island: umut, Block: COAL_ORE:0
[22:19:05] [Server thread/INFO]: [SuperiorSkyblock2] [DEBUG] Action: Generate Block, Island: Conquer, Block: STONE:0

No error appears.

**Comment by RequaizeN** [comment]
You can check the "Level:" section in the Scoreboard.
https://www.youtube.com/watch?v=SVfGvIVwNg8
I think it gets fixed again when you use the /is level command. (I'm not sure.)

**Comment by OmerBenGera** [comment]
Try running `/is admin debug Action: Block Place` and then break the generator blocks again.
Is there anything printed to console?

**Comment by RequaizeN** [comment]
It gives output that blocks such as coal, stone are broken, but It does not give an output that the broken cobblestone has been placed.

**Comment by OmerBenGera** [comment]
> It gives output that blocks such as coal, stone are broken, but It does not give an output that the broken cobblestone has been placed.

`Block Place` messages will not send any output on broken blocks, only on blocks that were placed.
Does cobblestone have a worth value?

**Comment by OmerBenGera** [comment]
Any news regarding this?
