### ISSUE TITLE
Database conversion error

### ISSUE THREAD

**Issue by JShin39** [BG-Software-LLC/SuperiorSkyblock2#825]
### Minecraft's Version

git-Paper-137 (MC:1.17.1)

### Plugin's Version

SuperiorSkyblock2-1.8.3 Stable

### Describe the bug

When upgrading the plugin, it gives a data conversion error and server crashes.

### To Reproduce

When upgrading the plugin jar and restarting the server.

### Additional Information

https://pastebin.com/VuU2PDB7

**Comment by OmerBenGera** [comment]
Use latest dev build, this issue should be fixed already.
