### ISSUE TITLE
Islands reset on server reboot.

### ISSUE THREAD

**Issue by SwartZCoding** [BG-Software-LLC/SuperiorSkyblock2#826]
### Minecraft's Version

1.16.5 Purpur Spigot.
Link to download this paper : https://www.mediafire.com/file/q8y15g0ukjglvse/paper.jar/file

### Plugin's Version

SuperiorSkyblock2 version 1.8.3

### Describe the bug

Nothing to describe, all in the title of this issues.

When i create an island, stop my server and reboot it, i lost my island and i need to recreate one.

### To Reproduce

Setup a MySql database. Start your server. 

Create an island, stop my server and reboot it, i lost my island and i need to recreate one.

### Additional Information

My server is only premium.

On my spigot.yml : Bungeecord: true
on my server.properties : online-mode: false

But i don't know why, SSB try to change my uuid on join. (But it's the same). Maybe an issue here ?

https://gyazo.com/15607c391f6a468e33f1cce709cb2f14

**Comment by OmerBenGera** [comment]
SSB doesn't change your UUID. the UUID saved in the database and the UUID you joined to the server are not the same.
Find what causes it and report back.

**Comment by OmerBenGera** [comment]
Maybe you had a database, and then you connected your server to Bungeecord, which may have lead to your UUID to change.
Have you tried to replicate the issue with a new database file?

**Comment by SwartZCoding** [comment]
> SSB doesn't change your UUID. the UUID saved in the database and the UUID you joined to the server are not the same. Find what causes it and report back.

Look my screen, UUID is exactly the same ^^. I already try to drop 100% of SSB database & recreate one. Same issues.

**Comment by OmerBenGera** [comment]
Weird.
I will look into that.

**Comment by SwartZCoding** [comment]
On localhost without Bungeecord, it's works. But my setup on prod is good ...

**Comment by OmerBenGera** [comment]
> On localhost without Bungeecord, it's works. But my setup on prod is good ...

Does it happen on Bungeecord on your localhost?

**Comment by SwartZCoding** [comment]
> > On localhost without Bungeecord, it's works. But my setup on prod is good ...
> 
> Does it happen on Bungeecord on your localhost?

It's work too ... I don't understand.

**Comment by SwartZCoding** [comment]
Ok, i think i just identify the fix for this issue, if i'm sure it's that, i share here the solution.

**Comment by SwartZCoding** [comment]
Ok to up this issues, if you have the same problem, and if you use LuckPerms, sometimes Luckperms change UUID for an unknow reason. I just clear my luckperm & clear SSB database and now, it's perfectly work. (I up this issues when i'm sure that's the correct issues ^^)

**Comment by OmerBenGera** [comment]
Weird...
I am closing this, if it happens again lmk.
