### ISSUE TITLE
Island warps privacity is resetting in each daily restart

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/SuperiorSkyblock2#828]
### Minecraft's Version

[07:00:19 INFO]: This server is running CraftBukkit version  (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Paper spigot

### Plugin's Version

Latest dev build (**SuperiorSkyblock2-1.8.3-b453.jar**)

### Describe the bug

On old version was working, but now when you have an island warp on public, (and by default island warps are private on config.yml), after a daily restart it comes again to private, and same if you've by default on public and you change island warp to private, it comes public again after a server restart.

### To Reproduce

Just changing your island warp to public (while having it on private by default on config.yml), and then restart your server

(I use SQl database, not MySQL)

**Comment by SwartZCoding** [comment]
I have the same issues on 1.12.2 (with latest stable build) with IS perm & warp, all restart, some peoples report me, they lost their configurations of is permissions & lost their warp.

**Comment by OmerBenGera** [comment]
> I have the same issues on 1.12.2 (with latest stable build) with IS perm & warp, all restart, some peoples report me, they lost their configurations of is permissions & lost their warp.

Update to latest dev build. If it still occurs, update me here.

**Comment by SwartZCoding** [comment]
> 

I never change my plugin version on production mode sorry. But i can try this on dev let me check ^^.

**Comment by OmerBenGera** [comment]
> > 
> 
> I never change my plugin version on production mode sorry. But i can try this on dev let me check ^^.

Unless you dont update, I cant help you.

**Comment by WarnDa** [comment]
> > I have the same issues on 1.12.2 (with latest stable build) with IS perm & warp, all restart, some peoples report me, they lost their configurations of is permissions & lost their warp.
> 
> Update to latest dev build. If it still occurs, update me here.

It still occur on latest dev build, I opened another issue (as I didn't see this one)

**Comment by OmerBenGera** [comment]
Lets keep this ticket related only to reset of warp status.

**Comment by OmerBenGera** [comment]
Should be fixed on latest dev build, let me know if it works.

**Comment by OmerBenGera** [comment]
Closing this for now
If the issue still occurs, let me know by replying here.
