### ISSUE TITLE
is admin setupgrade command does not work

### ISSUE THREAD

**Issue by RequaizeN** [BG-Software-LLC/SuperiorSkyblock2#829]
### Minecraft's Version

1.8.8 tacospigot

### Plugin's Version

SuperiorSkyblock2-1.8.3-b453

### Describe the bug

The /is admin setupgrade command does not work in SuperiorSkyblock2-1.8.3-b453
It was running on version SuperiorSkyblock2-1.8-b337.

### To Reproduce

The /is admin setupgrade command does not work in SuperiorSkyblock2-1.8.3-b453
It was running on version SuperiorSkyblock2-1.8-b337.

**Comment by KaanSuch** [comment]
I am having the same problem.

**Comment by Skizzles** [comment]
Referenced here
#827
