### ISSUE TITLE
Ghast Fireballs setting also effects Blaze

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#836]
### Minecraft's Version

1.17.1 dev purpur 1428

### Plugin's Version

dev 444

### Describe the bug

Ghast fireballs setting effects blaze as well

### To Reproduce

Turn off ghast fireball setting, see people not take any damage from blazes

### Additional Information

https://screenshots.skizzles.me/wAnA3/ReQUwODe94.mp4

Ideally it would be great to have these as different settings or have this corrected.

**Comment by OmerBenGera** [comment]
I am not sure if its possible to prevent only ghasts, as they use the same entity.
I will look into it tho

**Comment by OmerBenGera** [comment]
Let me know if it's fixed in latest build

**Comment by Skizzles** [comment]
@OmerBenGera Confirmed resolved, closing for you!
