### ISSUE TITLE
Dupe glitch with lava in generator and slimefun

### ISSUE THREAD

**Issue by abhisantos** [BG-Software-LLC/SuperiorSkyblock2#837]
### Minecraft's Version

Paper Spigot 1.18

### Plugin's Version

Version: 1.7.0-DEVb239

### Describe the bug

You can dupe (duplicate) slimefun items with the superior skyblock generator system using lava.
As shown in this video: https://www.youtube.com/watch?v=a-FR9ZxGgxA

I opened am issue on Slimefun's github and they said it's a superior skyblock's generator issue, here is the link to the issue opened there https://github.com/Slimefun/Slimefun4/issues/3418

### To Reproduce

As shown in this video: https://www.youtube.com/watch?v=a-FR9ZxGgxA

### Additional Information

Please refer to this issue if needed https://github.com/Slimefun/Slimefun4/issues/3418

**Comment by Skizzles** [comment]
@abhisantos By looking at this video, it seems the generator puts a block where the slimefun cargo node is and when the block is broken its still there.

I don't see there being more than one cargo node? Can you provide a better explanation of how to reproduce this issue as I can't tell by your video.

**Comment by abhisantos** [comment]
> In the video you can see how it's duplicating, the player recording the video is a staff and he looks at the other's player inventory, there you can see that the slimefun item is duplicated.

**Comment by OmerBenGera** [comment]
Slimefun should make sure that the broken blocks is also of the same type they suspect it to be.
Besides that, I am also gonna fix it on my end, as it makes no sense for the generated block to override existing blocks in the world, which hopefully will fix the issue as well.

**Comment by OmerBenGera** [comment]
Let me know if the bug is fixed on latest dev build

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know by replying here
