### ISSUE TITLE
Dupe issue with "setmobdrops" and WildStacker

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#839]
### Minecraft's Version

1.12.2

### Plugin's Version

b453

### Describe the bug

Hello, we have again the issue when we drop something with mobs drops set to 2 on the ground with stacked zombies. Look the video https://cdn.discordapp.com/attachments/930934317457219686/930935977730539560/2022-01-12_22-25-53.mp4

Previous solved issue : https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/540

### To Reproduce

Install WS and SSB2
Set mobs drop to 2
Give stackable item to stacked Zombie
Kill stacked zombie and see the result

**Comment by Skizzles** [comment]
@nivcoo In the future please attach videos directly to Github Issues as most people will not want to download a video to view it. I am marking this as Unconfirmed as I can't reproduce the issue on my end and will wait for Omer to be available to respond.

**Comment by nivcoo** [comment]
Yes sorry for the video i will do that

**Comment by nivcoo** [comment]
The uploaded video : https://pics.revolis.fr/2022/01/13/08-52_lpvm.mp4

**Comment by nivcoo** [comment]
The issue only works in 1.12.2, not 1.18 https://pics.revolis.fr/2022/01/13/10-00_CjJ9.mp4 for the example i've set the mobs drop multiplier to 4

**Comment by OmerBenGera** [comment]
Should be fixed on latest dev build, let me know if it works.

**Comment by nivcoo** [comment]
It works thx

**Comment by nivcoo** [comment]
Hello, i've allways the issue but more randomly, and sometimes all the dropped item disappear

**Comment by OmerBenGera** [comment]
> Hello, i've allways the issue but more randomly, and sometimes all the dropped item disappear

Does it still occur..?

**Comment by nivcoo** [comment]
> > Hello, i've allways the issue but more randomly, and sometimes all the dropped item disappear
> 
> Does it still occur..?

Yes, but less efficient

**Comment by OmerBenGera** [comment]
> > > Hello, i've allways the issue but more randomly, and sometimes all the dropped item disappear
> > 
> > 
> > Does it still occur..?
> 
> Yes, but less efficient

I will look into it..
I applied the same patch that used to be, not sure why it still occurs 0.0

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Tested on 1.12 - had a stack of 30 zombies to pickup a sword when I have mob-drops multiplier set to 5. I killed them and only one sword was dropped, while the other drops were multiplied.

**Comment by nivcoo** [comment]
we cant stack sword, try with redstone block

**Comment by OmerBenGera** [comment]
> we cant stack sword, try with redstone block

Works fine with redstone blocks as well

**Comment by OmerBenGera** [comment]
Any news regarding this?
