### ISSUE TITLE
Mobs burn in daylight even when having blocks above them due to schematics

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#840]
### Minecraft's Version

1.18.1

### Plugin's Version

b453

### Describe the bug

Hello, when i use ss2 schmatic generator and create a new island, the block in this island doesn't count for zombie/skeleton protection:

Look my video : https://pics.revolis.fr/2022/01/13/10-11_vDtH.mp4

### To Reproduce

Create new island, mine into this island to place zombie/skeleton

You can see in the day zombies will burn. Try now when you change the block above the zombie and you can see they don't still burn anymore.

**Comment by OmerBenGera** [comment]
It seems to happen to me, however even if I manually place a block above the mob, it still burns for me.
Anyways, I will try to fix both issues.

**Comment by OmerBenGera** [comment]
Seems to affect 1.16, 1.17, 1.18
Still investigating the issue

**Comment by nivcoo** [comment]
Yes thx

**Comment by OmerBenGera** [comment]
@nivcoo Try enabling lights updates for schematics in the config.
Let me know if it fixes the issue.

**Comment by nivcoo** [comment]
I activate the feature, /is reset and the bug still here

**Comment by OmerBenGera** [comment]
> I activate the feature, /is reset and the bug still here

Re-create your island from scratch, enabling lights using default schematics should fix it.
Let me know if this exact instructions fix it or not.

**Comment by nivcoo** [comment]
How to recreate from scratch ? I've to redefine all my schematic ?

**Comment by OmerBenGera** [comment]
> How to recreate from scratch ? I've to redefine all my schematic ?

Just try it on another server with default files

**Comment by OmerBenGera** [comment]
I pushed an update that should fix the issue, let me know if it works for you.
