### ISSUE TITLE
Crop Growth Multiplier not working properly

### ISSUE THREAD

**Issue by marcel-maqsood** [BG-Software-LLC/SuperiorSkyblock2#841]
### Minecraft's Version

This server is running Paper version git-Paper-23 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 057adb0)

### Plugin's Version

SuperiorSkyblock2-1.8.3-b455

### Describe the bug

Crop Growth multiplier does not affect carrots, potatoes and beetroots.

### To Reproduce

go on your island, plant the given crops, 
set the upgrade "crop-growth" to 500 and see what happens.

you can also plant everything else and see, how fast they grow next to the others.

**Comment by OmerBenGera** [comment]
Add `CARROTS`, `POTATOES` and `BEETROOTS` to the crops-grwoth list in the config.
I will fix it on my end as well so they will be included by default.
