### ISSUE TITLE
Farming Missions

### ISSUE THREAD

**Issue by Raiderpint** [BG-Software-LLC/SuperiorSkyblock2#843]
### Minecraft's Version

MC 1.8.8 Custom Jar, but also tested on tacospigot 1.8.8

### Plugin's Version

1.8.3.b465

### Describe the bug

When attempting the farming mission that includes the growth of cane, after hand placing every block and waiting for growth then hitting it, nothing registers on the mission progress.

### To Reproduce

Create a cane farm and test

### Additional Information

Testing using farming mission https://pastebin.com/LAfE15c6 created by Ome_R

**Comment by OmerBenGera** [comment]
The file you gave me is using material names for 1.13+.
You need to change the material names to match your minecraft version. You can use this website to find the correct material names for your server: https://bg-software.com/materials
