### ISSUE TITLE
%superior_island_top_worth_1% returns nothing but %superior_island_top_worth_leader_<#>% returns island name

### ISSUE THREAD

**Issue by sahilshinde** [BG-Software-LLC/SuperiorSkyblock2#845]
### Minecraft's Version

This server is running Paper version git-Paper-"eeb3dea" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: eeb3dea)

### Plugin's Version

SuperiorSkyblock1 Version: 1.8.3.462

### Describe the bug

I was trying to create an hologram to show the island top leaderboard sorted by worth.I tried using 
%superior_island_top_worth_1% - %superior_island_top_worth_value_1%....it returned the worth value of the island but not the island name.Then itchyditchy asked me to try %superior_island_top_worth_leader_<#>% instead but that returns the name of the island instead of the owner.

### To Reproduce

i tried /papi parse me %superior_island_top_worth_1% and it returns a blank.But when i try /papi parse me %superior_island_top_worth_leader_1% it returns the name of the island instead of the leader.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build. sorry about that
