### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#848]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b468

### Describe the bug

I saw this in console : 
https://pastebin.com/fzvL4ZdW

### To Reproduce

No idea

### Additional Information

Using MySQL

**Comment by OmerBenGera** [comment]
What is the max-island-size value in your config file?

**Comment by WarnDa** [comment]
> max-island

max-island-size: 500

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build.
Let me know if it works for you.

**Comment by WarnDa** [comment]
Seems fixed, I'll open a new ticket if it happens again
