### ISSUE TITLE
Database Won't Convert Properly

### ISSUE THREAD

**Issue by GalaxyGaming-GG** [BG-Software-LLC/SuperiorSkyblock2#851]
### Minecraft's Version

PaperSpigot-445 1.8.8

### Plugin's Version

Old: Unsure of old version but jar name was "SuperiorSkyblock-SafeBlockFix"
New: 1.8.3

Note: I can update to 261b before the plugin breaks from the database conversion

### Describe the bug

Whenever updating to the newest version the database will not convert properly. The islands and a lot of data do not transfer over.

### To Reproduce

Take database and run the newest version of the plugin.

### Additional Information

Error log when updating to 1.8.3: https://pastebin.com/4ycDwVKC

I have tried updating to many different version, but no version after the database change will convert my data correctly.

**Comment by OmerBenGera** [comment]
Are you using MySQL or SQLite?

**Comment by GalaxyGaming-GG** [comment]
SQLite

**Comment by OmerBenGera** [comment]
> SQLite

Do you know how to open it?

**Comment by GalaxyGaming-GG** [comment]
> > SQLite
> 
> Do you know how to open it?

Yes I've opened the old one and the new one it creates after it tries to convert

**Comment by GalaxyGaming-GG** [comment]
[database.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7884764/database.zip)
This is the old database I am trying to convert

**Comment by OmerBenGera** [comment]
Show me the faulty new one as well.

**Comment by GalaxyGaming-GG** [comment]
[database_new.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7892735/database_new.zip)

**Comment by OmerBenGera** [comment]
@GalaxyGaming-GG Do you have the jar that you used?
Your old database is missing the `uuid` column for islands, which is really weird.
I want to see which other columns it's missing, so I can patch everything.

**Comment by GalaxyGaming-GG** [comment]
[SuperiorSkyblock-SafeBlockFix.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/7908377/SuperiorSkyblock-SafeBlockFix.zip)
This is the old jar from I think 2020

**Comment by OmerBenGera** [comment]
I could replicate the issue using your jar.
It's so old that the plugin can't handle it haha

I am gonna fix everything and let you know once it's fixed

**Comment by OmerBenGera** [comment]
Let me know if it works for you using latest dev build

**Comment by GalaxyGaming-GG** [comment]
The latest dev build (b472) seems to convert everything properly
