### ISSUE TITLE
Nether basalt generator works even without soul soil beneath

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#854]
### Minecraft's Version

git-Paper-397 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 1a83e90 on ver/1.17.1)

### Plugin's Version

1.8.3.468

### Describe the bug

When you have edited generator for Nether island, your basalt generator works even without soul soil. It occures only in specific cases, when lava flows into the empty block next to the blue ice. If you place blue ice next to the any type of lava, nothing happens.

### To Reproduce

Setup specific generator for nether island (via upgrades, or commads /is admin (set/add)generator), go to nether, place blue ice and lava 2 block away from the blue ice. Blocks will generate even without soul soil underneath.

**Comment by OmerBenGera** [comment]
Just to make sure - soul soil must be under the generated block so blocks will generate in nether, right?
I made it to only work with lava and blue ice, thats why it works like that.

**Comment by Davisiiiik** [comment]
Yep, soul soil has to be underneath the lava and blue ice has to be adjacent to that lava from any side in order to change it into the basalt block

**Comment by OmerBenGera** [comment]
This seems to work fine for me.
Blocks are not generated if there is no sand soil below the generated block, alongside of lava and blue ice nearby.

**Comment by Davisiiiik** [comment]
Do you have edited generator for your island in nether? Cause if not, blocks are generated normally. Should I post a video closely describing an issue?

**Comment by OmerBenGera** [comment]
> Do you have edited generator for your island in nether? Cause if not, blocks are generated normally. Should I post a video closely describing an issue?

I tried by both using custom generator rates and vanilla generator.
And sure, a video may help.

**Comment by Davisiiiik** [comment]
https://user-images.githubusercontent.com/79375965/150783255-2c7f7a39-34d6-4450-89b8-551db3322e09.mp4

**Comment by OmerBenGera** [comment]
Fixed in latest build
