### ISSUE TITLE
Can't teleport to islands

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#861]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b463

### Describe the bug

Some players can't enter their island, when they move they are teleported to the spawn.

### To Reproduce

- Teleport to your island
- move
- You'll be teleported to spawn

### Additional Information

- No console error
- No message in console
- you can teleport, but if you move you are teleported to spawn
- with bypass you can move without issue

The issue seems the island border is same as "1" so once you move it teleports you because you are out of border.

- Back to b469 fix the issue

**Comment by OmerBenGera** [comment]
I don't understand what causes the issue.
What do you mean by "The issue seems the island border is same as "1" so once you move it teleports you because you are out of border."

**Comment by WarnDa** [comment]
> What do you mean by "The issue seems the island border is same as "1" so once you move it teleports you because you are out of border."

It's the same as if you teleport a player outside the island border, he will be teleported, but if he moves he is out of border so teleported to spawn.
But if you have bypass on, you can move without any issue

**Comment by WarnDa** [comment]
https://www.youtube.com/watch?v=jfxN_T-p-Ps

**Comment by OmerBenGera** [comment]
Is there a worldborder around the island?
Where you run /is admin show, where is this island located (it's center)? Is the teleport location in this area?

**Comment by WarnDa** [comment]
> Is there a worldborder around the island?

No (or it was visually disabled, I didn't check)

> Where you run /is admin show, where is this island located (it's center)? Is the teleport location in this area?

No it wasn't in the center, and I had to go back to b439 because I'm in prod.
Hopefully other people will give more information once they got the issue

**Comment by OmerBenGera** [comment]
> 

Downgrading fixed the issue..?

**Comment by OmerBenGera** [comment]
> > > 
> > 
> > 
> > Downgrading fixed the issue..?
> 
> yes I told it ![image](https://user-images.githubusercontent.com/31826333/150516629-58aa08b6-a8cc-4554-b409-0c9b413db8fe.png)
> 
> Might be b470 that have issue

Where was the teleport location and where was the center of the island?

**Comment by WarnDa** [comment]
> > > > 
> > > 
> > > 
> > > Downgrading fixed the issue..?
> > 
> > 
> > yes I told it ![image](https://user-images.githubusercontent.com/31826333/150516629-58aa08b6-a8cc-4554-b409-0c9b413db8fe.png)
> > Might be b470 that have issue
> 
> Where was the teleport location and where was the center of the island?

![image](https://user-images.githubusercontent.com/31826333/150522112-3c27bdca-afce-4894-b9f3-ea7b69b430d3.png)
The teleportation point.

**Comment by OmerBenGera** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Downgrading fixed the issue..?
> > > 
> > > 
> > > yes I told it ![image](https://user-images.githubusercontent.com/31826333/150516629-58aa08b6-a8cc-4554-b409-0c9b413db8fe.png)
> > > Might be b470 that have issue
> > 
> > 
> > Where was the teleport location and where was the center of the island?
> 
> ![image](https://user-images.githubusercontent.com/31826333/150522112-3c27bdca-afce-4894-b9f3-ea7b69b430d3.png) The teleportation point.

And the center of the island from /is admin show?

**Comment by WarnDa** [comment]
> 

![image](https://user-images.githubusercontent.com/31826333/150522305-89ce0a6e-57b8-4600-926d-45123ad22ddb.png)

**Comment by OmerBenGera** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/31826333/150522305-89ce0a6e-57b8-4600-926d-45123ad22ddb.png)

Looks good then.
I don't know what the issue is, and as you're not using the bugged build, I can't do much regarding this.
Try replicating it on another server using that build, otherwise I'll have to close this issue for now

**Comment by OmerBenGera** [comment]
Also, why did you run `/is admin recalc` when your server stated?
This is only gonna cause lag.

**Comment by WarnDa** [comment]
> Also, why did you run `/is admin recalc` when your server stated? This is only gonna cause lag due to chunks loading.

Because I updated from b467, and I wanted to recalc all the islands to fix the issue of old islands not being calculated. And there were only 40 players so no issue with lags

**Comment by WarnDa** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31826333/150522305-89ce0a6e-57b8-4600-926d-45123ad22ddb.png)
> 
> Looks good then. I don't know what the issue is, and as you're not using the bugged build, I can't do much regarding this. Try replicating it on another server using that build, otherwise I'll have to close this issue for now

I'll try, but this bug will be hard to reproduce as it doesn't happen to all islands, and there is no error :/

**Comment by WarnDa** [comment]
I reproduced it on b485 with a player, but I don't get much informations..
I'll try in private once I can (I hope this week)

**Comment by WarnDa** [comment]
fixed on latest dev build
