### ISSUE TITLE
Permissions and settings from pages after the first page can't be changed

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#865]
### Minecraft's Version

Purpur 1.17.1 latest

### Plugin's Version

d478

### Describe the bug

Like in the title - permissions and settings from pages after the first page can't be changed. Clicking does nothing

### To Reproduce

- Use `/is perms` or `/is settings` 
- Change to next page
- Try to change some setting or permission

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
