### ISSUE TITLE
EntityPortalEnterEvent  in nether portal in spawn

### ISSUE THREAD

**Issue by Stoiky20** [BG-Software-LLC/SuperiorSkyblock2#871]
### Minecraft's Version

#171 paper build 1.18.1

### Plugin's Version

1.8.3-484

### Describe the bug

So I have a nether portal in my spawn ( not on my island) and I setted it to execute a command with a plugin (commandregions, dungeonsxl, can be any plugin doesn't matter). So basically when I go to the portal this error spams the console https://mcpaste.io/e0c919282889f17b

### To Reproduce

Download the plugin
disable nether in bukkit.yml
go to spawn
place a nether portal
go into the nether portal
watch the console get the errors

### Additional Information

https://mcpaste.io/fc37842336faf8c4

**Comment by OmerBenGera** [comment]
The error is not from a dev build.
Are you sure you're using a dev build on your server?
Confirm it using /version.

**Comment by OmerBenGera** [comment]
By the way, you are using mojang-mapped version.
Not only it's not supported, it's also illegal and you should use Paper's original build and not the mojang-mapped version.
After you'll update your SSB jar and Paper, it will be fixed.
Therefore, I am closing this for now.

**Comment by banicola** [comment]
@OmerBenGera Actually I have the exact same issue on Paper 1.18.1 (latest build) and with the latest stable or DEV build of SSB

**Comment by OmerBenGera** [comment]
> @OmerBenGera Actually I have the exact same issue on Paper 1.18.1 (latest build) and with the latest stable or DEV build of SSB

Upload the error you have to pastebin and send it here please.

**Comment by Stoiky20** [comment]
Not sure what you mean by mojang mapped version..This is the build downloaded from https://papermc.io/downloads
https://mcpaste.io/fa618edee037a59e
![image](https://user-images.githubusercontent.com/67865149/151044731-99226a9c-1176-4fe8-b70b-052daf0ce0bf.png)

**Comment by Stoiky20** [comment]
https://mcpaste.io/5a5628b4fd4d7dcb

**Comment by banicola** [comment]
My error is the same as above: https://pastebin.com/raw/MwJmVkBa

**Comment by OmerBenGera** [comment]
Both of you use version of Minecraft that is not obfuscated.
Download Paper again, or contact them and ask them how to fix it.
Nothing to do with the plugin itself.

**Comment by banicola** [comment]
I'm using the latest build from here https://papermc.io/downloads#Paper-1.18

The official Paper version nothing else

**Comment by OmerBenGera** [comment]
Never mind, my bad.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
