### ISSUE TITLE
Biomes not Valid

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#872]
### Minecraft's Version

1.18.1

### Plugin's Version

b484

### Describe the bug

Hello i've this in my console

[15:23:04 INFO]: [SuperiorSkyblock2] Biome 'NETHER' is not valid, skipping...
[15:23:04 INFO]: [SuperiorSkyblock2] Biome 'WOODED_HILLS' is not valid, skipping...

I've tried to delete biome menu file and it's default value.

### To Reproduce

Run ss2 in 1.18.1 and check biomes.

**Comment by OmerBenGera** [comment]
The NETHER biome in 1.16+ is NETHER_WASTES. About the other biome, I dont remember the correct biome name - google "spigot biome" to find the correct biome name.

**Comment by OmerBenGera** [comment]
The NETHER biome in 1.16+ is NETHER_WASTES. About the other biome, I dont remember the correct biome name - google "spigot biome" to find the correct biome name.
