### ISSUE TITLE
Too many packets

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/SuperiorSkyblock2#876]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-20 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b9556fd on HEAD)
Previous version: git-Pufferfish-19 (MC: 1.17.1)

### Plugin's Version

b474

### Describe the bug

A player is kicked from the game when opening /is settings or /is panel.

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 10774286, should be less than 8388608): net.minecraft.network.protocol.game.PacketPlayOutWindowItems@21fe98e6 

### To Reproduce

I have a modified GUI for /is settings and /is panel.
When a player tries to open the GUI he gets thrown out.
From what I have noticed the GUI works at first, but after some time the problem starts to occur.

is settings: https://pastebin.com/ymuqT38i
panel: https://pastebin.com/Pi1T5djb

### Additional Information

https://pastebin.com/yHkiVfAe
https://pastebin.com/yHkiVfAe

ViaVersion support:
![image](https://user-images.githubusercontent.com/23367220/150701612-891d67fe-beb7-46de-9da4-74717ced23bd.png)

**Comment by OmerBenGera** [comment]
Contact ViaVersion regarding this, this is not an issue with the plugin.
For no reason, it can't handle all the items in the inventory 0.0

**Comment by OmerBenGera** [comment]
When you report them the error, make sure you also take a screenshot / small gif of the menu, so they understand how the menu looks like and what may cause it.
