### ISSUE TITLE
Island recalc broken

### ISSUE THREAD

**Issue by TheSuspectPT** [BG-Software-LLC/SuperiorSkyblock2#878]
### Minecraft's Version

1.18.1

### Plugin's Version

1.8.2.405

### Describe the bug

after adding "NETHERITE_BLOCK: 500" to the list of block values, it inially worked in giving value. but when doing "/is recalc", it went on an infinite attempt to recalc, making it impossible to place blocks in the island until server is restarted. Even after removing the code, the issue still persists (the code is  back to 100% what it was on installation) and i don't know how to go about this.

### To Reproduce

insert NETHERITE_BLOCK:500 on block value list, restart the server and do /is recalc.

**Comment by OmerBenGera** [comment]
Are there any errors?
Are you able to replicate the issue on another server?

**Comment by TheSuspectPT** [comment]
this is the issue i get on  console:
http://prntscr.com/26jmxa2
for replicating on another server im opening another one and will get back to you on that when its done

**Comment by OmerBenGera** [comment]
Update SSB, this error was already fixed.
