### ISSUE TITLE
Error during islands loading on Dev builds

### ISSUE THREAD

**Issue by banicola** [BG-Software-LLC/SuperiorSkyblock2#882]
### Minecraft's Version

Paper 1.18.1 (Latest build)

### Plugin's Version

Version 1.8.3 DEV BUILD 492

### Describe the bug

Since the latest dev build I have the following error when the server is starting. I did not change anything and it was working fine on previous update, for example in the 1.8.3 stable update.

The error: https://pastebin.com/raw/gj9FN4wz

### To Reproduce

I don't really know how to reproduce it other than setting a island chest inventory the way it is describe in the error on the stable update and then restart the server with the dev builds.

### Additional Information

I'm storing islands data on a MySQL database.

**Comment by banicola** [comment]
The islands with that issue aren't propertly loaded which means that you can not interact with them (neither do commands such as /is info -> https://pastebin.com/raw/uiguq54V)

**Comment by OmerBenGera** [comment]
Show me your config file please.

**Comment by banicola** [comment]
> 

Which file do you need?

**Comment by OmerBenGera** [comment]
> > 
> 
> Which file do you need?

As I said, show me your config file of the plugin.
Upload it to pastebin and send it here.

**Comment by banicola** [comment]
https://pastebin.com/raw/Reb0iqmb

**Comment by OmerBenGera** [comment]
> https://pastebin.com/raw/Reb0iqmb

This pastebin is invalid.

**Comment by banicola** [comment]
Yes I can't publish it in public (I removed the sql connection info but it still does not work). I'm looking for an other way.

![image](https://user-images.githubusercontent.com/25954399/151249283-f6dc5fac-8e44-4ded-bdc4-3b8e07b8a4d2.png)

**Comment by OmerBenGera** [comment]
> Yes I can't publish it in public (I removed the sql connection info but it still does not work). I'm looking for an other way.
> 
> ![image](https://user-images.githubusercontent.com/25954399/151249283-f6dc5fac-8e44-4ded-bdc4-3b8e07b8a4d2.png)

Then use another website... Github gist, hastebin - many exist.

**Comment by banicola** [comment]
https://www.toptal.com/developers/hastebin/raw/rupedokiwa

**Comment by OmerBenGera** [comment]
Should be fixed on latest dev build.

**Comment by banicola** [comment]
Thanks, I'm trying it

**Comment by banicola** [comment]
It works fine, thanks. I just noted that there's a debug printed every few seconds in the console when someone is on the island world. Maybe it is a coincidence that it happend only on the islands world and it's not from SSB but who knows.
![image](https://user-images.githubusercontent.com/25954399/151251060-3f6fddbc-210f-4750-9fd0-c2b36440a426.png)

**Comment by OmerBenGera** [comment]
This is not a debug message from SSB.
Closing this :)
