### ISSUE TITLE
Nether and The End generates same biome as normal world

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#883]
### Minecraft's Version

Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)

### Plugin's Version

SuperiorSkyblock2 version 1.8.3.489

### Describe the bug

When Nether and The End islands are generated, they come with Plains biome (same as normal). When you change your biome to anything (I used admin command) AFTER the worlds are generated, they change to right ones.

### To Reproduce

Create yourself an island, build Nether portal, enter it, hit F3 and see.

### Additional Information

config.yml worlds:
https://pastebin.com/vgD2CGi2

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
