### ISSUE TITLE
Issue with Bank menu

### ISSUE THREAD

**Issue by Superalex0102** [BG-Software-LLC/SuperiorSkyblock2#887]
### Minecraft's Version

1.12.2 paperspigot

### Plugin's Version

489

### Describe the bug

The island menu shows 0 balance
![image](https://user-images.githubusercontent.com/41546701/151352253-4a304982-e4bb-4b0d-a007-f7c67d6a98d6.png)

![image](https://user-images.githubusercontent.com/41546701/151352282-9ffecd20-e8ca-4163-8308-7ad02dcc213f.png)

### To Reproduce

-

**Comment by Davisiiiik** [comment]
Maybe send your island-bank.yml content using pastebin? This doesnt say anything.

**Comment by Superalex0102** [comment]
> 

https://pastebin.com/eZayjej1

I had no issues so far since I updated

**Comment by Superalex0102** [comment]
After a restart it works fine, but still weird

**Comment by OmerBenGera** [comment]
> After a restart it works fine, but still weird

Weird.
If it happens again, lmk by commenting here.

**Comment by Superalex0102** [comment]
I still have this issue

**Comment by OmerBenGera** [comment]
@Superalex0102 How to replicate the issue?
When does it happen?
I tested it and it looks fine.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Superalex0102** [comment]
Fixed
