### ISSUE TITLE
BlocksMissions blocks-placement option probably dont work

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#888]
### Minecraft's Version

Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)

### Plugin's Version

1.8.3.494

### Describe the bug

When in BlocksMissions is `blocks-placement` option set to `true`, mission doesn't count anything into the progress.

### To Reproduce

Create and BlocksMissions mission and set blocks-placement` option to `true`. Go place some materials. It wont count towards the progress.

### Additional Information

My mission config: https://pastebin.com/3qLaGaL3
Possible issue is here on line 191: https://github.com/BG-Software-LLC/SuperiorSkyblock2-Missions/blob/master/BlocksMissions/src/main/java/com/bgsoftware/superiorskyblock/missions/BlocksMissions.java

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
