### ISSUE TITLE
Part of schematics are duplicated and placed in the sky

### ISSUE THREAD

**Issue by OmerBenGera** [BG-Software-LLC/SuperiorSkyblock2#889]
### Minecraft's Version

Affecting all Spigot 1.18.X versions

### Plugin's Version

1.8.4.496-1.9.0.604

### Describe the bug

When an island is created for the first time, part of the schematic can be duplicated and placed in the sky, as can be shown below:
https://gyazo.com/e109aed63c6913f805b4d9c78a2ce1bd

### To Reproduce

Create an island after the server starts, and look above in the sky.

**Comment by OmerBenGera** [comment]
The solution for this is to just not use Spigot at this moment.
The issue is fixed in Paper.

Hopefully I will be able to find a solution that works with Spigot.
PRs are more than welcome :)

The code for placing blocks that is the problematic on spigot can be found here:
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/dev/v1_18_R2/src/main/java/com/bgsoftware/superiorskyblock/nms/v1_18_R2/NMSUtils.java#L176

**Comment by ItzFabb-uwu** [comment]
:(

**Comment by OmerBenGera** [comment]
> :(

It happened for you with Paper, no?
Also, are you sure its related to crop growth?

**Comment by ItzSave** [comment]
When modifying the crop growth causes crops to start dropping from the sky. The crops in question are placed after island generation (built by a user after island is created)

Command Used: /is admin setcropgrowth ItzSave 1000

Images of the farm & where they are falling from.
![2022-05-02_14 29 58](https://user-images.githubusercontent.com/44411260/166313109-421c8507-36b7-4969-9a8f-6fd1070f0515.png)
![2022-05-02_14 29 59](https://user-images.githubusercontent.com/44411260/166313110-900c4452-c110-4951-8770-114560bcd544.png)

**Comment by ItzSave** [comment]
> 

Forgot to add server & plugin version.
![image](https://user-images.githubusercontent.com/44411260/166313202-35960b68-66fe-4c16-8aff-ecfe15f32ceb.png)
![image](https://user-images.githubusercontent.com/44411260/166313235-c00fa454-d840-40e9-aca9-f1b814ec3d53.png)

**Comment by OmerBenGera** [comment]
> When modifying the crop growth causes crops to start dropping from the sky. The crops in question are placed after island generation (built by a user after island is created)
> 
> Command Used: /is admin setcropgrowth ItzSave 1000
> 
> Images of the farm & where they are falling from. ![2022-05-02_14 29 58](https://user-images.githubusercontent.com/44411260/166313109-421c8507-36b7-4969-9a8f-6fd1070f0515.png) ![2022-05-02_14 29 59](https://user-images.githubusercontent.com/44411260/166313110-900c4452-c110-4951-8770-114560bcd544.png)

Interesting.
I also looked at the code and the problematic line might be here:
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/bd893752adfc4b09d78cad32edf5b6fec21878d6/v1_18_R2/src/main/java/com/bgsoftware/superiorskyblock/nms/v1_18_R2/chunks/CropsTickingTileEntity.java#L112

The calculated position for ticking the block might be not the same as the block that is being checked, causing this weird and buggy behavior.
I will look into that later this week and hopefully patch this bug

**Comment by ItzSave** [comment]
> > When modifying the crop growth causes crops to start dropping from the sky. The crops in question are placed after island generation (built by a user after island is created)
> > Command Used: /is admin setcropgrowth ItzSave 1000
> > Images of the farm & where they are falling from. ![2022-05-02_14 29 58](https://user-images.githubusercontent.com/44411260/166313109-421c8507-36b7-4969-9a8f-6fd1070f0515.png) ![2022-05-02_14 29 59](https://user-images.githubusercontent.com/44411260/166313110-900c4452-c110-4951-8770-114560bcd544.png)
> 
> Interesting. I also looked at the code and the problematic line might be here:
> 
> https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/bd893752adfc4b09d78cad32edf5b6fec21878d6/v1_18_R2/src/main/java/com/bgsoftware/superiorskyblock/nms/v1_18_R2/chunks/CropsTickingTileEntity.java#L112
> 
> The calculated position for ticking the block might be not the same as the block that is being checked, causing this weird and buggy behavior. I will look into that later this week and hopefully patch this bug

Just an update that this was still happening as of build 642

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.
@ItzSave Let me know if it works for you
