### ISSUE TITLE
ItemsMissions {value_<block>} placeholder doesnt work

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#891]
### Minecraft's Version

Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)

### Plugin's Version

1.8.4.496

### Describe the bug

When using {value_<block>} (ie: {value_charcoal}), value doesnt show ingame.

### To Reproduce

Create a mission, set it to ItemsMissions, use {value_<block>} placeholder in lore, watch it how it doesnt work

### Additional Information

![image](https://user-images.githubusercontent.com/79375965/151576951-df64e7dc-46e9-403a-8564-4484c977fd69.png)

**Comment by OmerBenGera** [comment]
This placeholder doesn't exist for ItemsMissions, as ItemsMissions doesn't track items in your inventory.
It instead counts the items in the inventory once you click the mission.

It is not a bug :(

**Comment by Davisiiiik** [comment]
But it counts the general progress and {0} and {1} placeholders, so it has to count it before completition, or am I mistaken?

**Comment by OmerBenGera** [comment]
> But it counts the general progress and {0} and {1} placeholders, so it has to count it before completition, or am I mistaken?

I might added a placeholder that counts the items each time.
Anyways, it's not a bug.

**Comment by Davisiiiik** [comment]
Okay, I get it, thank you for your response.
