### ISSUE TITLE
Crafting Mission Error

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#893]
### Minecraft's Version

Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)

### Plugin's Version

1.8.4.499

### Describe the bug

Crafting missions wont load. I've checked the source code and the key word for crafted items is described by craftings.type? Not craftings.types?

![image](https://user-images.githubusercontent.com/79375965/151668774-56269832-9b8c-4d49-8b37-1b76c7c6eb92.png)

Anyway, I tried both variants and it still doesnt work, but the error is different.

### To Reproduce

You can just simply copy my configs and try them yourself.

### Additional Information

Using "type" key config: https://pastebin.com/hVhhQXyA
Using "types" key config: https://pastebin.com/5ifwdST3

Errors for both: https://pastebin.com/R0KtSSjD

**Comment by OmerBenGera** [comment]
You should use `craftings.type` as a string, not a list.
It should be like that:
```
craftings:
  '1':
    type: STONE_HOE
```

**Comment by Davisiiiik** [comment]
I tried all these three variants:
```
craftings:
  '1':
    type: STONE_HOE
    amount: 3
```
```
craftings:
  '1':
    type: 'STONE_HOE'
    amount: 3
```
```
craftings:
  '1':
    type: 'STONE_HOE'
```
Those three results in same result. Error, when I try to open the category containing them: https://pastebin.com/Qpzr6fC1
