### ISSUE TITLE
Schematic Island Creation Problem

### ISSUE THREAD

**Issue by zPopCorn10** [BG-Software-LLC/SuperiorSkyblock2#895]
### Minecraft's Version

1.8.8 Paper

### Plugin's Version

1.8.4 stable

### Describe the bug

https://youtu.be/i4zdvABA8Y8

### To Reproduce

Here: https://youtu.be/i4zdvABA8Y8

### Additional Information

I tried to follow the guide on the wiki too, it's called "use worldedit schematic"

**Comment by zPopCorn10** [comment]
Here for error log  https://pastebin.com/wxXr7gRb

**Comment by OmerBenGera** [comment]
What version of Paper are you using exactly?
I use the 1.8.8 version from their website and it works flawlessly fine.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by zPopCorn10** [comment]
I switched to SportPaper and it seems to be fixed, sorry for the delay and for the false report, have a good day!

**Comment by OmerBenGera** [comment]
Great.
If it happens again, let me know!
