### ISSUE TITLE
No protection on slimefun machines

### ISSUE THREAD

**Issue by zAlexPE** [BG-Software-LLC/SuperiorSkyblock2#896]
### Minecraft's Version

1.18.1 / spigot-1.18.1.jar

### Plugin's Version

SuperiorSkyblock2-1.8.3-b477.jar

### Describe the bug

Players are able to open other players' machines and steal the items inside without having permission on the island

### To Reproduce

Download Superiorskyblock
Download Slimefun
Put a machine in an island
Let other player try to open it

**Comment by Skizzles** [comment]
@zAlexPE Update to latest dev build, there is already a fix for this.
