### ISSUE TITLE
Nether problems

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#899]
### Minecraft's Version

Minecraft Version: 1.17.1
Server Jar: This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)
You are running the latest version

### Plugin's Version

SuperiorSkyblock2 version 1.8.4.495

### Describe the bug

1. Players can simply fly out of their nether island and into other players islands. They can fly as far as they want
2. Players don't have permission to place blocks in the nether for some reason

### To Reproduce

1. Go to the nether
2. Fly away

**Comment by OmerBenGera** [comment]
1. Look for the "stop-leaving" section in the config. Borders are visual only, and unless you enable the setting I mentioned, no enforcement will occur on players leaving the island. If it doesnt work, open a new issue.
2. What message do they get when they try to break blocks?

**Comment by DuneSciFye** [comment]
Alright, I enabled stop-leaving in the config. And for the second issue, it seems to be randomly fixed now
