### ISSUE TITLE
/island top | Skins and Display

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#900]
### Minecraft's Version

Purpur-1537 (MC: 1.18.1)

### Plugin's Version

Latest stable version
1.8.4

### Describe the bug

The servers that allow unofficial versions of Minecraft, do not display the skins of the players in the top-island, despite SkinRestorer installed and the top-island displays that from #2 the #1 is innexistent (not displayed in the top-island)

With SS2 version 1.8.3 all this works without problem

### To Reproduce

Put your server in offline mode, install SkinRestorer, create your island and then use the command (/island top)

**Comment by OmerBenGera** [comment]
Do you have SkinsRestorer installed on the same server that SSB is inatalled, or is it installed on bungee?

**Comment by DuckyDou** [comment]
Yes SkinRestorer is installed on Spigot and Bungeecord.

BTW it's not skinrestorer issue because with 1.8.3 of SS2 it's work great

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by DuckyDou** [comment]
Hi! Skins show is fixed but other issue persist (it's show only #2 top no #1)

![2022-02-05_23 01 13](https://user-images.githubusercontent.com/98712497/152667269-862e0828-d6be-4e97-8ea7-fdf02726369e.png)

**Comment by OmerBenGera** [comment]
> Hi! Skins show is fixed but other issue persist (it's show only #2 top no #1)
> 
> ![2022-02-05_23 01 13](https://user-images.githubusercontent.com/98712497/152667269-862e0828-d6be-4e97-8ea7-fdf02726369e.png)

Open a new issue regarding this

**Comment by DuckyDou** [comment]
issue with skin and skinrestorer is back.!!!!
