### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by KibbaCrafteR** [BG-Software-LLC/SuperiorSkyblock2#903]
### Minecraft's Version

1.8.8

### Plugin's Version

lateast

### Describe the bug

Hello How can my developer chance the currency to mobcoins for island upgrades

### To Reproduce

Hello How can my developer chance the currency to mobcoins for island upgrades

**Comment by OmerBenGera** [comment]
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/API/src/main/java/com/bgsoftware/superiorskyblock/api/handlers/ProvidersManager.java#L55

**Comment by KibbaCrafteR** [comment]
Could i have more information about the usage
