### ISSUE TITLE
Top island

### ISSUE THREAD

**Issue by Teyir** [BG-Software-LLC/SuperiorSkyblock2#904]
### Minecraft's Version

1.18.1

### Plugin's Version

latest build

### Describe the bug

Can't view player heads (top islands)

### To Reproduce

This is my entire top-islands.yml

`######################################################
######################################################

title: '&lTop Islands'
previous-menu: true

pattern:
  - 'A B ~ ~ ~ ~ ~ B A'
  - 'B ~ $ ~ ~ # ~ ~ B'
  - '~ * ~ ~ # # # ~ ~'
  - '~ ^ ~ # # # # # ~'
  - 'B ~ ~ ~ ~ ~ ~ ~ B'
  - 'M B ! ~ - ~ + B A'

slots: '#'
previous-page: '!'
current-page: '-'
next-page: '+'

player-island: '$'
sort-glow-when-selected: true

items:
  '#':
    island:
      type: PLAYER_HEAD
      name: '&e&l[!] Île: &6&n{0}&7 (#{1})'
      lore:
        - '&7'
        - '&6&l* &e&lNiveau d''île &7{2}'
        - '&7'
        - '&6&l* &e&lPlace &7#{1}'
        - '&6&l* &e&lNotation {8} &7({9})'
        - '&6&l* &e&lJoueurs &7{10}'
        - '&7'
        - '&6&l* &e&lMembres:'
        - '{4}:&f  - &7{}'
        - '&7'
        - '&7&o(( &f&oClique gauche &7&opour voir leurs items. ))'
        - '&7&o(( &f&oClique droit &7&opour se téléporter à leurs warps. ))'
    no-island:
      type: PLAYER_HEAD
      name: '&cEmplacement vide'
  '*':
    type: GOLD_INGOT
    sorting-type: 'LEVEL'
    name: '&6Trier par niveau'
  '^':
    type: EMERALD
    sorting-type: 'RATING'
    name: '&6Trier par notation'
  '!':
    type: PAPER
    name: '{0}Page précedente'
  '-':
    type: SUNFLOWER
    name: '&aPage actuelle'
    lore:
      - '&7Page {0}'
  '+':
    type: PAPER
    name: '{0}Page suivante'
  '~':
    type: BLUE_STAINED_GLASS_PANE
    data: 15
    name: '&f'
  'A':
    type: BLACK_STAINED_GLASS_PANE
    data: 11
    name: '&f'
  'B':
    type: PURPLE_STAINED_GLASS_PANE
    data: 2
    name: '&f'      
  'M':
    type: BARRIER
    name: '&cRetourner au menu de l''île'  
   

commands:
  'M':
    - '[close]'
    - 'trmenu open is %player%'     

sounds:
  '~':
    type: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 0.2
    pitch: 0.2`

### Additional Information

This is my GUI:
![image](https://user-images.githubusercontent.com/60007549/152123735-83684a2a-ba5a-43f6-9bfd-650c8c673505.png)

On hover:
![image](https://user-images.githubusercontent.com/60007549/152123779-6f6dac30-1407-40a7-a3e8-fe06d64c79d0.png)

**Comment by OmerBenGera** [comment]
You are probably have offline mode enabled.
Make aure you use SkinsRestorer or ChangeSkin on your spigot server (not bungeecord)

**Comment by Teyir** [comment]
I have a bungeecord (velocity server), and my network is online mode.

I absolutely need to use skinrestorer juste for the is top heads ? Bc my players  has already her skin

**Comment by Teyir** [comment]
I use TrMenu for my others customs menu and I have my players head @OmerBenGera

**Comment by OmerBenGera** [comment]
> I have a bungeecord (velocity server), and my network is online mode.
> 
> I absolutely need to use skinrestorer juste for the is top heads ? Bc my players has already her skin

Yes... otherwise, the plugin cannot retrieve skins for players, as your server is under a proxy.
