### ISSUE TITLE
Upgrades dont saving to database

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#905]
### Minecraft's Version

1.16.5

### Plugin's Version

b501

### Describe the bug

I using mariadb and upgrades reset every restart

### To Reproduce

Connect to mariadb
Buy upgrades
Restart server

**Comment by OmerBenGera** [comment]
After you purchase an upgrade, is it saved to the database?

**Comment by exzolink** [comment]
> After you purchase an upgrade, is it saved to the database?

Sometimes yes, sometimes no, mostly no.

**Comment by exzolink** [comment]
Some upgrades override another, in the morning the player had a hopper-limit 2 lvl upgrade, now he have only members-limit 2 lvl

**Comment by exzolink** [comment]
Its a fresh install

**Comment by exzolink** [comment]
Oh i got it, its save only last upgrade, if you upgraded something else its overrides current. Need fix ASAP

**Comment by exzolink** [comment]
> Oh i got it, its save only last upgrade, if you upgraded something else its overrides current. Need fix ASAP

@OmerBenGera

**Comment by OmerBenGera** [comment]
Fixed in latest dev build.

**Comment by JoshuaPHYT** [comment]
still happening
