### ISSUE TITLE
News schematic out of bounds

### ISSUE THREAD

**Issue by n54b** [BG-Software-LLC/SuperiorSkyblock2#906]
### Minecraft's Version

1.16.5 paper 

### Plugin's Version

1.8.4.501

### Describe the bug

i create a schematic with /is admin schematic but when i want to use i have this error : 

https://pastebin.com/eeYPQD8G

### To Reproduce

create a very big schematic (like 610x610) and try to use the schematic ^^

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
