### ISSUE TITLE
Invalid island privileges errors

### ISSUE THREAD

**Issue by kurkinsnetwork** [BG-Software-LLC/SuperiorSkyblock2#907]
### Minecraft's Version

Paper 1.17.1 paper.mc #408

### Plugin's Version

1.8.4

### Describe the bug

I get the following error when using a fresh copy of superiorskyblock #501

I don't have any issues using #402

I am using paper 1.17 #408 and java 17

### To Reproduce

https://pastebin.com/jWd4KPH4

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs.

**Comment by kurkinsnetwork** [comment]
![image](https://user-images.githubusercontent.com/96862152/152556624-fbbd3f4f-1e56-4806-a918-c7388da02811.png)
NOT WORK

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/96862152/152556624-fbbd3f4f-1e56-4806-a918-c7388da02811.png) NOT WORK

Send me new logs via pastebin.
This screenshot does not contain the entire stack trace and I can't do anything with it.

**Comment by kurkinsnetwork** [comment]
https://www.toptal.com/developers/hastebin/edunipuduq.yaml ı try #506 dev build and not work

**Comment by OmerBenGera** [comment]
What is your discord?
I want to send you a custom jar with more debug messages so I can better understand what's going on.

**Comment by kurkinsnetwork** [comment]
𝕶𝖚𝖗𝖐𝖎𝖓𝖘#7019
