### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by KibbaCrafteR** [BG-Software-LLC/SuperiorSkyblock2#909]
### Minecraft's Version

Could I know more information about the Change Currency Usage please 
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/API/src/main/java/com/bgsoftware/superiorskyblock/api/handlers/ProvidersManager.java#L55

### Plugin's Version

lateast

### Describe the bug

Could I know more information about the Change Currency Usage please 
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/API/src/main/java/com/bgsoftware/superiorskyblock/api/handlers/ProvidersManager.java#L55

### To Reproduce

Could I know more information about the Change Currency Usage please 
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/API/src/main/java/com/bgsoftware/superiorskyblock/api/handlers/ProvidersManager.java#L55

**Comment by OmerBenGera** [comment]
The EconomyProvider that will be set will be used for upgrade costs and warp costs.
For island bank actions, check out setBankEconomyProvider method.

**Comment by OmerBenGera** [comment]
Also, you already opened an issue.
There's no need to open a new one.
