### ISSUE TITLE
Island top dont show #1

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#911]
### Minecraft's Version

Minecraft 1.18.1
Purpur latest build

### Plugin's Version

Latest dev build #510

### Describe the bug

Top #1 of island dont show in /island top, it show only #2 #3 ect

### To Reproduce

Make /island top in game

### Additional Information

![152667269-862e0828-d6be-4e97-8ea7-fdf02726369e](https://user-images.githubusercontent.com/98712497/152687798-9acbaee5-098a-484f-8644-ede228feb26b.png)

**Comment by OmerBenGera** [comment]
Does it happen with default files as well?

**Comment by DuckyDou** [comment]
Yes.

Is since 1.8.4.

**Comment by DuckyDou** [comment]
> Does it happen with default files as well?

Yes

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
Send me your menu file please.

**Comment by DuckyDou** [comment]
Im using the default top menu

**Comment by DuckyDou** [comment]
Issue is same on default or not

**Comment by OmerBenGera** [comment]
Mind taking a video/gif when using default menu?

**Comment by DuckyDou** [comment]
What! Strange issue now top #1 show but player-island is not exist..
really a strange issue...

SS2 - 1.8.3
![2022-02-11_15 26 30](https://user-images.githubusercontent.com/98712497/153666485-49917970-bf8d-4be1-b946-d19707eae4b8.png)


SS2 - 1.8.4


![2022-02-11_15 35 46](https://user-images.githubusercontent.com/98712497/153666513-2650afa1-3364-44ab-b904-667e57e3c366.png)

**Comment by DuckyDou** [comment]
With my menu file (top-island) 1.8.3 show player-island and top #1
But with 1.8.4 it's dont show top #1 and no player-island
![2022-02-11_15 38 04](https://user-images.githubusercontent.com/98712497/153666753-bcb252a8-1086-4ca6-b995-d38817017503.png)


menu file
https://www.toptal.com/developers/hastebin/dufahinibi.http

**Comment by OmerBenGera** [comment]
> With my menu file (top-island) 1.8.3 show player-island and top #1 But with 1.8.4 it's dont show top #1 and no player-island ![2022-02-11_15 38 04](https://user-images.githubusercontent.com/98712497/153666753-bcb252a8-1086-4ca6-b995-d38817017503.png)
> 
> menu file https://www.toptal.com/developers/hastebin/dufahinibi.http

Check out latest dev build, the skins should work.

**Comment by DuckyDou** [comment]
Skin work.. but top #1 and player-island no

**Comment by OmerBenGera** [comment]
The issue with the player-island is fixed.
About top island not shown, take a video of the issue using default files.
You have yet to show me that it doesn't work with default files.
