### ISSUE TITLE
Island Top Placeholders. 

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#912]
### Minecraft's Version

1.18.1

### Plugin's Version

SuperiorSkyblock2-1.8.4 (stable)

### Describe the bug

The placeholders don't show the correct place after restart before you do /is top and they update again. 

### To Reproduce

restart server now is top placeholders are fucked.

**Comment by OmerBenGera** [comment]
The top islands are sorted when running /island top.
I will look into why they are not sorted when server starts tho

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed.
If it happens again, lmk
