### ISSUE TITLE
Island upgrades still wont save on local data base

### ISSUE THREAD

**Issue by JoshuaPHYT** [BG-Software-LLC/SuperiorSkyblock2#914]
### Minecraft's Version

[13:48:55 INFO]: Current: git-Purpur-1548 (MC: 1.18.1)*
[13:48:55 INFO]: Previous: git-Purpur-1547 (MC: 1.18.1)
[13:48:55 INFO]: * You are running the latest version

### Plugin's Version

im using the latest dev build #510

### Describe the bug

hmm you said you already fixed this issue. and it will not happend again. but its happening to our server every restart
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/913#issuecomment-1031773221
### To Reproduce

Buy upgrades
Restart server

**Comment by OmerBenGera** [comment]
> This happens as when you upgrade from previous version, the local db for upgrades doesnt have a primary key for the table, whereas the older versions do. Just gotta remove the primary key from the new upgrade table. ![Screenshot from 2022-02-08 16-08-32](https://user-images.githubusercontent.com/29209924/153007071-72fb8d67-366b-4aeb-815b-651f4d5b7bf1.png) You can use db browser to do this.

This is fixed automatically by the plugin.

**Comment by JoshuaPHYT** [comment]
> > This happens as when you upgrade from previous version, the local db for upgrades doesnt have a primary key for the table, whereas the older versions do. Just gotta remove the primary key from the new upgrade table. ![Screenshot from 2022-02-08 16-08-32](https://user-images.githubusercontent.com/29209924/153007071-72fb8d67-366b-4aeb-815b-651f4d5b7bf1.png) You can use db browser to do this.
> 
> This is fixed automatically by the plugin.

I'm using the latest version. but its not automatically Update

**Comment by nissiongot** [comment]
> > This happens as when you upgrade from previous version, the local db for upgrades doesnt have a primary key for the table, whereas the older versions do. Just gotta remove the primary key from the new upgrade table. ![Screenshot from 2022-02-08 16-08-32](https://user-images.githubusercontent.com/29209924/153007071-72fb8d67-366b-4aeb-815b-651f4d5b7bf1.png) You can use db browser to do this.
> 
> This is fixed automatically by the plugin.

no it doesnt. I have had 50 people from discord text me to help them out with this who upgraded from 1.8.3 to 1.8.4 and this happened, including  myself.

**Comment by OmerBenGera** [comment]
I will look into it.

**Comment by OmerBenGera** [comment]
I am closing this as it seems to be fixed.
If it happens again, lmk
