### ISSUE TITLE
Islands chest issues

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#915]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b510

### Describe the bug

Islands chests get big issues : 
> island-chests:
> The chest title.
> chest-title: '&4Coffre d''ile'
> Default amount of pages.
> You can set this value to 0 to not have any pages by default.
> default-pages: 16
> Default size for the pages.
> default-size: 6

Player get 16 chests by default, and I have nothing to increase it (so player can't get more than 16 chests)
But some player reported me that islanbds chests get issue where there were resetted/changed order.

So what we did : 
- put a renamed item in each chest (in is chest we set a paper called "paper number 1", in chest 2 a paper called "paper number 2", etc.)

After the first restart : 
It created some new is chest (but only for this island, not for everyone), it changed the content of some chests into another.
Also, we can see that new created chest are not  empty

After second restart, same, it created new chests, and changed the content of default chests to the new created chests

And after the third restart : 
is chest 1 : empty
is chest 2 : empty
is chest 3 : paper number 3
is chest 4 : empty
is chest 5 : empty
is chest 6 : empty
is chest 7 : empty
is chest 8 : empty
is chest 9 : empty
is chest 10 : empty
is chest 11 : empty
is chest 12 : empty
is chest 13 : empty
is chest 14 : empty
is chest 15 : empty
is chest 16 : paper number 16
is chest 17 : empty
is chest 18 : paper number 1
is chest 19 : paper number 2
is chest 20 : empty
is chest 21 : paper number 5
is chest 22 : paper number 4
is chest 23 : paper number 18
is chest 24 : paper number 22
is chest 25 : empty
is chest 26 : paper number 20
is chest 27 :  empty
is chest 28 :  empty
is chest 29 :  empty
is chest 30 :  empty
is chest 31 :  empty
is chest 32 :  paper number 17
is chest 33 :  empty
is chest 34 :  empty
is chest 35 :  empty
is chest 36 :  empty

new is chests compared to day 2 : 

is chest 37 : paper number 7
is chest 38 : paper number 13
is chest 39 : paper number 9 
is chest 40 : paper number 6
is chest 41 : paper number  21
is chest 42 : paper number 11
is chest 43 : paper number 15
is chest 44 : paper number  23
is chest 45 : paper number 14
is chest 46 : paper number 19
is chest 47 : paper number 8
is chest 48 : paper number 10
is chest 49 : paper number 12

### To Reproduce

Put items in all your islands chests and wait after some restarts

### Additional Information

- Using MySQL
- Upgrades disabled
- My chests are renamed by default (I know we had an issue because of this) https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/622
- I  can provide all my files in private

**Comment by OmerBenGera** [comment]
I dont understand what the issue is...
Contents of chest X moves to chest Y?

**Comment by WarnDa** [comment]
> I dont understand what the issue is... Contents of chest X moves to chest Y?

Yes, I'm changing my message because I understand badly the tests, I thought some chests were resetted but not, it justs creates new islands chests and put content of is chest X to the is chest Y

**Comment by WarnDa** [comment]
I finished editing message. you can now read

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's fixed.
