### ISSUE TITLE
Waxing a stack of copper blocks deletes the stack

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/SuperiorSkyblock2#916]
### Minecraft's Version

Purpur 1.18.1 1467

### Plugin's Version

dev 456

### Describe the bug

Whenever waxing a stacked block of copper blocks, the stack will break (tag will disappear, only drops 1 block when mined)

### To Reproduce

1. Enable stacking of copper blocks in the config
2. Stack some copper blocks
3. Wax the stacked block

### Additional Information

https://www.youtube.com/watch?v=9T-GJiWjtaI

**Comment by Skizzles** [comment]
Able to confirm this on 518 as well

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
