### ISSUE TITLE
Islands don't get created on Build #518

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#917]
### Minecraft's Version

1.18

### Plugin's Version

Build #518

### Describe the bug

islands don't get created. Islands get disbanded when starting server.

### To Reproduce

update to Build #518, create and island. It will actually load the schematic and set you a island home spawn but doesn't really creates and island data for you. You can't do nothing. 
When you restart the server, the island gets completely disbanded. 

### Additional Information

I revert to #513 and this issue is not occurring there.

Also, when will you fix the missions getting reset after server restarts bug?

**Comment by evildeedz** [comment]
Make sure to go to your plugin folder > SuperSkyblock2 Folder > Modules > check if there are 2 nashborn-engine jar files. If there are delete the previous one.. restart your server and see if this still happens.

**Comment by Trinchezito** [comment]
> 

Only 1. 
![image](https://user-images.githubusercontent.com/98068350/153760142-8fa18a71-b330-4019-93c7-ba44ee9b0b4d.png)
![image](https://user-images.githubusercontent.com/98068350/153760154-49cdbbc4-568d-4b99-a1e3-f1eff8078542.png)
I only get processing your request message. It creates an island but it doesn't assign it to me. I can do /is go, but i cannot interact. Then, when i restart the server it gets disbanded.

**Comment by Trinchezito** [comment]
So, I went back build by build. This doesn't happen on Build #514. So, it only happens from Build #515+

There are no errors on console.

**Comment by Skizzles** [comment]
Able to confirm this issue.

**Comment by Skizzles** [comment]
Hello @Trinchezito could you confirm that this is resolved? I tested this on the latest dev build and mine seems to be functioning.

**Comment by Trinchezito** [comment]
> 

Thank you. It works now tested on Build #526 . <3 Thanks for the support. We love you
