### ISSUE TITLE
Item rewards are not given when inventory is full

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#918]
### Minecraft's Version

Paper version git-Paper-175

### Plugin's Version

1.8.4.518

### Describe the bug

When completing a challenge, item rewards are not given, when the players inventory is full

### To Reproduce

Fill your inventory and complete any challenge with items reward

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
