### ISSUE TITLE
could not convert database properly

### ISSUE THREAD

**Issue by Neige7** [BG-Software-LLC/SuperiorSkyblock2#919]
### Minecraft's Version

Paper(790) 1.16.5-R0.1-SNAPSHOT

### Plugin's Version

b155 -> the latest build

### Describe the bug

[2022-02-13-1.log.gz](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8054868/2022-02-13-1.log.gz)

the latest bulid could not converts it properly

### To Reproduce

[SuperiorSkyblock2-b155.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8054871/SuperiorSkyblock2-b155.zip)

### Additional Information

I use mariadb

**Comment by OmerBenGera** [comment]
What is your discord?
I want to look into it through discord and give you instructions there.

**Comment by Neige7** [comment]
> 

Neige#8588

**Comment by Neige7** [comment]
[neige_2022_02_19.z01.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8102545/neige_2022_02_19.z01.txt)
[neige_2022_02_19.z02.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8102546/neige_2022_02_19.z02.txt)
[neige_2022_02_19.z03.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8102547/neige_2022_02_19.z03.txt)
[neige_2022_02_19.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/8102548/neige_2022_02_19.zip)

**Comment by OmerBenGera** [comment]
Fixed :)
