### ISSUE TITLE
Problem with island level

### ISSUE THREAD

**Issue by mazurrr** [BG-Software-LLC/SuperiorSkyblock2#921]
### Minecraft's Version

[1.17.1 Airplane](https://airplane.gg/dl/launcher-airplane1.17.1.jar)

### Plugin's Version

1.8.4 - latest stable version

### Describe the bug

Random islands have issue to calculate their level. Island's worth works correctly. Despite that we still have some exceptions where for example island is worth $60 000 and it's level is 0 (when someone else's island worth is $30 000 and their level is 15)

### To Reproduce

Actually I wasn't doing anything. Everything was fine for the last 2 weeks since we opened the server. I wasn't changing any configs or updating jar. Actually I updated jar file few minutes ago just to check if this will solve my issue but it didn't

### Additional Information

CASE 1 - Normally working island level (99% cases)
<img width="469" alt="Zrzut ekranu 2022-02-14 o 00 54 19" src="https://user-images.githubusercontent.com/54754163/153781052-77d36d4e-2095-4356-a2aa-34a3241a1cec.png">
Translate:
Worth: 597
Level: 11
CASE 2 - Island that's not able to calculate their level probably (rare case but it's still a problem for some player)
<img width="499" alt="Zrzut ekranu 2022-02-14 o 00 57 30" src="https://user-images.githubusercontent.com/54754163/153781139-e6bfd908-4a56-47ce-8144-a9512a3d269a.png">
Translate:
Worth: 66 934 usd
Level: 0

**Comment by OmerBenGera** [comment]
How did you configure your levels?

**Comment by Eth4nSP** [comment]
![image](https://user-images.githubusercontent.com/94498054/154788202-aa52aa64-9f4a-41bb-a2fa-704b3d44aed0.png)
is this the configuration?

**Comment by OmerBenGera** [comment]
There is a levels file under the block-values folder

**Comment by OmerBenGera** [comment]
Any news regarding this?
