### ISSUE TITLE
Admin rankup command doesn't work

### ISSUE THREAD

**Issue by KibbaCrafteR** [BG-Software-LLC/SuperiorSkyblock2#923]
### Minecraft's Version

1.8.8

### Plugin's Version

1.8.4

### Describe the bug

The Island Command Admin /is admin rankup works but when i do /is upgrades doesnt update it there and also doesnt work in a way and says "Successfully updated the level of the upgrade hoppers-limit for KibbaX's island." but the upgrade doesnt work

### To Reproduce

The Island Command Admin /is admin rankup works but when i do /is upgrades doesnt update it there and also doesnt work in a way and says "Successfully updated the level of the upgrade hoppers-limit for KibbaX's island." but the upgrade doesnt work

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it works.

**Comment by KibbaCrafteR** [comment]
Still No
Like if i set it to /is admin setupgrade Island hoppers-limit 2 it will update to is upgrades but when i do /is admin rankup island hoppers-limit it wont

**Comment by OmerBenGera** [comment]
Do you have `/is admin setupgrade` as a command for your upgrade?

**Comment by OmerBenGera** [comment]
Any news regarding this?
