### ISSUE TITLE
Item frames, armor stands and another entities from items don't come back after placing when limit is full

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#924]
### Minecraft's Version

1.17.1 Purpur

### Plugin's Version

d518

### Describe the bug

As in title - item frames, armor stands and another entities from items don't come back after placing when limit is full.

Items I found that don't return:
- item_frame
- glow_item_frame
- armor_stand
- all spawn eggs

Minecarts thankfully works fine

### To Reproduce

- Set limit in island for item frame, armor stand etc.
- Reach limit of that entity
- Place/spawn this entity again and see, how wonderful item doesn't come back after disappearing from ground

**Comment by OmerBenGera** [comment]
The entity limit system is being recoded and all of the mentioned issues will be fixed in this update.
