### ISSUE TITLE
There is no sound when you change island settings in GUI

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#925]
### Minecraft's Version

1.17.1 Purpur

### Plugin's Version

d518

### Describe the bug

Change island settings in GUI doesn't make any sound.

### To Reproduce

- Type `/is settings`
- Change some settings
- Listen to beautiful soun... oh, wait, there is no sound :<

**Comment by OmerBenGera** [comment]
Upload your menu file to pastebin and send it here.

**Comment by Ynfuien** [comment]
https://pastebin.com/SA5dvJi5

It's default one. When I have any bug on my server, I download latest dev build and upload it to the testing server, so I could be sure, that this bug isn't my fault.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
