### ISSUE TITLE
Shears mushroom issue

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#926]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b518

### Describe the bug

If you get "animal-spawner" on false in your /is settings, 
when you try to shears an mushroom cow, it won't create a cow but it will only drop the red mushrooms.

### To Reproduce

set animal spawner to false, shears mushroom.

### Additional Information

 https://youtu.be/u898OhKXLZ8

**Comment by OmerBenGera** [comment]
The issue turned to be an issue with WildStacker.
Update to latest version of WildStacker and it will be fixed.
