### ISSUE TITLE
Island Missions

### ISSUE THREAD

**Issue by KibbaCrafteR** [BG-Software-LLC/SuperiorSkyblock2#928]
### Minecraft's Version

1.8.8

### Plugin's Version

1.8.4

### Describe the bug

Hello Island missions reset after restarting the server

### To Reproduce

Hello Island missions reset after restarting the server

**Comment by OmerBenGera** [comment]
Use latest dev build, let me know if it still occurs.

**Comment by rentexfamily** [comment]
It is still occurs.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that.
