### ISSUE TITLE
SERVER auto stop when start

### ISSUE THREAD

**Issue by Frodwo** [BG-Software-LLC/SuperiorSkyblock2#930]
### Minecraft's Version

paper 1.18.1 latest

### Plugin's Version

Dev #518

### Describe the bug

when update 1.8.4 -> Dev #518

### To Reproduce

when update 1.8.4 -> Dev #518
SERVER auto stop when start

### Additional Information

https://controlc.com/be3d41f1

**Comment by Frodwo** [comment]
I wanted to update to the latest version to fix the #914 issue but these things happened. 
Dev #515 I also tried

**Comment by Frodwo** [comment]
When I turn the plugin back to 1.8.4, my player say issue #914 is fix

**Comment by OmerBenGera** [comment]
You have two nashorn engine modules.
Delete one of them and start again.
Let me know if it fixes the issue.

**Comment by Frodwo** [comment]
it fixed, thanks!!
