### ISSUE TITLE
Island Missions reset after server restart

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/SuperiorSkyblock2#931]
### Minecraft's Version

This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-399 (MC: 1.17.1)

### Plugin's Version

[12:07:24 INFO]: SuperiorSkyblock2 version 1.8.4.518
[12:07:24 INFO]: Feature packed Skyblock core.
[12:07:24 INFO]: Website: https://bg-software.com/
[12:07:24 INFO]: Author: Ome_R

### Describe the bug

So I have couple of missions sorted in categories and when player completes an mission, no matter of time how much passes before restart, it still get reset.
I have connected plugin to mysql from start.

Another thing I notice, if you finish 1st mission and you start doing progress for 2nd mission, after server restart, 1st mission get reset but 2nd mission progress is still there.

So plugin is automatically saving progress but not completion?

### To Reproduce

1. Finish or get progress in mission
2. Restart server

### Additional Information

I got this error everytime:
https://paste.gg/p/anonymous/f98afdf1b73e44859ec771137f9e2332

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that.
