### ISSUE TITLE
Farming missions Melon and Pumpkin bug

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#935]
### Minecraft's Version

Paper version git-Paper-175 (MC: 1.18.1)

### Plugin's Version

1.8.4.523

### Describe the bug

When Melon or Pumpkins are alone in a farming mission, progress is not counted. When they are together in a mission, it works fine.

### To Reproduce

Create a farming mission with only a melon or only a pumpkin to track and try to do some progress.

### Additional Information

In source code handling farming missions is this section (starting line 199). Is it possible that the lines `blockTypeName = "MELON";` and `blockTypeName = "PUMPKIN";` are switched?

```java
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onBlockPlace(BlockPlaceEvent e) {
        String blockTypeName = e.getBlock().getType().name();

        switch (blockTypeName) {
            case "PUMPKIN_STEM":
                blockTypeName = "MELON";
                break;
            case "MELON_STEM":
                blockTypeName = "PUMPKIN";
                break;
            case "BAMBOO_SAPLING":
                blockTypeName = "BAMBOO";
                break;
        }

        if (!isMissionPlant(blockTypeName))
            return;

        UUID placerUUID = getPlacerUUID(e.getPlayer());

        if (placerUUID == null)
            return;

        playerPlacedPlants.put(e.getBlock().getLocation(), placerUUID);
    }
```

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by Davisiiiik** [comment]
It works now, thank you.
