### ISSUE TITLE
Skinrestorer and latest dev build

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#936]
### Minecraft's Version

Purpur-1561 (MC: 1.18.1)

### Plugin's Version

SuperiorSkyblock2-1.8.4-b523

### Describe the bug

Skinrestorer dont work with SS2 (/island top)

Im using skinrestorer in bungeecord and spigot side

### To Reproduce

Server offline mode, use skin restorer and check /island top

### Additional Information

![skin_issu](https://user-images.githubusercontent.com/98712497/154612372-5d13a3a2-46d8-4e42-ae70-fa637572ea17.png)
![skin2](https://user-images.githubusercontent.com/98712497/154612375-ec0a0bd5-50d9-406a-aab7-1d813f2f12a4.png)

**Comment by OmerBenGera** [comment]
You must have SkinsRestorer installed on your spigot server

**Comment by OmerBenGera** [comment]
It seems like when having SkinsRestorer installed when having BungeeCord, trying to get skins return null for the skins.
It's not an issue with SSB, but with SkinsRestorer.

**Comment by DuckyDou** [comment]
work with 1.8.3 of ss2

**Comment by OmerBenGera** [comment]
I talked with the SkinsRestorer developers, and this is currently not possible to communicate with the SkinsRestorer instance on the Bungee server. However, if you get rid of the SkinsRestorer on your Spigot server, the plugin will try to get the skin of the player after SkinsRestorer changed it. It may not work after one attempt, and you will have to re-join the server to see your skin. However, it will work eventually :)
