### ISSUE TITLE
Nothing in my chest on default islands

### ISSUE THREAD

**Issue by GrayR0ot** [BG-Software-LLC/SuperiorSkyblock2#937]
### Minecraft's Version

paper-1.18.1

### Plugin's Version

Latest

### Describe the bug

Hi 
I'm having nothing in my chest on default islands
`default-containers:
  # Should this setting be enabled?
  enabled: true
  containers:`
This setting is toggled
and there is a lot of items

### To Reproduce

Only create an island with setting toggled

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
