### ISSUE TITLE
"only-natural-blocks" not working.

### ISSUE THREAD

**Issue by rentexfamily** [BG-Software-LLC/SuperiorSkyblock2#938]
### Minecraft's Version

[20:22:36 INFO]: This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
Previous version: git-Paper-399 (MC: 1.17.1)

### Plugin's Version

[20:22:25 INFO]: SuperiorSkyblock2 version 1.8.4.520
[20:22:25 INFO]: Feature packed Skyblock core.
[20:22:25 INFO]: Website: https://bg-software.com/
[20:22:25 INFO]: Author: Ome_R

### Describe the bug

So when you place and pumpkin and destroy it, you get an progress in mission when `only-natural-blocks: true` is defined in mission's yml.

Here's my mission: https://paste.gg/p/anonymous/e2d38fe0c83f471e9f36012ff2b2aaaa

### To Reproduce

1. Add `only-natural-blocks: true` into mission's yml
2. Start server
3. Place pumpkin (or any other block in mission)
4. Destroy it
5. _You got progress, fu3k._

### Additional Information

No error or warning in console.

**Comment by OmerBenGera** [comment]
I will look into that.
However, you configured your mission incorrectly. You are missing a can-complete item as well as setting the upgrade's level in the commands section.
Check how upgrades should be configured on the wiki.

**Comment by dusan01** [comment]
Any news on this? With proper config, it still counts all blocks, placed and natural.

**Comment by OmerBenGera** [comment]
I said I will look into that. There is no need to bump the issue

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
