### ISSUE TITLE
Superiorskyblock spawner rate

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/SuperiorSkyblock2#94]
![image](https://user-images.githubusercontent.com/61563491/109437313-34e49280-7a1c-11eb-8b42-b16d8287c3f5.png)

Displays Amount 4 but only spawns two and the spawner rate doesn't seem to increase when viewing the spawner stats (Shift right click)

**Comment by OmerBenGera** [comment]
The spawn rates doesn't change the spawn count, but only the amount of ticks until spawning the next entity.
What's the spawner boost on your island?

**Comment by YouSeeMeRunning2** [comment]
The spawner boost was x2

**Comment by OmerBenGera** [comment]
So the spawning delay should be between 100 ticks (5 seconds) and 400 ticks (20 seconds), weird.
Are you using latest dev build of SSB?

**Comment by YouSeeMeRunning2** [comment]
Build 76

**Comment by OmerBenGera** [comment]
Are you able to replicate the issue on a server with only SSB and WS installed?

**Comment by OmerBenGera** [comment]
Hey, how did you fix the issue?

**Comment by YouSeeMeRunning2** [comment]
I didn't. Jusy

**Comment by YouSeeMeRunning2** [comment]
So I've tried with x2 X3 and x4

**Comment by OmerBenGera** [comment]
Use latest verison of SSB and WildStacker if you aren't using it already, as I have been told that it fixes the issue

**Comment by YouSeeMeRunning2** [comment]
https://gyazo.com/9a65fe891e76540463f1c91859db345b

Any way to fix this and make it more smooth?

**Comment by OmerBenGera** [comment]
> 
> 
> https://gyazo.com/9a65fe891e76540463f1c91859db345b
> 
> Any way to fix this and make it more smooth?

ahm not really - it changes the spawn rate a few ticks after it's changed by minecraft, otherwise it will not work correctly.

**Comment by YouSeeMeRunning2** [comment]
It would seem like the upgrade isn't applying to preexisting islands 
![image](https://user-images.githubusercontent.com/61563491/110962208-9e33a200-8348-11eb-837a-8780d80439b5.png)

**Comment by OmerBenGera** [comment]
> 
> 
> It would seem like the upgrade isn't applying to preexisting islands (This user has x2 spawner boost)
> ![image](https://user-images.githubusercontent.com/61563491/110962208-9e33a200-8348-11eb-837a-8780d80439b5.png)

Check their spawner boost using /is admin show.
Everytime the spawner spawns an entity, the plugin will attempt to change the delay of the spawner, so it doesn't matter if the islands are preexisting or not

**Comment by YouSeeMeRunning2** [comment]
![image](https://user-images.githubusercontent.com/61563491/110965376-0768e480-834c-11eb-804a-4a8ee1340f3f.png)

**Comment by YouSeeMeRunning2** [comment]
I created a new island and it seems to be working correctly. On my island, I'm unable to get the high spawn times like seen in the image above

**Comment by OmerBenGera** [comment]
Well, idk what the issue is. There's no difference between new islands and existing islands. The only thing that can cause it is that the spawner rates multiplier isn't set correctly.

**Comment by YouSeeMeRunning2** [comment]
spawner-rates:
    '1':
      price: 25000000.0
      commands:
        - 'island admin setupgrade %player% spawner-rates 2'
        - 'island admin setspawnerrates %player% 2'
        - 'island admin msgall %player% &e&lSkyblock &7Your spawner-rates multiplier was increased to x2!'

**Comment by YouSeeMeRunning2** [comment]
Islands were created on b81 and then updated to b84

Wildstacker b80 and then updated to b83

**Comment by OmerBenGera** [comment]
Check using /is admin show if they have the spawn rates... This means nothing, especially when you don't have them synced with the updates (not sure why tbh)

**Comment by YouSeeMeRunning2** [comment]
I have already shown you that on the island they have spawner-rate 2
![image](https://user-images.githubusercontent.com/61563491/110993179-dc43bc80-836e-11eb-8117-a5bac74728b0.png)

**Comment by OmerBenGera** [comment]
Check the actual spawn rate. not the upgrade level.

**Comment by YouSeeMeRunning2** [comment]
![image](https://user-images.githubusercontent.com/61563491/110997244-0b5d2c80-8375-11eb-8d0d-8f34e97454bc.png)

**Comment by OmerBenGera** [comment]
Try setting the multiplier to 3, check if it works after that

**Comment by YouSeeMeRunning2** [comment]
![image](https://user-images.githubusercontent.com/61563491/110998683-1add7500-8377-11eb-8370-ac826ed4094e.png)
![image](https://user-images.githubusercontent.com/61563491/110998707-2335b000-8377-11eb-82fa-7412c7b16170.png)

**Comment by OmerBenGera** [comment]
if you break the spawner and place it back?
It just makes 0 sense how it works with some spawners and with some it doesn't

**Comment by YouSeeMeRunning2** [comment]
![image](https://user-images.githubusercontent.com/61563491/110999264-08177000-8378-11eb-86c4-4538ff067c1f.png)
![image](https://user-images.githubusercontent.com/61563491/110999293-11084180-8378-11eb-903f-cb00ca6e8f15.png)

**Comment by YouSeeMeRunning2** [comment]
I don't understand how it works on new islands but doesn't work on the current ones :)

**Comment by OmerBenGera** [comment]
It will not work for placed spawners for the first time - it will only work after the spawner is spawning a mob for the first time.

**Comment by YouSeeMeRunning2** [comment]
![image](https://user-images.githubusercontent.com/61563491/111036909-9b54b200-8419-11eb-9bdf-16b3c1a415bd.png)
![image](https://user-images.githubusercontent.com/61563491/111036918-a60f4700-8419-11eb-84a2-999f6e52e9cc.png)
I've had the cow spawn in three times now

**Comment by OmerBenGera** [comment]
Unless you are not gonna let me know how to replicate it, sending these pictures will not help in any way

**Comment by YouSeeMeRunning2** [comment]
Islands were created on b81 and then updated to b84

Wildstacker b80 and then updated to b83

Create an island on a previous version and them update plugin versions

**Comment by OmerBenGera** [comment]
Sorry for the late response.
Does it still occur?

**Comment by OmerBenGera** [comment]
???
