### ISSUE TITLE
how can ı get island owner is player with api ?

### ISSUE THREAD

**Issue by kurkinsnetwork** [BG-Software-LLC/SuperiorSkyblock2#941]
### Minecraft's Version

paper 1.17.1

### Plugin's Version

latest dev build 526

### Describe the bug

how can ı get island owner is player with api ?

### To Reproduce

how can ı get island owner is player with api ?

### Additional Information

how can ı get island owner is player with api ?

**Comment by OmerBenGera** [comment]
Island#getOwner. If you want to get the island of the player, use SuperiorPlayer#getIsland
https://bg-software.com/superiorskyblock/api/
