### ISSUE TITLE
Placeholder superior_island_flag_<flag> doesnt work

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#942]
### Minecraft's Version

Paper version git-Paper-207 (MC: 1.18.1)

### Plugin's Version

1.8.4.526

### Describe the bug

When using placeholder `%superior_island_flag_<flag>%`, output is empty no matter which flag you use. It doesnt work in menus nor via papi parse.

Tested:
- %superior_island_flag_always_day%
- %superior_island_flag_always_middle_day%
- %superior_island_flag_pvp%

### To Reproduce

Use command (with PlaceholdersAPI plugin): /papi parse me %superior_island_flag_always_day%
OR
Use these placeholders in menus

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Davisiiiik** [comment]
It works now in text and in CMI commands in menus (I didnt try commands from more other plugins), but when I use it in SuperiorSkyblock command (both in menu or in chat) (ie: `is admin msgall %player% %player% pvp %superior_island_flag_pvp%`, or `is admin setsettings %player% pvp %changeoutput_equals_{superior_island_flag_pvp}_true_true_false%`, the placeholder is not parsed.

**Comment by OmerBenGera** [comment]
> It works now in lores and in CMI commands in menus (I didnt try commands from more other plugins), but when I use it in SuperiorSkyblock command (both in menu or in chat) (ie: `is admin msgall %player% %player% pvp %superior_island_flag_pvp%`, or `is admin setsettings %player% pvp %changeoutput_equals_{superior_island_flag_pvp}_true_true_false%`, the placeholder is not parsed.

Placeholders are not supported in commands
