### ISSUE TITLE
GUI Issue

### ISSUE THREAD

**Issue by granpacho** [BG-Software-LLC/SuperiorSkyblock2#943]
### Minecraft's Version

1.17.1 Paper-402

### Plugin's Version

Superior Skyblock Verison: 1.8.3

### Describe the bug

So when I go to another GUI in the plugin it gives a flicker when I do it with a command and on the wiki it says use [tp] or [biome] and I used it and it says in chat "Usage: /is biome" or "Usage: /is tp" and it doesn't do it for me. Also when I do the brackets thing for permissions it says "Cannot find a player called" then it is blank afterward. But it only happens in my custom menu in the main regular menu where I tested it, I did it with the commands and it works fine. 

### To Reproduce

Use a custom menu and set the commands. 

### Additional Information

https://gyazo.com/f4111bc1f15251c77d42b14cc78c4bd7 <- With brackets 
https://gyazo.com/46b974e8e3c7baa7da6e13513afd4b38 <- Without Brackets 

MENUS: 
[menus.zip](https://github.com/BG-Software-LLC/WildStacker/files/8106109/menus.zip) - MENU WITH COMMANDS

[menus2.zip](https://github.com/BG-Software-LLC/WildStacker/files/8106126/menus2.zip) - MENU WITH BRACKETS

**Comment by OmerBenGera** [comment]
Upload the menus to pastebin and send them here

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by granpacho** [comment]
Sorry, here: 


Control.yml (CUSTOM MENU)
https://pastebin.com/T5KUA7RW

Control-Panel.yml
https://pastebin.com/2iagPMyv

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that
