### ISSUE TITLE
Spam lava, wat

### ISSUE THREAD

**Issue by DuckyDou** [BG-Software-LLC/SuperiorSkyblock2#944]
### Minecraft's Version

Purpur 1.18.1 - #1563

### Plugin's Version

SuperiorSkyblock2-1.8.4-b526

### Describe the bug

Hello, when a player is not on an island, he can put lava and water to be able to use-bug (it's only visual from the player's side, nobody can see it) but it causes anti-cheat alerts and allows access to a part of the island that is restricted for visitors.

### To Reproduce

Spam click with lava or bucket on other player island

### Additional Information

https://user-images.githubusercontent.com/98712497/155027702-8d180252-0c1d-452d-bc36-c88fb62982e0.mp4

**Comment by OmerBenGera** [comment]
This is not fixable, also its not a bug.
If the anticheat sends alerts on this, contact their developers for false alarms.

**Comment by DuckyDou** [comment]
why with worldguard lava dont stay?

**Comment by OmerBenGera** [comment]
I will look into that again

**Comment by SwartZCoding** [comment]
I think it's just a visual bug ?

**Comment by DuckyDou** [comment]
Yes its visual but it allows to go to places on the islands that are not open to visitors.

**Comment by OmerBenGera** [comment]
I can't replicate the issue.
It works fine for me

**Comment by DuckyDou** [comment]
Lava and water are removed instantly for you? Because i have tested with 1.15 , 1.17 , 1.18 of spigot and paper issue persist

Same with ssb 1.8.3

**Comment by OmerBenGera** [comment]
> Lava and water are removed instantly for you? Because i have tested with 1.15 , 1.17 , 1.18 of spigot and paper issue persist
> 
> Same with ssb 1.8.3

Yes. Worked fine for me.

**Comment by DuckyDou** [comment]
Ok so strange because with new fresh installation, only ssb installed i have the issue lmao, just spam lava and water .... wtf

**Comment by OmerBenGera** [comment]
> Ok so strange because with new fresh installation, only ssb installed i have the issue lmao, just spam lava and water .... wtf

Probably due to lag of the server or something.
Anyways, I can't fix it and it's only a visual glitch.
