### ISSUE TITLE
Leaving islands and returning to the main world

### ISSUE THREAD

**Issue by WaldperlachFabi** [BG-Software-LLC/SuperiorSkyblock2#945]
### Minecraft's Version

1.18.1 - Spigot

### Plugin's Version

1.8.4

### Describe the bug

I want to get back to the main world and when useing /is leave it says that i can’t leave. 

### To Reproduce

/is leave

**Comment by OmerBenGera** [comment]
/is leave is to leave your island.
You cant go to the main world using the plugin. You can set warps or spawn using other plugins and give players access to these commands.

**Comment by WaldperlachFabi** [comment]
Yeah I already tried that, but if I write in the chat after warping back to the main world the others doesn’t see that.
