### ISSUE TITLE
Teleport cause sync chunk load

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#946]
### Minecraft's Version

1.16.5 airplane

### Plugin's Version

b516

### Describe the bug

https://imgur.com/nNt6Lom

Teleport on warp cause sometimes sync chunk loading, maybe use paperlib#teleportAsync?

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Teleports of players are already using PaperLib#teleportAsync.

Take a spark profiler so we can understand what causes chunks to load on main thread.

**Comment by exzolink** [comment]
> Teleports of players are already using PaperLib#teleportAsync.
> 
> Take a spark profiler so we can understand what causes chunks to load on main thread.

Can this method run sync loading? 
https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/3b8ec1c462b40396c603285f8dbb98c403222021/v1_18_R1/src/main/java/com/bgsoftware/superiorskyblock/nms/v1_18_R1/mapping/level/WorldServer.java#L162

**Comment by OmerBenGera** [comment]
Take a spark profiler so we can understand what causes chunks to load on main thread.

**Comment by exzolink** [comment]
> Take a spark profiler so we can understand what causes chunks to load on main thread.

Yes, i'm waiting for lag spike

**Comment by exzolink** [comment]
I didn’t have time to take a profiler, I was not at home, but here’s what the paper writes https://pastebin.com/1hA4Fe79

**Comment by exzolink** [comment]
> Take a spark profiler so we can understand what causes chunks to load on main thread.

I didn’t have time to take a profiler, I was not at home, but here’s what the paper writes https://pastebin.com/1hA4Fe79

**Comment by OmerBenGera** [comment]
> > Take a spark profiler so we can understand what causes chunks to load on main thread.
> 
> I didn’t have time to take a profiler, I was not at home, but here’s what the paper writes https://pastebin.com/1hA4Fe79

This is async chunk loading

**Comment by exzolink** [comment]
But on main thread

**Comment by OmerBenGera** [comment]
> But on main thread

This is the logic of how the async works.
You can contact Paper to optimize it even further, it has nothing to do with the plugin.

The plugin uses getChunkAtAsync all the time. It will not load chunks synchronized.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by exzolink** [comment]
There was no more problem
