### ISSUE TITLE
Nether portal don’t work

### ISSUE THREAD

**Issue by WaldperlachFabi** [BG-Software-LLC/SuperiorSkyblock2#947]
### Minecraft's Version

1.18.1

### Plugin's Version

Newest

### Describe the bug

If i step into the nether portal on the island nothing habens and i don’t get teleported. How can i get to the nether island?

### To Reproduce

Go inside a nether portal

**Comment by Davisiiiik** [comment]
Do you have setting `nether.enabled` set to `true` in config.yml?
Did you unlock nether first if you have `nether.unlock` set to `false`?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by WaldperlachFabi** [comment]
Yeah, it’s working now but the endet dragon spawns on the wrong location in the end. He spawns at 0 0 0 and the island is on 200 100 100 or so.

**Comment by OmerBenGera** [comment]
> Yeah, it’s working now but the endet dragon spawns on the wrong location in the end. He spawns at 0 0 0 and the island is on 200 100 100 or so.

Open a new issue regarding this.
