### ISSUE TITLE
Island top not sorting properly

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#956]
### Minecraft's Version

Paper version git-Paper-207 (MC: 1.18.1)

### Plugin's Version

1.8.4.535

### Describe the bug

In island top sorting by different criteria doesnt work. The placeholders work fine, but when I try to sort by island ratings for example, numbers indicating placement are fine, but islands are not in right order (All heads are still sorted by island level).

### To Reproduce

Create few islands, open is top and try to order them by ratings for example.

### Additional Information

Image indicating the problem: In the 1st position is island with the biggest is level, but in is ratings it should be in 27th position.

![image](https://user-images.githubusercontent.com/79375965/155854718-807ef42d-c4e3-4d37-ac84-473d3c1bd233.png)

**Comment by OmerBenGera** [comment]
Are you using default menu file?

**Comment by Davisiiiik** [comment]
I tried both, my edited and default. I try clean new installation of the plugin.

**Comment by OmerBenGera** [comment]
> I tried both, my edited and default. I will try clean new installation of the plugin.

Okay, sounds good. Let me know once you tried that.

**Comment by Davisiiiik** [comment]
Clean installation, created two islands, default configs, issue still occures.

![image](https://user-images.githubusercontent.com/79375965/155857097-bcb0b615-65b5-45a8-9c5d-838641892995.png)

**Comment by OmerBenGera** [comment]
> 

Wait, I see that the island itself is actually in the correct place, however only the placeholder of its position is incorrect.
Am I right?

**Comment by OmerBenGera** [comment]
> No, sorry for missunderstanding, both pictures are sorted by Ratings, where one of the islands has 5 stars and the second one has 0 stars. So the placeholders are correct, position is bad.

In the screenshot you hover over the first island, however it's placeholder says 2

**Comment by Davisiiiik** [comment]
Island positions in slots dont change when I change the sorting criteria (Ratings, Level, Members, Worth). Only the placeholders change and are correct.

**Comment by OmerBenGera** [comment]
I could replicate the issue. It seems that changing sorting of top islands does not work.

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it still occurs.

**Comment by Davisiiiik** [comment]
Everything works great except one thing. When sorting by players, for some reason 2-player island is 1st and 3-player island is 2nd.

![image](https://user-images.githubusercontent.com/79375965/155858473-6609ddf4-1cf2-4e9a-bf51-d77ac8719bf6.png)

![image](https://user-images.githubusercontent.com/79375965/155858479-7210d181-4b03-4161-9587-7e7c4b9d4f9d.png)

**Comment by DuckyDou** [comment]
I got exactly the same issue!

**Comment by OmerBenGera** [comment]
> I got exactly the same issue!

Only with players?

**Comment by Davisiiiik** [comment]
> Everything works great except one thing. When sorting by players, for some reason 2-player island is 1st and 3-player island is 2nd. Event placeholder is wrong.
> 
> ![image](https://user-images.githubusercontent.com/79375965/155858473-6609ddf4-1cf2-4e9a-bf51-d77ac8719bf6.png)
> 
> ![image](https://user-images.githubusercontent.com/79375965/155858479-7210d181-4b03-4161-9587-7e7c4b9d4f9d.png)

I noticed something. In both cases there are more than one island members, but line `&6&l* &e&lHráči &7{10}` (Hráči in English means Players) show only 1. This number represents the number of players currently on island (any players, not just island members) instead of number of members of island. If the sorting mechanism sorts according to this number, the cause of this issue is clear.

I dont really know what is the intended behaviour (If it should sort by island members count, or total current players physically on island), but I believe, you can solve this issue now easily.

**Comment by OmerBenGera** [comment]
> > Everything works great except one thing. When sorting by players, for some reason 2-player island is 1st and 3-player island is 2nd. Event placeholder is wrong.
> > ![image](https://user-images.githubusercontent.com/79375965/155858473-6609ddf4-1cf2-4e9a-bf51-d77ac8719bf6.png)
> > ![image](https://user-images.githubusercontent.com/79375965/155858479-7210d181-4b03-4161-9587-7e7c4b9d4f9d.png)
> 
> I noticed something. In both cases there are more than one island members, but line `&6&l* &e&lHráči &7{10}` (Hráči in English means Players) show only 1. This number represents the number of players currently on island (any players, not just island members) instead of number of members of island. If the sorting mechanism sorts according to this number, the cause of this issue is clear.
> 
> I dont really know what is the intended behaviour (If it should sort by island members count, or total current players physically on island), but I believe, you can solve this issue now easily.

If it doesnt show the correct amount, I guess the issue is with the way the plugin detects players inside the island.
Do you have PlayerMoveEvent disabled by any chance?

**Comment by Davisiiiik** [comment]
I don't know now, can you tell me, where can I enable, or disable this event?
By the way, I wanna ask you something.

This placeholder I talked about, is it intented to show:
a) Members of island
b) All players currently located on island including visitors

**Comment by OmerBenGera** [comment]
> I don't know now, can you tell me, where can I enable, or disable this event? By the way, I wanna ask you something.
> 
> This placeholder I talked about, is it intented to show: a) Members of island b) All players currently located on island including visitors

You can disable or enalble this event in some forks of Spigot/Paper, in their config file.
About the placeholder, it should show the amount of players that are inside the island - no matter if they are members or visitors.

**Comment by Davisiiiik** [comment]
> > I don't know now, can you tell me, where can I enable, or disable this event? By the way, I wanna ask you something.
> > This placeholder I talked about, is it intented to show: a) Members of island b) All players currently located on island including visitors
> 
> You can disable or enalble this event in some forks of Spigot/Paper, in their config file. About the placeholder, it should show the amount of players that are inside the island - no matter if they are members or visitors.

I checked all three files (bukkit, pigot, paper) and didn't find it, so I think I have it enabled.
Sorry for confusion, if this is the case, this placeholder works fine. I thought it should sort by island member count. You can close this :)
