### ISSUE TITLE
Upgrade commands now executes by player

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#959]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b536

### Describe the bug

Upgrade commands now executes by player, so commands like /s admin ...
dont work for now

### To Reproduce

Try upgrade anything, it will tell you to type /is rankup <upgrade> instead of upgrading

**Comment by Davisiiiik** [comment]
Minecraft version: Paper version git-Paper-207 (MC: 1.18.1)
Plugin version: 1.8.4.536

I have same issue. No command I set in upgrades/config.yml is executed and even my money remains still the same amount. There is only a message in chat "Usage: /island rankup <upgrade>". I am starting my server tomorrow and this is kinda big issue, cause no upgrade works for me.

**Comment by exzolink** [comment]
@OmerBenGera

**Comment by OmerBenGera** [comment]
> @OmerBenGera

There is no need to mention me.
I will look into it when I am home.

**Comment by Trinchezito** [comment]
I confirm this. 

In the upgrade commands we have it to run: island admin setupgrade %player% generator-rates 2

but for some reason its throwing in the chat to run /is rankup <upgrade> instead

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
