### ISSUE TITLE
Command /is top not showing all islands

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#963]
### Minecraft's Version

Paper version git-Paper-207 (MC: 1.18.1)

### Plugin's Version

1.8.4.536

### Describe the bug

When you open `/is top`, there are shown 9 islands in default, but the second page starts showing islands from #11, island #10 is not shown. It doesnt matter how many islands you have shown on one page, everytime one island (which is one place worse than current page and one place better than the next page) is not shown.

### To Reproduce

Create 2 more islands than one page of island top can show on one page and try to find the penultimate island. (ie: set top-islands.yml to show 4 islands on one page, create 6 islands and try to find 5th in `/is top`)

### Additional Information

First image is page 1, second image is page 2.

![image](https://user-images.githubusercontent.com/79375965/156381031-87669adb-7c0c-4ce1-969f-1342b91081e2.png)
![image](https://user-images.githubusercontent.com/79375965/156381069-f2caa8c9-0067-4b9a-91b0-cc27129b3af8.png)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
