### ISSUE TITLE
Blocking Stacking - Doesn't work with some blocks

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/SuperiorSkyblock2#965]
### Minecraft's Version

1.16.5 Paper

### Plugin's Version

#530

### Describe the bug

Block stacking doesn't work with 
  - PRISMARINE_BRICKS
  - DARK_PRISMARINE

### To Reproduce

Enable block stacking and use these blocks

**Comment by YouSeeMeRunning2** [comment]
I'd like to add that PRISMARINE_BRICKS doesn't work on /is top either as a value block
![image](https://user-images.githubusercontent.com/61563491/156901323-6c33145b-755d-4824-a5b0-b8b0e66e2e0e.png)

**Comment by OmerBenGera** [comment]
The issue with stacked blocks is fixed in latest dev build.
About the values menu, mind sharing with me how you configured it?

**Comment by YouSeeMeRunning2** [comment]
Resolved the issue with the gui, all looks good

**Comment by YouSeeMeRunning2** [comment]
https://pastebin.com/waeQnX6c

**Comment by OmerBenGera** [comment]
> https://pastebin.com/waeQnX6c

I think the error is cut. Mind checking if it's the full trace?

**Comment by OmerBenGera** [comment]
Btw, why did you change the version of the plugin in the plugin.yml?

**Comment by YouSeeMeRunning2** [comment]
Using a custom fork that adds some stuff

https://pastebin.com/5GahJd3R
https://pastebin.com/YxJv84Z8

**Comment by OmerBenGera** [comment]
> Using a custom fork that adds some stuff
> 
> https://pastebin.com/5GahJd3R https://pastebin.com/YxJv84Z8

Check out latest dev build, let me know if it still occurs

**Comment by OmerBenGera** [comment]
I am closing this.
If it still occurs, lmk

**Comment by YouSeeMeRunning2** [comment]
https://pastebin.com/QBGEjMLA

**Comment by YouSeeMeRunning2** [comment]
Sorry I forgot to update this, I resolved it

**Comment by OmerBenGera** [comment]
> Sorry I forgot to update this, I resolved it

How did you resolve the issue?

**Comment by YouSeeMeRunning2** [comment]
The guy who manages the fork said a class hadn't initialised https://pastebin.com/QBGEjMLA 

After that I got a new error, https://pastebin.com/93sYMavt which was fixed

**Comment by OmerBenGera** [comment]
How did he correct it?
