### ISSUE TITLE
StatisticsMissions value not show

### ISSUE THREAD

**Issue by thedarkonekiller** [BG-Software-LLC/SuperiorSkyblock2#966]
### Minecraft's Version

paper 1.18.1 last update

### Plugin's Version

1.18.4.536

### Describe the bug

value of statistics not showing
![image_2022-03-04_020756](https://user-images.githubusercontent.com/76535453/156679654-dc9afa27-2e1b-477c-a518-5b8e7a9e7ef3.png)

######################################################
######################################################

# The mission file to use
mission-file: StatisticsMissions

# Whether the mission should be given when completing all requirements.
auto-reward: true

# Should block counts of players get reset when completing the mission?
reset-after-finish: true

# Rewards given when completing the mission.
rewards:
  commands:
    - 'money give %player% 50000'
    - 'is admin msg %player% &e&lExplorateur %player% | &7Tu as remplis avec succès la mission Explorateur I!'

# List of all required blocks must be gathered in order to complete the mission.
required-statistics:
  '1':
    statistics:
      - 'WALK_ONE_CM'
    amount: 25000
  '2':
    statistics:
      - 'SPRINT_ONE_CM'
    amount: 25000

# Icons used in the menus.
icons:
  not-completed:
    type: DIAMOND_BOOTS
    name: '&aExplorateur I'
    lore:
      - '&7Apprendre à Marcher et à Sprinter'
      - ''
      - '&6Tâches:'
      - '&7Marcher 25000 blocs.'
      - '&7Sprinter 25000 blocs.'
      - ''
      - '&6Récompenses:'
      - '&8 - &750000$'
      - ''
      - '&6Blocs parcourus en marchant: &7{value_walk_one_cm}/25000'
      - '&6Blocs parcourus en sprintant: &7{value_sprint_one_cm}/25000'
      - '&6Progression: &7{0}%'
      - '&c&l ✘ &7Non terminé'
  can-complete:
    type: DIAMOND_BOOTS
    name: '&aExplorateur I'
    lore:
      - '&7Apprendre à Marcher et à Sprinter'
      - ''
      - '&6Tâches:'
      - '&7Marcher 25000 blocs.'
      - '&7Sprinter 25000 blocs.'
      - ''
      - '&6Récompenses:'
      - '&8 - &750000$'
      - ''
      - '&6Blocs parcourus en marchant: &725000/25000'
      - '&6Blocs parcourus en sprintant: &725000/25000'
      - '&6Progression: &7100%'
      - '&a&l ✔ &7Cliquez pour échanger votre récompense.'
    enchants:
      DURABILITY: 1
    flags:
      - HIDE_ENCHANTS
  completed:
    type: SPYGLASS
    name: '&aExplorateur I'
    lore:
      - '&7Apprendre à Marcher et à Sprinter'
      - ''
      - '&6Récompenses:'
      - '&8 - &750000$'
      - ''
      - '&6Blocs parcourus en marchant: &725000/25000'
      - '&6Blocs parcourus en sprintant: &725000/25000'
      - '&6Progression: &7100%'
      - '&a&l ✔ &7Déjà réclamé.'

**Comment by thedarkonekiller** [comment]
> ### Minecraft's Version
> paper 1.18.1 last update
> 
> ### Plugin's Version
> 1.18.4.536
> 
> ### Describe the bug
> value of statistics not showing ![image_2022-03-04_020756](https://user-images.githubusercontent.com/76535453/156679654-dc9afa27-2e1b-477c-a518-5b8e7a9e7ef3.png)
> 
> ### To Reproduce
> ######################################################
> 
> ## SuperiorSkyblock 2
> ## Developed by Ome_R
> ######################################################
> 
> # The mission file to use
> mission-file: StatisticsMissions
> 
> # Whether the mission should be given when completing all requirements.
> auto-reward: true
> 
> # Should block counts of players get reset when completing the mission?
> reset-after-finish: true
> 
> # Rewards given when completing the mission.
> rewards: commands: - 'money give %player% 50000' - 'is admin msg %player% &e&lExplorateur %player% | &7Tu as remplis avec succès la mission Explorateur I!'
> 
> # List of all required blocks must be gathered in order to complete the mission.
> required-statistics: '1': statistics: - 'WALK_ONE_CM' amount: 25000 '2': statistics: - 'SPRINT_ONE_CM' amount: 25000
> 
> # Icons used in the menus.
> icons: not-completed: type: DIAMOND_BOOTS name: '&aExplorateur I' lore: - '&7Apprendre à Marcher et à Sprinter' - '' - '&6Tâches:' - '&7Marcher 25000 blocs.' - '&7Sprinter 25000 blocs.' - '' - '&6Récompenses:' - '&8 - &750000$' - '' - '&6Blocs parcourus en marchant: &7{value_walk_one_cm}/25000' - '&6Blocs parcourus en sprintant: &7{value_sprint_one_cm}/25000' - '&6Progression: &7{0}%' - '&c&l ✘ &7Non terminé' can-complete: type: DIAMOND_BOOTS name: '&aExplorateur I' lore: - '&7Apprendre à Marcher et à Sprinter' - '' - '&6Tâches:' - '&7Marcher 25000 blocs.' - '&7Sprinter 25000 blocs.' - '' - '&6Récompenses:' - '&8 - &750000$' - '' - '&6Blocs parcourus en marchant: &725000/25000' - '&6Blocs parcourus en sprintant: &725000/25000' - '&6Progression: &7100%' - '&a&l ✔ &7Cliquez pour échanger votre récompense.' enchants: DURABILITY: 1 flags: - HIDE_ENCHANTS completed: type: SPYGLASS name: '&aExplorateur I' lore: - '&7Apprendre à Marcher et à Sprinter' - '' - '&6Récompenses:' - '&8 - &750000$' - '' - '&6Blocs parcourus en marchant: &725000/25000' - '&6Blocs parcourus en sprintant: &725000/25000' - '&6Progression: &7100%' - '&a&l ✔ &7Déjà réclamé.'
> 
> ### Additional Information
> _No response_

not work with the example mission in the wiki
![2022-03-04_22 23 05](https://user-images.githubusercontent.com/76535453/156843609-7d203ecf-3fc1-4c58-a662-a4d172385f92.png)

**Comment by OmerBenGera** [comment]
The statistics missions jar does not display such information.
Try using regular placeholders from PAPI, let me know if it works for you.

**Comment by OmerBenGera** [comment]
I tested the regular placeholders from PAPI and it doesn't work neither, therefore I added support for built-in placeholders similar to the other missions.
