### ISSUE TITLE
Void Teleport Issue

### ISSUE THREAD

**Issue by DebuffPvP** [BG-Software-LLC/SuperiorSkyblock2#970]
### Minecraft's Version

This server is running Hyperion version TacoSpigot (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.8.4.536

### Describe the bug

# When enabled, players will get teleported upon void fall.
# If they fall not in an island, they will be teleported to spawn.
void-teleport:
  members: true
  visitors: false

When visitors is false and visitors fall in the void they don't get damaged they just keep falling.

### To Reproduce

look in bug description and set it that same way

**Comment by OmerBenGera** [comment]
Do you have visitors damage disabled in your config file?

**Comment by OmerBenGera** [comment]
Any news regarding this?
