### ISSUE TITLE
StatisticsMissions is completly buggy

### ISSUE THREAD

**Issue by thedarkonekiller** [BG-Software-LLC/SuperiorSkyblock2#971]
### Minecraft's Version

papaermc 1.18.1 last update

### Plugin's Version

1.8.4.537

### Describe the bug

StatisticsMissions are completly buggy....
Not show value (view my last report)
Reset mission dont work properly (view screenshots)

### To Reproduce

type commande : /is admin mission TheDarkOneKiller reset explorer_1
![2022-03-04_21 36 12](https://user-images.githubusercontent.com/76535453/156838482-4252323e-a5de-4a10-bbe2-2b9de3308c73.png)
![2022-03-04_21 36 28](https://user-images.githubusercontent.com/76535453/156838498-d12671bd-62e5-48d0-82d2-5c39a5694be7.png)
![2022-03-04_21 35 51](https://user-images.githubusercontent.com/76535453/156838541-40473f05-117c-47eb-9d98-95d32fba0f19.png)

**Comment by OmerBenGera** [comment]
Please upload your mission files to pastebin and send them here so I can test it myself.

**Comment by thedarkonekiller** [comment]
https://pastebin.com/bKG3EEPh

**Comment by OmerBenGera** [comment]
It works fine for me.
When I reset the mission, I can complete it again.
The progress for the mission does not reset of course, as it's based on statistics and this value does not change upon resetting missions.
