### ISSUE TITLE
Block Limit Bypass

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#972]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b536

### Describe the bug

Bypass works with growable blocks like cactus, chorus etc

For example i set 10 cactuses limit, then placed 10 cactuses and some of them are grow, then i break growed part and can place new cactus

### To Reproduce

Set 10 cactuses limit, then place 10 cactuses and wait when some of them are grow, then break growed part and can place new cactus

**Comment by Skizzles** [comment]
I am unable to confirm this issue directly. Can you test this with just SuperiorSkyblock installed?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by exzolink** [comment]
Still works on a fresh install without plugins

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
