### ISSUE TITLE
leaves decay

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#973]
### Minecraft's Version

1.18.1

### Plugin's Version

latest build 539 

### Describe the bug

leaves decay stopped working when i updated to the latest build. 

I don't have worldguard regions with leaf-decay flag. 

### To Reproduce

leaves won't decay

**Comment by OmerBenGera** [comment]
Leaves of schematics do not decay and its intended.
Are you referring to those?

**Comment by Trinchezito** [comment]
> Yes, from those. What i did was spawn a new tree grown from a sapling instead. That did the trick. But when i did a custom Tree, not from a sapling, the leaves didn't decay. So if it's intended then i guess you can close this report.
