### ISSUE TITLE
Is bank balance seems to be buged

### ISSUE THREAD

**Issue by RomualdLewandoski** [BG-Software-LLC/SuperiorSkyblock2#974]
### Minecraft's Version

1.17.1 (Paper latest version)

### Plugin's Version

[Version 1.8.4]

### Describe the bug

Is bank don't show the correct bank account's value

### To Reproduce

open is bank, deposit something, close and reopen the menu, the balance don't seems to be changed.

### Additional Information

Didn't have this issue with older version of the plugin

**Comment by RomualdLewandoski** [comment]
![image](https://user-images.githubusercontent.com/59136319/157088160-184ca1ac-43f2-41bb-82b8-b529578cd4b0.png)

**Comment by OmerBenGera** [comment]
Update to latest dev build

**Comment by RomualdLewandoski** [comment]
i'm gonna check that , thank for the fast reply
