### ISSUE TITLE
BlocksMissions dupe number with place/break

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#978]
### Minecraft's Version

1.18.1

### Plugin's Version

b539

### Describe the bug

Hello, when i set BlocksMissions to break i can place block and break block after to increase the number. Same with placement. Can you add a protection about that ? Maybe with going to negative number when we break same block ?

### To Reproduce

Add block break mission and place block and break it.

**Comment by OmerBenGera** [comment]
Add `only-natural-block` and set it to true for breaking blocks. About placement of blocks, set `blocks-replace` to false.
I recommend reading the wiki before posting bug reports:
https://wiki.bg-software.com/superiorskyblock/overview/missions/blocksmissions

**Comment by nivcoo** [comment]
I was thinking block-replace was for crops for exemple when server replace the same block, thx
