### ISSUE TITLE
Island minecart limit message

### ISSUE THREAD

**Issue by Trinchezito** [BG-Software-LLC/SuperiorSkyblock2#985]
### Minecraft's Version

1.18.2

### Plugin's Version

latest

### Describe the bug

when i reach the limit with the minecarts, it doesn't display a message in the chat saying i reached the limit like hoppers block limit do.  Maybe is something to do with block and entity type? 

### To Reproduce

reach the limit on minecarts entity limit.

**Comment by OmerBenGera** [comment]
Entity limits do not give messages to players when they are reached.
