### ISSUE TITLE
Bank interest charge even if bank limit is reached

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#986]
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b537

### Describe the bug

Bank interest charge even if bank limit is reached

### To Reproduce

-

**Comment by OmerBenGera** [comment]
I am closing this.
If it still occurs, lmk

**Comment by OmerBenGera** [comment]
> @OmerBenGera interest dont charge at all

Open a new issue then, as this is not related to this issue
