### ISSUE TITLE
Location placeholders don't work

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#988]
### Minecraft's Version

Latest Purpur 1.17.1

### Plugin's Version

Latest (d543)

### Describe the bug

Placeholders `%superior_location_island_...%` don't work. Any error in console isn't displayed and placeholder returns empty value. I used `/papi parse me <placeholder>` for testing. And yes, I was on an island.

### To Reproduce

Try using `%superior_location_island_...%` placeholders

**Comment by OmerBenGera** [comment]
It seems to work fine for me.
I was standing inside an island, ran `/papi parse me %superior_island_location_worth%` and received -1,000

**Comment by Ynfuien** [comment]
Ah, `island_location` not `location_island`. Yes, that works.

Then in wiki is incorrect information about it
![image](https://user-images.githubusercontent.com/88110072/157840072-cc2d228c-8d4f-47ee-b0ca-526f76875ddc.png)

**Comment by OmerBenGera** [comment]
> Ah, `island_location` not `location_island`. Yes, that works.
> 
> Then in wiki is incorrect information about it ![image](https://user-images.githubusercontent.com/88110072/157840072-cc2d228c-8d4f-47ee-b0ca-526f76875ddc.png)

You are right, gonna fix it right now.
