### ISSUE TITLE
Members and Visitors Menu not working

### ISSUE THREAD

**Issue by granpacho** [BG-Software-LLC/SuperiorSkyblock2#989]
### Minecraft's Version

Paper-402 (1.17.1) 

### Plugin's Version

SuperiorSkyblock2 1.8.4.535

### Describe the bug

The members and visitors menus are not working and there are no error messages. 

### To Reproduce

Not sure. 

### Additional Information

Members Menu: https://pastebin.com/hxaUtiZZ
Visitors Menu: https://pastebin.com/28rSkwQA

**Comment by Ynfuien** [comment]
Try using the latest dev build

**Comment by OmerBenGera** [comment]
What does not work exactly?
If you run `/is members` nothing happens?

**Comment by granpacho** [comment]
When I run /is visitors and /is members it takes me just to the main control panel menu.

**Comment by OmerBenGera** [comment]
> When I run /is visitors and /is members it takes me just to the main control panel menu.

Mind taking a video of the issue, as it works fine for me.

**Comment by granpacho** [comment]
https://gyazo.com/bffb5322ec119c9f4df0f325c1fa92f0

**Comment by OmerBenGera** [comment]
Ah, I think I know what the issue is.
Use latest dev build, let me know if it works for you.

**Comment by granpacho** [comment]
Works now with latest dev build. Thanks
