### ISSUE TITLE
Leash can be untied without permission

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#990]
### Minecraft's Version

Latest Purpur 1.17.1

### Plugin's Version

Latest (d543)

### Describe the bug

Any player can untide leash from eg. fence. Yes, island had LEASH permission denied for guests, I used default configuration. Leash perm only works for using lead on animals but doesn't work for tying/untying it from/to fences.

### To Reproduce

Untide leash from fence.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
