### ISSUE TITLE
Nether/end island home isn't fixed when it is set above air

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#991]
### Minecraft's Version

Latest Purpur 1.17.1

### Plugin's Version

Latest (d545)

### Describe the bug

As in title, home of nether/end island is not fixed when its location doesn't have any blocks under. So when not very smart players destroy blocks on their nether/end island and then they teleport to it, they are falling into the void.

### To Reproduce

- Destroy blocks under home location of nether/end island
- Teleport to it
- Die into the void

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
