### ISSUE TITLE
Startup error in 1.18.2

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#993]
### Minecraft's Version

1.18.2

### Plugin's Version

b547

### Describe the bug

Hello, the plugin works correctly in 1.18.1 but with 1.18.2 i've this issue : https://www.toptal.com/developers/hastebin/umumoxibax.csharp

### To Reproduce

Use the plugin in 1.18.2

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)
