### ISSUE TITLE
Safe teleportation isn't working properly

### ISSUE THREAD

**Issue by Ynfuien** [BG-Software-LLC/SuperiorSkyblock2#998]
### Minecraft's Version

Latest Purpur 1.17.1

### Plugin's Version

Latest (d557)

### Describe the bug

Safe teleportation can't handle slabs, glass and maybe other blocks. Plugin says that location is unsafe

https://youtu.be/a4aMSP7gFGg

### To Reproduce

- Set warp on glass or slab
- Try teleport to setted warp

**Comment by OmerBenGera** [comment]
I changed it so it doesnt accept slabs and fences, as you can easily get glitched through them.
About glass blocks, I will look into that.

**Comment by Ynfuien** [comment]
This change is a bit annoying for my players, because they have built a lot of platforms out of slabs and now they can't teleport to warps/homes setted on them. Can you change it back to what it was or maybe add an option to the config about this?

**Comment by OmerBenGera** [comment]
> This change is a bit annoying for my players, because they have built a lot of platforms out of slabs and now they can't teleport to warps/homes setted on them. Can you change it back to what it was or maybe add an option to the config about this?

I will look into it

**Comment by OmerBenGera** [comment]
I added the ability to configure the list of blocks that are consider "safe".
Now you can configure it however you want it to be :)

You can find it inside a new file called "safe_blocks.yml"
