### ISSUE TITLE
Is upgrade command is not working

### ISSUE THREAD

**Issue by granpacho** [BG-Software-LLC/SuperiorSkyblock2#999]
### Minecraft's Version

1.17.1 Paper-402

### Plugin's Version

Superior Skyblock: 1.8.4.552

### Describe the bug

/is upgrade command is not working no error in console on startup or when command is issued 

### To Reproduce

Not sure

### Additional Information

I tried looking for the issue but cannot find it. 

Upgrade Config: https://pastebin.com/ALSbHfQt
Upgrade GUI: https://pastebin.com/9eJrihF6

**Comment by OmerBenGera** [comment]
I think its because you have all the upgrade types disabled. Try enabling one of them, check if it fixes the issue
